SSAnne_2F_Room5_Frlg_MapScripts::
	.byte 0

SSAnne_2F_Room5_EventScript_Gentleman::
	msgbox SSAnne_2F_Room5_Text_HaveYouGoneToSafariZone, MSGBOX_NPC
	end

SSAnne_2F_Room5_EventScript_LittleBoy::
	msgbox SSAnne_2F_Room5_Text_WeThinkSafariZoneIsAwesome, MSGBOX_NPC
	end

SSAnne_2F_Room5_Text_HaveYouGoneToSafariZone::
	.string "Sei stato alla ZONA SAFARI\n"
	.string "di FUCHSIA CITY?\p"
	.string "Ci sono molti POKéMON\n"
	.string "rari.$"

SSAnne_2F_Room5_Text_WeThinkSafariZoneIsAwesome::
	.string "Io e il mio papà pensiamo che la\n"
	.string "ZONA SAFARI sia fantastica!\l"
	.string "Vorrei che ci tornassimo.$"

