SafariZone_North_Frlg_MapScripts::
	.byte 0

SafariZone_North_EventScript_RestHouseSign::
	msgbox SafariZone_North_Text_RestHouse, MSGBOX_SIGN
	end

SafariZone_North_EventScript_TrainerTips1::
	msgbox SafariZone_North_Text_SecretHouseStillAhead, MSGBOX_SIGN
	end

SafariZone_North_EventScript_AreaSign::
	msgbox SafariZone_North_Text_Area2, MSGBOX_SIGN
	end

SafariZone_North_EventScript_TrainerTips2::
	msgbox SafariZone_North_Text_ZigzagThroughTallGrass, MSGBOX_SIGN
	end

SafariZone_North_EventScript_TrainerTips3::
	msgbox SafariZone_North_Text_WinFreeHMFindSecretHouse, MSGBOX_SIGN
	end

SafariZone_North_Text_RestHouse::
	.string "CASA RIPOSO$"

SafariZone_North_Text_SecretHouseStillAhead::
	.string "CONSIGLI\p"
	.string "La CASA SEGRETA è ancora avanti.$"

SafariZone_North_Text_Area2::
	.string "ZONA 2$"

SafariZone_North_Text_ZigzagThroughTallGrass::
	.string "CONSIGLI\p"
	.string "I POKéMON si nascondono nell'erba alta.\p"
	.string "Zigzaga tra l'erba per\n"
	.string "stanarli.$"

SafariZone_North_Text_WinFreeHMFindSecretHouse::
	.string "CONSIGLI\p"
	.string "Vinci una MN gratis trovando\n"
	.string "la CASA SEGRETA.$"

