LavenderTown_SoulHouse_hns_MapScripts::
	.byte 0

LavenderTownSoulHouse_EventScript_MrFuji::
	msgbox MrFuji_Text_Main, MSGBOX_NPC
	end
LavenderTownSoulHouse_EventScript_Lass::
	msgbox SoulHouse_Text_Lass, MSGBOX_NPC
	end
LavenderTownSoulHouse_EventScript_Teacher::
	msgbox SoulHouse_Text_Teacher, MSGBOX_NPC
	end
LavenderTownSoulHouse_EventScript_Granny::
	msgbox SoulHouse_Text_Granny, MSGBOX_NPC
	end

MrFuji_Text_Main:
	.string "SIG. FUJI: Benvenuto.\p"
	.string "Hmm… Sembra che tu stia allevando\n"
	.string "i tuoi POKéMON con gentilezza\l"
	.string "e amore.\p"
	.string "Chi ama i POKéMON viene qui a\n"
	.string "rendere omaggio ai POKéMON\l"
	.string "scomparsi.\p"
	.string "Offri le tue condoglianze per le\n"
	.string "anime dei POKéMON scomparsi.\p"
	.string "Sono certo che ne saranno\n"
	.string "felici.$"

SoulHouse_Text_Teacher:
	.string "Ci sono altre tombe di POKéMON\n"
	.string "qui, credo.\p"
	.string "Ci sono molte stanze dove può\n"
	.string "entrare solo il SIG. FUJI.$"

SoulHouse_Text_Lass:
	.string "Sono venuta con la mamma a\n"
	.string "visitare le tombe…$"

SoulHouse_Text_Granny:
	.string "I POKéMON che vivevano con me…\p"
	.string "Li amavo come\n"
	.string "nipoti…$"
