BattleFrontier_Lounge8_MapScripts::
	.byte 0

BattleFrontier_Lounge8_EventScript_Man::
	msgbox BattleFrontier_Lounge8_Text_WhatATrainerNeeds, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_Woman::
	msgbox BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_NinjaBoy::
	msgbox BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling, MSGBOX_NPC
	end

BattleFrontier_Lounge8_Text_WhatATrainerNeeds:
	.string "Che serve a un ALLENATORE…\p"
	.string "Sapienza…\n"
	.string "Strategia…\l"
	.string "Fortuna…\l"
	.string "Dentistretti…\l"
	.string "Fatuanima…\l"
	.string "Ardimento…\l"
	.string "E abilità…\p"
	.string "Beh, io sono fornito per tutto!\n"
	.string "Sarò inarrestabile in ogni struttura!\p"
	.string "Eh? I POKéMON?\n"
	.string "Cosa sarebbero?$"

BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains:
	.string "Conosci gli ASSI del\n"
	.string "CONFINI?\p"
	.string "Sono i sette ALLENATORI speciali\n"
	.string "che SCOTT chiama così e che\l"
	.string "gestiscono le sette strutture.$"

BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling:
	.string "Alla TORRE LOTTA una ragazza più\n"
	.string "grande mi ha detto che ho tanto\l"
	.string "talento in battaglia!\p"
	.string "A me piacciono di più i CONCORSI POKéMON!\p"
	.string "Ma ai CONCORSI non sono brava!\p"
	.string "Visto che avere talento e\n"
	.string "piacere non sono la stessa cosa.$"

