SaffronCity_Mart_hns_MapScripts::
	.byte 0

SafronMart_EventScript_CooltrainerM::
	msgbox SaffronMart_Text_CooltrainerM, MSGBOX_NPC
	end
SafronMart_EventScript_CooltrainerF::
	msgbox SaffronMart_Text_CooltrainerF, MSGBOX_NPC
	end
SaffronMart_Text_CooltrainerM:
	.string "C'è una grande TORRE RADIO a\n"
	.string "LAVANDONIA.$"

SaffronMart_Text_CooltrainerF:
	.string "Voglio diventare più forte, ma\n"
	.string "non sono ancora brava…\p"
	.string "Mi mostri come si fa, qualche volta?$"
