SootopolisCity_House5_MapScripts::
	.byte 0

SootopolisCity_House5_EventScript_Maniac::
	msgbox SootopolisCity_House5_Text_SootopolisMtPyreConnection, MSGBOX_NPC
	end

SootopolisCity_House5_EventScript_Girl::
	msgbox SootopolisCity_House5_Text_BrotherUsedToStudySea, MSGBOX_NPC
	end

SootopolisCity_House5_Text_SootopolisMtPyreConnection:
	.string "Sembra esserci un legame\n"
	.string "tra SOOTOPOLIS e MT. PYRE.\p"
	.string "Io e i miei amici ci abbiamo fatto\n"
	.string "ricerca, nel laboratorio dove lavoravo.$"

SootopolisCity_House5_Text_BrotherUsedToStudySea:
	.string "Mio fratello maggiore studiava il mare.$"

