SevenIsland_TanobyRuins_Frlg_MapScripts::
	.byte 0

SevenIsland_TanobyRuins_Text_BrandonIntro::
	.string "Sai qualcosa di questa\n"
	.string "camera di pietra?$"

SevenIsland_TanobyRuins_Text_BrandonDefeat::
	.string "Non era necessario.\n"
	.string "Potevi essere più gentile.$"

SevenIsland_TanobyRuins_Text_BrandonPostBattle::
	.string "Le ROVINE TANOBY risalgono ad\n"
	.string "almeno 1500 anni fa.\p"
	.string "Ma resta un mistero fitto\n"
	.string "il motivo della loro costruzione.$"

SevenIsland_TanobyRuins_Text_BenjaminIntro::
	.string "Si dice che qui dentro dorma\n"
	.string "un POKéMON magico.$"

SevenIsland_TanobyRuins_Text_BenjaminDefeat::
	.string "Non sono granché in battaglia.$"

SevenIsland_TanobyRuins_Text_BenjaminPostBattle::
	.string "Ho sentito che ci sono altre rovine\n"
	.string "come questa.\p"
	.string "Forse sono i luoghi di riposo\n"
	.string "di altri POKéMON magici?$"

SevenIsland_TanobyRuins_Text_EdnaIntro::
	.string "CLIFFORD mi insegna a\n"
	.string "dipingere.$"

SevenIsland_TanobyRuins_Text_EdnaDefeat::
	.string "Potremmo metterci nei guai\n"
	.string "facendo rumore qui.$"

SevenIsland_TanobyRuins_Text_EdnaPostBattle::
	.string "Ho detto che volevo dipingere un\n"
	.string "edificio antico.\p"
	.string "Così CLIFFORD mi ha portata qui.$"

SevenIsland_TanobyRuins_Text_CliffordIntro::
	.string "Oggi, oltre alla lezione,\n"
	.string "siamo venuti a vedere la camera.$"

SevenIsland_TanobyRuins_Text_CliffordDefeat::
	.string "Perbacco, straordinario.$"

SevenIsland_TanobyRuins_Text_CliffordPostBattle::
	.string "Ah, quindi studi i POKéMON\n"
	.string "per conto tuo…\p"
	.string "Sì, sei davvero una persona\n"
	.string "straordinaria, altroché.$"
