GoldenrodCity_hns_MapScripts::
	.byte 0

GoldenrodCity_EventScript_Trigger:: @flagheap
	call_if_unset FLAG_SHOWN_ELM_TOGEPI, GoldenrodCity_Elm_Togepi_Call
	setflag FLAG_VISITED_GOLDENROD_CITY
	setflag FLAG_HIDE_GOLDENROD_ROCKETS
	setflag FLAG_HIDE_GOLDENROD_BILL
	setflag FLAG_HIDE_GOLDENROD_UNDERGROUND_KIMONO
	setflag FLAG_HIDE_GOLDENROD_UNDERGROUND_SILVER
	setflag FLAG_HIDE_ROCKET_GOLDENROD_RADIOTOWER_1
	setflag FLAG_HIDE_GOLDENROD_RADIOTOWER_PETREL
	setflag FLAG_HIDE_GOLDENROD_RADIOTOWER_DIRECTOR_2
	
	clearflag FLAG_HIDE_GOLDENROD_BEAUTY
	clearflag FLAG_HIDE_GOLDENROD_ROCKET_SCOUT
	clearflag FLAG_HIDE_GOLDENROD_NPCS
	clearflag FLAG_GOT_RETURN
	clearflag FLAG_GOT_FRUSTRATION
	clearflag FLAG_RECEIVED_BIKE
	clearflag FLAG_RECEIVED_SQUIRTBOTTLE
	clearflag FLAG_GOT_EEVEE
	clearflag FLAG_SYS_PC_BILL
	clearflag FLAG_RETURNED_MACHINE_PART
	clearflag FLAG_UNLOCKED_GOLDENROD_UNDERGROUND_DOOR
	clearflag FLAG_GOLDENROD_MACHOKE_1
	clearflag FLAG_GOLDENROD_MACHOKE_2
	clearflag FLAG_GOLDENROD_MACHOKE_3
	clearflag FLAG_COMPLETED_SWITCHES
	clearflag FLAG_ENABLE_RADIO
	clearflag FLAG_KANTO_RADIO_GOT
	clearflag FLAG_GOLDENROD_NPC_TRADE_COMPLETED
	clearflag FLAG_GOT_SUNNY_DAY
	clearflag FLAG_HIDE_RADIOTOWER_GATE
	clearflag FLAG_HIDE_GOLDENROD_RADIOTOWER_DIRECTOR
	clearflag FLAG_GOT_MARY_BRIGHT_POWDER
	clearflag FLAG_GOT_QUICK_CLAW
	clearflag FLAG_GOT_MAGNET

	setvar VAR_BUG_CONTEST_STATE, 0
	setvar VAR_KENYA, 0
	setvar VAR_LUGIA_OR_HOOH, 0
	setvar VAR_TRAIN, 0
	setvar VAR_ELEVATOR, 0
	setvar VAR_GOLDENROD_CITY_STATE, 1
	release
	end

GoldenrodCity_Trigger_Music::
	goto_if_lt VAR_GOLDENROD_CITY_STATE, 6, GoldenrodCity_Trigger_MusicNotYet
	goto_if_ge VAR_GOLDENROD_CITY_STATE, 11, GoldenrodCity_Trigger_MusicNotYet
	fadenewbgm MUS_HG_ROCKET_TAKEOVER
	special ShowMapNamePopup
	setvar VAR_TEMP_0, 1 
	end

GoldenrodCity_Trigger_Music2::
	goto_if_lt VAR_GOLDENROD_CITY_STATE, 6, GoldenrodCity_Trigger_MusicNotYet
	goto_if_ge VAR_GOLDENROD_CITY_STATE, 11, GoldenrodCity_Trigger_MusicNotYet
	fadedefaultbgm
	special ShowMapNamePopup
	setvar VAR_TEMP_0, 1
	end

GoldenrodCity_Trigger_MusicNotYet::
	special ShowMapNamePopup
	setvar VAR_TEMP_0, 1
	end

GoldenrodCity_Elm_Togepi_Call::
	lock
	setspeaker GoldenrodCity_Text_ElmName
	pokenavcall GoldenrodCity_Text_ElmCall
	waitmessage
	delay 30
	release
	return

GoldenrodCity_EventScript_PokefanM::
	lock
	faceplayer
	msgbox GoldenrodCity_Text_PokefanM, MSGBOX_DEFAULT
	closemessage
	release
	end

GoldenrodCity_EventScript_Youngster::
	msgbox GoldenrodCity_Text_Youngster1, MSGBOX_NPC
	end

GoldenrodCity_EventScript_Youngster2::
	msgbox GoldenrodCity_Text_Youngster2, MSGBOX_NPC
	end

GoldenrodCity_EventScript_CooltrainerF::
	lock
	faceplayer
	goto_if_set FLAG_HIDE_GOLDENROD_ROCKET_SCOUT, GoldenrodCity_EventScript_CooltrainerFCleared
	msgbox GoldenrodCity_Text_CooltrainerF1, MSGBOX_DEFAULT
	closemessage
	release
	end

GoldenrodCity_EventScript_CooltrainerFCleared::
	msgbox GoldenrodCity_Text_CooltrainerF1_Cleared, MSGBOX_NPC
	end

GoldenrodCity_EventScript_Lass::
	lock
	faceplayer
	msgbox GoldenrodCity_Text_Lass, MSGBOX_DEFAULT
	closemessage
	release
	end

GoldenrodCity_EventScript_Gramps::
	lock
	faceplayer
	msgbox GoldenrodCity_Text_Gramps, MSGBOX_DEFAULT
	closemessage
	release
	end

GoldenrodCity_EventScript_NameRaterSign::
	msgbox GoldenrodCity_Text_NameRaterSign, MSGBOX_SIGN
	end

GoldenrodCity_EventScript_RocketScout::
	lock
	msgbox GoldenrodCity_Text_RocketScout1, MSGBOX_DEFAULT
	closemessage
	PLAYSE SE_PIN
	applymovement LOCALID_GOLDENROD_ROCKET_SCOUT, Common_Movement_ExclamationMark
	delay 55
	waitmovement LOCALID_GOLDENROD_ROCKET_SCOUT
	faceplayer
	msgbox GoldenrodCity_Text_RocketScout2, MSGBOX_DEFAULT
	closemessage
	turnobject LOCALID_GOLDENROD_ROCKET_SCOUT, DIR_NORTH
	release
	end

GoldenrodCity_EventScript_Rocket1::
	lock
	faceplayer
	msgbox GoldenrodCity_Text_Rocket1, MSGBOX_DEFAULT
	closemessage
	release
	end

GoldenrodCity_EventScript_Rocket2::
	lock
	faceplayer
	msgbox GoldenrodCity_Text_Rocket2, MSGBOX_DEFAULT
	closemessage
	release
	end

GoldenrodCity_EventScript_Rocket3::
	lock
	faceplayer
	msgbox GoldenrodCity_Text_Rocket3, MSGBOX_DEFAULT
	closemessage
	release
	end

GoldenrodCity_EventScript_Rocket4::
	lock
	faceplayer
	msgbox GoldenrodCity_Text_Rocket4, MSGBOX_DEFAULT
	closemessage
	release
	end

GoldenrodCity_EventScript_Rocket5::
	lock
	faceplayer
	msgbox GoldenrodCity_Text_Rocket5, MSGBOX_DEFAULT
	closemessage
	release
	end

GoldenrodCity_EventScript_Rocket6::
	lock
	faceplayer
	msgbox GoldenrodCity_Text_Rocket6, MSGBOX_DEFAULT
	closemessage
	release
	end

GoldenrodCity_EventScript_Woman::
	lock
	faceplayer
	msgbox GoldenrodCity_Text_Woman, MSGBOX_DEFAULT
	closemessage
	release
	end

GoldenrodCity_EventScript_Hiker::
	lock
	faceplayer
	goto_if_set FLAG_DAY_POKEMON, GoldenrodCity_EventScript_Hiker2
	msgbox GoldenrodCity_Text_HikerDay, MSGBOX_DEFAULT
	closemessage
	release
	end

GoldenrodCity_EventScript_Hiker2::
	msgbox GoldenrodCity_Text_HikerNight, MSGBOX_DEFAULT
	closemessage
	release
	end

GoldenrodCity_EventScript_Snubbull::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_SNUBBULL, CRY_MODE_NORMAL
	msgbox GoldenrodCity_Text_Snubbull, MSGBOX_DEFAULT
	waitmoncry
	release
	end

GoldenrodCity_EventScript_Mime::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_MR_MIME, CRY_MODE_NORMAL
	msgbox GoldenrodCity_Text_MrMime, MSGBOX_DEFAULT
	waitmoncry
	release
	end

GoldenrodCity_EventScript_SignUnderground::
	lock
	msgbox GoldenrodCity_Text_UndergroundSouthSign, MSGBOX_SIGN
	closemessage
	release
	end
GoldenrodCity_EventScript_SignDept::
	lock
	msgbox GoldenrodCity_Text_DeptStoreSign, MSGBOX_SIGN
	closemessage
	release
	end
GoldenrodCity_EventScript_SignBike::
	lock
	msgbox GoldenrodCity_Text_BikeShopSign, MSGBOX_SIGN
	closemessage
	release
	end
GoldenrodCity_EventScript_SignTrain::
	lock
	msgbox GoldenrodCity_Text_StationSign, MSGBOX_SIGN
	closemessage
	release
	end
GoldenrodCity_EventScript_SignGym::
	lock
	msgbox GoldenrodCity_Text_GymSign, MSGBOX_SIGN
	closemessage
	release
	end
GoldenrodCity_EventScript_SignFlower::
	lock
	msgbox GoldenrodCity_Text_FlowerShopSign, MSGBOX_SIGN
	closemessage
	release
	end
GoldenrodCity_EventScript_SignRadio::
	lock
	msgbox GoldenrodCity_Text_RadioTowerSign, MSGBOX_SIGN
	closemessage
	release
	end
GoldenrodCity_EventScript_SignGameCorner::
	lock
	msgbox GoldenrodCity_Text_GameCornerSign, MSGBOX_SIGN
	closemessage
	release
	end

GoldenrodCity_EventScript_Beauty::
	lock
	faceplayer
	msgbox GoldenrodCity_Text_Beauty, MSGBOX_DEFAULT
	closemessage
	release
	end

GoldenrodCity_Text_Beauty:
	.string "Questa è la PALESTRA di GOLDENROD!\p"
	.string "La nostra capo WHITNEY non c'è\n"
	.string "ora. Forse è alla\l"
	.string "TORRE RADIO.$"

GoldenrodCity_Text_Woman:
	.string "Mi allenavo nella PALESTRA di CHIARA,\n"
	.string "ma il suo piagnucolare mi dava\l"
	.string "mal di testa.$"

GoldenrodCity_Text_HikerDay:
	.string "Quando sono entrato in SALA GIOCHI\n"
	.string "era notte... Quanto ci sono\l"
	.string "rimasto?!$"

GoldenrodCity_Text_HikerNight:
	.string "Quando sono entrato in SALA GIOCHI\n"
	.string "era giorno... Quanto ci sono\l"
	.string "rimasto?!$"

GoldenrodCity_Text_Snubbull:
	.string "SNUBBULL: SNUUUBUUUULL!$"

GoldenrodCity_Text_MrMime:
	.string "............................$"

GoldenrodCity_Text_ElmName:
	.string "PROF.ELM$"

GoldenrodCity_Text_ElmCall:
	.string "PROF.ELM: Ciao, {PLAYER}?\n"
	.string "L'UOVO si è schiuso?\p"
	.string "Quando si schiude, portalo\n"
	.string "in laboratorio! Devo\l"
	.string "vederlo!$"

GoldenrodCity_Text_PokefanM:
	.string "Hanno costruito la nuova TORRE RADIO\n"
	.string "al posto di quella vecchia.$"

GoldenrodCity_Text_Youngster1:
	.string "So che c'è un NEGOZIO DI BICI nuovo,\n"
	.string "ma non lo trovo da nessuna parte.$"

GoldenrodCity_Text_CooltrainerF1:
	.string "Quell'uomo in nero è vestito\n"
	.string "come un membro del TEAM ROCKET?\p"
	.string "Che sciocco!$"

GoldenrodCity_Text_CooltrainerF1_Cleared:
	.string "Quell'uomo in nero era davvero\n"
	.string "del TEAM ROCKET? Non ci credo!$"

GoldenrodCity_Text_CooltrainerF2:
	.string "La TORRE RADIO di GOLDENROD CITY\n"
	.string "è un vero simbolo.\p"
	.string "Ora fanno una promozione.\p"
	.string "Ti daranno una RADIO nuova\n"
	.string "se passi il loro quiz.$"

GoldenrodCity_Text_CooltrainerF2_GotCard:
	.string "Oh, il tuo POKéGEAR funziona già\n"
	.string "come radio!$"

GoldenrodCity_Text_Youngster2:
	.string "E-e-e-e…\p"
	.string "Mi sono cacciato nei guai giocando\n"
	.string "nel seminterrato del GRANDE MAGAZZINO.$"

GoldenrodCity_Text_Lass:
	.string "Quell'uomo dentro valuta i\n"
	.string "soprannomi dei POKéMON.\p"
	.string "Può anche cambiarli.$"

GoldenrodCity_Text_Gramps:
	.string "Uff! Questa città è così grande\n"
	.string "che non trovo nulla.$"

GoldenrodCity_Text_RocketScout1:
	.string "Ecco la TORRE RADIO…$"

GoldenrodCity_Text_RocketScout2:
	.string "Che vuoi, pulce?\n"
	.string "Sgombera!$"

GoldenrodCity_Text_Rocket1:
	.string "Togliti di mezzo!\n"
	.string "Sparisci, moccioso!$"

GoldenrodCity_Text_Rocket2:
	.string "Prendere la TORRE RADIO…\p"
	.string "Cosa? Non sono affari tuoi!$"

GoldenrodCity_Text_Rocket3:
	.string "I POKéMON? Sono solo arnesi\n"
	.string "per farci soldi!$"

GoldenrodCity_Text_Rocket4:
	.string "Il nostro sogno è ormai vicino…\p"
	.string "È stata dura, ma ce l'abbiamo fatta…$"

GoldenrodCity_Text_Rocket5:
	.string "Ehi, moccioso! Qui non puoi stare!\n"
	.string "Vai via!$"

GoldenrodCity_Text_Rocket6:
	.string "Vieni a provare il terrore del\n"
	.string "TEAM ROCKET!$"

GoldenrodCity_Text_StationSign:
	.string "STAZIONE DI FIORLI$"

GoldenrodCity_Text_RadioTowerSign:
	.string "TORRE RADIO DI FIORLI$"

GoldenrodCity_Text_DeptStoreSign:
	.string "Tutta la scelta di articoli POKéMON!\p"
	.string "CENTRO COMMERCIALE di GOLDENROD$"

GoldenrodCity_Text_GymSign:
	.string "PALESTRA POKéMON di GOLDENROD\n"
	.string "CAPO: WHITNEY\p"
	.string "La ragazza bellissima!$"

GoldenrodCity_Text_CitySign:
	.string "GOLDENROD CITY\p"
	.string "La città festosa dal fascino ricco$"

GoldenrodCity_Text_BikeShopSign:
	.string "Il mondo è una pista ciclabile!\n"
	.string "NEGOZIO DI BICICLETTE$"

GoldenrodCity_Text_GameCornerSign:
	.string "Il tuo parco giochi!\p"
	.string "SALA GIOCHI di GOLDENROD CITY$"

GoldenrodCity_Text_NameRaterSign:
	.string "VALUTATORE DI NOMI\p"
	.string "Fai valutare i soprannomi dei POKéMON$"

GoldenrodCity_Text_UndergroundNorthSign:
	.string "INGRESSO SOTTERRANEO$"

GoldenrodCity_Text_UndergroundSouthSign:
	.string "INGRESSO SOTTERRANEO$"


GoldenrodCity_Text_FlowerShopSign:
	.string "FIORITO NEGOZIO DI FIORI$"

GoldenrodCity_Text_MoveTutorAsk:
	.string "Posso insegnare ai tuoi POKéMON\n"
	.string "mosse incredibili!\p"
	.string "Ne insegno una?$"

GoldenrodCity_Text_MoveTutorCost:
	.string "Costa 1000 gettoni.\n"
	.string "Va bene?$"

GoldenrodCity_Text_MoveTutorDecline:
	.string "Oh… Ma sono mosse ottime!$"

GoldenrodCity_Text_MoveTutorWhich:
	.string "Wahahah! Non te ne pentirai!\p"
	.string "Quale mossa insegno?$"

GoldenrodCity_Text_MoveTutorNoCash:
	.string "Peccato. Devo prendere\n"
	.string "dei soldi da casa…$"

GoldenrodCity_Text_MoveTutorUnderstand:
	.string "Se capisci questa mossa,\n"
	.string "sei un vero allenatore.$"

GoldenrodCity_Text_MoveTutorFarewell:
	.string "Wahahah! Ciao, ragazzo!$"

GoldenrodCity_Text_MoveTutorBut:
	.string "M-ma…$"

GoldenrodCity_Text_MoveTutorNotEnoughCoins:
	.string "…Non hai abbastanza gettoni…$"
