OneIsland_House1_Frlg_MapScripts::
	.byte 0

OneIsland_House1_EventScript_OldMan::
	msgbox OneIsland_House1_Text_GazeUponVolcanoOnSunnyDays, MSGBOX_NPC
	end

OneIsland_House1_EventScript_OldWoman::
	msgbox OneIsland_House1_Text_LastTimeMtEmberErupted, MSGBOX_NPC
	end

OneIsland_House1_Text_GazeUponVolcanoOnSunnyDays::
	.string "Nei giorni di sole esco e guardo\n"
	.string "il vulcano.\p"
	.string "È la mia routine quotidiana.$"

OneIsland_House1_Text_LastTimeMtEmberErupted::
	.string "Fammi pensare... Quand'è stata l'ultima\n"
	.string "volta che il MONTE EMBER eruttò?$"

