SixIsland_WaterPath_Frlg_MapScripts::
	.byte 0

SixIsland_WaterPath_EventScript_HornWantedSign::
	msgbox SixIsland_WaterPath_Text_WantedUltimateHorn, MSGBOX_SIGN
	end

SixIsland_WaterPath_EventScript_RouteSign::
	msgbox SixIsland_WaterPath_Text_RouteSign, MSGBOX_SIGN
	end

SixIsland_WaterPath_Text_RoseIntro::
	.string "Mi sono lasciata guidare\n"
	.string "da una brezza piacevole.$"

SixIsland_WaterPath_Text_RoseDefeat::
	.string "Eh eh… sei così tenero quando\n"
	.string "ti impegni.$"

SixIsland_WaterPath_Text_RosePostBattle::
	.string "Vorrei andare nel bosco laggiù,\n"
	.string "ma…\p"
	.string "Ci sono molti POKéMON coleottero.\n"
	.string "Mi fanno un po' paura.$"

SixIsland_WaterPath_Text_EdwardIntro::
	.string "Mi alleno in segreto, così nessuno\n"
	.string "mi vede.$"

SixIsland_WaterPath_Text_EdwardDefeat::
	.string "Nessuno mi ha visto perdere, vero?$"

SixIsland_WaterPath_Text_EdwardPostBattle::
	.string "As a performer, I don't want people\n"
	.string "to know about the effort I put in.$"

SixIsland_WaterPath_Text_SamirIntro::
	.string "What, you're suggesting that you're\n"
	.string "sick of seeing SWIMMERS like me?\p"
	.string "Aww, don't be hatin'!$"

SixIsland_WaterPath_Text_SamirDefeat::
	.string "Oh, no, no, no.$"

SixIsland_WaterPath_Text_SamirPostBattle::
	.string "Non riesco a togliermi di dosso\n"
	.string "l'etichetta di NUOTATORE…$"

SixIsland_WaterPath_Text_DeniseIntro::
	.string "Il mio ragazzo è sempre impegnato,\n"
	.string "così nuoto da sola.$"

SixIsland_WaterPath_Text_DeniseDefeat::
	.string "Ohh, sapevo che sarebbe finita così!$"

SixIsland_WaterPath_Text_DenisePostBattle::
	.string "Quando non posso stare col mio ragazzo,\n"
	.string "sto in compagnia dei POKéMON\l"
	.string "che mi ha regalato.$"

SixIsland_WaterPath_Text_EarlIntro::
	.string "Dimmi, dove sono le montagne\n"
	.string "da queste parti?$"

SixIsland_WaterPath_Text_EarlDefeat::
	.string "Mi sono perso mentre\n"
	.string "lottavo!$"

SixIsland_WaterPath_Text_EarlPostBattle::
	.string "Non ci sono montagne qui\n"
	.string "in giro?$"

SixIsland_WaterPath_Text_MiuIntro::
	.string "MIU: Ciao, POKéMON!\n"
	.string "È ora di giocare!$"

SixIsland_WaterPath_Text_MiuDefeat::
	.string "MIU: Oh, no!\n"
	.string "Mamma!$"

SixIsland_WaterPath_Text_MiuPostBattle::
	.string "MIU: Quando perdiamo mi\n"
	.string "sento tanto triste…$"

SixIsland_WaterPath_Text_MiuNotEnoughMons::
	.string "MIU: MIA e io siamo GEMELLE.\n"
	.string "Vogliamo lottare insieme.$"

SixIsland_WaterPath_Text_MiaIntro::
	.string "MIA: Ciao, POKéMON!\n"
	.string "È ora di lottare!$"

SixIsland_WaterPath_Text_MiaDefeat::
	.string "MIA: Sei cattivo!\n"
	.string "Hai vinto, che rabbia!$"

SixIsland_WaterPath_Text_MiaPostBattle::
	.string "MIA: Ohh…\n"
	.string "Mi dispiace, POKéMON miei…$"

SixIsland_WaterPath_Text_MiaNotEnoughMons::
	.string "MIA: Oh, hai solo un\n"
	.string "POKéMON?\p"
	.string "Non ti senti solo?$"

SixIsland_WaterPath_Text_WantedUltimateHorn::
	.string "Cercasi!\n"
	.string "Il corno supremo!$"

SixIsland_WaterPath_Text_RouteSign::
	.string "PONTE ACQUA\n"
	.string "Porta alla VALLE DELLE ROVINE$"

