Route9_Frlg_MapScripts::
	.byte 0

Route9_EventScript_RouteSign::
	msgbox Route9_Text_RouteSign, MSGBOX_SIGN
	end

Route9_Text_AliciaIntro::
	.string "Hai dei POKéMON con te!\n"
	.string "Sei mio!$"

Route9_Text_AliciaDefeat::
	.string "Mi hai ingannata…$"

Route9_Text_AliciaPostBattle::
	.string "Il tunnel più avanti è buio\n"
	.string "pesto.\p"
	.string "Ti servirà FLASH per passare\n"
	.string "là dentro.$"

Route9_Text_ChrisIntro::
	.string "Chi sta passando con quei\n"
	.string "bei POKéMON?$"

Route9_Text_ChrisDefeat::
	.string "K.O. in un lampo!$"

Route9_Text_ChrisPostBattle::
	.string "Continua a camminare!$"

Route9_Text_DrewIntro::
	.string "Prendo il TUNNEL ROCCIOSO per\n"
	.string "andare a LAVANDONIA…$"

Route9_Text_DrewDefeat::
	.string "Non sono all'altezza…$"

Route9_Text_DrewPostBattle::
	.string "Vai anche tu al TUNNEL ROCCIOSO?$"

Route9_Text_CaitlinIntro::
	.string "Non osare trattarmi dall'alto in basso!$"

Route9_Text_CaitlinDefeat::
	.string "No!\n"
	.string "Sei troppo forte.$"

Route9_Text_CaitlinPostBattle::
	.string "Hai del talento.\n"
	.string "In bocca al lupo!$"

Route9_Text_JeremyIntro::
	.string "Bwahaha!\n"
	.string "Ottimo! Mi annoiavo, eh!$"

Route9_Text_JeremyDefeat::
	.string "Dammene ancora, eh!\p"
	.string "Oh, aspetta.\n"
	.string "Non ho più POKéMON!$"

Route9_Text_JeremyPostBattle::
	.string "Ci vuole fegato a sfidarmi\n"
	.string "così, eh?$"

Route9_Text_BriceIntro::
	.string "Ahahah!\n"
	.string "Ma sei un piccolo tutto pepe!$"

Route9_Text_BriceDefeat::
	.string "Che succede?$"

Route9_Text_BricePostBattle::
	.string "Ahahah!\n"
	.string "I ragazzini devono essere tosti!$"

Route9_Text_BrentIntro::
	.string "Mi alzavo presto ogni giorno per\n"
	.string "allevare i miei POKéMON dai bozzoli!$"

Route9_Text_BrentDefeat::
	.string "COSA?\p"
	.string "Che perdita di tempo!$"

Route9_Text_BrentPostBattle::
	.string "Devo raccogliere più che insetti\n"
	.string "per diventare più forte…$"

Route9_Text_AlanIntro::
	.string "Ahahahah!\n"
	.string "Fatti sotto!$"

Route9_Text_AlanDefeat::
	.string "Ahahahah!\n"
	.string "Mi hai battuto lealmente!$"

Route9_Text_AlanPostBattle::
	.string "Ahahahah!\n"
	.string "Noi ridiamo sempre, che caratterino!$"

Route9_Text_ConnerIntro::
	.string "Vai, miei super POKéMON COLEOTTERO!$"

Route9_Text_ConnerDefeat::
	.string "I miei insetti…$"

Route9_Text_ConnerPostBattle::
	.string "Se non ti piacciono i POKéMON\n"
	.string "COLEOTTERO, mi dai fastidio!$"

Route9_Text_RouteSign::
	.string "PERCORSO 9\n"
	.string "CERULEAN CITY - TUNNEL ROCCIOSO$"

