PewterCity_Mart_hns_MapScripts::
	.byte 0

PewterCity_Mart_EventScript_Youngster::
	msgbox PewterCity_Mart_Text_Youngster, MSGBOX_NPC
	end

PewterCity_Mart_EventScript_Nerd::
	msgbox PewterCity_Mart_Text_SuperNerd, MSGBOX_NPC
	end

PewterCity_Mart_Text_Youngster:
	.string "Ciao! Guarda il mio GYARADOS!\p"
	.string "L'ho allevato da un MAGIKARP. Non\n"
	.string "credo a quanto è diventato forte.$"

PewterCity_Mart_Text_SuperNerd:
	.string "C'era un vecchio strano che vendeva\n"
	.string "MAGIKARP.\p"
	.string "Diceva che i MAGIKARP del\n"
	.string "LAGO D'IRA erano eccellenti.$"

