Route21_South_Frlg_MapScripts::
	.byte 0

Route21_South_Text_JackIntro::
	.string "Ho preso i POKéMON in mare.$"

Route21_South_Text_JackDefeat::
	.string "Sub!\n"
	.string "Giù!!$"

Route21_South_Text_JackPostBattle::
	.string "Dove hai preso i tuoi POKéMON?$"

Route21_South_Text_JeromeIntro::
	.string "Ora sono in gara di triathlon.$"

Route21_South_Text_JeromeDefeat::
	.string "Ans…\n"
	.string "Ans… Ans…$"

Route21_South_Text_JeromePostBattle::
	.string "Sono a pezzi! Ma mi restano la\n"
	.string "gara in bici e la maratona!$"

Route21_South_Text_RolandIntro::
	.string "Ahh!\n"
	.string "Che sole e che vento!$"

Route21_South_Text_RolandDefeat::
	.string "Uff!\n"
	.string "Ho perso!$"

Route21_South_Text_RolandPostBattle::
	.string "Sono tutto bruciato dal sole!$"

Route21_South_Text_ClaudeIntro::
	.string "Ehi, non spaventare i pesci!$"

Route21_South_Text_ClaudeDefeat::
	.string "Scusa! Sono frustrato perché\n"
	.string "non prendo niente.$"

Route21_South_Text_ClaudePostBattle::
	.string "Cavoli, non ho preso niente.\n"
	.string "Che sia una piscina\l"
	.string "gigante o roba simile?$"

Route21_South_Text_NolanIntro::
	.string "Fammi compagnia finché abbocca.$"

Route21_South_Text_NolanDefeat::
	.string "Così ho passato il tempo.$"

Route21_South_Text_NolanPostBattle::
	.string "Ah, aspetta!\n"
	.string "Ha abboccato! Sì!$"

Route21_North_Text_LilIntro::
	.string "LIL: Eh? Una lotta?\n"
	.string "IAN, non puoi da solo?$"

Route21_North_Text_LilDefeat::
	.string "LIL: Visto?\n"
	.string "Abbiamo perso. Contento?$"

Route21_North_Text_LilPostBattle::
	.string "LIL: Sono stanca.\n"
	.string "Possiamo andare a casa?$"

Route21_North_Text_LilNotEnoughMons::
	.string "LIL: Eh? Una lotta?\n"
	.string "Da sola non ho voglia.\l"
	.string "Porta due POKéMON, ok?$"

Route21_North_Text_IanIntro::
	.string "IAN: Mia sorella non si allena\n"
	.string "abbastanza, così l'ho portata.$"

Route21_North_Text_IanDefeat::
	.string "IAN: Awww, Sorella!\n"
	.string "Datti una mossa!$"

Route21_North_Text_IanPostBattle::
	.string "IAN: Dai, sorella!\p"
	.string "Così non perdi\n"
	.string "peso!$"

Route21_North_Text_IanNotEnoughMons::
	.string "IAN: Vogliamo una lotta 2 contro 2.\n"
	.string "Puoi portare due POKéMON?$"
