SafariZone_West_Frlg_MapScripts::
	.byte 0

SafariZone_West_EventScript_RestHouseSign::
	msgbox SafariZone_West_Text_RestHouse, MSGBOX_SIGN
	end

SafariZone_West_EventScript_LostTeethNotice::
	msgbox SafariZone_West_Text_PleaseFindWardensLostTeeth, MSGBOX_SIGN
	end

SafariZone_West_EventScript_TrainerTips::
	msgbox SafariZone_West_Text_SearchForSecretHouse, MSGBOX_SIGN
	end

SafariZone_West_EventScript_AreaSign::
	msgbox SafariZone_West_Text_AreaSign, MSGBOX_SIGN
	end

SafariZone_West_Text_RestHouse::
	.string "CASA RIPOSO$"

SafariZone_West_Text_PleaseFindWardensLostTeeth::
	.string "AVVISO\p"
	.string "Chi trova i DENTI D'ORO perduti\n"
	.string "del GUARDIANO del SAFARI,\l"
	.string "sono qui intorno da qualche parte.\p"
	.string "Offerta ricompensa!\n"
	.string "Contatta: GUARDIANO$"

SafariZone_West_Text_SearchForSecretHouse::
	.string "CONSIGLI\p"
	.string "Campagna esplorazione!\n"
	.string "Alla ricerca della CASA SEGRETA!$"

SafariZone_West_Text_AreaSign::
	.string "ZONA 3\n"
	.string "EST: ZONA CENTRALE$"

