Gate_Route31_VioletCity_hns_MapScripts::
	.byte 0

Gate_Route31_VioletCity_EventScript_Policeman::
	lock
	faceplayer
	msgbox Gate_Route31_VioletCity_Text_Policeman, MSGBOX_DEFAULT
	closemessage
	release
	end

Gate_Route31_VioletCity_EventScript_CooltrainerF::
	lock
	faceplayer
	msgbox Gate_Route31_VioletCity_Text_CooltrainerF, MSGBOX_DEFAULT
	closemessage
	release
	end

Gate_Route31_VioletCity_Text_Policeman:
	.string "Ciao! Hai visto la\n"
	.string "TORRE SPROUT?$"

Gate_Route31_VioletCity_Text_CooltrainerF:
	.string "Ho visto un POKéMON\n"
	.string "carino.\p"
	.string "Sembrava PIKACHU!$"
