VermilionCity_Mart_hns_MapScripts::
	.byte 0

VermilionCity_Mart_EventScript_BirdMan::
	msgbox VermilionMart_Text_SuperNerd, MSGBOX_NPC
	end

VermilionCity_Mart_EventScript_Woman::
	msgbox VermilionMart_Text_Beauty, MSGBOX_NPC
	end

VermilionMart_Text_SuperNerd:
	.string "Il TEAM ROCKET non è più a\n"
	.string "KANTO.\p"
	.string "Solo questo mi rende felice.$"

VermilionMart_Text_Beauty:
	.string "Sto pensando di andare a fare spese\n"
	.string "a ZAFFERANOPOLI.$"
