SafariZone_West_RestHouse_Frlg_MapScripts::
	.byte 0

SafariZone_West_RestHouse_EventScript_Man::
	msgbox SafariZone_West_Text_BaitMakesMonStickAround, MSGBOX_NPC
	end

SafariZone_West_RestHouse_EventScript_Scientist::
	msgbox SafariZone_West_Text_RocksMakeMonRunButEasierCatch, MSGBOX_NPC
	end

SafariZone_West_RestHouse_EventScript_CooltrainerF::
	msgbox SafariZone_West_Text_HikedLotsDidntSeeMonIWanted, MSGBOX_NPC
	end

SafariZone_West_Text_KogaPatrolsSafariEverySoOften::
	.string "La ZONA SAFARI è enorme, non\n"
	.string "trovi?\p"
	.string "KOGA, CAPOPALESTRA di FUCSIAPOLI, \n"
	.string "patrolla il terreno ogni tanto.\p"
	.string "Grazie a lui, possiamo giocare qui\n"
	.string "sapendo di essere al sicuro.$"

SafariZone_West_Text_RocksMakeMonRunButEasierCatch::
	.string "Lanciare SASSI ai POKéMON può\n"
	.string "farli scappare, ma saranno\l"
	.string "più facili da catturare.$"

SafariZone_West_Text_BaitMakesMonStickAround::
	.string "Usare l'ESCA farà restare i POKéMON\n"
	.string "più a lungo se saranno\l"
	.string "impegnati a mangiare.$"

SafariZone_West_Text_HikedLotsDidntSeeMonIWanted::
	.string "Ho camminato molto, ma non ho visto\n"
	.string "i POKéMON che volevo.$"

