SevenIsland_SevaultCanyon_Frlg_MapScripts::
	.byte 0

SevenIsland_SevaultCanyon_EventScript_RouteSign::
	msgbox SevenIsland_SevaultCanyon_Text_RouteSign, MSGBOX_SIGN
	end

SevenIsland_SevaultCanyon_Text_CyndyIntro::
	.string "Sono in forma smagliante!$"

SevenIsland_SevaultCanyon_Text_CyndyDefeat::
	.string "Eh?\n"
	.string "Qualcosa non va…$"

SevenIsland_SevaultCanyon_Text_CyndyPostBattle::
	.string "Così come sono, forse la TORRE\n"
	.string "ALLENATORI può aspettare…$"

SevenIsland_SevaultCanyon_Text_EvanIntro::
	.string "It doesn't matter if you happen to\n"
	.string "have the strongest POKéMON…\p"
	.string "It doesn't mean a thing if you don't\n"
	.string "know how to use them properly!$"

SevenIsland_SevaultCanyon_Text_EvanDefeat::
	.string "Sei un maestro in questo.$"

SevenIsland_SevaultCanyon_Text_EvanPostBattle::
	.string "Ne vedi ogni tanto,\n"
	.string "ALLENATORI con POKéMON fortissimi\l"
	.string "che non sanno cosa fare.\p"
	.string "Prima di allenare i POKéMON,\n"
	.string "gli ALLENATORI devono crescere.$"

SevenIsland_SevaultCanyon_Text_JacksonIntro::
	.string "Proteggo l'ambiente.\n"
	.string "E la natura protegge me!$"

SevenIsland_SevaultCanyon_Text_JacksonDefeat::
	.string "Uao! Sei tosto!\n"
	.string "Mi fai da guardia del corpo?$"

SevenIsland_SevaultCanyon_Text_JacksonPostBattle::
	.string "Da lassù, tra le stelle, il nostro\n"
	.string "pianeta è una goccia d'acqua.\p"
	.string "Ma vogliamo proteggere quella\n"
	.string "goccia d'acqua per tutti.$"

SevenIsland_SevaultCanyon_Text_KatelynIntro::
	.string "Che scarpe sgargianti\n"
	.string "che hai.$"

SevenIsland_SevaultCanyon_Text_KatelynDefeat::
	.string "Sei un fenomeno, nonostante\n"
	.string "l'aria da bravo.$"

SevenIsland_SevaultCanyon_Text_KatelynPostBattle::
	.string "Tua mamma ti ha comprato quelle\n"
	.string "SCARPE DA GINNASTICA?\p"
	.string "Ti adora di certo.$"

SevenIsland_SevaultCanyon_Text_LeroyIntro::
	.string "Sembri forte.\n"
	.string "Lottiamo, ti prego!$"

SevenIsland_SevaultCanyon_Text_LeroyDefeat::
	.string "Lo sapevo!\n"
	.string "Sei tosto come pensavo!$"

SevenIsland_SevaultCanyon_Text_LeroyPostBattle::
	.string "Il tuo stile di lotta mi ha dato\n"
	.string "dati molto utili.\p"
	.string "Grazie mille!$"

SevenIsland_SevaultCanyon_Text_MichelleIntro::
	.string "Ho ricevuto la migliore\n"
	.string "istruzione per diventare forte.\p"
	.string "Non voglio perdere con nessuno!$"

SevenIsland_SevaultCanyon_Text_MichelleDefeat::
	.string "Grazie. Persa contro di te,\n"
	.string "mi sento libera.$"

SevenIsland_SevaultCanyon_Text_MichellePostBattle::
	.string "Per qualche motivo, mi infurio\n"
	.string "per un nonnulla.\p"
	.string "Mi calmerò respirando\n"
	.string "a fondo.$"

SevenIsland_SevaultCanyon_Text_LexIntro::
	.string "LEX: Mio caro NYA, insieme\n"
	.string "possiamo vincere!$"

SevenIsland_SevaultCanyon_Text_LexDefeat::
	.string "LEX: Sono stato troppo\n"
	.string "sbadato…$"

SevenIsland_SevaultCanyon_Text_LexPostBattle::
	.string "LEX: Credo sia stata una bella\n"
	.string "esperienza per NYA.\p"
	.string "Ti sono grato.$"

SevenIsland_SevaultCanyon_Text_LexNotEnoughMons::
	.string "LEX: Possiamo lottare contro\n"
	.string "noi due insieme?$"

SevenIsland_SevaultCanyon_Text_NyaIntro::
	.string "NYA: Darò il massimo per non\n"
	.string "essere da peso al mio maestro LEX!$"

SevenIsland_SevaultCanyon_Text_NyaDefeat::
	.string "NYA: Oh, no…\n"
	.string "Mi dispiace tanto, io…$"

SevenIsland_SevaultCanyon_Text_NyaPostBattle::
	.string "NYA: Credo di aver bisogno\n"
	.string "di molta più esperienza\l"
	.string "sotto LEX…\p"
	.string "…Quindi, LEX, posso restare\n"
	.string "con te, così?$"

SevenIsland_SevaultCanyon_Text_NyaNotEnoughMons::
	.string "NYA: Scusa, possiamo lottare\n"
	.string "in stile due contro due?$"

SevenIsland_SevaultCanyon_Text_RouteSign::
	.string "CANION SEVAULT\n"
	.string "ROVINE TANOBY PIÙ AVANTI$"

SevenIsland_SevaultCanyon_Text_BrunoTrainedWithBrawly::
	.string "Allenarsi da soli non è\n"
	.string "certo una brutta cosa.\p"
	.string "Ma non è male puntare in alto\n"
	.string "con un compagno.\p"
	.string "Persino BRUNO…\n"
	.string "Si allenò con un certo\l"
	.string "BRAWLY, tempo fa.$"
