Route11_Frlg_MapScripts::
	.byte 0

Route11_EventScript_DiglettsCaveSign::
	msgbox Route11_Text_DiglettsCave, MSGBOX_SIGN
	end

Route11_Text_HugoIntro::
	.string "Vincere, perdere o pareggiare!$"

Route11_Text_HugoDefeat::
	.string "Atcha!\n"
	.string "Non è andata come volevo!$"

Route11_Text_HugoPostBattle::
	.string "I POKéMON sono la vita!\n"
	.string "E vivere è giocare!$"

Route11_Text_JasperIntro::
	.string "Sfide!\n"
	.string "Non ne ho mai abbastanza!$"

Route11_Text_JasperDefeat::
	.string "Ci ho quasi fatto!$"

Route11_Text_JasperPostBattle::
	.string "Nel mondo dei POKéMON\n"
	.string "non puoi essere codardo!$"

Route11_Text_EddieIntro::
	.string "Andiamo, ma niente trucchi!$"

Route11_Text_EddieDefeat::
	.string "Eh?\n"
	.string "Non è giusto!$"

Route11_Text_EddiePostBattle::
	.string "Ho dato il massimo.\n"
	.string "Non ho rimpianti.$"

Route11_Text_BraxtonIntro::
	.string "Attenzione!\n"
	.string "Sto stendendo dei cavi!$"

Route11_Text_BraxtonDefeat::
	.string "Che scarica elettrica!$"

Route11_Text_BraxtonPostBattle::
	.string "Dillo in giro: risparmia energia!$"

Route11_Text_DillonIntro::
	.string "Sono appena diventato ALLENATORE.\n"
	.string "Ma credo di poter vincere.$"

Route11_Text_DillonDefeat::
	.string "I miei POKéMON non ce l'hanno fatta…\n"
	.string "Non sono cresciuti abbastanza?$"

Route11_Text_DillonPostBattle::
	.string "E adesso?\n"
	.string "Lasciami in pace!$"

Route11_Text_DirkIntro::
	.string "Fwahaha!\n"
	.string "Non ho mai perso!$"

Route11_Text_DirkDefeat::
	.string "La mia prima sconfitta!$"

Route11_Text_DirkPostBattle::
	.string "Sei stato solo fortunato, tutto qui.$"

Route11_Text_DarianIntro::
	.string "Non ho mai vinto prima…$"

Route11_Text_DarianDefeat::
	.string "Me l'aspettavo…$"

Route11_Text_DarianPostBattle::
	.string "Sono stato sfortunato, come sempre.$"

Route11_Text_YasuIntro::
	.string "Sono il migliore della classe.\n"
	.string "Mi alleno ogni mattina.$"

Route11_Text_YasuDefeat::
	.string "Accidenti!\n"
	.string "I miei POKéMON devono essere più forti!$"

Route11_Text_YasuPostBattle::
	.string "C'è un POKéMON grasso che scende\n"
	.string "dalle montagne.\p"
	.string "Scommetto che sarebbe forte\n"
	.string "se lo catturi.$"

Route11_Text_BernieIntro::
	.string "Attento ai fili scoperti!$"

Route11_Text_BernieDefeat::
	.string "Wow!\n"
	.string "Che scarica!$"

Route11_Text_BerniePostBattle::
	.string "Beh, meglio tornare al lavoro.$"

Route11_Text_DaveIntro::
	.string "Ho allevato i miei POKéMON con cura.\n"
	.string "Ora dovrebbero essere pronti!$"

Route11_Text_DaveDefeat::
	.string "Ciao ciao!\n"
	.string "Grazie e arrivederci!$"

Route11_Text_DavePostBattle::
	.string "Tch…\n"
	.string "Meglio cercarne di più forti!$"

Route11_Text_DiglettsCave::
	.string "GROTTA DIGLETT$"

