gText_ApprenticeChallenge0::
	.string "Ehm, sono l'allievo n. {STR_VAR_2} di {STR_VAR_1}.\n"
	.string "Sniff… che tensione…$"

gText_ApprenticeChallenge1::
	.string "Sono l'allievo n. {STR_VAR_2} di {STR_VAR_1}!\n"
	.string "Arriviamo!$"

gText_ApprenticeChallenge2::
	.string "Sono l'allievo n. {STR_VAR_2} di {STR_VAR_1}!\n"
	.string "Accetta la sfida!$"

gText_ApprenticeChallenge3::
	.string "Ehm… sono l'allievo n. {STR_VAR_2} di {STR_VAR_1}…\n"
	.string "Credi che uno come me possa vincere?$"

gText_ApprenticeChallenge4::
	.string "Sono l'allievo n. {STR_VAR_2} di {STR_VAR_1}!\n"
	.string "Ti lascio sfidarmi!$"

gText_ApprenticeChallenge5::
	.string "Sono occupatissimo, ma sono anche\n"
	.string "l'allievo n. {STR_VAR_2} di {STR_VAR_1}.$"

gText_ApprenticeChallenge6::
	.string "Sono l'allievo n. {STR_VAR_2} di {STR_VAR_1}.\n"
	.string "Piacere!$"

gText_ApprenticeChallenge7::
	.string "Sono l'allievo n. {STR_VAR_2} di {STR_VAR_1}.\n"
	.string "Posso iniziare?$"

gText_ApprenticeChallenge8::
	.string "Ih! Sono l'allievo n. {STR_VAR_2} di {STR_VAR_1}!\n"
	.string "Darò il massimo!$"

gText_ApprenticeChallenge9::
	.string "Iuuu! Sono l'allievo n. {STR_VAR_2} di {STR_VAR_1}!\n"
	.string "Su, difenditi!$"

gText_ApprenticeChallenge10::
	.string "Sono il millesimo allievo di {STR_VAR_1}!\n"
	.string "Anzi, sono il n. {STR_VAR_2}! Si parte!$"

gText_ApprenticeChallenge11::
	.string "Sì, sono l'allievo n. {STR_VAR_2} di {STR_VAR_1}!\n"
	.string "Diamo spettacolo!$"

gText_ApprenticeChallenge12::
	.string "Uhuuu! Sono quello che si dice\n"
	.string "l'allievo n. {STR_VAR_2} di {STR_VAR_1}!$"

gText_ApprenticeChallenge13::
	.string "Coff! Sono l'allievo n. {STR_VAR_2} di {STR_VAR_1}.\n"
	.string "Piacere! Coff!$"

gText_ApprenticeChallenge14::
	.string "Che emozione…\n"
	.string "Sono l'allievo n. {STR_VAR_2} di {STR_VAR_1}.$"

gText_ApprenticeChallenge15::
	.string "Sono l'allievo n. {STR_VAR_2} di {STR_VAR_1},\n"
	.string "e non scherzo.$"

gText_ApprenticePleaseTeach0::
	.string "Sei… {PLAYER}?\n"
	.string "Oh! Singhiozzo…\p"
	.string "Oh! S-scusa…\n"
	.string "Sono così nervoso che piango…\p"
	.string "Sono {STR_VAR_1}, e ti ammiro\n"
	.string "molto, {PLAYER}.\p"
	.string "Sognavo di incontrarti un giorno\n"
	.string "e chiederti dei POKéMON.\p"
	.string "Ti prego, ti prego, {PLAYER}!\n"
	.string "Insegnami tutto sui POKéMON!$"

gText_ApprenticeRejectTeaching0::
	.string "Oh… M-ma…\n"
	.string "Singhiozzo… Waaaaaaah!\p"
	.string "Ti prego!\n"
	.string "Ti supplico, ti prego!$"

gText_ApprenticeWhichLevelMode0::
	.string "Oh, davvero? Lo farai?\n"
	.string "Fantastico! Burbero! Uauuu!\p"
	.string "Oh… scusa…\n"
	.string "Sono così felice che piango…\p"
	.string "Ehm… Allora dimmi!\n"
	.string "Riguarda la TORRE LOTTA.\p"
	.string "Cosa sarebbe meglio per me: Livello 50\n"
	.string "o il Livello Libero?$"

gText_ApprenticeLevelModeThanks0::
	.string "{STR_VAR_1}?\n"
	.string "Waaaaah!\p"
	.string "Oh! Mi dispiace tanto!\n"
	.string "Sono felice che tu abbia scelto il\l"
	.string "livello per me, e mi hai fatto piangere…\p"
	.string "Sniff…\n"
	.string "Grazie mille!\l"
	.string "Riparliamo ancora, ti prego!$"

gText_ApprenticePleaseTeach1::
	.string "Uau! Tu sei {PLAYER}, vero?\n"
	.string "Sei fortissimo, vero?\p"
	.string "Sono {STR_VAR_1}!\n"
	.string "Sono appena diventato un ALLENATORE!\p"
	.string "Ti prego, {PLAYER}!\n"
	.string "Puoi essere il mio maestro e dirmi\l"
	.string "tante cose su come essere ALLENATORE?$"

gText_ApprenticeRejectTeaching1::
	.string "Aw, perché?\n"
	.string "Oh, ti prego? Ti prego tanto?\l"
	.string "Sii il mio maestro, ti prego!$"

gText_ApprenticeWhichLevelMode1::
	.string "Evvai! Grande!\p"
	.string "La prima cosa che volevo chiederti\n"
	.string "riguarda la TORRE LOTTA!\p"
	.string "Le Sale Livello 50 e Livello Libero…\n"
	.string "Quale sarebbe perfetta per me?$"

gText_ApprenticeLevelModeThanks1::
	.string "{STR_VAR_1}, eh? È vero!\n"
	.string "Là darò il massimo!\p"
	.string "Se ci rivediamo qui, insegnami\n"
	.string "qualcos'altro, prof!$"

gText_ApprenticePleaseTeach2::
	.string "Uhm… Sei {PLAYER}?\n"
	.string "Mi chiamo {STR_VAR_1}.\p"
	.string "Voglio diventare un ALLENATORE POKéMON,\n"
	.string "ma non so cosa fare…\p"
	.string "Così ho pensato di chiederti\n"
	.string "un consiglio, visto che sei famoso.\p"
	.string "{PLAYER}, mi daresti un consiglio?$"

gText_ApprenticeRejectTeaching2::
	.string "Oh, ma…\p"
	.string "Voglio davvero diventare un ALLENATORE\n"
	.string "di POKéMON!\p"
	.string "Ti prego, rispondi alle mie domande?$"

gText_ApprenticeWhichLevelMode2::
	.string "Grazie!\n"
	.string "Ecco subito la mia prima domanda!\p"
	.string "La TORRE LOTTA ha due livelli,\n"
	.string "Livello 50 e Livello Libero, vero?\p"
	.string "Quale livello pensi sia più\n"
	.string "adatto a me?$"

gText_ApprenticeLevelModeThanks2::
	.string "Oh, la sfida {STR_VAR_1}?\n"
	.string "Capito!\p"
	.string "Se avrò un'altra domanda, tornerò\n"
	.string "qui a chiederti un consiglio!$"

gText_ApprenticePleaseTeach3::
	.string "Oh? Eh? Tu sei…\n"
	.string "No, non può essere vero.\p"
	.string "Non è possibile che uno\n"
	.string "come me incontri {PLAYER}.\p"
	.string "…Sei davvero {PLAYER}?\n"
	.string "Non credo di parlarti davvero!\p"
	.string "Quando succede qualcosa di così bello,\n"
	.string "solo cose terribili mi accadranno\l"
	.string "ora, lo so già…\p"
	.string "…Scusa…\n"
	.string "Sono… {STR_VAR_1}…\p"
	.string "Non c'è nulla di speciale\n"
	.string "in me di cui essere orgoglioso…\p"
	.string "Non dovrei nemmeno parlare\n"
	.string "di me, perché mi dimenticherai…\p"
	.string "Sognavo che se ti avessi incontrato,\n"
	.string "{PLAYER}, forse avrei potuto chiederti\l"
	.string "un consiglio come ALLENATORE.\p"
	.string "Ma non credo che accetteresti\n"
	.string "questo.\p"
	.string "…O sarai così gentile da darmi\n"
	.string "un consiglio?$"

gText_ApprenticeRejectTeaching3::
	.string "Lo sapevo…\p"
	.string "Doveva succedere perché sono\n"
	.string "un nessuno noioso…\p"
	.string "Ma pensavo che forse…\n"
	.string "Non ci ripenserai, vero?\p"
	.string "Ma non posso arrendermi così.\n"
	.string "Te lo chiederò finché sono fortunato!\p"
	.string "Ti prego, sarai così gentile da darmi\n"
	.string "un consiglio?$"

gText_ApprenticeWhichLevelMode3::
	.string "Davvero? Non ci credo!\n"
	.string "Non credo che mi consiglierai!\l"
	.string "Sono… sono così felice…\p"
	.string "Quello che voglio chiederti è davvero\n"
	.string "banale, ma non riesco a decidere…\p"
	.string "Alla TORRE LOTTA ti fanno\n"
	.string "scegliere il Livello 50 o il Livello Libero.\p"
	.string "Quale pensi che anche per me\n"
	.string "possa avere una possibilità?$"

gText_ApprenticeLevelModeThanks3::
	.string "{STR_VAR_1}? Ok!\n"
	.string "Ma pensi davvero che uno come\l"
	.string "me abbia qualche possibilità?\p"
	.string "Farò del mio meglio, anche se non\n"
	.string "credo che funzionerà.\p"
	.string "Grazie mille per aver passato\n"
	.string "tempo con uno come me.$"

gText_ApprenticePleaseTeach4::
	.string "Oh! Tu sei {PLAYER}{KUN}, vero?\p"
	.string "Ho sentito che sei forte con i\n"
	.string "POKéMON!\p"
	.string "Sono {STR_VAR_1}!\n"
	.string "Sarò tuo amico!\p"
	.string "Lo sapevi?\p"
	.string "Non puoi vincere al PARCO LOTTA\n"
	.string "se sai solo ciò che insegnano alla\l"
	.string "SCUOLA ALLENATORI.\p"
	.string "Ascolterò i tuoi consigli.\n"
	.string "Sarai d'accordo, no?$"

gText_ApprenticeRejectTeaching4::
	.string "Eh? Perché mi rifiuti?\n"
	.string "Sono io che te lo chiedo!\l"
	.string "Devi ripensarci!$"

gText_ApprenticeWhichLevelMode4::
	.string "Ok, c'è questa cosa.\n"
	.string "Voglio che decidi tu per me.\p"
	.string "Sai che la TORRE LOTTA ha\n"
	.string "le sale Livello 50 e Livello Libero?\p"
	.string "Quale pensi sarebbe buona\n"
	.string "per me, {PLAYER}{KUN}?$"

gText_ApprenticeLevelModeThanks4::
	.string "Ok, {STR_VAR_1} fa per me?\n"
	.string "Grazie!\p"
	.string "Sapendo che hai deciso tu,\n"
	.string "{PLAYER}{KUN}, non mi dispiacerà tanto\l"
	.string "se perdo.\p"
	.string "Ok, ti chiederò ancora consiglio.\n"
	.string "Ciao!$"

gText_ApprenticePleaseTeach5::
	.string "Oh, ciao! {PLAYER}{KUN}!\n"
	.string "Ti conosco perché sei famoso!\l"
	.string "Chiamami {STR_VAR_1}! Piacere!\p"
	.string "Sono un TRIATLETA, quindi mi tengo\n"
	.string "in forma mentre alleno POKéMON.\p"
	.string "Mi occupo anche di altre cose\n"
	.string "come lavoro, pisolini, balli da sala…\p"
	.string "Essendo così occupato, non è facile per\n"
	.string "me diventare un ALLENATORE decente.\p"
	.string "Quindi ho una proposta!\p"
	.string "Ci sarà un motivo se ci siamo incontrati.\n"
	.string "Allora, {PLAYER}{KUN}, che ne dici di condividere\l"
	.string "la tua saggezza con me ogni tanto?$"

gText_ApprenticeRejectTeaching5::
	.string "Oh, ma, ti prego?\n"
	.string "Uno come me ha bisogno di uno come\l"
	.string "te, {PLAYER}{KUN}!\p"
	.string "Sinceramente, mi serve il tuo consiglio!$"

gText_ApprenticeWhichLevelMode5::
	.string "Grazie! Così mi piace!\n"
	.string "Allora, iniziamo con una facile!\p"
	.string "Conosci i due percorsi della\n"
	.string "TORRE LOTTA, vero?\l"
	.string "Sai, Livello 50 e Livello Libero.\p"
	.string "Da bravo occupato, per quale dovrei\n"
	.string "prepararmi?$"

gText_ApprenticeLevelModeThanks5::
	.string "{STR_VAR_1}, eh? Ok, capito.\n"
	.string "Troverò il tempo e ci proverò!\p"
	.string "…Ops, meglio che vada al lavoro!\n"
	.string "Grazie! Ci vediamo!$"

gText_ApprenticePleaseTeach6::
	.string "Non ci credo! No!\n"
	.string "Sei forse il vero {PLAYER}?\p"
	.string "A-ha! Fantastico! Sono {STR_VAR_1},\n"
	.string "che piacere conoscerti!\p"
	.string "{PLAYER}, sei molto forte,\n"
	.string "vero?\p"
	.string "Tutti parlano di te!\p"
	.string "Oh! Ho appena avuto un'idea geniale!\n"
	.string "Ti chiederò consigli, {PLAYER}!\l"
	.string "Sono sicuro che mi renderanno più forte!\p"
	.string "Non è un'idea geniale?\n"
	.string "Ti prego, voglio il tuo consiglio!$"

gText_ApprenticeRejectTeaching6::
	.string "Ahahaha, puoi fingere di essere cattivo,\n"
	.string "ma non mi inganni!\l"
	.string "Intendi sì, vero?$"

gText_ApprenticeWhichLevelMode6::
	.string "Evvai! Sapevo che hai un gran cuore,\n"
	.string "{PLAYER}!\p"
	.string "Cosa ti chiedo per primo?\n"
	.string "…Oh, mi è venuto in mente!\p"
	.string "Rullo di tamburi!\n"
	.string "La domanda che ho è…\p"
	.string "Se dovessi affrontare una sfida alla\n"
	.string "TORRE LOTTA, quale sceglierei?\p"
	.string "Livello 50 o Livello Libero?\n"
	.string "Quale mi si addice di più?$"

gText_ApprenticeLevelModeThanks6::
	.string "Oh-oh-oh!\n"
	.string "{STR_VAR_1}, dici!\l"
	.string "Grazie per una risposta così forte!\p"
	.string "Credo di averti chiesto tutto quello\n"
	.string "che volevo oggi.\p"
	.string "Ci rivediamo qui, ok?\n"
	.string "Grazie!$"

gText_ApprenticePleaseTeach7::
	.string "Chiedo scusa, ma…\n"
	.string "Sei {PLAYER}?\p"
	.string "Sono {STR_VAR_1}, e sono lieto di\n"
	.string "fare la tua conoscenza.\p"
	.string "Ti ammiro\n"
	.string "da molto tempo…\p"
	.string "… … … … … …\p"
	.string "Uhm… spero che questa richiesta\n"
	.string "non ti pesi troppo, ma…\p"
	.string "Posso diventare il tuo apprendista,\n"
	.string "{PLAYER}?$"

gText_ApprenticeRejectTeaching7::
	.string "Oh…!\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "…Devo essere svenuto dallo shock.\n"
	.string "Scusa, devo aver sentito male.\p"
	.string "Ti prego! Di' che mi accetti\n"
	.string "come tuo apprendista!$"

gText_ApprenticeWhichLevelMode7::
	.string "Oh… sono felice!\p"
	.string "Non voglio farti perdere tempo,\n"
	.string "quindi consigliami su questo.\p"
	.string "Ho intenzione di sfidare presto\n"
	.string "la TORRE LOTTA.\p"
	.string "Però ci sono due livelli…\p"
	.string "Quale sarebbe più adatto a me?\n"
	.string "Livello 50 o Livello Libero?$"

gText_ApprenticeLevelModeThanks7::
	.string "{STR_VAR_1} è la tua scelta!\n"
	.string "Capisco. Farò del mio meglio!\p"
	.string "Grazie, {PLAYER}.\n"
	.string "Spero di poterti contare ancora.\l"
	.string "Stammi bene!$"

gText_ApprenticePleaseTeach8::
	.string "Ih! Ih! {PLAYER}!\n"
	.string "Mi hai parlato!\l"
	.string "Io… sono felicissimo!\p"
	.string "Io! Mi chiamo {STR_VAR_1}!\n"
	.string "Sono appena diventato un ALLENATORE!\p"
	.string "Sono felice di averti incontrato, {PLAYER},\n"
	.string "il grande nome dei POKéMON!\p"
	.string "Oh-oh-oh, lo so!\n"
	.string "Posso chiederti un enorme favore, {PLAYER}?\p"
	.string "Prendimi come tuo apprendista!\n"
	.string "Voglio imparare da te!$"

gText_ApprenticeRejectTeaching8::
	.string "Waaaah!\n"
	.string "{PLAYER} mi ha rifiutato…\l"
	.string "È… È un'esperienza preziosa!\p"
	.string "{PLAYER}, ti prego! Voglio sentire\n"
	.string "una risposta affermativa stavolta!\p"
	.string "Ti supplico di guidarmi!$"

gText_ApprenticeWhichLevelMode8::
	.string "Ihihih! {PLAYER} ha detto sì!\n"
	.string "{PLAYER} ha detto sì!\p"
	.string "Stanotte non dormirò…\n"
	.string "Grazie mille!\p"
	.string "Allora, ecco la mia domanda!\p"
	.string "Alla TORRE LOTTA, cosa è giusto\n"
	.string "per me, Livello 50 o Livello Libero?$"

gText_ApprenticeLevelModeThanks8::
	.string "{STR_VAR_1}! Capito perfettamente!\n"
	.string "Ho capito perfettamente!\l"
	.string "Sono felicissimo!\p"
	.string "Spero che vorrai insegnarmi\n"
	.string "ancora qualcosa un'altra volta.$"

gText_ApprenticePleaseTeach9::
	.string "Whoa! Saresti forse…\n"
	.string "Saresti forse… {PLAYER}{KUN}?!\l"
	.string "Quell'ALLENATORE forte e famoso?\l"
	.string "Beh, ciao, sono il più fortunato!\p"
	.string "Ciao, mi chiamo {STR_VAR_1}!\p"
	.string "Ero alla ricerca di\n"
	.string "un insegnante POKéMON.\p"
	.string "E con un tempismo impeccabile,\n"
	.string "sei arrivato tu, {PLAYER}{KUN}!\p"
	.string "Quindi, ecco fatto, {PLAYER}{KUN}!\n"
	.string "Fammi fare l'apprendista da te!$"

gText_ApprenticeRejectTeaching9::
	.string "Gwaaaah!\n"
	.string "Sei davvero forte e tosto…\p"
	.string "Non fare così, ti prego.\n"
	.string "Te lo sto chiedendo!$"

gText_ApprenticeWhichLevelMode9::
	.string "Oh, sì! Che bella risposta!\n"
	.string "Aggiungerei: eccellente!\p"
	.string "Allora che ne dici di un primo consiglio\n"
	.string "sulla TORRE LOTTA?\p"
	.string "Se ci andassi, cosa sarebbe meglio?\n"
	.string "Livello 50 o Livello Libero?$"

gText_ApprenticeLevelModeThanks9::
	.string "Uh-huh, {STR_VAR_1}!\n"
	.string "Ok, tutto ok!\l"
	.string "Mostrerò il mio valore, che confettura!\p"
	.string "Bene, ti considero il mio mentore!\n"
	.string "Adios!$"

gText_ApprenticePleaseTeach10::
	.string "Oh, ciao, {PLAYER}{KUN}, giusto?\n"
	.string "La polizia ti stava cercando!\p"
	.string "… … …\n"
	.string "Certo che sto mentendo!\p"
	.string "Io sono {STR_VAR_1}. Nonostante\n"
	.string "l'aspetto, sono il CAMPIONE POKéMON!\l"
	.string "…Anche questa è una bugia!\p"
	.string "Questa però non è una bugia.\n"
	.string "Non sono molto bravo a lottare.\p"
	.string "Che ne dici di diventare il mio maestro\n"
	.string "in tutto ciò che riguarda i POKéMON?$"

gText_ApprenticeRejectTeaching10::
	.string "Se fai il freddo così,\n"
	.string "ti mostrerò cosa farò!\p"
	.string "Waaah! Waaah! Waaah!\n"
	.string "Singhiozzo!\p"
	.string "Ahahah, erano le mie FINITE LACRIME!\p"
	.string "Dai, sarai il mio\n"
	.string "maestro POKéMON?$"

gText_ApprenticeWhichLevelMode10::
	.string "Evviva!\n"
	.string "Per questo ti comprerei una barca!\p"
	.string "Certo che sto mentendo di nuovo!\n"
	.string "Ma… grazie, maestro!\p"
	.string "Sai che alla TORRE LOTTA ci sono il\n"
	.string "Livello 50 e il Livello Libero?\p"
	.string "Non riesco a decidere a quale\n"
	.string "livello sfidare…\p"
	.string "Puoi decidere per me, maestro?$"

gText_ApprenticeLevelModeThanks10::
	.string "Ok, quindi meglio {STR_VAR_1}!\n"
	.string "Allora vado all'altro livello!\p"
	.string "Scherzo!\n"
	.string "Seguirò i tuoi insegnamenti, maestro!\p"
	.string "Grazie, maestro!\n"
	.string "Spero che continuerai a insegnarmi!$"

gText_ApprenticePleaseTeach11::
	.string "A-H-O-Y!\n"
	.string "Si scrive ahoy, e vuol dire ciao!\p"
	.string "Sono {STR_VAR_1}, il MARINAIO rapper\n"
	.string "che c'è qua!\p"
	.string "Tocca a te ora, dimmi qualcosa\n"
	.string "su di te, dai, prova!\p"
	.string "Uh-huh, uh-huh!\n"
	.string "Ti chiami {PLAYER}{KUN},\l"
	.string "e i POKéMON sono il tuo gioco!\p"
	.string "E sei a un'età delicata\n"
	.string "in cui il mondo è il tuo palco!\p"
	.string "Comunque, voglio solo dire\n"
	.string "che sei il decimo ALLENATORE\l"
	.string "con cui parlo oggi.\p"
	.string "Festeggiamo!\n"
	.string "Diventa mio mentore per commemorare!$"

gText_ApprenticeRejectTeaching11::
	.string "Ma!\n"
	.string "Devi collaborare con me!\p"
	.string "Non prendermi in giro!\n"
	.string "Diventa mio mentore, ti prego!$"

gText_ApprenticeWhichLevelMode11::
	.string "Proprio così!\n"
	.string "{PLAYER}, hai spirito!\p"
	.string "Ecco la mia prima domanda\n"
	.string "che attende il tuo suggerimento!\p"
	.string "Riguarda la TORRE LOTTA,\n"
	.string "e dipende dalla mia forza!\p"
	.string "Livello 50 e Livello Libero ci sono,\n"
	.string "quale fa bene a me?$"

gText_ApprenticeLevelModeThanks11::
	.string "Ok, {STR_VAR_1} dici!\n"
	.string "Ci andrò per la mia strada!\p"
	.string "Se mai mi servirà un consiglio,\n"
	.string "{PLAYER}, seguirò sempre la tua parola!$"

gText_ApprenticePleaseTeach12::
	.string "Ehi, ma tu sei {PLAYER}?\n"
	.string "Che faccio? Ti parlo?\l"
	.string "Perché no? Ti sto già parlando!\p"
	.string "{PLAYER}, ti sorprendo?\n"
	.string "Meglio dirti chi sono!\p"
	.string "{STR_VAR_1} è il mio nome.\n"
	.string "La stella più brillante della chitarra,\l"
	.string "sono io!\p"
	.string "Mi ricevi?\n"
	.string "Mi ricevi!\p"
	.string "Ho una fortuna sfacciata,\n"
	.string "ti faccio una richiesta!\p"
	.string "{PLAYER}, fammi essere tuo allievo!\n"
	.string "Voglio che mi insegni tutto!$"

gText_ApprenticeRejectTeaching12::
	.string "Mi stai rifiutando?\n"
	.string "Dovrò chiedertelo di nuovo!\p"
	.string "{PLAYER}, ti supplico di prendermi!\n"
	.string "Devi insegnarmi tutto!$"

gText_ApprenticeWhichLevelMode12::
	.string "Fortuna, sì, evviva!\n"
	.string "Ti faccio una domanda?\p"
	.string "Visto che siamo al BATTLE TOWER,\n"
	.string "che ne dici di una sulla sua potenza?\p"
	.string "Fra le scelte che vedi,\n"
	.string "quale fa per me?$"

gText_ApprenticeLevelModeThanks12::
	.string "Se {STR_VAR_1} è il tuo consiglio,\n"
	.string "dev'essere il migliore in assoluto!\p"
	.string "Beh, {PLAYER}, io devo girare il mondo,\n"
	.string "ma tu non dimenticarmi.\p"
	.string "Ci vediamo, amico intelligente!$"

gText_ApprenticePleaseTeach13::
	.string "Oh, ciao! Tu là!\n"
	.string "Mi massaggi la spalla?\p"
	.string "…Sì, proprio lì! Così!\n"
	.string "Ahia, ahia! Oooh, che bello!\p"
	.string "Mi chiamo {STR_VAR_1}.\n"
	.string "Faccio karate, ma il mio corpo non è\l"
	.string "fatto per questi colpi…\p"
	.string "Ho deciso che lottarò con i POKéMON e\n"
	.string "mi temprerò.\p"
	.string "Sei {PLAYER}{KUN}, vero?\n"
	.string "Il CAMPIONE della LEGA POKéMON?\p"
	.string "Senti, mi daresti\n"
	.string "un consiglio?$"

gText_ApprenticeRejectTeaching13::
	.string "Oh, perché?\p"
	.string "Non sarò un peso, promesso!\n"
	.string "Ti prego?$"

gText_ApprenticeWhichLevelMode13::
	.string "Grazie. Molto gentile da parte tua!\n"
	.string "…Coff! Coff!\p"
	.string "Oogh, devo irrobustirmi in fretta…\p"
	.string "Andrò subito alla TORRE LOTTA,\n"
	.string "ma cosa sarebbe meglio per me?\l"
	.string "Livello 50 o Livello Libero?$"

gText_ApprenticeLevelModeThanks13::
	.string "Hm, va bene. Quindi {STR_VAR_1}.\n"
	.string "Ci andrò subito.\p"
	.string "Spero di poterti chiedere ancora\n"
	.string "aiuto: in fondo sei il mio mentore!$"

gText_ApprenticePleaseTeach14::
	.string "Ehm… Uhm…\n"
	.string "{PLAYER}{KUN}…?\p"
	.string "Ti prego, non guardarmi così.\n"
	.string "Mi fai sentire in imbarazzo.\p"
	.string "Io… sono {STR_VAR_1}.\p"
	.string "Mi vergogno molto a dirlo,\n"
	.string "ma esploro antiche rovine e simili.\p"
	.string "Mi vergogno ancora di più ad ammettere\n"
	.string "che mi interessa il PARCO LOTTA.\p"
	.string "{PLAYER}{KUN}, hai la fama di\n"
	.string "un ALLENATORE forte…\p"
	.string "È difficile dirlo,\n"
	.string "ma voglio chiederti una cosa.\p"
	.string "Potresti diventare il mio maestro e\n"
	.string "darmi consigli?$"

gText_ApprenticeRejectTeaching14::
	.string "Non liquidarmi così!\n"
	.string "Non posso vivere con l'umiliazione.\p"
	.string "Diventa il mio maestro!\n"
	.string "Mi serve il tuo consiglio!$"

gText_ApprenticeWhichLevelMode14::
	.string "G-grazie…\p"
	.string "Ma non guardarmi così.\n"
	.string "Mi fai agitare.\p"
	.string "Per favore, rispondi senza guardarmi\n"
	.string "negli occhi.\p"
	.string "Alla TORRE LOTTA…\n"
	.string "Quale livello dovrei provare?$"

gText_ApprenticeLevelModeThanks14::
	.string "Oh… Ok!\n"
	.string "Proverò a farlo.\p"
	.string "Spero di affrontarlo con baldanza\n"
	.string "senza agitarmi troppo…\p"
	.string "Grazie, {PLAYER}{KUN}.\n"
	.string "Se ci rivedremo, spero sarai\l"
	.string "altrettanto disponibile.$"

gText_ApprenticePleaseTeach15::
	.string "Hm? Tu sembri {PLAYER}{KUN}…\n"
	.string "Ma sei davvero reale?\p"
	.string "Puoi chiamarmi {STR_VAR_1}.\p"
	.string "Sto accarezzando l'idea di\n"
	.string "diventare allievo di un ALLENATORE forte.\p"
	.string "Che fortuna che tu sia passato!\n"
	.string "…Sei davvero {PLAYER}{KUN}, sì?\p"
	.string "No, no, se sei reale, va bene.\n"
	.string "Voglio solo che tu mi riconosca\l"
	.string "come tuo allievo.$"

gText_ApprenticeRejectTeaching15::
	.string "Oh?\n"
	.string "Ma cosa ti spinge a rifiutare?\p"
	.string "Mi scuso per aver dubitato della\n"
	.string "tua identità.\p"
	.string "Accetta le mie scuse e\n"
	.string "prendimi come apprendista.$"

gText_ApprenticeWhichLevelMode15::
	.string "Mi accetti davvero?\n"
	.string "Non voglio esultare troppo presto.\p"
	.string "Se è vero, mi scuso.\n"
	.string "Ma ora ho bisogno del tuo consiglio.\p"
	.string "Se entrassi nella TORRE LOTTA,\n"
	.string "cosa sarebbe degno di me?\l"
	.string "Livello 50 o Livello Libero?$"

gText_ApprenticeLevelModeThanks15::
	.string "{STR_VAR_1}?\n"
	.string "Ne sei certo?\p"
	.string "Capisco. Se è così, va bene.\n"
	.string "Ti ringrazio del tempo che mi dedichi.\p"
	.string "So di essere noioso, ma sono felice\n"
	.string "che tu mi abbia accettato.\p"
	.string "Ci rivedremo!$"

gText_ApprenticeWhatHeldItem0::
	.string "Sigh… Sob…\n"
	.string "Oh, {PLAYER}!\p"
	.string "Sono in un dilemma\n"
	.string "che non riesco a sciogliere.\p"
	.string "Non so cosa far tenere\n"
	.string "al mio {STR_VAR_1}.\p"
	.string "Dimmi, {PLAYER}.\n"
	.string "Quale oggetto gli faccio tenere?$"

gText_ApprenticeHoldNothing0::
	.string "Oh, davvero? Non devo far tenere\n"
	.string "nulla al mio {STR_VAR_1}?$"

gText_ApprenticeThanksNoHeldItem0::
	.string "Oh, ok! Sono felice che sia risolto!\n"
	.string "Grande! Burbero! Awoooh!\p"
	.string "Grazie mille!$"

gText_ApprenticeThanksHeldItem0::
	.string "Oh, sono così felice…\n"
	.string "Credo di avere anch'io quel {STR_VAR_1}.\p"
	.string "Sono felice che sia risolto!\n"
	.string "Fantastico! Burbero! Awoooh!\p"
	.string "Grazie mille!$"

gText_ApprenticeItemAlreadyRecommended0::
	.string "Waaaaah! Non essere cattivo!\p"
	.string "Quell'oggetto, {STR_VAR_1}, me l'avevi\n"
	.string "già consigliato, sigh…\p"
	.string "O vuoi dire che non devo far tenere\n"
	.string "nulla al mio {STR_VAR_2}?$"

gText_ApprenticeWhatHeldItem1::
	.string "Evviva! Sei {PLAYER}!\n"
	.string "Ottimo! Volevo chiederti una cosa!\p"
	.string "Fai tenere oggetti ai tuoi POKéMON?\n"
	.string "Io vorrei, ma…\p"
	.string "Quale oggetto sarebbe buono\n"
	.string "da far tenere a {STR_VAR_1}?\p"
	.string "Cosa ne pensi?$"

gText_ApprenticeHoldNothing1::
	.string "Eh? Vuoi dire che il mio {STR_VAR_1}\n"
	.string "non deve tenere nulla?$"

gText_ApprenticeThanksNoHeldItem1::
	.string "Oh, ho capito! Farò così!\n"
	.string "Grazie per avermi insegnato!$"

gText_ApprenticeThanksHeldItem1::
	.string "Oh, wow! Un {STR_VAR_1}, eh?\n"
	.string "Okay, lo farò!\p"
	.string "Grazie per avermelo insegnato!$"

gText_ApprenticeItemAlreadyRecommended1::
	.string "Oh, no, non intendevo quello.\n"
	.string "Voglio sapere di un oggetto diverso\l"
	.string "da quelli che già conosco.\p"
	.string "O vuoi dire che il mio POKéMON non\n"
	.string "deve tenere nulla stavolta?$"

gText_ApprenticeWhatHeldItem2::
	.string "{PLAYER}, ciao!\n"
	.string "Riguarda il mio {STR_VAR_1}…\p"
	.string "Voglio fargli tenere un buon oggetto.\n"
	.string "Cosa sarebbe adatto?$"

gText_ApprenticeHoldNothing2::
	.string "Oh, quindi il mio {STR_VAR_1} non deve\n"
	.string "tenere nulla?$"

gText_ApprenticeThanksNoHeldItem2::
	.string "Ok, ho capito!\n"
	.string "Ci vediamo!$"

gText_ApprenticeThanksHeldItem2::
	.string "Oh, l'oggetto {STR_VAR_1}?\n"
	.string "Capito!\p"
	.string "Farò del mio meglio per trovarlo!\n"
	.string "Ci vediamo!$"

gText_ApprenticeItemAlreadyRecommended2::
	.string "Qualcuno mi ha già parlato\n"
	.string "del {STR_VAR_1}.\p"
	.string "Voglio che i miei POKéMON tengano\n"
	.string "un oggetto diverso.\p"
	.string "O pensi che {STR_VAR_2} non\n"
	.string "debba tenere niente?$"

gText_ApprenticeWhatHeldItem3::
	.string "Ciao, {PLAYER}…\n"
	.string "Scusa il disturbo, ma volevo\l"
	.string "chiederti un'altra cosa.\p"
	.string "Non credo di essere abbastanza bravo\n"
	.string "a vincere da solo, quindi pensavo di\l"
	.string "far tenere un oggetto al mio {STR_VAR_1}.\p"
	.string "Ma non so quale sia buono.\p"
	.string "{PLAYER}, ti prego, decidi\n"
	.string "tu per me?$"

gText_ApprenticeHoldNothing3::
	.string "Un POKéMON di uno come me\n"
	.string "sta meglio senza oggetto?$"

gText_ApprenticeThanksNoHeldItem3::
	.string "Capisco…\n"
	.string "Dici che non devo contare sugli oggetti.\l"
	.string "Farò del mio meglio!\p"
	.string "Grazie mille!$"

gText_ApprenticeThanksHeldItem3::
	.string "L'oggetto {STR_VAR_1}, ok.\n"
	.string "Non so se riuscirò a trovarlo…\l"
	.string "No! Farò del mio meglio.\p"
	.string "Grazie mille!$"

gText_ApprenticeItemAlreadyRecommended3::
	.string "Oh, ma…\n"
	.string "Credo di averlo già sentito…\p"
	.string "Forse perché non ho usato bene\n"
	.string "l'oggetto {STR_VAR_1}?\p"
	.string "O vuoi dire che non devo far tenere\n"
	.string "nulla al mio {STR_VAR_2}?$"

gText_ApprenticeWhatHeldItem4::
	.string "Oh, {PLAYER}{KUN}.\n"
	.string "Volevo chiederti una cosa.\p"
	.string "Ricordi quando hai deciso quale\n"
	.string "POKéMON dovevo prendere?\p"
	.string "Ma non ti ho mai chiesto quale oggetto\n"
	.string "dovesse tenere.\p"
	.string "Visto che mi hai già consigliato,\n"
	.string "perché non finiamo l'opera?\p"
	.string "Cosa sarebbe buono? Voglio far\n"
	.string "tenere qualcosa al mio {STR_VAR_1}.$"

gText_ApprenticeHoldNothing4::
	.string "Oh! Quindi il mio {STR_VAR_1} deve\n"
	.string "dare il massimo a mani vuote?$"

gText_ApprenticeThanksNoHeldItem4::
	.string "Se pensi sia meglio, farò così.\p"
	.string "Sapendo che hai deciso tu,\n"
	.string "{PLAYER}{KUN}, non ci starò male se\l"
	.string "perdo.\p"
	.string "Ok, ti chiederò ancora consiglio.\n"
	.string "Ciao!$"

gText_ApprenticeThanksHeldItem4::
	.string "L'oggetto {STR_VAR_1}, eh?\n"
	.string "Non male. Lo userò!\p"
	.string "Sapendo che hai deciso tu,\n"
	.string "{PLAYER}{KUN}, non ci starò male se\l"
	.string "perdo.\p"
	.string "Ok, ti chiederò ancora consiglio.\n"
	.string "Ciao!$"

gText_ApprenticeItemAlreadyRecommended4::
	.string "Eh? Che cosa stai dicendo?\n"
	.string "Mi hai già parlato del {STR_VAR_1}\l"
	.string "prima d'ora.\p"
	.string "O vuoi dire che il mio {STR_VAR_2} deve\n"
	.string "cavarsela a mani vuote?$"

gText_ApprenticeWhatHeldItem5::
	.string "Ehi, {PLAYER}{KUN}!\p"
	.string "Siamo entrambi impegnati, ma ci\n"
	.string "incontriamo spesso lo stesso!\p"
	.string "Oggi devo camminare,\n"
	.string "pulire e spazzolare.\p"
	.string "Non ho avuto tempo di comprare\n"
	.string "nulla al mio {STR_VAR_1}.\p"
	.string "Non ho tempo, quindi perché non\n"
	.string "mi consigli cosa far tenere\l"
	.string "al mio {STR_VAR_1}?$"

gText_ApprenticeHoldNothing5::
	.string "Oh, dato che sono occupato, dici\n"
	.string "che al mio {STR_VAR_1} non serve nulla?$"

gText_ApprenticeThanksNoHeldItem5::
	.string "Ok, capito.\n"
	.string "Non mi servirà tempo per quello.\p"
	.string "Grazie di oggi!\n"
	.string "Ci vediamo!$"

gText_ApprenticeThanksHeldItem5::
	.string "Ok, capito.\n"
	.string "Troverò il tempo e procurerò\l"
	.string "quella {STR_VAR_1} che mi hai consigliato.\p"
	.string "Che bello averti come maestro.\n"
	.string "Grazie! Ci vediamo!$"

gText_ApprenticeItemAlreadyRecommended5::
	.string "Eh? Ma se conosco già\n"
	.string "quella {STR_VAR_1}.\p"
	.string "Ah, giusto, capisco.\n"
	.string "Quindi, dato che sono impegnato,\l"
	.string "il mio {STR_VAR_2} non serve nulla?$"

gText_ApprenticeWhatHeldItem6::
	.string "Ciao, {PLAYER}! Sono io!\n"
	.string "Oggi ho di nuovo bisogno di te.\l"
	.string "Ti prego, dammi un consiglio!\p"
	.string "Rullo di tamburi!\n"
	.string "La domanda che ho è…\p"
	.string "Se voglio far tenere a {STR_VAR_1}\n"
	.string "un oggetto, quale dovrebbe essere?$"

gText_ApprenticeHoldNothing6::
	.string "Ah, sì? Il mio {STR_VAR_1} non deve\n"
	.string "tenere un oggetto, dici.$"

gText_ApprenticeThanksNoHeldItem6::
	.string "Ok, farò così!\p"
	.string "Direi che è tutto quello che volevo\n"
	.string "chiederti oggi.\p"
	.string "Ci vediamo qui, ok?\n"
	.string "Grazie!$"

gText_ApprenticeThanksHeldItem6::
	.string "Certo! Una {STR_VAR_1}.\n"
	.string "Che scelta forte!\l"
	.string "La proverò di sicuro!\p"
	.string "Direi che è tutto quello che volevo\n"
	.string "chiederti oggi.\p"
	.string "Ci vediamo qui, ok?\n"
	.string "Grazie!$"

gText_ApprenticeItemAlreadyRecommended6::
	.string "Ahahah! Che sciocchezza!\n"
	.string "Mi hai già parlato di quel\l"
	.string "{STR_VAR_1} prima!\p"
	.string "Stai bene, {PLAYER}?\p"
	.string "Ah, aspetta! Il mio {STR_VAR_2} non\n"
	.string "deve tenere un oggetto, dici.$"

gText_ApprenticeWhatHeldItem7::
	.string "Hello, {PLAYER}. I hope you've been\n"
	.string "keeping well.\p"
	.string "May I approach you for advice?\p"
	.string "In a recent battle, my opponent\n"
	.string "seemed to have given his POKéMON\l"
	.string "an item to hold.\p"
	.string "As a result, I was defeated…\p"
	.string "I don't wish to be left behind.\n"
	.string "I would like to make my {STR_VAR_1}\l"
	.string "hold an item, too.\p"
	.string "It would please me if you could decide\n"
	.string "what would be right for my POKéMON…$"

gText_ApprenticeHoldNothing7::
	.string "In altre parole… il mio POKéMON\n"
	.string "non deve tenere un oggetto?$"

gText_ApprenticeThanksNoHeldItem7::
	.string "Ora ho capito bene!\n"
	.string "Continuerò così.\p"
	.string "Grazie, {PLAYER}.\n"
	.string "Spero di poterti contare ancora.\l"
	.string "Stammi bene!$"

gText_ApprenticeThanksHeldItem7::
	.string "Una {STR_VAR_1}, deciso!\n"
	.string "La ordinerò subito.\p"
	.string "Grazie, {PLAYER}.\n"
	.string "Spero di poterti contare ancora.\l"
	.string "Stammi bene!$"

gText_ApprenticeItemAlreadyRecommended7::
	.string "Me ne hai già parlato,\n"
	.string "e ce l'ho già.\p"
	.string "O stai dicendo… che i miei POKéMON non\n"
	.string "devono tenere oggetti?$"

gText_ApprenticeWhatHeldItem8::
	.string "Eek! {PLAYER}!\n"
	.string "I… I'm overjoyed to see you again!\p"
	.string "Oh-oh-oh! There's something I just\n"
	.string "had to ask you, {PLAYER}!\p"
	.string "Please decide what my {STR_VAR_1}\n"
	.string "should be holding!$"

gText_ApprenticeHoldNothing8::
	.string "Oh, uau! Non me l'aspettavo!\n"
	.string "Quindi un oggetto non serve?$"

gText_ApprenticeThanksNoHeldItem8::
	.string "Capito perfettamente!\n"
	.string "Andrò avanti senza oggetto!\p"
	.string "Spero che mi insegnerai\n"
	.string "ancora qualcosa.$"

gText_ApprenticeThanksHeldItem8::
	.string "{STR_VAR_1}! Userò quella!\p"
	.string "Ehm… {PLAYER}, anche tu fai\n"
	.string "tenere quell'oggetto ai POKéMON?\p"
	.string "Me la procurerò di sicuro!\n"
	.string "Spero che mi insegnerai\l"
	.string "ancora qualcosa.$"

gText_ApprenticeItemAlreadyRecommended8::
	.string "Oh? Mi avevi già consigliato\n"
	.string "quella {STR_VAR_1}.\p"
	.string "O è la cosa migliore da tenere?\n"
	.string "O intendi che il mio {STR_VAR_2} non\l"
	.string "deve tenere nulla?$"

gText_ApprenticeWhatHeldItem9::
	.string "Hola!\n"
	.string "Maestro mio, {PLAYER}{KUN}!\p"
	.string "Voglio chiederti un consiglio sugli\n"
	.string "strumenti dei POKéMON.\p"
	.string "Cosa pensi che sarebbe utile far tenere\n"
	.string "al mio {STR_VAR_1}?\p"
	.string "Non essere timido.\n"
	.string "Dillo subito!$"

gText_ApprenticeHoldNothing9::
	.string "Oh? Quindi dici che il mio {STR_VAR_1}\n"
	.string "può vincere senza tenere oggetti?$"

gText_ApprenticeThanksNoHeldItem9::
	.string "Si, bueno!\n"
	.string "Darò il massimo, tipo, schianto!\p"
	.string "Ok, grazie, come sempre!\n"
	.string "Adios!$"

gText_ApprenticeThanksHeldItem9::
	.string "Uh-huh, una {STR_VAR_1}?\n"
	.string "Si, bueno!\l"
	.string "Vado a prenderla, tipo, bam!\p"
	.string "Ok, grazie, come sempre!\n"
	.string "Adios!$"

gText_ApprenticeItemAlreadyRecommended9::
	.string "No, no! Mi hai già parlato di\n"
	.string "quel {STR_VAR_1} prima.\p"
	.string "Ah, aspetta un attimo…\n"
	.string "Quindi dici che il mio {STR_VAR_2}\l"
	.string "può vincere senza tenere oggetti?$"

gText_ApprenticeWhatHeldItem10::
	.string "{PLAYER}{KUN}, è successo\n"
	.string "qualcosa di incredibile!\p"
	.string "Stamattina il mio POKéMON\n"
	.string "aveva 10 PEPITE!\p"
	.string "Certo che mento!\n"
	.string "Wahahaha!\p"
	.string "Questo però non è falso.\n"
	.string "Non sono bravo a pensare\l"
	.string "a cosa far tenere ai POKéMON.\p"
	.string "Quindi decidi tu cosa deve tenere\n"
	.string "il mio {STR_VAR_1}, maestro?$"

gText_ApprenticeHoldNothing10::
	.string "Che vuol dire?\n"
	.string "Non fargli tenere nulla?$"

gText_ApprenticeThanksNoHeldItem10::
	.string "Ok, quindi non deve tenere nulla.\n"
	.string "Allora mi procuro qualcosa!\p"
	.string "Scherzavo!\n"
	.string "Obbedirò al tuo insegnamento, maestro!\p"
	.string "Grazie, maestro!\n"
	.string "Continua a insegnarmi!$"

gText_ApprenticeThanksHeldItem10::
	.string "Ok, allora una {STR_VAR_1}!\n"
	.string "Gliela farò tenere, ma non quella!\p"
	.string "Scherzo!\n"
	.string "Seguirò il tuo insegnamento, maestro!\p"
	.string "Grazie, maestro!\n"
	.string "Continua a insegnarmi!$"

gText_ApprenticeItemAlreadyRecommended10::
	.string "Ehm, me l'avevi già detto,\n"
	.string "no?\p"
	.string "Non c'è altro?\p"
	.string "O vuoi dire di non far tenere\n"
	.string "nulla al mio {STR_VAR_2}?$"

gText_ApprenticeWhatHeldItem11::
	.string "A-H-O-Y!\n"
	.string "Che si legge ahoy!\p"
	.string "Sono il MARINAIO rapper!\n"
	.string "Ti pongo una domanda\l"
	.string "davvero scanzonata!\p"
	.string "È una questione di oggetti\n"
	.string "che aspetta un tuo suggerimento!\p"
	.string "Il mio {STR_VAR_1} deve tenere un oggetto,\n"
	.string "Cosa scelgo, se posso osare?$"

gText_ApprenticeHoldNothing11::
	.string "Ah, sì?\n"
	.string "Il mio {STR_VAR_1} non deve\l"
	.string "tenere nulla?$"

gText_ApprenticeThanksNoHeldItem11::
	.string "Ok, ti ascolto, certo!\n"
	.string "Anche il mio POKéMON andrà a mani vuote!\p"
	.string "Se mi servirà un consiglio,\n"
	.string "{PLAYER}, ascolterò la tua parola!$"

gText_ApprenticeThanksHeldItem11::
	.string "Ok, una {STR_VAR_1},\n"
	.string "userò quella.\l"
	.string "Ho fatto bene a farti scegliere!\p"
	.string "Se mi servirà un consiglio,\n"
	.string "{PLAYER}, ascolterò la tua parola!$"

gText_ApprenticeItemAlreadyRecommended11::
	.string "Ok, un {STR_VAR_1}, dici?\n"
	.string "Me l'hai detto l'altro giorno.\l"
	.string "Voglio un'idea nuova, tutta nuova.\p"
	.string "O, che, è così?\n"
	.string "Il mio POKéMON non deve tenere\l"
	.string "nulla?$"

gText_ApprenticeWhatHeldItem12::
	.string "Ehi, {PLAYER}!\n"
	.string "Ti ho trovato di nuovo oggi!\p"
	.string "Che faccio? Ti chiedo un consiglio?\n"
	.string "Perché no? Ti sto già parlando!\p"
	.string "{PLAYER}, ti sto forse stancando?\n"
	.string "No, impossibile, non può essere.\p"
	.string "Mi ascolterai?\n"
	.string "Cerco un consiglio, ecco\l"
	.string "di cosa parlo.\p"
	.string "Riguarda un oggetto da far tenere\n"
	.string "al mio {STR_VAR_1}, qualcosa di buono.\l"
	.string "L'indecisione mi fa rimuginare.$"

gText_ApprenticeHoldNothing12::
	.string "Il mio {STR_VAR_1} non serve nulla?\n"
	.string "Non deve tenere niente?$"

gText_ApprenticeThanksNoHeldItem12::
	.string "Se non tenere nulla è meglio,\n"
	.string "ti seguirò!\p"
	.string "Beh, {PLAYER}, io devo andare,\n"
	.string "ma non dimenticarti di me.\p"
	.string "Ci vediamo, amico intelligente!$"

gText_ApprenticeThanksHeldItem12::
	.string "Se tenere quel {STR_VAR_1} è\n"
	.string "la cosa migliore, farò come dici!\p"
	.string "Beh, {PLAYER}, devo andare in giro,\n"
	.string "ma non dimenticarti di me.\p"
	.string "Ci vediamo, amico intelligente!$"

gText_ApprenticeItemAlreadyRecommended12::
	.string "Non avevo già sentito parlare\n"
	.string "di {STR_VAR_1}?\l"
	.string "Ne sono certo, sicuro!\p"
	.string "Voglio qualcosa di nuovo!\n"
	.string "O il mio {STR_VAR_2} non serve nulla?\l"
	.string "Non deve tenere niente?$"

gText_ApprenticeWhatHeldItem13::
	.string "Gwah! Ahia! {PLAYER}{KUN}, mi sono rotto il braccio!\n"
	.string "Non toccarlo, ti prego!\p"
	.string "Me lo sarò rotto provando\n"
	.string "vari oggetti da tenere con la mia banda\l"
	.string "di POKéMON.\p"
	.string "Quindi, vista la situazione,\n"
	.string "devi decidere tu per me.\p"
	.string "{PLAYER}{KUN}, cosa pensi sia\n"
	.string "buono da far tenere al mio {STR_VAR_1}?$"

gText_ApprenticeHoldNothing13::
	.string "Ahia…\p"
	.string "Quindi mi consigli che il mio {STR_VAR_1}\n"
	.string "non deve tenere nulla?$"

gText_ApprenticeThanksNoHeldItem13::
	.string "Hmm, va bene. Così è più facile\n"
	.string "per me, vista la situazione.\p"
	.string "Spero di poter ancora contare\n"
	.string "su di te.$"

gText_ApprenticeThanksHeldItem13::
	.string "Hm, va bene. Una {STR_VAR_1}.\n"
	.string "Il mio POKéMON sta bene, quindi\l"
	.string "gliela farò tenere subito.\p"
	.string "Spero di poterti chiedere\n"
	.string "ancora aiuto.$"

gText_ApprenticeItemAlreadyRecommended13::
	.string "No, no, me l'hai già detto\n"
	.string "di {STR_VAR_1}, ricordi?\p"
	.string "Non puoi dirmi qualcosa\n"
	.string "di ancora meglio?\p"
	.string "Oh, aspetta un attimo.\n"
	.string "Quindi mi consigli che il mio {STR_VAR_2}\l"
	.string "non deve tenere nulla?$"

gText_ApprenticeWhatHeldItem14::
	.string "Ehm… Uhm…\n"
	.string "{PLAYER}{KUN}…\p"
	.string "Ti prego, non guardarmi così.\n"
	.string "I miei POKéMON non hanno nulla.\p"
	.string "Mi… mi vergogno molto,\n"
	.string "ma ho davvero bisogno di te.\p"
	.string "Non so quale oggetto renderebbe\n"
	.string "forte il mio {STR_VAR_1}.\p"
	.string "{PLAYER}{KUN}, cosa pensi sia\n"
	.string "buono?$"

gText_ApprenticeHoldNothing14::
	.string "Oh… Quindi pensi che sia meglio\n"
	.string "se il mio {STR_VAR_1} non ha un oggetto?$"

gText_ApprenticeThanksNoHeldItem14::
	.string "Oh… Ok!\n"
	.string "Andrò senza oggetto.\p"
	.string "Che tensione, però.\n"
	.string "Non sarebbe troppo bello?\p"
	.string "Grazie, {PLAYER}{KUN}.\n"
	.string "Se ci rivedremo, spero sarai\l"
	.string "altrettanto d'aiuto.$"

gText_ApprenticeThanksHeldItem14::
	.string "Oh… Ok!\n"
	.string "Userò quella {STR_VAR_1}.\p"
	.string "Che tensione, però.\n"
	.string "Non sarebbe troppo bello?\p"
	.string "Grazie, {PLAYER}{KUN}.\n"
	.string "Se ci rivedremo, spero sarai\l"
	.string "altrettanto d'aiuto.$"

gText_ApprenticeItemAlreadyRecommended14::
	.string "M-ma l'ho già sentito.\p"
	.string "Non liquidarmi così!\n"
	.string "Non sopporto l'umiliazione.\p"
	.string "Oh… mi sto sbagliando?\n"
	.string "Pensi che sarebbe meglio se\l"
	.string "il mio {STR_VAR_2} non avesse un oggetto?$"

gText_ApprenticeWhatHeldItem15::
	.string "Hm? Tu sembri {PLAYER}{KUN}…\n"
	.string "Ma lo sei davvero?\l"
	.string "Forse sei un sosia?\p"
	.string "Oh, no, no, no, non preoccuparti!\n"
	.string "Se sei davvero {PLAYER}, ti prego\l"
	.string "dimentica la mia scortesia.\p"
	.string "Ciò che vorrei è ancora un po'\n"
	.string "dei tuoi ottimi consigli.\p"
	.string "Ho qui il mio {STR_VAR_1} a cui vorrei\n"
	.string "far tenere un oggetto comodo.\p"
	.string "Cosa sarebbe degno di lui?$"

gText_ApprenticeHoldNothing15::
	.string "Meglio se non tenesse nulla?\n"
	.string "Sei sicuro?$"

gText_ApprenticeThanksNoHeldItem15::
	.string "Capisco. Se è così, va bene.\n"
	.string "Grazie del tuo tempo.\p"
	.string "Ci rivedremo!$"

gText_ApprenticeThanksHeldItem15::
	.string "Una {STR_VAR_1}?\n"
	.string "Ne sei certo?\p"
	.string "Capisco. Se è così, va bene.\n"
	.string "Grazie del tuo tempo.\p"
	.string "Spero che il mio POKéMON sappia\n"
	.string "farne buon uso.\p"
	.string "Ci rivedremo!$"

gText_ApprenticeItemAlreadyRecommended15::
	.string "No, no, aspetta un momento.\n"
	.string "Credo che me l'abbia già insegnato.\p"
	.string "Vorrei che mi consigliassi\n"
	.string "qualcosa di diverso stavolta.\p"
	.string "Forse suggerisci che\n"
	.string "il mio {STR_VAR_2} non deve tenere nulla?\l"
	.string "Sei sicuro?$"

gText_ApprenticeWhichMonFirst0::
	.string "Uaaah, {PLAYER}!\n"
	.string "Ho un dilemma, singhiozzo…\p"
	.string "Voglio iniziare a lottare con altra gente,\n"
	.string "ma non so cosa fare.\p"
	.string "Come devo disporre i miei POKéMON\n"
	.string "perché siano al massimo?\p"
	.string "Dimmi, ti prego, {PLAYER}.\n"
	.string "Se fossi me, quale di questi POKéMON\l"
	.string "manderesti per primo?$"

gText_ApprenticeMonFirstThanks0::
	.string "Manda prima il mio {STR_VAR_1}?\n"
	.string "Waaaaah!\p"
	.string "Oh! Mi dispiace tanto!\n"
	.string "Sono felice che tu abbia scelto il mio\l"
	.string "primo POKéMON, e mi hai fatto piangere…\p"
	.string "Grazie mille!$"

gText_ApprenticeWhichMonFirst1::
	.string "Evviva! Sei {PLAYER}!\n"
	.string "Bene! Volevo chiederti una cosa!\p"
	.string "Ehm, dei miei POKéMON, quale pensi\n"
	.string "che debba entrare per primo?$"

gText_ApprenticeMonFirstThanks1::
	.string "Il mio {STR_VAR_1}? È vero.\n"
	.string "Ok, farò così!\p"
	.string "Grazie per avermelo insegnato!$"

gText_ApprenticeWhichMonFirst2::
	.string "{PLAYER}, ciao!\p"
	.string "Penso che in lotta sia molto importante\n"
	.string "quale POKéMON entra per primo.\p"
	.string "Tra i POKéMON che ho,\n"
	.string "quale sarebbe bene mandare per primo?$"

gText_ApprenticeMonFirstThanks2::
	.string "Il mio {STR_VAR_1} va per primo?\n"
	.string "Ok, capito!\p"
	.string "Ci vediamo!$"

gText_ApprenticeWhichMonFirst3::
	.string "Ciao, {PLAYER}…\n"
	.string "Scusa se ti disturbo ancora con\l"
	.string "un'altra domanda.\p"
	.string "Ho così poca fiducia, non so\n"
	.string "cosa farei senza di te, {PLAYER}.\p"
	.string "Forse è tempo perso preoccuparmi,\n"
	.string "ma proprio non riesco\l"
	.string "a decidere una cosa…\p"
	.string "Quale dei miei POKéMON mando\n"
	.string "per primo in lotta?$"

gText_ApprenticeMonFirstThanks3::
	.string "Il mio {STR_VAR_1}?\n"
	.string "Capito!\p"
	.string "Non riesco a credere che ti disturbi\n"
	.string "a rispondere così spesso!\p"
	.string "Sono così grato che tu persino\n"
	.string "parli con me… Grazie!$"

gText_ApprenticeWhichMonFirst4::
	.string "Oh, {PLAYER}{KUN}! Sono io!\n"
	.string "Che bello vederti, perché ho\l"
	.string "un piccolo problema.\p"
	.string "Non so decidere come disporre i miei\n"
	.string "POKéMON. Puoi decidere tu per me?\p"
	.string "Oh, non devi decidere tutta la\n"
	.string "squadra adesso.\p"
	.string "Che ne dici di decidere solo il primo\n"
	.string "POKéMON per me?$"

gText_ApprenticeMonFirstThanks4::
	.string "Il mio {STR_VAR_1}? Ottimo!\p"
	.string "Sapendo che hai deciso tu,\n"
	.string "{PLAYER}{KUN}, non mi dispiacerà tanto\l"
	.string "se perdo.\p"
	.string "Ok, ti chiederò ancora consiglio.\n"
	.string "Ciao!$"

gText_ApprenticeWhichMonFirst5::
	.string "Ciao, maestro {PLAYER}{KUN}!\n"
	.string "Oggi sono occupato di nuovo!\p"
	.string "Devo pedalare, fare spese\n"
	.string "e canticchiare.\p"
	.string "Non ho avuto tempo di decidere\n"
	.string "come disporre la mia squadra.\p"
	.string "Allora, che ne dici di dare un'occhiata?\n"
	.string "Quale deve andare per primo?$"

gText_ApprenticeMonFirstThanks5::
	.string "Ok, capito.\n"
	.string "Ho almeno il tempo di mettere\l"
	.string "il mio {STR_VAR_1} in testa alla squadra!\p"
	.string "Ops, la mia ragazza mi aspetta!\n"
	.string "Grazie! Ci vediamo!$"

gText_ApprenticeWhichMonFirst6::
	.string "Uuhuu! Ciao, {PLAYER}!\n"
	.string "Vai sempre in giro con aria tosta!\p"
	.string "Senti, ho di nuovo bisogno\n"
	.string "di te! È la solita cosa!\p"
	.string "Rullo di tamburi!\n"
	.string "La domanda riguarda la mia squadra.\p"
	.string "Quale dei miei POKéMON va per primo\n"
	.string "in lotta?$"

gText_ApprenticeMonFirstThanks6::
	.string "Hmhm!\n"
	.string "Il mio {STR_VAR_1}, dici!\l"
	.string "Grazie per una risposta così forte!\p"
	.string "Credo di averti chiesto tutto quello\n"
	.string "che volevo oggi.\p"
	.string "Ci rivediamo qui, ok?\n"
	.string "Grazie!$"

gText_ApprenticeWhichMonFirst7::
	.string "Grazie mille per esserti fermato\n"
	.string "a parlare con me, {PLAYER}.\p"
	.string "So che abuso della tua gentilezza,\n"
	.string "ma posso chiederti un consiglio?\p"
	.string "Vorrei che decidessi l'ordine\n"
	.string "della mia squadra POKéMON.\p"
	.string "Ti sarei grato se scegliessi\n"
	.string "quale POKéMON deve andare per primo.$"

gText_ApprenticeMonFirstThanks7::
	.string "Il mio {STR_VAR_1}!\n"
	.string "Lo metterò subito per primo!\p"
	.string "Grazie, {PLAYER}.\n"
	.string "Spero di poterti contare ancora.\l"
	.string "Stammi bene!$"

gText_ApprenticeWhichMonFirst8::
	.string "Ih! {PLAYER}!\n"
	.string "Io… sono felicissimo di rivederti!\p"
	.string "I miei POKéMON sono diventati molto\n"
	.string "più forti!\p"
	.string "Ma non vinco sempre. Sembra dipendere\n"
	.string "da quale POKéMON va per primo.\p"
	.string "{PLAYER}, ti prego, mi serve il tuo aiuto!\p"
	.string "Decidi quale dei miei POKéMON\n"
	.string "deve andare per primo!$"

gText_ApprenticeMonFirstThanks8::
	.string "Sigh… Sono sopraffatto dalla felicità…\p"
	.string "È come un sogno che decidi tu\n"
	.string "per me, {PLAYER}.\p"
	.string "Ma ho capito perfettamente!\n"
	.string "Inizio con il mio {STR_VAR_1}!\p"
	.string "Spero che vorrai insegnarmi\n"
	.string "ancora qualcosa un'altra volta.$"

gText_ApprenticeWhichMonFirst9::
	.string "Ciao, ciao!\n"
	.string "Il mio mentore, {PLAYER}{KUN}!\l"
	.string "Colpiscimi con il tuo saggio consiglio!\p"
	.string "Ho messo insieme una squadra di\n"
	.string "tre POKéMON. Fin qui tutto bene.\p"
	.string "Ma l'ordine di lotta della squadra\n"
	.string "non è ancora deciso.\p"
	.string "Qui entri in gioco tu, {PLAYER}{KUN}!\n"
	.string "Decidi quale POKéMON inizia!\p"
	.string "Non essere timido.\n"
	.string "Sputa il rospo!$"

gText_ApprenticeMonFirstThanks9::
	.string "Uh-huh, inizia il mio {STR_VAR_1}!\n"
	.string "Ok, tutto ok!\l"
	.string "Riordino la squadra, che botta!\p"
	.string "Bene, grazie, come sempre!\n"
	.string "Adios!$"

gText_ApprenticeWhichMonFirst10::
	.string "{PLAYER}{KUN}, ascolta!\n"
	.string "È una crisi!\p"
	.string "I miei POKéMON, tutti e tre, entrano\n"
	.string "in lotta insieme!\p"
	.string "Certo, è impossibile!\n"
	.string "Wahahaha!\p"
	.string "Però non è una bugia.\n"
	.string "Non sono bravo a pensare a\l"
	.string "come disporre i miei POKéMON.\p"
	.string "Allora, decidi tu per me quale\n"
	.string "POKéMON deve andare per primo, maestro?$"

gText_ApprenticeMonFirstThanks10::
	.string "Ok, quindi hai scelto il mio {STR_VAR_1}?\n"
	.string "Farò partire chiunque tranne lui!\p"
	.string "Scherzo!\n"
	.string "Seguirò i tuoi insegnamenti, maestro!\p"
	.string "Grazie, maestro!\n"
	.string "Spero che continuerai a insegnarmi!$"

gText_ApprenticeWhichMonFirst11::
	.string "A-H-O-Y!\n"
	.string "E si legge ahoy!\p"
	.string "Il MARINAIO rapper sono io!\n"
	.string "Ti presento una domanda\l"
	.string "che è un gioiello!\p"
	.string "È una domanda sulla squadra\n"
	.string "che chiede il tuo parere!\p"
	.string "Di questa truppa, chi va per primo\n"
	.string "come primo sul posto?$"

gText_ApprenticeMonFirstThanks11::
	.string "Ok, ti ascolto, certo che sì!\n"
	.string "Li cambierò, lo farò di sì!\p"
	.string "Se mai mi servirà un consiglio,\n"
	.string "{PLAYER}, seguirò sempre la tua parola!$"

gText_ApprenticeWhichMonFirst12::
	.string "Yahoo, {PLAYER}!\n"
	.string "Come va?\p"
	.string "Cosa devo fare? Chiedo io?\n"
	.string "Uh-huh, ho qualcosa da chiedere!\l"
	.string "Mi ricevi?\l"
	.string "Mi ricevi!\p"
	.string "Devi decidere quale dei miei\n"
	.string "POKéMON va per primo!\l"
	.string "In lotta, intendo dire.$"

gText_ApprenticeMonFirstThanks12::
	.string "Il mio {STR_VAR_1}? Sì!\n"
	.string "Va bene, nessun problema!\p"
	.string "Beh, {PLAYER}, io devo girare il mondo,\n"
	.string "ma tu non dimenticarmi.\p"
	.string "Ci vediamo, amico intelligente!$"

gText_ApprenticeWhichMonFirst13::
	.string "…Uff…ahi… {PLAYER}{KUN}…\n"
	.string "Mi fa male lo stomaco all'improvviso…\p"
	.string "…Sta passando ora…\p"
	.string "Devo essermi ammalato a forza di\n"
	.string "scervellarmi su come disporre\l"
	.string "la mia banda di POKéMON.\p"
	.string "Quindi, vista la situazione,\n"
	.string "devi decidere tu per me.\p"
	.string "{PLAYER}{KUN}, quale dei miei POKéMON va\n"
	.string "per primo? Per vincere, intendo.$"

gText_ApprenticeMonFirstThanks13::
	.string "Hm, va bene.\n"
	.string "Il mio {STR_VAR_1} va per primo.\p"
	.string "Sistemerò la squadra così dopo\n"
	.string "cena.\p"
	.string "Spero di poterti chiedere\n"
	.string "ancora aiuto così.$"

gText_ApprenticeWhichMonFirst14::
	.string "Ehm… Uhm…\n"
	.string "{PLAYER}{KUN}?\p"
	.string "Ti prego, non guardarmi così.\n"
	.string "Mi fai sentire confuso.\p"
	.string "Uhm…\n"
	.string "Ho davvero bisogno del tuo consiglio.\p"
	.string "Mi imbarazza dirlo,\n"
	.string "ma ho scelto la mia squadra di 3 POKéMON.\l"
	.string "Però non so decidere l'ordine.\p"
	.string "Quale POKéMON mando per primo\n"
	.string "per sembrare almeno capace?$"

gText_ApprenticeMonFirstThanks14::
	.string "Oh… Ok!\n"
	.string "Inizio con il mio {STR_VAR_1}.\p"
	.string "Spero di dare il massimo senza\n"
	.string "agitarmi troppo.\p"
	.string "Grazie, {PLAYER}{KUN}.\n"
	.string "Se ci rivedremo, spero sarai\l"
	.string "altrettanto disponibile.$"

gText_ApprenticeWhichMonFirst15::
	.string "Hm? Tu sembri {PLAYER}{KUN}…\n"
	.string "Ma sei davvero tu?\l"
	.string "Forse sei un abile sosia?\p"
	.string "Oh, no, no, no, non temere!\n"
	.string "Se sei davvero {PLAYER}, ti prego\l"
	.string "dimentica la mia scortesia.\p"
	.string "Vorrei il tuo buon consiglio.\p"
	.string "Ho qui la mia squadra di POKéMON.\n"
	.string "Vorrei che mi dicessi quale\l"
	.string "deve andare per primo in lotta.$"

gText_ApprenticeMonFirstThanks15::
	.string "Il mio {STR_VAR_1}…\n"
	.string "Non mi stai prendendo in giro?\p"
	.string "Capisco. Se è così, va bene.\n"
	.string "Ti ringrazio del tempo che mi dedichi.\p"
	.string "Sono come mi vedi, ma darò\n"
	.string "il massimo.\p"
	.string "Ci rivedremo!$"

gText_ApprenticeWhichMon0::
	.string "Singhiozzo…\n"
	.string "Oh, {PLAYER}!\p"
	.string "Che tempismo perfetto!\n"
	.string "C'è una cosa che non riesco a decidere…\p"
	.string "Non so quale POKéMON dovrei\n"
	.string "usare.\p"
	.string "Non so scegliere tra i POKéMON\n"
	.string "{STR_VAR_1} e {STR_VAR_2}…\p"
	.string "{PLAYER}, quale pensi darà\n"
	.string "anche a me una possibilità di vincere?$"

gText_ApprenticeMonThanks0::
	.string "Singhiozzo… Ca… capito!\n"
	.string "Oh! Mi dispiace tanto!\l"
	.string "Sono così felice che piango…\p"
	.string "Farò del mio meglio per prenderne\n"
	.string "un {STR_VAR_1}!\p"
	.string "Grazie mille!$"

gText_ApprenticeWhichMon1::
	.string "Evvai! Sei {PLAYER}!\n"
	.string "Evvai, sei arrivato al momento giusto!\l"
	.string "Mi serve di nuovo il tuo consiglio!\p"
	.string "Ehm, sono confuso: uso il mio\n"
	.string "{STR_VAR_1} o {STR_VAR_2}…\p"
	.string "Quale pensi che dovrei allenare,\n"
	.string "{PLAYER}?$"

gText_ApprenticeMonThanks1::
	.string "Ah, quindi il mio {STR_VAR_1} è meglio!\n"
	.string "Va bene, farò così!\p"
	.string "Grazie per avermi insegnato!$"

gText_ApprenticeWhichMon2::
	.string "{PLAYER}, ciao!\n"
	.string "Ho una domanda da farti.\p"
	.string "Sono indeciso se allevare\n"
	.string "un {STR_VAR_1} o un {STR_VAR_2}.\p"
	.string "Quale POKéMON pensi che\n"
	.string "sia più forte?$"

gText_ApprenticeMonThanks2::
	.string "{STR_VAR_1} è la tua scelta?\n"
	.string "Okay, ho capito!\p"
	.string "Andrò a prendere un {STR_VAR_1} forte\n"
	.string "subito!\p"
	.string "Ci vediamo!$"

gText_ApprenticeWhichMon3::
	.string "Ciao, {PLAYER}…\p"
	.string "Ehm, avrai già dimenticato\n"
	.string "uno come me…\p"
	.string "…Ma non importa se puoi\n"
	.string "darmi un consiglio…\p"
	.string "Non so decidere quale tipo di\n"
	.string "POKéMON allevare…\p"
	.string "Ho ristretto il campo ai POKéMON\n"
	.string "{STR_VAR_1} e {STR_VAR_2}, ma poi\l"
	.string "mi sono bloccato…\p"
	.string "{PLAYER}, forse non ti va,\n"
	.string "ma decidi tu per me.$"

gText_ApprenticeMonThanks3::
	.string "Ma un {STR_VAR_1} selvatico mi darà\n"
	.string "retta?\p"
	.string "Ci proverò!\p"
	.string "Ma riuscirò a prenderne uno…\n"
	.string "No! Farò del mio meglio!\p"
	.string "Grazie!$"

gText_ApprenticeWhichMon4::
	.string "Oh, {PLAYER}{KUN}! Che bello vederti!\n"
	.string "Stavo per venire a cercarti!\p"
	.string "Puoi decidere che tipo di POKéMON\n"
	.string "dovrei usare?\p"
	.string "Per esempio…\n"
	.string "Che ne dici dei POKéMON {STR_VAR_1}\l"
	.string "e {STR_VAR_2}?\p"
	.string "Quale pensi che sarebbe\n"
	.string "meglio?$"

gText_ApprenticeMonThanks4::
	.string "{STR_VAR_1}? Fantastico!\p"
	.string "Sapendo che hai deciso tu,\n"
	.string "{PLAYER}{KUN}, non mi dispiacerà\l"
	.string "se perdo.\p"
	.string "Okay, ti chiederò ancora consigli.\n"
	.string "Ciao!$"

gText_ApprenticeWhichMon5::
	.string "Guarda chi si vede, {PLAYER}{KUN}! Come va?\n"
	.string "Sono di nuovo occupato come sempre!\p"
	.string "Voglio fare sul serio con i POKéMON,\n"
	.string "ma non riesco a decidere\l"
	.string "quale POKéMON usare.\p"
	.string "Sai che i {STR_VAR_1} sembrano forti?\n"
	.string "Ma i {STR_VAR_2} non si ignorano.\p"
	.string "{PLAYER}{KUN}, dammi un buon\n"
	.string "consiglio! Quale andrebbe bene per me?$"

gText_ApprenticeMonThanks5::
	.string "Okay, capito.\n"
	.string "Troverò il tempo e prenderò\l"
	.string "quel {STR_VAR_1} che mi hai consigliato.\p"
	.string "Sono felice di averti come maestro.\n"
	.string "Grazie! Ci vediamo!$"

gText_ApprenticeWhichMon6::
	.string "Oh!\n"
	.string "Evviva, sei {PLAYER}!\p"
	.string "Non ho perso tempo a vantarmi con\n"
	.string "gli amici di averti incontrato!\p"
	.string "Oggi ti chiedo di nuovo aiuto.\n"
	.string "Per te è facile!\p"
	.string "Rullo di tamburi!\n"
	.string "La mia domanda è…\p"
	.string "Se dovessi allevare un POKéMON,\n"
	.string "e le scelte fossero un {STR_VAR_1}\l"
	.string "o un {STR_VAR_2}, quale dovrei prendere?$"

gText_ApprenticeMonThanks6::
	.string "Ahhh!\n"
	.string "{STR_VAR_1}, dici!\l"
	.string "Grazie per la risposta fantastica!\p"
	.string "Direi che era tutto quello che\n"
	.string "volevo chiederti oggi.\p"
	.string "Ci vediamo qui, okay?\n"
	.string "Grazie!$"

gText_ApprenticeWhichMon7::
	.string "Oh, sei tu, {PLAYER}?\n"
	.string "Che gioia rivederti!\p"
	.string "Da quando sono tuo apprendista,\n"
	.string "la mia sicurezza è sbocciata.\p"
	.string "Credo di essere pronto ad allevare un\n"
	.string "POKéMON tutto mio!\p"
	.string "{PLAYER}, posso chiederti di scegliere\n"
	.string "quale POKéMON allevare?\p"
	.string "Le scelte sono i POKéMON\n"
	.string "{STR_VAR_1} o {STR_VAR_2}…\l"
	.string "Quale POKéMON fa per me?$"

gText_ApprenticeMonThanks7::
	.string "Un {STR_VAR_1}, allora!\n"
	.string "Ne troverò uno subito!\p"
	.string "Grazie, {PLAYER}.\n"
	.string "Spero di potermi affidare a te.\l"
	.string "Abbi cura di te!$"

gText_ApprenticeWhichMon8::
	.string "Ah! {PLAYER}! Ti ho rivisto!\n"
	.string "Sono… sono felicissimo!\p"
	.string "Oh-oh-oh, ci sono!\n"
	.string "Non devo perdere questa occasione!\p"
	.string "Posso chiederti un favore, {PLAYER}?\n"
	.string "Scegli un POKéMON per me!\p"
	.string "Decidi quale sarebbe meglio,\n"
	.string "{STR_VAR_1} o {STR_VAR_2}!$"

gText_ApprenticeMonThanks8::
	.string "Wow! Hai deciso per me!\n"
	.string "Un {STR_VAR_1} è quello che alleverò\l"
	.string "al meglio delle mie capacità.\p"
	.string "Spero vorrai insegnarmi\n"
	.string "ancora in futuro.$"

gText_ApprenticeWhichMon9::
	.string "Ehi, ehi!\n"
	.string "Mio mentore, {PLAYER}{KUN}!\p"
	.string "Ciao, ti cercavo\n"
	.string "per un altro tuo saggio consiglio!\p"
	.string "Quale POKéMON farebbe per me,\n"
	.string "uno {STR_VAR_1} o {STR_VAR_2}?\p"
	.string "Non essere timido.\n"
	.string "Dillo subito!$"

gText_ApprenticeMonThanks9::
	.string "Uh-huh, un {STR_VAR_1}!\n"
	.string "OK, tutto OK!\l"
	.string "Lo prendo in una BALL, tipo, slam!\p"
	.string "Va bene, grazie, come sempre!\n"
	.string "Adios!$"

gText_ApprenticeWhichMon10::
	.string "{PLAYER}{KUN}, ascolta! Grande notizia!\n"
	.string "Ho catturato un POKéMON miraggio!\p"
	.string "Certo che sto mentendo!\n"
	.string "Wahahaha!\p"
	.string "Questo però non è uno scherzo.\n"
	.string "Non sono molto bravo a catturare\l"
	.string "POKéMON.\p"
	.string "Allora, perché non decidi tu quale\n"
	.string "tipo di POKéMON dovrei catturare,\l"
	.string "maestro?\p"
	.string "Quale sarebbe meglio?\n"
	.string "{STR_VAR_1} o {STR_VAR_2}?$"

gText_ApprenticeMonThanks10::
	.string "Quindi hai scelto {STR_VAR_1}?\n"
	.string "Allora prendo l'altro tipo!\p"
	.string "Scherzavo!\n"
	.string "Seguirò il tuo insegnamento!\p"
	.string "Grazie, maestro!\n"
	.string "Continua a insegnarmi!$"

gText_ApprenticeWhichMon11::
	.string "A-H-O-Y!\n"
	.string "Che si legge ahoy!\p"
	.string "Il MARINAIO rapper sono io!\n"
	.string "Ti ricordi chi sono, vero?\p"
	.string "Oggi ho una domanda sui POKéMON\n"
	.string "che attende il tuo suggerimento!\p"
	.string "Ho la scelta tra questo\n"
	.string "{STR_VAR_1} e {STR_VAR_2}, vedi.\l"
	.string "Quale devo catturare per me?$"

gText_ApprenticeMonThanks11::
	.string "{STR_VAR_1}, dici, ehi, ehi!\n"
	.string "Vado subito a prenderne uno!\p"
	.string "Se avrò bisogno di consigli,\n"
	.string "{PLAYER}, ascolterò le tue parole!$"

gText_ApprenticeWhichMon12::
	.string "Oh, uau, ma sei {PLAYER}!\p"
	.string "Che faccio? Ti chiedo un consiglio?\n"
	.string "Perché no? Ti sto già parlando!\p"
	.string "È da tanto. Rompiamo\n"
	.string "il ghiaccio. Cerco anch'io un consiglio!\l"
	.string "Mi ricevi?\l"
	.string "Mi ricevi!\p"
	.string "Il mio POKéMON: quale uso?\n"
	.string "È {STR_VAR_1} o {STR_VAR_2}.\l"
	.string "Quale scegli?$"

gText_ApprenticeMonThanks12::
	.string "Se {STR_VAR_1} è il migliore,\n"
	.string "farò come dici!\p"
	.string "Beh, {PLAYER}, devo andare in giro,\n"
	.string "ma non dimenticarti di me.\p"
	.string "Ci vediamo, amico intelligente!$"

gText_ApprenticeWhichMon13::
	.string "Oh, ciao, {PLAYER}{KUN}…\n"
	.string "Ho un mal di testa terribile…\p"
	.string "Devo essermi preoccupato troppo del\n"
	.string "tipo di POKéMON da allenare.\p"
	.string "Quindi, vista la situazione,\n"
	.string "devi decidere tu per me.\p"
	.string "{PLAYER}{KUN}, se dovessi scegliere tra\n"
	.string "i POKéMON {STR_VAR_1} e\l"
	.string "{STR_VAR_2}, quale sarebbe?$"

gText_ApprenticeMonThanks13::
	.string "Hm, un {STR_VAR_1}, va bene.\n"
	.string "Ne cercherò uno quando sarò più bravo.\p"
	.string "Spero di poterti chiedere\n"
	.string "ancora aiuto così.$"

gText_ApprenticeWhichMon14::
	.string "Ehm… Uhm…\n"
	.string "{PLAYER}{KUN}…?\p"
	.string "Ti prego, non guardarmi così.\n"
	.string "Mi sto agitando…\l"
	.string "Io… ho bisogno del tuo consiglio.\p"
	.string "Sono molto imbarazzato, ma non riesco\n"
	.string "a decidere quale POKéMON usare.\p"
	.string "Se le scelte fossero {STR_VAR_1} o\n"
	.string "{STR_VAR_2}, quale sarebbe meglio?$"

gText_ApprenticeMonThanks14::
	.string "Oh… Okay!\n"
	.string "Farò del mio meglio con un {STR_VAR_1}.\p"
	.string "Spero di farcela senza\n"
	.string "agitarmi troppo.\p"
	.string "Grazie, {PLAYER}{KUN}.\n"
	.string "Se ci rivedremo, spero sarai\l"
	.string "gentile come ora.$"

gText_ApprenticeWhichMon15::
	.string "Hm? Tu sembri {PLAYER}{KUN}…\n"
	.string "Ma sei davvero tu?\p"
	.string "No, no, se sei tu, va bene.\n"
	.string "A proposito, vorrei ottenere\l"
	.string "un tuo consiglio.\p"
	.string "Riguarda il POKéMON che userò.\p"
	.string "Se le scelte sono i POKéMON\n"
	.string "{STR_VAR_1} e {STR_VAR_2}, quale\l"
	.string "è più degno di me?$"

gText_ApprenticeMonThanks15::
	.string "{STR_VAR_1}?\n"
	.string "Ne sei certo?\p"
	.string "Capisco. Se è così, va bene.\n"
	.string "Grazie del tuo tempo.\p"
	.string "Spero sia qualcosa che anch'io\n"
	.string "possa gestire con calma.\p"
	.string "Ci rivedremo!$"

gText_ApprenticeWhichMove0::
	.string "Uaaah! Oh, {PLAYER}!\n"
	.string "Singhiozzo… Hic…\p"
	.string "Ho un dilemma!\n"
	.string "Non so decidere una mossa per\l"
	.string "il mio {STR_VAR_1}…\p"
	.string "Ti prego, ti prego, {PLAYER}.\n"
	.string "Puoi decidere per me?\p"
	.string "Per il mio {STR_VAR_1}, quale mossa\n"
	.string "sarebbe meglio: {STR_VAR_2}\l"
	.string "o {STR_VAR_3}?$"

gText_ApprenticeMoveThanks0::
	.string "{STR_VAR_1}?\n"
	.string "Waaaaah!\p"
	.string "Oh! Mi dispiace, {PLAYER}!\n"
	.string "Sono così felice che tu abbia scelto\l"
	.string "la mossa, che piango…\p"
	.string "Singhiozzo…\n"
	.string "Grazie mille!$"

gText_ApprenticeWhichMove1::
	.string "Evvai! Ciao, {PLAYER}!\n"
	.string "Mi serve di nuovo il tuo consiglio!\p"
	.string "Voglio insegnare al mio {STR_VAR_1}\n"
	.string "una mossa forte.\p"
	.string "Mi piacciono entrambe le mosse\n"
	.string "{STR_VAR_2} e {STR_VAR_3}.\l"
	.string "Cosa mi consigli?$"

gText_ApprenticeMoveThanks1::
	.string "{STR_VAR_1} è meglio? Direi di sì!\n"
	.string "Okay, vada per quella!\p"
	.string "Se ci rivediamo, insegnami\n"
	.string "qualcos'altro, maestro!$"

gText_ApprenticeWhichMove2::
	.string "{PLAYER}, ciao!\n"
	.string "Riguarda il mio {STR_VAR_1}, ma sono\l"
	.string "preoccupato per le sue mosse.\p"
	.string "Vedi, sono le mosse {STR_VAR_2}\n"
	.string "e {STR_VAR_3}.\p"
	.string "Quale è più forte e meglio per\n"
	.string "il mio {STR_VAR_1}?$"

gText_ApprenticeMoveThanks2::
	.string "{STR_VAR_1} è la tua scelta?\n"
	.string "Okay, ho capito!\p"
	.string "Insegnerò {STR_VAR_1} ai\n"
	.string "miei POKéMON subito!\p"
	.string "Ci vediamo!$"

gText_ApprenticeWhichMove3::
	.string "Oohh, {PLAYER}…\n"
	.string "Sono un disastro, davvero!\p"
	.string "Ho deciso di allevare un POKéMON,\n"
	.string "ma ora non so nemmeno decidere quale\l"
	.string "mossa fargli imparare…\p"
	.string "So che per te non significa niente,\n"
	.string "{PLAYER}.\p"
	.string "Ma per me significa molto…\p"
	.string "Ti prego, {PLAYER}, potresti scegliere\n"
	.string "una mossa per il mio {STR_VAR_1}?\p"
	.string "Se potessi scegliere tra\n"
	.string "{STR_VAR_2} e {STR_VAR_3}…$"

gText_ApprenticeMoveThanks3::
	.string "Ho capito!\p"
	.string "Ma sarà disposto a imparare\n"
	.string "{STR_VAR_1}…\l"
	.string "No! Farò del mio meglio!\p"
	.string "Grazie!$"

gText_ApprenticeWhichMove4::
	.string "Oh, {PLAYER}{KUN}!\n"
	.string "Speravo proprio di vederti!\p"
	.string "Mi chiedevo quale mossa sarebbe\n"
	.string "adatta al mio {STR_VAR_1}.\p"
	.string "Non so decidere, puoi decidere\n"
	.string "tu per me?\p"
	.string "Per esempio… Che ne dici delle mosse\n"
	.string "{STR_VAR_2} e {STR_VAR_3}?\l"
	.string "Quale sarebbe meglio?$"

gText_ApprenticeMoveThanks4::
	.string "{STR_VAR_1}? Fantastico!\p"
	.string "Sapendo che hai deciso tu,\n"
	.string "{PLAYER}{KUN}, non mi dispiacerà\l"
	.string "se perdo.\p"
	.string "Okay, ti chiederò ancora consigli.\n"
	.string "Ciao!$"

gText_ApprenticeWhichMove5::
	.string "Come si può essere così impegnati?\n"
	.string "Ehi, ma sei {PLAYER}{KUN}!\l"
	.string "Come va?\p"
	.string "Da stamattina ho fatto\n"
	.string "jogging, nuoto e cucina!\p"
	.string "Non immagini quanto sia impegnato!\p"
	.string "Non riesco nemmeno a decidere che mossa\n"
	.string "deve imparare il mio {STR_VAR_1}!\p"
	.string "{STR_VAR_2} sembra buona, eh?\n"
	.string "Ma anche {STR_VAR_3} non è male.\p"
	.string "{PLAYER}{KUN}, dammi un buon consiglio!\n"
	.string "Quale mossa mi conviene?$"

gText_ApprenticeMoveThanks5::
	.string "Okay, capito.\n"
	.string "Farò spazio nei miei impegni e\l"
	.string "insegnerò quella mossa.\p"
	.string "Sono felice di averti come maestro.\n"
	.string "Grazie! Ci vediamo!$"

gText_ApprenticeWhichMove6::
	.string "Oh! Che fortuna!\n"
	.string "Ti ho rivisto, {PLAYER}!\l"
	.string "Oggi ti chiedo di nuovo aiuto.\p"
	.string "Rullo di tamburi!\n"
	.string "La mia domanda è…\p"
	.string "Per il mio {STR_VAR_1}, quale mossa\n"
	.string "è più adatta, {STR_VAR_2} o\l"
	.string "{STR_VAR_3}?$"

gText_ApprenticeMoveThanks6::
	.string "Ahhh!\n"
	.string "{STR_VAR_1}, dici!\l"
	.string "Grazie per la risposta fantastica!\p"
	.string "Direi che era tutto quello che\n"
	.string "volevo chiederti oggi.\p"
	.string "Ci vediamo qui, okay?\n"
	.string "Grazie!$"

gText_ApprenticeWhichMove7::
	.string "Oh, ciao, {PLAYER}.\n"
	.string "Spero tu stia bene?\p"
	.string "Devo di nuovo chiedere il tuo consiglio.\n"
	.string "Riguarda il mio caro {STR_VAR_1}.\p"
	.string "Quale sarebbe la mossa ideale per\n"
	.string "il mio adorato {STR_VAR_1}?\l"
	.string "{STR_VAR_2} o {STR_VAR_3}?$"

gText_ApprenticeMoveThanks7::
	.string "{STR_VAR_1}, allora!\n"
	.string "La insegnerò subito!\p"
	.string "Grazie, {PLAYER}.\n"
	.string "Spero di potermi affidare a te.\l"
	.string "Abbi cura di te!$"

gText_ApprenticeWhichMove8::
	.string "Ih! {PLAYER}! Ti ho rivisto!\n"
	.string "Io… sono felicissimo!\p"
	.string "Ogni volta che ho bisogno, ci sei\n"
	.string "sempre tu, {PLAYER}!\p"
	.string "Oggi voglio che mi consigli\n"
	.string "una mossa!\p"
	.string "Scegli una mossa per\n"
	.string "il mio {STR_VAR_1}!\p"
	.string "Quale mossa sarebbe meglio,\n"
	.string "{STR_VAR_2} o {STR_VAR_3}?$"

gText_ApprenticeMoveThanks8::
	.string "Oh-oh-oh! Grazie!\n"
	.string "{STR_VAR_1}, allora!\l"
	.string "Capito perfettamente!\p"
	.string "Spero vorrai insegnarmi\n"
	.string "ancora in futuro.$"

gText_ApprenticeWhichMove9::
	.string "Hola, {PLAYER}{KUN}, bueno!\n"
	.string "Oggi spero in altri tuoi\l"
	.string "saggi consigli!\p"
	.string "Qual è la mossa migliore per\n"
	.string "il mio {STR_VAR_1}?\p"
	.string "Deve farmi vincere\n"
	.string "proprio così!\p"
	.string "Sarebbe {STR_VAR_2}?\n"
	.string "O {STR_VAR_3}?$"

gText_ApprenticeMoveThanks9::
	.string "Uh-huh, {STR_VAR_1}!\n"
	.string "Sì, bueno!\l"
	.string "La insegno, tipo, ka-blam!\p"
	.string "Va bene, grazie, come sempre!\n"
	.string "Adios!$"

gText_ApprenticeWhichMove10::
	.string "{PLAYER}{KUN}, è assurdo!\p"
	.string "Il mio POKéMON!\n"
	.string "Ha imparato sei mosse!\p"
	.string "Certo che mento!\n"
	.string "Wahahaha!\p"
	.string "Però non è una bugia.\n"
	.string "Non sono bravo a scegliere le mosse\l"
	.string "per i miei POKéMON.\p"
	.string "Allora, decidi tu quale\n"
	.string "tipo di mossa insegnargli?\p"
	.string "{STR_VAR_2} o {STR_VAR_3}: quale\n"
	.string "andrebbe meglio per il mio {STR_VAR_1}?$"

gText_ApprenticeMoveThanks10::
	.string "Quindi hai scelto {STR_VAR_1}?\n"
	.string "Allora scelgo un'altra mossa!\p"
	.string "Scherzavo!\n"
	.string "Seguirò il tuo insegnamento!\p"
	.string "Grazie, maestro!\n"
	.string "Continua a insegnarmi!$"

gText_ApprenticeWhichMove11::
	.string "A-H-O-Y!\n"
	.string "E questo fa ahoy!\p"
	.string "Il MARINAIO rapper sono io!\n"
	.string "Ci sono sempre, non chiedermi perché.\p"
	.string "Oggi ho una domanda su una mossa\n"
	.string "che attende il tuo suggerimento!\p"
	.string "{STR_VAR_2} e {STR_VAR_3} sono\n"
	.string "le mosse. Quale sarebbe la migliore\l"
	.string "per il mio {STR_VAR_1}, così va a ritmo?$"

gText_ApprenticeMoveThanks11::
	.string "{STR_VAR_1}, dici, ehi, ehi!\n"
	.string "Vado subito a insegnarla!\p"
	.string "Se avrò bisogno di consigli,\n"
	.string "{PLAYER}, ascolterò le tue parole!$"

gText_ApprenticeWhichMove12::
	.string "Oh, ehi, guarda chi c'è, {PLAYER}!\p"
	.string "Cosa devo fare? Chiederti un consiglio?\n"
	.string "Perché no? Ti sto già parlando!\p"
	.string "{PLAYER}, ti sorprendo?\n"
	.string "Voglio il tuo consiglio, non lo vedi?\p"
	.string "Mi ricevi?\n"
	.string "Mi ricevi!\p"
	.string "Il mio {STR_VAR_1}: cosa deve usare?\n"
	.string "È {STR_VAR_2} o {STR_VAR_3},\l"
	.string "cosa scegli?$"

gText_ApprenticeMoveThanks12::
	.string "Se {STR_VAR_1} è il migliore,\n"
	.string "farò come dici!\p"
	.string "Beh, {PLAYER}, devo andare in giro,\n"
	.string "ma non dimenticarti di me.\p"
	.string "Ci vediamo, amico intelligente!$"

gText_ApprenticeWhichMove13::
	.string "Gahack! Gaah! Oh, {PLAYER}{KUN}…\n"
	.string "Ho questo brutto raffreddore…\p"
	.string "Voglio scegliere una mossa per il mio\n"
	.string "POKéMON, ma non ci riesco…\p"
	.string "Quindi, visto come stanno le cose,\n"
	.string "devi decidere tu per me.\p"
	.string "{PLAYER}{KUN}, se dovessi scegliere tra\n"
	.string "{STR_VAR_2} e {STR_VAR_3} per\l"
	.string "il mio {STR_VAR_1}, quale sarebbe?$"

gText_ApprenticeMoveThanks13::
	.string "Hm, {STR_VAR_1}, va bene. Tosse!\n"
	.string "La insegnerò quando sarò più bravo.\p"
	.string "Spero di poterti chiedere\n"
	.string "ancora aiuto così.$"

gText_ApprenticeWhichMove14::
	.string "Ehm… Uhm…\n"
	.string "{PLAYER}{KUN}…?\p"
	.string "Ti prego, non guardarmi così.\n"
	.string "Mi sto confondendo…\l"
	.string "Io… ho bisogno del tuo consiglio.\p"
	.string "Io… sono molto imbarazzato, ma non so\n"
	.string "decidere quale mossa insegnare\l"
	.string "al mio POKéMON.\p"
	.string "È per il mio {STR_VAR_1}.\n"
	.string "Se le scelte fossero {STR_VAR_2} o\l"
	.string "{STR_VAR_3}, quale sarebbe meglio?$"

gText_ApprenticeMoveThanks14::
	.string "Oh… Okay!\n"
	.string "Proverò {STR_VAR_1}.\p"
	.string "Spero di riuscire a insegnarla…\n"
	.string "Che ansia…\p"
	.string "Grazie, {PLAYER}{KUN}.\n"
	.string "Se ci rivedremo, spero sarai\l"
	.string "gentile come ora.$"

gText_ApprenticeWhichMove15::
	.string "Hm? Tu sembri {PLAYER}{KUN}…\n"
	.string "Ma sei davvero tu?\p"
	.string "Forse sei uno di quei sosia\n"
	.string "in voga?\p"
	.string "No, no, se sei tu, va bene.\n"
	.string "Non serve arrabbiarsi, te lo assicuro!\p"
	.string "A proposito, vorrei ottenere\n"
	.string "un tuo consiglio.\p"
	.string "Riguarda il mio {STR_VAR_1}.\p"
	.string "Quale mossa sarebbe meglio che\n"
	.string "usasse, {STR_VAR_2} o {STR_VAR_3}?$"

gText_ApprenticeMoveThanks15::
	.string "{STR_VAR_1}?\n"
	.string "Non c'è dubbio?\p"
	.string "Capisco. Se è così, va bene.\n"
	.string "Grazie del tuo tempo.\p"
	.string "Spero sia qualcosa che anche\n"
	.string "i miei POKéMON possano imparare.\p"
	.string "Ci rivedremo!$"

gText_ApprenticePickWinSpeech0::
	.string "Oh… {PLAYER}?\n"
	.string "Sei {PLAYER}!\l"
	.string "Oh! Singhiozzo… Ascolta!\p"
	.string "Io… Quando lotto, mi agito così tanto\n"
	.string "che piango anche se vinco…\p"
	.string "Vorrei dire qualcosa di forte\n"
	.string "quando vinco…\p"
	.string "Ti prego, {PLAYER}!\n"
	.string "Potresti insegnarmi qualcosa\l"
	.string "da dire quando vinco senza piangere?$"

gText_ApprenticeWinSpeechThanks0::
	.string "{STR_VAR_1}\p"
	.string "Fantastico! Che urlo!\n"
	.string "È davvero forte!\p"
	.string "Oh… scusa…\n"
	.string "Sono così felice che piango…\p"
	.string "Singhiozzo… {PLAYER}!\n"
	.string "Grazie di cuore per tutto!\p"
	.string "Combatterò al meglio per\n"
	.string "te, {PLAYER}!\p"
	.string "{PLAYER}…\n"
	.string "La prossima volta… lottiamo!$"

gText_ApprenticePickWinSpeech1::
	.string "Evviva! Sei {PLAYER}! Ciao!\n"
	.string "Volevo chiederti una cosa!\p"
	.string "Voglio dire qualcosa di forte quando\n"
	.string "vinco una lotta.\p"
	.string "Hai una frase forte che\n"
	.string "mi consiglieresti?$"

gText_ApprenticeWinSpeechThanks1::
	.string "{STR_VAR_1}\p"
	.string "Oh, wow! Che forte!\n"
	.string "Ok, lo dirò!\p"
	.string "Grazie per avermi insegnato tanto!\n"
	.string "Darò il meglio\l"
	.string "ovunque andrò!\p"
	.string "Alla prossima sarà\n"
	.string "una lotta!$"

gText_ApprenticePickWinSpeech2::
	.string "{PLAYER}, ciao!\p"
	.string "Io e i miei POKéMON siamo pronti a\n"
	.string "tutto, tranne che a una cosa.\p"
	.string "Penso che sarebbe bello avere\n"
	.string "qualcosa da gridare quando vinco.\p"
	.string "Potresti inventare qualcosa\n"
	.string "da dire?$"

gText_ApprenticeWinSpeechThanks2::
	.string "{STR_VAR_1}\p"
	.string "…Forte!\n"
	.string "Userò quella!\p"
	.string "Andrò in giro a lottare\n"
	.string "ovunque.\p"
	.string "Chissà, magari un giorno lotterò\n"
	.string "con te, {PLAYER}.\p"
	.string "La prossima volta, vediamoci in un\n"
	.string "luogo di lotta!$"

gText_ApprenticePickWinSpeech3::
	.string "Ciao, {PLAYER}…\n"
	.string "Scusa il disturbo, ma sono un disastro…\p"
	.string "Anche quando…\n"
	.string "Anche quando vinco, non ho niente\l"
	.string "di speciale da dire…\p"
	.string "So che per te non significa nulla,\n"
	.string "{PLAYER}.\p"
	.string "Ma per me significa molto…\p"
	.string "Ti prego, {PLAYER}, cosa devo dire\n"
	.string "se vinco una lotta?$"

gText_ApprenticeWinSpeechThanks3::
	.string "{STR_VAR_1}\p"
	.string "È ispirato…\p"
	.string "Uh… va bene se uno come me\n"
	.string "lo dice?\p"
	.string "No! Darò il meglio!\p"
	.string "{PLAYER}, grazie mille per\n"
	.string "avermi sopportato così a lungo…\p"
	.string "Prometto che darò il meglio d'ora in poi.\p"
	.string "So che ti dimenticherai presto di\n"
	.string "uno come me, ma rivediamoci\l"
	.string "da qualche parte!$"

gText_ApprenticePickWinSpeech4::
	.string "Oh, {PLAYER}{KUN}.\n"
	.string "C'è una cosa che vuoi farti dire.\p"
	.string "So che non sembro sempre\n"
	.string "gentile o educato…\p"
	.string "Quando vinco una lotta, credo di\n"
	.string "sembrare arrogante.\p"
	.string "Non voglio che la gente mi odi,\n"
	.string "quindi voglio dire qualcosa di gentile\l"
	.string "a chi batto.\p"
	.string "Ma non mi viene in mente nulla!\n"
	.string "Potresti inventarlo tu?$"

gText_ApprenticeWinSpeechThanks4::
	.string "{STR_VAR_1}\p"
	.string "Niente male!\n"
	.string "Sì, userò proprio quella!\p"
	.string "Partirò e farò ciò\n"
	.string "che posso con ciò che mi hai insegnato\l"
	.string "nel cuore e nella mente.\p"
	.string "Scusa se sono stato insistente\n"
	.string "con te!\p"
	.string "La prossima volta, lottiamo, ok?\n"
	.string "Ci vediamo!$"

gText_ApprenticePickWinSpeech5::
	.string "Oh, sono sempre indaffarato!\n"
	.string "Oh, ciao, ti cercavo, {PLAYER}{KUN}.\p"
	.string "Tutto bene come sempre?\n"
	.string "Per me nulla è cambiato.\p"
	.string "Devo correre, lottare e mappare.\n"
	.string "Perché sono così impegnato?\p"
	.string "Ma anche impegnato, sarebbe sgarbato\n"
	.string "girare i tacchi e andarmene\l"
	.string "dopo una vittoria senza dir nulla.\p"
	.string "Allora, che frase dire per\n"
	.string "sottolineare quanto sono forte\l"
	.string "mentre me ne vado? {PLAYER}{KUN}, aiutami!$"

gText_ApprenticeWinSpeechThanks5::
	.string "{STR_VAR_1}\p"
	.string "Ok, capito.\n"
	.string "Troverò il tempo per dirlo!\p"
	.string "Sono davvero felice di aver trovato\n"
	.string "un bravo mentore come te.\p"
	.string "Troverò il tempo in qualche modo\n"
	.string "per dedicarmi alle lotte.\p"
	.string "Grazie di tutto, {PLAYER}{KUN}!\n"
	.string "Dobbiamo lottare insieme, un giorno!$"

gText_ApprenticePickWinSpeech6::
	.string "Ho avuto di nuovo fortuna!\n"
	.string "{PLAYER}! Che bello vederti!\l"
	.string "Come sempre, mi serve il tuo consiglio!\p"
	.string "Rullo di tamburi, prego!\n"
	.string "L'ultima domanda che ho è…\p"
	.string "Se vinco una battaglia e voglio finire\n"
	.string "con una bella mossa, cosa\l"
	.string "dovrei dire?$"

gText_ApprenticeWinSpeechThanks6::
	.string "{STR_VAR_1}\p"
	.string "Quella… è favolosa!\n"
	.string "È dignitosa e forte! La prendo!\p"
	.string "…Senti, credo di stare diventando\n"
	.string "bravo, eh?\p"
	.string "Quindi penso di sfidare altri\n"
	.string "ALLENATORI d'ora in poi.\p"
	.string "{PLAYER}, i tuoi consigli mi hanno aiutato molto.\p"
	.string "Magari un giorno arriverà il momento\n"
	.string "in cui lotteremo!\p"
	.string "Grazie di tutto!$"

gText_ApprenticePickWinSpeech7::
	.string "Oh, {PLAYER}.\n"
	.string "Sono così felice di averti incontrato!\p"
	.string "Non ho più dubbi\n"
	.string "riguardo ai miei POKéMON.\p"
	.string "È me stesso che mi preoccupa…\p"
	.string "Sai come un ALLENATORE dice\n"
	.string "qualcosa quando vince una battaglia?\p"
	.string "Davvero, vorrei poterlo fare\n"
	.string "anche io!\p"
	.string "Per favore, cosa dovrei dire quando\n"
	.string "vinco una battaglia?$"

gText_ApprenticeWinSpeechThanks7::
	.string "{STR_VAR_1}\p"
	.string "Ah! Quel detto! Mi rinfresca\n"
	.string "e mi fa sentire rinato!\p"
	.string "Devo usarlo subito!\p"
	.string "E ora devo andare,\n"
	.string "{PLAYER}…\p"
	.string "Andrò a lottare contro molti altri,\n"
	.string "ma mai dimenticherò i tuoi insegnamenti.\p"
	.string "Forse un giorno…\n"
	.string "Addio!$"

gText_ApprenticePickWinSpeech8::
	.string "Ah! Ho visto {PLAYER}!\n"
	.string "Sono… sono felicissimo di vederti!\p"
	.string "Oh-oh-oh! Devo proprio\n"
	.string "chiederti una cosa!\p"
	.string "Poco fa ho vinto una lotta.\n"
	.string "Che emozione!\p"
	.string "Ma ero così felice che\n"
	.string "mi sono commosso e non ho detto nulla!\p"
	.string "Ora, {PLAYER}, ti prego, voglio che\n"
	.string "pensi a una frase d'addio per le vittorie!$"

gText_ApprenticeWinSpeechThanks8::
	.string "{STR_VAR_1}\p"
	.string "Waaaaah!\n"
	.string "Dovrò dire quella?!\l"
	.string "Io… sono fuori di gioia!\p"
	.string "G-g-grazie!\n"
	.string "Non ho più nulla da rimpiangere!\p"
	.string "Ora viaggerò e lotterò\n"
	.string "con tanti tipi di persone.\p"
	.string "Tutto, lo devo a te, {PLAYER}.\n"
	.string "Davvero, davvero, grazie!\p"
	.string "Ora devo andare, ma vediamoci\n"
	.string "in lotta un giorno!$"

gText_ApprenticePickWinSpeech9::
	.string "Hola, bueno!\n"
	.string "{PLAYER}{KUN}!\p"
	.string "Sai, mi prudono le mani, voglio vagare\n"
	.string "e lottare dove capita.\p"
	.string "Ma prima, voglio il tuo consiglio\n"
	.string "ancora una volta, per favore!\p"
	.string "Se vincessi una battaglia, quale\n"
	.string "sarebbe un bel vanto da dire al mio\l"
	.string "avversario ALLENATORE caduto?$"

gText_ApprenticeWinSpeechThanks9::
	.string "{STR_VAR_1}\p"
	.string "Uh-huh, che dolce!\n"
	.string "Si, bueno!\l"
	.string "Proverò a dirlo, tipo, ham!\p"
	.string "E ora è ora di salutarsi!\n"
	.string "Grazie per un sacco di cose!\p"
	.string "Fammi fare una lotta un giorno, ok?\n"
	.string "Adios!$"

gText_ApprenticePickWinSpeech10::
	.string "{PLAYER}{KUN}, è un guaio grosso!\p"
	.string "Quando vinco, me ne vanto\n"
	.string "per almeno un'ora!\p"
	.string "Certo che mento!\n"
	.string "Wahahaha!\p"
	.string "Ma questo non è una bugia.\n"
	.string "Non sono bravo a parlare.\p"
	.string "Allora, decidi tu cosa devo dire\n"
	.string "dopo aver vinto una lotta,\l"
	.string "maestro?$"

gText_ApprenticeWinSpeechThanks10::
	.string "{STR_VAR_1}\p"
	.string "È quello che dovrei dire, eh?\n"
	.string "Allora me ne terrò alla larga!\p"
	.string "Scherzo!\n"
	.string "Seguirò i tuoi insegnamenti, maestro!\p"
	.string "Grazie per avermi insegnato tanto,\n"
	.string "maestro!\p"
	.string "Finalmente capisco cosa significa\n"
	.string "essere un ALLENATORE.\p"
	.string "Andrò in giro a vincere lotte\n"
	.string "contro ogni ALLENATORE.\p"
	.string "Magari un giorno toccherà a te, maestro!\p"
	.string "È tutto!\n"
	.string "Addio, maestro mio!$"

gText_ApprenticePickWinSpeech11::
	.string "A-H-O-Y!\n"
	.string "E questo si legge ahoy!\p"
	.string "Il MARINAIO rapper sono io!\n"
	.string "Sarà la mia ultima domanda,\l"
	.string "non piangere!\p"
	.string "È una domanda su una frase\n"
	.string "che chiede il tuo consiglio!\p"
	.string "Se vinco una lotta, cosa posso dire\n"
	.string "in modo davvero forte?$"

gText_ApprenticeWinSpeechThanks11::
	.string "{STR_VAR_1}\p"
	.string "Perfetto! Userò quello.\n"
	.string "Ho fatto bene a farti scegliere!\p"
	.string "E ora credo sia meglio\n"
	.string "volare via dal nido!\p"
	.string "Grazie per tutto ciò che mi hai insegnato.\n"
	.string "Parto per una serie di lotte!\p"
	.string "B-O-N-V-O-Y-A-G-E!\n"
	.string "E questo significa buon viaggio,\l"
	.string "per te è il mio omaggio!$"

gText_ApprenticePickWinSpeech12::
	.string "Oh, sì, {PLAYER}!\n"
	.string "Ti ho trovato di nuovo oggi!\p"
	.string "Cosa faccio? Ti chiedo ancora?\n"
	.string "Perché no? Ti sto già chiedendo!\p"
	.string "Comunque, {PLAYER}…\n"
	.string "Mi ricevi?\l"
	.string "Mi ricevi!\l"
	.string "Mi serve ancora un consiglio!\p"
	.string "Riguarda cosa dovrei gridare.\n"
	.string "Qualcosa di forte da urlare quando\l"
	.string "una lotta finisce bene.\p"
	.string "Dai, voglio sentirtelo dire!$"

gText_ApprenticeWinSpeechThanks12::
	.string "{STR_VAR_1}\p"
	.string "Bene, bene!\n"
	.string "La userò, è troppo forte!\p"
	.string "Non ho più nulla da chiederti.\n"
	.string "Resta solo di salutarti.\p"
	.string "Ma forse un giorno ci rivedremo,\n"
	.string "con uno destinato a perdere.\p"
	.string "Ma è davvero ora di salutarci.\p"
	.string "Beh, {PLAYER}, io girerò il mondo,\n"
	.string "ma tu non dimenticarmi!\p"
	.string "Abbi cura di te, {PLAYER}!\n"
	.string "Ti voglio bene!$"

gText_ApprenticePickWinSpeech13::
	.string "{PLAYER}{KUN}, ho finito…\n"
	.string "Il naso non smette di gocciolare…\p"
	.string "Cercavo di inventare qualcosa\n"
	.string "di forte da dire quando vinco.\p"
	.string "Mi ha ispirato tanto che ho pianto,\n"
	.string "e ora il naso non smette…\p"
	.string "Quindi, visto così,\n"
	.string "devi decidere tu, {PLAYER}{KUN}.\p"
	.string "Quando vinco una lotta,\n"
	.string "cosa devo dire?$"

gText_ApprenticeWinSpeechThanks13::
	.string "{STR_VAR_1}\p"
	.string "… … …Che bello.\n"
	.string "No, è da brividi!\l"
	.string "Mi fa venire le lacrime agli occhi!\p"
	.string "Ma nonostante le lacrime e il\n"
	.string "naso che cola, userò quella frase!\p"
	.string "Non ho più nulla da chiederti,\n"
	.string "{PLAYER}{KUN}.\p"
	.string "Da ora siamo rivali!\n"
	.string "Grazie di tutto!$"

gText_ApprenticePickWinSpeech14::
	.string "Ehm… Uhm…\n"
	.string "{PLAYER}{KUN}…\p"
	.string "Ti prego, non guardarmi così.\n"
	.string "Mi fai agitare.\p"
	.string "Io… Mi serve di nuovo il tuo aiuto.\n"
	.string "Sarà l'ultima volta, però…\p"
	.string "È davvero imbarazzante chiedere,\n"
	.string "ma se vinco una lotta?\l"
	.string "Cosa devo dire?$"

gText_ApprenticeWinSpeechThanks14::
	.string "{STR_VAR_1}\p"
	.string "Oh… ok!\n"
	.string "Proverò a dirlo!\l"
	.string "Magari sarò troppo nervoso per dirlo…\p"
	.string "Grazie, {PLAYER}{KUN}.\n"
	.string "Ora devo salutarti.\p"
	.string "Seguirò tutto ciò che mi hai insegnato,\n"
	.string "{PLAYER}{KUN}, e darò il meglio.$"

gText_ApprenticePickWinSpeech15::
	.string "Hm? Sembri {PLAYER}{KUN}…\n"
	.string "Ma lo sei davvero?\l"
	.string "Forse un abile {PLAYER} DOLL?\p"
	.string "Oh, no, no, no, non preoccuparti!\n"
	.string "Se sei davvero tu, ti prego\l"
	.string "dimentica la mia scortesia.\p"
	.string "Non arrabbiarti. Desidero solo\n"
	.string "ancora i tuoi ottimi consigli.\p"
	.string "Riguarda una frase.\p"
	.string "Più precisamente, cosa devo dire\n"
	.string "se vinco una lotta?$"

gText_ApprenticeWinSpeechThanks15::
	.string "{STR_VAR_1}\p"
	.string "… … … … … …\n"
	.string "Quando vinco una lotta…\p"
	.string "{STR_VAR_1}\p"
	.string "…Dici sul serio?\p"
	.string "Capisco. Se dici sul serio, va bene.\n"
	.string "Ti ringrazio del tempo che mi hai dato.\p"
	.string "Spero che anch'io saprò\n"
	.string "usare bene quella frase.\p"
	.string "Mi pare di aver finito i consigli\n"
	.string "che mi servono.\p"
	.string "Credo sia ora di salutarti\n"
	.string "e partire per conto mio.\p"
	.string "Grazie, mio mentore!\n"
	.string "Chiedo scusa per il mio scetticismo!$"
