
#if IS_HNS
FallarborTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Ti do il benvenuto alla TENDA LOTTA!\p"
	.string "Sono la guida al Torneo KO a squadre!$"
#else
FallarborTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "I welcome you to the BATTLE TENT\n"
	.string "FALLARBOR SITE!\p"
	.string "I am your guide to the Set KO Tourney!$"
#endif

FallarborTown_BattleTentLobby_Text_TakeChallenge:
	.string "Ora, vuoi accettare la sfida\n"
	.string "del Torneo KO a squadre?$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge:
	.string "Ti aspettiamo di nuovo\n"
	.string "per una sfida!$"

FallarborTown_BattleTentLobby_Text_ExplainFallarborTent:
#if IS_HNS
	.string "Nel TENDALOTTA ARENA\n"
#else
	.string "In the FALLARBOR BATTLE TENT,\n"
#endif
	.string "si tiene il Torneo KO a squadre.\p"
	.string "Tutti i partecipanti gareggiano con\n"
	.string "tre POKéMON.\p"
	.string "I tre POKéMON vanno schierati\n"
	.string "nell'ordine in cui entreranno.\p"
	.string "Durante la lotta appariranno\n"
	.string "uno alla volta, nell'ordine stabilito.\p"
	.string "Un POKéMON entrato in lotta deve\n"
	.string "restare fino alla decisione del match.\p"
	.string "Se un match resta indeciso\n"
	.string "dopo tre turni, si va ai punti.\p"
	.string "Se vuoi interrompere la sfida,\n"
	.string "salva il gioco.\p"
	.string "Se non salvi, non potrai\n"
	.string "continuare la sfida.\p"
	.string "Se riesci a battere\n"
	.string "tre ALLENATORI di fila,\l"
	.string "ti daremo un bel premio.$"

FallarborTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Prima di condurti alla TENDA\n"
	.string "LOTTA, devo salvare. Va bene?$"

@ Unused
FallarborTown_BattleTentLobby_Text_WhichLevelMode:
	.string "Offriamo due livelli di sfida,\n"
	.string "Livello 50 e Livello Libero.\l"
	.string "Quale scegli?$"

FallarborTown_BattleTentLobby_Text_SelectThreeMons:
	.string "Bene, ora scegli pure\n"
	.string "i tuoi tre POKéMON.$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "Mio caro sfidante!\p"
	.string "Non hai i tre POKéMON\n"
	.string "richiesti per l'iscrizione.\p"
	.string "Inoltre non devono tenere gli stessi\n"
	.string "tipi di oggetti.\p"
	.string "Le UOVA{STR_VAR_1} non valide.\p"
	.string "Quando avrai fatto i preparativi,\n"
	.string "torna pure.$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "Mio caro sfidante!\p"
	.string "Non hai i tre POKéMON\n"
	.string "richiesti per l'iscrizione.\p"
	.string "Per qualificarti, devi portare tre\n"
	.string "tipi diversi di POKéMON.\p"
	.string "Inoltre non devono tenere gli stessi\n"
	.string "tipi di oggetti.\p"
	.string "Le UOVA{STR_VAR_1} non valide.\p"
	.string "Quando avrai fatto i preparativi,\n"
	.string "torna pure.$"

FallarborTown_BattleTentLobby_Text_GuideYouToBattleTent:
	.string "Ora ti condurrò alla\n"
	.string "TENDA LOTTA.$"

FallarborTown_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "Mio caro sfidante!\p"
	.string "Non hai salvato prima\n"
	.string "di spegnere, vero?\p"
	.string "Purtroppo questo comporta\n"
	.string "la tua squalifica\l"
	.string "dalla sfida.\p"
	.string "Puoi ricominciare\n"
	.string "da capo.$"

FallarborTown_BattleTentLobby_Text_BeatThreeTrainers:
	.string "Che splendido! Hai battuto\n"
	.string "tre ALLENATORI di fila!$"

FallarborTown_BattleTentLobby_Text_WaitWhileSaveGame:
	.string "Attendi mentre salvo il gioco.$"

FallarborTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "In ricordo della tua serie di 3 vittorie,\n"
	.string "ti diamo questo premio.$"

FallarborTown_BattleTentLobby_Text_ReceivedPrize:
	.string "{PLAYER} ha ottenuto\n"
	.string "{STR_VAR_1}.$"

FallarborTown_BattleTentLobby_Text_BagFullReturnForPrize:
	.string "Oh?\n"
	.string "La tua BORSA è piena.\p"
	.string "Fai spazio e torna\n"
	.string "a ritirare il premio.$"

FallarborTown_BattleTentLobby_Text_ThankYouWaitWhileSaving:
	.string "Grazie per la partecipazione!\p"
	.string "Attendi mentre salvo il gioco.$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge2:
	.string "Ti aspettiamo di nuovo\n"
	.string "per una sfida!$"

FallarborTown_BattleTentLobby_Text_LookingForwardToArrival:
	.string "Non vedevamo l'ora del\n"
	.string "tuo arrivo.\p"
	.string "Prima di condurti alla TENDA LOTTA,\n"
	.string "devo salvare. Attendi.$"

#if IS_HNS
VerdanturfTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Ti do il benvenuto al TENDONE LOTTA!\p"
	.string "Qui si mette alla prova la fiducia\n"
	.string "dell'ALLENATORE nei POKéMON.$"
#else
VerdanturfTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "I welcome you to the BATTLE TENT\n"
	.string "VERDANTURF SITE!\p"
	.string "Here, the TRAINER's trust toward\n"
	.string "POKéMON is tested.$"
#endif
VerdanturfTown_BattleTentLobby_Text_TakeChallenge:
#if IS_HNS
	.string "Vuoi accettare la sfida del TENDONE\n"
#else
	.string "Do you wish to take the VERDANTURF\n"
#endif
	.string "LOTTA PALACE?$"

VerdanturfTown_BattleTentLobby_Text_ExplainVerdanturfTent:
#if IS_HNS
	.string "Nel TENDONE LOTTA PALACE,\n"
#else
	.string "In the VERDANTURF BATTLE TENT,\n"
#endif
	.string "c'è una regola cruciale da\l"
	.string "rispettare.\p"
	.string "Gli ALLENATORI possono solo scambiare\n"
	.string "i loro POKéMON.\p"
	.string "Non possono altrimenti dare ordini\n"
	.string "ai loro POKéMON.\p"
	.string "I POKéMON agiscono secondo\n"
	.string "la loro natura e lottano da soli.\p"
	.string "Devi riporre fiducia nei tuoi\n"
	.string "POKéMON e vegliare su di loro.\p"
	.string "Se batti tre ALLENATORI\n"
	.string "di fila in successione,\l"
	.string "ti daremo un premio.\p"
	.string "Se vuoi interrompere la tua\n"
	.string "sfida, salva il gioco.\p"
	.string "Se non salvi prima di interrompere,\n"
	.string "verrai squalificato.$"

VerdanturfTown_BattleTentLobby_Text_ReturnFortified:
	.string "Quando hai rafforzato il cuore\n"
	.string "e i POKéMON, devi tornare.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_WhichLevelMode:
	.string "Ci sono due livelli di difficoltà,\n"
	.string "Livello 50 e Livello Libero.\l"
	.string "Quale sfida scegli?$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "Sigh…\p"
	.string "Non hai i tre POKéMON\n"
	.string "richiesti per la sfida.\p"
	.string "Per partecipare, devi fornire tre\n"
	.string "tipi diversi di POKéMON.\p"
	.string "Inoltre non devono tenere\n"
	.string "lo stesso tipo di oggetti.\p"
	.string "Le UOVA{STR_VAR_1} non valgono.\p"
	.string "Torna quando hai fatto\n"
	.string "i tuoi preparativi.$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "Sigh…\p"
	.string "Non hai i tre POKéMON\n"
	.string "richiesti per la sfida.\p"
	.string "Per partecipare, devi fornire tre\n"
	.string "tipi diversi di POKéMON.\p"
	.string "Inoltre non devono tenere\n"
	.string "lo stesso tipo di oggetti.\p"
	.string "Le UOVA{STR_VAR_1} non valgono.\p"
	.string "Torna quando hai fatto\n"
	.string "i tuoi preparativi.$"

VerdanturfTown_BattleTentLobby_Text_SelectThreeMons:
	.string "Bene. Ora scegli i tuoi\n"
	.string "tre POKéMON.$"

VerdanturfTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Devo salvare prima di portarti\n"
	.string "al TENDONE LOTTA. Va bene?$"

VerdanturfTown_BattleTentLobby_Text_NowFollowMe:
	.string "Bene.\n"
	.string "Ora seguimi.$"

VerdanturfTown_BattleTentLobby_Text_ResultsWillBeRecorded:
	.string "È stato un onore vedere le\n"
	.string "gesta dei tuoi POKéMON.\p"
	.string "I risultati saranno registrati.\n"
	.string "Ti chiedo di aspettare un attimo.$"

VerdanturfTown_BattleTentLobby_Text_AchievedThreeWinStreak:
	.string "Per fare 3 vittorie di fila…\p"
	.string "Il legame che unisce il tuo cuore ai\n"
	.string "tuoi POKéMON sembra saldo e puro.$"

VerdanturfTown_BattleTentLobby_Text_FeatWillBeRecorded:
	.string "La tua impresa sarà registrata.\n"
	.string "Ti chiedo di aspettare un attimo.$"

VerdanturfTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "Per l'impresa delle tue 3 vittorie di fila,\n"
	.string "ti diamo questo premio.$"


#if IS_HNS
SlateportCity_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Benvenuto alla TENDA LOTTA!\p"
	.string "Sono la guida al Torneo\n"
	.string "Scambio Lotta.$"
#else
SlateportCity_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Welcome to the BATTLE TENT\n"
	.string "SLATEPORT SITE!\p"
	.string "I am your guide to the Battle Swap\n"
	.string "Tournament.$"
#endif


SlateportCity_BattleTentLobby_Text_TakeChallenge:
	.string "Vuoi accettare la sfida\n"
	.string "Scambio Lotta?$"

SlateportCity_BattleTentLobby_Text_ExplainSlateportTent:
#if IS_HNS
	.string "Qui alla TENDA LOTTA FABBRICA,\n"
#else
	.string "Here at the SLATEPORT BATTLE TENT,\n"
#endif
	.string "teniamo eventi Scambio Lotta\l"
	.string "con POKéMON a noleggio.\p"
	.string "Prima ti verranno prestati tre\n"
	.string "POKéMON appositamente per l'evento.\p"
	.string "Con i POKéMON a noleggio forniti,\n"
	.string "dovrai fare una LOTTA SINGOLA.\p"
	.string "Se vinci, puoi scambiare\n"
	.string "uno dei tuoi POKéMON a noleggio.\p"
	.string "Ripeti questo ciclo di lotta e\n"
	.string "scambio: se vinci tre volte di\l"
	.string "fila, guadagnerai un bel premio.\p"
	.string "Se vuoi interrompere la\n"
	.string "sfida, salva il gioco.\p"
	.string "Se non salvi prima di interrompere,\n"
	.string "verrai squalificato.$"

SlateportCity_BattleTentLobby_Text_LookForwardToNextVisit:
	.string "Ti aspettiamo alla prossima volta.$"

@ Unused
SlateportCity_BattleTentLobby_Text_WhichLevelMode:
	.string "A quale livello vuoi sfidare?\n"
	.string "Livello 50 o Livello 100?$"

SlateportCity_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Prima di iniziare la sfida,\n"
	.string "devo salvare i dati. Va bene?$"

@ Unused
SlateportCity_BattleTentLobby_Text_HoldMonsForSafekeeping:
	.string "Bene, custodisco i tuoi POKéMON\n"
	.string "mentre gareggi.$"

SlateportCity_BattleTentLobby_Text_StepThisWay:
	.string "Da questa parte, prego.$"

SlateportCity_BattleTentLobby_Text_ReturnRentalMonsSaveResults:
	.string "Grazie per aver partecipato!\p"
	.string "Ti restituisco i POKéMON in cambio\n"
	.string "di quelli a noleggio.\p"
	.string "Devo anche salvare i risultati.\n"
	.string "Attendi, prego.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnMonsExchangeRentals:
	.string "Ti restituisco i tuoi POKéMON\n"
	.string "in cambio di quelli a noleggio.$"

SlateportCity_BattleTentLobby_Text_WonThreeMatchesReturnMons:
	.string "Congratulazioni!\n"
	.string "Hai vinto tre incontri di fila!\p"
	.string "Ti restituisco i tuoi POKéMON in cambio\n"
	.string "dei nostri POKéMON a noleggio.\p"
	.string "Devo anche salvare i risultati.\n"
	.string "Attendi.$"

SlateportCity_BattleTentLobby_Text_AwardYouThisPrize:
	.string "Per la tua serie di 3 vittorie,\n"
	.string "ti diamo questo premio.$"

SlateportCity_BattleTentLobby_Text_NoRoomInBagMakeRoom:
	.string "Oh?\n"
	.string "Sembra che tu non abbia spazio.\p"
	.string "Fai spazio nella BORSA e\n"
	.string "avvisami.$"

SlateportCity_BattleTentLobby_Text_BeenWaitingForYou:
	.string "Ti aspettavamo!\p"
	.string "Prima di riprendere la sfida,\n"
	.string "devo salvare il gioco.$"

SlateportCity_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "Mi dispiace, ma l'ultima volta\n"
	.string "non hai salvato prima di uscire.\p"
	.string "Quindi sei stato squalificato\n"
	.string "dalla sfida.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnPersonalMons:
	.string "Ti restituiremo i tuoi POKéMON.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReceivedPrize:
	.string "{PLAYER} ha ottenuto\n"
	.string "{STR_VAR_1}.$"

@ Unused
SlateportCity_BattleTentLobby_Text_RulesAreListed:
	.string "Le regole dello Scambio sono elencate.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReadWhichHeading:
	.string "Quale voce vuoi leggere?$"

SlateportCity_BattleTentLobby_Text_ExplainBasicRules:
	.string "Nello Scambio Lotta puoi usare\n"
	.string "solo tre POKéMON.\p"
	.string "Che tu noleggi o scambi,\n"
	.string "non puoi avere due o più\l"
	.string "POKéMON uguali.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapPartnerRules:
	.string "Puoi scambiare POKéMON solo con\n"
	.string "l'ALLENATORE appena sconfitto.\p"
	.string "E solo per i POKéMON usati\n"
	.string "da quell'ALLENATORE.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNumberRules:
	.string "Dopo ogni lotta vinta, puoi\n"
	.string "scambiare con uno dei POKéMON\l"
	.string "dell'avversario battuto.\p"
	.string "Non potrai scambiare POKéMON\n"
	.string "con il terzo ALLENATORE dell'evento.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNotes:
	.string "Ci sono due punti chiave da\n"
	.string "sapere sugli scambi.\p"
	.string "Primo, durante lo scambio non\n"
	.string "puoi vedere le statistiche dei\l"
	.string "POKéMON che ricevi.\p"
	.string "Secondo, i POKéMON della tua\n"
	.string "squadra sono in fila secondo\l"
	.string "l'ordine in cui li hai noleggiati.\p"
	.string "Questa sequenza resta invariata\n"
	.string "anche dopo gli scambi.$"

SlateportCity_BattleTentLobby_Text_ExplainMonRules:
	.string "I POKéMON della TENDA LOTTA di\n"
	.string "PORTO ALGHE sono tutti a noleggio.\p"
	.string "Tutti i POKéMON a noleggio sono\n"
	.string "al Livello 30.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_RulesAreListed2:
	.string "Sono elencate le regole del\n"
	.string "TENDONE LOTTA di VERDANTURF.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ReadWhichHeading:
	.string "Quale voce vuoi leggere?$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainBasicRules:
	.string "Qui al TENDONE LOTTA di VERDANTURF,\n"
	.string "i POKéMON devono pensare e\l"
	.string "lottare da soli.\p"
	.string "A differenza dei selvatici, i POKéMON\n"
	.string "che vivono con le persone si comportano\l"
	.string "in modi diversi a seconda della natura.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainNatureRules:
	.string "A seconda della natura, un POKéMON\n"
	.string "può preferire attaccare sempre.\p"
	.string "Un altro può preferire proteggersi\n"
	.string "da ogni danno.\p"
	.string "Un altro ancora può divertirsi a\n"
	.string "infastidire o confondere i nemici.\p"
	.string "A seconda della natura, un POKéMON\n"
	.string "avrà mosse preferite in cui è bravo\l"
	.string "a usare.\p"
	.string "Può anche non gradire alcune mosse\n"
	.string "che gli riescono difficili.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainMoveRules:
	.string "Ci sono mosse offensive\n"
	.string "che colpiscono il nemico.\p"
	.string "E mosse difensive, per\n"
	.string "prepararsi agli attacchi o\l"
	.string "curare i PS e altro.\p"
	.string "Poi vi sono mosse strane\n"
	.string "che affliggono il nemico con\l"
	.string "problemi come Veleno\l"
	.string "o paralisi.\p"
	.string "I POKéMON scelgono tra\n"
	.string "queste tre categorie.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainUnderpoweredRules:
	.string "Senza ordini dell'ALLENATORE,\n"
	.string "un POKéMON può non usare\l"
	.string "bene certe mosse.\p"
	.string "Un POKéMON non riesce mai\n"
	.string "con una mossa che odia.\p"
	.string "Se ha solo mosse diverse\n"
	.string "dalla sua natura, spesso\l"
	.string "non dà il massimo.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainWhenInDangerRules:
	.string "In base alla natura, un POKéMON\n"
	.string "può usare mosse contrarie\l"
	.string "quando è in difficoltà.\p"
	.string "Se un POKéMON si comporta\n"
	.string "male, osservalo bene.$"

BattleTentLobby_Text_ExplainLevelRules:
	.string "In questa TENDA LOTTA, i livelli dei\n"
	.string "tuoi avversari saranno adattati a\l"
	.string "quelli dei tuoi POKéMON.\p"
	.string "Però nessun ALLENATORE che affronterai\n"
	.string "avrà POKéMON sotto il Livello 30.$"

VerdanturfTown_BattleTentLobby_Text_RulesAreListed:
	.string "Sono elencate le regole del\n"
	.string "TENDONE LOTTA di VERDANTURF.$"

BattleTentLobby_Text_EarnedBattlePoints:
	.string "Hai guadagnato {STR_VAR_1} Punti Lotta!$"

