
#if IS_HNS
FallarborTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "I welcome you to the BATTLE TENT!\p"
	.string "I am your guide to the Set KO Tourney!$"
#else
FallarborTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "I welcome you to the BATTLE TENT\n"
	.string "FALLARBOR SITE!\p"
	.string "I am your guide to the Set KO Tourney!$"
#endif

FallarborTown_BattleTentLobby_Text_TakeChallenge:
	.string "Now, do you wish to take the challenge\n"
	.string "of a Set KO Tourney?$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge:
	.string "Ti aspettiamo di nuovo\n"
	.string "per una sfida!$"

FallarborTown_BattleTentLobby_Text_ExplainFallarborTent:
#if IS_HNS
	.string "In the ARENA BATTLE TENT,\n"
#else
	.string "In the FALLARBOR BATTLE TENT,\n"
#endif
	.string "we undertake the Set KO Tourney.\p"
	.string "All participants enter with a team of\n"
	.string "three POKéMON.\p"
	.string "The three POKéMON must be lined up\n"
	.string "in the order that they are to appear in.\p"
	.string "During battle, the POKéMON will appear\n"
	.string "one at a time in the preset order.\p"
	.string "Once a POKéMON enters battle, it must\n"
	.string "remain out until the match is decided.\p"
	.string "If a match remains undecided in\n"
	.string "three turns, it goes to judging.\p"
	.string "If you wish to interrupt your challenge,\n"
	.string "please save the game.\p"
	.string "If you don't save, you will not be able\n"
	.string "to continue with your challenge.\p"
	.string "If you pull off the feat of beating\n"
	.string "three TRAINERS in succession,\l"
	.string "we will present you with a fine prize.$"

FallarborTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Before showing you to the BATTLE\n"
	.string "TENT, I must save. Is that okay?$"

@ Unused
FallarborTown_BattleTentLobby_Text_WhichLevelMode:
	.string "We offer two levels of challenge,\n"
	.string "Level 50 and Open Level.\l"
	.string "Which is your choice?$"

FallarborTown_BattleTentLobby_Text_SelectThreeMons:
	.string "Bene, ora scegli pure\n"
	.string "i tuoi tre POKéMON.$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "My dear challenger!\p"
	.string "You do not have the three POKéMON\n"
	.string "required for entry.\p"
	.string "They also must not hold the same\n"
	.string "kinds of items.\p"
	.string "EGGS{STR_VAR_1} ineligible.\p"
	.string "When you have made your preparations,\n"
	.string "please do return.$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "My dear challenger!\p"
	.string "You do not have the three POKéMON\n"
	.string "required for entry.\p"
	.string "To qualify, you must bring three\n"
	.string "different kinds of POKéMON.\p"
	.string "They also must not hold the same\n"
	.string "kinds of items.\p"
	.string "EGGS{STR_VAR_1} ineligible.\p"
	.string "When you have made your preparations,\n"
	.string "please do return.$"

FallarborTown_BattleTentLobby_Text_GuideYouToBattleTent:
	.string "I shall now guide you to\n"
	.string "the BATTLE TENT.$"

FallarborTown_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "Caro sfidante!\p"
	.string "Non hai salvato prima\n"
	.string "di spegnere, vero?\p"
	.string "Purtroppo questo comporta\n"
	.string "la tua squalifica\l"
	.string "dalla sfida.\p"
	.string "Puoi riprovare da capo,\n"
	.string "beninteso.$"

FallarborTown_BattleTentLobby_Text_BeatThreeTrainers:
	.string "How splendid! You have beaten\n"
	.string "three TRAINERS in succession!$"

FallarborTown_BattleTentLobby_Text_WaitWhileSaveGame:
	.string "Please wait while I save the game.$"

FallarborTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "In commemoration of your 3-win streak,\n"
	.string "we present you with this prize.$"

FallarborTown_BattleTentLobby_Text_ReceivedPrize:
	.string "{PLAYER} ha ottenuto\n"
	.string "{STR_VAR_1}.$"

FallarborTown_BattleTentLobby_Text_BagFullReturnForPrize:
	.string "Oh?\n"
	.string "La tua BORSA è piena.\p"
	.string "Fai spazio e torna\n"
	.string "a ritirare il premio.$"

FallarborTown_BattleTentLobby_Text_ThankYouWaitWhileSaving:
	.string "Grazie per la partecipazione!\p"
	.string "Attendi mentre salvo il gioco.$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge2:
	.string "Ti aspettiamo di nuovo\n"
	.string "per una sfida!$"

FallarborTown_BattleTentLobby_Text_LookingForwardToArrival:
	.string "We have been looking forward to\n"
	.string "your arrival.\p"
	.string "Before I show you to the BATTLE TENT,\n"
	.string "I must save the game. Please wait.$"

#if IS_HNS
VerdanturfTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "I welcome you to the BATTLE TENT!\p"
	.string "Here, the TRAINER's trust toward\n"
	.string "POKéMON is tested.$"
#else
VerdanturfTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "I welcome you to the BATTLE TENT\n"
	.string "VERDANTURF SITE!\p"
	.string "Here, the TRAINER's trust toward\n"
	.string "POKéMON is tested.$"
#endif
VerdanturfTown_BattleTentLobby_Text_TakeChallenge:
#if IS_HNS
	.string "Do you wish to take the PALACE\n"
#else
	.string "Do you wish to take the VERDANTURF\n"
#endif
	.string "BATTLE TENT challenge?$"

VerdanturfTown_BattleTentLobby_Text_ExplainVerdanturfTent:
#if IS_HNS
	.string "In the PALACE BATTLE TENT,\n"
#else
	.string "In the VERDANTURF BATTLE TENT,\n"
#endif
	.string "there is one crucial rule that must\l"
	.string "be obeyed.\p"
	.string "TRAINERS are permitted only to switch\n"
	.string "their POKéMON in and out.\p"
	.string "TRAINERS are otherwise forbidden to\n"
	.string "command their POKéMON.\p"
	.string "The POKéMON are to behave according\n"
	.string "to their nature and battle on their own.\p"
	.string "You must put your trust in your\n"
	.string "POKéMON and watch over them.\p"
	.string "If you achieve the honor of beating\n"
	.string "three TRAINERS in succession,\l"
	.string "we will present you with a prize.\p"
	.string "If you want to interrupt your\n"
	.string "challenge, please save the game.\p"
	.string "If you don't save before interrupting,\n"
	.string "you will be disqualified.$"

VerdanturfTown_BattleTentLobby_Text_ReturnFortified:
	.string "Quando hai rafforzato il cuore\n"
	.string "e i POKéMON, devi tornare.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_WhichLevelMode:
	.string "There are two levels of difficulty,\n"
	.string "Level 50 and Open Level.\l"
	.string "Which is your choice of a challenge?$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "Sigh…\p"
	.string "You do not have the three POKéMON\n"
	.string "required for the challenge.\p"
	.string "To enter, you must provide three\n"
	.string "different kinds of POKéMON.\p"
	.string "They also must not be holding\n"
	.string "the same kinds of items.\p"
	.string "EGGS{STR_VAR_1} ineligible.\p"
	.string "Come back when you have made\n"
	.string "your preparations.$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "Sigh…\p"
	.string "You do not have the three POKéMON\n"
	.string "required for the challenge.\p"
	.string "To enter, you must provide three\n"
	.string "different kinds of POKéMON.\p"
	.string "They also must not be holding\n"
	.string "the same kinds of items.\p"
	.string "EGGS{STR_VAR_1} ineligible.\p"
	.string "Come back when you have made\n"
	.string "your preparations.$"

VerdanturfTown_BattleTentLobby_Text_SelectThreeMons:
	.string "Bene. Ora scegli i tuoi\n"
	.string "tre POKéMON.$"

VerdanturfTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "I must save before I show you to\n"
	.string "the BATTLE TENT. Is that okay?$"

VerdanturfTown_BattleTentLobby_Text_NowFollowMe:
	.string "Bene.\n"
	.string "Ora seguimi.$"

VerdanturfTown_BattleTentLobby_Text_ResultsWillBeRecorded:
	.string "È stato un onore vedere le\n"
	.string "gesta dei tuoi POKéMON.\p"
	.string "I risultati saranno registrati.\n"
	.string "Ti chiedo di aspettare un attimo.$"

VerdanturfTown_BattleTentLobby_Text_AchievedThreeWinStreak:
	.string "To achieve a 3-win streak…\p"
	.string "The bonds that bind your heart with\n"
	.string "your POKéMON seem firm and true.$"

VerdanturfTown_BattleTentLobby_Text_FeatWillBeRecorded:
	.string "La tua impresa sarà registrata.\n"
	.string "Ti chiedo di aspettare un attimo.$"

VerdanturfTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "For the feat of your 3-win streak,\n"
	.string "we present you with this prize.$"


#if IS_HNS
SlateportCity_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Welcome to the BATTLE TENT!\p"
	.string "I am your guide to the Battle Swap\n"
	.string "Tournament.$"
#else
SlateportCity_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Welcome to the BATTLE TENT\n"
	.string "SLATEPORT SITE!\p"
	.string "I am your guide to the Battle Swap\n"
	.string "Tournament.$"
#endif


SlateportCity_BattleTentLobby_Text_TakeChallenge:
	.string "Would you like to take the Battle\n"
	.string "Swap challenge?$"

SlateportCity_BattleTentLobby_Text_ExplainSlateportTent:
#if IS_HNS
	.string "Here at the FACTORY BATTLE TENT,\n"
#else
	.string "Here at the SLATEPORT BATTLE TENT,\n"
#endif
	.string "we hold Battle Swap events\l"
	.string "using rental POKéMON.\p"
	.string "First, you will be loaned three\n"
	.string "POKéMON specifically for this event.\p"
	.string "Using the supplied rental POKéMON,\n"
	.string "you must conduct a SINGLE BATTLE.\p"
	.string "If you win, you are permitted to trade\n"
	.string "one of your rental POKéMON.\p"
	.string "Repeat this cycle of battling and\n"
	.string "trading--if you win three times in\l"
	.string "a row, you will earn a fine prize.\p"
	.string "If you want to interrupt your\n"
	.string "challenge, please save the game.\p"
	.string "If you don't save before interrupting,\n"
	.string "you will be disqualified.$"

SlateportCity_BattleTentLobby_Text_LookForwardToNextVisit:
	.string "Ti aspettiamo alla prossima volta.$"

@ Unused
SlateportCity_BattleTentLobby_Text_WhichLevelMode:
	.string "Which level do you wish to challenge?\n"
	.string "Level 50 or Level 100?$"

SlateportCity_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Before you begin your challenge,\n"
	.string "I need to save data. Is that okay?$"

@ Unused
SlateportCity_BattleTentLobby_Text_HoldMonsForSafekeeping:
	.string "Bene, custodisco i tuoi POKéMON\n"
	.string "mentre gareggi.$"

SlateportCity_BattleTentLobby_Text_StepThisWay:
	.string "Da questa parte, prego.$"

SlateportCity_BattleTentLobby_Text_ReturnRentalMonsSaveResults:
	.string "Thank you for participating!\p"
	.string "I will return your POKéMON in exchange\n"
	.string "for our rental POKéMON.\p"
	.string "I must also save your event results.\n"
	.string "Please wait.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnMonsExchangeRentals:
	.string "Ti restituisco i tuoi POKéMON\n"
	.string "in cambio di quelli a noleggio.$"

SlateportCity_BattleTentLobby_Text_WonThreeMatchesReturnMons:
	.string "Congratulations!\n"
	.string "You've won three straight matches!\p"
	.string "I will return your POKéMON in exchange\n"
	.string "for our rental POKéMON.\p"
	.string "I must also save your event results.\n"
	.string "Please wait.$"

SlateportCity_BattleTentLobby_Text_AwardYouThisPrize:
	.string "In recognition of your 3-win streak,\n"
	.string "we award you this prize.$"

SlateportCity_BattleTentLobby_Text_NoRoomInBagMakeRoom:
	.string "Oh?\n"
	.string "Sembra che tu non abbia spazio.\p"
	.string "Fai spazio nella BORSA e\n"
	.string "avvisami.$"

SlateportCity_BattleTentLobby_Text_BeenWaitingForYou:
	.string "Ti aspettavamo!\p"
	.string "Prima di riprendere la sfida,\n"
	.string "devo salvare il gioco.$"

SlateportCity_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "Mi dispiace, ma l'ultima volta\n"
	.string "non hai salvato prima di uscire.\p"
	.string "Quindi sei stato squalificato\n"
	.string "dalla sfida.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnPersonalMons:
	.string "Ti restituiremo i tuoi POKéMON.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReceivedPrize:
	.string "{PLAYER} ha ottenuto\n"
	.string "{STR_VAR_1}.$"

@ Unused
SlateportCity_BattleTentLobby_Text_RulesAreListed:
	.string "Le regole dello Scambio sono elencate.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReadWhichHeading:
	.string "Quale voce vuoi leggere?$"

SlateportCity_BattleTentLobby_Text_ExplainBasicRules:
	.string "Nello Scambio Lotta puoi usare\n"
	.string "solo tre POKéMON.\p"
	.string "Che tu noleggi o scambi,\n"
	.string "non puoi avere due o più\l"
	.string "POKéMON uguali.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapPartnerRules:
	.string "Puoi scambiare POKéMON solo con\n"
	.string "l'ALLENATORE appena sconfitto.\p"
	.string "E solo per i POKéMON usati\n"
	.string "da quell'ALLENATORE.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNumberRules:
	.string "After every battle you win, you may\n"
	.string "swap for one of your defeated\l"
	.string "opponent's POKéMON.\p"
	.string "You will not be able to swap POKéMON\n"
	.string "with the third TRAINER in the event.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNotes:
	.string "Ci sono due punti chiave da\n"
	.string "sapere sugli scambi.\p"
	.string "Primo, durante lo scambio non\n"
	.string "puoi vedere le statistiche dei\l"
	.string "POKéMON che ricevi.\p"
	.string "Secondo, i POKéMON della tua\n"
	.string "squadra sono in fila secondo\l"
	.string "l'ordine in cui li hai noleggiati.\p"
	.string "Questa sequenza resta invariata\n"
	.string "anche dopo gli scambi.$"

SlateportCity_BattleTentLobby_Text_ExplainMonRules:
	.string "The POKéMON of the SLATEPORT\n"
	.string "BATTLE TENT are all rentals.\p"
	.string "All rental POKéMON are kept at\n"
	.string "Level 30.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_RulesAreListed2:
	.string "The VERDANTURF BATTLE TENT\n"
	.string "rules are listed.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ReadWhichHeading:
	.string "Quale voce vuoi leggere?$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainBasicRules:
	.string "Here at the VERDANTURF BATTLE TENT,\n"
	.string "POKéMON are required to think and\l"
	.string "battle by themselves.\p"
	.string "Unlike in the wild, POKéMON that live\n"
	.string "with people behave differently\l"
	.string "depending on their nature.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainNatureRules:
	.string "Depending on its nature, a POKéMON\n"
	.string "may prefer to attack no matter what.\p"
	.string "Another POKéMON may prefer to protect\n"
	.string "itself from any harm.\p"
	.string "Yet another may enjoy vexing or\n"
	.string "confounding its foes.\p"
	.string "Depending on its nature, a POKéMON\n"
	.string "will have favorite moves that it is good\l"
	.string "at using.\p"
	.string "It may also dislike certain moves that\n"
	.string "it has trouble using.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainMoveRules:
	.string "Ci sono mosse offensive\n"
	.string "che colpiscono il nemico.\p"
	.string "E mosse difensive, per\n"
	.string "prepararsi agli attacchi o\l"
	.string "curare i PS e altro.\p"
	.string "Poi vi sono mosse strane\n"
	.string "che affliggono il nemico con\l"
	.string "problemi come Veleno\l"
	.string "o paralisi.\p"
	.string "I POKéMON scelgono tra\n"
	.string "queste tre categorie.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainUnderpoweredRules:
	.string "Senza gli ordini del suo\n"
	.string "ALLENATORE, un POKéMON può\l"
	.string "non usare bene certe mosse.\p"
	.string "Un POKéMON non riesce mai\n"
	.string "con una mossa che odia.\p"
	.string "Se ha solo mosse diverse\n"
	.string "dalla sua natura, spesso\l"
	.string "non dà il massimo.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainWhenInDangerRules:
	.string "In base alla natura, un POKéMON\n"
	.string "può usare mosse contrarie\l"
	.string "quando è in difficoltà.\p"
	.string "Se un POKéMON si comporta\n"
	.string "male, osservalo bene.$"

BattleTentLobby_Text_ExplainLevelRules:
	.string "At this BATTLE TENT, the levels of\n"
	.string "your opponents will be adjusted to\l"
	.string "match the levels of your POKéMON.\p"
	.string "However, no TRAINER you face will\n"
	.string "have any POKéMON below Level 30.$"

VerdanturfTown_BattleTentLobby_Text_RulesAreListed:
	.string "The VERDANTURF BATTLE TENT\n"
	.string "rules are listed.$"

BattleTentLobby_Text_EarnedBattlePoints:
	.string "You've earned {STR_VAR_1} Battle Points!$"

