PetalburgCity_Gym_Text_GiveEnigmaBerry:
	.string "PAPÀ: Ciao, {PLAYER}!\p"
	.string "Ho appena ricevuto una BACCA rarissima.\n"
	.string "Vorrei che l'avessi tu.$"

Route104_Text_PlantBerriesInSoilTakeThis:
	.string "Se vedi BACCE che crescono nel terreno\n"
	.string "fertile, prendile pure.\p"
	.string "Ma pianta una BACCA nello\n"
	.string "stesso punto. È buona educazione.\p"
	.string "Ecco, ti do questo.$"

Route104_Text_TrainersOftenMakeMonHoldBerries:
	.string "Dal tuo aspetto, devi essere un\n"
	.string "ALLENATORE, no?\p"
	.string "Gli ALLENATORI fanno spesso tenere\n"
	.string "le BACCE ai POKéMON.\p"
	.string "Sta a te coltivare le BACCE\n"
	.string "o usarle.$"

Route111_Text_WateredPlantsEveryDayTakeBerry:
	.string "Ho annaffiato le piante ogni giorno.\n"
	.string "Hanno fatto tanti fiori.\p"
	.string "E mi hanno dato anche tante BACCE.\p"
	.string "Tieni!\n"
	.string "Puoi averla!$"

Route111_Text_GoingToTryToMakeDifferentColorBerries:
	.string "Mi impegnerò davvero e creerò\n"
	.string "BACCE di colori diversi.\p"
	.string "Spero che anche tu ti impegni!$"

Route111_Text_WhatColorBerriesToLookForToday:
	.string "Chissà di che colore cercherò le\n"
	.string "BACCE oggi?$"

Route114_Text_LoveUsingBerryCrushShareBerry:
	.string "Adoro usare la macchina BERRY CRUSH,\n"
	.string "quindi colleziono BACCE.\p"
	.string "Te ne do una, se vuoi.$"

Route114_Text_TryBerryCrushWithFriends:
	.string "Dovresti provare la macchina\n"
	.string "BERRY CRUSH con i tuoi amici.$"

Route114_Text_FunToThinkAboutBerries:
	.string "Quale BACCA piantare?\n"
	.string "Usare le BACCE o accumularle?\p"
	.string "È divertente pensarci.$"

Route120_Text_BerriesExpressionOfLoveIsntIt:
	.string "Le BACCHE crescono assorbendo la luce.\p"
	.string "Le aiutiamo a crescere annaffiandole\n"
	.string "con regolarità.\p"
	.string "È una prova d'amore, no?$"

Route120_Text_YesYouUnderstand:
	.string "Sì, sì.\n"
	.string "Capisci cosa intendo.\p"
	.string "Dovresti prendere questo.$"

Route120_Text_MakeYourOwnImpressions:
	.string "Oh… But it is important to make your\n"
	.string "own impressions, I guess…\p"
	.string "You can have this.$"

Route120_Text_BerryIsRareRaiseItWithCare:
	.string "Penso che quella BACCA sia rara.\n"
	.string "Spero che la cresca con amore.$"

Route120_Text_IllGetMoreBerriesFromBerryMaster:
	.string "Prenderò altre BACCE dal\n"
	.string "BERRY MASTER.$"

LilycoveCity_Text_BerrySuitsYou:
	.string "When it gets right down to it…\p"
	.string "The same way suits suit me perfectly,\n"
	.string "a crisp breeze suits the sea.\p"
	.string "And you, a BERRY suits you to a “T”…\p"
	.string "Why should that be so?$"

LilycoveCity_Text_BecauseYoureTrainer:
	.string "In fondo, in fin dei conti…\p"
	.string "È perché sei un ALLENATORE!$"

LilycoveCity_Text_PokeblocksSuitPokemon:
	.string "In fondo, in fin dei conti…\p"
	.string "Come la sobria eleganza sta bene a me,\n"
	.string "i {POKEBLOCK} stanno bene ai POKéMON.$"

Route123_BerryMastersHouse_Text_YoureDeservingOfBerry:
	.string "Puoi chiamarmi MAESTRO DELLE BACCHE.\p"
	.string "Sogno di riempire il mondo di\n"
	.string "bei fiori, così coltivo BACCHE\l"
	.string "e le regalo a tutti.\p"
	.string "Tu ne meriti una!$"

Route123_BerryMastersHouse_Text_WhyBeStingyTakeAnother:
	.string "Perché fare i tirchi?\n"
	.string "Prendine un'altra!$"

Route123_BerryMastersHouse_Text_VisitPrettyPetalFlowerShop:
	.string "Visita il negozio di fiori\n"
	.string "PRETTY PETAL vicino a RUSTBORO.\p"
	.string "Che i fiori riempiano il mondo!$"

Route123_BerryMastersHouse_Text_DoneForToday:
	.string "Per oggi ho finito.\n"
	.string "Torna un altro giorno.\p"
	.string "I fiori riempiano il mondo!$"

Route123_BerryMastersHouse_Text_HeardAGoodSayingLately:
	.string "Come coltiva BACCHE mio marito,\n"
	.string "oh, è il migliore al mondo.\p"
	.string "Mi rende orgogliosa, altroché.\p"
	.string "A proposito, piccolo, hai sentito\n"
	.string "un bel detto di recente?$"

Route123_BerryMastersHouse_Text_InspirationalTakeThis:
	.string "Ah! Che detto straordinario!\n"
	.string "Che ispirazione!\p"
	.string "Voglio farti un regalo.$"

Route123_BerryMastersHouse_Text_GoodSayingTakeThis:
	.string "Oh! Che bel detto.\n"
	.string "Sei proprio in gamba.\p"
	.string "Voglio farti un regalo.$"

Route123_BerryMastersHouse_Text_JoyNeverGoesOutOfMyLife:
	.string "I nostri quattro nipoti diventeranno\n"
	.string "più bravi di mio marito.\p"
	.string "La gioia non mi lascia mai!$"

Route123_BerryMastersHouse_Text_Ah:
	.string "Ah…$"

Route104_PrettyPetalFlowerShop_Text_ThisIsPrettyPetalFlowerShop:
	.string "Ciao!\p"
	.string "Questo è il negozio di fiori PRETTY PETAL.\n"
	.string "Fiori in tutto il mondo!$"

Route104_PrettyPetalFlowerShop_Text_LearnAboutBerries:
	.string "{PLAYER}{KUN}, vorresti sapere qualcosa\n"
	.string "sulle BACCE?$"

Route104_PrettyPetalFlowerShop_Text_IntroLearnAboutBerries:
	.string "Come ti chiami?\p"
	.string "{PLAYER}{KUN}.\n"
	.string "Che bel nome.\p"
	.string "{PLAYER}{KUN}, vorresti sapere qualcosa\n"
	.string "sulle BACCE?$"

Route104_PrettyPetalFlowerShop_Text_BerriesExplanation:
	.string "Le BACCHE crescono su alberi che\n"
	.string "vivono solo in terreno morbido.\p"
	.string "Se prendi delle BACCHE, piantane\n"
	.string "una di nuovo nel terreno.\p"
	.string "La BACCA piantata germoglierà,\n"
	.string "diventerà pianta, fiorirà\l"
	.string "e produrrà nuove BACCHE.\p"
	.string "Voglio vedere il mondo intero\n"
	.string "pieno di fiori bellissimi.\l"
	.string "È il mio sogno.\p"
	.string "Aiutami, {PLAYER}{KUN}. Pianta BACCHE\n"
	.string "e porta più fiori nel mondo.$"

Route104_PrettyPetalFlowerShop_Text_FlowersBringHappiness:
	.string "I fiori danno tanta felicità alle\n"
	.string "persone, vero?$"

Route104_PrettyPetalFlowerShop_Text_YouCanHaveThis:
	.string "Ciao!\p"
	.string "Più cure dai ai fiori,\n"
	.string "più belli sbocciano.\p"
	.string "Ti piacerà prenderti cura dei fiori.\n"
	.string "Ne sono certo. Prendi questo.$"

Route104_PrettyPetalFlowerShop_Text_WailmerPailExplanation:
	.string "While BERRY plants are growing,\n"
	.string "water them with the WAILMER PAIL.\p"
	.string "Oh, another thing.\p"
	.string "If you don't pick BERRIES for a while,\n"
	.string "they'll drop off onto the ground.\l"
	.string "But they'll sprout again.\p"
	.string "Isn't that awesome?\n"
	.string "It's like they have the will to live.$"

Route104_PrettyPetalFlowerShop_Text_ImGrowingFlowers:
	.string "Provo a imitare le mie sorelle grandi.\n"
	.string "Anch'io coltivo i fiori!\p"
	.string "Tieni!\n"
	.string "È per te!$"

Route104_PrettyPetalFlowerShop_Text_MachineMixesBerries:
	.string "Puoi piantare una BACCA e farla crescere,\n"
	.string "o farla tenere a un POKéMON.\p"
	.string "Ma ora c'è una macchina che mescola\n"
	.string "diverse BACCE e crea caramelle\l"
	.string "per i POKéMON.\p"
	.string "Anch'io voglio una caramella.$"

SootopolisCity_Text_NameIsKiriHaveOneOfThese:
	.string "Ciao, come ti chiami?\p"
	.string "… … …  … … …  … … …\n"
	.string "Ok. Che bel nome!\p"
	.string "Io mi chiamo KIRI.\p"
	.string "Mamma e papà me l'hanno dato perché\n"
	.string "crescessi sana e di buon cuore.\l"
	.string "Questo era il loro desiderio.\p"
	.string "Puoi prenderne una di queste.$"

SootopolisCity_Text_GiveYouThisBerryToo:
	.string "KIRI ti darà anche questa BACCA!\n"
	.string "Mi piace proprio tanto!$"

SootopolisCity_Text_WhatKindOfWishInYourName:
	.string "Chissà quale desiderio c'è\n"
	.string "nel tuo nome.$"

SootopolisCity_Text_LikeSeasonBornIn:
	.string "Primavera, estate, autunno e inverno.\p"
	.string "Se nasci in primavera, ti piace\n"
	.string "la primavera, e se nasci in\l"
	.string "estate, ti piace l'estate?$"

SootopolisCity_Text_ThenILoveAutumn:
	.string "Allora KIRI è nata in autunno,\n"
	.string "quindi amo l'autunno!\p"
	.string "Quale stagione ti piace?$"

SootopolisCity_Text_OhDoesntMatter:
	.string "Oh…\n"
	.string "Non importa…\p"
	.string "Vorrei sapere così tante cose…$"
