gText_Birch_Welcome::
	.string "Ciao! Scusa l'attesa!\p"
	.string "Benvenuto nel mondo dei POKéMON!\p"
	.string "Mi chiamo BIRCH.\p"
	.string "Ma tutti mi chiamano il\n"
	.string "PROFESSOR POKéMON.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Questo lo chiamiamo “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Questo mondo è abitato da\n"
	.string "creature note come POKéMON.\p"
	.string "Noi umani viviamo accanto ai POKéMON,\n"
	.string "a volte come amici di giochi, e\l"
	.string "a volte come collaboratori.\p"
	.string "E qualche volta ci alleiamo\n"
	.string "e lottiamo contro altri come noi.\p"
	.string "Ma nonostante la vicinanza, non\n"
	.string "sappiamo tutto dei POKéMON.\p"
	.string "Anzi, ci sono molti, molti\n"
	.string "segreti intorno ai POKéMON.\p"
	.string "Per svelare i misteri dei POKéMON,\n"
	.string "ho intrapreso delle ricerche.\l"
	.string "Ecco cosa faccio.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "E tu chi sei?$"

gText_Birch_BoyOrGirl::
	.string "Sei un maschio?\n"
	.string "O sei una femmina?$"

gText_Birch_WhatsYourName::
	.string "Bene.\n"
	.string "Come ti chiami?$"

gText_Birch_SoItsPlayer::
	.string "Quindi sei {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, capito!\p"
	.string "Sei {PLAYER}{KUN}, che si trasferisce\n"
	.string "nel mio paese natale, LITTLEROOT.\l"
	.string "Ora ho capito!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Bene, sei pronto?\p"
	.string "La tua avventura sta per\n"
	.string "cominciare.\p"
	.string "Fatti coraggio e tuffati nel\n"
	.string "mondo dei POKéMON, dove sogni,\l"
	.string "avventure e amicizie ti attendono!\p"
	.string "Bene, ti aspetterò più tardi.\n"
	.string "Passa a trovarmi nel mio LAB.\p"
	.string "$"
