BerryBlender_Text_BlendWithTheBlendMaster:
	.string "MAESTRO MIXER: Proprio così!\n"
	.string "Il MAESTRO MIXER sono io!\p"
	.string "Mixa con me e vedrai\n"
	.string "la maestria che ci metto!$"

BerryBlender_Text_SeeMyMasteryInAction:
	.string "MAESTRO MIXER: Mmmh! Quindi vuoi\n"
	.string "vedere la mia maestria in azione?$"

BerryBlender_Text_TooBusyNowIsee:
	.string "Mmmh!\p"
	.string "Sei troppo occupato adesso, capisco!\p"
	.string "Ma non temere!\n"
	.string "Starò qui tutto il giorno!\l"
	.string "Torna presto dalla tua commissione!$"

BerryBlender_Text_BlendMasterNoBerries:
	.string "Mmmh!\p"
	.string "Non hai nemmeno una BACCA!\p"
	.string "Starò qui tutto il giorno!\n"
	.string "Torna presto con delle BACCHE!$"

BerryBlender_Text_BlendMasterKnowHowToMakePokeblocks:
	.string "Ma certo!\n"
	.string "Ma certo!\p"
	.string "A proposito…\n"
	.string "Sai come si creano le {POKEBLOCK}\l"
	.string "dalle BACCHE?$"

BerryBlender_Text_BlendMasterExplainBerryBlending:
	.string "Mmmh!\p"
	.string "Ah, ma è una cosa semplice!\p"
	.string "Quando la freccia del MIXER arriva\n"
	.string "sul tuo segno, premi il tasto A.\p"
	.string "Tutto qui.\p"
	.string "Quando vedrai con quanta precisione\n"
	.string "premo il tasto A, capirai.$"

BerryBlender_Text_BlendMasterLetsBerryBlender:
	.string "Bene!\p"
	.string "Cominciamo, allora!\p"
	.string "Tutti insieme al MAESTRO DELLA MIXER,\n"
	.string "facciamo MIXER BACCHE!$"

BerryBlender_Text_BlendMasterNoPokeblockCase:
	.string "Mmmh!\p"
	.string "Sembra che tu non abbia\n"
	.string "la {POKEBLOCK} CASE!\p"
	.string "Starò qui tutto il giorno!\n"
	.string "Trova la {POKEBLOCK} CASE e torna presto!$"

BerryBlender_Text_BlendMasterPokeblockCaseFull:
	.string "Mmmh!\p"
	.string "La tua {POKEBLOCK} CASE è piena!\p"
	.string "Starò qui tutto il giorno!\n"
	.string "Usa qualche {POKEBLOCK} e torna presto!$"

BerryBlender_Text_WhoaAwesome:
	.string "Uau!\n"
	.string "Fantastico!$"

BerryBlender_Text_WickedlyFast:
	.string "Velocissimo!$"

BerryBlender_Text_WhatAnExpert:
	.string "Che esperto!$"

BerryBlender_Text_MadeAmazingPokeblocksWithMaster:
	.string "Quando ho mixato col MAESTRO,\n"
	.string "abbiamo creato {POKEBLOCK} fantastiche!$"

BerryBlender_Text_QualitiesOfBlendMaster:
	.string "Occhi che seguono la freccia con\n"
	.string "intensità meccanica…\p"
	.string "Una mano che preme il tasto A\n"
	.string "con precisione da orologio…\p"
	.string "Avere queste qualità rende\n"
	.string "il MAESTRO MIXER davvero grande.$"

BerryBlender_Text_MasterWorksOnSkillsInMountains:
	.string "Il MAESTRO MIXER dovrebbe allenarsi\n"
	.string "in fondo alle montagne.\p"
	.string "A volte viene a LILYCOVE\n"
	.string "a mixare BACCHE tutto il giorno.$"
