CableClub_Text_WelcomeWhichCableClubService:
	.string "Benvenuto nel CLUB CAVO\n"
	.string "POKéMON.\p"
	.string "Quale dei nostri servizi vuoi\n"
	.string "usare?$"

CableClub_Text_WhichService:
	.string "Quale dei nostri servizi vuoi\n"
	.string "usare?$"

CableClub_Text_TradeUsingLinkCable::
	.string "Scambia POKéMON con un altro giocatore\n"
	.string "usando un cavo GBA Game Link.$"

CableClub_Text_BattleUsingLinkCable::
	.string "Puoi lottare contro un altro\n"
	.string "ALLENATORE con un cavo GBA.$"

CableClub_Text_RecordCornerUsingLinkCable::
	.string "Puoi usare il RECORD CORNER con\n"
	.string "altri tramite cavo Game Link GBA.$"

@ Unused
CableClub_Text_CloseThisMenu:
	.string "Chiudi questo menu.$"

CableClub_Text_NeedTwoMonsForDoubleBattle:
	.string "Per una LOTTA DOPPIA devi\n"
	.string "avere almeno due POKéMON.$"

CableClub_Text_NeedTwoMonsToTrade:
	.string "Per scambiare devi avere con te\n"
	.string "almeno due POKéMON.$"

CableClub_Text_CantTradeEnigmaBerry:
	.string "Un POKéMON che tiene la {STR_VAR_1}\n"
	.string "non può essere scambiato.$"

gText_PleaseWaitForLink::
	.string "Attendi.\n"
	.string "… … Tasto B: Annulla$"

gText_ConfirmLinkWhenPlayersReady::
	.string "Quando tutti sono pronti…\n"
	.string "Tasto A: Conferma\l"
	.string "Tasto B: Annulla$"

gText_ConfirmStartLinkWithXPlayers::
	.string "Collega con {STR_VAR_1} giocatori.\n"
	.string "Tasto A: Conferma\l"
	.string "Tasto B: Annulla$"

gText_AwaitingLinkup::
	.string "In attesa del collegamento…\n"
	.string "… … Tasto B: Annulla$"

@ Unused
CableClub_Text_OkayToSaveProgress::
	.string "Devi salvare i progressi prima di\n"
	.string "collegarti. Va bene se salvo?$"

CableClub_Text_PleaseEnter:
	.string "Entra, prego.$"

CableClub_Text_DirectYouToYourRoom:
	.string "Ora ti accompagno nella tua stanza.$"

Text_SomeoneIsNotReadyToLink:
	.string "Qualcuno non è pronto a collegarsi.\p"
	.string "Torna dopo che tutti\n"
	.string "si saranno preparati.$"

Text_LinkErrorPleaseReset:
	.string "Spiacente, c'è un errore di collegamento…\n"
	.string "Riavvia e riprova.$"

Text_PlayersMadeDifferentSelections:
	.string "I partner del collegamento sembrano\n"
	.string "aver scelto opzioni diverse.$"

CableClub_Text_PleaseVisitAgain:
	.string "Torna a trovarci.$"

CableClub_Text_IncorrectNumberOfParticipants:
	.string "Il numero di partecipanti non\n"
	.string "è corretto.$"

CableClub_Text_CantSingleBattleWithXPlayers:
	.string "La modalità LOTTA IN SINGOLO non\n"
	.string "si può usare in {STR_VAR_1} giocatori.$"

CableClub_Text_CantDoubleBattleWithXPlayers:
	.string "La modalità LOTTA IN DOPPIO non\n"
	.string "si può usare in {STR_VAR_1} giocatori.$"

CableClub_Text_NeedFourPlayers:
	.string "Servono quattro giocatori per questa\n"
	.string "Modalità Lotta.$"

CableClub_Text_PleaseConfirmNumberAndRestart:
	.string "Conferma il numero di\n"
	.string "giocatori e ricomincia.$"

Text_TerminateLinkConfirmation:
	.string "Il collegamento si chiuderà se\n"
	.string "esci dalla stanza. Va bene?$"

Text_TerminateLinkPleaseWait:
	.string "Chiusura del collegamento…\n"
	.string "Verrai accompagnato fuori\l"
	.string "dalla stanza. Attendi.$"

CableClub_Text_TooBusyToNotice:
	.string "Questo ALLENATORE è troppo\n"
	.string "occupato…$"

CableClub_Text_GotToLookAtTrainerCard:
	.string "Evvai! Ho visto la {STR_VAR_1}\n"
	.string "SCHEDA ALLENATORE!$"

CableClub_Text_GotToLookAtColoredTrainerCard:
	.string "Score! Got to look at {STR_VAR_1}'s\n"
	.string "TRAINER CARD!\p"
	.string "It's a {STR_VAR_2} card!$"

BattleColosseum_2P_Text_TakePlaceStartBattle:
	.string "Prendi posto e comincia\n"
	.string "la tua lotta.$"

TradeCenter_Text_TakeSeatStartTrade:
	.string "Prendi posto e inizia\n"
	.string "lo scambio.$"

RecordCorner_Text_ThanksForComing:
	.string "Grazie per essere venuto.$"

CableClub_Text_TrainerCardDataOverwritten:
	.string "I dati della SCHEDA ALLENATORE\n"
	.string "saranno sovrascritti.$"

CableClub_Text_HopeToSeeYouAgain:
	.string "Spero di rivederti!$"

CableClub_Text_NotSetUpForFarAwayRegion:
	.string "Mi dispiace molto.\p"
	.string "Non siamo attrezzati per scambiare\n"
	.string "con ALLENATORI lontani in un'altra\l"
	.string "regione…$"

CableClub_Text_OtherTrainerNotReady:
	.string "L'altro ALLENATORE non è pronto.$"

CableClub_Text_YouHaveAMonThatCantBeTaken:
	.string "Hai almeno un POKéMON\n"
	.string "che non può essere portato.$"

RecordCorner_Text_TakeSeatAndWait:
	.string "Accomodati e attendi.$"

RecordCorner_Text_PlayerSentOverOneX:
	.string "{STR_VAR_1} ti ha inviato\n"
	.string "{STR_VAR_2}.$"

CableClub_Text_CantMixWithJapaneseGame:
	.string "Spiacente, c'è un errore di trasmissione.\p"
	.string "Non puoi scambiare i dati con  \n"
	.string "versioni giapponesi di Rubino o Zaffiro.\p"
	.string "Inoltre, non puoi scambiare i dati con\n"
	.string "Smeraldo giapponese e Rubino o Zaffiro\l"
	.string "stranieri allo stesso tempo.$"

CableClub_Text_AdapterNotConnected:
	.string "L'Adattatore Wireless non è\n"
	.string "collegato bene.$"

CableClub_Text_ParticipantsStepUpToCounter:
	.string "I partecipanti sono invitati a farsi\n"
	.string "avanti al banco accoglienza.$"

@ Unused
CableClub_Text_Hello:
	.string "Ciao!$"

@ Unused
CableClub_Text_PleaseWait:
	.string "Attendi.$"

CableClub_Text_YouMayTradeHere::
	.string "Qui puoi scambiare i tuoi POKéMON\n"
	.string "con un altro ALLENATORE.$"

CableClub_Text_YouMayBattleHere::
	.string "Puoi lottare con i tuoi amici\n"
	.string "qui.$"

CableClub_Text_CanMakeBerryPowder::
	.string "Da due a cinque ALLENATORI possono\n"
	.string "creare PULVISCOPPIO insieme.$"

CableClub_Text_CanMixRecords::
	.string "I record di due a quattro giocatori\n"
	.string "possono essere mixati.$"

@ Unused
CableClub_Text_GuideToVariousServices:
	.string "Una guida ai vari servizi del\n"
	.string "WIRELESS CLUB.$"

CableClub_Text_CancelSelectedItem::
	.string "Annulla la voce di MENU scelta.$"

@ Unused
CableClub_Text_WhichBattleMode:
	.string "Quale modalità di lotta vuoi?$"

@ Unused
CableClub_Text_ReturnsToPreviousStep:
	.string "Torna al passaggio precedente.$"

CableClub_Text_NeedBerryForBerryCrush:
	.string "Per usare il servizio SPRIMIBACCA,\n"
	.string "devi avere almeno una BACCA.$"

CableClub_Text_NeedTwoMonsForUnionRoom:
	.string "Per entrare nella SALA UNIONE devi\n"
	.string "avere almeno due POKéMON.$"

CableClub_Text_NoEnigmaBerryInUnionRoom:
	.string "Nessun POKéMON che tiene la {STR_VAR_1}\n"
	.string "può entrare nella SALA UNIONE.$"

CableClub_Text_UnionRoomAdapterNotConnected:
	.string "Questa è la SALA UNIONE del CLUB\n"
	.string "WIRELESS POKéMON.\p"
	.string "Purtroppo il tuo Adattatore Wireless\n"
	.string "non è collegato bene.\p"
	.string "Torna a trovarci, mi raccomando.$"

@ Unused
CableClub_Text_OhExcuseMe:
	.string "Oh…\n"
	.string "Scusami!$"

CableClub_Text_PlayerIsWaiting:
	.string "Sembra che {STR_VAR_1} stia\n"
	.string "giocando ora.\l"
	.string "Forza, vai!$"

MossdeepCity_GameCorner_1F_Text_DescribeWhichGame:
	.string "Posso spiegarti le regole,\n"
	.string "se vuoi.\p"
	.string "Quale gioco ti descrivo?$"

MossdeepCity_GameCorner_1F_Text_PokemonJumpInfo:
	.string "“POKéMON JUMP”\p"
	.string "Fai saltare i tuoi POKéMON sopra la\n"
	.string "corda LIANA con il pulsante A.\p"
	.string "Solo i mini POKéMON alti circa 70 cm\n"
	.string "o meno possono partecipare.\p"
	.string "I POKéMON che nuotano, scavano o\n"
	.string "volano non sono bravi a saltare.\p"
	.string "Perciò quei POKéMON non possono\n"
	.string "partecipare.\p"
	.string "Succedono cose belle se tutti\n"
	.string "saltano a tempo.$"

MossdeepCity_GameCorner_1F_Text_DodrioBerryPickingInfo:
	.string "“DODRIO BERRY-PICKING”\p"
	.string "Guida le tre teste di DODRIO\n"
	.string "per prendere le BACche che cadono.\p"
	.string "Premi destra, su o sinistra sul\n"
	.string "{PLUS} Control Pad per muoverle.\p"
	.string "Per questo gioco serve\n"
	.string "un DODRIO.$"

MossdeepCity_GameCorner_1F_Text_TalkToOldManToPlay:
	.string "Se vuoi giocare,\n"
	.string "parla al vecchio accanto a me.$"

MossdeepCity_GameCorner_1F_Text_WelcomeCanYouWait:
	.string "Ciao, benvenuto!\n"
	.string "Sei qui per giocare usando la\l"
	.string "Comunicazione Wireless?\p"
	.string "Puoi aspettare un attimo?$"

MossdeepCity_GameCorner_1F_Text_ComeAgain:
	.string "Va bene, torna presto!$"

MossdeepCity_GameCorner_1F_Text_AdapterNotConnected:
	.string "L'Adattatore Wireless non è collegato.\n"
	.string "Torna quando l'avrai collegato!$"

MossdeepCity_GameCorner_1F_Text_PlayWhichGame:
	.string "Bene, a quale gioco vuoi\n"
	.string "giocare?$"

MossdeepCity_GameCorner_1F_Text_EnterWhichPokemon:
	.string "Quale POKéMON vuoi\n"
	.string "iscrivere?$"

MossdeepCity_GameCorner_1F_Text_AllGoodToGo:
	.string "Ok, è tutto pronto.\n"
	.string "Non lasciarti battere dagli altri!$"

@ Unused
MossdeepCity_GameCorner_1F_Text_LeavingDoComeAgain:
	.string "Te ne vai già?\n"
	.string "Torna a trovarci!$"

MossdeepCity_GameCorner_1F_Text_ExplainRequiredMon:
	.string "Non sembra che tu abbia dei\n"
	.string "POKéMON che possano partecipare…\p"
	.string "Vuoi che ti spieghi quali\n"
	.string "POKéMON possono partecipare?$"

MossdeepCity_GameCorner_1F_Text_ShortJumpingPokemonAllowed:
	.string "“POKéMON JUMP” è aperto ai POKéMON\n"
	.string "di 70 cm o meno.\p"
	.string "Non puoi iscrivere quelli\n"
	.string "che non sanno saltare.\p"
	.string "Tipo i POKéMON che solo\n"
	.string "nuotano, scavano o volano.\p"
	.string "Questo è tutto.$"

MossdeepCity_GameCorner_1F_Text_OnlyDodrioAllowed:
	.string "DODRIO BERRY-PICKING è un gioco a cui \n"
	.string "solo DODRIO può partecipare.$"

@ Unused
MossdeepCity_GameCorner_1F_Text_RetryPlease:
	.string "Potresti ricominciare tutto dall'inizio,\n"
	.string "per favore?$"

CableClub_Text_WelcomeWhichDirectCornerRoom:
	.string "Benvenuto nell'ANGOLO DIRETTO del\n"
	.string "CLUB WIRELESS POKéMON.\p"
	.string "Qui puoi interagire direttamente\n"
	.string "con i tuoi amici.\p"
	.string "In quale sala vuoi\n"
	.string "entrare?$"

CableClub_Text_TradePokemon:
	.string "Vuoi scambiare dei POKéMON?$"

CableClub_Text_PlayWhichBattleMode:
	.string "Quale Modalità Lotta vuoi\n"
	.string "giocare?$"

CableClub_Text_AccessRecordCorner:
	.string "Vuoi accedere\n"
	.string "all'ANGOLO RECORD?$"

CableClub_Text_UseBerryCrush:
	.string "Vuoi usare il Sistema\n"
	.string "SPRIMIBACCA?$"

CableClub_Text_ExplainBattleModes:
	.string "Ci sono tre modalità di lotta.\p"
	.string "SINGLE BATTLE è per due ALLENATORI\n"
	.string "con uno o più POKéMON ciascuno.\p"
	.string "Ogni ALLENATORE può avere un POKéMON\n"
	.string "in lotta alla volta.\p"
	.string "DOUBLE BATTLE è per due ALLENATORI\n"
	.string "con due o più POKéMON ciascuno.\p"
	.string "Ogni ALLENATORE manderà due\n"
	.string "POKéMON in lotta alla volta.\p"
	.string "MULTI BATTLE è per quattro ALLENATORI\n"
	.string "con uno o più POKéMON ciascuno.\p"
	.string "Ogni ALLENATORE può avere un POKéMON\n"
	.string "in lotta alla volta.$"

CableClub_Text_ChooseGroupLeaderOfTwo:
	.string "Decidete chi di voi due\n"
	.string "sarà il CAPO.\p"
	.string "L'altro giocatore deve poi scegliere\n"
	.string "“UNISCITI AL GRUPPO.”$"

CableClub_Text_ChooseGroupLeaderOfFour:
	.string "Decidete chi di voi quattro\n"
	.string "sarà il CAPO GRUPPO.\p"
	.string "Gli altri giocatori devono poi scegliere\n"
	.string "“UNISCITI AL GRUPPO.”$"

CableClub_Text_ChooseGroupLeader:
	.string "Decidete chi di voi\n"
	.string "sarà il CAPO GRUPPO.\p"
	.string "Gli altri giocatori devono poi scegliere\n"
	.string "“UNISCITI AL GRUPPO.”$"

CableClub_Text_WelcomeUnionRoomEnter:
	.string "Benvenuto nella SALA UNIONE del CLUB\n"
	.string "WIRELESS POKéMON.\p"
	.string "Qui puoi interagire direttamente\n"
	.string "con altri ALLENATORI, alcuni\l"
	.string "che potresti non conoscere.\p"
	.string "Vuoi entrare nella SALA?$"

CableClub_Text_UnionRoomInfo:
	.string "Gli ALLENATORI nella SALA UNIONE\n"
	.string "saranno i giocatori intorno a te\l"
	.string "che sono entrati anche loro.\p"
	.string "Qui puoi fare tante cose,\n"
	.string "come scambiarti saluti.\p"
	.string "Puoi far entrare due POKéMON fino\n"
	.string "al Lv. 30 per una lotta uno contro uno.\p"
	.string "Puoi partecipare a una chat con\n"
	.string "da due a cinque persone.\p"
	.string "Oppure puoi registrare un POKéMON\n"
	.string "da scambiare.\p"
	.string "Vuoi entrare nella SALA?$"

CableClub_Text_EnjoyUnionRoom:
	.string "Spero che ti divertirai nella\n"
	.string "SALA UNIONE.$"

CableClub_Text_FirstTimeRightThisWay:
	.string "Ciao!\n"
	.string "Mi chiamo TEALA.\p"
	.string "Questa dev'essere la tua prima\n"
	.string "visita quassù.\p"
	.string "Ti mostro come funziona il Sistema\n"
	.string "di Comunicazione Wireless.\p"
	.string "Prima ti mostro questo\n"
	.string "piano del nostro CENTRO POKéMON.\p"
	.string "Da questa parte, prego.$"

CableClub_Text_ExplainWirelessClubFirstTime:
	.string "All'ultimo piano ci sono due\n"
	.string "sale.\p"
	.string "Prima, la sala a sinistra.\n"
	.string "È la SALA UNIONE.\p"
	.string "Puoi collegarti con gli ALLENATORI\n"
	.string "intorno a te entrati\l"
	.string "nella SALA UNIONE.\p"
	.string "Con loro puoi chattare, lottare\n"
	.string "e scambiare.\p"
	.string "Seconda, la sala a destra è\n"
	.string "l'ANGOLO DIRETTO.\p"
	.string "Puoi scambiare o lottare con i\n"
	.string "POKéMON dei tuoi amici qui.\p"
	.string "Se l'Adattatore Wireless non è\n"
	.string "collegato, puoi comunque unirti\l"
	.string "con un cavo GBA Game Link.\p"
	.string "In tal caso, devi andare\n"
	.string "all'ANGOLO DIRETTO.\p"
	.string "Spero che apprezzerai il Sistema\n"
	.string "di Comunicazione Wireless.$"

CableClub_Text_AskAboutLinking:
	.string "Ciao, {PLAYER}!\p"
	.string "Sono io, TEALA, l'addetta al\n"
	.string "PIANO 2 del CENTRO POKéMON.\p"
	.string "Volevi chiedermi qualcosa\n"
	.string "sul collegamento?$"

CableClub_Text_ExplainWirelessClub:
	.string "Ti spiego come funziona il\n"
	.string "CLUB WIRELESS POKéMON.\p"
	.string "Qui, all'ultimo piano, ci sono\n"
	.string "due sale.\p"
	.string "Prima, la sala a sinistra.\n"
	.string "È la SALA UNIONE.\p"
	.string "Puoi collegarti con gli ALLENATORI\n"
	.string "intorno a te entrati\l"
	.string "nella SALA UNIONE.\p"
	.string "Con loro puoi chattare, lottare\n"
	.string "e scambiare.\p"
	.string "Seconda, la sala a destra è\n"
	.string "l'ANGOLO DIRETTO.\p"
	.string "Puoi scambiare o lottare con i\n"
	.string "POKéMON dei tuoi amici qui.\p"
	.string "A volte potresti non riuscire a\n"
	.string "trovare gli amici nella SALA UNIONE\l"
	.string "o nell'ANGOLO DIRETTO.\p"
	.string "In tal caso, avvicinati\n"
	.string "ai tuoi amici.\p"
	.string "Se l'Adattatore Wireless non è\n"
	.string "collegato, puoi comunque unirti\l"
	.string "con un cavo GBA Game Link.\p"
	.string "In tal caso, devi andare\n"
	.string "all'ANGOLO DIRETTO.\p"
	.string "Spero che apprezzerai il Sistema\n"
	.string "di Comunicazione Wireless.$"

CableClub_Text_HopeYouEnjoyWirelessSystem:
	.string "Spero che apprezzerai il Sistema\n"
	.string "di Comunicazione Wireless.$"
