Text_PictureBookShelf:
	.string "Ci sono dei libri illustrati sui POKéMON.$"

Text_BookShelf:
	.string "È pieno di libri di ogni genere.$"

Text_PokemonCenterBookShelf:
	.string "Riviste POKéMON!\n"
	.string "POKéMON PAL…\p"
	.string "POKéMON HANDBOOK…\n"
	.string "POKéMON ADORABILI…$"

Text_Vase:
	.string "Questo vaso sembra costoso…\n"
	.string "Ho guardato dentro…\p"
	.string "Ma era vuoto.$"

Text_EmptyTrashCan:
	.string "È vuoto.$"

Text_ShopShelf:
	.string "Gli scaffali straripano di\n"
	.string "merchandise POKéMON.$"

Text_Blueprint:
	.string "Una specie di progetto?\n"
	.string "È troppo complicato!$"
