@ Same as Hoenn's day-care text, used by the Four Island Day-Care. Unused text translated in Emerald

DayCare_Text_ImDaycareManSpeakToMyWife::
	.string "Sono il PENSIONATO.\p"
	.string "Mi prendo cura dei preziosi\n"
	.string "POKéMON degli ALLENATORI.\p"
	.string "Se vuoi che allievi i tuoi\n"
	.string "POKéMON, parla con mia moglie.$"

DayCare_Text_DoYouWantEgg::
	.string "Ah, sei tu!\p"
	.string "Stavamo allevando il tuo POKéMON e\n"
	.string "perbacco, che sorpresa!\p"
	.string "Il tuo POKéMON aveva un Uovo!\p"
	.string "Non sappiamo come sia finito lì,\n"
	.string "ma il tuo POKéMON lo aveva.\p"
	.string "Lo vuoi, vero?$"

DayCare_Text_YourMonIsDoingFine::
	.string "Ah, sei tu! Che piacere vederti.\n"
	.string "Il tuo {STR_VAR_1} sta bene.$"

DayCare_Text_IllKeepIt::
	.string "Beh, allora me lo terrò.\n"
	.string "Grazie!$"

DayCare_Text_YouHaveNoRoomForIt::
	.string "Non hai spazio per lui…\n"
	.string "Torna quando avrai fatto spazio.$"

DayCare_Text_ReceivedEgg::
	.string "{PLAYER} riceve l'UOVO da\n"
	.string "l'UOMO DEL CENTRO ALLEVAMENTO.$"

DayCare_Text_TakeGoodCareOfIt::
	.string "Prenditene cura.$"

DayCare_Text_SeeWifeIfYouWantToPickUpMon::
	.string "ポケモンを　ひきとりたい　ときは\n"
	.string "ばさんに　いって　おくれ$"

DayCare_Text_YourMonsAreDoingFine::
	.string "Ah, sei tu! Il tuo {STR_VAR_1} e\n"
	.string "{STR_VAR_2} stanno bene.$"

DayCare_Text_IWillKeepDoYouWantIt::
	.string "Me lo terrò davvero.\n"
	.string "Lo vuoi, vero?$"

DayCare_Text_WouldYouLikeUsToRaiseMon::
	.string "Sono la SIGNORA DEL CENTRO ALLEVAMENTO.\p"
	.string "Possiamo allenare i POKéMON per te.\p"
	.string "Vuoi che ne alleniamo uno?$"

DayCare_Text_WhichMonShouldWeRaise::
	.string "Quale POKéMON dobbiamo allenare\n"
	.string "per te?$"

DayCare_Text_WellRaiseYourMon::
	.string "Bene, alleveremo il tuo {STR_VAR_1}\n"
	.string "per un po'.\p"
	.string "Torna a riprenderlo più tardi.$"

DayCare_Text_WeCanRaiseOneMore::
	.string "Possiamo allevare due POKéMON.\p"
	.string "Vuoi che ne alleviamo un altro\n"
	.string "per te?$"

DayCare_Text_HusbandWasLookingForYou::
	.string "Mio marito ti stava cercando.$"

DayCare_Text_FineThenComeAgain::
	.string "Oh, va bene.\n"
	.string "Torna quando vuoi.$"

DayCare_Text_NotEnoughMoney::
	.string "Non hai abbastanza soldi…$"

DayCare_Text_TakeOtherOneBackToo::
	.string "Vuoi riprendere anche\n"
	.string "l'altro?$"

DayCare_Text_ComeAgain::
	.string "Va bene.\n"
	.string "Torna quando vuoi.$"

DayCare_Text_GoodToSeeYou::
	.string "Ah, sei tu!\n"
	.string "Che bello vederti.\p"
	.string "Il tuo POKéMON non può che stare\n"
	.string "bene!$"

DayCare_Text_YourMonHasGrownXLevels::
	.string "In quanto a livello, il tuo {STR_VAR_1}\n"
	.string "è cresciuto di {STR_VAR_2}.$"

DayCare_Text_YourPartyIsFull::
	.string "La tua squadra POKéMON è piena.\n"
	.string "Fai spazio e torna da me.$"

DayCare_Text_TakeBackWhichMon::
	.string "どっちの　ポケモンを　ひきとるかい？$"

DayCare_Text_ItWillCostX::
	.string "Se vuoi indietro {STR_VAR_1},\n"
	.string "ti costerà ¥{STR_VAR_2}.$"

DayCare_Text_HeresYourMon::
	.string "Perfetto!\n"
	.string "Ecco il tuo POKéMON.$"

DayCare_Text_TookBackMon::
	.string "{PLAYER} riprende {STR_VAR_1} dalla\n"
	.string "SIGNORA DEL CENTRO ALLEVAMENTO.$"

DayCare_Text_YouHaveJustOneMon::
	.string "Oh? Ma hai soltanto un\n"
	.string "POKéMON.\p"
	.string "Torna un'altra volta.$"

DayCare_Text_TakeYourMonBack::
	.string "Vuoi riprendere il tuo POKéMON?$"

DayCare_Text_WhatWillYouBattleWith::
	.string "Se mi lasci quel POKéMON,\n"
	.string "con cosa combatterai?\p"
	.string "Torna un'altra volta.$"

DayCare_Text_Huh::
	.string "Eh?$"
