EventTicket_Text_ShowOldSeaMap:
	.string "Il traghetto per PORTO ALGHE…\p"
	.string "Come dici?\n"
	.string "Possiamo salpare verso questo posto?\p"
	.string "Conosco chi ti aiuterà meglio.\n"
	.string "Attendi, prego.$"

EventTicket_Text_ThatPass:
	.string "Il traghetto per SLATEPORT è…\p"
	.string "Oh?\n"
	.string "Quel Superpass…$"

EventTicket_Text_ShowEonTicket:
	.string "Ehi, amico, sei tu quello che ha\n"
	.string "quel Superpass così strano?\p"
	.string "Ti dico, stai cercando di raggiungere una\n"
	.string "piccola isola sperduta a sud.\p"
	.string "Chissà cosa incontreremo\n"
	.string "una volta arrivati, eh.\l"
	.string "Mi tremano le ossa!\p"
	.string "Tutti a bordo!$"

#if IS_HNS
EventTicket_Text_SouthernIslandSailBack:
	.string "Ehi, amico, non c'è niente da\n"
	.string "vedere o fare su quest'isola dimenticata.\p"
	.string "Che ne dici di tornare a OLIVINE?$"
#else
EventTicket_Text_SouthernIslandSailBack:
	.string "Aye, mate, there's nothing here to\n"
	.string "see or do on this forgettable island.\p"
	.string "What say we sail back to LILYCOVE?$"
#endif 


EventTicket_Text_SailHome:
	.string "Va bene, allora!\n"
	.string "Torniamo a casa!$"

EventTicket_Text_AsYouLike:
	.string "Va bene, come vuoi, allora.$"

SouthernIsland_Interior_Text_Sign:
	.string "“Ogni sogno è un'altra realtà.\n"
	.string "Non dimenticare mai…”$"

SouthernIsland_Exterior_Text_Sign:
	.string "“Chi perde i ricordi cerca di\n"
	.string "inciderli nel cuore…”$"
