EventTicket_Text_OldSeaMapTooFar:
	.string "Che succede, ragazzo?\p"
	.string "Cosa, sei tu quello che dovrebbe avere\n"
	.string "una vecchia mappa sgualcita?\p"
	.string "Vediamo un po'.\n"
	.string "… … … … … …\p"
	.string "Ragazzo, è davvero lontana.\n"
	.string "Temo di non poterti aiutare…$"

EventTicket_Text_BrineyHoldOnASecond:
	.string "BRINEY: Aspetta un attimo!\p"
	.string "Come ti viene in mente di dire di no\n"
	.string "a chi ti deve così tanto?$"

EventTicket_Text_BrineyLetsSail:
	.string "{PLAYER}{KUN}, mi dispiace tanto.\p"
	.string "Sei venuto da me per un aiuto,\n"
	.string "e ti stavo quasi cacciando via.\p"
	.string "Lascia che rimedi.\p"
	.string "Salperemo subito, certo!\p"
	.string "Troviamo quest'isola su\n"
	.string "questa VECCHIA MAPPA MARINA!$"

EventTicket_Text_OddTicketGetOnBoard:
	.string "Sei tu che hai portato quel\n"
	.string "biglietto strano?\p"
	.string "Dove vuoi andare è un'isola\n"
	.string "molto, molto lontana.\p"
	.string "Nessuno sa cosa ci attende…\p"
	.string "Il solo pensiero mi fa ribollire il sangue\n"
	.string "da marinaio!\p"
	.string "Sali a bordo, ragazzo!$"

FarawayIsland_Entrance_Text_SailorReturn:
	.string "CAP. BRINEY può essere irritante\n"
	.string "volubile…\p"
#if IS_HNS
	.string "Vuoi tornare a OLIVINE?$"
#else
	.string "Do you want to return to LILYCOVE?$"
#endif

BirthIsland_Harbor_Text_SailorReturn:
	.string "Che isola dalla forma strana, eh?\n"
#if IS_HNS
	.string "Vuoi tornare a OLIVINE?$"
#else
	.string "Do you want to return to LILYCOVE?$"
#endif

EventTicket_Text_OddTicketsWhereTo:
	.string "Sei tu che hai portato quei\n"
	.string "biglietti strani?\p"
	.string "… … …Hm.\p"
	.string "Questi biglietti ti porteranno su isole\n"
	.string "molto, molto lontane.\p"
	.string "Nessuno sa cosa ci attende,\n"
	.string "né cosa potrà succedere.\p"
	.string "Il solo pensiero mi fa ribollire il sangue\n"
	.string "da marinaio!\p"
	.string "Sali a bordo, ragazzo!\n"
	.string "Dove salpiamo prima?$"

NavelRock_Harbor_Text_SailorReturn:
	.string "Hai… Hai sentito anche tu?\n"
	.string "Quel ringhio cupo dal profondo.\p"
	.string "Sei sicuro che sia sicuro?\n"
	.string "Non credi che dovremmo andare via?$"

FarawayIsland_Entrance_Text_Sign:
	.string "La scrittura svanisce, come se fosse\n"
	.string "stata scritta molto tempo fa…\p"
	.string "“…bre, sesto giorno\n"
	.string "Se qualche umano…mette piede qui…\l"
	.string "ancora…ia una persona gentile…\l"
	.string "…on questa speranza, me ne vado…”$"

FarawayIsland_Interior_Text_Mew:
	.string "Miu…$"
