gFameCheckerFlavorText_ProfOak0:: @ 0x81AD106
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Cosa fa questa persona?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LABORATORIO POKéMON OAK$"

gFameCheckerFlavorText_ProfOak1:: @ 0x81AD145
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Come è questa persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Creare una guida completa su\n"
	.string "tutti i POKéMON del mondo…\p"
	.string "Era il mio sogno!$"

gFameCheckerFlavorText_ProfOak2:: @ 0x81AD1BB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Come è questa persona?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Il PROF. OAK non sembra granché,\n"
	.string "ma è l'autorità sui POKéMON.\p"
	.string "Molti ALLENATORI lo tengono in\n"
	.string "grande considerazione.$"

gFameCheckerFlavorText_ProfOak3:: @ 0x81AD258
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Famiglia e amici?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Il PROF. OAK vive coi nipoti,\n"
	.string "DAISY e {RIVAL}.$"

gFameCheckerFlavorText_ProfOak4:: @ 0x81AD2B9
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Famiglia e amici?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Sento che OAK si è molto\n"
	.string "interessato a te, ragazzo.\p"
	.string "Quel vecchio era forte e\n"
	.string "affascinante.\p"
	.string "Ma decenni fa.\n"
	.string "Ora è l'ombra di sé stesso.$"

gFameCheckerFlavorText_ProfOak5:: @ 0x81AD377
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Cosa fa questa persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Il PROF. OAK avrà presto un suo\n"
	.string "programma radio.\p"
	.string "Si chiamerà IL SEMINARIO\n"
	.string "SUI POKéMON DEL PROF. OAK.$"

gFameCheckerFlavorText_Daisy0:: @ 0x81AD40C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che lavoro fa?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Se mostri un POKéMON a DAISY,\n"
	.string "lei ti dice quanto le piace.\p"
	.string "A volte ti toeletta anche\n"
	.string "un POKéMON.$"

gFameCheckerFlavorText_Daisy1:: @ 0x81AD4AE
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che tipo è?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Ma chi è più amata dai POKéMON\n"
	.string "credo sia DAISY.$"

gFameCheckerFlavorText_Daisy2:: @ 0x81AD516
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che tipo è?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Toelettava i POKéMON con dolcezza…\n"
	.string "Era un angioletto.\p"
	.string "Il nome di quella bambina…\n"
	.string "Mi pare fosse DAISY.$"

gFameCheckerFlavorText_Daisy3:: @ 0x81AD5A7
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Famiglia e amici?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Il PROF. OAK vive coi nipoti,\n"
	.string "DAISY e {RIVAL}.$"

gFameCheckerFlavorText_Daisy4:: @ 0x81AD608
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che tipo è?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}DAISY, una ragazza di BIANCAVILLA,\n"
	.string "beve Tè ogni giorno.\p"
	.string "Va al CENTRO COMMERCIALE di\n"
	.string "AZZURROPOLI a comprare il Tè.$"

gFameCheckerFlavorText_Daisy5:: @ 0x81AD69F
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Gira una voce…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}La campionessa del CONCORSO\n"
	.string "POKéMON di primavera è DAISY OAK di\l"
	.string "BIANCAVILLA!$"

gFameCheckerFlavorText_Brock0:: @ 0x81AD705
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che lavoro fa?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}PALESTRA POKéMON DI PLUMBEOPOLI\n"
	.string "CAPO: BROCK\l"
	.string "L'allenatore roccioso!$"

gFameCheckerFlavorText_Brock1:: @ 0x81AD771
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}POKéMON preferiti?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}La mia volontà di roccia si vede\n"
	.string "anche nei miei POKéMON.\p"
	.string "Sono tutti duri come pietre e\n"
	.string "hanno una gran determinazione.\p"
	.string "Esatto: i miei POKéMON sono\n"
	.string "tutti di tipo ROCCIA!$"

gFameCheckerFlavorText_Brock2:: @ 0x81AD840
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che tipo è?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Qui non ci sono molti allenatori\n"
	.string "POKéMON seri.\p"
	.string "Sono tutti PIGLIAMOSCHE,\n"
	.string "sai, semplici hobbisti.\p"
	.string "Ma BROCK della palestra di\n"
	.string "PLUMBEOPOLI non è così.$"

gFameCheckerFlavorText_Brock3:: @ 0x81AD908
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che tipo è?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BROCK è forte, e non solo di muscoli.\n"
	.string "La gente lo stima e gli vuole bene.\p"
	.string "Voglio diventare CAPOPALESTRA\n"
	.string "come lui.$"

gFameCheckerFlavorText_Brock4:: @ 0x81AD99A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che lavoro fa?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Ciao, scavo fossili qui sotto\n"
	.string "il MONTE LUNA.\p"
	.string "A volte BROCK della palestra di\n"
	.string "PLUMBEOPOLI mi dà una mano.$"

gFameCheckerFlavorText_Brock5:: @ 0x81ADA27
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che tipo è?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BROCK ride di rado, ma dicono che\n"
	.string "poi non riesca più a smettere.$"

gFameCheckerFlavorText_Misty0:: @ 0x81ADA91
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Cosa fa questa persona?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}PALESTRA POKéMON di\n"
	.string "CELESTOPOLI: MISTY\l"
	.string "La sirenetta maschiaccio!$"

gFameCheckerFlavorText_Misty1:: @ 0x81ADAF6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Tipo di POKéMON preferito?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}La mia tattica è un attacco\n"
	.string "totale coi POKéMON d'ACQUA!$"

gFameCheckerFlavorText_Misty2:: @ 0x81ADB5A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Come è questa persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}MISTY è un'ALLENATRICE che\n"
	.string "continuerà a migliorare.\p"
	.string "Non perderà con uno come te!$"

gFameCheckerFlavorText_Misty3:: @ 0x81ADBD9
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Gira una voce…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}ALLENATORI forti e POKéMON\n"
	.string "d'ACQUA sono comuni da queste parti.\p"
	.string "Dicono che MISTY della PALESTRA\n"
	.string "di CELESTOPOLI si alleni qui.$"

gFameCheckerFlavorText_Misty4:: @ 0x81ADC72
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Corre voce…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Questo capo è un famoso luogo d'incontri.\p"
	.string "MISTY, la CAPOPALESTRA, ci tiene\n"
	.string "molto a questo posto.$"

gFameCheckerFlavorText_Misty5:: @ 0x81ADCEB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Gira una voce…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Si dice che MISTY adori LORELEI\n"
	.string "dei SUPERQUATTRO.$"

gFameCheckerFlavorText_LtSurge0:: @ 0x81ADD3C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Cosa fa questa persona?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}PALESTRA POKéMON di\n"
	.string "ARANCIONI: LT. SURGE\l"
	.string "L'americano del fulmine!$"

gFameCheckerFlavorText_LtSurge1:: @ 0x81ADDA7
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Tipo di POKéMON preferito?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Ti dico, ragazzo, i POKéMON\n"
	.string "elettrici mi salvarono in guerra!$"

gFameCheckerFlavorText_LtSurge2:: @ 0x81ADE0B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Come è questa persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Quando ero nell'esercito, LT. SURGE\n"
	.string "era il mio comandante severo.\p"
	.string "Era un capo inflessibile.$"

gFameCheckerFlavorText_LtSurge3:: @ 0x81ADE82
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Come è questa persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LT. SURGE era famoso\n"
	.string "per la sua prudenza nell'esercito.$"

gFameCheckerFlavorText_LtSurge4:: @ 0x81ADEEC
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Come è questa persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LT. SURGE installò le trappole\n"
	.string "della PALESTRA di persona.\p"
	.string "Mise doppie serrature ovunque.$"

gFameCheckerFlavorText_LtSurge5:: @ 0x81ADF6A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Gira una voce…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Si dice che LT. SURGE sia stato\n"
	.string "pilota quando viveva in America.\p"
	.string "Usava l'elettricità generata\n"
	.string "dai POKéMON per il suo aereo.$"

gFameCheckerFlavorText_Erika0:: @ 0x81AE009
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che lavoro fa?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}PALESTRA POKéMON DI AZZURROPOLI\n"
	.string "CAPO: ERIKA\l"
	.string "La principessa amante della natura!$"

gFameCheckerFlavorText_Erika1:: @ 0x81AE072
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}POKéMON preferiti?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Studio l'arte della\n"
	.string "composizione floreale.\p"
	.string "I miei POKéMON sono tutti di\n"
	.string "tipo ERBA.$"

gFameCheckerFlavorText_Erika2:: @ 0x81AE0F3
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che tipo è?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}La nostra CAPO ERIKA sarà Quieta,\n"
	.string "ma qui è famosa.$"

gFameCheckerFlavorText_Erika3:: @ 0x81AE15B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che tipo è?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}In palestra usiamo solo POKéMON\n"
	.string "di tipo ERBA.\p"
	.string "Perché? Ci servono anche per\n"
	.string "la composizione floreale!$"

gFameCheckerFlavorText_Erika4:: @ 0x81AE1E5
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}POKéMON preferiti?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Non collezionerei mai POKéMON\n"
	.string "se fossero brutti.$"

gFameCheckerFlavorText_Erika5:: @ 0x81AE247
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Gira una voce…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Si dice che sbirciando nella\n"
	.string "palestra di AZZURROPOLI si veda\l"
	.string "spesso ERIKA che dorme.$"

gFameCheckerFlavorText_Koga0:: @ 0x81AE2B6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che lavoro fa?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}PALESTRA POKéMON DI FUCSIAPOLI\n"
	.string "CAPO: KOGA\l"
	.string "Il maestro Ninja del Veleno$"

gFameCheckerFlavorText_Koga1:: @ 0x81AE31D
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}POKéMON preferiti?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Rassegnati all'orrore strisciante dei\n"
	.string "POKéMON di tipo VELENO!$"

gFameCheckerFlavorText_Koga2:: @ 0x81AE37D
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che tipo è?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Anche se ho perso, continuerò ad\n"
	.string "allenarmi seguendo gli insegnamenti\l"
	.string "di KOGA, il mio maestro Ninja.$"

gFameCheckerFlavorText_Koga3:: @ 0x81AE407
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Famiglia e amici?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Mio padre è il CAPOPALESTRA di\n"
	.string "questa città.\p"
	.string "Mi alleno coi POKéMON VELENO\n"
	.string "proprio come lui.$"

gFameCheckerFlavorText_Koga4:: @ 0x81AE48D
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Gira una voce…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Si dice che KOGA abbia una grande\n"
	.string "conoscenza delle medicine.\p"
	.string "Prepara medicine per rimettere\n"
	.string "in salute i suoi POKéMON.$"

gFameCheckerFlavorText_Koga5:: @ 0x81AE51B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Cosa fa questa persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}La ZONA SAFARI è enorme, non\n"
	.string "credi?\p"
	.string "KOGA, CAPOPALESTRA di FUCSIAPOLI, \n"
	.string "patrolla la zona ogni tanto.\p"
	.string "Grazie a lui, possiamo giocare qui\n"
	.string "sapendo di essere al sicuro.$"

gFameCheckerFlavorText_Sabrina0:: @ 0x81AE5E8
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Cosa fa questa persona?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}PALESTRA POKéMON di\n"
	.string "ZAFFERANO: SABRINA\l"
	.string "La maestra dei POKéMON PSICHICI!$"

gFameCheckerFlavorText_Sabrina1:: @ 0x81AE656
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Tipo di POKéMON preferito?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Conosci una ragazza CAPOPALESTRA\n"
	.string "a ZAFFERANO?\p"
	.string "Usa POKéMON di tipo PSICHICO,\n"
	.string "vero?$"

gFameCheckerFlavorText_Sabrina2:: @ 0x81AE6D7
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Com'è questa persona?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Ho poteri psichici da quando\n"
	.string "ero bambina.\p"
	.string "È iniziato quando un cucchiaio\n"
	.string "che lanciai per gioco si piegò.$"

gFameCheckerFlavorText_Sabrina3:: @ 0x81AE762
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Com'è questa persona?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Non amo lottare, ma se vuoi,\n"
	.string "ti mostrerò i miei poteri!$"

gFameCheckerFlavorText_Sabrina4:: @ 0x81AE7CB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Gira una voce…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Dicono che SABRINA sappia\n"
	.string "comunicare con i suoi POKéMON\l"
	.string "in lotta senza parlare.$"

gFameCheckerFlavorText_Sabrina5:: @ 0x81AE841
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Com'è questa persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}SABRINA ha appena stracciato il\n"
	.string "MAESTRO KARATE qui accanto.$"

gFameCheckerFlavorText_Blaine0:: @ 0x81AE89E
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Cosa fa questa persona?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}PALESTRA POKéMON DI ISOLA CANNELLA\n"
	.string "CAPO: BLAINE\l"
	.string "Il Maestro dei Quiz Impetuoso!$"

gFameCheckerFlavorText_Blaine1:: @ 0x81AE90A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}POKéMON preferiti?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I miei POKéMON di fuoco sono tutti\n"
	.string "belli caldi e pieni di energia!\p"
	.string "Bruciano tutti gli sfidanti!$"

gFameCheckerFlavorText_Blaine2:: @ 0x81AE990
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}POKéMON preferiti?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Il nostro CAPO BLAINE si perse\n"
	.string "nelle montagne per davvero.\p"
	.string "Scese la notte e apparve un\n"
	.string "POKéMON uccello fiammeggiante.\p"
	.string "La sua luce permise a BLAINE di\n"
	.string "trovare la strada in salvo.$"

gFameCheckerFlavorText_Blaine3:: @ 0x81AEA59
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che persona è?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BLAINE della PALESTRA di ISOLA\n"
	.string "CANNELLA è un tipo davvero strano.\p"
	.string "Vive sull'isola da molto\n"
	.string "prima che costruissero il LAB.$"

gFameCheckerFlavorText_Blaine4:: @ 0x81AEAEE
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Famiglia e amici?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}È una foto di BLAINE e\n"
	.string "SIGNOR FUJI.\p"
	.string "Sono spalla a spalla con\n"
	.string "un gran sorriso.$"

gFameCheckerFlavorText_Blaine5:: @ 0x81AEB69
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Gira una voce…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Si dice che BLAINE tolga gli\n"
	.string "occhiali scuri solo quando pensa a\l"
	.string "nuove domande per il quiz.$"

gFameCheckerFlavorText_Lorelei0:: @ 0x81AEBDF
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Cosa fa questa persona?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Sono LORELEI dei SUPERQUATTRO.$"

gFameCheckerFlavorText_Lorelei1:: @ 0x81AEC28
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Tipo di POKéMON preferito?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Con i POKéMON di ghiaccio\n"
	.string "non mi batte nessuno.$"

gFameCheckerFlavorText_Lorelei2:: @ 0x81AEC82
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Dove è nata questa persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Su quest'isola è cresciuta\n"
	.string "un'ALLENATRICE forte e potente.\p"
	.string "Scommetto che la conosci.\n"
	.string "È LORELEI dei SUPERQUATTRO!$"

gFameCheckerFlavorText_Lorelei3:: @ 0x81AED27
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Come è questa persona?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Nota per lo stile logico,\n"
	.string "calcolato e freddo, LORELEI\l"
	.string "ha un segreto sorprendente!$"

gFameCheckerFlavorText_Lorelei4:: @ 0x81AEDAA
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Come è questa persona?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Sapevi che LORELEI ha un sacco\n"
	.string "e sacco di peluche?\p"
	.string "Ogni volta che torna\n"
	.string "all'ISOLA QUATTRO, cresce!$"

gFameCheckerFlavorText_Lorelei5:: @ 0x81AEE51
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Tipo di POKéMON preferito?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Il LAPRAS che ha, immagino sia\n"
	.string "quello che incontrò da bambina.\p"
	.string "Credo sia nella GROTTA\n"
	.string "GELATA che lo catturò.\p"
	.string "Forse quel POKéMON le è\n"
	.string "rimasto accanto da allora.$"

gFameCheckerFlavorText_Bruno0:: @ 0x81AEF25
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che lavoro fa?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Sono BRUNO dei SUPERQUATTRO!$"

gFameCheckerFlavorText_Bruno1:: @ 0x81AEF6C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}POKéMON preferiti?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Ho vissuto e mi sono allenato con\n"
	.string "i miei POKéMON lottatori!$"

gFameCheckerFlavorText_Bruno2:: @ 0x81AEFC6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che tipo è?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BRUNO è entrato nei SUPERQUATTRO\n"
	.string "per la smania di sfidare i\l"
	.string "migliori allenatori.$"

gFameCheckerFlavorText_Bruno3:: @ 0x81AF04C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che tipo è?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BRUNO, che è più anziano di me,\n"
	.string "a volte va alle terme.\p"
	.string "Ci va per curare gli infortuni,\n"
	.string "suoi e dei suoi POKéMON.$"

gFameCheckerFlavorText_Bruno4:: @ 0x81AF0F0
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Gira una voce…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}È uno dei SUPERQUATTRO.\n"
	.string "Si chiama BRUNO.\p"
	.string "Se n'è andato deluso quando ha\n"
	.string "scoperto che erano finiti\l"
	.string "i dolcetti Ira.$"

gFameCheckerFlavorText_Bruno5:: @ 0x81AF19A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Famiglia e amici?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Anche BRUNO…\n"
	.string "Si è allenato con un certo\l"
	.string "BRAWLY, tempo fa.$"

gFameCheckerFlavorText_Agatha0:: @ 0x81AF200
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Cosa fa questa persona?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Sono AGATHA dell'ELITE FOUR.$"

gFameCheckerFlavorText_Agatha1:: @ 0x81AF248
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}POKéMON preferiti?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I POKéMON di tipo Spettro di\n"
	.string "AGATHA sono spaventosamente duri.$"

gFameCheckerFlavorText_Agatha2:: @ 0x81AF2B7
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che persona è?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Quella vecchia signora ha anche\n"
	.string "un caratterino bello corto.\p"
	.string "Non ci vuole niente per far\n"
	.string "gridare quella signora spaventosa.$"

gFameCheckerFlavorText_Agatha3:: @ 0x81AF34E
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}C'è una voce…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Da giovane, AGATHA e il PROF.\n"
	.string "OAK erano rivali che si sfidavano\l"
	.string "per la supremazia come ALLENATORI.$"

gFameCheckerFlavorText_Agatha4:: @ 0x81AF3BE
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Famiglia e amici?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Sento che OAK si è molto\n"
	.string "interessato a te, ragazzo.\p"
	.string "Quel vecchio era forte e\n"
	.string "affascinante.\p"
	.string "Ma decenni fa.\n"
	.string "Ora è l'ombra di sé stesso.$"

gFameCheckerFlavorText_Agatha5:: @ 0x81AF47C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che persona è?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Prendi AGATHA, per esempio.\p"
	.string "Ha stabilito il record di membro\n"
	.string "più anziano dell'ELITE FOUR.$"

gFameCheckerFlavorText_Lance0:: @ 0x81AF4FD
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che lavoro fa?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Guido i SUPERQUATTRO.\p"
	.string "Puoi chiamarmi LANCE, l'allenatore\n"
	.string "drago.$"

gFameCheckerFlavorText_Lance1:: @ 0x81AF567
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}POKéMON preferiti?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Sai che i draghi sono POKéMON\n"
	.string "mitici.\p"
	.string "Sono difficili da catturare e allevare,\n"
	.string "ma la loro forza è superiore.\p"
	.string "Sono quasi indistruttibili.\n"
	.string "Non ci puoi usare astuzia.$"

gFameCheckerFlavorText_Lance2:: @ 0x81AF641
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Come è questa persona?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}È un paladino di giustizia!\n"
	.string "È forte, ma anche passionale!\l"
	.string "È il più grande, LANCE!$"

gFameCheckerFlavorText_Lance3:: @ 0x81AF6BA
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Gira una voce…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Abbiamo un cliente, LANCE, che\n"
	.string "viene ogni tanto.\p"
	.string "Compra sempre dei mantelli.\p"
	.string "Chissà… Ne avrà molti\n"
	.string "identici a casa?$"

gFameCheckerFlavorText_Lance4:: @ 0x81AF758
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Famiglia e amici?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Si dice che il nonno di LANCE\n"
	.string "sia l'anziano di un famoso clan\l"
	.string "di maestri dei draghi.$"

gFameCheckerFlavorText_Lance5:: @ 0x81AF7CB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Famiglia e amici?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Da quel che ho sentito, LANCE ha\n"
	.string "un cugino CAPOPALESTRA\l"
	.string "da qualche parte lontano.$"

gFameCheckerFlavorText_Bill0:: @ 0x81AF83E
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Cosa fa questa persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BILL è famoso in tutto il mondo\n"
	.string "come POKéMANIAC.\p"
	.string "Ha anche inventato il Sistema\n"
	.string "di Memorizzazione POKéMON del PC.$"

gFameCheckerFlavorText_Bill1:: @ 0x81AF8CA
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}POKéMON preferiti?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BILL ha un sacco di POKéMON!\n"
	.string "Colleziona anche quelli rari!$"

gFameCheckerFlavorText_Bill2:: @ 0x81AF929
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che persona è?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}È mio nipote!\p"
	.string "Gli è sempre piaciuto collezionare\n"
	.string "cose, anche da bambino!$"

gFameCheckerFlavorText_Bill3:: @ 0x81AF998
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}POKéMON preferiti?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BILL è un POKéMANIAC, li ama\n"
	.string "tutti quanti.\p"
	.string "Pare che il primo che ha preso\n"
	.string "fosse un ABRA.$"

gFameCheckerFlavorText_Bill4:: @ 0x81AFA20
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Famiglia e amici?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BILL viene da FIORLISOPOLI,\n"
	.string "dove vivono ancora i suoi.\p"
	.string "Ho sentito che è una città\n"
	.string "festosa e piena di vita.$"

gFameCheckerFlavorText_Bill5:: @ 0x81AFAB9
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}C'è una voce…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Pare che BILL non riesca\n"
	.string "proprio a mandar giù il latte.$"

gFameCheckerFlavorText_MrFuji0:: @ 0x81AFB0C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Cosa fa questa persona?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}È molto gentile.\p"
	.string "Si prende cura dei POKéMON\n"
	.string "abbandonati e orfani.$"

gFameCheckerFlavorText_MrFuji1:: @ 0x81AFB76
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Come è questa persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Questo vecchietto è arrivato\n"
	.string "dritto al nostro NASCONDIGLIO.\p"
	.string "Poi si è messo a strillare che\n"
	.string "il TEAM ROCKET maltratta i POKéMON.\p"
	.string "Così ne stiamo parlando\n"
	.string "da adulti.$"

gFameCheckerFlavorText_MrFuji2:: @ 0x81AFC38
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Come è questa persona?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}RIVISTA FAN DEI POKéMON\n"
	.string "Estrazione mensile!\p"
	.string "Il modulo di iscrizione è…\p"
	.string "Sparito! È stato ritagliato.\n"
	.string "Qualcuno si sarà già iscritto.$"

gFameCheckerFlavorText_MrFuji3:: @ 0x81AFCE9
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Gira una voce…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Sento che neppure il SIG. FUJI\n"
	.string "è originario di queste parti.$"

gFameCheckerFlavorText_MrFuji4:: @ 0x81AFD49
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Famiglia e amici?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}È una foto di BLAINE e\n"
	.string "SIGNOR FUJI.\p"
	.string "Sono spalla a spalla con\n"
	.string "un gran sorriso.$"

gFameCheckerFlavorText_MrFuji5:: @ 0x81AFDC4
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Come è questa persona?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Redattore: il timido SIG. FUJI ha\n"
	.string "rifiutato le nostre interviste.\p"
	.string "È un uomo gentile, adorato\n"
	.string "e rispettato a LAVANDONIA.$"

gFameCheckerFlavorText_Giovanni0:: @ 0x81AFE68
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che lavoro fa?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Il TEAM ROCKET cattura POKéMON in\n"
	.string "tutto il mondo.\p"
	.string "Sono strumenti preziosi per andare\n"
	.string "avanti con i nostri affari.\p"
	.string "Sono il capo, GIOVANNI!$"

gFameCheckerFlavorText_Giovanni1:: @ 0x81AFF23
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}POKéMON preferiti?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Quei teppisti che hanno occupato\n"
	.string "il nostro palazzo…\p"
	.string "Il loro CAPO cercava\n"
	.string "POKéMON forti.$"

gFameCheckerFlavorText_Giovanni2:: @ 0x81AFFA8
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che tipo è?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Il CAPO del TEAM ROCKET è\n"
	.string "Sanguefreddo!\p"
	.string "Per lui i POKéMON sono solo\n"
	.string "strumenti da usare.$"

gFameCheckerFlavorText_Giovanni3:: @ 0x81B0022
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che lavoro fa?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Benvenuto nel mio covo!\p"
	.string "Lo resterà finché non riporterò\n"
	.string "il TEAM ROCKET al suo splendore.$"

gFameCheckerFlavorText_Giovanni4:: @ 0x81B00A6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che lavoro fa?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Non ci credo! GIOVANNI era il\n"
	.string "CAPOPALESTRA di SMERALDOPOLI?$"

gFameCheckerFlavorText_Giovanni5:: @ 0x81B0106
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Famiglia e amici?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Tu… Non sarai mica il figlio\n"
	.string "di GIOVANNI?\p"
	.string "No, impossibile.\n"
	.string "Il figlio di GIOVANNI ha i capelli rossi.$"


gFameCheckerPersonName_ProfOak:: @ 0x81B0188
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}PROF. OAK$"

gFameCheckerPersonQuote_ProfOak:: @ 0x81B0198
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Da: PROF. OAK\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Perché i POKéMON lottano e si\n"
	.string "impegnano tanto per te?\p"
	.string "Lo fanno perché vedono\n"
	.string "l'amore e la fiducia che hai\l"
	.string "verso i POKéMON.\p"
	.string "Non dimenticarlo mai.$"

gFameCheckerPersonName_Daisy:: @ 0x81B0251
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}DAISY$"

gFameCheckerPersonQuote_Daisy:: @ 0x81B025D
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Da: DAISY\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Mentre io mi godevo tranquilla\n"
	.string "le mie pause Tè, tu sei cresciuto\l"
	.string "molto e sei diventato forte.\p"
	.string "Spero resterai un buon rivale\n"
	.string "per mio fratello.$"

gFameCheckerPersonName_Brock:: @ 0x81B030F
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}BROCK$"

gFameCheckerPersonQuote_Brock:: @ 0x81B031B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Da: BROCK\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}In questo nostro gran mondo ci\n"
	.string "saranno molti ALLENATORI forti.\p"
	.string "Continuiamo ad allenarci e a\n"
	.string "diventare più forti insieme!$"

gFameCheckerPersonName_Misty:: @ 0x81B03B3
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}MISTY$"

gFameCheckerPersonQuote_Misty:: @ 0x81B03BF
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Da: MISTY\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Continuerò ad allenarmi qui in\n"
	.string "questa PALESTRA.\p"
	.string "Quando sarò più brava, vorrei\n"
	.string "andare in giro a viaggiare.$"

gFameCheckerPersonName_LtSurge:: @ 0x81B0446
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}LT. SURGE$"

gFameCheckerPersonQuote_LtSurge:: @ 0x81B0456
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Da: LT. SURGE\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Ehi, ragazzo!\n"
	.string "Mi hai caricato a mille nella lotta!\p"
	.string "Non sapevo che esistessero\n"
	.string "ALLENATORI così coraggiosi.\p"
	.string "Mi hai fatto cambiare idea\n"
	.string "su di te!$"

gFameCheckerPersonName_Erika:: @ 0x81B0504
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}ERIKA$"

gFameCheckerPersonQuote_Erika:: @ 0x81B0510
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Da: ERIKA\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Sono felice che esistano ALLENATORI\n"
	.string "forti come te.\p"
	.string "Saperlo mi ispira e mi spinge\n"
	.string "a impegnarmi di più.\p"
	.string "Torna a trovarmi.\n"
	.string "Zzz…$"

gFameCheckerPersonName_Koga:: @ 0x81B05C2
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}KOGA$"

gFameCheckerPersonQuote_Koga:: @ 0x81B05CD
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Da: KOGA\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Io e te dobbiamo puntare più in alto\n"
	.string "e lavorare per affrontare\l"
	.string "le nostre sfide.\p"
	.string "Ora devo andare ad allenare mia figlia.$"

gFameCheckerPersonName_Sabrina:: @ 0x81B0667
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}SABRINA$"

gFameCheckerPersonQuote_Sabrina:: @ 0x81B0675
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Da: SABRINA\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}L'amore che provi verso i tuoi\n"
	.string "POKéMON…\p"
	.string "È un potere che i miei poteri\n"
	.string "psichici non hanno mai battuto.$"

gFameCheckerPersonName_Blaine:: @ 0x81B06FB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}BLAINE$"

gFameCheckerPersonQuote_Blaine:: @ 0x81B0708
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Da: BLAINE\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I miei POKéMON di FUOCO!\n"
	.string "Diventeranno ancora più forti!\p"
	.string "E ora un quiz. Quanti tipi di\n"
	.string "POKéMON di tipo FUOCO esistono?$"

gFameCheckerPersonName_Lorelei:: @ 0x81B079F
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}LORELEI$"

gFameCheckerPersonQuote_Lorelei:: @ 0x81B07AD
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Da: LORELEI\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Volevo ringraziarti per il tuo\n"
	.string "aiuto.\p"
	.string "Ma ciò non ha nulla a che fare con\n"
	.string "le nostre lotte.\p"
	.string "Attento la prossima volta!$"

gFameCheckerPersonName_Bruno:: @ 0x81B0845
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}BRUNO$"

gFameCheckerPersonQuote_Bruno:: @ 0x81B0851
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Da: BRUNO\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}La super forza dei tuoi POKéMON\n"
	.string "e la tua l'ho provata io stesso.\p"
	.string "La prossima volta potrei mostrarti\n"
	.string "come allenarti da solo.$"

gFameCheckerPersonName_Agatha:: @ 0x81B08EE
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}AGATHA$"

gFameCheckerPersonQuote_Agatha:: @ 0x81B08FB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Da: AGATHA\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Da grande, non ti azzardare a\n"
	.string "rammollirti come quel rimbambito di OAK!\p"
	.string "Fai come me e continua a lottare!$"

gFameCheckerPersonName_Lance:: @ 0x81B097F
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}LANCE$"

gFameCheckerPersonQuote_Lance:: @ 0x81B098B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Da: LANCE\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Sto pensando di tornare nel mio\n"
	.string "paese natale.\p"
	.string "Voglio riallenare i miei POKéMON\n"
	.string "di tipo DRAGO e rinforzarli.\p"
	.string "Mi piacerebbe invitarti da me\n"
	.string "un giorno.$"

gFameCheckerPersonName_Bill:: @ 0x81B0A45
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}BILL$"

gFameCheckerPersonQuote_Bill:: @ 0x81B0A50
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Da: BILL\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Ehi, ciao! CELIO ti ha riempito\n"
	.string "di complimenti.\p"
	.string "Saperlo mi rende felice.\p"
	.string "Quando catturi POKéMON rari,\n"
	.string "vieni a mostrarmeli, ok? Promesso!$"

gFameCheckerPersonName_MrFuji:: @ 0x81B0AFF
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}MR. FUJI$"

gFameCheckerPersonQuote_MrFuji:: @ 0x81B0B0E
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Da: MR. FUJI\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Invece di sperare nella felicità\n"
	.string "dei soli tuoi POKéMON…\p"
	.string "…posso farti desiderare la\n"
	.string "felicità di tutti i POKéMON?$"

gFameCheckerPersonName_Giovanni:: @ 0x81B0BA6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}GIOVANNI$"

gFameCheckerPersonQuote_Giovanni:: @ 0x81B0BB5
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Da: GIOVANNI\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Non ho niente da\n"
	.string "dirti.\p"
	.string "Mi concentrerò solo sul\n"
	.string "migliorare me stesso, e nessun altro.$"

gFameCheckerFlavorTextOriginLocation_ProfOak0:: @ 0x81B0C45
	.string "BIANCAVILLA$"

gFameCheckerFlavorTextOriginLocation_ProfOak1::
	.string "LAB. RICERCHE$"

gFameCheckerFlavorTextOriginLocation_ProfOak2::
	.string "LAB. RICERCHE$"

gFameCheckerFlavorTextOriginLocation_ProfOak3::
	.string "SMERALDOPOLI$"

gFameCheckerFlavorTextOriginLocation_ProfOak4::
	.string "Lega Pokémon$"

gFameCheckerFlavorTextOriginLocation_ProfOak5::
	.string "LAB. RICERCHE$"

gFameCheckerFlavorTextOriginLocation_Daisy0::
	.string "LAB. RICERCHE$"

gFameCheckerFlavorTextOriginLocation_Daisy1::
	.string "ARANCIOPOLI$"

gFameCheckerFlavorTextOriginLocation_Daisy2::
	.string "LABIRINTO ACQUA$"

gFameCheckerFlavorTextOriginLocation_Daisy3::
	.string "SMERALDOPOLI$"

gFameCheckerFlavorTextOriginLocation_Daisy4::
	.string "VILLA AZZURROPOLI$"

gFameCheckerFlavorTextOriginLocation_Daisy5::
	.string "QUARTA ISOLA$"

gFameCheckerFlavorTextOriginLocation_Brock0::
	.string "PLUMBEOPOLI$"

gFameCheckerFlavorTextOriginLocation_Brock1::
	.string "PALESTRA PLUMBEO$"

gFameCheckerFlavorTextOriginLocation_Brock2::
	.string "PLUMBEOPOLI$"

gFameCheckerFlavorTextOriginLocation_Brock3::
	.string "PERCORSO 4$"

gFameCheckerFlavorTextOriginLocation_Brock4::
	.string "MONTE LUNA$"

gFameCheckerFlavorTextOriginLocation_Brock5::
	.string "MUSEO PLUMBEO$"

gFameCheckerFlavorTextOriginLocation_Misty0::
	.string "CELESTOPOLI$"

gFameCheckerFlavorTextOriginLocation_Misty1::
	.string "PALESTRA DI CELESTOPOLI$"

gFameCheckerFlavorTextOriginLocation_Misty2::
	.string "PALESTRA DI CELESTOPOLI$"

gFameCheckerFlavorTextOriginLocation_Misty3::
	.string "ISOLE SEAFOAM$"

gFameCheckerFlavorTextOriginLocation_Misty4::
	.string "PROMONTORIO CELESTE$"

gFameCheckerFlavorTextOriginLocation_Misty5::
	.string "CELESTOPOLI$"

gFameCheckerFlavorTextOriginLocation_LtSurge0::
	.string "ARANCIOPOLI$"

gFameCheckerFlavorTextOriginLocation_LtSurge1::
	.string "PALESTRA DI ARANCIOPOLI$"

gFameCheckerFlavorTextOriginLocation_LtSurge2::
	.string "PALESTRA DI ARANCIOPOLI$"

gFameCheckerFlavorTextOriginLocation_LtSurge3::
	.string "PALESTRA DI ARANCIOPOLI$"

gFameCheckerFlavorTextOriginLocation_LtSurge4::
	.string "PALESTRA DI ARANCIOPOLI$"

gFameCheckerFlavorTextOriginLocation_LtSurge5::
	.string "ARANCIOPOLI$"

gFameCheckerFlavorTextOriginLocation_Erika0::
	.string "Azzurropoli$"

gFameCheckerFlavorTextOriginLocation_Erika1::
	.string "PALESTRA DI AZZURROPOLI$"

gFameCheckerFlavorTextOriginLocation_Erika2::
	.string "PALESTRA DI AZZURROPOLI$"

gFameCheckerFlavorTextOriginLocation_Erika3::
	.string "PALESTRA DI AZZURROPOLI$"

gFameCheckerFlavorTextOriginLocation_Erika4::
	.string "PALESTRA DI AZZURROPOLI$"

gFameCheckerFlavorTextOriginLocation_Erika5::
	.string "VILLA AZZURROPOLI$"

gFameCheckerFlavorTextOriginLocation_Koga0::
	.string "FUCSIAPOLI$"

gFameCheckerFlavorTextOriginLocation_Koga1::
	.string "PALESTRA DI FUCSIAPOLI$"

gFameCheckerFlavorTextOriginLocation_Koga2::
	.string "PALESTRA DI FUCSIAPOLI$"

gFameCheckerFlavorTextOriginLocation_Koga3::
	.string "FUCSIAPOLI$"

gFameCheckerFlavorTextOriginLocation_Koga4::
	.string "FUCSIAPOLI$"

gFameCheckerFlavorTextOriginLocation_Koga5::
	.string "ZONA SAFARI$"

gFameCheckerFlavorTextOriginLocation_Sabrina0::
	.string "ZAFFIROPOLI$"

gFameCheckerFlavorTextOriginLocation_Sabrina1::
	.string "TERZA ISOLA$"

gFameCheckerFlavorTextOriginLocation_Sabrina2::
	.string "PALESTRA ZAFFIROPOLI$"

gFameCheckerFlavorTextOriginLocation_Sabrina3::
	.string "PALESTRA ZAFFIROPOLI$"

gFameCheckerFlavorTextOriginLocation_Sabrina4::
	.string "ZAFFIROPOLI$"

gFameCheckerFlavorTextOriginLocation_Sabrina5::
	.string "PALESTRA ZAFFIROPOLI$"

gFameCheckerFlavorTextOriginLocation_Blaine0::
	.string "ISOLA CANNELLA$"

gFameCheckerFlavorTextOriginLocation_Blaine1::
	.string "PALESTRA DI ISOLA CANNELLA$"

gFameCheckerFlavorTextOriginLocation_Blaine2::
	.string "PALESTRA DI ISOLA CANNELLA$"

gFameCheckerFlavorTextOriginLocation_Blaine3::
	.string "ISOLA CANNELLA$"

gFameCheckerFlavorTextOriginLocation_Blaine4::
	.string "PALESTRA DI ISOLA CANNELLA$"

gFameCheckerFlavorTextOriginLocation_Blaine5::
	.string "RESORT BELLISSIMO$"

gFameCheckerFlavorTextOriginLocation_Lorelei0::
	.string "Lega Pokémon$"

gFameCheckerFlavorTextOriginLocation_Lorelei1::
	.string "Lega Pokémon$"

gFameCheckerFlavorTextOriginLocation_Lorelei2::
	.string "QUARTA ISOLA$"

gFameCheckerFlavorTextOriginLocation_Lorelei3::
	.string "QUINTA ISOLA$"

gFameCheckerFlavorTextOriginLocation_Lorelei4::
	.string "QUARTA ISOLA$"

gFameCheckerFlavorTextOriginLocation_Lorelei5::
	.string "QUARTA ISOLA$"

gFameCheckerFlavorTextOriginLocation_Bruno0::
	.string "Lega Pokémon$"

gFameCheckerFlavorTextOriginLocation_Bruno1::
	.string "Lega Pokémon$"

gFameCheckerFlavorTextOriginLocation_Bruno2::
	.string "ZAFFIROPOLI$"

gFameCheckerFlavorTextOriginLocation_Bruno3::
	.string "TERME SFAVILLANTE$"

gFameCheckerFlavorTextOriginLocation_Bruno4::
	.string "DUE ISOLA$"

gFameCheckerFlavorTextOriginLocation_Bruno5::
	.string "CANION SEVAULT$"

gFameCheckerFlavorTextOriginLocation_Agatha0::
	.string "Lega Pokémon$"

gFameCheckerFlavorTextOriginLocation_Agatha1::
	.string "ALTOPIANO INDIGO$"

gFameCheckerFlavorTextOriginLocation_Agatha2::
	.string "ALTOPIANO INDIGO$"

gFameCheckerFlavorTextOriginLocation_Agatha3::
	.string "SETTE ISOLA$"

gFameCheckerFlavorTextOriginLocation_Agatha4::
	.string "Lega Pokémon$"

gFameCheckerFlavorTextOriginLocation_Agatha5::
	.string "SEI ISOLA$"

gFameCheckerFlavorTextOriginLocation_Lance0::
	.string "Lega Pokémon$"

gFameCheckerFlavorTextOriginLocation_Lance1::
	.string "Lega Pokémon$"

gFameCheckerFlavorTextOriginLocation_Lance2::
	.string "ZAFFIROPOLI$"

gFameCheckerFlavorTextOriginLocation_Lance3::
	.string "CENTRO COMM. AZZURROPOLI$"

gFameCheckerFlavorTextOriginLocation_Lance4::
	.string "ALTOPIANO INDIGO$"

gFameCheckerFlavorTextOriginLocation_Lance5::
	.string "ALTOPIANO INDIGO$"

gFameCheckerFlavorTextOriginLocation_Bill0::
	.string "CELESTOPOLI$"

gFameCheckerFlavorTextOriginLocation_Bill1::
	.string "CELESTOPOLI$"

gFameCheckerFlavorTextOriginLocation_Bill2::
	.string "FUCSIAPOLI$"

gFameCheckerFlavorTextOriginLocation_Bill3::
	.string "UN'ISOLA$"

gFameCheckerFlavorTextOriginLocation_Bill4::
	.string "UN'ISOLA$"

gFameCheckerFlavorTextOriginLocation_Bill5::
	.string "UN'ISOLA$"

gFameCheckerFlavorTextOriginLocation_MrFuji0::
	.string "LAVANDONIA$"

gFameCheckerFlavorTextOriginLocation_MrFuji1::
	.string "TORRE POKéMON$"

gFameCheckerFlavorTextOriginLocation_MrFuji2::
	.string "LAVANDONIA$"

gFameCheckerFlavorTextOriginLocation_MrFuji3::
	.string "LAVANDONIA$"

gFameCheckerFlavorTextOriginLocation_MrFuji4::
	.string "PALESTRA DI ISOLA CANNELLA$"

gFameCheckerFlavorTextOriginLocation_MrFuji5::
	.string "ISOLA CANNELLA$"

gFameCheckerFlavorTextOriginLocation_Giovanni0::
	.string "NASCONDIGLIO ROCKET$"

gFameCheckerFlavorTextOriginLocation_Giovanni1::
	.string "SILPH SPA$"

gFameCheckerFlavorTextOriginLocation_Giovanni2::
	.string "SILPH SPA$"

gFameCheckerFlavorTextOriginLocation_Giovanni3::
	.string "PALESTRA DI SMERALDOPOLI$"

gFameCheckerFlavorTextOriginLocation_Giovanni4::
	.string "PALESTRA DI SMERALDOPOLI$"

gFameCheckerFlavorTextOriginLocation_Giovanni5::
	.string "MAGAZZINO ROCKET$"

gFameCheckerFlavorTextOriginObjectName_ProfOak0::
	.string "CARTELLO$"

gFameCheckerFlavorTextOriginObjectName_ProfOak1::
	.string "PROF. OAK$"

gFameCheckerFlavorTextOriginObjectName_ProfOak2::
	.string "AIUTO$"

gFameCheckerFlavorTextOriginObjectName_ProfOak3::
	.string "AGENDA POKéMON$"

gFameCheckerFlavorTextOriginObjectName_ProfOak4::
	.string "AGATHA$"

gFameCheckerFlavorTextOriginObjectName_ProfOak5::
	.string "AIUTO$"

gFameCheckerFlavorTextOriginObjectName_Daisy0::
	.string "AIUTO$"

gFameCheckerFlavorTextOriginObjectName_Daisy1::
	.string "DONNA$"

gFameCheckerFlavorTextOriginObjectName_Daisy2::
	.string "UOMO$"

gFameCheckerFlavorTextOriginObjectName_Daisy3::
	.string "AGENDA POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Daisy4::
	.string "SIGNORA$"

gFameCheckerFlavorTextOriginObjectName_Daisy5::
	.string "AGENDA POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Brock0::
	.string "CARTELLO$"

gFameCheckerFlavorTextOriginObjectName_Brock1::
	.string "BROCK$"

gFameCheckerFlavorTextOriginObjectName_Brock2::
	.string "GIOVANE$"

gFameCheckerFlavorTextOriginObjectName_Brock3::
	.string "RAGAZZO$"

gFameCheckerFlavorTextOriginObjectName_Brock4::
	.string "UOMO$"

gFameCheckerFlavorTextOriginObjectName_Brock5::
	.string "AGENDA POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Misty0::
	.string "CARTELLO$"

gFameCheckerFlavorTextOriginObjectName_Misty1::
	.string "MISTY$"

gFameCheckerFlavorTextOriginObjectName_Misty2::
	.string "LUIS$"

gFameCheckerFlavorTextOriginObjectName_Misty3::
	.string "GIOVANE$"

gFameCheckerFlavorTextOriginObjectName_Misty4::
	.string "DAMA$"

gFameCheckerFlavorTextOriginObjectName_Misty5::
	.string "AGENDA POKéMON$"

gFameCheckerFlavorTextOriginObjectName_LtSurge0::
	.string "CARTELLO$"

gFameCheckerFlavorTextOriginObjectName_LtSurge1::
	.string "LT. SURGE$"

gFameCheckerFlavorTextOriginObjectName_LtSurge2::
	.string "TUCKER$"

gFameCheckerFlavorTextOriginObjectName_LtSurge3::
	.string "TUCKER$"

gFameCheckerFlavorTextOriginObjectName_LtSurge4::
	.string "DWAYNE$"

gFameCheckerFlavorTextOriginObjectName_LtSurge5::
	.string "AGENDA POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Erika0::
	.string "CARTELLO$"

gFameCheckerFlavorTextOriginObjectName_Erika1::
	.string "ERIKA$"

gFameCheckerFlavorTextOriginObjectName_Erika2::
	.string "LOLA$"

gFameCheckerFlavorTextOriginObjectName_Erika3::
	.string "TAMIA$"

gFameCheckerFlavorTextOriginObjectName_Erika4::
	.string "ERIKA$"

gFameCheckerFlavorTextOriginObjectName_Erika5::
	.string "AGENDA POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Koga0::
	.string "CARTELLO$"

gFameCheckerFlavorTextOriginObjectName_Koga1::
	.string "KOGA$"

gFameCheckerFlavorTextOriginObjectName_Koga2::
	.string "KIRK$"

gFameCheckerFlavorTextOriginObjectName_Koga3::
	.string "CHARINE$"

gFameCheckerFlavorTextOriginObjectName_Koga4::
	.string "AGENDA POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Koga5::
	.string "UOMO$"

gFameCheckerFlavorTextOriginObjectName_Sabrina0::
	.string "CARTELLO$"

gFameCheckerFlavorTextOriginObjectName_Sabrina1::
	.string "GIOVANE$"

gFameCheckerFlavorTextOriginObjectName_Sabrina2::
	.string "SABRINA$"

gFameCheckerFlavorTextOriginObjectName_Sabrina3::
	.string "SABRINA$"

gFameCheckerFlavorTextOriginObjectName_Sabrina4::
	.string "AGENDA POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Sabrina5::
	.string "TYRON$"

gFameCheckerFlavorTextOriginObjectName_Blaine0::
	.string "CARTELLO$"

gFameCheckerFlavorTextOriginObjectName_Blaine1::
	.string "BLAINE$"

gFameCheckerFlavorTextOriginObjectName_Blaine2::
	.string "DEREK$"

gFameCheckerFlavorTextOriginObjectName_Blaine3::
	.string "DONNA$"

gFameCheckerFlavorTextOriginObjectName_Blaine4::
	.string "FOTO$"

gFameCheckerFlavorTextOriginObjectName_Blaine5::
	.string "AGENDA POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Lorelei0::
	.string "LORELEI$"

gFameCheckerFlavorTextOriginObjectName_Lorelei1::
	.string "LORELEI$"

gFameCheckerFlavorTextOriginObjectName_Lorelei2::
	.string "VECCHIETTO$"

gFameCheckerFlavorTextOriginObjectName_Lorelei3::
	.string "AGENDA POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Lorelei4::
	.string "BAMBINA$"

gFameCheckerFlavorTextOriginObjectName_Lorelei5::
	.string "SIGNORA$"

gFameCheckerFlavorTextOriginObjectName_Bruno0::
	.string "BRUNO$"

gFameCheckerFlavorTextOriginObjectName_Bruno1::
	.string "BRUNO$"

gFameCheckerFlavorTextOriginObjectName_Bruno2::
	.string "AGENDA POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Bruno3::
	.string "LOTTATORE$"

gFameCheckerFlavorTextOriginObjectName_Bruno4::
	.string "DONNA$"

gFameCheckerFlavorTextOriginObjectName_Bruno5::
	.string "LOTTATORE$"

gFameCheckerFlavorTextOriginObjectName_Agatha0::
	.string "AGATHA$"

gFameCheckerFlavorTextOriginObjectName_Agatha1::
	.string "LOTTATORE$"

gFameCheckerFlavorTextOriginObjectName_Agatha2::
	.string "LOTTATORE$"

gFameCheckerFlavorTextOriginObjectName_Agatha3::
	.string "AGENDA POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Agatha4::
	.string "AGATHA$"

gFameCheckerFlavorTextOriginObjectName_Agatha5::
	.string "SIGNORA$"

gFameCheckerFlavorTextOriginObjectName_Lance0::
	.string "LANCE$"

gFameCheckerFlavorTextOriginObjectName_Lance1::
	.string "LANCE$"

gFameCheckerFlavorTextOriginObjectName_Lance2::
	.string "DONNA$"

gFameCheckerFlavorTextOriginObjectName_Lance3::
	.string "BAMBINA$"

gFameCheckerFlavorTextOriginObjectName_Lance4::
	.string "AGENDA POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Lance5::
	.string "GIOVANE$"

gFameCheckerFlavorTextOriginObjectName_Bill0::
	.string "{RIVAL}$"

gFameCheckerFlavorTextOriginObjectName_Bill1::
	.string "BIMBO$"

gFameCheckerFlavorTextOriginObjectName_Bill2::
	.string "VECCHIETTO$"

gFameCheckerFlavorTextOriginObjectName_Bill3::
	.string "CELIO$"

gFameCheckerFlavorTextOriginObjectName_Bill4::
	.string "CELIO$"

gFameCheckerFlavorTextOriginObjectName_Bill5::
	.string "CELIO$"

gFameCheckerFlavorTextOriginObjectName_MrFuji0::
	.string "BAMBINA$"

gFameCheckerFlavorTextOriginObjectName_MrFuji1::
	.string "TEAM ROCKET$"

gFameCheckerFlavorTextOriginObjectName_MrFuji2::
	.string "RIVISTA$"

gFameCheckerFlavorTextOriginObjectName_MrFuji3::
	.string "UOMO$"

gFameCheckerFlavorTextOriginObjectName_MrFuji4::
	.string "FOTO$"

gFameCheckerFlavorTextOriginObjectName_MrFuji5::
	.string "AGENDA POKéMON$"

gFameCheckerFlavorTextOriginObjectName_Giovanni0::
	.string "GIOVANNI$"

gFameCheckerFlavorTextOriginObjectName_Giovanni1::
	.string "SCIENZIATO$"

gFameCheckerFlavorTextOriginObjectName_Giovanni2::
	.string "SCIENZIATO$"

gFameCheckerFlavorTextOriginObjectName_Giovanni3::
	.string "GIOVANNI$"

gFameCheckerFlavorTextOriginObjectName_Giovanni4::
	.string "UOMO$"

gFameCheckerFlavorTextOriginObjectName_Giovanni5::
	.string "GIDEON$"

PokemonJournal_Text_SpecialFeatureBrock::
	.string "AGENDA POKéMON\p"
	.string "Speciale: PALESTRA di PLUMBEOPOLI\n"
	.string "CAPOPALESTRA BROCK!\p"
	.string "BROCK ride di rado, ma se inizia\n"
	.string "si dice che non riesca più a fermarsi.$"

PokemonJournal_Text_SpecialFeatureMisty::
	.string "AGENDA POKéMON\p"
	.string "Speciale: PALESTRA di CELESTOPOLI\n"
	.string "CAPOPALESTRA MISTY!\p"
	.string "Si dice che MISTY adori LORELEI\n"
	.string "dei SUPERQUATTRO.$"

PokemonJournal_Text_SpecialFeatureLtSurge::
	.string "AGENDA POKéMON\p"
	.string "Speciale: PALESTRA di ARANCIOPOLI\n"
	.string "CAPOPALESTRA LT. SURGE!\p"
	.string "Si dice che LT. SURGE sia stato\n"
	.string "un pilota in America.\p"
	.string "Usava l'elettricità dei POKéMON\n"
	.string "per alimentare il suo aereo.$"

PokemonJournal_Text_SpecialFeatureErika::
	.string "AGENDA POKéMON\p"
	.string "Speciale: PALESTRA di AZZURROPOLI\n"
	.string "CAPOPALESTRA ERIKA!\p"
	.string "Dicono che sbirciando nella\n"
	.string "PALESTRA di AZZURROPOLI si veda\l"
	.string "spesso ERIKA che sonnecchia.$"

PokemonJournal_Text_SpecialFeatureKoga::
	.string "AGENDA POKéMON\p"
	.string "Speciale: PALESTRA di FUCSIAPOLI\n"
	.string "CAPOPALESTRA KOGA!\p"
	.string "Si dice che KOGA abbia una profonda\n"
	.string "conoscenza della medicina.\p"
	.string "Prepara persino medicine per curare\n"
	.string "i suoi POKéMON.$"

PokemonJournal_Text_SpecialFeatureSabrina::
	.string "AGENDA POKéMON\p"
	.string "Speciale: PALESTRA di ZAFFIROPOLI\n"
	.string "CAPOPALESTRA SABRINA!\p"
	.string "Dicono che SABRINA possa\n"
	.string "comunicare con i suoi POKéMON\l"
	.string "in lotta senza parlare.$"

PokemonJournal_Text_SpecialFeatureBlaine::
	.string "AGENDA POKéMON\p"
	.string "Speciale: PALESTRA di ISOLA CANNELLA\n"
	.string "CAPOPALESTRA BLAINE!\p"
	.string "Si dice che BLAINE tolga gli occhiali\n"
	.string "scuri solo quando pensa a nuove\l"
	.string "domande per il quiz.$"

PokemonJournal_Text_SpecialFeatureLorelei::
	.string "AGENDA POKéMON\p"
	.string "Servizio speciale:\n"
	.string "LORELEI dei SUPERQUATTRO!\p"
	.string "Nota per lo stile logico, calcolato\n"
	.string "e freddo, LORELEI ha un\l"
	.string "sorprendente segreto!$"

PokemonJournal_Text_SpecialFeatureBruno::
	.string "AGENDA POKéMON\p"
	.string "Servizio speciale:\n"
	.string "BRUNO dei SUPERQUATTRO!\p"
	.string "BRUNO si è unito ai SUPERQUATTRO\n"
	.string "per l'ardente desiderio di sfidare\l"
	.string "i migliori ALLENATORI.$"

PokemonJournal_Text_SpecialFeatureAgatha::
	.string "AGENDA POKéMON\p"
	.string "Servizio speciale:\n"
	.string "AGATHA dei SUPERQUATTRO!\p"
	.string "Da giovane, AGATHA e il PROF.\n"
	.string "OAK erano rivali che si sfidavano\l"
	.string "per essere i migliori ALLENATORI.$"

PokemonJournal_Text_SpecialFeatureLance::
	.string "AGENDA POKéMON\p"
	.string "Servizio speciale:\n"
	.string "LANCE dei SUPERQUATTRO!\p"
	.string "Si pensa che il nonno di LANCE sia\n"
	.string "l'anziano di un famoso clan di\l"
	.string "domatori di draghi.$"

PokemonJournal_Text_SpecialFeatureProfOak::
	.string "AGENDA POKéMON\p"
	.string "Speciale: PROF. OAK,\n"
	.string "il Ricercatore POKéMON!\p"
	.string "Si dice che il PROF. OAK viva con i\n"
	.string "nipoti DAISY e {RIVAL}.$"

PokemonJournal_Text_SpecialFeatureDaisyOak::
	.string "Questa è un'AGENDA POKéMON di\n"
	.string "anni fa…\p"
	.string "AGENDA POKéMON\n"
	.string "Speciale GARA!\p"
	.string "La Gran Campionessa della GARA\n"
	.string "POKéMON di primavera è DAISY OAK\l"
	.string "di BIANCAVILLA!$"

PokemonJournal_Text_SpecialFeatureMrFuji::
	.string "AGENDA POKéMON\p"
	.string "Servizio speciale:\n"
	.string "MR. FUJI della CASA POKéMON!\p"
	.string "Redazione: il timido MR. FUJI ha\n"
	.string "rifiutato la nostra intervista.\p"
	.string "È un uomo gentile, amato\n"
	.string "e rispettato a LAVANDONIA.$"
