Trade_Text_LookingForMonWannaTradeForMon::
	.string "Sto cercando il POKéMON\n"
	.string "{STR_VAR_1}!\p"
	.string "Vuoi scambiarlo col mio\n"
	.string "{STR_VAR_2}?$"

Trade_Text_AwwOhWell::
	.string "Aaah!\n"
	.string "Beh, pace…$"

Trade_Text_WhatThatsNoMon::
	.string "Cosa?\n"
	.string "Non è un {STR_VAR_1}!$"

Trade_Text_HeyThanks::
	.string "Ehi, grazie!$"

Trade_Text_IsntMyOldMonGreat::
	.string "Non è fantastico il mio vecchio {STR_VAR_2}?$"

Trade_Text_DoYouHaveMonWouldYouTradeForMon::
	.string "Ciao! Per caso hai\n"
	.string "un {STR_VAR_1}?\p"
	.string "Accetteresti di scambiarlo con\n"
	.string "il mio {STR_VAR_2}?$"

Trade_Text_WellIfYouDontWantTo::
	.string "Beh, se non vuoi…$"

Trade_Text_ThisIsntMon::
	.string "Mmmh?\n"
	.string "Questo non è un {STR_VAR_1}.\p"
	.string "Pensa a me se ne trovi uno.$"

Trade_Text_Thanks::
	.string "Grazie!$"

Trade_Text_HasTradedMonGrownStronger::
	.string "Il {STR_VAR_2} che ti ho scambiato,\n"
	.string "è diventato più forte?$"

Trade_Text_DoYouHaveMonWantToTradeForMon::
	.string "Ciao!\n"
	.string "Hai un {STR_VAR_1}?\p"
	.string "Vuoi scambiarlo con il mio\n"
	.string "{STR_VAR_2}?$"

Trade_Text_ThatsTooBad::
	.string "Che peccato.$"

Trade_Text_ThisIsNoMon::
	.string "…Questo non è un {STR_VAR_1}.\p"
	.string "Se ne trovi uno, scambialo con me.$"

Trade_Text_ThanksYoureAPal::
	.string "Grazie, sei un amico!$"

Trade_Text_HowIsMyOldMon::
	.string "Come sta il mio vecchio {STR_VAR_2}?\n"
	.string "Il mio {STR_VAR_1} va alla grande!$"
