LilycoveCity_DepartmentStore_1F_Text_LotteryCornerDrawTicket:
	.string "This is the POKéMON LOTTERY CORNER.\p"
	.string "All shoppers at our DEPARTMENT STORE\n"
	.string "get to draw a POKéMON LOTO TICKET.\p"
	.string "If the LOTO TICKET's number matches\n"
	.string "the ID number of any of your POKéMON,\l"
	.string "you will receive a fabulous gift.\p"
	.string "Would you like to draw a POKéMON\n"
	.string "LOTO TICKET?$"

LilycoveCity_DepartmentStore_1F_Text_ComeBackTomorrow:
	.string "Torna domani.$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain:
	.string "Torna a trovarci.$"

LilycoveCity_DepartmentStore_1F_Text_PleasePickTicket:
	.string "Scegli un BIGLIETTO LOTO.\n"
	.string "…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

LilycoveCity_DepartmentStore_1F_Text_TicketNumberIsXPleaseWait:
	.string "Il numero del BIGLIETTO LOTO è {STR_VAR_1}.\p"
	.string "Devo controllare questo numero\n"
	.string "per vedere se corrisponde a un\l"
	.string "ID dei tuoi POKéMON. Attendi.$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPartyMon:
	.string "Congratulations!\p"
	.string "The ID number of your team's\n"
	.string "{STR_VAR_1} matches your\l"
	.string "LOTO TICKET's number!$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPCMon:
	.string "Congratulations!\p"
	.string "The ID number of your PC-boxed\n"
	.string "{STR_VAR_1} matches your\l"
	.string "LOTO TICKET's number!$"

LilycoveCity_DepartmentStore_1F_Text_NoNumbersMatched:
	.string "Mi dispiace.\n"
	.string "Nessun numero corrisponde.$"

LilycoveCity_DepartmentStore_1F_Text_TwoDigitsMatched:
	.string "Due cifre uguali: vinci il\n"
	.string "terzo premio!\l"
	.string "Hai vinto {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_ThreeDigitsMatched:
	.string "Tre cifre uguali: vinci il\n"
	.string "secondo premio!\l"
	.string "Hai vinto {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_FourDigitsMatched:
	.string "Quattro cifre azzeccate, vinci il\n"
	.string "secondo premio!\l"
	.string "Hai vinto {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_AllFiveDigitsMatched:
	.string "Oh, santo cielo, cinque cifre\n"
	.string "azzeccate!\p"
	.string "Hai vinto il primo premio!\n"
	.string "Hai vinto {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_NoRoomForThis:
	.string "Oh?\n"
	.string "Sembra che tu non abbia spazio.\p"
	.string "Fai spazio nella BORSA e\n"
	.string "avvisami.$"

LilycoveCity_DepartmentStore_1F_Text_PrizeWeveBeenHolding:
	.string "{PLAYER}?\n"
	.string "Sì, ti aspettavo.\p"
	.string "Questo è il premio che ti abbiamo\n"
	.string "serbato.$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain2:
	.string "Torna a trovarci.$"
