MatchCall_WildBattleText1::
	.string "Ciao! {PLAYER}{KUN}, salve!\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Ho visto questo {STR_VAR_2} poco fa\n"
	.string "ma non l'ho preso.\p"
	.string "Ero così vicino!\n"
	.string "Beh, ci vediamo!$"

MatchCall_WildBattleText2::
	.string "Ciao, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Ho provato a prendere un bel {STR_VAR_2}\n"
	.string "poco fa.\p"
	.string "Ma è scappato.\n"
	.string "Che delusione!\p"
	.string "Va bene, ciao!$"

MatchCall_WildBattleText3::
	.string "Ehi, {PLAYER}!\n"
	.string "Sono io, {STR_VAR_1}.\p"
	.string "Ho appena provato a prendere\n"
	.string "questo {STR_VAR_2}, ma è fuggito.\p"
	.string "Ero così vicino!\p"
	.string "Mi ha rovinato la giornata…\n"
	.string "Va bene, ci vediamo!$"

MatchCall_WildBattleText4::
	.string "Ehi, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Conosci il POKéMON {STR_VAR_2}?\n"
	.string "Sono stato vicino a prenderne uno.\p"
	.string "Poco tempo fa.\n"
	.string "Credevo di averlo, ma è scappato.\p"
	.string "Se lo rivedo, lo prendo di\n"
	.string "sicuro, però.\p"
	.string "Okay, ci sentiamo.$"

MatchCall_WildBattleText5::
	.string "Ciao, {PLAYER}{KUN}!\n"
	.string "Sono {STR_VAR_1}.\l"
	.string "Catturi POKéMON ultimamente?\p"
	.string "Poco fa sono stato vicino a\n"
	.string "prenderne uno, ma è scappato.\p"
	.string "Bene, stammi bene!$"

MatchCall_WildBattleText6::
	.string "Ehi, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\l"
	.string "Catturato POKéMON ultimamente?\p"
	.string "Ne ho quasi preso uno l'altro giorno.\n"
	.string "Ma mi è sfuggito.\p"
	.string "Stammi bene.$"

MatchCall_WildBattleText7::
	.string "…Uh, {PLAYER}{KUN}?\n"
	.string "Sono io, {STR_VAR_1}.\p"
	.string "Oh, aspetta! Aspetta!\n"
	.string "Posso prendere questo {STR_VAR_2}…\p"
	.string "Aaarrrgh! È scappato!\n"
	.string "Ci ero così vicino!$"

MatchCall_WildBattleText8::
	.string "Oh, {PLAYER}{KUN}, come va?\n"
	.string "Sono {STR_VAR_1} che parla.\p"
	.string "Hai avuto successo catturando\n"
	.string "POKéMON ultimamente?\p"
	.string "Ci sono andato vicinissimo poco\n"
	.string "fa, ma il mio obiettivo è fuggito.\p"
	.string "Devo impegnarmi di più!\n"
	.string "Ci vediamo!$"

MatchCall_WildBattleText9::
	.string "Oh, {PLAYER}{KUN}, ciao!\n"
	.string "Sono {STR_VAR_1}!\p"
	.string "Allora? Stai mettendo insieme\n"
	.string "altri POKéMON?\p"
	.string "Per me sta andando malissimo!\n"
	.string "Mi scappano tutti!\p"
	.string "Ci vediamo!$"

MatchCall_WildBattleText10::
	.string "Oh, {PLAYER}{KUN}, ciao…\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Senti, sono stato a un passo dal\n"
	.string "prendere questo {STR_VAR_2}…\p"
	.string "Ma mi è sfuggito…\p"
	.string "Devo impegnarmi di più.\n"
	.string "Ci vediamo.$"

MatchCall_WildBattleText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\l"
	.string "Come va con te?\p"
	.string "Ho provato a prendere un {STR_VAR_2}\n"
	.string "selvatico, ma è scappato.\p"
	.string "Mi sento sconfitto…$"

MatchCall_WildBattleText12::
	.string "Ciao, {PLAYER}{KUN}.\n"
	.string "Sono io, {STR_VAR_1}.\l"
	.string "Stai ancora catturando POKéMON?\p"
	.string "Ci sto provando anch'io,\n"
	.string "ma non è così facile.\p"
	.string "La via dei POKéMON è profonda!$"

MatchCall_WildBattleText13::
	.string "Ah, ciao, {PLAYER}{KUN}!\n"
	.string "Sono {STR_VAR_1}!\l"
	.string "Stai catturando POKéMON?\p"
	.string "Ci sto provando anch'io,\n"
	.string "ma con poco successo.\p"
	.string "La via dei POKéMON è profonda!$"

MatchCall_WildBattleText14::
	.string "Oh, ciao {PLAYER}{KUN}, come va?\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Proprio ora ho provato a prendere\n"
	.string "un tenero {STR_VAR_2}.\p"
	.string "Però è scappato!\n"
	.string "Che delusione!\p"
	.string "Ciao ciao!$"

MatchCall_WildBattleText15::
	.string "Ehi, {PLAYER}!\n"
	.string "Sono {STR_VAR_1}!\p"
	.string "Stavo pensando di provare\n"
	.string "a catturare qualche POKéMON.\p"
	.string "Ma non ne trovo nessuno.\n"
	.string "Che bel rebus per me!\p"
	.string "Non so più che fare!\n"
	.string "Ci vediamo!$"

MatchCall_NegativeBattleText1::
	.string "Ciao! {PLAYER}{KUN}, salve!\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Ho sfidato un altro ALLENATORE,\n"
	.string "ma ho perso.\p"
	.string "Che delusione.\n"
	.string "Beh, ci vediamo!$"

MatchCall_NegativeBattleText2::
	.string "Ciao, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Ho sfidato un altro dopo\n"
	.string "la nostra lotta.\p"
	.string "Ci sono andato vicino, ma ho\n"
	.string "perso. Pazienza!$"

MatchCall_NegativeBattleText3::
	.string "Ehi, {PLAYER}!\n"
	.string "Sono io, {STR_VAR_1}.\p"
	.string "Mi hanno appena stracciato.\p"
	.string "Direi che devo allenare di più\n"
	.string "la squadra!$"

MatchCall_NegativeBattleText4::
	.string "Ehi, {PLAYER}.\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Ieri ho provato un'altra lotta,\n"
	.string "ma non ho vinto.\p"
	.string "La squadra va allenata di più.\n"
	.string "Ok, ci sentiamo.$"

MatchCall_NegativeBattleText5::
	.string "Ciao, {PLAYER}!\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Come te la passi?\p"
	.string "Ho continuato a lottare,\n"
	.string "ma non vinco spesso.\p"
	.string "Non riesco a combinare.\n"
	.string "Beh, stammi bene!$"

MatchCall_NegativeBattleText6::
	.string "Ehi, {PLAYER}.\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Come va da te?\p"
	.string "Ultimamente lotto sodo,\n"
	.string "ma con scarsi risultati.\p"
	.string "Non riesco a entrare in ritmo.\n"
	.string "Stammi bene.$"

MatchCall_NegativeBattleText7::
	.string "Sono {STR_VAR_1}.\n"
	.string "Come va di recente?\p"
	.string "Ieri ho perso una lotta,\n"
	.string "e non penso ad altro.\p"
	.string "Devo ideare un piano…\n"
	.string "Ci vediamo.$"

MatchCall_NegativeBattleText8::
	.string "Oh, {PLAYER}{KUN}, come va?\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Come stanno i tuoi POKéMON?\n"
	.string "L'altro giorno ho perso.\p"
	.string "Devo impegnarmi di più!\n"
	.string "Ci vediamo!$"

MatchCall_NegativeBattleText9::
	.string "Oh, {PLAYER}{KUN}, ciao!\n"
	.string "Sono {STR_VAR_1}!\p"
	.string "Ascolta, devi sentire\n"
	.string "questa!\p"
	.string "Poco fa ho fatto una lotta,\n"
	.string "ma ho perso all'ultimo secondo.\p"
	.string "Oh, che rabbia!$"

MatchCall_NegativeBattleText10::
	.string "Oh, {PLAYER}{KUN}, ciao…\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Poco fa ero in una lotta.\n"
	.string "Ho perso, però.\p"
	.string "Devo allenare di più i POKéMON.\n"
	.string "Ci vediamo.$"

MatchCall_NegativeBattleText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\l"
	.string "Come stanno i tuoi POKéMON?\p"
	.string "Ho appena perso un'altra lotta.\p"
	.string "Beh, ci vediamo!$"

MatchCall_NegativeBattleText12::
	.string "Ciao, {PLAYER}{KUN}.\n"
	.string "Sono io, {STR_VAR_1}.\l"
	.string "Stai ancora lottando sodo?\p"
	.string "Io ho perso di recente, quindi\n"
	.string "alleno la squadra dappertutto.\p"
	.string "Ci rivediamo.$"

MatchCall_NegativeBattleText13::
	.string "Ah, ciao, {PLAYER}{KUN}!\n"
	.string "Sono {STR_VAR_1}!\p"
	.string "Spero che tu stia bene.\p"
	.string "Ero in una lotta poco\n"
	.string "fa.\p"
	.string "{PLAYER}{KUN}, sii attivo come me.\n"
	.string "Ci vediamo!$"

MatchCall_NegativeBattleText14::
	.string "Oh, ciao, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Tu stai bene?\p"
	.string "Però dovresti tornare a casa\n"
	.string "ogni tanto.\p"
	.string "Ciao ciao!$"

MatchCall_PositiveBattleText1::
	.string "Ciao! {PLAYER}{KUN}, ehilà!\n"
	.string "Sono {STR_VAR_1}!\p"
	.string "Ho lottato contro un altro ALLENATORE.\n"
	.string "Ho vinto! Ho vinto!\p"
	.string "Il mio {STR_VAR_2} si è davvero dato\n"
	.string "da fare. È fantastico!$"

MatchCall_PositiveBattleText2::
	.string "Ciao, {PLAYER}{KUN}!\n"
	.string "Sono {STR_VAR_1}!\p"
	.string "Ieri ho fatto una battaglia e\n"
	.string "ho vinto! È fantastico!$"

MatchCall_PositiveBattleText3::
	.string "Ehilà, {PLAYER}!\n"
	.string "Sono io, {STR_VAR_1}!\l"
	.string "Come va con le lotte?\p"
	.string "Io l'altro giorno ho lottato,\n"
	.string "e il mio {STR_VAR_2} è stato grande!\p"
	.string "La prossima volta che ti sfido,\n"
	.string "{PLAYER}, non perderò io!$"

MatchCall_PositiveBattleText4::
	.string "Ehi, {PLAYER}.\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Ho fatto una lotta prima.\n"
	.string "Ho vinto, ma è stata dura.\p"
	.string "Il mio {STR_VAR_2} ha fatto\n"
	.string "una prova ispirata.$"

MatchCall_PositiveBattleText5::
	.string "Ciao, {PLAYER}{KUN}!\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Come vanno le cose con te?\n"
	.string "Lotti molto?\p"
	.string "Ho appena vinto poco fa!\n"
	.string "Il mio {STR_VAR_2} è stato brillante!\p"
	.string "Aspetta. La prossima volta\n"
	.string "ti batterò! Ehi, stammi bene!$"

MatchCall_PositiveBattleText6::
	.string "Ehi, {PLAYER}{KUN}.\n"
	.string "Qui {STR_VAR_1}.\p"
	.string "Come va per te?\p"
	.string "Sono in un periodo d'oro.\n"
	.string "Tanto che ho appena vinto una battaglia.\p"
	.string "Alla prossima lotta,\n"
	.string "di sicuro non perderò!$"

MatchCall_PositiveBattleText7::
	.string "{PLAYER}{KUN}?\n"
	.string "Qui {STR_VAR_1}.\p"
	.string "Il mio {STR_VAR_2} è una forza!\n"
	.string "Mi ha fatto vincere un'altra lotta ora!\p"
	.string "Non vedo l'ora di fare una rivincita\n"
	.string "con te.$"

MatchCall_PositiveBattleText8::
	.string "Oh, {PLAYER}{KUN}, come va?\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Spero che tu stia bene.\n"
	.string "Volevo dirti che ho appena vinto.\p"
	.string "Il mio {STR_VAR_2} ha lottato\n"
	.string "duro per la vittoria.\p"
	.string "Ci vediamo!$"

MatchCall_PositiveBattleText9::
	.string "Oh, {PLAYER}{KUN}, ciao!\n"
	.string "Sono {STR_VAR_1}!\p"
	.string "Come stanno i tuoi POKéMON?\n"
	.string "I miei hanno appena vinto!\p"
	.string "Il mio {STR_VAR_2} è stato\n"
	.string "spettacolare!\p"
	.string "Vorrei poterti mostrare!\n"
	.string "Ci vediamo!$"

MatchCall_PositiveBattleText10::
	.string "Oh, {PLAYER}{KUN}, ciao…\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Come ti tratta la vita?\p"
	.string "I miei POKéMON sembrano carichi\n"
	.string "di energia.\p"
	.string "Ho appena vinto una battaglia con loro.\n"
	.string "Ci vediamo in giro.$"

MatchCall_PositiveBattleText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Hai lottato ultimamente?\n"
	.string "Oggi ne ho vinta un'altra!\p"
	.string "Sono in forma! Gahahaha!\n"
	.string "Beh, ci vediamo!$"

MatchCall_PositiveBattleText12::
	.string "Ciao, {PLAYER}{KUN}.\n"
	.string "Sono io, {STR_VAR_1}.\p"
	.string "Spero che tu stia bene?\n"
	.string "Sono ancora pieno di vita!\p"
	.string "Tanto che ora ho vinto un altro incontro.\n"
	.string "Non lascio ancora il posto\l"
	.string "ai giovani!$"

MatchCall_PositiveBattleText13::
	.string "Ah, ciao, {PLAYER}{KUN}!\n"
	.string "Sono {STR_VAR_1}!\p"
	.string "Spero che tu stia bene.\n"
	.string "Ho ancora la Molla addosso!\p"
	.string "Tanto che ho appena vinto un'altra lotta.\n"
	.string "Oh, non perderò contro i giovani\l"
	.string "tanto presto!\p"
	.string "Ci rivediamo!$"

MatchCall_PositiveBattleText14::
	.string "Oh, ciao, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Ho lottato di recente, e il mio\n"
	.string "{STR_VAR_2} è stato eccezionale!\p"
	.string "Vorrei che l'avessi visto,\n"
	.string "{PLAYER}{KUN}. Ciao ciao!$"

MatchCall_SameRouteBattleRequestText1::
	.string "Ciao! {PLAYER}, hey!\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Eh? Sei vicino a\n"
	.string "{STR_VAR_2}?\p"
	.string "Oh, allora dobbiamo lottare!\n"
	.string "Ti aspetto! Ciao!$"

MatchCall_SameRouteBattleRequestText2::
	.string "Ciao, {PLAYER}!\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Oh? Sei dalle parti di\n"
	.string "{STR_VAR_2} adesso?\p"
	.string "Vuoi lottare ora?\n"
	.string "Ti aspetto! Ci vediamo!$"

MatchCall_SameRouteBattleRequestText3::
	.string "Ehi, {PLAYER}!\n"
	.string "Sono io, {STR_VAR_1}.\p"
	.string "Oh, sei vicino a\n"
	.string "{STR_VAR_2} adesso?\p"
	.string "Ti va di lottare con\n"
	.string "me ora?\p"
	.string "Non perderò di nuovo!\n"
	.string "Ti aspetto! A presto!$"

MatchCall_SameRouteBattleRequestText4::
	.string "Ehi, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Dove sei adesso?\n"
	.string "Eh? {STR_VAR_2}?\p"
	.string "Vuoi lottare ora?\n"
	.string "Ti aspetto. Ci vediamo!$"

MatchCall_SameRouteBattleRequestText5::
	.string "Ehi, {PLAYER}{KUN}!\n"
	.string "Sono {STR_VAR_1}.\l"
	.string "Come te la passi?\p"
	.string "Sei dove ora?\n"
	.string "{STR_VAR_2}?\p"
	.string "Beh, che ne dici di una\n"
	.string "rivincita subito?\p"
	.string "Ti terrò d'occhio.\n"
	.string "A presto!$"

MatchCall_SameRouteBattleRequestText6::
	.string "Ehi, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\l"
	.string "Come stanno i tuoi POKéMON?\p"
	.string "Oh, davvero? Sei vicino a\n"
	.string "{STR_VAR_2}?\p"
	.string "Beh, allora meglio fare\n"
	.string "una rivincita.\p"
	.string "Posso aspettare, certo.\n"
	.string "Ci vediamo!$"

MatchCall_SameRouteBattleRequestText7::
	.string "…Ehm, {PLAYER}{KUN}?\n"
	.string "Sono {STR_VAR_1}…\p"
	.string "Oh, sei dalle parti di\n"
	.string "{STR_VAR_2}?\p"
	.string "Allora lottiamo.\n"
	.string "Subito, intendo.\p"
	.string "Ti mostro i miei POKéMON.\n"
	.string "Ti aspetto.$"

MatchCall_SameRouteBattleRequestText8::
	.string "Oh, {PLAYER}{KUN}, come va?\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Spero che tu stia bene.\n"
	.string "Oh, sei vicino a {STR_VAR_2}.\p"
	.string "Ti va di lottare\n"
	.string "con me, allora?\p"
	.string "Ti aspetto.\n"
	.string "A presto!$"

MatchCall_SameRouteBattleRequestText9::
	.string "Oh, {PLAYER}{KUN}, ciao!\n"
	.string "Sono {STR_VAR_1}!\p"
	.string "Come te la cavi?\n"
	.string "Oh, sei vicino a {STR_VAR_2}?\p"
	.string "Oh, beh, non pensi che\n"
	.string "dobbiamo lottare?\p"
	.string "Non farmi aspettare troppo!$"

MatchCall_SameRouteBattleRequestText10::
	.string "Oh, {PLAYER}{KUN}, ciao…\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Come te la passi?\n"
	.string "Oh, sei vicino a {STR_VAR_2}.\p"
	.string "Allora lottiamo adesso.\p"
	.string "Sono qui che aspetto.\n"
	.string "Sbrigati!$"

MatchCall_SameRouteBattleRequestText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Ah, quindi ora sei a\n"
	.string "{STR_VAR_2}?\p"
	.string "Beh, allora dobbiamo proprio\n"
	.string "lottare, no?\p"
	.string "Ti aspetto qui!\n"
	.string "Ci vediamo, presto!$"

MatchCall_SameRouteBattleRequestText12::
	.string "Ciao, {PLAYER}{KUN}.\n"
	.string "Sono io, {STR_VAR_1}.\l"
	.string "Dove sarai ora?\p"
	.string "{STR_VAR_2}?\n"
	.string "Sei abbastanza vicino!\p"
	.string "Che ne dici di lottare\n"
	.string "ora?\p"
	.string "Posso aspettare.\n"
	.string "Ci vediamo!$"

MatchCall_SameRouteBattleRequestText13::
	.string "Ah, ciao, {PLAYER}{KUN}!\n"
	.string "Sono {STR_VAR_1}!\p"
	.string "Spero che tu stia bene.\n"
	.string "Oh, sei vicino a {STR_VAR_2}?\p"
	.string "Visto che non è lontano,\n"
	.string "vieni a lottare con me.\p"
	.string "Ti aspetto.\n"
	.string "Ciao per ora.$"

MatchCall_SameRouteBattleRequestText14::
	.string "Oh, ciao, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Sei dove? …{STR_VAR_2}?\n"
	.string "È molto vicino.\p"
	.string "Non pensi che dovremmo\n"
	.string "lottare?\p"
	.string "Ti cercherò!\n"
	.string "Ciao ciao!$"

MatchCall_DifferentRouteBattleRequestText1::
	.string "Ciao! {PLAYER}, salve!\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Ti va di lottare con me?\p"
	.string "Ti aspetto nei pressi di\n"
	.string "{STR_VAR_2}!$"

MatchCall_DifferentRouteBattleRequestText2::
	.string "Ciao, {PLAYER}!\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Ti va di fare una lotta\n"
	.string "di nuovo con me?\p"
	.string "Mi trovi nei pressi di\n"
	.string "{STR_VAR_2}. Ti aspetto!$"

MatchCall_DifferentRouteBattleRequestText3::
	.string "Ehi, {PLAYER}!\n"
	.string "Sono io, {STR_VAR_1}.\p"
	.string "I miei POKéMON sono cresciuti\n"
	.string "molto dall'ultra volta.\p"
	.string "Voglio vedere quanto sono forti\n"
	.string "contro i tuoi, {PLAYER}.\p"
	.string "Quindi, sfidiamoci!\p"
	.string "Ti aspetto nei dintorni di\n"
	.string "{STR_VAR_2}.$"

MatchCall_DifferentRouteBattleRequestText4::
	.string "Ehi, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\l"
	.string "Come te la passi?\p"
	.string "I miei POKéMON sono diventati\n"
	.string "belli forti di recente.\p"
	.string "Ehi, ti va di fare un'altra\n"
	.string "battaglia con me?\p"
	.string "Ci vediamo vicino a\n"
	.string "{STR_VAR_2}, ok?$"

MatchCall_DifferentRouteBattleRequestText5::
	.string "Ciao, {PLAYER}{KUN}!\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "I miei POKéMON crescono\n"
	.string "bene.\p"
	.string "Mi piacerebbe fare un'altra\n"
	.string "battaglia con te.\p"
	.string "Ti cercherò nei dintorni di\n"
	.string "{STR_VAR_2}. A presto!$"

MatchCall_DifferentRouteBattleRequestText6::
	.string "Ehi, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\l"
	.string "Spero che tu sia in forma.\p"
	.string "Pensavo che mi piacerebbe\n"
	.string "un'altra lotta con te. Che dici?\p"
	.string "Se ti va di lottare,\n"
	.string "vieni a {STR_VAR_2}.\p"
	.string "Ci vediamo!$"

MatchCall_DifferentRouteBattleRequestText7::
	.string "…Ehm, {PLAYER}{KUN}?\n"
	.string "Sono {STR_VAR_1}…\l"
	.string "Allora? I tuoi POKéMON crescono?\p"
	.string "I miei sono più forti.\n"
	.string "Vorrei mostrartelo.\p"
	.string "Sarò nei dintorni di {STR_VAR_2}.\n"
	.string "Vieni a sfidarmi.\p"
	.string "Ci vediamo.$"

MatchCall_DifferentRouteBattleRequestText8::
	.string "Oh, {PLAYER}{KUN}, come va?\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Spero che tu stia bene.\n"
	.string "I miei POKéMON sono vivaci.\p"
	.string "Se passi da queste parti,\n"
	.string "concedimi la rivincita.\p"
	.string "Sarò vicino a {STR_VAR_2}.\n"
	.string "A presto!$"

MatchCall_DifferentRouteBattleRequestText9::
	.string "Oh, {PLAYER}{KUN}, ciao!\n"
	.string "Sono {STR_VAR_1}!\l"
	.string "Come stanno i tuoi POKéMON?\p"
	.string "I miei migliorano sempre.\n"
	.string "Vorrei mostrartelo, {PLAYER}{KUN}.\p"
	.string "Ora sono vicino a {STR_VAR_2},\n"
	.string "lottiamo se sei nei paraggi.\p"
	.string "Spero di vederti presto!$"

MatchCall_DifferentRouteBattleRequestText10::
	.string "Oh, {PLAYER}{KUN}, ciao…\n"
	.string "Sono {STR_VAR_1}.\l"
	.string "Allora, come va con te?\p"
	.string "I miei POKéMON sono molto\n"
	.string "più forti di prima.\p"
	.string "Mi piacerebbe lottare ancora con te,\n"
	.string "{PLAYER}{KUN}.\p"
	.string "Sarò nei pressi di {STR_VAR_2}.\n"
	.string "Passa se sei vicino.$"

MatchCall_DifferentRouteBattleRequestText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\l"
	.string "Dove sarai ora?\p"
	.string "I miei POKéMON sono pieni di vita.\n"
	.string "Sembrano non vedere l'ora\l"
	.string "di conoscere i tuoi, {PLAYER}{KUN}.\p"
	.string "Sono nei pressi di {STR_VAR_2}.\n"
	.string "Spero che ci cercherai.$"

MatchCall_DifferentRouteBattleRequestText12::
	.string "Ciao, {PLAYER}{KUN}.\n"
	.string "Sono io, {STR_VAR_1}.\p"
	.string "Devo dirti che i miei POKéMON sono\n"
	.string "diventati proprio robusti.\p"
	.string "Vorrei vederli in lotta\n"
	.string "con te, {PLAYER}{KUN}.\p"
	.string "Saremo nei pressi di {STR_VAR_2}.\n"
	.string "Passa quando vuoi!$"

MatchCall_DifferentRouteBattleRequestText13::
	.string "Ah, ciao, {PLAYER}{KUN}!\n"
	.string "Sono {STR_VAR_1}!\l"
	.string "I tuoi POKéMON stanno bene?\p"
	.string "I miei sono così in forma\n"
	.string "che non sembrano capaci di perdere!\p"
	.string "Vorrei davvero fare un'altra\n"
	.string "lotta con te.\p"
	.string "Se sei nei pressi di {STR_VAR_2},\n"
	.string "vieni a trovarci.$"

MatchCall_DifferentRouteBattleRequestText14::
	.string "Oh, ciao, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\l"
	.string "Spero che tu stia bene.\p"
	.string "Oh, sì! I miei POKéMON sono\n"
	.string "molto più forti di prima.\p"
	.string "Non credi che dovremmo fare\n"
	.string "una lotta, {PLAYER}{KUN}?\p"
	.string "Ti aspetteremo nei pressi di\n"
	.string "{STR_VAR_2}.\p"
	.string "Vieni a trovarci, okay?$"

MatchCall_PersonalizedText1::
	.string "Sono io, l'amante della montagna\n"
	.string "{STR_VAR_1}!\p"
	.string "Beh, da quando ci siamo conosciuti, hai\n"
	.string "imparato ad apprezzare le montagne?\p"
	.string "Ti vedo di rado tra i monti…\p"
	.string "La prossima volta, ci vediamo\n"
	.string "nei dintorni di {STR_VAR_2}.$"

MatchCall_PersonalizedText2::
	.string "Sono {STR_VAR_1}.\n"
	.string "Salve.\p"
	.string "Stavo parlando di te a una nuova\n"
	.string "ALLENATRICE.\p"
	.string "Le ho parlato di un ALLENATORE forte\n"
	.string "che alleva POKéMON con cura.\p"
	.string "Spero che diventerai un ALLENATORE\n"
	.string "che tutti ammireranno.\p"
	.string "Spero di rivederti!$"

MatchCall_PersonalizedText3::
	.string "Ciao! Sono {STR_VAR_1}.\p"
	.string "Adoro il posto in cui sono ora.\n"
	.string "È piacevole, con aromi dolci!\p"
	.string "Credo che qualcuno abbia piantato\n"
	.string "delle BACche, e sono sbocciate.\p"
	.string "Ci vediamo presto!$"

MatchCall_PersonalizedText4::
	.string "Ciao! Trent'anni di esplorazioni,\n"
	.string "{STR_VAR_1} al tuo servizio!\p"
	.string "Sembra che tu viaggi con energia\n"
	.string "qua e là.\p"
	.string "Hai scoperto nuove rovine?\n"
	.string "Fammelo sapere se sì!\p"
	.string "Ora, se mi scusi,\n"
	.string "ho delle rovine da esplorare.$"

MatchCall_PersonalizedText5::
	.string "Sono {STR_VAR_1}!\p"
	.string "Sai cosa faccio oggi?\n"
	.string "Guardo le onde dalla spiaggia!\p"
	.string "Sigh… Le onde brillano tutte.\n"
	.string "Il mare è più bello da qui.\l"
	.string "Mi sta venendo fame, ciao ciao!$"

MatchCall_PersonalizedText6::
	.string "Sgranocchia…\n"
	.string "Oh, ciao, sono {STR_VAR_1}.\l"
	.string "Adoro mangiare in spiaggia.\p"
	.string "Io e i miei POKéMON stiamo\n"
	.string "benone. Siamo carichi!\l"
	.string "Vado a fare un bagno. Ciao!$"

MatchCall_PersonalizedText7::
	.string "Ciao, sono {STR_VAR_1}…\p"
	.string "Mi sono un po' stancato di tutta\n"
	.string "questa storia da COOLTRAINER…\p"
	.string "Tutti pensano che io sia un ALLENATORE\n"
	.string "perfetto, e questo mi spinge a\l"
	.string "essere all'altezza.\p"
	.string "Ma credo che faccia parte dell'essere\n"
	.string "un COOLTRAINER.\p"
	.string "Dovrò solo rimboccarmi le maniche…\n"
	.string "e stringere i denti.\p"
	.string "Sei l'unico con cui posso\n"
	.string "confidarmi così.\p"
	.string "Ma quando ti vedrò,\n"
	.string "non temere, non mi lamenterò!$"

MatchCall_PersonalizedText8::
	.string "Yahoo, sono {STR_VAR_1}!\n"
	.string "Come stai?\p"
	.string "Ho allenato i miei POKéMON con\n"
	.string "te come obiettivo.\p"
	.string "Non ho intenzione di perdere quando\n"
	.string "ci batteremo di nuovo.\p"
	.string "Non è fantastico avere ALLENATORI\n"
	.string "amici? Ci vediamo presto!$"

MatchCall_PersonalizedText9::
	.string "Sono {STR_VAR_1}…\n"
	.string "Proprio ora, dietro di te…\l"
	.string "Non c'era qualcosa…?\p"
	.string "Il potere dei POKéMON che\n"
	.string "dormono qui al MT. PYRE…\p"
	.string "Mi sta parlando di te…\p"
	.string "Dovresti allontanarti in fretta e\n"
	.string "non voltarti mai…\p"
	.string "Ehehe…\n"
	.string "Addio…$"

MatchCall_PersonalizedText10::
	.string "Sono {STR_VAR_1}.\n"
	.string "Come stai?\p"
	.string "Non è comodo poter\n"
	.string "chiacchierare a distanza?\p"
	.string "Prima, per parlare con\n"
	.string "qualcuno, mio padre doveva\l"
	.string "accompagnarmi…\p"
	.string "Ora devo andare.\n"
	.string "Sono contenta di questa chiacchierata.$"

MatchCall_PersonalizedText11::
	.string "Sono {STR_VAR_1}!\n"
	.string "Vuoi sentire questa?\p"
	.string "Mi piace molto la ZONA SAFARI,\n"
	.string "ma ogni volta mi perdo!\p"
	.string "Tutta quell'erba alta!\n"
	.string "Ed è troppo dispersiva!\p"
	.string "Mi sento meglio ora che\n"
	.string "me lo sono tolto!\p"
	.string "Vado di nuovo alla ZONA SAFARI!\n"
	.string "Ci si vede!$"

MatchCall_PersonalizedText12::
	.string "Ciao, sono {STR_VAR_1}.\n"
	.string "Sì, esatto, sono ricco, sì.\p"
	.string "Devo dirti che la mia ricchezza\n"
	.string "è cresciuta dall'ultra volta.\p"
	.string "Inoltre, anche i miei POKéMON\n"
	.string "sono più forti.\p"
	.string "Non riesco a togliermi l'idea che\n"
	.string "questo mondo esista per me!\p"
	.string "Oh, non serve dire nulla!\n"
	.string "Tutti sanno che è vero!\p"
	.string "Oh, devo scusarmi, ho una\n"
	.string "cena formale a cui andare.$"

MatchCall_PersonalizedText13::
	.string "Ufufufufu…\n"
	.string "Sono io, {STR_VAR_1}…\p"
	.string "Indovini cosa sto vedendo?\n"
	.string "Due {STR_VAR_2} in lotta.\p"
	.string "Forse proverò a catturare il vincitore…\n"
	.string "Ufufufufufu…\p"
	.string "Io… ora sono un po' occupata.\n"
	.string "Devo andare.$"

MatchCall_PersonalizedText14::
	.string "Oh, sono {STR_VAR_1}!\p"
	.string "Stavo pensando che mi sto\n"
	.string "annoiando della NAVE ABBANDONATA.\p"
	.string "Ma visto che sono già qui,\n"
	.string "e voglio batterti una volta,\l"
	.string "resto ancora un po'.\p"
	.string "Se ti senti spinto, perché non\n"
	.string "vieni a trovarmi?\p"
	.string "Penso che oggi sarà il giorno in cui\n"
	.string "sfiderò finalmente il vicino\l"
	.string "di casa.\p"
	.string "Ci vediamo!$"

MatchCall_PersonalizedText15::
	.string "Sono {STR_VAR_1}!\n"
	.string "L'uomo del mare!\p"
	.string "Sai cosa penso?\p"
	.string "Gli ALLENATORI in mare sono\n"
	.string "i più duri dei duri!\p"
	.string "Dovresti imparare da me e allenarti\n"
	.string "in mare…\p"
	.string "Ops, onda gigante in arrivo!\p"
	.string "È una grande occasione di allenamento!\n"
	.string "Scusa, devo andare!$"

MatchCall_PersonalizedText16::
	.string "Sono {STR_VAR_1}! Senti, ho\n"
	.string "insegnato karate ai miei POKéMON.\p"
	.string "Ma ora sono più forti di me!\n"
	.string "Non faccio che perdere con loro!\p"
	.string "Ma anche se posso perdere con\n"
	.string "i POKéMON, non perderò con un altro\l"
	.string "ALLENATORE, no!\p"
	.string "Dobbiamo lottare di nuovo!\n"
	.string "Ugwaah!$"

MatchCall_PersonalizedText17::
	.string "Sono io, {STR_VAR_1}.\n"
	.string "Come procedono i tuoi viaggi?\p"
	.string "…Wow, davvero?\n"
	.string "Sembra molto stimolante!\p"
	.string "Potrei scrivere una canzone su\n"
	.string "uno dei tuoi episodi.\p"
	.string "…Oh, ehi, la sento.\n"
	.string "Ho i riff in testa.\p"
	.string "Meglio scrivere bene questo brano,\n"
	.string "quindi devo volare! Ciao!$"

MatchCall_PersonalizedText18::
	.string "Sono {STR_VAR_1}…\n"
	.string "Ascolta la mia nuova canzone.\p"
	.string "Lalala, {STR_VAR_2}, {STR_VAR_2}!\n"
	.string "Perché sei così {STR_VAR_2}?\l"
	.string "Perché non posso essere te, {STR_VAR_2}?\l"
	.string "Lala, {STR_VAR_2} e {STR_VAR_1},\l"
	.string "{STR_VAR_1} e {STR_VAR_2}…\p"
	.string "Ripeti il ritornello, dissolvenza…$"

MatchCall_PersonalizedText19::
	.string "Sono {STR_VAR_1}, sai,\n"
	.string "l'esperto di campeggio!\p"
	.string "Quando abbiamo lottato, non ho\n"
	.string "potuto che perdere.\p"
	.string "Dopotutto, la mia specialità è\n"
	.string "il campeggio.\p"
	.string "Ma vincere o perdere, mi piace lottare\n"
	.string "quando sono in campeggio.\p"
	.string "Lotta di nuovo con noi, ok?\n"
	.string "Oh, e andiamo anche in campeggio!$"

MatchCall_PersonalizedText20::
	.string "Sono io, io, {STR_VAR_1}!\p"
	.string "Sinceramente, vorrei scalare altre\n"
	.string "montagne oltre a questa.\p"
	.string "Ma non so se ci siano\n"
	.string "ragazze come sul MT. CAMINO.\p"
	.string "Se conosci un'altra montagna\n"
	.string "con ragazze, dimmelo!\p"
	.string "Ehehehe, ci vediamo!$"

MatchCall_PersonalizedText21::
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Sono {STR_VAR_1}…\p"
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "È tutto per oggi…$"

MatchCall_PersonalizedText22::
	.string "Sono {STR_VAR_1}. Oggi avevo\n"
	.string "la sensazione che avrei parlato con te.\p"
	.string "Il mio desiderio di batterti cresce\n"
	.string "giorno e notte.\p"
	.string "Hai un rivale così, vero?\n"
	.string "Vorrei essere io…\p"
	.string "Sono felice che tu mi abbia ascoltato.\n"
	.string "Ci vediamo!$"

MatchCall_PersonalizedText23::
	.string "Sono {STR_VAR_1}.\p"
	.string "Quando c'è un ALLENATORE forte\n"
	.string "nei paraggi, a volte lo sento\l"
	.string "in qualche modo.\p"
	.string "Sei passato vicino, {PLAYER}{KUN}?\n"
	.string "Forse eri tu.\p"
	.string "Aspetto la tua visita.\n"
	.string "Ciao!$"

MatchCall_PersonalizedText24::
	.string "Ciao, sono {STR_VAR_1}.\n"
	.string "Sembri in forma, {PLAYER}{KUN}.\p"
	.string "Ho girato il mondo,\n"
	.string "ma devo dire che mi sono\l"
	.string "molto affezionato a questa regione.\p"
	.string "Penso di restare un po'.\n"
	.string "Forse possiamo rivederci?\p"
	.string "Non ho dimenticato le tue tecniche\n"
	.string "corposgargianti.\p"
	.string "Spero in una rivincita.$"

MatchCall_PersonalizedText25::
	.string "Tirate su col naso… Sono… {STR_VAR_1}…\n"
	.string "…Singhiozzo…\p"
	.string "ROXANNE mi ha sgridato in classe\n"
	.string "oggi.\p"
	.string "Ma non la odio per questo.\p"
	.string "ROXANNE mi dice esattamente\n"
	.string "cosa ho sbagliato, così imparo.\p"
	.string "Ci andrò di sicuro domani,\n"
	.string "alla SCUOLA ALLENATORI!\p"
	.string "Ci vediamo!$"

MatchCall_PersonalizedText26::
	.string "Sono {STR_VAR_1}!\p"
	.string "ROXANNE mi ha fatto lottare con lei\n"
	.string "ieri.\p"
	.string "Il risultato…\n"
	.string "Terribile, come immaginerai.\p"
	.string "Ma sono felice che ROXANNE\n"
	.string "mi abbia lasciato sfidarla!\p"
	.string "Non crederesti a quanto\n"
	.string "la ammiri!\p"
	.string "Mi impegnerò sul serio!\n"
	.string "Meglio che vada!$"

MatchCall_PersonalizedText27::
	.string "Ciao, sono ANNA! Sono di nuovo\n"
	.string "con la mia apprendista MEG.\p"
	.string "Adoro prendermi cura di MEG e dei\n"
	.string "POKéMON. Sono così teneri!\p"
	.string "Vorrei badare a loro\n"
	.string "come se fossero miei fratelli!\p"
	.string "Oh, ciao, MEG!\n"
	.string "Hai preso le brioche?\p"
	.string "Eh? No, no, non ti tratto\n"
	.string "come una serva!\p"
	.string "Hai perso lo scontro, quindi\n"
	.string "vai a comprare il pane come punizione!\p"
	.string "Non ti tratterei da serva,\n"
	.string "MEG! Sei troppo speciale per me!\p"
	.string "Ora devo andare.\n"
	.string "È l'ora della merenda!$"

MatchCall_PersonalizedText28::
	.string "Adoro i POKéMON!\n"
	.string "Sono {STR_VAR_1} del FAN CLUB!\p"
	.string "Devi sentire questa!\n"
	.string "Il mio dolce POKéMON…\p"
	.string "Sbuff! Wahaha!\n"
	.string "Non posso dire altro! È un segreto!\l"
	.string "È troppo tenero per le parole!\p"
	.string "Oh, il mio dolce {STR_VAR_2} chiede\n"
	.string "un {POKEBLOCK}!\p"
	.string "È il ritratto della tenerezza!\p"
	.string "Scusa, ora non posso parlare!\n"
	.string "Lo sentirai la prossima volta!$"

MatchCall_PersonalizedText29::
	.string "Ohoho!\p"
	.string "Sono {STR_VAR_1}! Non vedo l'ora di\n"
	.string "parlarti del mio adorato POKéMON!\p"
	.string "Ti prego, devi ascoltare.\n"
	.string "Riguarda il mio adorato {STR_VAR_2}.\p"
	.string "Quando qualcuno lo prende in braccio,\n"
	.string "salta dritto tra le mie braccia!\p"
	.string "Oh… Oh… Può esserci qualcosa\n"
	.string "di più beato?\p"
	.string "Oh, è una sensazione celestiale!\p"
	.string "Sono felice di averti potuto\n"
	.string "condividere un po' della mia felicità.\p"
	.string "Bene, devo andare.\n"
	.string "Ciao, allora!$"

MatchCall_PersonalizedText30::
	.string "Sono… {STR_VAR_1}.\n"
	.string "Mi chiamano ESPERTO.\p"
	.string "Ma c'è una cosa che so.\n"
	.string "Non potrei essere ESPERTO da solo\l"
	.string "con le mie forze.\p"
	.string "Solo con l'aiuto dei POKéMON un\n"
	.string "ALLENATORE può diventare ESPERTO.\p"
	.string "Uhm! Credo di aver detto\n"
	.string "qualcosa di profondo!\p"
	.string "Vi lascio di buon umore!$"

MatchCall_PersonalizedText31::
	.string "Sono {STR_VAR_1}.\n"
	.string "Sono felice di chiacchierare!\p"
	.string "Mi sento vivo e rinvigorito\n"
	.string "immerso in questa vasca termale.\p"
	.string "Ho lottato con giovani ALLENATORI\n"
	.string "da quando ci siamo visti, ma sei\l"
	.string "ancora il migliore.\p"
	.string "Immagino che diventerai un ESPERTO\n"
	.string "da vecchio! Ohohoho…$"

MatchCall_PersonalizedText32::
	.string "Evvai! Sono {STR_VAR_1}!\n"
	.string "Come va?\p"
	.string "Forse me lo immagino, ma quando\n"
	.string "vinco i combattimenti, i miei pantaloncini\l"
	.string "sembrano, tipo, meglio. Materialmente.\p"
	.string "Cosa intendo con questo?\n"
	.string "È un po' difficile da spiegare, ma…\l"
	.string "Come lo direi ora…\l"
	.string "I miei pantaloncini sono più setosi!\p"
	.string "E quando ho lottato con te, {PLAYER}{KUN},\n"
	.string "i miei pantaloncini erano ruvidi e ruvidi.\p"
	.string "… … … … … …\n"
	.string "Non ci hai creduto davvero?\l"
	.string "Ehehehe, tutto qui! Ciao!$"

MatchCall_PersonalizedText33::
	.string "Ehi!\n"
	.string "Sono {STR_VAR_1}!\p"
	.string "Come sempre, pesco con selvaggia\n"
	.string "abbandono!\p"
	.string "Ci sono altri posti dove posso pescare\n"
	.string "oltre al mare e ai fiumi?\p"
	.string "Ho forti impulsi di\n"
	.string "pescare ovunque!\p"
	.string "Oh, cavolo!\n"
	.string "La lenza si è aggrovigliata!\p"
	.string "Devo andare!\n"
	.string "Trovami nuovi posti per pescare!$"

MatchCall_PersonalizedText34::
	.string "Ehi, ciao! Sono {STR_VAR_1}.\n"
	.string "La prendi con calma?\p"
	.string "Fin da bambino, sai,\n"
	.string "sono sempre stato tranquillo, eh?\p"
	.string "Non sono mai stato tipo da\n"
	.string "stressarmi o andare di fretta.\p"
	.string "Ma guarda un po',\n"
	.string "ora sono un TRIATLETA.\p"
	.string "Non sai mai dove ti porterà la vita,\n"
	.string "se capisci cosa intendo.\p"
	.string "Ora sei un ALLENATORE, ma chissà\n"
	.string "cosa riserva il futuro, eh?\p"
	.string "Immaginati come insegnante,\n"
	.string "o magari artista. Forte, no?\p"
	.string "Ma ehi, stai tranquillo. Con calma.\n"
	.string "Ci vediamo in giro.$"

MatchCall_PersonalizedText35::
	.string "Sono {STR_VAR_1}!\n"
	.string "Ora sto in bici.\p"
	.string "Adoro nuotare e correre,\n"
	.string "ma la bici è il mio primo amore!\p"
	.string "Fa sentire tutto il corpo come se\n"
	.string "fossi tutt'uno col vento.\p"
	.string "Mi esalto come se\n"
	.string "volassi!\p"
	.string "Ok! Oggi batterò un nuovo\n"
	.string "record sulla PISTA CICLABILE!\p"
	.string "Dovresti provarci anche tu!\n"
	.string "Ci vediamo!$"

MatchCall_PersonalizedText36::
	.string "Ehi, sono {STR_VAR_1}! Sono proprio\n"
	.string "nel bel mezzo di un triathlon!\p"
	.string "Ma, ehi, ho sempre tempo per\n"
	.string "due chiacchiere!\p"
	.string "Allenarsi con i POKéMON\n"
	.string "fa sentire benissimo!\p"
	.string "Senza parole, ci sincronizziamo\n"
	.string "come se condividessimo un cuore.\p"
	.string "È stimolante!\p"
	.string "Anf… Parlare mentre corro…\n"
	.string "Mi sto stancando…\l"
	.string "Anf… Devo…andare…$"

MatchCall_PersonalizedText37::
	.string "Ciao, sono {STR_VAR_1}.\n"
	.string "Se vuoi migliorare la resistenza,\l"
	.string "l'allenamento in altura è perfetto!\p"
	.string "Prova a correre in cima a una montagna.\n"
	.string "Resterai senza fiato in un attimo!\p"
	.string "Anche io sono a corto di ossigeno!\n"
	.string "Ci vediamo!$"

MatchCall_PersonalizedText38::
	.string "Oh, sono {STR_VAR_1}, ciao.\p"
	.string "Ho nuotato tanto ma non riesco\n"
	.string "ancora ad arrivare a EVRGRANDE.\p"
	.string "Magari nuoto solo in tondo.\p"
	.string "No, no, impossibile.\n"
	.string "Wahahaha.\l"
	.string "Stammi bene!$"

MatchCall_PersonalizedText39::
	.string "Ehi, sono {STR_VAR_1}…\n"
	.string "Ops!\p"
	.string "Splash!\p"
	.string "Blug-blug-blug-blug…\p"
	.string "Sploosh!\p"
	.string "Fiiiu! Fiiiu!\p"
	.string "Ehi! Scusa!\n"
	.string "Mi sono appena messo l'olio solare.\p"
	.string "Così il POKéNAV mi è scivolato\n"
	.string "di mano in acqua!\p"
	.string "Ma il POKéNAV della DEVON è fatto\n"
	.string "robusto. Ha resistito al tuffo!\p"
	.string "Comunque, sono occupato a prendere\n"
	.string "il sole, chiacchieriamo un'altra volta.$"

MatchCall_PersonalizedText40::
	.string "Ciao, sono {STR_VAR_1}.\p"
	.string "Delle tre gare del triathlon,\n"
	.string "il nuoto è quella che preferisco.\p"
	.string "Ma se resto troppo in mare,\n"
	.string "non diventerò tutto raggrinzito?\p"
	.string "Ooh, il triathlon è una prova\n"
	.string "durissima per la resistenza! Ciao!$"

MatchCall_PersonalizedText41::
	.string "Ciao, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Come stanno i tuoi POKéMON?\p"
	.string "I miei POKéMON DRAGO sembrano\n"
	.string "in forma smagliante. Ci sentiamo.$"

MatchCall_PersonalizedText42::
	.string "Sono {STR_VAR_1}.\p"
	.string "Il mio {STR_VAR_2} è diventato anche\n"
	.string "più forte dell'ultra volta.\p"
	.string "Non perderò di nuovo con te.\n"
	.string "Aspetta la prossima volta!\p"
	.string "Ci vediamo!$"

MatchCall_PersonalizedText43::
	.string "Sono {STR_VAR_1}.\p"
	.string "Ho continuato i miei studi\n"
	.string "nell'arte del nascondersi.\p"
	.string "Ma ho avuto troppo successo.\n"
	.string "Nessuno è riuscito a trovarmi.\l"
	.string "Il successo mi rende solo…\p"
	.string "Come fumo svanisco!\n"
	.string "Addio!$"

MatchCall_PersonalizedText44::
	.string "Sono {STR_VAR_1}.\n"
	.string "Mi sono allenato da quando ci siamo visti.\p"
	.string "Il mio {STR_VAR_2} sta diventando\n"
	.string "forte.\p"
	.string "Allenarsi in spiaggia funziona,\n"
	.string "proprio come pensavo. Ciao!$"

MatchCall_PersonalizedText45::
	.string "Come va?\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Chissà quando smetterà di cadere\n"
	.string "questa cenere vulcanica?\p"
	.string "Se si accumula troppo, coprirà\n"
	.string "il disegno sul mio parasole…\p"
	.string "Promettiamo di rivederci!$"

MatchCall_PersonalizedText46::
	.string "Ciao, sono {STR_VAR_1}.\p"
	.string "Lo sapevi che è più facile\n"
	.string "galleggiare nel mare che in piscina?\p"
	.string "Standosene immobili, il corpo\n"
	.string "galleggia da solo.\p"
	.string "Ma se galleggi troppo a lungo,\n"
	.string "attento a non farti portare\l"
	.string "troppo al largo.\p"
	.string "…Dove sono, poi?\n"
	.string "Meglio che vada!$"

MatchCall_PersonalizedText47::
	.string "Oh, {PLAYER}{KUN}, ciao!\n"
	.string "Sono {STR_VAR_1}.\l"
	.string "Ora sono su in montagna.\p"
	.string "Ma il terreno è troppo irregolare.\n"
	.string "Non riesco a piantare la tenda…\p"
	.string "Oh, ho avuto un'idea geniale!\p"
	.string "Magari posso far spiattellare\n"
	.string "il terreno ai miei POKéMON!\p"
	.string "Proverò subito!\n"
	.string "Ciao ciao!$"

MatchCall_PersonalizedText48::
	.string "Oh, ciao ciao, sono {STR_VAR_1}!\p"
	.string "Allevo POKéMON con LIV!\n"
	.string "Ci impegniamo molto!\p"
	.string "Se ci impegniamo di più, possiamo\n"
	.string "diventare i numeri uno? Ciao ciao!$"

MatchCall_PersonalizedText49::
	.string "Sono {STR_VAR_1}!\p"
	.string "Sono un MARINAIO, ma ora non sono\n"
	.string "su una nave.\p"
	.string "Mi chiedo: come si chiama\n"
	.string "un MARINAIO a terra?\p"
	.string "È quello che pensavo\n"
	.string "guardando le onde.\p"
	.string "Va bene, alla prossima!$"

MatchCall_PersonalizedText50::
	.string "Sono {STR_VAR_1}.\n"
	.string "Allora? Hai preso altri POKéMON?\p"
	.string "Se catturi un nuovo POKéMON,\n"
	.string "devi venirlo a mostrare.\p"
	.string "Non piangerò per averlo, giuro.\n"
	.string "Ti aspetto. Ci vediamo.$"

MatchCall_PersonalizedText51::
	.string "Sono {STR_VAR_1}.\p"
	.string "Stai allevando i tuoi POKéMON\n"
	.string "nel modo ottimale?\p"
	.string "L'aria è pulita dove sono io.\n"
	.string "È l'ambiente perfetto per\l"
	.string "allevare POKéMON.\p"
	.string "Se vuoi concentrarti sull'allevamento\n"
	.string "dei POKéMON, dovresti venire a\l"
	.string "{STR_VAR_2}. Stammi bene.$"

MatchCall_PersonalizedText52::
	.string "Ciao, sono {STR_VAR_1}.\p"
	.string "Ho dato un {POKEBLOCK} al mio {STR_VAR_2}.\n"
	.string "Sembrava gradirlo molto.\p"
	.string "Pare che i POKéMON abbiano\n"
	.string "preferenze per i {POKEBLOCK}.\p"
	.string "Lo trovo affascinante.\n"
	.string "Stammi bene.$"

MatchCall_PersonalizedText53::
	.string "Sono {STR_VAR_1}.\p"
	.string "Se collabori con i POKéMON,\n"
	.string "si sta bene allo stato selvatico.\p"
	.string "Tutti dovrebbero capirlo e\n"
	.string "collaborare di più coi POKéMON.\p"
	.string "Sarebbe l'ideale.\n"
	.string "Lo penso davvero.\p"
	.string "Credo che sei sulla strada giusta!\n"
	.string "Ci vediamo!$"

MatchCall_PersonalizedText54::
	.string "Ciao, sono {STR_VAR_1}. Sai,\n"
	.string "l'ALLENATORE sempre preparato!\p"
	.string "{PLAYER}{KUN}, hai abbastanza oggetti?\n"
	.string "I tuoi POKéMON sono pronti?\p"
	.string "Tenere tutto perfetto intorno\n"
	.string "a te è il segreto per\l"
	.string "portare avanti il viaggio.\p"
	.string "Meglio che controlli le mie\n"
	.string "scorte! Sii vigile!$"

MatchCall_PersonalizedText55::
	.string "Sono {STR_VAR_1}!\n"
	.string "Sono {STR_VAR_1}!\p"
	.string "{STR_VAR_2} è una via molto\n"
	.string "trafficata, quindi vengo sfidato\l"
	.string "da ogni tipo di ALLENATORE ogni giorno.\p"
	.string "Oggi ho vinto cinque lotte e perso\n"
	.string "solo tre!\p"
	.string "Tu come sei andato oggi?\n"
	.string "Raccontamelo la prossima volta, ok?$"

MatchCall_PersonalizedText56::
	.string "Sono io, {STR_VAR_1}.\p"
	.string "Sono famoso perché ho tanti\n"
	.string "POKéMON COLEOTTERO, vero?\p"
	.string "Oggi ho portato a scuola\n"
	.string "i miei coleotteri preferiti.\p"
	.string "Una ragazza che mi piace ha pianto!\n"
	.string "Ridi pure, se vuoi.\p"
	.string "Devo insegnarle cosa rende\n"
	.string "i COLEOTTERO così affascinanti.\p"
	.string "Singhiozzo…\n"
	.string "Ci vediamo!$"

MatchCall_PersonalizedText57::
	.string "Ah! Ah! Ah! Ah!\p"
	.string "Ciao! Sono {STR_VAR_1}! Ah! Ah!\p"
	.string "Provare a chiacchierare…\n"
	.string "Mentre si arrampica…\l"
	.string "È un esercizio duro… Ah! Ah!\p"
	.string "Uff! Oof…\n"
	.string "Ora è più ripido…\l"
	.string "Ci sentiamo…un'altra volta…\l"
	.string "Ah! Ah! Ah!$"

MatchCall_PersonalizedText58::
	.string "Oh, ciao!\p"
	.string "Sto ancora cercando tesori\n"
	.string "con KIRA!\p"
	.string "Magari non c'è nessun tesoro\n"
	.string "qui…\p"
	.string "Ma l'importante è che io\n"
	.string "cerchi insieme a KIRA.\p"
	.string "Oh, ehi, KIRA!\n"
	.string "Pe-perché sei arrabbiata?\p"
	.string "Non ti sto ignorando, tesoro!\n"
	.string "Sei la mia unica e sola!\p"
	.string "…{PLAYER}, devo andare, ciao!$"

MatchCall_PersonalizedText59::
	.string "Sono {STR_VAR_1}!\p"
	.string "Sono tornato alla PALESTRA di\n"
	.string "PORTOVECCHIO per allenarmi.\p"
	.string "RUDY, il CAPOPALESTRA, sembra\n"
	.string "più forte ora.\p"
	.string "Sarà perché è temprato\n"
	.string "dalle onde selvagge…\p"
	.string "Ma è sempre forte come prima.\n"
	.string "Le ragazze lo adorano!\l"
	.string "Sinceramente, mi fa invidia.\p"
	.string "Chissà… Il suo amico BRUNO\n"
	.string "è come RUDY?\p"
	.string "Sai, tutto sudato e puzzolente,\n"
	.string "e tipo che chiama la gente\l"
	.string "“grande onda”, quel genere di cose.\p"
	.string "Ma ehi, questa gelosia non è\n"
	.string "molto dignitosa, vero?\p"
	.string "Dimentica questa chiacchierata,\n"
	.string "che ne dici? Addio!$"

MatchCall_PersonalizedText60::
	.string "È un piacere chiacchierare con\n"
	.string "un giovane ALLENATORE come te.\p"
	.string "Immagino che continuerai a\n"
	.string "goderti i POKéMON a ogni età.\p"
	.string "Non sarebbe bello avere\n"
	.string "un legame come il nostro?\p"
	.string "Certo, {PLAYER}{KUN}, tu già\n"
	.string "godi della fiducia e compagnia\l"
	.string "dei tuoi POKéMON.\p"
	.string "Hai già i presupposti per rapporti\n"
	.string "lunghi e duraturi!\p"
	.string "Hahaha!\n"
	.string "Mai scoraggiarsi!$"

MatchCall_PersonalizedText61::
	.string "Ciao, sono {STR_VAR_1}!\n"
	.string "Abbiamo appena vinto una lotta!\p"
	.string "Non vinciamo spesso, ma era un\n"
	.string "NUOTATORE forte.\p"
	.string "Mia sorella si è arrabbiata!\p"
	.string "Voleva fingere di essere\n"
	.string "debole per fare colpo!\p"
	.string "Mi sgrida sempre, che sia\n"
	.string "vittoria o sconfitta!\p"
	.string "{PLAYER}{KUN}, puoi dirle qualcosa\n"
	.string "la prossima volta?\p"
	.string "Ok, ci vediamo!$"

MatchCall_PersonalizedText62::
	.string "Sono {STR_VAR_1}, sì.\n"
	.string "Ieri sono andato per mare.\p"
	.string "Speravo di trovare una nuova\n"
	.string "rovina da esplorare.\p"
	.string "Ma le maree sembravano\n"
	.string "riportarmi al punto di partenza.\p"
	.string "Sono ancora debole nelle lotte…\n"
	.string "Prendimi pure in giro…\l"
	.string "Ma non mi arrenderò.\p"
	.string "Verrà il giorno in cui scoprirò\n"
	.string "una nuova rovina!\p"
	.string "È tutto quello che ho da dire!\n"
	.string "Addio per ora!$"

MatchCall_PersonalizedText63::
	.string "Ehilà!\n"
	.string "Sono io, {STR_VAR_1}!\l"
	.string "Sono sul PERCORSO 108!\l"
	.string "In altre parole, dove sto sempre!\p"
	.string "Oggi, una bellissima NUOTATRICE \n"
	.string "mi è passata accanto!\p"
	.string "Allora l'ho spaventata con un urlo!\p"
	.string "E lei mi ha lanciato un'occhiataccia!\p"
	.string "È tutto dal PERCORSO 108!\n"
	.string "Offerto da {STR_VAR_1}!$"

MatchCall_PersonalizedText64::
	.string "Sono {STR_VAR_1}!\p"
	.string "Sono un po' occupato, ma ho pensato\n"
	.string "di farti sapere che oggi ho\l"
	.string "battuto altri cinque ALLENATORI.\p"
	.string "Se continuo così, probabilmente\n"
	.string "ti batterò la prossima volta.\p"
	.string "Credo che saremo buoni rivali,\n"
	.string "io e te. Per ora ciao!$"

MatchCall_BattleFrontierStreakText1::
	.string "Ciao! Sono {STR_VAR_1}.\n"
	.string "Ho sentito la notizia!\p"
	.string "Dicono che sei andato alla grande\n"
	.string "al {STR_VAR_2}.\p"
	.string "È fantastico, {STR_VAR_3} vittorie di fila?\n"
	.string "Ci vediamo!$"

MatchCall_BattleFrontierStreakText2::
	.string "Ciao, sono {STR_VAR_1}!\n"
	.string "Ho sentito parlare di te!\p"
	.string "Dicono che hai vinto {STR_VAR_3} lotte di\n"
	.string "fila alla {STR_VAR_2}.\p"
	.string "Che roba! Dovrei impegnarmi\n"
	.string "anch'io! Ci vediamo!$"

MatchCall_BattleFrontierStreakText3::
	.string "Ehi, {PLAYER}!\n"
	.string "Sono io, {STR_VAR_1}.\p"
	.string "Ho sentito che hai fatto il pieno\n"
	.string "alla {STR_VAR_2}!\p"
	.string "Una serie di {STR_VAR_3} vittorie…\n"
	.string "Bel record, no?\p"
	.string "Devo darmi una mossa anch'io!\n"
	.string "A presto!$"

MatchCall_BattleFrontierStreakText4::
	.string "Ehi, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}. Come va?\p"
	.string "Gira voce che hai messo insieme\n"
	.string "{STR_VAR_3} vittorie di fila\l"
	.string "alla {STR_VAR_2}.\p"
	.string "Devo darmi da fare anch'io.\n"
	.string "Ci vediamo!$"

MatchCall_BattleFrontierStreakText5::
	.string "Ciao, {PLAYER}{KUN}!\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Eri al {STR_VAR_2}\n"
	.string "e hai vinto {STR_VAR_3} lotte di fila?\l"
	.string "Mica male!\p"
	.string "Meglio che alleni di più i POKéMON.\n"
	.string "A presto!$"

MatchCall_BattleFrontierStreakText6::
	.string "Ehi, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}. Come stai?\p"
	.string "A proposito, ho sentito che hai fatto\n"
	.string "l'impresa di {STR_VAR_3} vittorie di fila\l"
	.string "al {STR_VAR_2}.\p"
	.string "Mi ispiri a concentrarmi\n"
	.string "sulla mia squadra.$"

MatchCall_BattleFrontierStreakText7::
	.string "…Ehm, {PLAYER}{KUN}?\n"
	.string "Sono {STR_VAR_1}…\p"
	.string "Ah, sì, eri alla\n"
	.string "{STR_VAR_2}, vero?\p"
	.string "E hai vinto {STR_VAR_3} lotte di fila.\p"
	.string "Oh, ecco un POKéMON raro!\n"
	.string "Devo andare!$"

MatchCall_BattleFrontierStreakText8::
	.string "Oh, {PLAYER}{KUN}, come stai?\n"
	.string "Sono {STR_VAR_1}.\l"
	.string "Spero che tu stia bene.\p"
	.string "Oh, ma sì. Ho sentito che\n"
	.string "hai vinto {STR_VAR_3} lotte di fila al\l"
	.string "{STR_VAR_2}.\p"
	.string "È davvero impressionante!\n"
	.string "Spero che continui così.$"

MatchCall_BattleFrontierStreakText9::
	.string "Oh, {PLAYER}{KUN}, ciao!\n"
	.string "Sono {STR_VAR_1}!\p"
	.string "Ho sentito! La tua serie di {STR_VAR_3}\n"
	.string "vittorie alla {STR_VAR_2}!\p"
	.string "Che forza!\n"
	.string "Devo impegnarmi anch'io!$"

MatchCall_BattleFrontierStreakText10::
	.string "Oh, {PLAYER}{KUN}, ciao…\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Hai vinto {STR_VAR_3} lotte di fila alla\n"
	.string "{STR_VAR_2}?\p"
	.string "Un bel risultato, davvero.\n"
	.string "Devo allenarmi di più.$"

MatchCall_BattleFrontierStreakText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Ho sentito che sei il terrore della\n"
	.string "{STR_VAR_2}?\p"
	.string "Hai vinto, tipo, {STR_VAR_3} lotte di\n"
	.string "fila?\p"
	.string "Sei forte, eh.\n"
	.string "Chissà quante ne vincerò io?$"

MatchCall_BattleFrontierStreakText12::
	.string "Ciao, {PLAYER}{KUN}.\n"
	.string "Sono io, {STR_VAR_1}.\l"
	.string "Tutto bene?\p"
	.string "Qualcuno mi ha parlato di te.\n"
	.string "Hai vinto {STR_VAR_3} lotte di fila\l"
	.string "in un posto chiamato {STR_VAR_2}?\p"
	.string "Che storia.\n"
	.string "Ci vediamo!$"

MatchCall_BattleFrontierStreakText13::
	.string "Ah, ciao, {PLAYER}{KUN}!\n"
	.string "Sono {STR_VAR_1}!\l"
	.string "Spero che tu stia bene.\p"
	.string "Dicono che hai vinto {STR_VAR_3} lotte\n"
	.string "di fila alla {STR_VAR_2}.\p"
	.string "Ammiro la tua energia!\n"
	.string "Ciao ciao.$"

MatchCall_BattleFrontierStreakText14::
	.string "Oh, ciao, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Ho sentito parlare di te!\n"
	.string "Non hai appena vinto {STR_VAR_3} lotte di\l"
	.string "fila al {STR_VAR_2}?\p"
	.string "Sei un esempio!\n"
	.string "Ciao ciao!$"

MatchCall_BattleFrontierRecordStreakText1::
	.string "Ciao! Sono {STR_VAR_1}.\n"
	.string "Ho sentito la notizia!\p"
	.string "Dicono che sei andato benissimo\n"
	.string "alla {STR_VAR_2}.\p"
	.string "Fantastico, {STR_VAR_3} vittorie di fila?\n"
	.string "Ci vediamo!$"

MatchCall_BattleFrontierRecordStreakText2::
	.string "Ciao, sono {STR_VAR_1}!\n"
	.string "Ho sentito parlare di te!\p"
	.string "Dicono che hai vinto {STR_VAR_3} lotte di\n"
	.string "fila alla {STR_VAR_2}.\p"
	.string "Che roba! Dovrei impegnarmi\n"
	.string "anch'io! Ci vediamo!$"

MatchCall_BattleFrontierRecordStreakText3::
	.string "Ehi, {PLAYER}!\n"
	.string "Sono io, {STR_VAR_1}.\p"
	.string "Ho sentito che hai fatto il pieno\n"
	.string "alla {STR_VAR_2}!\p"
	.string "Una serie di {STR_VAR_3} vittorie…\n"
	.string "Bel record, no?\p"
	.string "Devo darmi una mossa anch'io!\n"
	.string "A presto!$"

MatchCall_BattleFrontierRecordStreakText4::
	.string "Ehi, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}. Come va?\p"
	.string "Gira voce che hai messo insieme\n"
	.string "{STR_VAR_3} vittorie di fila\l"
	.string "alla {STR_VAR_2}.\p"
	.string "Devo darmi da fare anch'io.\n"
	.string "Ci vediamo!$"

MatchCall_BattleFrontierRecordStreakText5::
	.string "Ciao, {PLAYER}{KUN}!\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Eri alla {STR_VAR_2}\n"
	.string "e hai vinto {STR_VAR_3} lotte di fila?\l"
	.string "Mica male!\p"
	.string "Io? Direi che progredisco.\n"
	.string "A presto!$"

MatchCall_BattleFrontierRecordStreakText6::
	.string "Ehi, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}. Come stai?\p"
	.string "A proposito, hai fatto\n"
	.string "{STR_VAR_3} vittorie di fila\l"
	.string "alla {STR_VAR_2}.\p"
	.string "Devo impegnarmi di più anch'io!\n"
	.string "A presto!$"

MatchCall_BattleFrontierRecordStreakText7::
	.string "…Ehm, {PLAYER}{KUN}?\n"
	.string "Sono {STR_VAR_1}…\p"
	.string "Ah, sì, eri alla\n"
	.string "{STR_VAR_2}, vero?\p"
	.string "E hai vinto {STR_VAR_3} lotte di fila.\p"
	.string "Oh, ecco un POKéMON raro!\n"
	.string "Devo andare!$"

MatchCall_BattleFrontierRecordStreakText8::
	.string "Oh, {PLAYER}{KUN}, come va?\n"
	.string "Sono {STR_VAR_1}.\l"
	.string "Spero che tu stia bene.\p"
	.string "Oh, ma certo. Ho sentito che\n"
	.string "hai vinto {STR_VAR_3} lotte di fila\l"
	.string "alla {STR_VAR_2}.\p"
	.string "Molto impressionante!\n"
	.string "Devo allenare i POKéMON anch'io!$"

MatchCall_BattleFrontierRecordStreakText9::
	.string "Oh, {PLAYER}{KUN}, ciao!\n"
	.string "Sono {STR_VAR_1}!\p"
	.string "Ho sentito! La tua serie di {STR_VAR_3}\n"
	.string "vittorie alla {STR_VAR_2}!\p"
	.string "Che forza!\n"
	.string "Devo impegnarmi anch'io!$"

MatchCall_BattleFrontierRecordStreakText10::
	.string "Oh, {PLAYER}{KUN}, ciao…\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Hai vinto {STR_VAR_3} lotte di fila alla\n"
	.string "{STR_VAR_2}?\p"
	.string "Un bel risultato, davvero.\n"
	.string "Devo allenarmi di più.$"

MatchCall_BattleFrontierRecordStreakText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Ho sentito che sei il terrore della\n"
	.string "{STR_VAR_2}?\p"
	.string "Hai vinto, tipo, {STR_VAR_3} lotte di\n"
	.string "fila?\p"
	.string "Sei forte, eh.\n"
	.string "Chissà quante ne vincerò io?$"

MatchCall_BattleFrontierRecordStreakText12::
	.string "Ciao, {PLAYER}{KUN}.\n"
	.string "Sono io, {STR_VAR_1}.\l"
	.string "Tutto bene?\p"
	.string "Qualcuno mi ha parlato di te.\n"
	.string "Hai vinto {STR_VAR_3} lotte di fila\l"
	.string "in un posto chiamato {STR_VAR_2}?\p"
	.string "Che storia.\n"
	.string "Ci vediamo!$"

MatchCall_BattleFrontierRecordStreakText13::
	.string "Ah, ciao, {PLAYER}{KUN}!\n"
	.string "Sono {STR_VAR_1}!\l"
	.string "Spero che tu stia bene.\p"
	.string "Dicono che hai vinto {STR_VAR_3} lotte\n"
	.string "di fila alla {STR_VAR_2}.\p"
	.string "Ammiro la tua energia!\n"
	.string "Ciao ciao.$"

MatchCall_BattleFrontierRecordStreakText14::
	.string "Oh, ciao, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\l"
	.string "Ho sentito parlare di te!\p"
	.string "Non hai appena vinto {STR_VAR_3} lotte di\n"
	.string "fila alla {STR_VAR_2}?\p"
	.string "Sei un'ispirazione!\n"
	.string "Ciao ciao!$"

MatchCall_BattleDomeText1::
	.string "Ciao! {PLAYER}?\n"
	.string "Salve, sono {STR_VAR_1}!\l"
	.string "Ho sentito la notizia!\p"
	.string "Sei diventato campione alla\n"
	.string "{STR_VAR_2} {STR_VAR_3} volte?\p"
	.string "È fantastico! Devo impegnarmi!\n"
	.string "Ci vediamo!$"

MatchCall_BattleDomeText2::
	.string "Ciao, sono {STR_VAR_1}!\n"
	.string "Ho sentito parlare di te!\p"
	.string "Dicono che hai vinto {STR_VAR_3} titoli\n"
	.string "alla {STR_VAR_2}.\p"
	.string "Fantastico! Chissà se posso\n"
	.string "diventare un campione?$"

MatchCall_BattleDomeText3::
	.string "Ehi, {PLAYER}!\n"
	.string "Sono io, {STR_VAR_1}.\l"
	.string "Come va?\p"
	.string "Hai vinto {STR_VAR_3} gare alla\n"
	.string "{STR_VAR_2}!\p"
	.string "La prossima volta fanne una in più!\n"
	.string "A presto!$"

MatchCall_BattleDomeText4::
	.string "Ehi, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Sei diventato campione alla\n"
	.string "{STR_VAR_2} {STR_VAR_3} volte.\p"
	.string "Vedo che ti impegni.\n"
	.string "Cercherò di starti dietro!$"

MatchCall_BattleDomeText5::
	.string "Ciao, {PLAYER}{KUN}!\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Hai vinto {STR_VAR_3} volte di fila\n"
	.string "alla {STR_VAR_2}.\p"
	.string "Devo darmi da fare anch'io!\n"
	.string "A presto!$"

MatchCall_BattleDomeText6::
	.string "Ehi, {PLAYER}{KUN}?\n"
	.string "Sono {STR_VAR_1}. Come stai?\p"
	.string "A proposito, dicono che sei\n"
	.string "diventato campione {STR_VAR_3} volte alla\l"
	.string "{STR_VAR_2}.\p"
	.string "Meglio allenare i POKéMON prima\n"
	.string "che tu vada troppo avanti.$"

MatchCall_BattleDomeText7::
	.string "{PLAYER}{KUN}?\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Eri alla {STR_VAR_2}\n"
	.string "e sei diventato campione {STR_VAR_3} volte?\p"
	.string "Notevole. A proposito, hai\n"
	.string "preso POKéMON rari di recente?\p"
	.string "Ah, davvero.\n"
	.string "Ok, ciao.$"

MatchCall_BattleDomeText8::
	.string "Oh, {PLAYER}{KUN}, come va?\n"
	.string "Sono {STR_VAR_1}.\l"
	.string "Spero che tu stia bene.\l"
	.string "Oh, ma certo che stai bene.\p"
	.string "Ho sentito che hai vinto {STR_VAR_3} titoli\n"
	.string "alla {STR_VAR_2}.\p"
	.string "Devo allenare i miei POKéMON come te.\n"
	.string "Ci vediamo.$"

MatchCall_BattleDomeText9::
	.string "Oh, {PLAYER}{KUN}, ciao!\n"
	.string "Sono {STR_VAR_1}!\p"
	.string "Ho sentito! Hai preso il titolo\n"
	.string "{STR_VAR_3} volte alla {STR_VAR_2}!\p"
	.string "Che forza!\n"
	.string "Devo impegnarmi anch'io!$"

MatchCall_BattleDomeText10::
	.string "Oh, {PLAYER}{KUN}, ciao.\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Hai vinto {STR_VAR_3} volte di fila alla\n"
	.string "{STR_VAR_2}?\p"
	.string "Un bel risultato, davvero.\n"
	.string "Devo allenarmi di più.$"

MatchCall_BattleDomeText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Ho sentito che sei il terrore della\n"
	.string "{STR_VAR_2}?\p"
	.string "Hai vinto, tipo, {STR_VAR_3} volte di\n"
	.string "fila?\p"
	.string "Chissà se diventerò mai\n"
	.string "campione?\p"
	.string "…Quasi impossibile, eh?\n"
	.string "Beh, ci vediamo!$"

MatchCall_BattleDomeText12::
	.string "Ciao, {PLAYER}{KUN}.\n"
	.string "Sono io, {STR_VAR_1}.\l"
	.string "Tutto bene?\p"
	.string "Hai vinto {STR_VAR_3} gare in un posto\n"
	.string "chiamato {STR_VAR_2}?\p"
	.string "Che storia.\n"
	.string "Ci vediamo!$"

MatchCall_BattleDomeText13::
	.string "Ah, ciao, {PLAYER}{KUN}!\n"
	.string "Sono {STR_VAR_1}!\l"
	.string "Spero che tu stia bene.\p"
	.string "Dicono che hai vinto {STR_VAR_3} gare\n"
	.string "alla {STR_VAR_2}?\p"
	.string "Ammiro la tua energia!\n"
	.string "Ciao ciao.$"

MatchCall_BattleDomeText14::
	.string "Oh, ciao, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\l"
	.string "Ho sentito parlare di te!\p"
	.string "Non hai vinto {STR_VAR_3} titoli\n"
	.string "alla {STR_VAR_2}?\p"
	.string "Sei un'ispirazione!\n"
	.string "Ci vediamo!$"

MatchCall_BattlePikeText1::
	.string "Ciao! {PLAYER}?\n"
	.string "Ciao, sono {STR_VAR_1}!\l"
	.string "Ho sentito la notizia!\p"
	.string "Hai superato {STR_VAR_3} stanze\n"
	.string "al {STR_VAR_2}!\p"
	.string "Che fantastico!\n"
	.string "Ci vediamo!$"

MatchCall_BattlePikeText2::
	.string "Ciao, sono {STR_VAR_1}!\n"
	.string "Ho sentito parlare di te!\p"
	.string "Dicono che hai superato\n"
	.string "{STR_VAR_3} stanze al {STR_VAR_2}.\p"
	.string "Devo impegnarmi molto di più!\n"
	.string "Ciao!$"

MatchCall_BattlePikeText3::
	.string "Ehi, {PLAYER}!\n"
	.string "Sono io, {STR_VAR_1}.\l"
	.string "Come va?\p"
	.string "Ho sentito che hai superato {STR_VAR_3} stanze\n"
	.string "al {STR_VAR_2}!\p"
	.string "Fai ancora meglio la prossima volta!\n"
	.string "Ci sentiamo!$"

MatchCall_BattlePikeText4::
	.string "Ehi, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Ho sentito che hai fatto {STR_VAR_3} stanze\n"
	.string "al {STR_VAR_2}.\p"
	.string "Meglio che alleni i POKéMON e\n"
	.string "che mi dia da fare!$"

MatchCall_BattlePikeText5::
	.string "Ciao, {PLAYER}{KUN}!\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Ho sentito che hai superato {STR_VAR_3} stanze\n"
	.string "al {STR_VAR_2}.\p"
	.string "Meglio che mi dia da fare anch'io!\n"
	.string "A presto!$"

MatchCall_BattlePikeText6::
	.string "Ehi, {PLAYER}{KUN}?\n"
	.string "Sono {STR_VAR_1}. Come stai?\p"
	.string "A proposito, ho sentito che hai superato\n"
	.string "{STR_VAR_3} stanze al {STR_VAR_2}.\p"
	.string "Meglio che alleni i POKéMON prima\n"
	.string "che tu vada troppo avanti.$"

MatchCall_BattlePikeText7::
	.string "{PLAYER}{KUN}?\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Eri al {STR_VAR_2}\n"
	.string "e hai superato {STR_VAR_3} stanze?\p"
	.string "Che burbero.\p"
	.string "Oh, ecco un POKéMON raro!\n"
	.string "Okay, ciao.$"

MatchCall_BattlePikeText8::
	.string "Oh, {PLAYER}{KUN}, come stai?\n"
	.string "Sono {STR_VAR_1}.\l"
	.string "Spero che tu stia bene.\l"
	.string "Oh, ma sì.\p"
	.string "Ho sentito che hai superato\n"
	.string "{STR_VAR_3} stanze al {STR_VAR_2}.\p"
	.string "Che impressionante!\n"
	.string "Devo allenare i POKéMON come te.\l"
	.string "Ci vediamo.$"

MatchCall_BattlePikeText9::
	.string "Oh, {PLAYER}{KUN}, ciao!\n"
	.string "Sono {STR_VAR_1}!\p"
	.string "Ho sentito! Hai superato\n"
	.string "{STR_VAR_3} stanze al {STR_VAR_2}!\p"
	.string "Che forte!\n"
	.string "Meglio che mi impegni anch'io!$"

MatchCall_BattlePikeText10::
	.string "Oh, {PLAYER}{KUN}, ciao.\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Hai superato {STR_VAR_3} stanze\n"
	.string "al {STR_VAR_2}?\p"
	.string "Bel risultato.\n"
	.string "Devo impegnarmi di più.$"

MatchCall_BattlePikeText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Sento che sei il terrore\n"
	.string "del {STR_VAR_2}?\p"
	.string "Hai superato, che so, {STR_VAR_3} stanze?\n"
	.string "Qualcosa conta, dai.\p"
	.string "Chissà se potrò mai diventare\n"
	.string "un campione?\p"
	.string "…Praticamente impossibile?\n"
	.string "Beh, ci vediamo!$"

MatchCall_BattlePikeText12::
	.string "Ciao, {PLAYER}{KUN}.\n"
	.string "Sono io, {STR_VAR_1}.\l"
	.string "Stai bene?\p"
	.string "Hai vinto superando {STR_VAR_3} stanze in\n"
	.string "un posto chiamato {STR_VAR_2}?\p"
	.string "Che storia.\n"
	.string "Ci vediamo!$"

MatchCall_BattlePikeText13::
	.string "Ah, ciao, {PLAYER}{KUN}!\n"
	.string "Sono {STR_VAR_1}!\l"
	.string "Spero che tu stia bene.\p"
	.string "Dicono che hai vinto in {STR_VAR_3} stanze\n"
	.string "al {STR_VAR_2}?\p"
	.string "Ammiro la tua energia!\n"
	.string "Ciao ora.$"

MatchCall_BattlePikeText14::
	.string "Oh, ciao, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\l"
	.string "Ho sentito parlare di te!\p"
	.string "Non hai superato {STR_VAR_3} stanze\n"
	.string "al {STR_VAR_2}?\p"
	.string "Sei un esempio!\n"
	.string "Ci vediamo!$"

MatchCall_BattlePyramidText1::
	.string "Ciao! {PLAYER}?\n"
	.string "Ciao, sono {STR_VAR_1}!\l"
	.string "Ho sentito la notizia!\p"
	.string "Hai salito {STR_VAR_3} piani dentro\n"
	.string "la {STR_VAR_2}, vero?\p"
	.string "Che fantastico!\n"
	.string "Dovrei provare anch'io.$"

MatchCall_BattlePyramidText2::
	.string "Ciao, sono {STR_VAR_1}!\n"
	.string "Ho sentito parlare di te!\p"
	.string "Dicono che hai superato\n"
	.string "{STR_VAR_3} piani nella {STR_VAR_2}.\p"
	.string "Wow, fantastico!\n"
	.string "Meglio che alleni i POKéMON anch'io!$"

MatchCall_BattlePyramidText3::
	.string "Ehi, {PLAYER}!\n"
	.string "Sono io, {STR_VAR_1}.\l"
	.string "Come va?\p"
	.string "Ho sentito che hai salito {STR_VAR_3} piani\n"
	.string "nella {STR_VAR_2}!\p"
	.string "Fai ancora meglio la prossima volta!\n"
	.string "Ci sentiamo!$"

MatchCall_BattlePyramidText4::
	.string "Ehi, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Ho sentito che hai salito {STR_VAR_3} piani\n"
	.string "nella {STR_VAR_2}.\p"
	.string "Meglio che mi impegni e provi\n"
	.string "a tenere il passo!$"

MatchCall_BattlePyramidText5::
	.string "Ciao, {PLAYER}{KUN}!\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Ho sentito che hai salito {STR_VAR_3} piani\n"
	.string "nella {STR_VAR_2}.\p"
	.string "Meglio che mi dia da fare anch'io!\n"
	.string "A presto!$"

MatchCall_BattlePyramidText6::
	.string "Ehi, {PLAYER}{KUN}?\n"
	.string "Sono {STR_VAR_1}. Come stai?\p"
	.string "A proposito, ho sentito che hai superato\n"
	.string "{STR_VAR_3} piani nella {STR_VAR_2}.\p"
	.string "Meglio che alleni i POKéMON prima\n"
	.string "che tu vada troppo avanti.$"

MatchCall_BattlePyramidText7::
	.string "{PLAYER}{KUN}?\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Eri al {STR_VAR_2}\n"
	.string "e hai salito {STR_VAR_3} piani?\p"
	.string "Bello. C'erano POKéMON rari\n"
	.string "lì?\p"
	.string "No, eh?\n"
	.string "Okay, ciao.$"

MatchCall_BattlePyramidText8::
	.string "Oh, {PLAYER}{KUN}, come stai?\n"
	.string "Sono {STR_VAR_1}.\l"
	.string "Spero che tu stia bene.\l"
	.string "Oh, ma sì.\p"
	.string "Ho sentito che hai superato\n"
	.string "{STR_VAR_3} piani nella {STR_VAR_2}.\p"
	.string "Che impressionante!\n"
	.string "Devo allenare i POKéMON come te.\l"
	.string "Ci vediamo.$"

MatchCall_BattlePyramidText9::
	.string "Oh, {PLAYER}{KUN}, ciao!\n"
	.string "Sono {STR_VAR_1}!\p"
	.string "Ho sentito! Hai superato\n"
	.string "{STR_VAR_3} piani nella {STR_VAR_2}!\p"
	.string "Che forte!\n"
	.string "Meglio che mi impegni anch'io!$"

MatchCall_BattlePyramidText10::
	.string "Oh, {PLAYER}{KUN}, ciao.\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Hai salito {STR_VAR_3} piani dentro\n"
	.string "la {STR_VAR_2}?\p"
	.string "Bel risultato.\n"
	.string "Devo impegnarmi di più.$"

MatchCall_BattlePyramidText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\p"
	.string "Sento che sei il terrore\n"
	.string "della {STR_VAR_2}?\p"
	.string "Hai salito, che so, {STR_VAR_3} piani?\n"
	.string "Qualcosa conta, dai.\p"
	.string "Chissà se potrò mai diventare\n"
	.string "un campione?\p"
	.string "…Praticamente impossibile?\n"
	.string "Beh, ci vediamo!$"

MatchCall_BattlePyramidText12::
	.string "Ciao, {PLAYER}{KUN}.\n"
	.string "Sono io, {STR_VAR_1}.\l"
	.string "Stai bene?\p"
	.string "Hai vinto superando {STR_VAR_3} piani in\n"
	.string "un posto chiamato {STR_VAR_2}?\p"
	.string "Che storia.\n"
	.string "Ci vediamo!$"

MatchCall_BattlePyramidText13::
	.string "Ah, ciao, {PLAYER}{KUN}!\n"
	.string "Sono {STR_VAR_1}!\l"
	.string "Spero che tu stia bene.\p"
	.string "Dicono che hai salito {STR_VAR_3} piani\n"
	.string "nella {STR_VAR_2}?\p"
	.string "Ammiro la tua energia!\n"
	.string "Ciao ora.$"

MatchCall_BattlePyramidText14::
	.string "Oh, ciao, {PLAYER}{KUN}.\n"
	.string "Sono {STR_VAR_1}.\l"
	.string "Ho sentito parlare di te!\p"
	.string "Non hai superato {STR_VAR_3} piani\n"
	.string "nella {STR_VAR_2}?\p"
	.string "Sei un esempio!\n"
	.string "Ci vediamo!$"

MatchCall_Text_Mom1::
	.string "MAMMA: Tuo padre e tu…\n"
	.string "I POKéMON affascinano tutti.\p"
	.string "Qual è il fascino dei POKéMON?\p"
	.string "Io?\n"
	.string "Adoro i POKéMON che mi aiutano\l"
	.string "nelle faccende di ogni giorno.$"

MatchCall_Text_Mom2::
	.string "MAMMA: Ciao, {PLAYER}!\n"
	.string "Tuo padre si chiude in continuazione\l"
	.string "nella PALESTRA di PETALBURG.\p"
	.string "Torna a casa ogni tanto.\n"
	.string "Ma poi ci ritorna quando\l"
	.string "ha mangiato tutto il possibile.\p"
	.string "Immagino che perdere contro di te\n"
	.string "sia stato un duro colpo per lui!$"

MatchCall_Text_Mom3::
	.string "MAMMA: {PLAYER}…\n"
	.string "Non preoccuparti per me o per casa.\p"
	.string "Consuma quelle SCARPE DA GINNASTICA\n"
	.string "fino a consumarle, tesoro!$"

MatchCall_Text_Baoba1::
	.string "BAOBA: {PLAYER}!\n"
	.string "La SAFARI ZONE è quasi pronta!\p"
	.string "Ti chiamo appena\n"
	.string "è finita!$"

MatchCall_Text_Baoba2::
	.string "BAOBA: {PLAYER}!\n"
	.string "La SAFARI ZONE è aperta! Vieni\p"
	.string "quando vuoi!$"

MatchCall_Text_Roxanne1::
	.string "ROXANNE: Oh, ciao, {PLAYER}!\p"
	.string "Mi sono allenata molto\n"
	.string "da quando ci siamo visti.\p"
	.string "Mi servirà ancora un po' di tempo\n"
	.string "prima di riaprire la PALESTRA.\p"
	.string "Ma quando lo farò, vieni a trovarmi\n"
	.string "per una rivincita!$"

MatchCall_Text_Roxanne2::
	.string "ROXANNE: Sei {PLAYER}?\n"
	.string "Congratulazioni!\l"
	.string "Ho sentito parlare di te!\p"
	.string "Quanto a me, mi serve ancora un po'\n"
	.string "di tempo prima di riaprire la PALESTRA.\p"
	.string "Ma quando lo farò, vieni a trovarmi\n"
	.string "per una rivincita!$"

MatchCall_Text_Roxanne3::
	.string "ROXANNE: {PLAYER}!\n"
	.string "La mia PALESTRA è pronta!\p"
	.string "Passa a RUSTBORO quando\n"
	.string "puoi!$"

MatchCall_Text_Roxanne4::
	.string "ROXANNE: Nella PALESTRA di RUSTBORO,\n"
	.string "il fatto che ci siamo battuti, {PLAYER},\l"
	.string "è motivo d'orgoglio.$"

MatchCall_Text_Brawly1::
	.string "BRAWLY: Ehi, {PLAYER}{KUN}!\p"
	.string "Ho imparato molto dalla lotta\n"
	.string "che abbiamo fatto.\p"
	.string "Voglio rifare allenamento,\n"
	.string "poi riaprire la PALESTRA.\p"
	.string "Ci vorrà un po' prima che\n"
	.string "io sia pronto a gestirla di nuovo.\p"
	.string "Ma se riapro la PALESTRA,\n"
	.string "voglio che mi sfidi ancora.$"

MatchCall_Text_Brawly2::
	.string "BRAWLY: Ehi, {PLAYER}{KUN}!\n"
	.string "Congratulazioni!\p"
	.string "La notizia delle tue imprese è\n"
	.string "arrivata con le onde!\p"
	.string "Sembra che io debba lavorare\n"
	.string "ancora sul mio allenamento.\p"
	.string "Ci vorrà un po' prima che\n"
	.string "io sia pronto a gestirla di nuovo.\p"
	.string "Ma se riapro la PALESTRA,\n"
	.string "voglio che mi sfidi ancora.$"

MatchCall_Text_Brawly3::
	.string "BRAWLY: Ehi, {PLAYER}{KUN}!\n"
	.string "La mia PALESTRA è pronta!\p"
	.string "Torna a PORTOALGHE quando\n"
	.string "vuoi per un'altra sfida!$"

MatchCall_Text_Brawly4::
	.string "BRAWLY: {PLAYER}{KUN}, non credo\n"
	.string "che mi stancherò mai di lottare con te!$"

MatchCall_Text_Wattson1::
	.string "WATTSON: Oh, sei tu!\p"
	.string "Da quando te ne sei andato, ho rifatto\n"
	.string "l'allenamento da zero.\p"
	.string "Direi che mi serve ancora un po'\n"
	.string "di tempo per riaprire la PALESTRA.\p"
	.string "Dovrai aspettare!\n"
	.string "Wahahahaha!$"

MatchCall_Text_Wattson2::
	.string "WATTSON: Wahahahaha!\p"
	.string "Hai fatto sul serio, eh?\n"
	.string "Ho sentito parlare di te!\p"
	.string "A quanto pare devo allenarmi\n"
	.string "ancora un po'.\p"
	.string "Direi che mi serve ancora un po'\n"
	.string "di tempo per riaprire la PALESTRA.\p"
	.string "Dovrai aspettare!\n"
	.string "Wahahahaha!$"

MatchCall_Text_Wattson3::
	.string "WATTSON: Oh, sei tu!\n"
	.string "La mia PALESTRA è pronta!\p"
	.string "Vieni a CICLAMIPO quando vuoi!\n"
	.string "Wahahahaha!$"

MatchCall_Text_Wattson4::
	.string "WATTSON: Wahahaha!\p"
	.string "Lottare con te è sempre carico\n"
	.string "di energia elettrizzante!$"

MatchCall_Text_Flannery1::
	.string "FIAMMETTA: {PLAYER}…\p"
	.string "Nella nostra lotta ho capito quanto\n"
	.string "fossi immatura.\p"
	.string "Ma non ho finito!\p"
	.string "Ricomincio l'allenamento e\n"
	.string "riapro la PALESTRA.\p"
	.string "Quando sarà il momento, {PLAYER},\n"
	.string "sfidaci di nuovo.$"

MatchCall_Text_Flannery2::
	.string "FIAMMETTA: Ciao, {PLAYER}?\n"
	.string "Congratulazioni!\p"
	.string "La notizia del tuo successo è arrivata\n"
	.string "come il calore di un vulcano!\p"
	.string "Il nostro allenamento procede\n"
	.string "benissimo.\p"
	.string "Quando la PALESTRA sarà pronta,\n"
	.string "apparirà un segno accanto al mio\l"
	.string "nome nella lista del MATCH CALL.$"

MatchCall_Text_Flannery3::
	.string "FIAMMETTA: Oh, {PLAYER}?\n"
	.string "La nostra PALESTRA è pronta!\p"
	.string "Vieni a CAMPIANA per un bagno\n"
	.string "alle sorgenti e una sfida!$"

MatchCall_Text_Flannery4::
	.string "FIAMMETTA: {PLAYER}…\n"
	.string "Sono certa che migliori\l"
	.string "ad allenarti ogni volta.$"

MatchCall_Text_Winona1::
	.string "WINONA: Ciao, {PLAYER}!\p"
	.string "Grazie alla nostra lotta ho capito\n"
	.string "quali sono i miei punti deboli!\p"
	.string "Quando riaprirò la PALESTRA, non\n"
	.string "perderò più!$"

MatchCall_Text_Winona2::
	.string "WINONA: Ce l'hai fatta, {PLAYER}!\p"
	.string "La notizia del nuovo CAMPIONE\n"
	.string "è arrivata a DORSOPOLI!\p"
	.string "Ma… La prossima volta non\n"
	.string "finirà allo stesso modo.$"

MatchCall_Text_Winona3::
	.string "WINONA: Sei tu, {PLAYER}?\n"
	.string "La nostra PALESTRA ha riaperto!\p"
	.string "Ti aspettiamo a DORSOPOLI!$"

MatchCall_Text_Winona4::
	.string "WINONA: {PLAYER}…\n"
	.string "Ho perso, ma le mie ali non\l"
	.string "si spezzeranno mai.\p"
	.string "Proprio come tu non hai mai perso\n"
	.string "di vista il tuo sogno.$"

MatchCall_Text_TateLiza1::
	.string "TATE: Oh! Tu sei…\n"
	.string "LIZA: {PLAYER}!\p"
	.string "TATE: Ci stiamo allenando di nuovo…\n"
	.string "LIZA: Per riaprire la nostra PALESTRA!\p"
	.string "TATE: Quando sarà pronta…\n"
	.string "LIZA: Quando sarà pronta…\p"
	.string "TATE: Apparirà un segno accanto al nome…\n"
	.string "LIZA: Nella lista del POKéNAV.$"

MatchCall_Text_TateLiza2::
	.string "TATE: {PLAYER}, congratulazioni!\n"
	.string "LIZA: {PLAYER}, congratulazioni!\p"
	.string "TATE: Noi due siamo…\n"
	.string "LIZA: Ancora in allenamento!\p"
	.string "TATE: Ci serve ancora tempo, ma…\n"
	.string "LIZA: Quando sarà pronta…\p"
	.string "TATE: Apparirà un segno accanto al nome…\n"
	.string "LIZA: Nella lista del POKéNAV.$"

MatchCall_Text_TateLiza3::
	.string "TATE: {PLAYER}!\n"
	.string "LIZA: {PLAYER}!\p"
	.string "TATE: La PALESTRA è pronta!\n"
	.string "LIZA: La PALESTRA è pronta!\p"
	.string "TATE: Vieni a trovarci…\n"
	.string "LIZA: A PORTOALGHE quando vuoi!$"

MatchCall_Text_TateLiza4::
	.string "TATE: {PLAYER}, la nostra lotta…\n"
	.string "LIZA: È un'esperienza preziosa.\p"
	.string "TATE: Sarebbe bello se…\n"
	.string "LIZA: Potessimo lottare di nuovo!$"

MatchCall_Text_Juan1::
	.string "RODOLFO: Hmm…\n"
	.string "{PLAYER}{KUN}… vero?\p"
	.string "La nostra lotta mi ha\n"
	.string "riportato alla mente quando\l"
	.string "incontrai ADRIANO.\p"
	.string "Forse sei un genio che potrà\n"
	.string "superare ADRIANO!$"

MatchCall_Text_Juan2::
	.string "RODOLFO: Fufu… {PLAYER}{KUN}…\n"
	.string "Hai infine raggiunto il tuo scopo.\p"
	.string "Il mio occhio per il talento non\n"
	.string "si è sbagliato…\p"
	.string "Spero in un'altra occasione di\n"
	.string "incontrarti, hai scalato la vetta\l"
	.string "del potere e del prestigio.$"

MatchCall_Text_Juan3::
	.string "RODOLFO: Hoho… {PLAYER}{KUN}…\p"
	.string "La nostra PALESTRA di PORTO ALTO\n"
	.string "ha riaperto, infine.\p"
	.string "Se vuoi vedermi, sei\n"
	.string "il benvenuto quando vuoi.$"

MatchCall_Text_Juan4::
	.string "RODOLFO: {PLAYER}{KUN}…\p"
	.string "Come la musica migliore, le lotte\n"
	.string "che combattiamo insieme toccano\l"
	.string "corde d'ispirazione nel mio cuore…\p"
	.string "Chiudendo gli occhi, ti vedo salire\n"
	.string "insieme alla melodia…$"

MatchCall_Text_Sidney::
	.string "SIDNEY: Ehi, {PLAYER}!\p"
	.string "Se vuoi batterti di nuovo\n"
	.string "con me, torna quando vuoi\l"
	.string "alla LEGA POKéMON.\p"
	.string "Sarò sempre qui!\n"
	.string "Ti aspetto!$"

MatchCall_Text_Phoebe::
	.string "PHOEBE: Ciao, {PLAYER}!\p"
	.string "Che ne dici di tornare qui\n"
	.string "ancora?\p"
	.string "Vorrei vedere quanto è diventato\n"
	.string "più stretto il tuo legame con i\l"
	.string "POKéMON.$"

MatchCall_Text_Glacia::
	.string "GLACIA: Ciao, {PLAYER}.\p"
	.string "Spero che tu non sia\n"
	.string "diventato pigro col tuo potere?\p"
	.string "Se vuoi raffreddare un po'\n"
	.string "le tue emozioni, vieni\l"
	.string "alla LEGA POKéMON…$"

MatchCall_Text_Drake::
	.string "DRAKE: Questa voce… {PLAYER}, giusto?\n"
	.string "Sembri in forma…\p"
	.string "Ho saputo che ora c'è\n"
	.string "una struttura chiamata BATTLE\l"
	.string "FRONTIER che mette alla prova\l"
	.string "gli ALLENATORI.\p"
	.string "Però, se vuoi vere lotte,\n"
	.string "non c'è niente come\l"
	.string "la LEGA POKéMON!\p"
	.string "Non sei d'accordo, {PLAYER}?$"

MatchCall_Text_Wallace::
	.string "WALLACE: Ciao, {PLAYER}{KUN}.\n"
	.string "Hai conosciuto STEVEN?\p"
	.string "Lui è…\n"
	.string "Davvero incredibilmente abile.\p"
	.string "Però è un tipo strano,\n"
	.string "lotta di rado.\p"
	.string "Preferisce cercare\n"
	.string "pietre rare.\p"
	.string "Scommetto che scava in una grotta\n"
	.string "o su una montagna impervia.\p"
	.string "Ma cos'è una pietra rara?\n"
	.string "Mi viene in mente solo un METEORITE…$"

MatchCall_Text_MayRayquazaCall:
	.string "… … … … … …\n"
	.string "… … … … … Beep!\p"
	.string "MAY: Ciao, {PLAYER}{KUN}!\p"
	.string "Ero a PACIFIDLOG fino a poco\n"
	.string "fa.\p"
	.string "Ho visto un POKéMON verde\n"
	.string "gigantesco volare nel cielo.\p"
	.string "Io…\n"
	.string "Non ho mai visto niente del genere.\p"
	.string "Chissà cos'era.\n"
	.string "Forse è una scoperta importante?\p"
	.string "… … … … … …\n"
	.string "… … … … … Click!$"

MatchCall_Text_BrendanRayquazaCall:
	.string "… … … … … …\n"
	.string "… … … … … Bip!\p"
	.string "BRANDON: Ehi, {PLAYER}!\n"
	.string "Ero a RIOLIVO poco fa.\p"
	.string "Ho visto un enorme POKéMON verde\n"
	.string "volare nel cielo.\p"
	.string "Non avevo mai visto niente di\n"
	.string "così straordinario.\p"
	.string "Vorrei che l'avessi visto\n"
	.string "anche tu, {PLAYER}.\p"
	.string "… … … … … …\n"
	.string "… … … … … Clic!$"

MatchCall_Text_May1::
	.string "PALOMA: Ciao, {PLAYER}{KUN}!\p"
	.string "Il SIG. MARINO ha lasciato il mare,\n"
	.string "ma lo vedo ancora in acqua\l"
	.string "col suo PEEKO ogni tanto.\p"
	.string "Dev'essere ancora innamorato del mare.$"

MatchCall_Text_May2::
	.string "MAY: Ciao, {PLAYER}{KUN}!\p"
	.string "Sai che paesini come\n"
	.string "PETALBURG e PORTOALGHE hanno PALESTRE?\p"
	.string "Chissà perché il grande porto di\n"
	.string "SLATEPORT non ha una PALESTRA.\p"
	.string "Quando ne costruiranno una lì,\n"
	.string "dovrei candidarmi come CAPO.$"

MatchCall_Text_May3::
	.string "PALOMA: Ciao, {PLAYER}{KUN}!\p"
	.string "Ti ricordi un uomo chiamato\n"
	.string "il TAGLIABOSCHI a FERRUGIPOLI?\l"
	.string "Aveva una casa lì, ricordi?\p"
	.string "Beh, ho scoperto che il suo\n"
	.string "fratellino vive a CICLAMIPOLI.\p"
	.string "Indovina come si chiama?\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "IL TIPO SPACCAROCCE!$"

MatchCall_Text_May4::
	.string "PALOMA: {PLAYER}{KUN}?\p"
	.string "GALLERIA FERRUGIPOLI…\n"
	.string "L'hanno chiamata così perché\l"
	.string "unisce FERRUGIPOLI e VERDANOVA.$"

MatchCall_Text_May5::
	.string "PALOMA: {PLAYER}{KUN}, come stai?\p"
	.string "Sono sul PERCORSO 111.\p"
	.string "Vado a riposarmi a casa di\n"
	.string "una signora.\p"
	.string "Vive proprio a nord\n"
	.string "del deserto.$"

MatchCall_Text_May6::
	.string "PALOMA: Ciao, {PLAYER}{KUN}!\p"
	.string "Conosci la TORRE\n"
	.string "MIRAGGIO nel deserto?\p"
	.string "Dicono che, come un miraggio,\n"
	.string "appaia e sparisca misteriosamente.\p"
	.string "Vorrei vederla.$"

MatchCall_Text_May7::
	.string "PALOMA: {PLAYER}{KUN}, ciao!\n"
	.string "Sono sul PERCORSO 119.\p"
	.string "C'è un gran fiume qui, e\n"
	.string "piove spesso.\p"
	.string "Sono fradicia!$"

MatchCall_Text_May8::
	.string "MAY: {PLAYER}{KUN}, ciao.\p"
	.string "MT. PYRE è un memoriale per i POKéMON\n"
	.string "che hanno perso la vita.\p"
	.string "Forse per questo è infestato\n"
	.string "da molti POKéMON di tipo SPETTRO!$"

MatchCall_Text_May9::
	.string "MAY: Ciao, {PLAYER}{KUN}!\p"
	.string "Pensavo di andare alle terme\n"
	.string "di LAVARIDGE.\p"
	.string "Ma lungo la strada, vicino al\n"
	.string "JAGGED PASS, ho incontrato dei\l"
	.string "loschi figuri. Che brutta aria!$"

MatchCall_Text_May10::
	.string "PALOMA: Ciao, {PLAYER}{KUN}!\n"
	.string "Hai visto le notizie?\p"
	.string "Dicono che il CAP. STERN abbia trovato\n"
	.string "la CAVERNA ABISSALE durante la sua\l"
	.string "spedizione col sottomarino.$"

MatchCall_Text_May11::
	.string "PALOMA: Ciao, {PLAYER}{KUN}!\n"
	.string "Non è bello?\p"
	.string "Anche senza barca puoi\n"
	.string "attraversare il mare con\l"
	.string "una mossa POKéMON.\p"
	.string "Sapevi che c'è di più?\p"
	.string "C'è una mossa POKéMON che ti\n"
	.string "porta sul fondo del mare.$"

MatchCall_Text_May12::
	.string "PALOMA: Ciao, {PLAYER}{KUN}!\n"
	.string "Spero vada tutto bene!\p"
	.string "Ti è mai capitato sul mare di\n"
	.string "trovare la strada\l"
	.string "bloccata?\p"
	.string "Immergiti e segui\n"
	.string "le fosse.\p"
	.string "Quando arrivi dall'altra parte,\n"
	.string "risali in superficie. Facile!$"

MatchCall_Text_May13::
	.string "PALOMA: Ciao, {PLAYER}{KUN}!\p"
	.string "Come va?\n"
	.string "Completi il POKéDEX?\p"
	.string "Ho sentito una voce: esistono\n"
	.string "POKéMON antichissimi.\l"
	.string "E sono tre!\p"
	.string "Ne vorrei vedere almeno uno…$"

MatchCall_Text_May14::
	.string "PALOMA: {PLAYER}{KUN}!\n"
	.string "Ho sentito le voci!\p"
	.string "Hai battuto il CAPOPALESTRA\n"
	.string "di PORTO ALTO?\p"
	.string "Allora non ti manca molto,\n"
	.string "vero?$"

MatchCall_Text_May15::
	.string "PALOMA: Non c'è un solo ALLENATORE\n"
	.string "in tutto HOENN che non sappia chi\l"
	.string "sei, {PLAYER}{KUN}!\p"
	.string "Quando dico che siamo amiche,\n"
	.string "{PLAYER}{KUN}, restano tutti\l"
	.string "sorpresi!$"

MatchCall_Text_Brendan1::
	.string "BRANDON: Ehi, {PLAYER}!\p"
	.string "Il SIG. MARINO ha lasciato il mare,\n"
	.string "ma lo vedo ancora in acqua\l"
	.string "col suo PEEKO ogni tanto.\p"
	.string "Dev'essere ancora innamorato\n"
	.string "del mare.$"

MatchCall_Text_Brendan2::
	.string "BRENDAN: Ehi, {PLAYER}!\p"
	.string "Non capisco come PETALBURG e\n"
	.string "DEWFORD abbiano una PALESTRA.\p"
	.string "Cioè, non quando il grande porto di\n"
	.string "SLATEPORT non ne ha una.\p"
	.string "Quando finalmente la costruiranno,\n"
	.string "mi candido come CAPOPALESTRA.$"

MatchCall_Text_Brendan3::
	.string "BRANDON: Ehi, {PLAYER}!\p"
	.string "Ti ricordi un tipo chiamato\n"
	.string "il TAGLIABOSCHI a FERRUGIPOLI?\l"
	.string "Aveva una casa lì, no?\p"
	.string "Beh, pare che il suo\n"
	.string "fratellino viva a CICLAMIPOLI.\p"
	.string "Indovina come si chiama?\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "IL TIPO SPACCAROCCE!$"

MatchCall_Text_Brendan4::
	.string "BRENDAN: Questa voce… {PLAYER}?\p"
	.string "La GALLERIA MONTANA ha questo nome\n"
	.string "perché unisce RUSTBORO e\l"
	.string "VERDANTURF.\p"
	.string "Lo sapevi?$"

MatchCall_Text_Brendan5::
	.string "BRANDON: {PLAYER}, come va?\p"
	.string "Sono sul PERCORSO 111.\p"
	.string "Vado a riposarmi a casa di\n"
	.string "una signora a nord del deserto.\p"
	.string "Se passi da quelle parti,\n"
	.string "vai a trovarla anche tu.$"

MatchCall_Text_Brendan6::
	.string "BRANDON: Ehi, {PLAYER}!\p"
	.string "Conosci la TORRE\n"
	.string "MIRAGGIO nel deserto?\p"
	.string "Dicono che, come un miraggio,\n"
	.string "si veda solo a volte.\p"
	.string "Vorrei vederla!$"

MatchCall_Text_Brendan7::
	.string "BRANDON: Chi parla? Ah, {PLAYER}?\n"
	.string "Indovina? Sono sul PERCORSO 119.\p"
	.string "C'è un gran fiume qui, e\n"
	.string "piove sempre.\p"
	.string "Sono fradicio!$"

MatchCall_Text_Brendan8::
	.string "BRENDAN: {PLAYER}!\p"
	.string "MT. PYRE è un memoriale per i POKéMON\n"
	.string "che hanno perso la vita.\p"
	.string "Forse per questo è infestato\n"
	.string "da molti POKéMON di tipo SPETTRO!$"

MatchCall_Text_Brendan9::
	.string "BRANDON: Ehi, {PLAYER}.\p"
	.string "Tornavo verso le sorgenti\n"
	.string "calde di CAMPIANA.\p"
	.string "Ma vicino al PASSAGGIO FRANATO ho visto\n"
	.string "dei tipi poco raccomandabili.\p"
	.string "Che inquietanti…\n"
	.string "Credo fossero del TEAM MAGMA.$"

MatchCall_Text_Brendan10::
	.string "BRANDON: Ciao, {PLAYER}!\n"
	.string "Hai sentito le notizie?\p"
	.string "Dicono che il CAP. STERN abbia trovato\n"
	.string "la CAVERNA ABISSALE durante la sua\l"
	.string "spedizione col sottomarino.$"

MatchCall_Text_Brendan11::
	.string "BRANDON: Ehi, {PLAYER}!\n"
	.string "Non è fantastico?\p"
	.string "Anche senza barca puoi\n"
	.string "attraversare il mare con\l"
	.string "una mossa POKéMON.\p"
	.string "E c'è una mossa che ti porta\n"
	.string "sul fondo del mare.\p"
	.string "I POKéMON possono tutto!$"

MatchCall_Text_Brendan12::
	.string "BRANDON: Ciao, {PLAYER}!\n"
	.string "Come te la passi?\p"
	.string "Ti è mai capitato di trovare\n"
	.string "la strada bloccata sul mare?\p"
	.string "Immergiti e segui le\n"
	.string "fosse sul fondo.\p"
	.string "Quando arrivi dall'altra parte,\n"
	.string "risali in superficie. Facile!$"

MatchCall_Text_Brendan13::
	.string "BRANDON: Ehi, {PLAYER}!\p"
	.string "Come va? Completi il\n"
	.string "POKéDEX?\p"
	.string "Ho sentito una voce: esistono\n"
	.string "POKéMON antichissimi.\l"
	.string "E non uno, ma tre!\p"
	.string "Ne vorrei catturare almeno uno…$"

MatchCall_Text_Brendan14::
	.string "BRANDON: {PLAYER}!\n"
	.string "Ho sentito le voci!\p"
	.string "Hai battuto il CAPOPALESTRA\n"
	.string "di PORTO ALTO? Fantastico!\p"
	.string "Ormai sei quasi arrivato!$"

MatchCall_Text_Brendan15::
	.string "BRANDON: Non c'è ALLENATORE in\n"
	.string "tutto HOENN che non sappia chi\l"
	.string "sei, {PLAYER}!\p"
	.string "Quando dico che siamo amici,\n"
	.string "{PLAYER}, tutti quanti\l"
	.string "mi invidiano!$"

MatchCall_Text_Wally1::
	.string "WALLY: Oh, {PLAYER}!\p"
	.string "Sto diventando più sano\n"
	.string "e in forma.\p"
	.string "Spero di diventare presto un ALLENATORE\n"
	.string "come te, {PLAYER}!$"

MatchCall_Text_Wally2::
	.string "WALLY: {PLAYER}, ciao!\p"
	.string "Da quando è stato aperto il\n"
	.string "TUNNEL METAURI, WANDA è felicissima!$"

MatchCall_Text_Wally3::
	.string "WALLY: Oh, {PLAYER}!\p"
	.string "Io… ho lasciato casa di mio zio\n"
	.string "a METAURI senza dire nulla.\p"
	.string "Chissà se è furioso con me…\p"
	.string "{PLAYER}, tu capisci come\n"
	.string "mi sento, vero?$"

MatchCall_Text_Wally4::
	.string "WALLY: {PLAYER}?\n"
	.string "Sono io, WALLY!\p"
	.string "Il mondo degli ALLENATORI è fantastico!\p"
	.string "Con i miei POKéMON accanto,\n"
	.string "tutti mi salutano!\p"
	.string "È come se ci unissimo\n"
	.string "tutti grazie ai POKéMON!$"

MatchCall_Text_Wally5::
	.string "WALLY: {PLAYER}? È fantastico!\n"
	.string "Quel RALTS che abbiamo preso insieme?\l"
	.string "Si è evoluto, {PLAYER}!\p"
	.string "Forse sono portato…\p"
	.string "Oh, ma non devo montarmi\n"
	.string "la testa così!\p"
	.string "Dopotutto, i complimenti vanno\n"
	.string "ai POKéMON!$"

MatchCall_Text_Wally6::
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "WALLY sembra fuori dalla\n"
	.string "portata del POKéNAV…$"

MatchCall_Text_Wally7::
	.string "WALLY: Oh, {PLAYER}!\p"
	.string "Prima di conoscerti, uscivo\n"
	.string "quasi mai di casa…\p"
	.string "Ma ora vivo un'avventura con\n"
	.string "i miei POKéMON…\p"
	.string "{PLAYER}…\n"
	.string "Grazie…$"

MatchCall_Text_Scott1::
	.string "SCOTT: Ciao, {PLAYER}{KUN}!\p"
	.string "Lo sai che i POKéMON si trovano\n"
	.string "ovunque?\p"
	.string "Come in montagna, nel mare,\n"
	.string "nell'erba alta dappertutto?\p"
	.string "Proprio come i POKéMON, anche gli\n"
	.string "ALLENATORI sono ovunque.\p"
	.string "Perciò devo correre\n"
	.string "dappertutto anch'io. Che vita!$"

MatchCall_Text_Scott2::
	.string "SCOTT: Sono sul PERCORSO 119 ora.\n"
	.string "È pieno di ALLENATORI!\p"
	.string "Ed è anche ricoperto di erba alta\n"
	.string "dappertutto, a quanto pare.\p"
	.string "Camminare qui in pantaloncini\n"
	.string "mi fa il solletico!$"

MatchCall_Text_Scott3::
	.string "SCOTT: Ciao ciao, {PLAYER}{KUN}!\p"
	.string "Hai avuto modo di salire sul\n"
	.string "MT. PYRE?\p"
	.string "È un memoriale per i POKéMON\n"
	.string "che sono passati a miglior vita.\p"
	.string "Ogni ALLENATORE dovrebbe salirci\n"
	.string "in cima almeno una volta.$"

MatchCall_Text_Scott4::
	.string "SCOTT: Ciao, {PLAYER}{KUN}!\p"
	.string "Ho sentito di queste strane\n"
	.string "bande che danno fastidio.\p"
	.string "TEAM MAGMA e TEAM AQUA,\n"
	.string "credo fossero.\p"
	.string "Immagino ci siano degli\n"
	.string "ALLENATORI abili tra loro.\p"
	.string "…Ma se sono teppisti…$"

MatchCall_Text_Scott5::
	.string "SCOTT: Oh, ciao, {PLAYER}{KUN}.\p"
	.string "Ci saranno ALLENATORI forti\n"
	.string "in fondo al mare?\p"
	.string "Non posso andare a controllare.\n"
	.string "Tanto non so nuotare.\l"
	.string "E non alleno POKéMON…$"

MatchCall_Text_Scott6::
	.string "SCOTT: Ciao, ciao, {PLAYER}{KUN}!\p"
	.string "Sai che puoi sfidare\n"
	.string "la LEGA POKéMON quando hai\l"
	.string "preso tutte le MEDAGLIE?\p"
	.string "Con il tuo talento, diventare\n"
	.string "CAMPIONE non è un sogno.\p"
	.string "Ma lo sapevi?\n"
	.string "C'è un posto ancora migliore.\p"
	.string "Ma non dico altro\n"
	.string "per il momento.\p"
	.string "È qualcosa che puoi\n"
	.string "aspettarti.\p"
	.string "Quando avrai vinto nella\n"
	.string "LEGA POKéMON entrando nella HALL\l"
	.string "OF FAME!$"

MatchCall_Text_Scott7::
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "SCOTT sembra fuori dalla\n"
	.string "portata del POKéNAV…$"

MatchCall_Text_Norman1::
	.string "PAPÀ: A RUSTBORO c'è un uomo\n"
	.string "che va con lo strano nome di\l"
	.string "TAGLIABOSCHI.\p"
	.string "Se passi da quelle parti, dovresti\n"
	.string "andarlo a trovare.$"

MatchCall_Text_Norman2::
	.string "PAPÀ: Hm… Piano piano, ma di\n"
	.string "certo, stai diventando\l"
	.string "più forte, {PLAYER}.\p"
	.string "Più diventi forte, più lontano\n"
	.string "e in alto voli da Mamma\l"
	.string "e da me…\p"
	.string "Difficile spiegare questa sensazione.$"

MatchCall_Text_Norman3::
	.string "PAPÀ: Capisco…\n"
	.string "Hai collezionato quattro MEDAGLIE…\p"
	.string "Ora non si può più evitare.\n"
	.string "Ci batteremo come promesso.\p"
	.string "Vieni quando vuoi.\n"
	.string "Ti aspetteremo tutti!$"

MatchCall_Text_Norman4::
	.string "PAPÀ: {PLAYER}! Vai a trovare\n"
	.string "la mamma ogni tanto.\p"
	.string "Io resto qui e\n"
	.string "raddoppio l'allenamento.\p"
	.string "La via della lotta è profonda\n"
	.string "e implacabile!$"

MatchCall_Text_Norman5::
	.string "PAPÀ: Oh, ciao, {PLAYER}!\p"
	.string "Come? L'EMBLEMA MAGMA?\n"
	.string "Non so cosa sia.\p"
	.string "Ma con un nome simile, forse\n"
	.string "è legato in qualche modo a un vulcano!$"

MatchCall_Text_Norman6::
	.string "PAPÀ: Hiyah! Haah! Dwah!\p"
	.string "…Oh? {PLAYER}!\p"
	.string "Mi hai colto proprio in mezzo\n"
	.string "a una sessione di allenamento!$"

MatchCall_Text_Norman7::
	.string "PAPÀ: {PLAYER}!\p"
	.string "Chi l'avrebbe mai detto che saresti\n"
	.string "diventato CAMPIONE della LEGA…\p"
	.string "Okay!\n"
	.string "Non mi lascerò superare!$"

MatchCall_Text_Norman8::
	.string "PAPÀ: Hm? {PLAYER}?\n"
	.string "Che tempismo!\p"
	.string "Stavolta ti sfido\n"
	.string "a una lotta.\p"
	.string "Ti aspetto nella PALESTRA di PETALBURG.\n"
	.string "Accetta la sfida quando vuoi!$"

MatchCall_Text_Norman9::
	.string "PAPÀ: …Mi stupisci, {PLAYER}.\n"
	.string "Fin dove ti innalzerai?$"

MatchCall_Text_Steven1::
	.string "STEVEN: Ciao, {PLAYER}{KUN}!\p"
	.string "Sei già stato a\n"
	.string "CICLAMIPOLI?\p"
	.string "Dovresti visitare il NEGOZIO BICICLETTE\n"
	.string "e prendere una MACH BIKE.\p"
	.string "Poi esplora bene la\n"
	.string "GROTTA GRANITO.\p"
	.string "Potresti fare una nuova\n"
	.string "scoperta.$"

MatchCall_Text_Steven2::
	.string "STEVEN: Ciao, {PLAYER}{KUN}!\p"
	.string "Ho conosciuto tanti\n"
	.string "ALLENATORI finora.\p"
	.string "Ma tu sei unico.\n"
	.string "Non sei come nessun altro.$"

MatchCall_Text_Steven3::
	.string "STEVEN: Ciao, {PLAYER}{KUN}!\p"
	.string "Quando vivi un'avventura con i\n"
	.string "tuoi POKéMON, cosa pensi?\p"
	.string "Li consideri dei forti\n"
	.string "compagni?\p"
	.string "Li vedi come simpatici\n"
	.string "compagni di viaggio?\p"
	.string "A seconda di come la pensi,\n"
	.string "l'avventura cambia significato.$"

MatchCall_Text_Steven4::
	.string "STEVEN: Pronto?\n"
	.string "{PLAYER}{KUN}?\p"
	.string "Ho un piccolo problema\n"
	.string "al CENTRO SPAZIALE.\p"
	.string "Scusa, ma ora non posso parlare.\n"
	.string "Ciao!$"

MatchCall_Text_Steven5::
	.string "STEVEN: Oh!\n"
	.string "{PLAYER}{KUN}!\p"
	.string "Non serve parlare.\n"
	.string "È troppo tardi per parlare.\p"
	.string "Devi credere in te stesso\n"
	.string "e fare ciò che è giusto.$"

MatchCall_Text_Steven6::
	.string "… … … … … …\p"
	.string "STEVEN non sembra rispondere\n"
	.string "alla chiamata…$"

MatchCall_Text_Steven7::
	.string "STEVEN: {PLAYER}{KUN}… Congratulazioni\n"
	.string "per essere entrato nell'ALBO D'ONORE.\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "Spero di rivederti\n"
	.string "da qualche parte!$"

MatchCall_Text_BirchRegisterCall:
	.string "PROF. BIRCH: Oh, {PLAYER}{KUN}!\n"
	.string "Ho già sentito parlare di te!\p"
	.string "Sembra che il tuo POKéNAV sia\n"
	.string "stato aggiornato con MATCH CALL.\p"
	.string "Beh, mi registro anch'io!\p"
	.string "Così potrò esaminare\n"
	.string "il tuo POKéDEX anche mentre sei\l"
	.string "in giro sul campo.\p"
	.string "… … … … … …$"

MatchCall_Text_RegisteredBirch:
	.string "PROF. BIRCH registrato\n"
	.string "nel POKéNAV.$"

MatchCall_Text_UnusedProfBirch:
	.string "PROF. BIRCH: Quando si ha sia\n"
	.string "il POKéDEX che il POKéNAV, studiare\l"
	.string "i POKéMON è più divertente, eh?$"

MatchCall_Text_MrStone1::
	.string "STONE: Oh? {PLAYER}{KUN}!\p"
	.string "Da quando mi hai chiamato, il POKéNAV\n"
	.string "deve funzionare bene!\p"
	.string "Anche altri saranno registrati,\n"
	.string "prova a chiamare pure loro!\p"
	.string "Bene! Bene!\n"
	.string "Sembri proprio felice!\p"
	.string "Hm…\n"
	.string "Come faccio a saperlo?\p"
	.string "Perché ti sto guardando dall'alto\n"
	.string "dalla finestra del mio ufficio!\p"
	.string "Wahahaha!\n"
	.string "Ci vediamo!$"

MatchCall_Text_MrStone2::
	.string "STONE: Oh? {PLAYER}{KUN}!\p"
	.string "Che succede? Hai dimenticato\n"
	.string "quella mia piccola commissione?\p"
	.string "Devi consegnare la mia lettera\n"
	.string "a STEVEN a DEWFORD.\p"
	.string "Poi consegna il nostro pacco al\n"
	.string "CAP. STERN a SLATEPORT.\p"
	.string "Te lo ricordi, vero?\p"
	.string "Ora, dato che sono un PRESIDENTE\n"
	.string "occupato, devo andare! Ciao ciao!$"

MatchCall_Text_MrStone3::
	.string "STONE: Oh! {PLAYER}{KUN}!\p"
	.string "Ah, quindi hai conosciuto STEVEN!\n"
	.string "Allora è meglio che ti ricompensi!\p"
	.string "Quando torni a RUSTBORO,\n"
	.string "passa dal mio ufficio.\p"
	.string "Ti aspetto!$"

MatchCall_Text_MrStone4::
	.string "STONE: Oh! {PLAYER}{KUN}!\p"
	.string "Sapevi che la DEVON stava\n"
	.string "scavando il TUNNEL RUSTURF?\p"
	.string "Ma abbiamo fermato l'operazione per\n"
	.string "proteggere i POKéMON della zona.\p"
	.string "C'era poco da pensare, davvero.\p"
	.string "È più importante lasciare i POKéMON\n"
	.string "in pace che preoccuparci del nostro\l"
	.string "comodo.$"

MatchCall_Text_MrStone5::
	.string "STONE: Ciao ciao, {PLAYER}{KUN}!\p"
	.string "Ho saputo da qualcuno a PETALBURG\n"
	.string "che sei figlio di NORMAN!\p"
	.string "Non c'è da stupirsi che tu sia\n"
	.string "così capace!$"

MatchCall_Text_MrStone6::
	.string "STONE: Come dici?\p"
	.string "Hai sfidato tuo padre e\n"
	.string "l'hai battuto?\p"
	.string "Incredibile!\p"
	.string "Non sapevo di essere amico\n"
	.string "di qualcuno così speciale! Wahaha!$"

MatchCall_Text_MrStone7::
	.string "Pronto!\n"
	.string "Qui è la DEVON CORPORATI…\l"
	.string "Oh, ciao, {PLAYER}!\p"
	.string "Il nostro PRESIDENTE era qui poco\n"
	.string "fa, ma è uscito.\p"
	.string "Il nostro PRESIDENTE è occupato, ma\n"
	.string "anche tu sembri esserlo, {PLAYER}.$"

MatchCall_Text_MrStone8::
	.string "…Eh? …Come dici?\p"
	.string "GROU… Sì? …DON?\p"
	.string "La linea cade…\n"
	.string "…non sento…\p"
	.string "BZZZZ…$"

MatchCall_Text_MrStone9::
	.string "…Eh? …Come dici?\p"
	.string "Seaflo… Sì? …Caver…?\p"
	.string "La linea cade…\n"
	.string "…non sento…\p"
	.string "BZZZZ…$"

MatchCall_Text_MrStone10::
	.string "STONE: {PLAYER}{KUN}! Sono io!\p"
	.string "A quanto pare sei stato coinvolto in\n"
	.string "mille cose, ma io, preso dagli affari,\l"
	.string "non ho idea di cosa esattamente!\p"
	.string "Comunque, ti esorto a prendere\n"
	.string "la strada in cui credi e a seguirla.\p"
	.string "Sarò sempre dalla tua parte!\n"
	.string "Abbi cura di te!$"

MatchCall_Text_MrStone11::
	.string "STONE: … … … … … …\n"
	.string "Sei forse {PLAYER}{KUN}?\p"
	.string "La tua voce è piena di sicurezza,\n"
	.string "non ti avevo riconosciuto subito!\p"
	.string "Hm! Devi venire a trovarci alla DEVON\n"
	.string "qualche volta!$"
