@ Only contains the text for the Mauville Man named Giddy. The rest is in scripts/mauville_man.inc
GiddyText_SoPretty::
	.string " così bello!$"

GiddyText_SoDarling::
	.string " così carino!$"

GiddyText_SoRelaxed::
	.string " così rilassante!$"

GiddyText_SoSunny::
	.string " che sole!$"

GiddyText_SoDesirable::
	.string " così desiderabile!$"

GiddyText_SoExciting::
	.string " così emozionante!$"

GiddyText_SoAmusing::
	.string " così divertente!$"

GiddyText_SoMagical::
	.string " così magico!$"

GiddyText_Is::
	.string " è$"

GiddyText_DontYouAgree::
	.string "\n"
	.string "Non sei d'accordo?$"

GiddyText_ISoWantToGoOnAVacation::
	.string "Voglio tanto andare in vacanza.\n"
	.string "Conosci un bel posto?$"

GiddyText_IBoughtCrayonsWith120Colors::
	.string "Ho preso pastelli con 120 colori!\n"
	.string "Non è bello?$"

GiddyText_WouldntItBeNiceIfWeCouldFloat::
	.string "Sarebbe bello fluttuare\n"
	.string "via su una nuvola di bolle?$"

GiddyText_WhenYouWriteOnASandyBeach::
	.string "Se scrivi sulla sabbia,\n"
	.string "le onde cancellano. Che tristezza.$"

GiddyText_WhatsTheBottomOfTheSeaLike::
	.string "Com'è il fondo del mare?\n"
	.string "Una volta vorrei proprio andarci!$"

GiddyText_WhenYouSeeTheSettingSunDoesIt::
	.string "Vedere il sole che tramonta\n"
	.string "ti fa venire voglia di casa?$"

GiddyText_LyingBackInTheGreenGrass::
	.string "Sdraiato sull'erba verde…\n"
	.string "Oh, che bello, che bello!$"

GiddyText_SecretBasesAreSoWonderful::
	.string "Le BASI SEGRETE sono fantastiche!\n"
	.string "Non senti l'emozione?$"
