MoveRelearner_Text_WouldLearnNewMoves:
	.string "Ciao, sono il Maestro Mosse.\n"
	.string "Vuoi imparare nuove mosse?$"

MoveRelearner_Text_LevelUpMoves:
	.string "Mosse Livello$"

MoveRelearner_Text_EggMoves:
	.string "Mosse Uovo$"

MoveRelearner_Text_TMMoves:
	.string "Mosse MT$"

MoveRelearner_Text_TutormoveMoves:
	.string "Mosse Tutor$"

MoveRelearner_Text_SeeYa:
	.string "Ci vediamo!$"

MoveRelearner_Text_AnythingElse:
	.string "Posso fare altro per te?$"

MoveRelearner_Text_ChoosePkmn:
	.string "Scegli un POKéMON.$"

MoveRelearner_Text_HaveNoPkmn:
	.string "Non hai POKéMON.$"

MoveRelearner_Text_CantTeachMoveToEgg:
	.string "Mi dispiace…\n"
	.string "Ma un Uovo non impara mosse.$"

MoveRelearner_Text_CantTeachMoveToPkmn:
	.string "Mi dispiace…\p"
	.string "Non mi pare di avere mosse\n"
	.string "da insegnare a quel POKéMON.$"

MoveRelearner_Text_LevelUpMoveLWR::
	.string "mossa livello$"

MoveRelearner_Text_EggMoveLWR::
	.string "mossa uovo$"

MoveRelearner_Text_TMMoveLWR::
	.string "mossa MT$"

MoveRelearner_Text_TutorMoveLWR::
	.string "mossa tutor$"

MoveRelearner_Text_MoveLWR::
	.string "mossa$"

MoveRelearner_Text_WhichXmoveShouldTeach:
	.string "Quale {STR_VAR_3} insegno?$"

MoveRelearner_Text_ThankYouComeAgain:
	.string "Grazie per averci scelto.\n"
	.string "Torna presto!$"
