MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnce:
	.string "Questa mossa si può imparare\n"
	.string "solo una volta. Va bene?$"

MoveTutor_Text_SwaggerTeach:
	.string "Eh! Il mio POKéMON è il migliore!\n"
	.string "È più forte di qualsiasi POKéMON!\p"
	.string "Facevo il bullo e me la tiravo\n"
	.string "così, finché il PRESIDENTE\l"
	.string "mi ha sgridato.\p"
	.string "Mi è passata la voglia di fare il bullo.\p"
	.string "Se vuoi, insegno la mossa\n"
	.string "BULLO a un tuo POKéMON.$"

MoveTutor_Text_SwaggerDeclined:
	.string "Come, no? Non riesci a entrare\n"
	.string "nello spirito della cosa?$"

MoveTutor_Text_SwaggerWhichMon:
	.string "Bene, a quale POKéMON vuoi\n"
	.string "insegnare BULLO?$"

MoveTutor_Text_SwaggerTaught:
	.string "D'ora in poi mi limiterò a lodare\n"
	.string "il mio POKéMON senza fare il bullo.$"

MoveTutor_Text_RolloutTeach:
	.string "Lo sapevi che da qui puoi andare\n"
	.string "lontano in quella direzione\l"
	.string "senza cambiare direzione?\p"
	.string "Potrei persino rotolare\n"
	.string "da quella parte.\p"
	.string "Secondo te il tuo POKéMON\n"
	.string "vorrà rotolare anche lui?\p"
	.string "Posso insegnargli la mossa ROTOLAMENTO\n"
	.string "se vuoi.$"

MoveTutor_Text_RolloutDeclined:
	.string "Non devi mica vergognarti.\n"
	.string "Rotoliamo!$"

MoveTutor_Text_RolloutWhichMon:
	.string "Ehehe, certo! Sarebbe bello\n"
	.string "se il POKéMON mi somigliasse.$"

MoveTutor_Text_RolloutTaught:
	.string "Rotolare nell'erba mi rende\n"
	.string "felice. Dai, rotoliamo!$"

MoveTutor_Text_FuryCutterTeach:
	.string "C'è una mossa che diventa più forte\n"
	.string "se la usi di seguito.\p"
	.string "È una mossa di tipo Coleottero,\n"
	.string "ed è davvero forte.\p"
	.string "Si chiama FURY CUTTER.\n"
	.string "La insegno a un POKéMON?$"

MoveTutor_Text_FuryCutterDeclined:
	.string "Non siamo sulla stessa lunghezza d'onda.$"

MoveTutor_Text_FuryCutterWhichMon:
	.string "Evvai!\n"
	.string "Dimmi a quale POKéMON insegno.$"

MoveTutor_Text_FuryCutterTaught:
	.string "Mi emoziona vedere se\n"
	.string "la mossa colpisce di seguito!$"

MoveTutor_MimicTeach:
	.string "Ah, giovincello!\p"
	.string "Anch'io sono giovane, ma imito\n"
	.string "stile e parlata degli anziani\l"
	.string "di questo paese.\p"
	.string "Che ne dici, giovincello?\n"
	.string "Accetteresti se ti offrissi\l"
	.string "di insegnarti la mossa MIMICA?$"

MoveTutor_MimicDeclined:
	.string "Oh, che peccato! Volevo insegnare\n"
	.string "MIMICA al tuo POKéMON!$"

MoveTutor_Text_MimicWhichMon:
	.string "Fwofwo! Così sia!\n"
	.string "Fammi vedere il POKéMON\l"
	.string "a cui vuoi che la insegni.$"

MoveTutor_Text_MimicTaught:
	.string "MIMICA è una mossa molto profonda.\p"
	.string "Sapresti eseguirla alla perfezione\n"
	.string "come me…?$"

MoveTutor_Text_MetronomeTeach:
	.string "Voglio un sacco di cose!\n"
	.string "Ma ho finito la paghetta…\p"
	.string "Non sarebbe bello se esistesse\n"
	.string "un incantesimo che fa apparire soldi\l"
	.string "agitando un dito?\p"
	.string "Se vuoi, posso insegnare al tuo POKéMON\n"
	.string "la mossa PLESSIMETRO.\p"
	.string "I soldi non appariranno, ma il POKéMON\n"
	.string "agiterà un dito. Ci stai?$"

MoveTutor_Text_MetronomeDeclined:
	.string "Va bene. Sono qui se cambi\n"
	.string "idea.$"

MoveTutor_Text_MetronomeWhichMon:
	.string "Okay! Gliela insegno!\n"
	.string "A quale POKéMON la insegno?$"

MoveTutor_Text_MetronomeTaught:
	.string "Quando un POKéMON agita il dito\n"
	.string "come il PLESSIMETRO, succedono\l"
	.string "un sacco di cose belle.\p"
	.string "Non sarebbe bello se potessimo\n"
	.string "usarlo anche noi?$"

MoveTutor_Text_SleepTalkTeach:
	.string "Umpf! Mia moglie usa FORZASEGRETA\n"
	.string "per restare sveglia.\p"
	.string "Dovrebbe schiacciare un pisolino come me,\n"
	.string "e usare SONNELOQUIO.\p"
	.string "Posso insegnare al tuo POKéMON\n"
	.string "SONNELOQUIO. Ti va?$"

MoveTutor_Text_SleepTalkDeclined:
	.string "Oh, va bene. Vuoi restare sveglio\n"
	.string "con FORZASEGRETA, eh…$"

MoveTutor_Text_SleepTalkWhichMon:
	.string "Ah, un bambino che apprezza!\n"
	.string "A quale POKéMON la insegno?$"

MoveTutor_Text_SleepTalkTaught:
	.string "Non ho mai azzeccato il gioco\n"
	.string "della moneta di mia moglie.\p"
	.string "Sarei felice di riuscirci\n"
	.string "anche mentre SONNELOQUIO…$"

MoveTutor_Text_SubstituteTeach:
	.string "Quando guardo il mondo da quassù\n"
	.string "sul tetto…\p"
	.string "Penso a quanto sarebbe bello\n"
	.string "se ci fossero più di un me\l"
	.string "per godermi tante vite diverse.\p"
	.string "Certo, è impossibile.\n"
	.string "Eh eh…\p"
	.string "Lo so! Ti andrebbe di far imparare\n"
	.string "SOSTITUTO a un POKéMON?$"

MoveTutor_Text_SubstituteDeclined:
	.string "Oh, no?\p"
	.string "A POKéMON can make a copy of\n"
	.string "itself using it, you know.$"

MoveTutor_Text_SubstituteWhichMon:
	.string "Eh eh…\n"
	.string "A quale POKéMON vuoi che\l"
	.string "insegni SOSTITUTO?$"

MoveTutor_Text_SubstituteTaught:
	.string "Noi esseri umani dovremmo goderci\n"
	.string "la nostra vita al massimo!\p"
	.string "Spero che diventerai così anche tu!$"

MoveTutor_Text_DynamicPunchTeach:
	.string "Non ce la faccio più!\p"
	.string "È del tutto inutile!\p"
	.string "Sono un ALLENATORE di tipo LOTTA,\n"
	.string "quindi non vinco alla PALESTRA\l"
	.string "per quanto mi sforzi!\p"
	.string "Argh! Pugno! Pugno! Pugno!\n"
	.string "Pugno! Pugno! Pugno!\p"
	.string "Ehi, non guardarmi così!\n"
	.string "Sto solo colpendo il suolo!\p"
	.string "O vuoi che insegni al tuo\n"
	.string "POKéMON DYNAMICPUNCH?$"

MoveTutor_Text_DynamicPunchDeclined:
	.string "Dannazione! Mi prendi in giro?\n"
	.string "Pugno! Pugno! Pugno!$"

MoveTutor_Text_DynamicPunchWhichMon:
	.string "Cosa? Davvero? Sei una brava persona!\n"
	.string "A quale POKéMON insegno?$"

MoveTutor_Text_DynamicPunchTaught:
	.string "Voglio che vinca alla PALESTRA di\n"
	.string "CERULEAN con quel DYNAMICPUNCH!$"

MoveTutor_Text_DoubleEdgeTeach:
	.string "Sigh…\p"
	.string "Il CAPOPALESTRA è davvero\n"
	.string "adorabile e ammirevole.\p"
	.string "Ma questo significa tanti\n"
	.string "rivali che lo vogliono.\p"
	.string "Ha un fascino da DOUBLE-EDGE.\n"
	.string "Non mi guarda nemmeno.\p"
	.string "Ti prego, lascia che insegni al\n"
	.string "tuo POKéMON la mossa DOUBLE-EDGE!$"

MoveTutor_Text_DoubleEdgeDeclined:
	.string "Oh…\n"
	.string "Anche tu mi rifiuti…$"

MoveTutor_Text_DoubleEdgeWhichMon:
	.string "Ok, a quale POKéMON insegno\n"
	.string "DOUBLE-EDGE?$"

MoveTutor_Text_DoubleEdgeTaught:
	.string "Non vivrò più d'amore!\n"
	.string "Diventerò forte!$"

MoveTutor_Text_ExplosionTeach:
	.string "Non intendo restare bloccato\n"
	.string "in questo posto sperduto per sempre.\p"
	.string "Vedrai, andrò in città\n"
	.string "e diventerò famoso.\p"
	.string "Davvero, provocherò\n"
	.string "una grande ESPLOSIONE di fama!\p"
	.string "Se hai sentito, con gioia\n"
	.string "insegno ESPLOSIONE al tuo POKéMON!$"

MoveTutor_Text_ExplosionDeclined:
	.string "Gaah! Mi rifiuti perché\n"
	.string "vivo in campagna?$"

MoveTutor_Text_ExplosionWhichMon:
	.string "Bene! Un'ESPLOSIONE sia!\n"
	.string "Quale POKéMON vuole saltare?$"

MoveTutor_Text_ExplosionTaught:
	.string "Per anni ho insegnato ai POKéMON\n"
	.string "a usare ESPLOSIONE, ma non ho\l"
	.string "mai acceso la mia ESPLOSIONE…\p"
	.string "Forse perché in fondo\n"
	.string "preferirei restare qui…$"

MoveTutor_Text_HeadbuttTeach:
	.string "Cosa sto facendo?\p"
	.string "Scuoto gli alberi con BOTTINTESTA.\p"
	.string "Secondo te il tuo POKéMON\n"
	.string "vorrà usare BOTTINTESTA?\p"
	.string "Posso insegnargli la mossa\n"
	.string "se vuoi. È divertente!$"
	
MoveTutor_Text_HeadbuttWhichMon:
	.string "Ehehe, certo! Sarebbe bello\n"
	.string "se il POKéMON mi somigliasse.$"

MoveTutor_Text_HeadbuttDeclined:
	.string "Non devi mica vergognarti.\n"
	.string "Diamo testate!$"

MoveTutor_Text_HeadbuttTaught:
	.string "Scuoti gli alberi con BOTTINTESTA.\n"
	.string "A volte ne cade un POKéMON addormentato.$"
