gOtherText_NewName::
	.string "NUOVO NOME$"

gNameChoice_Green::
	.string "VERDE$"

gNameChoice_Red::
	.string "ROSSO$"

gNameChoice_Leaf::
	.string "FOGLIA$"

gNameChoice_Fire::
	.string "FUOCO$"

gNameChoice_Gary::
	.string "GARY$"

gNameChoice_Kaz::
	.string "KAZ$"

gNameChoice_Toru::
	.string "TORU$"

gNameChoice_Ash::
	.string "ASH$"

gNameChoice_Kene::
	.string "KENE$"

gNameChoice_Geki::
	.string "GEKI$"

gNameChoice_Jak::
	.string "JAK$"

gNameChoice_Janne::
	.string "JANNE$"

gNameChoice_Jonn::
	.string "JONN$"

gNameChoice_Kamon::
	.string "KAMON$"

gNameChoice_Karl::
	.string "KARL$"

gNameChoice_Taylor::
	.string "TAYLOR$"

gNameChoice_Oscar::
	.string "OSCAR$"

gNameChoice_Hiro::
	.string "HIRO$"

gNameChoice_Max::
	.string "MAX$"

gNameChoice_Jon::
	.string "JON$"

gNameChoice_Ralph::
	.string "RALPH$"

gNameChoice_Kay::
	.string "KAY$"

gNameChoice_Tosh::
	.string "TOSH$"

gNameChoice_Roak::
	.string "ROAK$"

gNameChoice_Omi::
	.string "OMI$"

gNameChoice_Jodi::
	.string "JODI$"

gNameChoice_Amanda::
	.string "AMANDA$"

gNameChoice_Hillary::
	.string "HILLARY$"

gNameChoice_Makey::
	.string "MAKEY$"

gNameChoice_Michi::
	.string "MICHI$"

gNameChoice_Paula::
	.string "PAULA$"

gNameChoice_June::
	.string "JUNE$"

gNameChoice_Cassie::
	.string "CASSIE$"

gNameChoice_Rey::
	.string "REY$"

gNameChoice_Seda::
	.string "SEDA$"

gNameChoice_Kiko::
	.string "KIKO$"

gNameChoice_Mina::
	.string "MINA$"

gNameChoice_Norie::
	.string "NORIE$"

gNameChoice_Sai::
	.string "SAI$"

gNameChoice_Momo::
	.string "MOMO$"

gNameChoice_Suzi::
	.string "SUZI$"

gControlsGuide_Text_Intro::
	.string "I vari pulsanti saranno spiegati\n"
	.string "in ordine di importanza.$"

gControlsGuide_Text_DPad::
	.string "Muove il protagonista.\n"
	.string "Serve anche a scegliere le varie\n"
	.string "voci dei dati.$"

gControlsGuide_Text_AButton::
	.string "Serve a confermare, controllare\n"
	.string "le cose, parlare e far scorrere il testo.$"

gControlsGuide_Text_BButton::
	.string "Serve a uscire, annullare una scelta\n"
	.string "e annullare una modalità.$"

gControlsGuide_Text_StartButton::
	.string "Premi questo pulsante per aprire il\n"
	.string "MENU.$"

gControlsGuide_Text_SelectButton::
	.string "Serve a spostare gli strumenti e a usare\n"
	.string "uno strumento registrato.$"

gControlsGuide_Text_LRButtons::
	.string "Se ti serve aiuto per giocare\n"
	.string "o per come fare qualcosa,\n"
	.string "premi il pulsante L o R.$"

gOakSpeech_Text_AskPlayerGender::
	.string "Ora dimmi. Sei un maschio?\n"
	.string "O sei una femmina?$"

gPikachuIntro_Text_Page1::
	.string "Nel mondo in cui stai per\n"
	.string "entrare vivrai una grande\n"
	.string "avventura da protagonista.\n"
	.string "\n"
	.string "Parla con la gente e osserva\n"
	.string "tutto, in città, sui percorsi\n"
	.string "e nelle grotte. Cerca indizi\n"
	.string "e informazioni ovunque.$"

gPikachuIntro_Text_Page2::
	.string "Aiutando chi ha bisogno, superando\n"
	.string "prove e risolvendo misteri\n"
	.string "si apriranno nuove strade.\n"
	.string "\n"
	.string "A volte dovrai affrontare\n"
	.string "sfide e POKéMON selvatici.\n"
	.string "Sii audace e non fermarti.$"

gPikachuIntro_Text_Page3::
	.string "Durante l'avventura speriamo\n"
	.string "che incontrerai tante\n"
	.string "persone e crescerai dentro.\n"
	.string "È il nostro obiettivo.\n"
	.string "\n"
	.string "Premi A e che\n"
	.string "l'avventura abbia inizio!$"

gOakSpeech_Text_WelcomeToTheWorld::
	.string "Ciao!\n"
	.string "Piacere di conoscerti!\p"
	.string "Benvenuto nel mondo dei POKéMON!\p"
	.string "Io sono OAK.\p"
	.string "Tutti mi chiamano\n"
	.string "il PROFESSOR POKéMON.\p$"

gOakSpeech_Text_ThisWorld::
	.string "Questo mondo…$"

gOakSpeech_Text_IsInhabitedFarAndWide::
	.string "…è abitato in lungo e in largo da\n"
	.string "creature chiamate POKéMON.\p$"

gOakSpeech_Text_IStudyPokemon::
	.string "Per alcuni i POKéMON sono animali.\n"
	.string "Altri li usano per lottare.\p"
	.string "Quanto a me…\p"
	.string "Io studio i POKéMON di professione.\p$"

gOakSpeech_Text_TellMeALittleAboutYourself::
	.string "Ma prima, dimmi qualcosa\n"
	.string "di te.\p$"

gOakSpeech_Text_YourNameWhatIsIt::
	.string "Partiamo dal tuo nome.\n"
	.string "Qual è?\p$"

gOakSpeech_Text_SoYourNameIsPlayer::
	.string "Bene…\n"
	.string "Quindi ti chiami {PLAYER}.$"

gOakSpeech_Text_WhatWasHisName::
	.string "Lui è mio nipote.\p"
	.string "È tuo rivale da quando\n"
	.string "eravate piccoli.\p"
	.string "…Mmh, come si chiamava?$"

gOakSpeech_Text_YourRivalsNameWhatWasIt::
	.string "Il nome del tuo rivale, come era?$"

gOakSpeech_Text_ConfirmRivalName::
	.string "…Ehm, era {RIVAL}?$"

gOakSpeech_Text_RememberRivalsName::
	.string "Giusto! Ora ricordo!\n"
	.string "Si chiama {RIVAL}!\p$"

gOakSpeech_Text_LetsGo::
	.string "{PLAYER}!\p"
	.string "La tua personale leggenda POKéMON\n"
	.string "sta per iniziare!\p"
	.string "Un mondo di sogni e avventure\n"
	.string "con i POKéMON ti attende! Andiamo!$"
