gText_Oak_Welcome::
	.string "Ciao! Scusa l'attesa!\p"
	.string "Benvenuto nel mondo dei POKéMON!\p"
	.string "Io mi chiamo OAK.\p"
	.string "Tutti mi chiamano\n"
	.string "PROFESSOR POKéMON.\p"
	.string "$"

gText_Oak_Pokemon::
	.string "Questo lo chiamiamo “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Oak_MainSpeech::
	.string "Questo mondo è abitato da\n"
	.string "creature chiamate POKéMON.\p"
	.string "Persone e POKéMON vivono insieme,\n"
	.string "aiutandosi a vicenda.\p"
	.string "Alcuni giocano con i POKéMON,\n"
	.string "altri li fanno lottare. \p"
	.string "Ma non sappiamo ancora tutto\n"
	.string "sui POKéMON. \p"
	.string "Ci sono tanti misteri\n"
	.string "da risolvere. Perciò studio\l"
	.string "i POKéMON ogni giorno.\p"
	.string "$"

gText_Oak_AndYouAre::
	.string "E tu chi sei?$"

gText_Oak_BoyOrGirl::
	.string "Sei un maschio?\n"
	.string "O sei una femmina?$"

gText_Oak_WhatChallenge::
	.string "Quale sfida ti\n"
	.string "aspetti?$"

gText_Oak_ChallengeSelected::
	.string "Mi sembra il livello\n"
	.string "di sfida giusto!$" 

gText_Oak_WhatsYourName::
	.string "E tu come ti chiami?$"

gText_Oak_SoItsPlayer::
	.string "Oh! Quindi sei {PLAYER}{KUN}?$"

gText_Oak_YourePlayer::
	.string "{PLAYER}{KUN}, sei pronto?\p"
	.string "La tua avventura sta per\n"
	.string "cominciare.\p"
	.string "$"

gText_Oak_AreYouReady::
	.string "Affronterai momenti belli\n"
	.string "e sfide dure.\p"
	.string "Un mondo di sogni e avventure\n"
	.string "con i POKéMON ti aspetta! Via!\p"
	.string "Ci vediamo più tardi!\p"
	.string "$"
