gText_ObtainedTheItem::
	.string "Hai ottenuto {STR_VAR_2}!$"

gText_TheBagIsFull::
	.string "Lo ZAINO è pieno…$"

gText_PutItemInPocket::
	.string "{PLAYER} ha messo via {STR_VAR_2}\n"
	.string "nella TASCA {STR_VAR_3}.$"

gText_PlayerFoundOneItem::
	.string "{PLAYER} ha trovato un {STR_VAR_2}!$"

gText_TooBadBagIsFull::
	.string "Che peccato!\n"
	.string "Lo ZAINO è pieno…$"

gText_PlayerPutItemInBag::
	.string "{PLAYER} ha messo via {STR_VAR_2}\n"
	.string "nello ZAINO.$"

gText_ObtainedTheDecor::
	.string "Hai ottenuto {STR_VAR_2}!$"

gText_NoRoomLeftForAnother::
	.string "Che peccato! Non c'è più spazio per\n"
	.string "un altro {STR_VAR_2}…$"

gText_TheDecorWasTransferredToThePC::
	.string "Il {STR_VAR_2} è stato trasferito\n"
	.string "nel PC.$"

gText_ObtainedTheItems::
	.string "Hai ottenuto {STR_VAR_1} {STR_VAR_2}!$"

gText_PlayerFoundItems::
	.string "{PLAYER} ha trovato {STR_VAR_1} {STR_VAR_2}!$"

gText_PutCoinsAwayInCoinCase::
	.string "{PLAYER} ha messo i GETTONI\n"
	.string "nel PORTAGETTONI.$"

gText_FoundXCoins::
	.string "{PLAYER} ha trovato\n"
	.string "{STR_VAR_1} {STR_VAR_2}!$"

gText_FoundXItems::
	.string "{PLAYER} ha trovato\n"
	.string "{STR_VAR_1} {STR_VAR_2}(s)!$"

gText_CoinCaseIsFull::
	.string "Che peccato!\n"
	.string "Il PORTAGETTONI è pieno…$"

gText_NothingToPutThemIn::
	.string "Che peccato!\n"
	.string "Non c'è niente per metterli…$"
