Text_BootUpPC:
	.string "{PLAYER} ha acceso il PC.$"

gText_WhichPCShouldBeAccessed::
	.string "A quale PC vuoi accedere?$"

gText_AccessedSomeonesPC::
	.string "Accesso al PC di QUALCUNO.$"

gText_StorageSystemOpened::
	.string "Sistema di Memoria POKéMON aperto.$"

gText_AccessedPlayersPC::
	.string "Accesso al PC di {PLAYER}.$"

gText_AccessedLanettesPC::
	.string "Accesso al PC di LANETTE.$"

gText_AccessedBillsPC::
	.string "Accesso al PC di BILL.$"
