gText_WouldYouLikeToRestYourPkmn::
	.string "Ciao, benvenuto al\n"
	.string "CENTRO POKéMON.\p"
	.string "Curiamo i tuoi POKéMON\n"
	.string "stanchi.\p"
	.string "Vuoi far riposare i tuoi POKéMON?$"

gText_IllTakeYourPkmn::
	.string "Okay, ti prendo i POKéMON\n"
	.string "per qualche secondo.$"

gText_RestoredPkmnToFullHealth::
	.string "Grazie per l'attesa.\p"
	.string "Abbiamo curato i tuoi POKéMON\n"
	.string "completamente.$"

gText_WeHopeToSeeYouAgain::
	.string "Speriamo di rivederti!$"

gText_WelcomeCutShort::
	.string "Hello, and welcome to\n"
	.string "the POKéMON CENTER.\p"
	.string "We restore your tired POKéMON\n"
	.string "to full health.\p"
	.string "Would you like to…$"

gText_NoticesGoldCard::
	.string "Qu-questa carta…\n"
	.string "Ma è… la CARTA ORO?!\p"
	.string "Oh, il colore oro è stupendo!\n"
	.string "Le quattro stelle sembrano brillare!\p"
	.string "Ho visto vari ALLENATORI con\n"
	.string "una CARTA ARGENTO, ma, {PLAYER},\l"
	.string "sei il primo ALLENATORE che vedo\l"
	.string "con una CARTA ORO!\p"
	.string "Okay, {PLAYER}, permettimi\n"
	.string "di far riposare i tuoi POKéMON!$"

gText_YouWantTheUsual::
	.string "Che piacere vederti, {PLAYER}!\n"
	.string "Vuoi il solito, vero?$"

gText_IllTakeYourPkmn2::
	.string "Okay, ti prendo i POKéMON\n"
	.string "per qualche secondo.$"

gText_ThankYouForWaiting::
	.string "Grazie per l'attesa.$"

gText_WeHopeToSeeYouAgain2::
	.string "Speriamo di rivederti!$"

gText_PkmnCenterChallenge_NoVisitsLeft:: @ tx_difficulty_challenge
    .string "Scusa, ma stai giocando alla\n"
    .string "sfida POKéCENTER!\p"
    .string "Buona fortuna!{PAUSE_UNTIL_PRESS}$"
