gBirchDexRatingText_AreYouCurious::
	.string "PROF. BIRCH: Ah, {PLAYER}{KUN}!\p"
	.string "Sei curioso di sapere come va\n"
	.string "il tuo POKéDEX?$"

gBirchDexRatingText_Cancel::
	.string "Hm? Oh, non hai catturato abbastanza\n"
	.string "POKéMON perché ne valga la pena.$"

gBirchDexRatingText_SoYouveSeenAndCaught::
	.string "Hmhm…\p"
	.string "Dunque hai visto {STR_VAR_1} POKéMON,\n"
	.string "e ne hai catturati {STR_VAR_2}…$"

gBirchDexRatingText_LessThan10::
	.string "Vai di più nell'erba alta e cerca\n"
	.string "i POKéMON con più attenzione.$"

gBirchDexRatingText_LessThan20::
	.string "Direi che ci stai prendendo\n"
	.string "la mano. Ma da qui diventa più difficile.$"

gBirchDexRatingText_LessThan30::
	.string "Alcuni POKéMON appaiono solo in\n"
	.string "certe zone.\l"
	.string "Devi essere persistente.$"

gBirchDexRatingText_LessThan40::
	.string "Beh, servirebbe più quantità,\n"
	.string "ma ora comincia a sembrare\l"
	.string "un POKéDEX.$"

gBirchDexRatingText_LessThan50::
	.string "Sta venendo su piuttosto bene.\n"
	.string "Continua così.$"

gBirchDexRatingText_LessThan60::
	.string "Stai usando delle CANNE?\n"
	.string "Ci sono molti POKéMON nel mare.$"

gBirchDexRatingText_LessThan70::
	.string "Invece di limitarti a catturare POKéMON,\n"
	.string "che ne dici di farli anche evolvere?$"

gBirchDexRatingText_LessThan80::
	.string "Sarà un POKéDEX\n"
	.string "fantastico.\l"
	.string "È quello che sento.$"

gBirchDexRatingText_LessThan90::
	.string "Ne hai raccolti così tanti…\n"
	.string "Che talento straordinario!$"

gBirchDexRatingText_LessThan100::
	.string "Hai visitato la ZONA SAFARI?\p"
	.string "Dicono che ci siano POKéMON che\n"
	.string "si possono catturare solo lì.$"

gBirchDexRatingText_LessThan110::
	.string "Hai finalmente raggiunto\n"
	.string "il traguardo dei 100.\p"
	.string "Questo è un POKéDEX impressionante!$"

gBirchDexRatingText_LessThan120::
	.string "Potrebbero esserci POKéMON che si\n"
	.string "trovano usando SPACCAROCCIA.$"

gBirchDexRatingText_LessThan130::
	.string "Dovresti procurarti altri POKéMON\n"
	.string "scambiando con gli altri.$"

gBirchDexRatingText_LessThan140::
	.string "Ho sentito di POKéMON che si evolvono\n"
	.string "quando amano davvero il loro\l"
	.string "ALLENATORE.$"

gBirchDexRatingText_LessThan150::
	.string "Non sapevo che ci fossero così\n"
	.string "tante specie di POKéMON nella regione\l"
	.string "di HOENN.$"

gBirchDexRatingText_LessThan160::
	.string "A volte alcuni POKéMON appaiono\n"
	.string "in gran numero, come ondate.\p"
	.string "Non perdere occasioni\n"
	.string "simili.$"

gBirchDexRatingText_LessThan170::
	.string "Si può avere un'idea molto chiara\n"
	.string "dei POKéMON della regione di HOENN\l"
	.string "guardando il tuo POKéDEX.$"

gBirchDexRatingText_LessThan180::
	.string "Direi che ormai sei un\n"
	.string "PROFESSORE POKéMON, e anche\l"
	.string "bravo!$"

gBirchDexRatingText_LessThan190::
	.string "Con un POKéDEX così completo,\n"
	.string "sei davvero un professionista!$"

gBirchDexRatingText_LessThan200::
	.string "Sei molto vicino a completare\n"
	.string "questo POKéDEX.\l"
	.string "Me lo sento nelle ossa!$"

gBirchDexRatingText_DexCompleted::
	.string "Congratulazioni!\n"
	.string "Il tuo POKéDEX è completo!$"

gBirchDexRatingText_OnANationwideBasis::
	.string "Hmhm…\n"
	.string "A livello nazionale…\p"
	.string "Hai visto {STR_VAR_1} POKéMON,\n"
	.string "e ne hai catturati {STR_VAR_2}…$"

@ FRLG

PokedexRating_Text_HowIsPokedexComingAlong::
	.string "OAK: Che bello vederti!\n"
	.string "Come va il tuo POKéDEX?\p"
	.string "Dai, fammi dare un'occhiata.$"

PokedexRating_Text_SeenXOwnedY::
	.string "I progressi che hai fatto\n"
	.string "nel POKéDEX sono:\p"
	.string "{STR_VAR_1} POKéMON visti e\n"
	.string "{STR_VAR_2} POKéMON catturati.\p"
	.string "{FONT_NORMAL}Valutazione del PROF. OAK:$"

PokedexRating_Text_LessThan10::
	.string "Hai ancora molto da fare.\p"
	.string "Cerca in ogni cespuglio d'erba\n"
	.string "che vedi e trova POKéMON!$"

PokedexRating_Text_LessThan20::
	.string "Sembra che tu sia sulla\n"
	.string "strada giusta!\p"
	.string "Ho dato a un mio ASSISTENTE\n"
	.string "la MN di BALENO. Vai a prenderla!$"

PokedexRating_Text_LessThan30::
	.string "Il tuo POKéDEX ha bisogno di\n"
	.string "altre voci!\p"
	.string "Prova a catturare altre specie\n"
	.string "di POKéMON!$"

PokedexRating_Text_LessThan40::
	.string "Bene, si vede che ti stai\n"
	.string "impegnando!\p"
	.string "Ho dato a un mio ASSISTENTE un\n"
	.string "DETECTOR. Vai a prenderlo!$"

PokedexRating_Text_LessThan50::
	.string "Il tuo POKéDEX procede molto\n"
	.string "bene!\p"
	.string "Ho dato a un mio ASSISTENTE una\n"
	.string "MONETAMULETO. Vai a prenderla!$"

PokedexRating_Text_LessThan60::
	.string "Ah, hai superato le 50\n"
	.string "specie!\p"
	.string "Ho dato a un mio ASSISTENTE un\n"
	.string "CONDIVIS. ESP. Vai a prenderlo!$"

PokedexRating_Text_LessThan70::
	.string "Hoho! Questo POKéDEX sta\n"
	.string "diventando rispettabile!$"

PokedexRating_Text_LessThan80::
	.string "Molto bene!\p"
	.string "Penso che catturerai altri\n"
	.string "POKéMON andando a pesca!$"

PokedexRating_Text_LessThan90::
	.string "Meraviglioso! Fammi indovinare…\n"
	.string "Ti piace collezionare, vero?$"

PokedexRating_Text_LessThan100::
	.string "Sono impressionato!\n"
	.string "Dev'essere stato difficile!$"

PokedexRating_Text_LessThan110::
	.string "Hai raggiunto 100 specie!\n"
	.string "Non credo a quanto sei bravo!$"

PokedexRating_Text_LessThan120::
	.string "Hai anche le forme evolute\n"
	.string "dei POKéMON! Fantastico!$"

PokedexRating_Text_LessThan130::
	.string "Eccellente! Scambia con gli amici\n"
	.string "per averne altri!$"

PokedexRating_Text_LessThan140::
	.string "Eccezionale!\n"
	.string "Sei diventato un vero esperto!$"

PokedexRating_Text_LessThan150::
	.string "Non ho più nulla da dire!\n"
	.string "Ora sei tu il PROFESSOR POKéMON!$"

PokedexRating_Text_Complete::
	.string "Il tuo POKéDEX è completo!\n"
	.string "Congratulazioni!!$"

PokedexRating_Text_NationalDexSeenXOwnedY::
	.string "E il tuo POKéDEX NAZIONALE è:\p"
	.string "{STR_VAR_1} POKéMON visti e\n"
	.string "{STR_VAR_2} POKéMON catturati.$"

PokedexRating_Text_LookForwardToFilledNationalDex::
	.string "Non vedo l'ora di vederti\n"
	.string "completare il POKéDEX NAZIONALE!$"

PokedexRating_Text_YouveCompletedDex::
	.string "Finalmente…\p"
	.string "Hai completato il\n"
	.string "POKéDEX!\p"
	.string "È magnifico!\n"
	.string "Davvero un'impresa fantastica!$"

PokedexRating_Text_Wroooaaarrr::
	.string "Wroooooooaaaaaarrrr!$"

PokedexRating_Text_ThankYouMadeDreamReality::
	.string "Grazie, {PLAYER}!\n"
	.string "Davvero, grazie!\l"
	.string "Hai realizzato il mio sogno!$"

PokedexRating_Text_LoveSeeingYourPokedex::
	.string "OAK: Ah, benvenuto!\p"
	.string "Dimmi, come va il tuo POKéDEX\n"
	.string "di recente?\p"
	.string "Wahaha!\p"
	.string "Lo so già, ma mi piace\n"
	.string "vederlo lo stesso!\p"
	.string "Vediamo…$"

@ HnS (mostly directly copied from HGSS)

gElmDexRatingText_GoFindMrPokemon::
	.string "PROF. ELM: Ah, {PLAYER}{KUN}!\p"
	.string "Hai già trovato la casa di\n"
	.string "MR. POKéMON? È al PERCORSO 30,\p"
	.string "non puoi sbagliare!$"

gElmDexRatingText_Robbery::
	.string "PROF. ELM: {PLAYER}{KUN}!\p"
	.string "Vieni qui subito! È successo\n"
	.string "qualcosa di terribile!$"

gElmDexRatingText_AreYouCurious::
	.string "PROF. ELM: Ah, {PLAYER}{KUN}!\p"
	.string "Vuoi sapere come va\n"
	.string "il tuo POKéDEX?$"

gElmDexRatingText_AreYouCuriousNational::
	.string "PROF. ELM: Ah, {PLAYER}{KUN}!\p"
	.string "Vuoi sapere come va il tuo\n"
	.string "POKéDEX Nazionale?$"

gJohtoDexRatingText_LessThan10::
	.string "Cerca POKéMON nell'erba alta!$"

gJohtoDexRatingText_LessThan20::
	.string "Bene. Vedo che sai usare\n"
	.string "le Poké Ball.$"

gJohtoDexRatingText_LessThan35::
	.string "Stai migliorando,\n"
	.string "ma la strada è ancora lunga.$"

gJohtoDexRatingText_LessThan50::
	.string "Hmm, stai catturando POKéMON\n"
	.string "a buon ritmo!$"

gJohtoDexRatingText_LessThan65::
	.string "Ci stai provando, si vede.\n"
	.string "Il tuo POKéDEX prende forma.$"

gJohtoDexRatingText_LessThan80::
	.string "Li stai allenando bene. Lo sai\n"
	.string "che alcuni POKéMON non evolvono\p"
	.string "solo lottando, vero?$"

gJohtoDexRatingText_LessThan95::
	.string "Hai una Canna da Pesca?\n"
	.string "Alcuni POKéMON si trovano\p"
	.string "solo pescando!$"

gJohtoDexRatingText_LessThan110::
	.string "Eccellente! Sembri bravo a\n"
	.string "collezionare cose!$"

gJohtoDexRatingText_LessThan125::
	.string "Alcuni POKéMON appaiono solo in\n"
	.string "certi momenti della giornata.$"

gJohtoDexRatingText_LessThan140::
	.string "Il tuo POKéDEX si sta riempiendo.\n"
	.string "Continua così!$"

gJohtoDexRatingText_LessThan155::
	.string "Sono impressionato.\n"
	.string "Fai evolvere i POKéMON, non li\p"
	.string "catturi e basta.$"

gJohtoDexRatingText_LessThan170::
	.string "Se impari a usare bene le\n"
	.string "Poké Ball artigianali di Kurt,\p"
	.string "potrai catturare i POKéMON\n"
	.string "più facilmente!$"

gJohtoDexRatingText_LessThan185::
	.string "Quando scambi POKéMON, scambi\n"
	.string "anche informazioni. Gli amici\p"
	.string "possono aiutarti davvero!$"

gJohtoDexRatingText_LessThan200::
	.string "Scambi i tuoi POKéMON?\n"
	.string "Da soli è dura!$"

gJohtoDexRatingText_LessThan215::
	.string "Wow! Hai raggiunto 200!\n"
	.string "Il tuo POKéDEX è fantastico!$"

@ Taken from Platinum
gJohtoDexRatingText_LessThan230::
	.string "Hai dimostrato di essere capace.\n"
    .string "Non c'è nulla da temere.\p"
    .string "Continua a catturare POKéMON\n"
    .string "come hai fatto finora.$"

@ Taken from Platinum
gJohtoDexRatingText_LessThan245::
	.string "Il tuo POKéDEX è quasi\n"
	.string "completo.\p"
	.string "Questo POKéDEX è come un\n"
	.string "diario della tua avventura.$"

gJohtoDexRatingText_LessThan260::
	.string "Hai trovato tantissimi POKéMON!\n"
	.string "Hai aiutato molto i miei studi!$"

gJohtoDexRatingText_LessThan275::
	.string "Magnifico! Potresti diventare\n"
	.string "un grande PROFESSOR\p"
	.string "POKéMON un giorno!$"

gJohtoDexRatingText_LessThanMaxDex::
	.string "Il tuo POKéDEX è incredibile!\n"
	.string "Puoi diventare un professionista!$"

gJohtoDexRatingText_Complete::
	.string "Wow!\n"
	.string "È un POKéDEX di Johto completo!\p"  
	.string "Grazie a te, {PLAYER}, il POKéDEX\n"
	.string "di Johto è completo!\p"
	.string "Wow…\n"
	.string "Hai fatto un lavoro incredibile!$"

gNationalDexRatingText_LessThan100::
	.string "L'obiettivo è lontano, ma non\n"
	.string "arrenderti! Continua così!$"

gNationalDexRatingText_LessThan150::
	.string "Non dimenticare: alcuni POKéMON\n"
	.string "appaiono solo in certi momenti!$"

gNationalDexRatingText_LessThan200::
	.string "Se spacchi le rocce, alcuni\n"
	.string "POKéMON nascosti potrebbero\p"
	.string "saltare fuori!$"

gNationalDexRatingText_LessThan250::
	.string "Che bello che tu sia riuscito\n"
	.string "a raccogliere tanti POKéMON!\p"
	.string "La strada è lunga. Continua\n"
	.string "così!$"

gNationalDexRatingText_LessThan300::
	.string "Se usi Bottintesta su un albero,\n"
	.string "a volte un POKéMON cade giù!$"

gNationalDexRatingText_LessThan350::
	.string "Molti POKéMON che non vivono a\n"
	.string "Johto si radunano\p"
	.string "alla Zona Safari$"

gNationalDexRatingText_LessThan400::
@	.string "Music on the radio might also\n"
@	.string "entice POKéMON to leap out$"
	.string "Ci sono luoghi nascosti in\n"
	.string "tutto il mondo con POKéMON\p"
	.string "rari e insoliti, prova a\n"
	.string "trovarli tutti!$"

gNationalDexRatingText_LessThan435::
	.string "Wow, sei arrivato lontano…!\n"
	.string "Sono quasi sorpreso!$"

gNationalDexRatingText_LessThan465::
	.string "È un momento decisivo!\n"
	.string "Non puoi scoraggiarti!$"

gNationalDexRatingText_LessThan475::
	.string "Ancora un pochino!\n"
	.string "Ho grandi aspettative su di te!$"

gNationalDexRatingText_LessThanMaxDex::
	.string "In tutti i miei anni non ho mai\n"
	.string "visto un Allenatore così incredibile!$"

gNationalDexRatingText_Complete::
	.string "Eccellente! È un fantastico\n"
	.string "POKéDEX Nazionale!\p"
	.string "Wow…{PAUSE 10}\p"
	.string "Hai soddisfatto le mie\n"
	.string "aspettative alla grande!\p"
	.string "No, le hai superate, {PLAYER}.\n"
	.string "Sei diventato un Allenatore incredibile!\p"
	.string "Grazie, {PLAYER}!$"
