Questionnaire_Text_FillOut::
	.string "C'è un questionario.\n"
	.string "Vuoi compilarlo?$"

Questionnaire_Text_ThankYou::
	.string "Grazie per aver dedicato del tempo\n"
	.string "a compilare il nostro questionario.\p"
	.string "Le tue risposte serviranno\n"
	.string "in futuro.$"

Questionnaire_Text_YouKnowThoseWordsGift::
	.string "Oh, ciao!\n"
	.string "Conosci quelle parole?\p"
	.string "Allora devi sapere del\n"
	.string "DONO SEGRETO.\p"
	.string "D'ora in poi riceverai\n"
	.string "dei DONI SEGRETI!$"

Questionnaire_Text_YouCanAccessMysteryGift::
	.string "Una volta salvato il gioco, potrai\n"
	.string "accedere al DONO SEGRETO.$"

Questionnaire_Text_YouKnowThoseWordsEvent::
	.string "Oh, ciao!\n"
	.string "Conosci quelle parole?\p"
	.string "Allora devi sapere del\n"
	.string "DONO SEGRETO.$"

Questionnaire_Text_YouCanAccessMysteryEvent::
	.string "Una volta salvato il gioco, potrai\n"
	.string "accedere al DONO SEGRETO.$"

MysteryGift_Text_TheresATicketForYou::
	.string "Grazie per usare il sistema\n"
	.string "DONO SEGRETO.\p"
	.string "Tu devi essere {PLAYER}.\n"
	.string "C'è un biglietto per te.$"

MysteryGift_Text_TryUsingItAtLilycovePort::
	.string "Sembra che vada usato al\n"
	.string "porto di PORTOALGHE.\p"
	.string "Perché non provi a vedere\n"
	.string "di cosa si tratta?$"
