	.align 2
gText_ConfirmSave::
	.string "Vuoi salvare il gioco?$"

gText_AlreadySavedFile::
	.string "C'è già un file salvato.\n"
	.string "Va bene sovrascriverlo?$"

gText_SavingDontTurnOff::
	.string "SALVATAGGIO…\n"
	.string "NON SPEGNERE LA CONSOLE.$"

gText_PlayerSavedGame::
	.string "{PLAYER} ha salvato il gioco.$"

gText_DifferentSaveFile::
	.string "ATTENZIONE!\p"
	.string "C'è un file di gioco diverso\n"
	.string "già salvato.\p"
	.string "Se salvi ora, l'avventura dell'altro\n"
	.string "file, compresi oggetti e\l"
	.string "POKéMON, andrà persa del tutto.\p"
	.string "Vuoi davvero salvare ora\n"
	.string "e sovrascrivere l'altro file?$"

gText_SaveError::
	.string "Errore di salvataggio.\p"
	.string "Cambia la\n"
	.string "memoria di backup.$"

gText_SavingDontTurnOffPower::
	.string "SALVATAGGIO…\n"
	.string "NON SPEGNERE LA CONSOLE.$"
