SecretBase_Text_Trainer0Intro:
	.string "Hai già creato una BASE SEGRETA?\p"
	.string "Ho girato qua e là ovunque prima\n"
	.string "di scegliere questo posto.\p"
	.string "Visto che sei qui, ti va di\n"
	.string "fare una lotta?$"

SecretBase_Text_Trainer0AcceptBattle:
	.string "Okay!\n"
	.string "Arriviamo!$"

SecretBase_Text_Trainer0DeclineBattle:
	.string "Come?\n"
	.string "Ah, ora non puoi…$"

SecretBase_Text_Trainer0Defeated::
	.string "Waaargh! Sei troppo forte!\n"
	.string "Che ho perso… Non dirlo in giro!$"

SecretBase_Text_Trainer0PostBattle:
	.string "Che ne pensi della mia BASE SEGRETA?\n"
	.string "Torna a trovarmi domani.$"

SecretBase_Text_Trainer0PreChampion:
	.string "Hai già creato una BASE SEGRETA?\p"
	.string "Ho girato qua e là ovunque prima\n"
	.string "di scegliere questo posto.\p"
	.string "Fai pure come se fossi a casa!$"

SecretBase_Text_Trainer5Intro:
	.string "Ci sono tanti posti dove\n"
	.string "puoi creare una BASE SEGRETA.\p"
	.string "Ma questo mi piace più di tutti.\n"
	.string "Non trovi sia bello?\p"
	.string "Oh, ti va di lottare?$"

SecretBase_Text_Trainer5AcceptBattle:
	.string "Ok, si comincia!$"

SecretBase_Text_Trainer5DeclineBattle:
	.string "Oh…\n"
	.string "Ora non puoi, va bene.$"

SecretBase_Text_Trainer5Defeated::
	.string "Mmm… Abbiamo perso…\n"
	.string "Ma non dirlo a nessuno!\l"
	.string "È un segreto confidenziale!$"

SecretBase_Text_Trainer5PostBattle:
	.string "Se ripassi da queste parti,\n"
	.string "spero che verrai a trovarmi.$"

SecretBase_Text_Trainer5PreChampion:
	.string "Ci sono tanti posti dove puoi\n"
	.string "creare una BASE SEGRETA.\p"
	.string "Ma questo mi piace più di tutti.\n"
	.string "Non trovi sia bello?$"

SecretBase_Text_Trainer1Intro:
	.string "This is a popular spot.\n"
	.string "It's always taken.\p"
	.string "Oh! Were you thinking about\n"
	.string "taking this spot, too?\p"
	.string "I'll tell you what, you can have this\n"
	.string "spot if you can beat me.$"

SecretBase_Text_Trainer1AcceptBattle:
	.string "Okay!\n"
	.string "Difenderò la mia BASE SEGRETA!$"

SecretBase_Text_Trainer1DeclineBattle:
	.string "Come? Davvero?\n"
	.string "Questo posto non ti interessa?$"

SecretBase_Text_Trainer1Defeated::
	.string "Non ce la faccio più!\n"
	.string "Mi arrendo!$"

SecretBase_Text_Trainer1PostBattle:
	.string "Okay, il giorno che me ne andrò,\n"
	.string "questo posto sarà tuo!$"

SecretBase_Text_Trainer1PreChampion:
	.string "Questo posto è molto richiesto.\n"
	.string "È sempre occupato.\p"
	.string "Ho aspettato tanto che si liberasse.\n"
	.string "Finalmente posso usarlo!$"

SecretBase_Text_Trainer6Intro:
	.string "Benvenuto nel mio LABORATORIO POKéMON.\p"
	.string "Faccio ricerche sulle lotte in\n"
	.string "segreto.\p"
	.string "Vuoi vedere quanto sono forte?$"

SecretBase_Text_Trainer6AcceptBattle:
	.string "Darò il massimo!$"

SecretBase_Text_Trainer6DeclineBattle:
	.string "Oh.\n"
	.string "Un'altra volta, allora!$"

SecretBase_Text_Trainer6Defeated::
	.string "Mmm… Ho ancora molto da imparare.\n"
	.string "Devo studiare di più.$"

SecretBase_Text_Trainer6PostBattle:
	.string "Grazie per aver lottato con me.\n"
	.string "Torna a trovarmi domani.$"

SecretBase_Text_Trainer6PreChampion:
	.string "Benvenuto nel mio LABORATORIO POKéMON.\p"
	.string "Faccio ricerche sulle lotte in\n"
	.string "segreto.$"

SecretBase_Text_Trainer2Intro:
	.string "Una grande villa è bella, ma io preferisco\n"
	.string "un posto così.\p"
	.string "Mi piace perché viene a trovarmi\n"
	.string "gente di ogni tipo.\p"
	.string "Allora, ti va di lottare?$"

SecretBase_Text_Trainer2AcceptBattle:
	.string "Così si fa!$"

SecretBase_Text_Trainer2DeclineBattle:
	.string "Quando sei pronto, chiamami!$"

SecretBase_Text_Trainer2Defeated::
	.string "Ahia! Sono andato giù!\n"
	.string "Ma lottare è sempre divertente!$"

SecretBase_Text_Trainer2PostBattle:
	.string "Comunque, devo andare a comprare\n"
	.string "decorazioni e mobili.\p"
	.string "Voglio che la mia BASE SEGRETA sia un\n"
	.string "posto che gli altri possano godersi.$"

SecretBase_Text_Trainer2PreChampion:
	.string "Una grande villa è bella, ma io preferisco\n"
	.string "un posto così.\p"
	.string "Mi piace perché viene a trovarmi\n"
	.string "gente di ogni tipo.$"

SecretBase_Text_Trainer7Intro:
	.string "Adoro comprare decorazioni\n"
	.string "e mobili.\p"
	.string "E amo anche allevare POKéMON\n"
	.string "altrettanto.\p"
	.string "Se non ti dispiace, vuoi lottare\n"
	.string "con i miei POKéMON?$"

SecretBase_Text_Trainer7AcceptBattle:
	.string "Grazie.\n"
	.string "Cominciamo?$"

SecretBase_Text_Trainer7DeclineBattle:
	.string "Oh.\n"
	.string "Che peccato…$"

SecretBase_Text_Trainer7Defeated::
	.string "Mi arrendo…$"

SecretBase_Text_Trainer7PostBattle:
	.string "È stato un bello svago!\n"
	.string "Ora vado a godermi lo shopping.$"

SecretBase_Text_Trainer7PreChampion:
	.string "Adoro comprare decorazioni\n"
	.string "e mobili.\p"
	.string "E amo anche allevare POKéMON\n"
	.string "altrettanto.$"

SecretBase_Text_Trainer3Intro:
	.string "C'è chi costruisce la BASE SEGRETA in\n"
	.string "posti difficili da trovare.\l"
	.string "Vogliono solo nascondersi?\p"
	.string "Ma visto che mi hai trovato, che ne dici\n"
	.string "di lottare?$"

SecretBase_Text_Trainer3AcceptBattle:
	.string "Non mi arrendo facilmente!$"

SecretBase_Text_Trainer3DeclineBattle:
	.string "Oh… Forse sei stanco di cercare\n"
	.string "questo posto?$"

SecretBase_Text_Trainer3Defeated::
	.string "Sono andato giù…$"

SecretBase_Text_Trainer3PostBattle:
	.string "Dov'è la tua BASE SEGRETA?\n"
	.string "Dovrei venire a trovarti.$"

SecretBase_Text_Trainer3PreChampion:
	.string "C'è chi costruisce la BASE SEGRETA in\n"
	.string "posti difficili da trovare.\l"
	.string "Vogliono solo nascondersi?$"

SecretBase_Text_Trainer8Intro:
	.string "Mi han detto che si possono ottenere\n"
	.string "decorazioni in vari modi.\p"
	.string "Facciamo una gara a chi trova\n"
	.string "decorazioni e mobili più belli!\p"
	.string "Intanto, ti va di lottare?$"

SecretBase_Text_Trainer8AcceptBattle:
	.string "Questa è la mia BASE SEGRETA.\n"
	.string "Non posso perdere!$"

SecretBase_Text_Trainer8DeclineBattle:
	.string "Lotto con te quando vuoi.$"

SecretBase_Text_Trainer8Defeated::
	.string "Eh?\n"
	.string "Ho appena perso?$"

SecretBase_Text_Trainer8PostBattle:
	.string "Non perderò a collezionare decorazioni.\n"
	.string "Torna a trovarmi!$"

SecretBase_Text_Trainer8PreChampion:
	.string "Mi han detto che si possono ottenere\n"
	.string "decorazioni in vari modi.\p"
	.string "Facciamo una gara a chi trova\n"
	.string "decorazioni e mobili più belli!$"

SecretBase_Text_Trainer4Intro:
	.string "Ho trovato un posto che mi piaceva e l'ho\n"
	.string "riempito con le mie decorazioni preferite.\p"
	.string "Allenò i POKéMON che amo e cresco\n"
	.string "forte insieme a loro.\p"
	.string "Ecco cosa faccio.\n"
	.string "Ti va di lottare con me?$"

SecretBase_Text_Trainer4AcceptBattle:
	.string "Fammi vedere di che pasta sei!$"

SecretBase_Text_Trainer4DeclineBattle:
	.string "Beh, ci sono momenti in cui non hai\n"
	.string "voglia.$"

SecretBase_Text_Trainer4Defeated::
	.string "Ora so di che pasta sei fatto.$"

SecretBase_Text_Trainer4PostBattle:
	.string "Possiamo diventare più forti entrambi.\n"
	.string "Continuiamo così!$"

SecretBase_Text_Trainer4PreChampion:
	.string "Ho trovato un posto che mi piaceva e l'ho\n"
	.string "riempito di decorazioni preferite.\p"
	.string "Allenavo i POKéMON che amo e divento\n"
	.string "più forte con loro.\p"
	.string "Ogni giorno è fantastico.$"

SecretBase_Text_Trainer9Intro:
	.string "Si capisce molto del gusto\n"
	.string "e del senso delle persone da\l"
	.string "come sono arredate e da come\l"
	.string "lo mostrano.\p"
	.string "Cosa pensi del mio gusto?\n"
	.string "Sei senza parole?\p"
	.string "Vuoi vedere il mio stile in lotta?$"

SecretBase_Text_Trainer9AcceptBattle:
	.string "Non mi trattengo di certo!$"

SecretBase_Text_Trainer9DeclineBattle:
	.string "Ti mostrerò il mio stile\n"
	.string "quando vuoi.$"

SecretBase_Text_Trainer9Defeated::
	.string "Hai un talento supremo!\n"
	.string "La tua forza sembra illimitata…$"

SecretBase_Text_Trainer9PostBattle:
	.string "Cosa pensi del mio stile?\n"
	.string "Continuerò a perfezionarlo!$"

SecretBase_Text_Trainer9PreChampion:
	.string "Si capisce molto del gusto\n"
	.string "e del senso delle persone da\l"
	.string "come sono arredate e da come\l"
	.string "lo mostrano.\p"
	.string "Cosa pensi del mio gusto?\n"
	.string "Sei senza parole?$"
