CeladonCity_GameCorner_Text_TryPokemonPrinter::
	.string "È una STAMPANTE POKéMON!\p"
	.string "Può stampare i tuoi POKéMON\n"
	.string "sul retro della SCHEDA ALLENATORE.\p"
	.string "Costa solo ¥50.\n"
	.string "Vuoi provarla?$"

CeladonCity_GameCorner_Text_DontHaveEnoughMoney::
	.string "Non hai abbastanza soldi.$"

CeladonCity_GameCorner_Text_ChoosePrintType::
	.string "Scegli il tipo di stampa.$"

CeladonCity_GameCorner_Text_BigSmileForPhoto::
	.string "Un bel sorriso per la foto!\n"
	.string "Tre… Due… Uno…\p"
	.string "Flash!$"

CeladonCity_GameCorner_Text_PrintIsReadyCheckTrainerCard::
	.string "La stampa dei tuoi POKéMON è pronta!\n"
	.string "Controlla il tuo SCHEDA ALLENATORE.$"

FourIsland_House2_Text_WishICouldShowOffStickers::
	.string "Eheh…\n"
	.string "Ho collezionato un sacco di ADESIVI.\l"
	.string "Vorrei poterli mostrare…$"

FourIsland_House2_Text_GiveYouStickerIfYouBrag::
	.string "Oh, eccellente!\n"
	.string "Sei nel posto giusto!\p"
	.string "Guarda, guarda! Vedi? Vedi?\n"
	.string "Questi sono i miei ADESIVI!\l"
	.string "Guarda quanti ne ho!\p"
	.string "Scommetto che ne vuoi qualcuno.\n"
	.string "Lo scommetto!\p"
	.string "Ti do un ADESIVO se sai dirmi\n"
	.string "qualcosa di fantastico\l"
	.string "su di te.\p"
	.string "Di cosa ti vanterai?$"

FourIsland_House2_Text_BragAboutSomethingForMe::
	.string "Vantati di qualcosa per me.\n"
	.string "Ti darò un ADESIVO.$"

FourIsland_House2_Text_BragAboutWhatToday::
	.string "Oh, ciao!\n"
	.string "Ecco il fanfarone.\p"
	.string "Di cosa ti vanterai\n"
	.string "oggi?$"

FourIsland_House2_Text_WowHoFLowest::
	.string "Oh, uau, sei entrato nella\n"
	.string "HALL OF FAME.\p"
	.string "Mica male, davvero!\n"
	.string "Ti do uno di questi.$"

FourIsland_House2_Text_WowHoFLow::
	.string "Oh, uau, sei entrato nella\n"
	.string "HALL OF FAME spesso!\p"
	.string "Notevole, davvero!\n"
	.string "Ti do uno di questi.$"

FourIsland_House2_Text_WowHoFHigh::
	.string "Uau! Sei entrato nella\n"
	.string "HALL OF FAME così spesso?\l"
	.string "È davvero incredibile!\p"
	.string "Sei il padrone della LEGA POKéMON!\n"
	.string "Ti do uno di questi.$"

FourIsland_House2_Text_WowHoFHighest::
	.string "Non ci credo! Sei entrato nella\n"
	.string "HALL OF FAME tutte quelle volte?\p"
	.string "Sei incredibile, davvero!\n"
	.string "E basta, devo darti questo.$"

FourIsland_House2_Text_HoFStickerApplied::
	.string "L'ADESIVO HALL OF FAME è stato\n"
	.string "applicato alla SCHEDA ALLENATORE.$"

FourIsland_House2_Text_ComeBackWithBetterStoryHoF::
	.string "Hmm…\p"
	.string "Torna con una storia migliore la\n"
	.string "prossima volta, ok?$"

FourIsland_House2_Text_LivingLegendHoF::
	.string "Oh, no, non se ne parla.\p"
	.string "Sei praticamente una leggenda vivente.\n"
	.string "Non ho più ADESIVI da dare.$"

FourIsland_House2_Text_WowEggsLowest::
	.string "Oh, uau, esistono le UOVA POKéMON?\n"
	.string "Non lo sapevo!\p"
	.string "Mica male, davvero!\n"
	.string "Ti do uno di questi.$"

FourIsland_House2_Text_WowEggsLow::
	.string "Hai schiuso tutte quelle UOVA?\n"
	.string "Ti piacciono davvero!\p"
	.string "Notevole, davvero!\n"
	.string "Ti do uno di questi.$"

FourIsland_House2_Text_WowEggsHigh::
	.string "Uau! Hai schiuso un bel po'\n"
	.string "di UOVA!\p"
	.string "Sei una macchina da UOVA!\n"
	.string "Ti do uno di questi.$"

FourIsland_House2_Text_WowEggsHighest::
	.string "Cosa… Hai schiuso così tante UOVA?\p"
	.string "Cosa c'è dietro il tuo amore per le UOVA?\n"
	.string "È incredibile, davvero!\p"
	.string "Sei troppo forte, sai.\n"
	.string "E basta, devo darti questo.$"

FourIsland_House2_Text_EggStickerApplied::
	.string "L'ADESIVO UOVO è stato applicato\n"
	.string "alla SCHEDA ALLENATORE.$"

FourIsland_House2_Text_ComeBackWithBetterStoryEggs::
	.string "Hmm…\p"
	.string "Torna con una storia migliore la\n"
	.string "prossima volta, ok?$"

FourIsland_House2_Text_LivingLegendEggs::
	.string "Oh, no, non se ne parla.\p"
	.string "Sei praticamente una leggenda vivente.\n"
	.string "Non ho più ADESIVI da dare.$"

FourIsland_House2_Text_WowLinkWinsLowest::
	.string "Oh, hai avuto successo\n"
	.string "in link, eh?\p"
	.string "Sei abbastanza forte, sì!\n"
	.string "Ti do uno di questi.$"

FourIsland_House2_Text_WowLinkWinsLow::
	.string "Hai battuto gli amici tante\n"
	.string "volte in link, eh?\p"
	.string "Sei forte, davvero!\n"
	.string "Ti do uno di questi.$"

FourIsland_House2_Text_WowLinkWinsHigh::
	.string "Uau! Hai battuto i tuoi amici\n"
	.string "un numero spaventoso di volte.\p"
	.string "Hai perso amici per questo?\n"
	.string "Ti do uno di questi.$"

FourIsland_House2_Text_WowLinkWinsHighest::
	.string "Cavoli… ma dai!\n"
	.string "Hai vinto che è un piacere!\p"
	.string "Mi fa impazzire pensare\n"
	.string "a quanto sei forte.\p"
	.string "Sei un incubo vivente!\n"
	.string "Ci siamo, devo darti questo.$"

FourIsland_House2_Text_VictoryStickerApplied::
	.string "L'ADESIVO VITTORIA è stato applicato\n"
	.string "alla SCHEDA ALLENATORE.$"

FourIsland_House2_Text_ComeBackWithBetterStoryLinkWins::
	.string "Hmm…\p"
	.string "Torna con una storia migliore la\n"
	.string "prossima volta, ok?$"

FourIsland_House2_Text_LivingLegendLinkWins::
	.string "Oh, no, non se ne parla.\p"
	.string "Sei praticamente una leggenda vivente.\n"
	.string "Non ho più ADESIVI da dare.$"
