Route102_Text_CalvinIntro:
	.string "Se hai dei POKéMON con te, allora\n"
	.string "sei un ALLENATORE ufficiale!\l"
	.string "Non puoi rifiutare la mia sfida!$"

Route102_Text_CalvinDefeated:
	.string "Argh, ho perso…\n"
	.string "Dovevo allenare di più i miei…$"

Route102_Text_CalvinPostBattle:
	.string "Senti, se sei forte,\n"
	.string "dovevi dirmelo prima!$"

Route102_Text_CalvinRegister:
	.string "Mi sono allenato sodo da quando\n"
	.string "ti ho visto.\p"
	.string "Voglio risfidarti, mi registri\n"
	.string "nel POKéNAV?$"

Route102_Text_CalvinRegisterShort:
	.string "Voglio risfidarti, mi registri\n"
	.string "nel POKéNAV?$"

Route102_Text_CalvinRematchIntro:
	.string "Da quando ho perso, ho allenato\n"
	.string "i POKéMON senza sosta.\l"
	.string "Non puoi rifiutare la mia sfida!$"

Route102_Text_CalvinRematchDefeated:
	.string "Argh, ho perso…\n"
	.string "Il mio metodo non va bene?$"

Route102_Text_CalvinRematchPostBattle:
	.string "Se diventerai più forte,\n"
	.string "diventerò più forte anch'io.$"

Route102_Text_AllenIntro:
	.string "Sei appena diventato un ALLENATORE?\n"
	.string "Siamo entrambi principianti!$"

Route102_Text_AllenDefeated:
	.string "Ti ho sfidato perché pensavo\n"
	.string "di poterti battere…$"

Route102_Text_AllenPostBattle:
	.string "Non ho ancora vinto una volta…\n"
	.string "Vorrei vincere presto…$"

Route102_Text_RickIntro:
	.string "Ahah! Ci siamo guardati!\n"
	.string "Ti sfido con i miei POKéMON COLEOTTERO!$"

Route102_Text_RickDefeated:
	.string "Ahia! K.O.!$"

Route102_Text_RickPostBattle:
	.string "Se incroci lo sguardo di un ALLENATORE,\n"
	.string "devi sfidarlo! È la regola!$"

Route102_Text_TianaIntro:
	.string "Continuerò a vincere per\n"
	.string "diventare la migliore ALLENATRICE.\p"
	.string "Aiutami a fare carriera!$"

Route102_Text_TianaDefeated:
	.string "Ti ho fatto fare carriera…$"

Route102_Text_TianaPostBattle:
	.string "Per continuare a vincere, capisco che\n"
	.string "devo catturare più POKéMON.$"

Route103_Text_DaisyIntro:
	.string "Hai sentito il richiamo della nostra\n"
	.string "fragranza che calma l'anima?$"

Route103_Text_DaisyDefeated:
	.string "Il nostro aroma non ti ha fatto smarrire…$"

Route103_Text_DaisyPostBattle:
	.string "L'Aromaterapia è una cura mentale\n"
	.string "che agisce con le fragranze.$"

Route103_Text_AmyIntro:
	.string "AMY: Sono AMY.\n"
	.string "E lei è mia sorella LIV.\l"
	.string "Lottiamo insieme!$"

Route103_Text_AmyDefeated:
	.string "AMY: Oh no, abbiamo perso.$"

Route103_Text_AmyPostBattle:
	.string "AMY: Devi pensare a tante cose\n"
	.string "quando lotti\l"
	.string "contro due ALLENATORI.$"

Route103_Text_AmyNotEnoughPokemon:
	.string "AMY: Oh no, hai un solo\n"
	.string "POKéMON con te.\l"
	.string "Così non puoi sfidarci.$"

Route103_Text_LivIntro:
	.string "LIV: Lottiamo insieme come una\n"
	.string "squadra.$"

Route103_Text_LivDefeated:
	.string "LIV: Oh, abbiamo perso, sorellona…$"

Route103_Text_LivPostBattle:
	.string "LIV: Formiamo una coppia perfetta,\n"
	.string "io e mia sorella…\p"
	.string "Ma abbiamo perso lo stesso…$"

Route103_Text_AmyLivRegister:
	.string "LIV: Siamo molto più forti…\n"
	.string "Davvero! Te lo mostreremo!$"

Route103_Text_LivNotEnoughPokemon:
	.string "LIV: Se vuoi sfidarci,\n"
	.string "devi avere due POKéMON!\l"
	.string "Così non è leale!$"

Route103_Text_AmyRematchIntro:
	.string "AMY: Sono AMY.\n"
	.string "E lei è mia sorella LIV.\l"
	.string "Lottiamo insieme!$"

Route103_Text_AmyRematchDefeated:
	.string "AMY: Oh, che peccato!\n"
	.string "Non abbiamo vinto di nuovo…$"

Route103_Text_AmyRematchPostBattle:
	.string "AMY: Devi pensare a tante cose\n"
	.string "quando lotti\l"
	.string "contro due ALLENATORI.$"

Route103_Text_AmyRematchNotEnoughPokemon:
	.string "AMY: Oh no, hai un solo\n"
	.string "POKéMON con te.\l"
	.string "Così non puoi sfidarci.$"

Route103_Text_LivRematchIntro:
	.string "LIV: Lottiamo insieme come una\n"
	.string "squadra.$"

Route103_Text_LivRematchDefeated:
	.string "LIV: Ohhh, abbiamo perso di nuovo…\n"
	.string "Sorellona…$"

Route103_Text_LivRematchPostBattle:
	.string "LIV: Formiamo una bella coppia,\n"
	.string "io e mia sorella maggiore…\p"
	.string "Ma perché abbiamo perso di nuovo?$"

Route103_Text_LivRematchNotEnoughPokemon:
	.string "LIV: Per lottare contro di noi\n"
	.string "ti servono due POKéMON!\l"
	.string "Altrimenti non è giusto!$"

Route103_Text_AndrewIntro:
	.string "Ah! La lenza è tutta ingarbugliata!\n"
	.string "Sono nervoso e cattivo!\l"
	.string "Basta! Lotta con me!$"

Route103_Text_AndrewDefeated:
	.string "Ah! Ho perso!\n"
	.string "Ora sono ancora più irritato!$"

Route103_Text_AndrewPostBattle:
	.string "Ah, sono ancora furioso…\n"
	.string "Grrrrr…$"

Route103_Text_MiguelIntro:
	.string "Il mio POKéMON è adorabile!\n"
	.string "Non essere timido, te lo mostro!$"

Route103_Text_MiguelDefeated:
	.string "Oh, santo cielo!\n"
	.string "Il mio adorato POKéMON!$"

Route103_Text_MiguelPostBattle:
	.string "Il mio delizioso POKéMON è adorabile\n"
	.string "anche quando è esausto!$"

Route103_Text_MiguelRegister:
	.string "Ti farò uscire di nuovo per ammirare\n"
	.string "il mio delizioso POKéMON!$"

Route103_Text_MiguelRematchIntro:
	.string "Ciao! Il mio deliziosamente adorabile\n"
	.string "POKéMON è ancora più carino!$"

Route103_Text_MiguelRematchDefeated:
	.string "Oh!\n"
	.string "Il mio adorato POKéMON!$"

Route103_Text_MiguelRematchPostBattle:
	.string "Più tempo passo con lui,\n"
	.string "più il mio POKéMON diventa adorabile.$"

Route103_Text_PeteIntro:
	.string "Con questa distanza…\n"
	.string "dovresti fartela a nuoto!$"

Route103_Text_PeteDefeated:
	.string "Oh, niente male!$"

Route103_Text_PetePostBattle:
	.string "Oh, ora capisco il tuo\n"
	.string "punto di vista.\p"
	.string "Se avessi un POKéMON così fidato,\n"
	.string "vorrei usare SURF anch'io!$"

Route103_Text_IsabelleIntro:
	.string "Guarda dove vai!\n"
	.string "Ci scontreremo!$"

Route103_Text_IsabelleDefeated:
	.string "Uff…$"

Route103_Text_IsabellePostBattle:
	.string "Nuoto male, mi stavo allenando…\n"
	.string "Scusa se ti ho quasi colpito.$"

Route103_Text_RhettIntro:
	.string "Whoa!\n"
	.string "How'd you get into a space this small?$"

Route103_Text_RhettDefeated:
	.string "Uau!\n"
	.string "Il ragazzino spacca!$"

Route103_Text_RhettPostBattle:
	.string "Ti piacciono gli spazi stretti\n"
	.string "come questo?$"

Route103_Text_MarcosIntro:
	.string "Did my guitar's wailing draw you in?$"

Route103_Text_MarcosDefeated:
	.string "Il mio spettacolo è rovinato…$"

Route103_Text_MarcosPostBattle:
	.string "Suonavo la chitarra dove c'era poca\n"
	.string "gente, ma si è radunata\l"
	.string "una folla.\p"
	.string "Eh, forse dovrei diventare famoso.$"

Route104_Text_GinaIntro:
	.string "GINA: Okay, lottiamo con i nostri\n"
	.string "POKéMON!$"

Route104_Text_GinaDefeat:
	.string "GINA: Perdere mi irrita!$"

Route104_Text_GinaPostBattle:
	.string "GINA: Sei forte!\n"
	.string "Dobbiamo allenarci molto di più!$"

Route104_Text_GinaNotEnoughMons:
	.string "GINA: Oh? Un solo POKéMON?\n"
	.string "Allora non lottiamo con te.\p"
	.string "Con un solo POKéMON si sentirebbe\n"
	.string "solo. Non va bene.$"

Route104_Text_MiaIntro:
	.string "MIA: Siamo gemelle, quindi lottiamo\n"
	.string "coi POKéMON insieme.$"

Route104_Text_MiaDefeat:
	.string "MIA: Abbiamo lottato insieme, ma\n"
	.string "abbiamo perso…$"

Route104_Text_MiaPostBattle:
	.string "MIA: Allenermo di più i POKéMON\n"
	.string "e saremo forti come te.$"

Route104_Text_MiaNotEnoughMons:
	.string "MIA: Vuoi lottare con noi?\p"
	.string "Non se ne parla se non hai due\n"
	.string "POKéMON con te.\l"
	.string "Siamo troppo forti!$"

Route104_Text_IvanIntro:
	.string "Perché tenerlo segreto?\n"
	.string "Sono l'esperto di POKéMON ACQUA!\p"
	.string "Eh?\n"
	.string "Non mi conosci?$"

Route104_Text_IvanDefeat:
	.string "Credevo di non essere male, se posso\n"
	.string "dirlo, ma evidentemente no… Bleah…$"

Route104_Text_IvanPostBattle:
	.string "Ho pescato troppo.\n"
	.string "Mi sono scordato di allenare i POKéMON…$"

Route104_Text_BillyIntro:
	.string "Lasciare impronte sulla sabbia\n"
	.string "è divertentissimo!$"

Route104_Text_BillyDefeat:
	.string "Uah! Ho la sabbia nelle scarpe!\n"
	.string "Sono tutte piene di sabbia!$"

Route104_Text_BillyPostBattle:
	.string "Vorrei lasciare le mie impronte\n"
	.string "sulla sabbia ovunque, ma\l"
	.string "spariscono in fretta…$"

Route104_Text_HaleyIntro:
	.string "Dovrei…\n"
	.string "O non dovrei?\p"
	.string "Okay, sì, lotterò!$"

Route104_Text_HaleyDefeat:
	.string "Non avrei dovuto lottare…$"

Route104_Text_HaleyPostBattle:
	.string "Se hai una decisione da prendere e\n"
	.string "lasci scegliere ad altri,\l"
	.string "te ne pentirai, comunque\l"
	.string "vada a finire.$"

Route104_Text_HaleyRegister1:
	.string "Sei forte, ma dovrei registrarti\n"
	.string "nel mio POKéNAV?\l"
	.string "Forse non dovrei…\p"
	.string "Okay, sì, ti registro!$"

Route104_Text_HaleyRegister2:
	.string "Sei forte, ma dovrei registrarti\n"
	.string "nel mio POKéNAV?\l"
	.string "Forse non dovrei…\p"
	.string "Okay, sì, ti registro!$"

Route104_Text_HaleyRematchIntro:
	.string "Dai, lotta con me!$"

Route104_Text_HaleyRematchDefeat:
	.string "Ohh…\n"
	.string "Credevo di poter vincere…$"

Route104_Text_HaleyPostRematch:
	.string "Ho scelto di lottare, quindi\n"
	.string "accetto la sconfitta con grazia.\p"
	.string "Però perdere mi secca ancora!$"

Route104_Text_WinstonIntro:
	.string "Certo, accetto la tua sfida.\n"
	.string "Ho un sacco di soldi.$"

Route104_Text_WinstonDefeat:
	.string "Perché non ho vinto?$"

Route104_Text_WinstonPostBattle:
	.string "Ci sono cose che i soldi non comprano.\n"
	.string "Cioè i POKéMON…$"

Route104_Text_WinstonRegister1:
	.string "Hm?\n"
	.string "Ah, hai un POKéNAV.\p"
	.string "Ti registro volentieri.\n"
	.string "Dopotutto, ho un sacco di soldi.$"

Route104_Text_WinstonRegister2:
	.string "Hm?\n"
	.string "Ah, hai un POKéNAV.\p"
	.string "Ti registro volentieri.\n"
	.string "Dopotutto, ho un sacco di soldi.$"

Route104_Text_WinstonRematchIntro:
	.string "Dopo che ti ho perso contro, ho imparato\n"
	.string "un sacco di cose sui POKéMON.$"

Route104_Text_WinstonRematchDefeat:
	.string "Ho perso di nuovo?\n"
	.string "Perché non ho vinto?$"

Route104_Text_WinstonPostRematch:
	.string "Sono ricchissimo, ma non riesco\n"
	.string "a vincere coi POKéMON…\p"
	.string "È così profondo, il mondo dei POKéMON…$"

Route104_Text_CindyIntro:
	.string "Eravamo destinati a incontrarci.\n"
	.string "Posso chiederti una lotta?$"

Route104_Text_CindyDefeat:
	.string "Oh, cielo!$"

Route104_Text_CindyPostBattle:
	.string "“Ciao” è l'inizio di “addio”.\n"
	.string "Spero di rivederti.$"

Route104_Text_CindyRegister1:
	.string "Ciao, ci rivediamo.\p"
	.string "Sembra che ci attiriamo. Registriamoci\n"
	.string "nei nostri POKéNAV.$"

Route104_Text_CindyRegister2:
	.string "Dovremmo ricordare come sembriamo\n"
	.string "attratti l'uno dall'altra.\p"
	.string "Registriamoci nei nostri\n"
	.string "POKéNAV.$"

Route104_Text_CindyRematchIntro:
	.string "Ciao, ci rivediamo.\n"
	.string "Posso chiederti una lotta?$"

Route104_Text_CindyRematchDefeat:
	.string "Oh, cielo…\n"
	.string "Ho dato il massimo…$"

Route104_Text_CindyPostRematch:
	.string "“Ciao” è l'inizio di “addio”.\n"
	.string "Spero di rivederti.$"

Route104_Text_DarianIntro:
	.string "Ho pescato un POKéMON dall'aria tosta!\p"
	.string "Ha qualcosa di magico!\n"
	.string "Sembra davvero tosto, altroché!$"

Route104_Text_DarianDefeat:
	.string "Ma che…$"

Route104_Text_DarianPostBattle:
	.string "Ehi, MAGIKARP, non sei all'altezza\n"
	.string "del tuo nome, vero?$"

Route105_Text_FosterIntro:
	.string "Dovrebbe esserci una roccia\n"
	.string "mistica da queste parti.\l"
	.string "Ne sai qualcosa?$"

Route105_Text_FosterDefeated:
	.string "Pensavo troppo a quella\n"
	.string "roccia, e i POKéMON sono rimasti deboli…$"

Route105_Text_FosterPostBattle:
	.string "Posso passare ore e ore a fissare\n"
	.string "una bella roccia senza annoiarmi.$"

Route105_Text_LuisIntro:
	.string "Fiu! Temevo che un bambino stesse\n"
	.string "affogando quando ti ho visto.\p"
	.string "Sembri stare bene, quindi che dici\n"
	.string "di una lotta?$"

Route105_Text_LuisDefeated:
	.string "Glub… Glub…$"

Route105_Text_LuisPostBattle:
	.string "Se stai affogando, il segnale è\n"
	.string "agitare un braccio verso la spiaggia.$"

Route105_Text_DominikIntro:
	.string "Nuotare nel mare blu profondo…\n"
	.string "È la cosa più bella!$"

Route105_Text_DominikDefeated:
	.string "Ho perso…\n"
	.string "Ora sono giù di morale…$"

Route105_Text_DominikPostBattle:
	.string "Perché il mare è blu?\p"
	.string "L'ho imparato al MUSEO di\n"
	.string "PORTO ALGHE, ma me lo sono scordato.$"

Route105_Text_BeverlyIntro:
	.string "Nell'acqua il corpo è più leggero.\n"
	.string "È come se fossi dimagrita!$"

Route105_Text_BeverlyDefeated:
	.string "Sto fluttuando…$"

Route105_Text_PostBattle:
	.string "Sott'acqua il tuo peso si riduce\n"
	.string "a un decimo.\p"
	.string "Così diventerei…\n"
	.string "Ops! Non ti dico quanto peso!$"

Route105_Text_ImaniIntro:
	.string "Il cielo blu, blu…\n"
	.string "Il mare immenso…\l"
	.string "Che pace…$"

Route105_Text_ImaniDefeated:
	.string "Ho perso mentre riposavo!$"

Route105_Text_ImaniPostBattle:
	.string "Vorrei che mi dicessero che con me\n"
	.string "si sta rilassati. Eh eh.$"

Route105_Text_AndresIntro:
	.string "Sono convinto che il mare ci nasconda\n"
	.string "dei segreti.$"

Route105_Text_AndresDefeated:
	.string "Sì…\n"
	.string "Non sono bravo a lottare…$"

Route105_Text_AndresPostBattle:
	.string "Sono certo che ci siano molti segreti\n"
	.string "da scoprire nei mari del mondo.\p"
	.string "Li troverò tutti!$"

Route105_Text_AndresRegister:
	.string "Eh? Sono così debole, ma vuoi\n"
	.string "registrarmi nel POKéNAV?$"

Route105_Text_AndresRematchIntro:
	.string "Te l'ho detto che sono debole…\n"
	.string "Sicuro di volerlo fare?$"

Route105_Text_AndresRematchDefeated:
	.string "Sì…\n"
	.string "Non pensavo di poter vincere.$"

Route105_Text_AndresRematchPostBattle:
	.string "Sarò debole a lottare, ma la mia\n"
	.string "voglia di esplorare non si batte.\p"
	.string "Viaggerò per tutti i mari\n"
	.string "del mondo!$"

Route105_Text_JosueIntro:
	.string "Sono esausto per il nuoto.\n"
	.string "Non ci sono abituato.\p"
	.string "Mi serve una lotta per cambiare!$"

Route105_Text_JosueDefeated:
	.string "Ho perso perché ho lottato in mare.$"

Route105_Text_JosuePostBattle:
	.string "Sì, per me il cielo è molto meglio\n"
	.string "del mare.$"

Route106_Text_ElliotIntro:
	.string "Preferisci pescare in mare\n"
	.string "o in un torrente?$"

Route106_Text_ElliotDefeated:
	.string "Come nella pesca d'altura,\n"
	.string "ho perso alla grande!$"

Route106_Text_ElliotPostBattle:
	.string "Pescare è stupendo, in mare\n"
	.string "o in un torrente.\l"
	.string "Vero, sei d'accordo?$"

Route106_Text_ElliotRegister:
	.string "Pescare è bello, ma lottare di più.\n"
	.string "Se ti va, ci ribattiamo?$"

Route106_Text_ElliotRematchIntro:
	.string "Pescando ho preso un sacco di POKéMON.\n"
	.string "Ti farò vedere una lotta coi fiocchi!$"

Route106_Text_ElliotRematchDefeated:
	.string "Ho perso di nuovo alla grande!$"

Route106_Text_ElliotRematchPostBattle:
	.string "Vinci o perdi, i POKéMON sono il massimo!\n"
	.string "Sei d'accordo con me, vero?$"

Route106_Text_NedIntro:
	.string "Dove si va quando serve\n"
	.string "andare in bagno?\p"
	.string "E se il mio AMO aggancia un pesce grosso\n"
	.string "mentre sono in bagno? Non posso andare…$"

Route106_Text_NedDefeated:
	.string "Ho perso perché sto cercando\n"
	.string "di non andare in bagno…$"

Route106_Text_NedPostBattle:
	.string "Oh, no! Ho la sensazione che\n"
	.string "aggancerò un pesce grosso!$"

Route106_Text_DouglasIntro:
	.string "Ahahah! Corro male, ma\n"
	.string "nell'acqua non mi batti!$"

Route106_Text_DouglasDefeated:
	.string "Mi arrendo!$"

Route106_Text_DouglasPostBattle:
	.string "In una gara di nuoto non perderei…$"

Route106_Text_KylaIntro:
	.string "Il mare è casa mia. Non ci vado\n"
	.string "piano solo perché sei un bambino!$"

Route106_Text_KylaDefeated:
	.string "Per caso mi hai\n"
	.string "trattata con i guanti?$"

Route106_Text_KylaPostBattle:
	.string "Andare alla deriva fra le onde…\n"
	.string "Adoro! Perché non provi anche tu?$"

Route107_Text_DarrinIntro:
	.string "Sbadiglio…\p"
	.string "Devo essermi addormentato mentre\n"
	.string "andavo alla deriva fra le onde.$"

Route107_Text_DarrinDefeated:
	.string "Ahaha, ho perso…\n"
	.string "Credo che mi farò un pisolino…$"

Route107_Text_DarrinPostBattle:
	.string "Fluttuare cullati dalle onde,\n"
	.string "è come dormire in un letto\l"
	.string "morbido e comodo.$"

Route107_Text_TonyIntro:
	.string "Il mare è come casa mia.\n"
	.string "Lottiamo!$"

Route107_Text_TonyDefeated:
	.string "Ho perso in casa mia…\n"
	.string "Sono scioccato!$"

Route107_Text_TonyPostBattle:
	.string "Nuoto nei mari con il cuore pieno\n"
	.string "di sogni…\p"
	.string "È una canzone!\n"
	.string "Comunque, vado a nuotare ancora.$"

Route107_Text_TonyRegister:
	.string "Mi hai scosso fin nelle ossa!\n"
	.string "Beh, così non mi dimenticherai…$"

Route107_Text_TonyRematchIntro:
	.string "Nuotando nel mare grande e aperto,\n"
	.string "i miei POKéMON si sono rinforzati!$"

Route107_Text_TonyRematchDefeated:
	.string "Che shock!\p"
	.string "I miei POKéMON sono più forti,\n"
	.string "ma io resto un ALLENATORE debole!$"

Route107_Text_TonyRematchPostBattle:
	.string "Ciò che impari lottando ti rende\n"
	.string "un ALLENATORE più forte.\l"
	.string "Me l'hanno insegnato le onde.$"

Route107_Text_DeniseIntro:
	.string "Conosci una cittadina chiamata\n"
	.string "PORTO ALGHE?$"

Route107_Text_DeniseDefeated:
	.string "Che rabbia!$"

Route107_Text_DenisePostBattle:
	.string "Un modo di dire strano va molto\n"
	.string "di moda al PORTO ALGHE.$"

Route107_Text_BethIntro:
	.string "Volevi lottare con me?\n"
	.string "Certo, vengo con te!$"

Route107_Text_BethDefeated:
	.string "Non sono stata all'altezza.$"

Route107_Text_BethPostBattle:
	.string "Penso che migliorerai sempre\n"
	.string "di più. Anch'io ci proverò!$"

Route107_Text_LisaIntro:
	.string "LISA: Ti sfidiamo come sorella\n"
	.string "e fratello!$"

Route107_Text_LisaDefeated:
	.string "LISA: Fantastico.\n"
	.string "Sei di un'altra categoria di forza.$"

Route107_Text_LisaPostBattle:
	.string "LISA: Hai amici che verrebbero\n"
	.string "in spiaggia con te?$"

Route107_Text_LisaNotEnoughPokemon:
	.string "LISA: Se vuoi lottare con noi,\n"
	.string "porta più POKéMON.$"

Route107_Text_RayIntro:
	.string "RAY: Io e mia sorella lottiamo\n"
	.string "sempre con i POKéMON.\p"
	.string "Perdo sempre, ma ti battiamo\n"
	.string "in due contro due!$"

Route107_Text_RayDefeated:
	.string "RAY: Uau, sei di un livello\n"
	.string "più alto del nostro!$"

Route107_Text_RayPostBattle:
	.string "RAY: I POKéMON me li ha dati mia sorella.\n"
	.string "L'ho allenato, ora è il mio partner\l"
	.string "importante!$"

Route107_Text_RayNotEnoughPokemon:
	.string "RAY: Se vuoi sfidarci,\n"
	.string "porta altri POKéMON!$"

Route107_Text_CamronIntro:
	.string "Sono a metà di un triathlon,\n"
	.string "ma non sono per niente stanco!$"

Route107_Text_CamronDefeated:
	.string "Che fatica…$"

Route107_Text_CamronPostBattle:
	.string "Dopo questa mi restano nuoto\n"
	.string "e corsa da fare.\p"
	.string "Ce la farò?$"

Route108_Text_JeromeIntro:
	.string "Sogno di nuotare i sette mari\n"
	.string "del mondo!$"

Route108_Text_JeromeDefeated:
	.string "Così non potrò nuotare i sette mari\n"
	.string "del mondo…$"

Route108_Text_JeromePostBattle:
	.string "Giocare con i POKéMON marini è uno\n"
	.string "dei piaceri del nuoto!$"

Route108_Text_MatthewIntro:
	.string "Ehilà! Vai anche tu verso\n"
	.string "la NAVE ABBANDONATA?$"

Route108_Text_MatthewDefeated:
	.string "Sto affondando!\n"
	.string "Glub… Glub…$"

Route108_Text_MatthewPostBattle:
	.string "C'è chi entra perfino dentro quella\n"
	.string "NAVE ABBANDONATA.$"

Route108_Text_TaraIntro:
	.string "Il mio bugiardo di fidanzato mi ha detto\n"
	.string "che sto benissimo in bikini…$"

Route108_Text_TaraDefeated:
	.string "Oh, che pizza!$"

Route108_Text_TaraPostBattle:
	.string "Anche se è una bugia, adoro sentirmi dire\n"
	.string "che sto bene…\l"
	.string "Noi ragazze siamo complicate…$"

Route108_Text_MissyIntro:
	.string "Adoro il mare!\n"
	.string "Nuotando dimentico ogni pensiero!$"

Route108_Text_MissyDefeated:
	.string "Quando perdo una lotta,\n"
	.string "mi stresso tutta!$"

Route108_Text_MissyPostBattle:
	.string "Sfoga lo stress nuotando!\n"
	.string "Fa così bene!$"

Route108_Text_CoryIntro:
	.string "Adoro i POKéMON di tipo ACQUA.\n"
	.string "Adoro anche gli altri POKéMON!$"

Route108_Text_CoryDefeated:
	.string "Waaah! Ho perso!\n"
	.string "Waaah! Waaah!$"

Route108_Text_CoryPostBattle:
	.string "Urlare mi fa bene!\n"
	.string "Mi tira su!$"

Route108_Text_CoryRegister:
	.string "Adoro anche gli ALLENATORI forti!\n"
	.string "Registrami nel POKéNAV!$"

Route108_Text_CoryRematchIntro:
	.string "Vinca o perda, adoro lottare in mare!$"

Route108_Text_CoryRematchDefeated:
	.string "Waaah! Ho perso di nuovo!\n"
	.string "Waaah! Waaah!$"

Route108_Text_CoryRematchPostBattle:
	.string "Se ti trovi davanti a una sfida,\n"
	.string "prova a urlare al mare!$"

Route108_Text_CarolinaIntro:
	.string "Vado molto fiera dei miei POKéMON.\n"
	.string "Ti mostrerò una lotta veloce!$"

Route108_Text_CarolinaDefeated:
	.string "Non è stato affatto carino.$"

Route108_Text_CarolinaPostBattle:
	.string "In mezzo al mare, non mi dispiacerebbe\n"
	.string "mettere un costume rosa con le balze…$"

Route109_Text_DavidIntro:
	.string "Hiyah! Guarda che addominali scolpiti!\n"
	.string "Questo si chiama “taglio”!$"

Route109_Text_DavidDefeated:
	.string "Ahià!\n"
	.string "Ho toppato!$"

Route109_Text_DavidPostBattle:
	.string "Hiyah!\p"
	.string "I miei addominali scolpiti non c'entrano\n"
	.string "con le lotte POKéMON!$"

Route109_Text_AliceIntro:
	.string "Sei ben protetto contro\n"
	.string "il sole?$"

Route109_Text_AliceDefeated:
	.string "Ahia, ahia, ahia!$"

Route109_Text_AlicePostBattle:
	.string "Le guance sono le prime a scottarsi!$"

Route109_Text_HueyIntro:
	.string "Ho gettato l'ancora in porti di\n"
	.string "tutto il mondo, ma PORTOALGHE è il top.$"

Route109_Text_HueyDefeated:
	.string "Sei il migliore!$"

Route109_Text_HueyPostBattle:
	.string "Nel porto migliore c'era il miglior\n"
	.string "ALLENATORE…$"

Route109_Text_EdmondIntro:
	.string "Urrrrppp…\n"
	.string "Una lotta? Con me?$"

Route109_Text_EdmondDefeated:
	.string "Burp… Ooooooohhhhhh…\n"
	.string "Burrrp…$"

Route109_Text_EdmondPostBattle:
	.string "Di solito sono più forte!\n"
	.string "È il mal di mare, cane che mi fa!\p"
	.string "Sono un MARINAIO, ma…$"

Route109_Text_RickyIntro:
	.string "Ho sete… berrei una GASSOSA\n"
	.string "alla CASA SUL MARE…$"

Route109_Text_RickyDefeated:
	.string "Uff…$"

Route109_Text_RickyPostBattle:
	.string "Sto morendo di fame… Il salvagente\n"
	.string "sembra una ciambella gigante…$"

Route109_Text_RickyRegister:
	.string "Facciamo un'altra lotta quando\n"
	.string "non ho tutta questa sete?$"

Route109_Text_RickyRematchIntro:
	.string "Ho fame, ma ho abbastanza energia\n"
	.string "per una lotta!$"

Route109_Text_RickyRematchDefeated:
	.string "Ho perso…\n"
	.string "È perché ho fame…$"

Route109_Text_RickyRematchPostBattle:
	.string "Quando mangi sulla spiaggia, tutto\n"
	.string "sembra avere un sapore migliore.$"

Route109_Text_LolaIntro:
	.string "Un ombrellone non sembra forse\n"
	.string "un fiore gigante?$"

Route109_Text_LolaDefeated:
	.string "Mamma!$"

Route109_Text_LolaPostBattle:
	.string "Se guardi la spiaggia dal cielo,\n"
	.string "sembra un grande giardino fiorito!$"

Route109_Text_LolaRegister:
	.string "Io?\n"
	.string "Sono qui ogni giorno!$"

Route109_Text_LolaRematchIntro:
	.string "Non perderò di nuovo con te!\n"
	.string "Per questo ho il mio salvagente!$"

Route109_Text_LolaRematchDefeated:
	.string "Mamma!$"

Route109_Text_LolaRematchPostBattle:
	.string "Con il salvagente, la tenerezza mia\n"
	.string "e dei miei POKéMON sale alle stelle!$"

Route109_Text_AustinaIntro:
	.string "Non so nuotare senza il salvagente,\n"
	.string "ma ai POKéMON non perdo!$"

Route109_Text_AustinaDefeated:
	.string "Ho perso perché ho il salvagente\n"
	.string "gonfiabile?$"

Route109_Text_AustinaPostBattle:
	.string "Il mio salvagente è un accessorio.\n"
	.string "Non posso farmi vedere senza.$"

Route109_Text_GwenIntro:
	.string "Ciao, grande ALLENATORE.\n"
	.string "Ti va di lottare con me?$"

Route109_Text_GwenDefeated:
	.string "Oh, sei forte.$"

Route109_Text_GwenPostBattle:
	.string "Come hai fatto a diventare così forte?$"

Route109_Text_CarterIntro:
	.string "Wahahah! Questo tipo ne pescherà\n"
	.string "uno grosso!$"

Route109_Text_CarterDefeated:
	.string "Questo tipo ha appena perso…$"

Route109_Text_CarterPostBattle:
	.string "Questo tipo ti crede uno grosso.\n"
	.string "No, uno che diventerà grosso!$"

Route109_Text_PaulIntro:
	.string "PAUL: Beh, che guastafeste.\p"
	.string "Vorrei che non disturbassi il nostro\n"
	.string "prezioso tempo insieme.$"

Route109_Text_PaulDefeated:
	.string "PAUL: Beh, mi arrendo.$"

Route109_Text_PaulPostBattle:
	.string "PAUL: Beh, non dire a nessuno che\n"
	.string "siamo qui.\l"
	.string "È il nostro mondo privato per due!$"

Route109_Text_PaulNotEnoughPokemon:
	.string "PAUL: Siamo innamorati persi.\n"
	.string "Per questo facciamo lottare i nostri\l"
	.string "POKéMON insieme.$"

Route109_Text_MelIntro:
	.string "MEL: Siamo, tipo, innamorati persi.\n"
	.string "Il nostro amore scalda tutta HOENN!$"

Route109_Text_MelDefeated:
	.string "MEL: Abbiamo perso, è colpa mia!\n"
	.string "PAUL mi odierà!$"

Route109_Text_MelPostBattle:
	.string "MEL: Ehm, PAUL, sei arrabbiato con me?\n"
	.string "Ti prego, non arrabbiarti.$"

Route109_Text_MelNotEnoughPokemon:
	.string "MEL: Siamo, tipo, innamorati persi.\n"
	.string "Per questo facciamo lottare i nostri\l"
	.string "POKéMON insieme.$"

Route109_Text_ChandlerIntro:
	.string "Tadaah! Visto?\n"
	.string "Il mio salvagente è rotondo!$"

Route109_Text_ChandlerDefeated:
	.string "Oh, oh!\n"
	.string "Che peccato!$"

Route109_Text_ChandlerPostBattle:
	.string "E dopo che ti ho mostrato il mio\n"
	.string "salvagente rotondo…$"

Route109_Text_HaileyIntro:
	.string "Non so nuotare, quindi fingo\n"
	.string "di nuotare.$"

Route109_Text_HaileyDefeated:
	.string "Lo sapevo!\n"
	.string "Non credevo che vincessimo.$"

Route109_Text_HaileyPostBattle:
	.string "Quando imparerò a nuotare, i miei\n"
	.string "POKéMON diventeranno più forti.$"

Route109_Text_ElijahIntro:
	.string "Per uno macho come me, questo\n"
	.string "tipo di POKéMON è perfetto!$"

Route109_Text_ElijahDefeated:
	.string "Resto un duro anche se perdo, eh?$"

Route109_Text_ElijahPostBattle:
	.string "Per uno macho come me, un porto\n"
	.string "è lo scenario perfetto!\p"
	.string "Penso che andrò a PORTOALGHE.$"

Route110_Text_JacobIntro:
	.string "Whoa! Attento!\n"
	.string "Non sei abituato alle corse in Bicicletta.$"

Route110_Text_JacobDefeated:
	.string "Whoa!\n"
	.string "I miei freni hanno ceduto!$"

Route110_Text_JacobPostBattle:
	.string "Gomme a terra e freni guasti\n"
	.string "possono causare gravi infortuni!\l"
	.string "Controlla la Bicicletta!$"

Route110_Text_AnthonyIntro:
	.string "Ehi, tu!\n"
	.string "Riesci a tenere il mio ritmo?$"

Route110_Text_AnthonyDefeated:
	.string "Che botta!$"

Route110_Text_AnthonyPostBattle:
	.string "Solo la velocità non basta per vincere.\n"
	.string "Devo ripensarci…$"

Route110_Text_BenjaminIntro:
	.string "Niente panico se la BICI va veloce!$"

Route110_Text_BenjaminDefeated:
	.string "Non dovrei farmi prendere dal panico\n"
	.string "nelle lotte…$"

Route110_Text_BenjaminPostBattle:
	.string "Non serve farsi prendere dal panico.\n"
	.string "Con calma. C'è tutto il tempo.$"

Route110_Text_BenjaminRegister:
	.string "Continuerò senza stressarmi.\n"
	.string "Fammi un fischio se ti va.$"

Route110_Text_BenjaminRematchIntro:
	.string "Non stai andando un po' troppo veloce?\n"
	.string "Con calma, lottiamo.$"

Route110_Text_BenjaminRematchDefeated:
	.string "Non mi sono agitato, ma ho perso…$"

Route110_Text_BenjaminRematchPostBattle:
	.string "Non serve farsi prendere dal panico.\n"
	.string "Con calma. C'è tutto il tempo.$"

Route110_Text_AbigailIntro:
	.string "Il triathlon è durissimo.\p"
	.string "Devi completare le tre prove\n"
	.string "di nuoto, ciclismo e corsa.$"

Route110_Text_AbigailDefeated:
	.string "Anche le lotte POKéMON sono dure!$"

Route110_Text_AbigailPostBattle:
	.string "Sono esausta, mi serve una pausa.\n"
	.string "È importante riposare bene.$"

Route110_Text_AbigailRegister:
	.string "Sai, mi piaci!\n"
	.string "Rivinciamoci sulla PISTA CICLABILE.$"

Route110_Text_AbigailRematchIntro:
	.string "Non è bello lottare mentre\n"
	.string "si va in bicicletta?$"

Route110_Text_AbigailRematchDefeated:
	.string "Wow…\n"
	.string "Come fai a essere così forte?$"

Route110_Text_AbigailRematchPostBattle:
	.string "Andavi a caccia di un record?\p"
	.string "Scusa se ti ho rallentato!$"

Route110_Text_JasmineIntro:
	.string "Pedalo senza mai fermarmi.\n"
	.string "Ho le cosce dure come rocce!$"

Route110_Text_JasmineDefeated:
	.string "Temo i crampi muscolari…$"

Route110_Text_JasminePostBattle:
	.string "Oh, hai delle MEDAGLIE?\n"
	.string "Ecco perché sei così forte!$"

Route110_Text_EdwardIntro:
	.string "Ho previsto le tue intenzioni!\n"
	.string "Non posso assolutamente perdere!$"

Route110_Text_EdwardDefeated:
	.string "Non ho saputo prevedere la mia fine!$"

Route110_Text_EdwardPostBattle:
	.string "Vedo il tuo futuro…\p"
	.string "Hmm…\n"
	.string "Vedo una luce splendente…$"

Route110_Text_JaclynIntro:
	.string "Ahahahaha!\n"
	.string "Ti stupirò con le mie meraviglie!$"

Route110_Text_JaclynDefeated:
	.string "Ho perso in modo prodigioso!$"

Route110_Text_JaclynPostBattle:
	.string "Hai vinto solo perché è stato\n"
	.string "un prodigio! Sì, un prodigio!\l"
	.string "Non credere di vincere sempre!$"

Route110_Text_EdwinIntro:
	.string "Posso vedere i tuoi POKéMON?\n"
	.string "Solo un'occhiata, ti prego?$"

Route110_Text_EdwinDefeated:
	.string "Volevo completare\n"
	.string "la mia collezione…$"

Route110_Text_EdwinPostBattle:
	.string "Quando vedo un POKéMON che non conosco,\n"
	.string "si accende la passione del collezionista!$"

Route110_Text_EdwinRegister:
	.string "Mi piace collezionare anche\n"
	.string "le iscrizioni MATCH CALL…$"

Route110_Text_EdwinRematchIntro:
	.string "Ciao, hai catturato POKéMON nuovi?\p"
	.string "Posso vedere i tuoi POKéMON?\n"
	.string "Solo un'occhiata, ti prego?$"

Route110_Text_EdwinRematchDefeated:
	.string "I tuoi POKéMON…\n"
	.string "Ti invidio.$"

Route110_Text_EdwinRematchPostBattle:
	.string "Oh, desidero tanto che tutti i POKéMON\n"
	.string "rari siano miei!$"

Route110_Text_DaleIntro:
	.string "Ehi!\n"
	.string "Non arrivarmi alle spalle così!$"

Route110_Text_DaleDefeated:
	.string "Ho perso!\n"
	.string "Accidenti!$"

Route110_Text_DalePostBattle:
	.string "Pescare è questione di concentrazione.\n"
	.string "Devi fissare il galleggiante.$"

Route110_Text_IsabelIntro:
	.string "Ahahaha! Andrei ovunque per sfoggiare\n"
	.string "i miei deliziosi POKéMON.$"

Route110_Text_IsabelDefeated:
	.string "Oh, cielo, così non va.$"

Route110_Text_IsabelPostBattle:
	.string "Invece di lottare, forse dovrei\n"
	.string "sfoggiare i POKéMON al FAN CLUB.$"

Route110_Text_IsabelRegister:
	.string "Non era nemmeno lontanamente quello\n"
	.string "che so fare coi miei POKéMON.\p"
	.string "Ti avrò come pubblico in gabbia\n"
	.string "il più spesso possibile!$"

Route110_Text_IsabelRematchIntro:
	.string "Ahahahaha! Sarei felice di sfoggiare\n"
	.string "i miei POKéMON quanto ti pare!$"

Route110_Text_IsabelRematchDefeated:
	.string "Oh, cielo, così non va.$"

Route110_Text_IsabelRematchPostBattle:
	.string "Credo che non smetterei mai\n"
	.string "di sfoggiare i miei POKéMON.\p"
	.string "Ma mi piace anche lottare!$"

Route110_Text_TimmyIntro:
	.string "Ho trovato POKéMON forti nell'erba\n"
	.string "qui intorno!$"

Route110_Text_TimmyDefeated:
	.string "Essere forti non basta per vincere…$"

Route110_Text_TimmyPostBattle:
	.string "È dura lottare con POKéMON\n"
	.string "appena catturati.$"

Route110_Text_AlyssaIntro:
	.string "Sono caduta dalla PISTA CICLABILE…\p"
	.string "Mi riprenderò dalla figuraccia\n"
	.string "lottando con te!$"

Route110_Text_AlyssaDefeated:
	.string "Ops!\n"
	.string "Ho finito per perdere!$"

Route110_Text_AlyssaPostBattle:
	.string "Cadere… Perdere…\n"
	.string "Che umiliazione per me!$"

Route110_Text_JosephIntro:
	.string "Okay! Si va a tutta velocità! Chi non\n"
	.string "segue il ritmo resta indietro!$"

Route110_Text_JosephDefeated:
	.string "Hai trovato il ritmo, eh…$"

Route110_Text_JosephPostBattle:
	.string "Questo non mi abbatterà!\n"
	.string "Perdere mi ha reso migliore!$"

Route110_Text_KalebIntro:
	.string "Quando dei bei POKéMON si aiutano…\n"
	.string "Non c'è vista più adorabile!$"

Route110_Text_KalebDefeated:
	.string "Non hai pietà né compassione?$"

Route110_Text_KalebPostBattle:
	.string "Okay, okay, avete dato il massimo,\n"
	.string "miei tesori.$"

Route111_Text_DrewIntro:
	.string "Oh, ehi! Ti stanno bene quegli OCCHIALI.\n"
	.string "Ma credo stiano meglio a me.\p"
	.string "Decidiamo chi li porta meglio\n"
	.string "con una lotta!$"

Route111_Text_DrewDefeat:
	.string "Con gli OCCHIALI ANTI-SABBIA non\n"
	.string "vedevo cosa succedeva ai lati.$"

Route111_Text_DrewPostBattle:
	.string "Gli OCCHIALI ANTI-SABBIA permettono di\n"
	.string "attraversare le tempeste di sabbia.\l"
	.string "Che bello!$"

Route111_Text_HeidiIntro:
	.string "Sto facendo un picnic nel deserto.\p"
	.string "Gli ALLENATORI si trovano sempre,\n"
	.string "quindi posso anche lottare!$"

Route111_Text_HeidiDefeat:
	.string "Ohhh! Sei cattivo!$"

Route111_Text_HeidiPostBattle:
	.string "Quando lotti in una tempesta di sabbia,\n"
	.string "attento ai PS dei POKéMON.\p"
	.string "Possono svenire se non\n"
	.string "li controlli!$"

Route111_Text_BeauIntro:
	.string "Con questi OCCHIALONI mi sento\n"
	.string "come un supereroe.\l"
	.string "Ora nessuno può battermi!$"

Route111_Text_BeauDefeat:
	.string "Non posso vincere col solo Fatuanima…$"

Route111_Text_BeauPostBattle:
	.string "Un giorno sarò un vero eroe.\n"
	.string "Mi impegnerò di più per rendere\l"
	.string "forti me e i miei POKéMON.$"

Route111_Text_BeckyIntro:
	.string "Ho sentito che nel deserto si trovano\n"
	.string "fossili. Dove saranno?$"

Route111_Text_BeckyDefeat:
	.string "Non ce l'ho fatta…$"

Route111_Text_BeckyPostBattle:
	.string "Se nel deserto si trovano fossili,\n"
	.string "prima doveva essere un mare.$"

Route111_Text_DustyIntro:
	.string "Da trent'anni cerco\n"
	.string "rovine antiche!\l"
	.string "Vuoi sfidarmi?$"

Route111_Text_DustyDefeat:
	.string "Ho cercato rovine,\n"
	.string "ma non POKéMON forti.$"

Route111_Text_DustyPostBattle:
	.string "Da trent'anni cerco\n"
	.string "rovine antiche!\p"
	.string "No, aspetta, erano quarant'anni?\n"
	.string "Quanti erano?$"

Route111_Text_DustyRegister:
	.string "Non ho mai cercato\n"
	.string "POKéMON forti.\p"
	.string "Ma, non so perché, adoro\n"
	.string "i POKéNAV.$"

Route111_Text_DustyRematchIntro:
	.string "Da trent'anni cerco\n"
	.string "rovine antiche!\p"
	.string "No, aspetta, erano quarant'anni?\n"
	.string "Comunque, vuoi sfidarmi?$"

Route111_Text_DustyRematchDefeat:
	.string "Non ho trovato rovine, né\n"
	.string "POKéMON forti…$"

Route111_Text_DustyPostRematch:
	.string "Da trent'anni cerco\n"
	.string "rovine antiche!\p"
	.string "No, aspetta, erano quarant'anni\n"
	.string "che cerco?\p"
	.string "Hmm… Forse anche cinquanta…\n"
	.string "Da quanto vado avanti?$"

Route111_Text_TravisIntro:
	.string "Sono pieno di brio!\n"
	.string "E anche i miei POKéMON!$"

Route111_Text_TravisDefeat:
	.string "I miei POKéMON hanno perso la grinta…$"

Route111_Text_TravisPostBattle:
	.string "Se vedo un ALLENATORE pieno di brio,\n"
	.string "non riesco a non guardarlo.$"

Route111_Text_IreneIntro:
	.string "Non so dove stai andando,\n"
	.string "ma ti va di lottare?$"

Route111_Text_IreneDefeat:
	.string "Oh, sei bravo da far schifo!$"

Route111_Text_IrenePostBattle:
	.string "Pensavo di andare\n"
	.string "sul MT. CAMINO, ma il panorama\l"
	.string "qui è molto bello.$"

Route111_Text_DaisukeIntro:
	.string "Per allenarmi, sfido chiunque\n"
	.string "incontri!$"

Route111_Text_DaisukeDefeat:
	.string "Zio! Mi arrendo!$"

Route111_Text_DaisukePostBattle:
	.string "Mi allenerò finché non potrò\n"
	.string "battere ALLENATORI forti\l"
	.string "come te.$"

Route111_Text_WiltonIntro:
	.string "Fammi vedere quanto hai temprato\n"
	.string "i tuoi POKéMON.$"

Route111_Text_WiltonDefeat:
	.string "Capisco, li hai temprati\n"
	.string "parecchio.$"

Route111_Text_WiltonPostBattle:
	.string "POKéMON e ALLENATORI imparano molto\n"
	.string "lottando.\p"
	.string "L'importante è non arrendersi\n"
	.string "mai, anche se perdi.$"

Route111_Text_WiltonRegister:
	.string "C'è molto da imparare dal\n"
	.string "tuo stile di allenamento.\p"
	.string "Ti chiedo una rivincita,\n"
	.string "se ti va.$"

Route111_Text_WiltonRematchIntro:
	.string "Ci alleniamo qui per salire\n"
	.string "di livello.\l"
	.string "Resta ad allenarti con noi!$"

Route111_Text_WiltonRematchDefeat:
	.string "Ooh, niente male!$"

Route111_Text_WiltonPostRematch:
	.string "Se sei così forte, punta\n"
	.string "alla LEGA POKéMON.$"

Route111_Text_BrookeIntro:
	.string "Oh, i tuoi POKéMON sembrano\n"
	.string "attori seri.\l"
	.string "Devo chiederti un duello.$"

Route111_Text_BrookeDefeat:
	.string "Non sembravano solo forti,\n"
	.string "sono forti!$"

Route111_Text_BrookePostBattle:
	.string "Credevo di allenare i POKéMON\n"
	.string "con cura, ma c'è ancora\l"
	.string "molto da fare.$"

Route111_Text_BrookeRegister:
	.string "Vorrei fare amicizia con\n"
	.string "altre persone forti come te!$"

Route111_Text_BrookeRematchIntro:
	.string "Puoi rendere i POKéMON più forti o\n"
	.string "deboli a seconda delle mosse che\l"
	.string "insegnifai loro.\p"
	.string "Che mosse conoscono\n"
	.string "i tuoi POKéMON?$"

Route111_Text_BrookeRematchDefeat:
	.string "Hai insegnato loro belle mosse!$"

Route111_Text_BrookePostRematch:
	.string "Forse non dovevo far evolvere\n"
	.string "i POKéMON prima che\l"
	.string "imparassero mosse migliori…$"

Route111_Text_CeliaIntro:
	.string "Non dovevo venire in un posto\n"
	.string "così per un picnic!$"

Route111_Text_CeliaDefeat:
	.string "Oh!\n"
	.string "Non dovevo proprio venire!$"

Route111_Text_CeliaPostBattle:
	.string "Con questa tempesta di sabbia non posso\n"
	.string "preparare il picnic nemmeno con\l"
	.string "gli OCCHIALI ANTI-SABBIA…$"

Route111_Text_BryanIntro:
	.string "Quanto sei forte?\n"
	.string "Sveleremo quel segreto!$"

Route111_Text_BryanDefeat:
	.string "Oh! La tua forza!\n"
	.string "È avvolta nel mistero!$"

Route111_Text_BryanPostBattle:
	.string "Questo deserto cela misteri\n"
	.string "fra le sue sabbie mobili!$"

Route111_Text_BrandenIntro:
	.string "Ti do un po' del mio panino\n"
	.string "se perdi.$"

Route111_Text_BrandenDefeat:
	.string "Tch! Credevo che un panino\n"
	.string "bastasse come tangente…$"

Route111_Text_BrandenPostBattle:
	.string "Il mio SANDSHREW adora mangiare\n"
	.string "i miei panini.$"

Route111_Text_TyronIntro:
	.string "Questo è il mio tipo di POKéMON preferito!$"

Route111_Text_TyronDefeat:
	.string "Aspetta!\n"
	.string "Hai visto bene i miei POKéMON?$"

Route111_Text_TyronPostBattle:
	.string "In lotta mi diverto un sacco a\n"
	.string "mostrare i miei POKéMON.\p"
	.string "Scommetto che lo sentono tutti\n"
	.string "quando entrano in lotta!$"

Route111_Text_CelinaIntro:
	.string "Mostrami come dare un po' di pepe\n"
	.string "alla mia vita.$"

Route111_Text_CelinaDefeat:
	.string "Oh… Mio…\n"
	.string "Che bella emozione!$"

Route111_Text_CelinaPostBattle:
	.string "Il cuore mi batte ancora forte.\n"
	.string "Sei un ALLENATORE favoloso.$"

Route111_Text_HaydenIntro:
	.string "Quando hai fame come me,\n"
	.string "non c'è spazio per la pietà!$"

Route111_Text_HaydenDefeat:
	.string "Uff…$"

Route111_Text_HaydenPostBattle:
	.string "Il mio stomaco brontola!\n"
	.string "Forse posso grigliare delle BACche…$"

Route111_Text_BiancaIntro:
	.string "Vieni da MAUVILLE?\n"
	.string "Allora dovresti essere pieno di energia!$"

Route111_Text_BiancaDefeat:
	.string "Ooh lala!\n"
	.string "È dura da digerire!$"

Route111_Text_BiancaPostBattle:
	.string "Questa strada…\n"
	.string "Hai ancora molta da fare.$"

Route112_Text_BriceIntro:
	.string "Ahahahah!\n"
	.string "Facciamo una lotta?\l"
	.string "Tu e io!\l"
	.string "Ahahahah!$"

Route112_Text_BriceDefeat:
	.string "Ho perso!\n"
	.string "Ahahahah!$"

Route112_Text_BricePostBattle:
	.string "Ahahahah! Mi è andato qualcosa nel naso!\n"
	.string "Ahahaha-éccciù!$"

Route112_Text_TrentIntro:
	.string "Ho gambe d'acciaio a forza di salire\n"
	.string "e scendere per le montagne.\p"
	.string "Non cedono facilmente,\n"
	.string "amico!$"

Route112_Text_TrentDefeat:
	.string "Ahi! Mi sono venuti i crampi alle gambe!$"

Route112_Text_TrentPostBattle:
	.string "Fai escursioni, e intendo davvero\n"
	.string "pestando i sentieri di montagna\l"
	.string "con uno zaino pesante, decine di\l"
	.string "chili.\p"
	.string "Ecco, amico mio, come ti fai un fisico\n"
	.string "serio.$"

Route112_Text_TrentRegister:
	.string "Ahia, mi sono venuti i crampi.\n"
	.string "Mi prendi delle bende dal\l"
	.string "mio zaino?\p"
	.string "No, quello è il mio POKéNAV!\n"
	.string "Va bene, ti registro.$"

Route112_Text_TrentRematchIntro:
	.string "Mi tengo in forma con le escursioni.\n"
	.string "Di potenza ne ho da vendere!$"

Route112_Text_TrentRematchDefeat:
	.string "Sono stato battuto in potenza?$"

Route112_Text_TrentRematchPostBattle:
	.string "Dicono che ci siano ALLENATORI\n"
	.string "tosti in cima al MONTE CAMINO.\p"
	.string "Voglio arrivarci e lanciare\n"
	.string "una sfida!$"

Route112_Text_LarryIntro:
	.string "Sono forte.\n"
	.string "Non piango se perdo.$"

Route112_Text_LarryDefeat:
	.string "Waaaaaah!$"

Route112_Text_LarryPostBattle:
	.string "Non piango perché mi manca la mamma!\n"
	.string "Singhiozzo…$"

Route112_Text_CarolIntro:
	.string "Quando sei a un picnic, beh,\n"
	.string "devi per forza cantare!\l"
	.string "Dai, canta con me!$"

Route112_Text_CarolDefeat:
	.string "Oh, sei fortissimo!$"

Route112_Text_CarolPostBattle:
	.string "Non conta se sei bravo o no\n"
	.string "a cantare o coi POKéMON.\p"
	.string "Se ti diverti di più, hai vinto!$"

Route112_Text_BryantIntro:
	.string "Ho preso POKéMON focosi nel FIERY PATH!\n"
	.string "Dai un'occhiata!$"

Route112_Text_BryantDefeat:
	.string "Che corsa accidentata!$"

Route112_Text_BryantPostBattle:
	.string "Mi piace come lotti.\n"
	.string "Hai un certo stile.$"

Route112_Text_ShaylaIntro:
	.string "Oh, che ALLENATORE adorabile!\n"
	.string "Ti prego, voglio una lotta romantica!\l"
	.string "Non me la cavo male!$"

Route112_Text_ShaylaDefeat:
	.string "Oh, quanto sei forte!\n"
	.string "Mi hai dato un bello spavento!$"

Route112_Text_ShaylaPostBattle:
	.string "Sei occupato adesso?\n"
	.string "Pensavo che magari potremmo fare\l"
	.string "una rivincita proprio ora…\l"
	.string "Ma va bene anche se sei occupato.$"

Route113_Text_JaylenIntro:
	.string "Sai perché da queste parti\n"
	.string "si sta così bene?$"

Route113_Text_JaylenDefeat:
	.string "Puuuh!\n"
	.string "Che puzza!$"

Route113_Text_JaylenPostBattle:
	.string "La cenere vulcanica blocca il sole,\n"
	.string "quindi non fa molto caldo.\p"
	.string "Per me è ottimo, non sopporto il caldo!$"

Route113_Text_DillonIntro:
	.string "L'eruzione del vulcano prova che\n"
	.string "la terra è viva.$"

Route113_Text_DillonDefeat:
	.string "Sei forte davvero!$"

Route113_Text_DillonPostBattle:
	.string "Ahi! Ahia! Non ci vedo!\n"
	.string "Ho la cenere tra le ciglia!\p"
	.string "Capito? Cenere e ciglia?\p"
	.string "Ok, era brutta, scusa…$"

Route113_Text_MadelineIntro:
	.string "Uso questo ombrellino per riparare\n"
	.string "il mio caro NUMEL da questa\l"
	.string "sporca cenere vulcanica.$"

Route113_Text_MadelineDefeat:
	.string "Fiu, fiu…\n"
	.string "Sono esausta…$"

Route113_Text_MadelinePostBattle:
	.string "Sei molto bravo.\n"
	.string "Devo dire che sono colpita!$"

Route113_Text_MadelineRegister:
	.string "Vieni, infilati sotto il mio ombrellino.\n"
	.string "Ti registro nel mio POKéNAV.$"

Route113_Text_MadelineRematchIntro:
	.string "Oh, ciao, quanto tempo!\n"
	.string "Ti va di lottare con me?$"

Route113_Text_MadelineRematchDefeat:
	.string "Oh, che meraviglia!$"

Route113_Text_MadelinePostRematch:
	.string "Sei rimasto molto bravo.\n"
	.string "Devo dire che sono colpita!$"

Route113_Text_LaoIntro:
	.string "Dalle ceneri balzo fuori! Hiyah!\n"
	.string "Ti sfido!$"

Route113_Text_LaoDefeat:
	.string "Con onore ammetto la sconfitta!$"

Route113_Text_LaoPostBattle:
	.string "Devo affinare l'arte del mimetismo.\n"
	.string "Ti saluto.$"

Route113_Text_LaoRegister:
	.string "Yiiyaah! Ammira l'antica tecnica\n"
	.string "ninja della registrazione POKéNAV!$"

Route113_Text_LaoRematchIntro:
	.string "Dalle ceneri balzo fuori! Hiyah!\n"
	.string "Ti sfido!$"

Route113_Text_LaoRematchDefeat:
	.string "Con onore ammetto la sconfitta!$"

Route113_Text_LaoPostRematch:
	.string "Il mio mimetismo impeccabile è stato\n"
	.string "rovinato dalle mie scarse doti in lotta…\p"
	.string "Ti saluto.$"

Route113_Text_LungIntro:
	.string "Grazie per avermi trovato!\n"
	.string "Ma dobbiamo ancora lottare!$"

Route113_Text_LungDefeat:
	.string "Userò il mio ninjutsu su di te…\n"
	.string "“MANTELLO VORTICE DI CENERE”!\p"
	.string "…Come?\n"
	.string "È già finita?$"

Route113_Text_LungPostBattle:
	.string "Sai cosa c'è di brutto nel nascondersi?\n"
	.string "È triste se non arriva nessuno.$"

Route113_Text_ToriIntro:
	.string "TORI: Noi due raccogliamo cenere.\n"
	.string "E lottiamo anche coi POKéMON.$"

Route113_Text_ToriDefeat:
	.string "TORI: Abbiamo perso… Che noia, vado\n"
	.string "a raccogliere altra cenere.$"

Route113_Text_ToriPostBattle:
	.string "TORI: Quanta cenere abbiamo?\n"
	.string "Spero abbastanza per un FLUTO BIANCO.$"

Route113_Text_ToriNotEnoughMons:
	.string "TORI: Vogliamo lottare 2 contro 2.\n"
	.string "Se no, perderemmo!$"

Route113_Text_TiaIntro:
	.string "TIA: Noi due raccogliamo cenere.\n"
	.string "E lottiamo anche coi POKéMON.$"

Route113_Text_TiaDefeat:
	.string "TIA: Non abbiamo vinto… Che noia,\n"
	.string "vado a raccogliere altra cenere.$"

Route113_Text_TiaPostBattle:
	.string "TIA: Abbiamo tanta cenere!\n"
	.string "Direi abbastanza per un FLUTO BIANCO!$"

Route113_Text_TiaNotEnoughMons:
	.string "TIA: Vogliamo lottare 2 contro 2.\n"
	.string "Se no, non vinciamo!$"

Route113_Text_CobyIntro:
	.string "Pfft, con queste ali ti\n"
	.string "spazzo via!$"

Route113_Text_CobyDefeat:
	.string "A… Come?$"

Route113_Text_CobyPostBattle:
	.string "Non so che dire quando vengo\n"
	.string "battuto così facilmente…$"

Route113_Text_SophieIntro:
	.string "Il caldo qui mi fa sonnecchiare.\n"
	.string "Lotta con me per restare sveglia.$"

Route113_Text_SophieDefeat:
	.string "Questo è un sogno.\n"
	.string "Ne sono certa…$"

Route113_Text_SophiePostBattle:
	.string "Perdere mi brucia…\n"
	.string "Dormirò proprio qui!\l"
	.string "Zzz!$"

Route113_Text_LawrenceIntro:
	.string "Per caso eri in mezzo\n"
	.string "a raccogliere ceneri vulcaniche?$"

Route113_Text_LawrenceDefeat:
	.string "Ehehe.\n"
	.string "Ci hanno battuti nettamente.$"

Route113_Text_LawrencePostBattle:
	.string "I ought to hide under the ashes, too.$"

Route113_Text_WyattIntro:
	.string "V-vuoi lottare con me?\n"
	.string "Anche se ho appena preso il POKéMON?$"

Route113_Text_WyattDefeat:
	.string "S-siete tutti contenti di vincere?\n"
	.string "Anche se c'ero solo io?$"

Route113_Text_WyattPostBattle:
	.string "Oh, ora vuoi dire qualcosa\n"
	.string "allo sconfitto?\p"
	.string "Non sei proprio il massimo?\n"
	.string "Umpf!$"

Route114_Text_LennyIntro:
	.string "Iodelaihiuu!\p"
	.string "… …\p"
	.string "Dovresti gridare\n"
	.string "“iodelaihiuu”, dato che qui non\l"
	.string "c'è eco!$"

Route114_Text_LennyDefeat:
	.string "Iodelaihiuu!$"

Route114_Text_LennyPostBattle:
	.string "Da piccolo credevo che\n"
	.string "ci fosse qualcuno che mi imitava gridando\l"
	.string "“Iodelaihiuu”.$"

Route114_Text_LucasIntro:
	.string "Se non sei preparato, non dovresti\n"
	.string "stare in montagna!$"

Route114_Text_LucasDefeat:
	.string "Le montagne non perdonano…$"

Route114_Text_LucasPostBattle:
	.string "In inverno le montagne diventano letali\n"
	.string "con bufere e valanghe.$"

Route114_Text_ShaneIntro:
	.string "Il campeggio è divertente! Puoi pescare,\n"
	.string "abbrustolire marshmallow e raccontare\p"
	.string "storie di paura! Ma la cosa migliore\n"
	.string "sono le lotte POKéMON!$"

Route114_Text_ShaneDefeat:
	.string "Troppo forte!$"

Route114_Text_ShanePostBattle:
	.string "Penso sia fantastico poter andare\n"
	.string "in campeggio con i miei POKéMON.$"

Route114_Text_NancyIntro:
	.string "Devo muovermi dopo mangiato.\n"
	.string "Facciamo una lotta!$"

Route114_Text_NancyDefeat:
	.string "Oh, no!$"

Route114_Text_NancyPostBattle:
	.string "Ho appena mangiato bene.\n"
	.string "Mi sta venendo sonno…$"

Route114_Text_SteveIntro:
	.string "Ufufufufufu…\n"
	.string "Vuoi lottare contro i miei POKéMON?$"

Route114_Text_SteveDefeat:
	.string "I-Il mio POKéMON…$"

Route114_Text_StevePostBattle:
	.string "Un corpo enorme, bitorzoluto e duro,\n"
	.string "corna gigantesche e zanne feroci…\p"
	.string "Ufufufufu…\n"
	.string "Vorrei un POKéMON così…$"

Route114_Text_SteveRegister:
	.string "Non dimenticare cosa mi hai fatto!\n"
	.string "Farò in modo che tu non possa scordarlo!$"

Route114_Text_SteveRematchIntro:
	.string "Ufufufufufu…\n"
	.string "Dai, lotta con i miei POKéMON…$"

Route114_Text_SteveRematchDefeat:
	.string "Che fortuna poter vedere i tuoi\n"
	.string "POKéMON…$"

Route114_Text_StevePostRematch:
	.string "Ufufufufufu…\p"
	.string "Quando vedo dei POKéMON lottare,\n"
	.string "mi vengono brividi e tremori…$"

Route114_Text_BernieIntro:
	.string "Se accendi un falò,\n"
	.string "tieni dell'acqua a portata di mano.$"

Route114_Text_BernieDefeat:
	.string "Grazie per aver spento il mio fuoco!$"

Route114_Text_BerniePostBattle:
	.string "Devi stare attento con\n"
	.string "qualsiasi tipo di fuoco in una foresta.\p"
	.string "Non sottovalutare mai la potenza\n"
	.string "del fuoco.$"

Route114_Text_BernieRegister:
	.string "Mi hai acceso l'anima.\n"
	.string "Registriamoci a vicenda!$"

Route114_Text_BernieRematchIntro:
	.string "Hai imparato a tenere l'acqua a portata\n"
	.string "per i falò?$"

Route114_Text_BernieRematchDefeat:
	.string "Mi hanno spento prima che potessi\n"
	.string "divampare, direi.$"

Route114_Text_BerniePostRematch:
	.string "Devi stare attento con\n"
	.string "qualsiasi tipo di fuoco in una foresta.\p"
	.string "Non sottovalutare mai la potenza\n"
	.string "del fuoco.$"

Route114_Text_ClaudeIntro:
	.string "Se stessimo pescando, non avresti\n"
	.string "speranza contro di me.\l"
	.string "Forza, tira fuori i tuoi POKéMON!$"

Route114_Text_ClaudeDefeat:
	.string "Se stessimo pescando, avrei vinto…$"

Route114_Text_ClaudePostBattle:
	.string "Proverò a pescare\n"
	.string "un bel pesce alle CASCATE METEORA.\p"
	.string "Là dentro c'è per forza qualcosa.\n"
	.string "Lo so e basta.$"

Route114_Text_NolanIntro:
	.string "Mi piace pescare. Ma mi piace anche\n"
	.string "lottare!\p"
	.string "Se qualcuno mi sfida, ci sono,\n"
	.string "anche se sto pescando.$"

Route114_Text_NolanDefeat:
	.string "Mi piace lottare, ma non\n"
	.string "significa che sia bravo…$"

Route114_Text_NolanPostBattle:
	.string "Stavolta ce la farò!\p"
	.string "Lo penso sempre, così non riesco a\n"
	.string "lasciare la pesca o i POKéMON.$"

Route114_Text_TyraIntro:
	.string "TYRA: Beh, certo.\n"
	.string "Ne ho voglia.\l"
	.string "Ti insegnerò qualcosa sui POKéMON.$"

Route114_Text_TyraDefeat:
	.string "TYRA: Che stile di lotta fantastico!$"

Route114_Text_TyraPostBattle:
	.string "TYRA: Stavo insegnando a IVY,\n"
	.string "la mia allieva, cose sui POKéMON.$"

Route114_Text_TyraNotEnoughMons:
	.string "TYRA: Ihih…\n"
	.string "Se vuoi lottare con noi, un solo\l"
	.string "POKéMON non basta!$"

Route114_Text_IvyIntro:
	.string "IVY: Chi ti ha parlato dei POKéMON?$"

Route114_Text_IvyDefeat:
	.string "IVY: Che stile di lotta fantastico!$"

Route114_Text_IvyPostBattle:
	.string "IVY: Ho iniziato ad allenare POKéMON\n"
	.string "perché TYRA, la mia maestra,\l"
	.string "mi ha insegnato!$"

Route114_Text_IvyNotEnoughMons:
	.string "IVY: Hai solo un POKéMON?\n"
	.string "Immagino si senta solo.$"

Route114_Text_KaiIntro:
	.string "Ho preso un pesce grosso!\n"
	.string "Enorme, te lo dico!$"

Route114_Text_KaiDefeat:
	.string "Che è successo?\n"
	.string "Il mio era più piccolo?$"

Route114_Text_KaiPostBattle:
	.string "Va bene!\n"
	.string "Me ne pescherò uno più grande!$"

Route114_Text_CharlotteIntro:
	.string "Io!\n"
	.string "Non sono solo un bel muso!$"

Route114_Text_CharlotteDefeat:
	.string "Non è stato affatto carino!$"

Route114_Text_CharlottePostBattle:
	.string "Non voglio un POKéMON che sia\n"
	.string "solo carino.\p"
	.string "Adoro quelli carini che hanno\n"
	.string "qualche stranezza!$"

Route114_Text_AngelinaIntro:
	.string "Hai fatto evolvere molto\n"
	.string "i tuoi POKéMON?$"

Route114_Text_AngelinaDefeat:
	.string "Oh, capisco.\n"
	.string "Buono a sapersi.$"

Route114_Text_AngelinaPostBattle:
	.string "Certi POKéMON cambiano tanto\n"
	.string "quando si evolvono, che spavento!$"

Route115_Text_TimothyIntro:
	.string "Hm…\n"
	.string "Sembri piuttosto capace…\l"
	.string "Fammi compagnia!$"

Route115_Text_TimothyDefeat:
	.string "Sei molto più forte di\n"
	.string "quanto immaginassi!$"

Route115_Text_TimothyPostBattle:
	.string "Non esistono geni nati.\n"
	.string "Tutto dipende dall'impegno!\l"
	.string "Questo è ciò che credo…$"

Route115_Text_TimothyRegister:
	.string "Mmm… Una sconfitta così netta non la\n"
	.string "ricordavo da tempo.\p"
	.string "Se me lo concedi, vorrei avere\n"
	.string "un'altra occasione per lottare.$"

Route115_Text_TimothyRematchIntro:
	.string "Mmm… La tua agilità parla\n"
	.string "da sola.\l"
	.string "Vieni, fammi compagnia!$"

Route115_Text_TimothyRematchDefeat:
	.string "Forte come sempre!$"

Route115_Text_TimothyPostRematch:
	.string "Tutto ciò che serve è l'impegno!\p"
	.string "Ho perso perché non mi sono\n"
	.string "impegnato abbastanza!$"

Route115_Text_KoichiIntro:
	.string "Tu!\p"
	.string "I miei MACHOP!\p"
	.string "Ti sfidiamo a lottare!$"

Route115_Text_KoichiDefeat:
	.string "Ahia, ahia, ahia!$"

Route115_Text_KoichiPostBattle:
	.string "La mia squadra di MACHOP!\p"
	.string "Finché cercheranno la forza, io\n"
	.string "crescerò insieme a loro!$"

Route115_Text_NobIntro:
	.string "Il mio talento migliore è spaccare\n"
	.string "mattoni con la fronte!$"

Route115_Text_NobDefeat:
	.string "Ugwaaaah!\n"
	.string "Mi sono spaccato la testa!$"

Route115_Text_NobPostBattle:
	.string "Ho insegnato il karate ai miei POKéMON.\p"
	.string "Sembra che diventeranno molto più\n"
	.string "forti di me. Ne sono felice.$"

Route115_Text_NobRegister:
	.string "Mi hai impressionato! Ridammi una\n"
	.string "sfida dopo che mi sarò riallenato!$"

Route115_Text_NobRematchIntro:
	.string "Dopo che mi hai battuto, ci siamo\n"
	.string "allenati duramente.\l"
	.string "Dai, ridacci la rivincita!$"

Route115_Text_NobRematchDefeat:
	.string "Ugwaaah!\n"
	.string "Abbiamo perso di nuovo!$"

Route115_Text_NobPostRematch:
	.string "I miei POKéMON diventeranno più forti!\n"
	.string "Raddoppierò gli allenamenti!$"

Route115_Text_CyndyIntro:
	.string "Questa spiaggia è il mio posto segreto\n"
	.string "per allenarmi! Non intrometterti!$"

Route115_Text_CyndyDefeat:
	.string "Non mi sono allenata abbastanza!$"

Route115_Text_CyndyPostBattle:
	.string "La sabbia attutisce i colpi e riduce\n"
	.string "gli infortuni.\l"
	.string "È il posto perfetto per allenarsi.$"

Route115_Text_CyndyRegister:
	.string "Va bene, puoi venire qui.\n"
	.string "In cambio, voglio lottare di nuovo con te.$"

Route115_Text_CyndyRematchIntro:
	.string "Forza, diamo il via a questa lotta!$"

Route115_Text_CyndyRematchDefeat:
	.string "Posso lottare, ma i miei POKéMON…$"

Route115_Text_CyndyPostRematch:
	.string "Anche quando perdo, mi diverto\n"
	.string "lo stesso.\l"
	.string "Dev'essere perché amo i POKéMON.$"

Route115_Text_HectorIntro:
	.string "Ho un POKéMON raro!\n"
	.string "Vuoi che te lo mostri?$"

Route115_Text_HectorDefeat:
	.string "Tu…\n"
	.string "Vuoi il mio POKéMON, vero?$"

Route115_Text_HectorPostBattle:
	.string "Ho questo POKéMON raro.\n"
	.string "Mi basta per essere soddisfatto.$"

Route115_Text_KyraIntro:
	.string "Lotterò mentre corro!\n"
	.string "Prova a starmi dietro!$"

Route115_Text_KyraDefeat:
	.string "Anf, anf…$"

Route115_Text_KyraPostBattle:
	.string "Ho sbagliato a lottare mentre\n"
	.string "correvo!\p"
	.string "Dovrei fare una corsa per calmarmi…$"

Route115_Text_JaidenIntro:
	.string "Prendi questo!\n"
	.string "Attacco ninja ultra POKéMON!$"

Route115_Text_JaidenDefeat:
	.string "Uaaah!\n"
	.string "La nostra strategia è fallita!$"

Route115_Text_JaidenPostBattle:
	.string "Ma i miei POKéMON erano ultra,\n"
	.string "no?$"

Route115_Text_HeleneIntro:
	.string "I miei POKéMON hanno la forza di\n"
	.string "una cintura nera!$"

Route115_Text_HeleneDefeat:
	.string "Che umiliazione!$"

Route115_Text_HelenePostBattle:
	.string "Raramente incontro qualcuno più\n"
	.string "forte di me…\p"
	.string "Ho capito!\n"
	.string "Sei un CAPOPALESTRA, vero?$"

Route115_Text_AlixIntro:
	.string "I nostri sguardi si sono incrociati!\n"
	.string "Ora non puoi più scappare!$"

Route115_Text_AlixDefeat:
	.string "Ah!\n"
	.string "Mica male!$"

Route115_Text_AlixPostBattle:
	.string "Beh, pazienza.\n"
	.string "Penso che mi TELETRASPORTerò a casa.$"

Route115_Text_MarleneIntro:
	.string "Hai disturbato la mia meditazione…\n"
	.string "Per questo verrai punito.$"

Route115_Text_MarleneDefeat:
	.string "Hai spezzato la mia concentrazione!$"

Route115_Text_MarlenePostBattle:
	.string "Meditavo con i miei POKéMON.\n"
	.string "Ma questo posto non è molto tranquillo…$"

Route116_Text_ClarkIntro:
	.string "Se il tunnel non passa, allora\n"
	.string "passerò sopra la cima.$"

Route116_Text_ClarkDefeat:
	.string "Anf… Anf…\n"
	.string "Perdere mi ha stancato…$"

Route116_Text_ClarkPostBattle:
	.string "Non importa se non c'è un tunnel.\n"
	.string "Per un MONTANARO i monti sono strade!$"

Route116_Text_JoeyIntro:
	.string "I miei POKéMON spaccano!\n"
	.string "Guardali!$"

Route116_Text_JoeyDefeat:
	.string "Ahia! Che graffio!\n"
	.string "Devo mettermi un cerotto!$"

Route116_Text_JoeyPostBattle:
	.string "I cerotti sono segni di forza!\n"
	.string "Ne ho un altro!$"

Route116_Text_JoseIntro:
	.string "I miei POKéMON COLEOTTERO sono forti!\n"
	.string "Lottiamo!$"

Route116_Text_JoseDefeat:
	.string "Ho perso!\n"
	.string "Credevo di averti battuto!$"

Route116_Text_JosePostBattle:
	.string "I POKéMON COLEOTTERO evolvono presto.\n"
	.string "Così diventano forti in fretta.$"

Route116_Text_JaniceIntro:
	.string "Ti mostro quanto sono forti i miei\n"
	.string "adorabili POKéMON!$"

Route116_Text_JaniceDefeat:
	.string "Sei un gradino sopra di me…$"

Route116_Text_JanicePostBattle:
	.string "POKéMON che uniscono grazia e\n"
	.string "forza, ecco l'ideale, credo.$"

Route116_Text_JerryIntro:
	.string "Alla SCUOLA ALLENATORI impariamo\n"
	.string "un sacco di cose.\p"
	.string "Voglio provarle sul campo!$"

Route116_Text_JerryDefeat:
	.string "A scuola non studiavo…\n"
	.string "Ecco perché ho perso.$"

Route116_Text_JerryPostBattle:
	.string "Dovrò rifare qualche corso alla\n"
	.string "SCUOLA ALLENATORI.\l"
	.string "Altrimenti ROXANNE si arrabbierà.$"

Route116_Text_JerryRegister1:
	.string "Alla SCUOLA ALLENATORI ho imparato\n"
	.string "che il POKéNAV registra gli ALLENATORI.\p"
	.string "Non capisco bene cosa significhi,\n"
	.string "posso provare?$"

Route116_Text_JerryRegister2:
	.string "Alla SCUOLA ALLENATORI ho imparato\n"
	.string "che il POKéNAV registra gli ALLENATORI.\p"
	.string "Non capisco bene cosa significhi,\n"
	.string "posso provare?$"

Route116_Text_JerryRematchIntro:
	.string "Ho studiato seriamente alla\n"
	.string "SCUOLA ALLENATORI.\l"
	.string "Non perderò come l'altra volta.$"

Route116_Text_JerryRematchDefeat:
	.string "Eh?\n"
	.string "Ho studiato con impegno.$"

Route116_Text_JerryPostRematch:
	.string "Dovrò rifare qualche corso alla\n"
	.string "SCUOLA ALLENATORI.\l"
	.string "Altrimenti ROXANNE si arrabbierà.$"

Route116_Text_KarenIntro:
	.string "Studio a scuola e studio anche\n"
	.string "tornando a casa!$"

Route116_Text_KarenDefeat:
	.string "Che shock, ho perso?$"

Route116_Text_KarenPostBattle:
	.string "Uffa, così non diventerò mai un'\n"
	.string "ALLENATRICE elegante come ROXANNE!$"

Route116_Text_KarenRegister1:
	.string "Oh, wow! Quello è un POKéNAV?\n"
	.string "Ce l'ho anche io! Registrami, ti prego!$"

Route116_Text_KarenRegister2:
	.string "Oh, wow! Quello è un POKéNAV?\n"
	.string "Ce l'ho anche io! Registrami, ti prego!$"

Route116_Text_KarenRematchIntro:
	.string "Ho studiato molto da quando ti ho visto.\n"
	.string "Devi vedere i miei progressi!$"

Route116_Text_KarenRematchDefeat:
	.string "Che shock.\n"
	.string "Ho perso di nuovo?$"

Route116_Text_KarenPostRematch:
	.string "Hai battuto ROXANNE?\n"
	.string "Allora non posso vincere. Non ancora.$"

Route116_Text_SarahIntro:
	.string "Sappi che non sono mai stata\n"
	.string "battuta da nessuno in nulla.$"

Route116_Text_SarahDefeat:
	.string "Oh, santo cielo.\n"
	.string "È una novità per me.$"

Route116_Text_SarahPostBattle:
	.string "La mia vita di lusso mi concede tutto\n"
	.string "ciò che potrei desiderare.\p"
	.string "Però, quando si tratta di POKéMON,\n"
	.string "la mia ricchezza non ha valore.$"

Route116_Text_DawsonIntro:
	.string "Quando vedrai il pelo stupendo dei\n"
	.string "miei POKéMON, la loro bellezza ti\l"
	.string "lascerà senza forze!$"

Route116_Text_DawsonDefeat:
	.string "Oh, tesoro, dimmi che non è vero!$"

Route116_Text_DawsonPostBattle:
	.string "Oh, no, no, no!\n"
	.string "Hai scompigliato il pelo dei miei POKéMON!\l"
	.string "Hai rovinato anche la mia acconciatura!\l"
	.string "Ora devo chiamare il parrucchiere!$"

Route116_Text_DevanIntro:
	.string "Ti faremo a pezzi!$"

Route116_Text_DevanDefeat:
	.string "Ahi ahi!\n"
	.string "Non c'è stata partita!$"

Route116_Text_DevanPostBattle:
	.string "Dovrei provare POKéMON di\n"
	.string "tipi diversi, è quello che dovrei fare.$"

Route116_Text_JohnsonIntro:
	.string "Quassù è un vicolo cieco.\n"
	.string "Mi annoio, facciamo una lotta?$"

Route116_Text_JohnsonDefeat:
	.string "È stato divertente anche se ho perso.$"

Route116_Text_JohnsonPostBattle:
	.string "Vuoi restare qui a farmi\n"
	.string "compagnia?$"

Route117_Text_IsaacIntro:
	.string "Senti, potresti lottare contro\n"
	.string "i POKéMON che sto allevando?$"

Route117_Text_IsaacDefeat:
	.string "Hai allevato i tuoi in modo superbo…$"

Route117_Text_IsaacPostBattle:
	.string "I POKéMON non sono solo forza.\p"
	.string "Curare un aspetto unico del loro\n"
	.string "carattere è un altro modo di godersi\l"
	.string "i POKéMON.$"

Route117_Text_IsaacRegister:
	.string "Raddoppierò il mio allenamento.\n"
	.string "Verresti a trovarci?$"

Route117_Text_IsaacRematchIntro:
	.string "I POKéMON che ho allevato\n"
	.string "sono in forma, come prima.$"

Route117_Text_IsaacRematchDefeat:
	.string "Sai come allevarli bene.\n"
	.string "Potresti avere doti da PENSIONE…$"

Route117_Text_IsaacPostRematch:
	.string "I tuoi POKéMON stanno crescendo bene!\n"
	.string "Dovresti farli partecipare alle GARE.$"

Route117_Text_LydiaIntro:
	.string "Ti prego, fammi valutare se hai\n"
	.string "allevato bene i tuoi POKéMON.$"

Route117_Text_LydiaDefeat:
	.string "Sì, stanno crescendo bene.$"

Route117_Text_LydiaPostBattle:
	.string "Prova ad allevare i POKéMON dando\n"
	.string "più peso ai tratti del carattere.$"

Route117_Text_LydiaRegister:
	.string "I'm glad I met a superb TRAINER in you.\n"
	.string "I hope to see you again.$"

Route117_Text_LydiaRematchIntro:
	.string "Fammi rivalutare se hai\n"
	.string "allevato bene i tuoi POKéMON.$"

Route117_Text_LydiaRematchDefeat:
	.string "Stanno crescendo in modo ammirevole.$"

Route117_Text_LydiaPostRematch:
	.string "I POKéMON sembrano gradire tipi\n"
	.string "diversi di {POKEBLOCK} a seconda della natura.$"

Route117_Text_DylanIntro:
	.string "Sono a metà di un triathlon, ma\n"
	.string "vabbè, facciamo una lotta!$"

Route117_Text_DylanDefeat:
	.string "Ho esaurito le energie!$"

Route117_Text_DylanPostBattle:
	.string "Forse ho fatto un disastro…\p"
	.string "In quella lotta potrei essere\n"
	.string "scivolato all'ultimo posto…$"

Route117_Text_DylanRegister:
	.string "Anche i POKéMON devono essere forti?\n"
	.string "Vorrei che mi allenassi tu!$"

Route117_Text_DylanRematchIntro:
	.string "Sono nel bel mezzo di un triathlon,\n"
	.string "ma sono comodamente in testa.\l"
	.string "Facciamo una lotta veloce!$"

Route117_Text_DylanRematchDefeat:
	.string "Ho di nuovo esaurito le energie!$"

Route117_Text_DylanPostRematch:
	.string "Ero il migliore in nuoto e bici,\n"
	.string "ma non sono ancora così sicuro\l"
	.string "con i POKéMON.$"

Route117_Text_MariaIntro:
	.string "Mi alleno per il triathlon con i POKéMON,\n"
	.string "quindi sono sicura della mia velocità.$"

Route117_Text_MariaDefeat:
	.string "Devo allenarmi di più,\n"
	.string "direi.$"

Route117_Text_MariaPostBattle:
	.string "L'allenamento ha senso solo se\n"
	.string "lo fai con regolarità.\p"
	.string "Ok! Riprendo l'allenamento!\n"
	.string "Domani!$"

Route117_Text_MariaRegister:
	.string "Vedo che ti alleni come si deve…\n"
	.string "Se vuoi, ti sfido più tardi!$"

Route117_Text_MariaRematchIntro:
	.string "Ti stai allenando come si deve?\n"
	.string "Io di sicuro!\l"
	.string "Lascia che ti mostri le prove!$"

Route117_Text_MariaRematchDefeat:
	.string "Devo allenarmi di più,\n"
	.string "direi.$"

Route117_Text_MariaPostRematch:
	.string "Riprenderò ad allenarmi domani.\n"
	.string "Lottiamo di nuovo qualche volta!$"

Route117_Text_DerekIntro:
	.string "Prima PIGLIABUG!\n"
	.string "Ora MANIACO DEL COLEOTTERO!\p"
	.string "Ma il mio amore per i POKéMON\n"
	.string "resta immutato!$"

Route117_Text_DerekDefeat:
	.string "Anche la mia incapacità\n"
	.string "resta immutata…$"

Route117_Text_DerekPostBattle:
	.string "Ho solo seguito il cuore, e ora\n"
	.string "mi chiamano MANIACO DEL COLEOTTERO…\p"
	.string "Sono un esperto di POKéMON\n"
	.string "COLEOTTERO, quindi è naturale che\l"
	.string "mi chiamino MANIACO DEL COLEOTTERO.$"

Route117_Text_AnnaIntro:
	.string "ANNA: Sono con la mia graziosa\n"
	.string "allieva. Devo fare bella figura!$"

Route117_Text_AnnaDefeat:
	.string "ANNA: Sono con la mia graziosa\n"
	.string "allieva! Lasciami vincere!$"

Route117_Text_AnnaPostBattle:
	.string "ANNA: I tuoi POKéMON hanno\n"
	.string "ottime combinazioni.\p"
	.string "Direi che sei secondo solo a noi!$"

Route117_Text_AnnaAndMegRegister:
	.string "ANNA: Non ci arrendiamo di certo!\n"
	.string "Tornerai a trovarci, vero?$"

Route117_Text_AnnaNotEnoughMons:
	.string "ANNA: Se vuoi sfidarci,\n"
	.string "porta due POKéMON.$"

Route117_Text_MegIntro:
	.string "MEG: Farò coppia col mio super\n"
	.string "compagno veterano e ti batterò!$"

Route117_Text_MegDefeat:
	.string "MEG: Oh, no!\n"
	.string "Scusa, ANNA! Ti ho delusa…$"

Route117_Text_MegPostBattle:
	.string "MEG: Ho trascinato giù ANNA…\n"
	.string "Se no, avrebbe vinto lei!$"

Route117_Text_MegNotEnoughMons:
	.string "MEG: Hai solo un POKéMON?\n"
	.string "Allora non possiamo lottare.\p"
	.string "Vogliamo una lotta 2 contro 2.$"

Route117_Text_AnnaRematchIntro:
	.string "ANNA: Non posso continuare a perdere\n"
	.string "davanti alla mia allieva, no?$"

Route117_Text_AnnaRematchDefeat:
	.string "ANNA: Non ero in vena.$"

Route117_Text_AnnaPostRematch:
	.string "ANNA: I tuoi POKéMON hanno\n"
	.string "ottime combinazioni.\p"
	.string "Direi che sei secondo solo a noi!$"

Route117_Text_AnnaRematchNotEnoughMons:
	.string "ANNA: Se vuoi sfidarci,\n"
	.string "porta due POKéMON.$"

Route117_Text_MegRematchIntro:
	.string "MEG: Farò coppia col mio\n"
	.string "compagno veterano e stavolta vincerò!$"

Route117_Text_MegRematchDefeat:
	.string "MEG: Troppo forte!$"

Route117_Text_MegPostRematch:
	.string "MEG: Ho lottato col mio\n"
	.string "compagno veterano, ma abbiamo perso…\p"
	.string "Che scoraggiamento…$"

Route117_Text_MegRematchNotEnoughMons:
	.string "MEG: Hai solo un POKéMON?\n"
	.string "Allora non possiamo lottare.\p"
	.string "Vogliamo una lotta 2 contro 2.$"

Route117_Text_MelinaIntro:
	.string "Non è bello? Lottare guardando\n"
	.string "dei bei fiori?$"

Route117_Text_MelinaDefeat:
	.string "Oh, niente male davvero!$"

Route117_Text_MelinaPostBattle:
	.string "È meraviglioso fare una corsetta\n"
	.string "guardando i fiori.$"

Route117_Text_BrandiIntro:
	.string "Ti mostro la forza\n"
	.string "nascosta in un POKéMON PSICHICO!$"

Route117_Text_BrandiDefeat:
	.string "Sbalorditivo!$"

Route117_Text_BrandiPostBattle:
	.string "I POKéMON PSICHICI sono complessi.\n"
	.string "Prova a catturarne qualcuno.$"

Route117_Text_AishaIntro:
	.string "Punta a vincere.\n"
	.string "Io lotto così!$"

Route117_Text_AishaDefeat:
	.string "Non perdo tempo a arrabbiarmi\n"
	.string "per una sconfitta, meglio allenarmi.$"

Route117_Text_AishaPostBattle:
	.string "Se temi di perdere,\n"
	.string "è più probabile che tu perda.$"

Route118_Text_RoseIntro:
	.string "L'aroma dei fiori ha un potere\n"
	.string "stregone. Ci purifica corpo e anima.$"

Route118_Text_RoseDefeat:
	.string "Oh, povere me.\n"
	.string "Mi sa che ho perso.$"

Route118_Text_RosePostBattle:
	.string "Fiori, POKéMON…\n"
	.string "Amo tutto ciò che profuma bene.\p"
	.string "Le cose puzzolenti…\n"
	.string "Le passo.$"

Route118_Text_RoseRegister:
	.string "Sniff… Quell'odore, è un POKéNAV!\n"
	.string "Dobbiamo registrarci a vicenda!$"

Route118_Text_RoseRematchIntro:
	.string "Sei stato attirato qui dal dolce\n"
	.string "aroma?$"

Route118_Text_RoseRematchDefeat:
	.string "Il potere dell'aroma…\n"
	.string "Non ha fatto granché.$"

Route118_Text_RosePostRematch:
	.string "Se usi bene un aroma dolce,\n"
	.string "i POKéMON ne restano attratti.$"

Route118_Text_PerryIntro:
	.string "I POKéMON UCCELLO che VOLANO eleganti\n"
	.string "nel cielo… Sono i migliori!$"

Route118_Text_PerryDefeat:
	.string "Urgh…\n"
	.string "Sono precipitato…$"

Route118_Text_PerryPostBattle:
	.string "Hai dei POKéMON fantastici.\n"
	.string "Dovrò allenare meglio i miei.$"

Route118_Text_ChesterIntro:
	.string "Prendete il volo!\n"
	.string "Miei POKéMON UCCELLO!$"

Route118_Text_ChesterDefeat:
	.string "Hanno preso il volo…$"

Route118_Text_ChesterPostBattle:
	.string "Se diventassero più forti, potrebbero\n"
	.string "volare più liberi…$"

Route118_Text_BarnyIntro:
	.string "I'm a FISHERMAN, but also a TRAINER.\n"
	.string "I'm raising the POKéMON I caught.$"

Route118_Text_BarnyDefeat:
	.string "Credevo di allenarmi\n"
	.string "bene…$"

Route118_Text_BarnyPostBattle:
	.string "Non potevo vincere allenando POKéMON\n"
	.string "mentre pescavo…\p"
	.string "Facevo le cose a metà?$"

Route118_Text_WadeIntro:
	.string "Per i PESCATORI l'attrezzatura è tutto.\p"
	.string "Ma per gli ALLENATORI gli ingredienti\n"
	.string "sono i POKéMON e il cuore, certo!$"

Route118_Text_WadeDefeat:
	.string "Ho perso nel cuore?$"

Route118_Text_WadePostBattle:
	.string "A pensarci bene, pescare è una lotta\n"
	.string "tra un PESCATORE e un POKéMON.$"

Route118_Text_DaltonIntro:
	.string "Che la mia melodia ti scuota l'anima!$"

Route118_Text_DaltonDefeat:
	.string "La-lalala…$"

Route118_Text_DaltonPostBattle:
	.string "Una chitarra elettrica non deve\n"
	.string "essere per forza rumorosa…\p"
	.string "Si può strimpellare per tirar fuori\n"
	.string "questa melodia commovente…$"

Route118_Text_DaltonRegister:
	.string "Quando comporrò melodie migliori,\n"
	.string "devi venire ad ascoltare, ok?$"

Route118_Text_DaltonRematchIntro:
	.string "Una melodia dai miei POKéMON e da me…\n"
	.string "Lascia che ti arrivi nell'anima.$"

Route118_Text_DaltonRematchDefeat:
	.string "La-lalala…$"

Route118_Text_DaltonPostRematch:
	.string "Quando suono, le mie emozioni devono\n"
	.string "arrivarti attraverso la mia chitarra…$"

Route118_Text_DeandreIntro:
	.string "Vai, vai, vai!\n"
	.string "POKéMON 1, 2 e 3!$"

Route118_Text_DeandreDefeat:
	.string "Venite qui, POKéMON! Tutto ok?\n"
	.string "POKéMON 1, 2 e 3?!$"

Route118_Text_DeandrePostBattle:
	.string "Non è forte che ho una squadra\n"
	.string "da lotta di POKéMON?\p"
	.string "Puoi copiarmi, non mi offendo!$"

Route119_Text_BrentIntro:
	.string "Siamo il CIRCOLO MIMICA!\n"
	.string "Imitiamo tutto ciò che fai!$"

Route119_Text_BrentDefeat:
	.string "Ops!\n"
	.string "Ho perso!$"

Route119_Text_BrentPostBattle:
	.string "Cosa ha di bello la mimica?\p"
	.string "Fufufu…\n"
	.string "Non capirai mai…$"

Route119_Text_DonaldIntro:
	.string "So, we finally meet!\n"
	.string "My BUG POKéMON will keep you company!$"

Route119_Text_DonaldDefeat:
	.string "Vorrei non averti mai incontrato…$"

Route119_Text_DonaldPostBattle:
	.string "Voglio imitarti ancora un po'.\n"
	.string "Puoi sbrigarti a muoverti?$"

Route119_Text_TaylorIntro:
	.string "Se fai un passo avanti, lo faccio anch'io.\p"
	.string "Se giri a destra, giro anch'io…$"

Route119_Text_TaylorDefeat:
	.string "Ma se tu vinci, io perdo…$"

Route119_Text_TaylorPostBattle:
	.string "Non posso usare MIMICA per la vittoria.\n"
	.string "È semplicemente impossibile…\l"
	.string "Mi brucia dentro…$"

Route119_Text_DougIntro:
	.string "Sì, mi hai finalmente preso!\n"
	.string "O cercavi di evitarmi?$"

Route119_Text_DougDefeat:
	.string "Whoop, che bella lotta!$"

Route119_Text_DougPostBattle:
	.string "Siamo il CIRCOLO MIMICA!\n"
	.string "Spero che lo spettacolo ti sia piaciuto.$"

Route119_Text_GregIntro:
	.string "Non sai chi sono, vero?\p"
	.string "Ma anch'io non ti conosco.\n"
	.string "Quindi ci battiamo!$"

Route119_Text_GregDefeat:
	.string "Sei piuttosto forte!$"

Route119_Text_GregPostBattle:
	.string "Finché non te ne andrai via,\n"
	.string "continueremo a imitare ogni tua mossa.$"

Route119_Text_KentIntro:
	.string "Il CIRCOLO MIMICA è nato da gente\n"
	.string "a cui piace la MIMICA.\p"
	.string "La lotta inizia appena ci incontriamo!$"

Route119_Text_KentDefeat:
	.string "Mi arrendo!$"

Route119_Text_KentPostBattle:
	.string "Vuoi entrare nel nostro CIRCOLO MIMICA?$"

Route119_Text_JacksonIntro:
	.string "Chi ha la sapienza e\n"
	.string "la tecnica per sopravvivere?\p"
	.string "Gli RANGER POKéMON, ecco chi!$"

Route119_Text_JacksonDefeat:
	.string "Non avevo abbastanza\n"
	.string "esperienza…$"

Route119_Text_JacksonPostBattle:
	.string "Staccarsi dalla civiltà e\n"
	.string "risvegliare lo spirito selvaggio!\p"
	.string "Questa è la nostra visione.$"

Route119_Text_JacksonRegister:
	.string "Spero mi darai una rivincita senza\n"
	.string "deridere la mia mancanza di sapienza.$"

Route119_Text_JacksonRematchIntro:
	.string "Ritroverò il mio spirito selvaggio\n"
	.string "stando insieme ai POKéMON.$"

Route119_Text_JacksonRematchDefeat:
	.string "Sei rimasto forte!$"

Route119_Text_JacksonPostRematch:
	.string "Credi nei tuoi POKéMON.\n"
	.string "Credi in te stesso.\p"
	.string "La strada ti si rivelerà da sola.$"

Route119_Text_CatherineIntro:
	.string "Oh? Guarda un po'.\p"
	.string "Per uno in viaggio,\n"
	.string "porti davvero poco con te.$"

Route119_Text_CatherineDefeat:
	.string "Gli incidenti capitano se non sei\n"
	.string "preparato!$"

Route119_Text_CatherinePostBattle:
	.string "Porti poco, ma hai\n"
	.string "tutto il necessario.\p"
	.string "Sei in gamba sia di testa\n"
	.string "che di corpo.$"

Route119_Text_CatherineRegister:
	.string "Hai un POKéNAV?\n"
	.string "È indispensabile per ogni ALLENATORE.\p"
	.string "Oh, ce l'hai!\n"
	.string "Registriamoci a vicenda, allora!$"

Route119_Text_CatherineRematchIntro:
	.string "Come va il tuo viaggio con i POKéMON\n"
	.string "?$"

Route119_Text_CatherineRematchDefeat:
	.string "Mi manca ancora qualcosa…$"

Route119_Text_CatherinePostRematch:
	.string "Come tu, da ALLENATORE,\n"
	.string "conti sui tuoi POKéMON, i tuoi POKéMON\l"
	.string "contano su di te.$"

Route119_Text_HughIntro:
	.string "Il vasto cielo promette chissà cosa!\p"
	.string "Nulla si può paragonare al brivido\n"
	.string "puro del volo!$"

Route119_Text_HughDefeat:
	.string "K.O. totale!$"

Route119_Text_HughPostBattle:
	.string "I miei POKéMON UCCELLO hanno realizzato\n"
	.string "il mio sogno di volare!$"

Route119_Text_PhilIntro:
	.string "Ti mostrerò il vero potenziale mio\n"
	.string "e dei miei POKéMON UCCELLO!$"

Route119_Text_PhilDefeat:
	.string "Ci è mancato il potenziale…$"

Route119_Text_PhilPostBattle:
	.string "Fin da bambino ho sempre\n"
	.string "ammirato i POKéMON UCCELLO…$"

Route119_Text_YasuIntro:
	.string "Appostarmi nell'ombra, vivere\n"
	.string "nell'oscurità… Questo è il mio destino.\p"
	.string "Emergo per sfidarti!$"

Route119_Text_YasuDefeat:
	.string "Ammetto la sconfitta!$"

Route119_Text_YasuPostBattle:
	.string "Chi perde in battaglia si ritira\n"
	.string "in silenzio nell'ombra.\l"
	.string "Anche questo è destino…$"

Route119_Text_TakashiIntro:
	.string "Se non stai in guardia,\n"
	.string "ti aspetta un bel dolore!$"

Route119_Text_TakashiDefeat:
	.string "Sei sorprendentemente forte!$"

Route119_Text_TakashiPostBattle:
	.string "Il mio attacco a sorpresa è finito\n"
	.string "male…$"

Route119_Text_HideoIntro:
	.string "Per nascondere un albero, una foresta!$"

Route119_Text_HideoDefeat:
	.string "Mi inchino alla tua superiorità.$"

Route119_Text_HideoPostBattle:
	.string "Per nascondere un albero, una foresta!\n"
	.string "Per nascondere un POKéMON, un POKéMON!\p"
	.string "Non c'è alcun significato\n"
	.string "nascosto.$"

Route119_Text_ChrisIntro:
	.string "Mi hai parlato…\n"
	.string "Quindi vuoi sfidarmi!\p"
	.string "Certo! Proverò i POKéMON che ho preso\n"
	.string "mentre facevo SURF!$"

Route119_Text_ChrisDefeat:
	.string "Non ho idea di cosa\n"
	.string "serva per vincere.$"

Route119_Text_ChrisPostBattle:
	.string "Faccio SURF con il mio POKéMON…\p"
	.string "Poi pesco dalla sua schiena…\p"
	.string "È un momento di lusso indescrivibile!$"

Route119_Text_FabianIntro:
	.string "Colpiscimi con un power chord!\n"
	.string "La vittoria è mia!\l"
	.string "È il nostro momento, whoa, yeah!$"

Route119_Text_FabianDefeat:
	.string "Mi hai mostrato chi comanda!\n"
	.string "Dobbiamo accettare la sconfitta, oh, no!$"

Route119_Text_FabianPostBattle:
	.string "Colpiscimi con un altro power chord!\n"
	.string "Lasciami in pace!\l"
	.string "La tua vittoria devi espiare!$"

Route119_Text_DaytonIntro:
	.string "Hohoho!\n"
	.string "Mi piacciono gli ALLENATORI bambini!\l"
	.string "Facciamo una bella lotta!$"

Route119_Text_DaytonDefeat:
	.string "Sei davvero incredibile!\n"
	.string "Hohoho!$"

Route119_Text_DaytonPostBattle:
	.string "Hohoho!\n"
	.string "Proverò a imitare il brio degli\l"
	.string "ALLENATORI come te!$"

Route119_Text_RachelIntro:
	.string "Ovunque e in qualsiasi momento,\n"
	.string "ho sempre il parasole in mano.$"

Route119_Text_RachelDefeat:
	.string "Oh, ma…\n"
	.string "Non è giusto.$"

Route119_Text_RachelPostBattle:
	.string "Chiedi se il mio parasole è pesante?\n"
	.string "La tua BORSA è piena di più cianfrusaglie\l"
	.string "di quante ne porti mai io.$"

Route120_Text_ColinIntro:
	.string "Hai mosse capaci di colpire\n"
	.string "un POKéMON volante?$"

Route120_Text_ColinDefeat:
	.string "Mi hai superato in volo!$"

Route120_Text_ColinPostBattle:
	.string "La mossa VOLO è comoda,\n"
	.string "non trovi?\p"
	.string "Mentre il POKéMON vola,\n"
	.string "quasi nessuna mossa lo colpisce.$"

Route120_Text_RobertIntro:
	.string "Il mio POKéMON è forte!\n"
	.string "E il tuo?$"

Route120_Text_RobertDefeat:
	.string "I tuoi POKéMON erano più forti…$"

Route120_Text_RobertPostBattle:
	.string "Un POKéMON che cresce con costanza è\n"
	.string "uno su cui contare.$"

Route120_Text_RobertRegister:
	.string "Si può contare sul tuo miglioramento.\n"
	.string "Voglio registrarti nel POKéNAV!$"

Route120_Text_RobertRematchIntro:
	.string "Un POKéMON che cresce con costanza è\n"
	.string "uno su cui contare.$"

Route120_Text_RobertRematchDefeat:
	.string "I tuoi POKéMON sono davvero forti.$"

Route120_Text_RobertPostRematch:
	.string "I miei POKéMON diventano più forti.\n"
	.string "Devo crescere anch'io.$"

Route120_Text_LorenzoIntro:
	.string "Controllerò i tuoi POKéMON per vedere\n"
	.string "se sono adatti all'aperto.$"

Route120_Text_LorenzoDefeat:
	.string "Con POKéMON così forti non rischi\n"
	.string "di aver bisogno di soccorso!$"

Route120_Text_LorenzoPostBattle:
	.string "Viaggiare dove vuole il cuore\n"
	.string "con i POKéMON…\l"
	.string "Questa è la gioia di essere ALLENATORE.$"

Route120_Text_JennaIntro:
	.string "Come sei messo a fitness?\n"
	.string "Se non sei in forma, potresti fare\l"
	.string "fatica nelle situazioni critiche.$"

Route120_Text_JennaDefeat:
	.string "Sono in gran forma, però…$"

Route120_Text_JennaPostBattle:
	.string "L'allenamento fa parte della routine.\n"
	.string "Corro sempre coi miei POKéMON.$"

Route120_Text_JeffreyIntro:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Vuoi lottare?$"

Route120_Text_JeffreyDefeat:
	.string "Ho perso…$"

Route120_Text_JeffreyPostBattle:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Mi impegnerò di più…$"

Route120_Text_JeffreyRegister:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Hai un POKéNAV…?$"

Route120_Text_JeffreyRematchIntro:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Vuoi lottare ancora?$"

Route120_Text_JeffreyRematchDefeat:
	.string "… … … … … …\n"
	.string "Ho perso di nuovo…$"

Route120_Text_JeffreyPostRematch:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Mi impegnerò di più…\l"
	.string "Per i miei preziosi POKéMON COLEOTTERO…$"

Route120_Text_JenniferIntro:
	.string "I POKéMON hanno molte abilità speciali.\n"
	.string "Se vuoi diventare un ALLENATORE\l"
	.string "di primo livello, studiale.$"

Route120_Text_JenniferDefeat:
	.string "Si vede che ci stai pensando.$"

Route120_Text_JenniferPostBattle:
	.string "Le abilità speciali dei POKéMON\n"
	.string "cambiano gli stili di lotta.$"

Route120_Text_ChipIntro:
	.string "E tu chi saresti?\p"
	.string "Forse cerchi antiche rovine che,\n"
	.string "secondo la leggenda, potrebbero\l"
	.string "esistere davvero?$"

Route120_Text_ChipDefeat:
	.string "Che vergognosa battuta d'arresto…$"

Route120_Text_ChipPostBattle:
	.string "Quel macigno… Vorrei credere che\n"
	.string "contenga davvero antiche rovine.\l"
	.string "Ma non vedo alcun ingresso.$"

Route120_Text_ClarissaIntro:
	.string "Perché porto questo parasole?\p"
	.string "Te lo dico se riesci a battermi.$"

Route120_Text_ClarissaDefeat:
	.string "Un parasole non para gli attacchi\n"
	.string "dei POKéMON…$"

Route120_Text_ClarissaPostBattle:
	.string "Non credo che il sole forte faccia bene\n"
	.string "ai miei POKéMON.\l"
	.string "Perciò li schermo col parasole.$"

Route120_Text_AngelicaIntro:
	.string "Io, i POKéMON e il mio parasole…\p"
	.string "Se ne manca anche uno solo,\n"
	.string "il quadro di bellezza sarà rovinato.$"

Route120_Text_AngelicaDefeat:
	.string "Hai rovinato tutta la mia bellezza…$"

Route120_Text_AngelicaPostBattle:
	.string "Un parasole non ti si addice affatto.\p"
	.string "Anzi, una cosa così ti sarebbe solo\n"
	.string "d'intralcio.$"

Route120_Text_KeigoIntro:
	.string "Adotterò i movimenti dei POKéMON\n"
	.string "e creerò nuove tecniche ninja.$"

Route120_Text_KeigoDefeat:
	.string "Creare nuove tecniche ninja\n"
	.string "è solo un sogno lontano…$"

Route120_Text_KeigoPostBattle:
	.string "Forse dovrei fare apprendistato\n"
	.string "da un maestro ninja.$"

Route120_Text_RileyIntro:
	.string "Noi ninja ci nascondiamo sotto i\n"
	.string "mantelli mimetici.\l"
	.string "Scommetto che non sapevi dove fossi!$"

Route120_Text_RileyDefeat:
	.string "Ho perso!\n"
	.string "Devo camuffare la mia vergogna!$"

Route120_Text_RileyPostBattle:
	.string "I nostri mantelli mimetici sono tutti\n"
	.string "fatti a mano.$"

Route120_Text_CallieIntro:
	.string "Se non stai attento,\n"
	.string "potresti farti male!$"

Route120_Text_CallieDefeat:
	.string "Ahia!\n"
	.string "Sono stata io a farmi male.$"

Route120_Text_CalliePostBattle:
	.string "Chissà… Dovrei far evolvere i POKéMON?\n"
	.string "Però sono così carini come sono.$"

Route120_Text_LeonelIntro:
	.string "I POKéMON della tua squadra…\n"
	.string "Hanno tipi diversi?$"

Route120_Text_LeonelDefeat:
	.string "Ho visto la tua strategia in azione!$"

Route120_Text_LeonelPostBattle:
	.string "Trovo fantastico che tu sia così forte\n"
	.string "lottando coi POKéMON che ami.$"

Route121_Text_VanessaIntro:
	.string "Vuoi giocare con i miei POKéMON\n"
	.string "così graziosi?$"

Route121_Text_VanessaDefeat:
	.string "Non intendevo questo!$"

Route121_Text_VanessaPostBattle:
	.string "Vado a una GARA a LILYCOVE.\p"
	.string "I miei POKéMON vinceranno\n"
	.string "facilmente la CLASSE MASTER.$"

Route121_Text_WalterIntro:
	.string "Con i miei POKéMON ho girato\n"
	.string "i quattro angoli del mondo.\p"
	.string "Direi che ho fiducia\n"
	.string "nelle mie capacità.$"

Route121_Text_WalterDefeat:
	.string "Ah, ben giocato.$"

Route121_Text_WalterPostBattle:
	.string "Vorrei fare il giro del mondo\n"
	.string "ancora con i miei POKéMON.$"

Route121_Text_WalterRegister:
	.string "La tua abilità con i POKéMON è notevole.\n"
	.string "Lascia che ti registri come ricordo.$"

Route121_Text_WalterRematchIntro:
	.string "Con i miei POKéMON ho girato\n"
	.string "i quattro angoli del mondo.\p"
	.string "Direi che ho fiducia\n"
	.string "nelle mie capacità.$"

Route121_Text_WalterRematchDefeat:
	.string "Ah, ben giocato.$"

Route121_Text_WalterPostRematch:
	.string "I tuoi POKéMON e tu…\p"
	.string "Insieme siete forti,\n"
	.string "anche all'estero.$"

Route121_Text_TammyIntro:
	.string "Esistono poteri oltre la nostra\n"
	.string "comprensione in questo mondo…$"

Route121_Text_TammyDefeat:
	.string "Ho perso…$"

Route121_Text_TammyPostBattle:
	.string "MT. PYRE…\n"
	.string "Là agisce un potere\l"
	.string "misterioso…$"

Route121_Text_KateIntro:
	.string "KATE: Insieme non temiamo nulla!\n"
	.string "Ti mostreremo quanto siamo forti!$"

Route121_Text_KateDefeat:
	.string "KATE: Ho fatto brutta figura davanti alla\n"
	.string "mia compagna più giovane…$"

Route121_Text_KatePostBattle:
	.string "KATE: Quando qualcuno conta su di me,\n"
	.string "mi viene voglia di sembrare forte\l"
	.string "davanti a lui…$"

Route121_Text_KateNotEnoughMons:
	.string "KATE: Se hai un solo POKéMON,\n"
	.string "non possiamo combattere.\p"
	.string "Sarebbe prepotenza.$"

Route121_Text_JoyIntro:
	.string "JOY: Insieme non temiamo nulla!\n"
	.string "Ti mostreremo quanto siamo forti!$"

Route121_Text_JoyDefeat:
	.string "JOY: Perdonami, KATE!$"

Route121_Text_JoyPostBattle:
	.string "JOY: Ehehe, dovrò riallenarmi con KATE,\n"
	.string "la mia compagna più grande.$"

Route121_Text_JoyNotEnoughMons:
	.string "JOY: Ti servono almeno due POKéMON\n"
	.string "se vuoi sfidarci!$"

Route121_Text_JessicaIntro:
	.string "Fermo! Ammira i miei preziosi\n"
	.string "POKéMON!$"

Route121_Text_JessicaDefeat:
	.string "Oh, come osi!\n"
	.string "Non prendertela troppo!$"

Route121_Text_JessicaPostBattle:
	.string "Forse andrò a prendere altri POKéMON al\n"
	.string "PARCHI SAFARI.$"

Route121_Text_JessicaRegister:
	.string "Stavolta sono stata clemente!\n"
	.string "La prossima volta non sarà così!$"

Route121_Text_JessicaRematchIntro:
	.string "I miei preziosi POKéMON sono cresciuti!\n"
	.string "Ammirali bene!$"

Route121_Text_JessicaRematchDefeat:
	.string "Oh, come osi!\n"
	.string "Non sei ancora clemente!$"

Route121_Text_JessicaPostRematch:
	.string "Forse andrò a prendere altri POKéMON al\n"
	.string "PARCHI SAFARI.$"

Route121_Text_CristinIntro:
	.string "Ho la mia routine.\n"
	.string "Batto cinque ALLENATORI al giorno.\l"
	.string "Indovina? Sei il numero cinque!$"

Route121_Text_CristinDefeat:
	.string "No!\n"
	.string "Sei odioso!$"

Route121_Text_CristinPostBattle:
	.string "Non pensavo di perdere così facilmente…\n"
	.string "La prossima volta vinco!$"

Route121_Text_CristinRegister:
	.string "Che umiliazione!\n"
	.string "Non ti dimenticherò…\l"
	.string "Dammi il tuo POKéNAV!$"

Route121_Text_CristinRematchIntro:
	.string "Ho una nuova routine.\n"
	.string "Batto dieci ALLENATORI al giorno.\l"
	.string "Indovina? Sei il numero dieci!$"

Route121_Text_CristinRematchDefeat:
	.string "Aspetta! Che sgarbo!\n"
	.string "Esigo la rivincita!$"

Route121_Text_CristinPostRematch:
	.string "Un rivale che proprio non batto…\n"
	.string "Sniff…\l"
	.string "Non ci credo che stia succedendo…$"

Route121_Text_CaleIntro:
	.string "Non vedi che ho tutta questa\n"
	.string "roba con me?\p"
	.string "Eppure insisti comunque per\n"
	.string "combattere?$"

Route121_Text_CaleDefeat:
	.string "Certo che ho perso!\n"
	.string "Ho le mani piene di roba!$"

Route121_Text_CalePostBattle:
	.string "Ho comprato troppa roba al\n"
	.string "CENTRO COMMERCIALE di PORTOVIVO.\p"
	.string "È su per la strada.\n"
	.string "Vorrei una BORSA come la tua.$"

Route121_Text_MylesIntro:
	.string "Non c'è nulla che ami più di\n"
	.string "guardare i POKéMON altrui!$"

Route121_Text_MylesDefeat:
	.string "Troppo forte!$"

Route121_Text_MylesPostBattle:
	.string "Sono grandi, i tuoi POKéMON!\n"
	.string "Come li alleni?$"

Route121_Text_PatIntro:
	.string "Voglio che tutti vedano i POKéMON\n"
	.string "che ho allevato!$"

Route121_Text_PatDefeat:
	.string "Wow!\n"
	.string "Spettacolare!$"

Route121_Text_PatPostBattle:
	.string "Alleno ogni POKéMON con lo stesso\n"
	.string "amore, senza preferenze.$"

Route121_Text_MarcelIntro:
	.string "I miei POKéMON non hanno mai perso!\n"
	.string "Alla prossima vittoria li iscrivo\l"
	.string "alle GARE.$"

Route121_Text_MarcelDefeat:
	.string "Oh, ma cosa è successo qui?$"

Route121_Text_MarcelPostBattle:
	.string "Dovrò allenare di più la squadra\n"
	.string "prima di iscriverla a una GARA.$"

Route123_Text_WendyIntro:
	.string "Vuoi sapere quanto sei forte?\n"
	.string "Sarò io il test!$"

Route123_Text_WendyDefeat:
	.string "Promosso a pieni voti!$"

Route123_Text_WendyPostBattle:
	.string "Battere persino me…\n"
	.string "La tua forza è meravigliosa!$"

Route123_Text_BraxtonIntro:
	.string "Sembra che tu abbia una bella collezione\n"
	.string "di MEDAGLIE.\p"
	.string "Vediamo se sei davvero all'altezza di\n"
	.string "quelle MEDAGLIE!$"

Route123_Text_BraxtonDefeat:
	.string "Oh, sei davvero all'altezza!$"

Route123_Text_BraxtonPostBattle:
	.string "In quella lotta hai reso onore alle tue\n"
	.string "MEDAGLIE!$"

Route123_Text_VioletIntro:
	.string "Dicono che i bei momenti siano\n"
	.string "pieni di buoni profumi.$"

Route123_Text_VioletDefeat:
	.string "Oh…\n"
	.string "Sento l'odore amaro della sconfitta…$"

Route123_Text_VioletPostBattle:
	.string "Il giardino del BERRY MASTER è pieno\n"
	.string "di fragranze che tirano su il morale.$"

Route123_Text_CameronIntro:
	.string "Essere psichici è questione di volontà.\p"
	.string "Ho voluto non perdere mai\n"
	.string "con nessuno. Questo mi rende forte!$"

Route123_Text_CameronDefeat:
	.string "Mi sento triste…$"

Route123_Text_CameronPostBattle:
	.string "Essere psichici è questione di volontà.\n"
	.string "Credevo di non perdere contro di te…$"

Route123_Text_CameronRegister:
	.string "Lo sento!\n"
	.string "Noi due ci batteremo ancora!\l"
	.string "Non so se vincerò, però…\p"
	.string "Mostrami il POKéNAV.$"

Route123_Text_CameronRematchIntro:
	.string "Mi sono convinto che non\n"
	.string "perderò più. Questo mi rende forte!$"

Route123_Text_CameronRematchDefeat:
	.string "Mi sento triste…$"

Route123_Text_CameronPostRematch:
	.string "Dovrei allenarmi al MT. PYRE…\n"
	.string "Così non ti batterò mai…$"

Route123_Text_JackiIntro:
	.string "Non esultare se i tuoi POKéMON\n"
	.string "sviluppano poteri psichici.\p"
	.string "Devi affinarli, quei poteri,\n"
	.string "per renderli davvero utili.$"

Route123_Text_JackiDefeat:
	.string "Sopraffatto!$"

Route123_Text_JackiPostBattle:
	.string "Tutti abbiamo poteri psichici.\n"
	.string "Ci siamo solo dimenticati come si usano.$"

Route123_Text_JackiRegister:
	.string "Vorrei sfidarti di nuovo.\n"
	.string "Per te va bene?$"

Route123_Text_JackiRematchIntro:
	.string "Hai risvegliato i poteri psichici\n"
	.string "che hai dentro?$"

Route123_Text_JackiRematchDefeat:
	.string "Sbalorditivo!$"

Route123_Text_JackiPostRematch:
	.string "Il tuo legame coi POKéMON…\n"
	.string "Potrebbe essere un potere psichico.$"

Route123_Text_MiuIntro:
	.string "MIU: Ciao, ALLENATORE. Spero che i tuoi\n"
	.string "POKéMON non piangano se perdono.$"

Route123_Text_MiuDefeat:
	.string "MIU: Oh-oh, abbiamo perso.$"

Route123_Text_MiuPostBattle:
	.string "MIU: ALLENATORE, i tuoi POKéMON sono\n"
	.string "forti perché siete amici.$"

Route123_Text_MiuNotEnoughMons:
	.string "MIU: Lottare non è divertente se\n"
	.string "non hai due POKéMON.$"

Route123_Text_YukiIntro:
	.string "YUKI: Ok!\n"
	.string "Battiamo i POKéMON dell'ALLENATORE!$"

Route123_Text_YukiDefeat:
	.string "YUKI: Oh-oh, abbiamo perso.$"

Route123_Text_YukiPostBattle:
	.string "YUKI: Perché sei così forte?\n"
	.string "Non avevamo mai perso prima.$"

Route123_Text_YukiNotEnoughMons:
	.string "YUKI: Lottare non è divertente se\n"
	.string "non hai due POKéMON.$"

Route123_Text_KindraIntro:
	.string "MT. PYRE…\n"
	.string "Dove dormono gli spiriti dei POKéMON…\l"
	.string "I tuoi POKéMON dormiranno?$"

Route123_Text_KindraDefeat:
	.string "Traboccante di vitalità…$"

Route123_Text_KindraPostBattle:
	.string "MT. PYRE…\n"
	.string "Dove dormono gli spiriti dei POKéMON…\p"
	.string "Deve traboccare di un potere\n"
	.string "che calma gli spiriti…$"

Route123_Text_FernandoIntro:
	.string "Ti spengo le luci mentre\n"
	.string "suono questa melodia!$"

Route123_Text_FernandoDefeat:
	.string "Ehi, aspetta!\n"
	.string "Stavo ancora suonando l'intro!$"

Route123_Text_FernandoPostBattle:
	.string "Sei una roccia.\n"
	.string "Vorrei scrivere una canzone su di te.$"

Route123_Text_FernandoRegister:
	.string "La prossima volta, ascolta\n"
	.string "la canzone intera, ok?$"

Route123_Text_FernandoRematchIntro:
	.string "Oggi è il giorno giusto!\n"
	.string "Ti spegnerò le luci prima\l"
	.string "di finire di cantare la mia canzone!$"

Route123_Text_FernandoRematchDefeat:
	.string "Ehi, aspetta!\n"
	.string "Non sono ancora al ritornello!$"

Route123_Text_FernandoPostRematch:
	.string "Credevo che la mia melodia\n"
	.string "ti avrebbe incantato al punto da perdere.$"

Route123_Text_DavisIntro:
	.string "Questo è il mio fantastico coleottero!\n"
	.string "Me l'ha preso mio fratello maggiore.$"

Route123_Text_DavisDefeat:
	.string "Waaaah!\n"
	.string "Sei cattivo!$"

Route123_Text_DavisPostBattle:
	.string "Non dire a mio fratello che ho perso.\n"
	.string "Devi tenere il segreto!$"

Route123_Text_JazmynIntro:
	.string "Battere uno forte mi darà\n"
	.string "una bella carica di fiducia!$"

Route123_Text_JazmynDefeat:
	.string "Addio fiducia in me stessa…$"

Route123_Text_JazmynPostBattle:
	.string "Dicono che non si giudica una persona\n"
	.string "dall'aspetto.\p"
	.string "Ma spesso l'aspetto non mente…$"

Route123_Text_FrederickIntro:
	.string "Ciao, bambino!\n"
	.string "Hai un po' di tempo?$"

Route123_Text_FrederickDefeat:
	.string "Ah, che bambino capace!\n"
	.string "Lascia che ti contribuisca la paghetta.$"

Route123_Text_FrederickPostBattle:
	.string "Contribuire alla tua paghetta?\n"
	.string "Il premio non bastava?$"

Route123_Text_AlbertoIntro:
	.string "Devo dirtelo, i POKéMON UCCELLO\n"
	.string "sono la mia ossessione!\p"
	.string "Gli uccelli son forti!\n"
	.string "Sono i migliori!$"

Route123_Text_AlbertoDefeat:
	.string "Even in defeat, BIRD POKéMON are cool!$"

Route123_Text_AlbertoPostBattle:
	.string "Raccolgo le piume dei POKéMON UCCELLO\n"
	.string "che cadono in lotta.\p"
	.string "Farò un cappello con\n"
	.string "le piume dei POKéMON UCCELLO.$"

Route123_Text_EdIntro:
	.string "Quando non c'è nessun ALLENATORE,\n"
	.string "faccio lottare i miei POKéMON tra loro.\l"
	.string "Li osservo.$"

Route123_Text_EdDefeat:
	.string "Il tuo POKéMON mi piace un po'.$"

Route123_Text_EdPostBattle:
	.string "Eh eh, ti rubo le tattiche di lotta!\n"
	.string "Penso che mi miglioreranno.$"

Route123_Text_JonasIntro:
	.string "Ero in agguato, e un ALLENATORE\n"
	.string "è caduto nella mia trappola!$"

Route123_Text_JonasDefeat:
	.string "Se non perdi mai, come faccio\n"
	.string "a divertirmi a fare il ninja?$"

Route123_Text_JonasPostBattle:
	.string "La prossima volta tendo un'imboscata\n"
	.string "a un ALLENATORE più debole.$"

Route123_Text_KayleyIntro:
	.string "Ho appena comprato questo parasole.\n"
	.string "La mia tenerezza sale di un terzo!$"

Route123_Text_KayleyDefeat:
	.string "Sei più forte di me\n"
	.string "tipo cinque volte!$"

Route123_Text_KayleyPostBattle:
	.string "Usare bene gli accessori è\n"
	.string "il segreto del fascino.$"

Route124_Text_SpencerIntro:
	.string "Ehi, ti sei perso in mare?\p"
	.string "Se batti i miei POKéMON,\n"
	.string "posso farti da timoniere.$"

Route124_Text_SpencerDefeat:
	.string "Ho perso la rotta nella lotta!$"

Route124_Text_SpencerPostBattle:
	.string "Molti perdono la rotta in mare.\p"
	.string "Se sei uno di quelli, guarda\n"
	.string "la MAPPA del POKéNAV.$"

Route124_Text_RolandIntro:
	.string "Hm! Cavalchi un POKéMON invece\n"
	.string "di nuotare tu…\p"
	.string "Che invidia!$"

Route124_Text_RolandDefeat:
	.string "Oh!\n"
	.string "Non ce la faccio…$"

Route124_Text_RolandPostBattle:
	.string "Sto prendendo freddo…\n"
	.string "Sono stato troppo in acqua…\p"
	.string "Vorrei cavalcare un POKéMON come te…$"

Route124_Text_JennyIntro:
	.string "Se resti a galla nel mare così,\n"
	.string "i POKéMON si avvicinano a giocare.$"

Route124_Text_JennyDefeat:
	.string "Oh, no…\n"
	.string "Ho perso, ecco.$"

Route124_Text_JennyPostBattle:
	.string "Nuotando ho notato che alcuni\n"
	.string "POKéMON attaccano e altri guardano.\p"
	.string "Forse i POKéMON hanno carattere\n"
	.string "tutto loro.$"

Route124_Text_JennyRegister:
	.string "È solo un capriccio, ma forse\n"
	.string "ti farò registrare sul POKéNAV.$"

Route124_Text_JennyRematchIntro:
	.string "Se resti a galla nel mare così,\n"
	.string "gli ALLENATORI ti sfidano!$"

Route124_Text_JennyRematchDefeat:
	.string "Strano…\n"
	.string "Ho perso di nuovo…$"

Route124_Text_JennyPostRematch:
	.string "Non c'entra niente, ma forse\n"
	.string "visiterò la TRICK HOUSE.$"

Route124_Text_GraceIntro:
	.string "Mi sto stancando di nuotare…\n"
	.string "Ti va una lotta?$"

Route124_Text_GraceDefeat:
	.string "Non avevo idea che fossi\n"
	.string "così forte!$"

Route124_Text_GracePostBattle:
	.string "Tutto l'impegno che ci hai messo\n"
	.string "ti ha reso così forte.$"

Route124_Text_ChadIntro:
	.string "Fufufufu… mi immergo in profondità\n"
	.string "per agire in incognito.\l"
	.string "Scandagliare gli abissi è il mio forte!$"

Route124_Text_ChadDefeat:
	.string "Glub, glub, glub…\n"
	.string "Sto affondando…$"

Route124_Text_ChadPostBattle:
	.string "So per certo che\n"
	.string "da queste parti c'è un punto SUB.\p"
	.string "Mi viene voglia di andare\n"
	.string "di nuovo a fondo…$"

Route124_Text_LilaIntro:
	.string "LILA: Sigh…\p"
	.string "Eccomi nel mare, ma chi mi sta accanto?\n"
	.string "Mio fratellino!\p"
	.string "Lottiamo, così non ci penso\n"
	.string "più!$"

Route124_Text_LilaDefeat:
	.string "LILA: ROY! È colpa tua se abbiamo perso!\n"
	.string "Dopo ti sistemo!$"

Route124_Text_LilaPostBattle:
	.string "LILA: Sigh…\p"
	.string "Se solo al posto mio ci fosse\n"
	.string "un bel fidanzato…$"

Route124_Text_LilaNotEnoughMons:
	.string "LILA: Vuoi sfidarci?\n"
	.string "Solo se hai due POKéMON.$"

Route124_Text_RoyIntro:
	.string "ROY: Mia sorella è forte coi POKéMON!\p"
	.string "Non piangere se perdi!$"

Route124_Text_RoyDefeat:
	.string "ROY: Uh-oh…\n"
	.string "Mia sorella mi sgriderà…$"

Route124_Text_RoyPostBattle:
	.string "ROY: Mia sorella fa davvero paura\n"
	.string "quando si arrabbia.\p"
	.string "Ecco perché non ha un\n"
	.string "fidanzato.$"

Route124_Text_LilaRoyRegister:
	.string "ROY: Ci sfiderai di nuovo?\n"
	.string "Ma vai piano la prossima volta, ok?$"

Route124_Text_RoyNotEnoughMons:
	.string "ROY: Volevi sfidarci?\n"
	.string "Porta due POKéMON, allora.$"

Route124_Text_LilaRematchIntro:
	.string "LILA: Sigh…\p"
	.string "Eccomi nel mare, ma chi mi sta accanto?\n"
	.string "Mio fratellino!\p"
	.string "Oh, ciao, è da un po'. Lottiamo,\n"
	.string "così non ci penso più!$"

Route124_Text_LilaRematchDefeat:
	.string "LILA: ROY!\n"
	.string "È colpa tua se abbiamo perso di nuovo!\p"
	.string "Dopo ci alleniamo!$"

Route124_Text_LilaPostRematch:
	.string "LILA: Sigh…\p"
	.string "Con un bel fidanzato batteremmo\n"
	.string "tutti con belle combinazioni…$"

Route124_Text_LilaRematchNotEnoughMons:
	.string "LILA: Vuoi sfidarci?\n"
	.string "Solo se hai due POKéMON.$"

Route124_Text_RoyRematchIntro:
	.string "ROY: Se perdiamo, sono guai.\n"
	.string "Darò davvero il massimo!$"

Route124_Text_RoyRematchDefeat:
	.string "ROY: Uh-oh…\n"
	.string "Mia sorella mi sgriderà di nuovo.$"

Route124_Text_RoyPostRematch:
	.string "ROY: Mia sorella fa davvero paura\n"
	.string "quando si arrabbia.\p"
	.string "Dopo mi farà allenare\n"
	.string "duro coi POKéMON…$"

Route124_Text_RoyRematchNotEnoughMons:
	.string "ROY: Volevi sfidarci?\n"
	.string "Porta due POKéMON, allora.$"

Route124_Text_DeclanIntro:
	.string "Eccomi a nuotare tutto solo\n"
	.string "su questo mare ampio e bellissimo.\p"
	.string "Non c'è altro modo per dirlo.\n"
	.string "Che pena che faccio!$"

Route124_Text_DeclanDefeat:
	.string "Mi sento giù.\n"
	.string "Giù come il cielo…$"

Route124_Text_DeclanPostBattle:
	.string "Dovrei approcciare le nuotatrici\n"
	.string "e invitarle a una lunga nuotata.$"

Route124_Text_IsabellaIntro:
	.string "Non perderò contro un\n"
	.string "ALLENATORE surfista.$"

Route124_Text_IsabellaDefeat:
	.string "Ho solo sudore negli occhi!\n"
	.string "Non sto piangendo!$"

Route124_Text_IsabellaPostBattle:
	.string "Qui in giro si trovano belle\n"
	.string "schegge colorate.$"

Route125_Text_NolenIntro:
	.string "Ti ho sentito arrivare, così ti ho\n"
	.string "aspettato!$"

Route125_Text_NolenDefeat:
	.string "Mi arrendo!$"

Route125_Text_NolenPostBattle:
	.string "Il suono viaggia più veloce nell'acqua\n"
	.string "che nell'aria.$"

Route125_Text_StanIntro:
	.string "Ehi, ciao!\n"
	.string "Guarda che bei POKéMON ho!$"

Route125_Text_StanDefeat:
	.string "Sono affondato…$"

Route125_Text_StanPostBattle:
	.string "Il fascino di HORSEA mi ha conquistato,\n"
	.string "così ho iniziato a nuotare anch'io.$"

Route125_Text_TanyaIntro:
	.string "Sono stanca di nuotare.\n"
	.string "Ti va una lotta con me?$"

Route125_Text_TanyaDefeat:
	.string "Sei troppo forte!$"

Route125_Text_TanyaPostBattle:
	.string "Uff…\n"
	.string "Da che parte si va a MOSSDEEP?$"

Route125_Text_SharonIntro:
	.string "Ti va di sfidare i POKéMON di tipo\n"
	.string "ACQUA che ho allevato?$"

Route125_Text_SharonDefeat:
	.string "Ho perso…$"

Route125_Text_SharonPostBattle:
	.string "Che forza… Sei davvero in gamba.\n"
	.string "Sono stupita!$"

Route125_Text_ErnestIntro:
	.string "Ahoy! Sono un MARINAIO robusto!\n"
	.string "Ho sfidato i mari del mondo!$"

Route125_Text_ErnestDefeat:
	.string "Gwrroooar!\n"
	.string "Non ho potuto vincere!$"

Route125_Text_ErnestPostBattle:
	.string "La marea sale e scende nella\n"
	.string "GROTTA SHOAL.\p"
	.string "A proposito, passano circa sei ore\n"
	.string "dall'alta alla bassa marea. Lo sapevi?$"

Route125_Text_ErnestRegister:
	.string "Registrami sul POKéNAV,\n"
	.string "e ti dirò una cosa utile.$"

Route125_Text_ErnestRematchIntro:
	.string "È ora che mi prenda la rivincita\n"
	.string "su di te! Forza, si combatte!$"

Route125_Text_ErnestRematchDefeat:
	.string "Non ho potuto vincere!\n"
	.string "Proprio non ho potuto vincere!$"

Route125_Text_ErnestRematchPostBattle:
	.string "La GROTTA SHOAL…\p"
	.string "Ci sono posti dove puoi arrivare e\n"
	.string "altri no, a seconda dell'alta e bassa\l"
	.string "marea.\p"
	.string "A proposito, passano circa sei ore\n"
	.string "dall'alta alla bassa marea. Non scordarlo!$"

Route125_Text_KimIntro:
	.string "KIM: Nella GROTTA SHOAL vive un\n"
	.string "vecchietto buffo. Me l'hanno detto.\l"
	.string "Vai a vederlo anche tu?$"

Route125_Text_KimDefeat:
	.string "KIM: Credevo che avremmo vinto.$"

Route125_Text_KimPostBattle:
	.string "KIM: Nella GROTTA SHOAL vive un\n"
	.string "vecchietto buffo, vero?\p"
	.string "Andiamo a vederlo, IRIS!$"

Route125_Text_KimNotEnoughMons:
	.string "KIM: No, no, no! Ti servono due POKéMON,\n"
	.string "o non vale proprio!$"

Route125_Text_IrisIntro:
	.string "IRIS: KIM, mi dici cosa stiamo\n"
	.string "cercando qui fuori?$"

Route125_Text_IrisDefeat:
	.string "IRIS: Oh, ci siamo andati vicini.$"

Route125_Text_IrisPostBattle:
	.string "IRIS: KIM, entriamo davvero nella\n"
	.string "GROTTA SHOAL?\l"
	.string "Ci bagneremo tutte.$"

Route125_Text_IrisNotEnoughMons:
	.string "IRIS: Oh, non faremmo mai e poi mai\n"
	.string "una lotta 2 contro 1.$"

Route125_Text_PresleyIntro:
	.string "Perché uno come me, ORNITOLOGO,\n"
	.string "viene fin qui al mare?$"

Route125_Text_PresleyDefeat:
	.string "Okay.\n"
	.string "Ti dico perché sono qui.$"

Route125_Text_PresleyPostBattle:
	.string "Ho messo un messaggio in una bottiglia\n"
	.string "e l'ho buttata in mare.\p"
	.string "Sono certo che una RAGAZZA NUOTATRICE\n"
	.string "lo troverà!$"

Route125_Text_AuronIntro:
	.string "Ehi! Sei tu che gettavi spazzatura\n"
	.string "in mare?$"

Route125_Text_AuronDefeat:
	.string "Oh, non stavi buttando rifiuti\n"
	.string "in mare.$"

Route125_Text_AuronPostBattle:
	.string "Prima ho trovato una brutta bottiglia\n"
	.string "tra le onde.\p"
	.string "Mi fa arrabbiare chi\n"
	.string "inquina il mare!$"

Route126_Text_BarryIntro:
	.string "Nuotare allena tutto il corpo!\n"
	.string "Ti farà stare in forma!$"

Route126_Text_BarryDefeat:
	.string "Lo ammetto!\n"
	.string "Hai vinto!$"

Route126_Text_BarryPostBattle:
	.string "Grazie ai miei allenamenti quotidiani…\n"
	.string "Guarda! Che fisico da ammirare!$"

Route126_Text_DeanIntro:
	.string "Questa imponente montagna bianca\n"
	.string "di roccia è SOOTOPOLIS.$"

Route126_Text_DeanDefeat:
	.string "Mi hai battuto?$"

Route126_Text_DeanPostBattle:
	.string "Non trovo l'ingresso di\n"
	.string "SOOTOPOLIS. Dove sarà?$"

Route126_Text_NikkiIntro:
	.string "Ufufufufu!\n"
	.string "Sono una sirena!$"

Route126_Text_NikkiDefeat:
	.string "Il mio sogno è scoppiato come una bolla!\n"
	.string "Blub, blub, blub…$"

Route126_Text_NikkiPostBattle:
	.string "Mi hai stracciata… Voglio\n"
	.string "sparire in un'onda di disperazione…$"

Route126_Text_BrendaIntro:
	.string "Ciao, piccolo!\n"
	.string "Vuoi lottare con me?$"

Route126_Text_BrendaDefeat:
	.string "Oh, nooooh!$"

Route126_Text_BrendaPostBattle:
	.string "Adoro giocare con i POKéMON nel\n"
	.string "mare, così!$"

Route126_Text_PabloIntro:
	.string "Guarda che fisico scolpito!\n"
	.string "Sono più scolpito di un BLACK BELT!$"

Route126_Text_PabloDefeat:
	.string "Ops! Troppo forte!\n"
	.string "Mica male! Mica male!$"

Route126_Text_PabloPostBattle:
	.string "Perdere con te mi ha acceso i sensi!\n"
	.string "Mi allenerò io e i POKéMON di più!$"

Route126_Text_PabloRegister:
	.string "Già, mica male davvero!\n"
	.string "Vorrei conoscerti meglio!$"

Route126_Text_PabloRematchIntro:
	.string "Guarda che fisico stupendo!\n"
	.string "Sono più in forma di un NUOTATORE!$"

Route126_Text_PabloRematchDefeat:
	.string "Ops! Davvero troppo forte!\n"
	.string "Mica male! Mica male!$"

Route126_Text_PabloPostRematch:
	.string "Mi allenerò ancora più duramente!\n"
	.string "Sei un grande motivatore!\l"
	.string "Devi tornare a trovarmi!$"

Route126_Text_LeonardoIntro:
	.string "L'anno scorso non sapevo nuotare,\n"
	.string "ora sono un NUOTATORE decente.\p"
	.string "Credo di saper fare qualsiasi cosa.$"

Route126_Text_LeonardoDefeat:
	.string "Uffa, con l'ingordigia non ho\n"
	.string "concluso niente.$"

Route126_Text_LeonardoPostBattle:
	.string "Se ti alleni in qualcosa,\n"
	.string "migliori.\p"
	.string "Sei giovane, non aver paura di\n"
	.string "provare di tutto!$"

Route126_Text_IsobelIntro:
	.string "Se ti va l'acqua di mare nel naso,\n"
	.string "non è terribile?$"

Route126_Text_IsobelDefeat:
	.string "Ah! Ma come…\n"
	.string "Glub!$"

Route126_Text_IsobelPostBattle:
	.string "Ooh, ho bevuto l'acqua!\n"
	.string "È amara! È salata!!$"

Route126_Text_SiennaIntro:
	.string "Ci sto mettendo tutto il cuore\n"
	.string "in questo!$"

Route126_Text_SiennaDefeat:
	.string "Ci hai messo più cuore!$"

Route126_Text_SiennaPostBattle:
	.string "Ora devo rinfrescarmi…\n"
	.string "Penso che andrò a fare un'immersione.$"

Route127_Text_CamdenIntro:
	.string "Si legge in faccia.\n"
	.string "Vuoi sfidarmi.$"

Route127_Text_CamdenDefeat:
	.string "Aaah… aaah… ah…$"

Route127_Text_CamdenPostBattle:
	.string "Una bella sfida mi lascia\n"
	.string "rinfrescato e tranquillo.$"

Route127_Text_DonnyIntro:
	.string "Hai un rivale contro cui\n"
	.string "odi perdere?$"

Route127_Text_DonnyDefeat:
	.string "Arrrgh!\n"
	.string "Odio perdere!$"

Route127_Text_DonnyPostBattle:
	.string "Se hai un rivale, non ti viene\n"
	.string "la sensazione di dover migliorare\l"
	.string "sempre di più?$"

Route127_Text_JonahIntro:
	.string "Pescando ho raggiunto uno\n"
	.string "stato di quiete serena…\p"
	.string "Ti prego, lasciami mostrare…$"

Route127_Text_JonahDefeat:
	.string "Ho perso, ma il cuore resta\n"
	.string "calmo…$"

Route127_Text_JonahPostBattle:
	.string "Non importa se non prendo nulla.\n"
	.string "La lenza resta nell'acqua…$"

Route127_Text_HenryIntro:
	.string "Ops! Non dirmi che ho preso\n"
	.string "un POKéMON SURF?$"

Route127_Text_HenryDefeat:
	.string "Non riesco a starti dietro!$"

Route127_Text_HenryPostBattle:
	.string "Sarebbe un bel problema se\n"
	.string "abboccasse il tuo POKéMON forte!$"

Route127_Text_RogerIntro:
	.string "Ehi! Questa è una sfida tra\n"
	.string "un fan dei POKéMON e un pescatore!$"

Route127_Text_RogerDefeat:
	.string "No! La lenza è tutta aggrovigliata!\n"
	.string "La festa è finita!$"

Route127_Text_RogerPostBattle:
	.string "La mia lenza balla!\n"
	.string "Il tango dei nodi! Ahahah, che urlo!$"

Route127_Text_AidanIntro:
	.string "I POKéMON UCCELLO hanno una vista\n"
	.string "ottima. Vedono le prede dall'alto.$"

Route127_Text_AidanDefeat:
	.string "Uff… mi arrendo.$"

Route127_Text_AidanPostBattle:
	.string "Ci sono molti punti d'immersione\n"
	.string "nel mare qui intorno.\p"
	.string "Si vedono bene dal cielo\n"
	.string "per il loro colore scuro.$"

Route127_Text_KojiIntro:
	.string "Corri a piedi nudi.\n"
	.string "Ti indurirà le piante!$"

Route127_Text_KojiDefeat:
	.string "Ahia!\n"
	.string "Ho un sassolino sotto l'unghia!$"

Route127_Text_KojiPostBattle:
	.string "A piedi nudi si sta benissimo.\n"
	.string "Ma le tue SCARPE DA GINNASTICA son belle.$"

Route127_Text_KojiRegister:
	.string "Ecco cosa faccio a chi mi batte!\n"
	.string "Spero di rifarlo presto.$"

Route127_Text_KojiRematchIntro:
	.string "Corro ancora a piedi nudi.\n"
	.string "Ho le piante dure!$"

Route127_Text_KojiRematchDefeat:
	.string "Ahia!\n"
	.string "Sassolini sotto le piante!$"

Route127_Text_KojiPostRematch:
	.string "Vuoi andare a piedi nudi un po'?\n"
	.string "Così provo le tue SCARPE DA GINNASTICA?$"

Route127_Text_AthenaIntro:
	.string "Dovremmo fare una sfida lenta\n"
	.string "e metodica.$"

Route127_Text_AthenaDefeat:
	.string "Non mi hai dato il tempo di\n"
	.string "studiare una strategia.$"

Route127_Text_AthenaPostBattle:
	.string "Quando sono tra il mare blu\n"
	.string "e il cielo, il tempo sembra rallentare.$"

Route128_Text_IsaiahIntro:
	.string "EVER GRANDE è ancora lontana\n"
	.string "da qui…$"

Route128_Text_IsaiahDefeat:
	.string "La mia prima vittoria sembra ancora\n"
	.string "lontana…$"

Route128_Text_IsaiahPostBattle:
	.string "Ho sempre perso per tutta la vita,\n"
	.string "ma non mi arrenderò mai!$"

Route128_Text_IsaiahRegister:
	.string "So di non essere forte ora, ma credo\n"
	.string "che prima o poi vincerò.\p"
	.string "Registrami sul POKéNAV, per favore.$"

Route128_Text_IsaiahRematchIntro:
	.string "Sto ancora bene. Continuerò a\n"
	.string "nuotare verso EVER GRANDE.$"

Route128_Text_IsaiahRematchDefeat:
	.string "Non ho ancora assaporato la vittoria…$"

Route128_Text_IsaiahPostRematch:
	.string "Prima o poi raggiungerò EVER GRANDE,\n"
	.string "dove prima o poi vincerò…$"

Route128_Text_KatelynIntro:
	.string "In un triathlon nuoti, vai in bici\n"
	.string "e poi corri una maratona.\p"
	.string "È una gara sfiancante fatta\n"
	.string "di tre prove.$"

Route128_Text_KatelynDefeat:
	.string "Anche una lotta POKéMON è sfiancante…$"

Route128_Text_KatelynPostBattle:
	.string "Ora dovrei andare in BICICLETTA, ma…\n"
	.string "sto per gettare la spugna…$"

Route128_Text_KatelynRegister:
	.string "Beh, tanto vale approfittarne.\n"
	.string "Mi piacerebbe una rivincita.$"

Route128_Text_KatelynRematchIntro:
	.string "Un triathlon è lungo. Ma anche la\n"
	.string "strada per diventare CAMPIONE\l"
	.string "POKéMON è lunga e sfiancante.$"

Route128_Text_KatelynRematchDefeat:
	.string "Una lotta POKéMON è davvero dura\n"
	.string "e implacabile…$"

Route128_Text_KatelynPostRematch:
	.string "Dovresti riflettere seriamente sulle\n"
	.string "sfide sulla VIA VITTORIA.$"

Route128_Text_AlexaIntro:
	.string "Ci stiamo impegnando per affrontare\n"
	.string "la sfida della LEGA POKéMON…\p"
	.string "Non possiamo perdere ora!$"

Route128_Text_AlexaDefeat:
	.string "Oh!\n"
	.string "Come è potuto succedere?!$"

Route128_Text_AlexaPostBattle:
	.string "Dopo tutto ciò che ho fatto per arrivare,\n"
	.string "non mi arrendo per una sconfitta.$"

Route128_Text_RubenIntro:
	.string "Non esiste ALLENATORE più forte di me!$"

Route128_Text_RubenDefeat:
	.string "Non è possibile!$"

Route128_Text_RubenPostBattle:
	.string "Probabilmente non esiste ALLENATORE\n"
	.string "più forte di te!$"

Route128_Text_WayneIntro:
	.string "Voglio visitare EVER GRANDE, quindi\n"
	.string "ho preso un POKéMON che conosce\l"
	.string "la mossa CASCATA per salire.$"

Route128_Text_WayneDefeat:
	.string "Sono a terra!$"

Route128_Text_WaynePostBattle:
	.string "Uffa, che peccato!\p"
	.string "Il mio POKéMON conosce CASCATA, ma\n"
	.string "non ho la MEDAGLIA di PORTO ALGHE!$"

Route128_Text_HarrisonIntro:
	.string "Hai un aspetto davvero tosto.\n"
	.string "Chissà se posso vincere?$"

Route128_Text_HarrisonDefeat:
	.string "Ahia!\n"
	.string "Era impossibile vincere.$"

Route128_Text_HarrisonPostBattle:
	.string "Ci sono ALLENATORI forti in giro\n"
	.string "nei pressi di EVER GRANDE.\p"
	.string "Secondo te sono fuori\n"
	.string "dalla mia categoria?$"

Route128_Text_CarleeIntro:
	.string "La luce del sole sembra più forte\n"
	.string "in questa zona.$"

Route128_Text_CarleeDefeat:
	.string "Non vedevo bene per via del\n"
	.string "bagliore del sole.$"

Route128_Text_CarleePostBattle:
	.string "Dovrei tornare presto.\n"
	.string "Devo rimettermi la crema solare.$"

Route129_Text_ChaseIntro:
	.string "Questo è il mio primo triathlon.\n"
	.string "Sono tutto teso e nervoso!$"

Route129_Text_ChaseDefeat:
	.string "Wroooaaar!\n"
	.string "Ho perso!$"

Route129_Text_ChasePostBattle:
	.string "Se sono tutto teso, non riuscirò a\n"
	.string "dare il massimo.$"

Route129_Text_AllisonIntro:
	.string "Sono nel bel mezzo di un triathlon,\n"
	.string "ma perché no, lottiamo?$"

Route129_Text_AllisonDefeat:
	.string "Ero sicura di vincere!$"

Route129_Text_AllisonPostBattle:
	.string "Sai qual è la cosa più bella\n"
	.string "dei triathlon?\p"
	.string "Mettere alla prova i propri\n"
	.string "limiti di forza e resistenza\l"
	.string "contro Madre Natura!$"

Route129_Text_ReedIntro:
	.string "Ehi, ciao!\n"
	.string "Diamoci dentro!$"

Route129_Text_ReedDefeat:
	.string "Ritmo o no, ho perso.\n"
	.string "È finita, basta!$"

Route129_Text_ReedPostBattle:
	.string "Per un perdente non c'è niente.\n"
	.string "È ora che me ne torni a casa.$"

Route129_Text_TishaIntro:
	.string "Che fretta hai?\n"
	.string "Prendiamola con calma.$"

Route129_Text_TishaDefeat:
	.string "Oh, cielo.\n"
	.string "Volevo rilassarmi ancora un po'…$"

Route129_Text_TishaPostBattle:
	.string "Odi anche tu fare errori quando\n"
	.string "hai fretta?\p"
	.string "Per questo io cerco di fare\n"
	.string "tutto piano.$"

Route129_Text_ClarenceIntro:
	.string "Surfare non è facile come sembra,\n"
	.string "vero?$"

Route129_Text_ClarenceDefeat:
	.string "Vincere non è certo facile.$"

Route129_Text_ClarencePostBattle:
	.string "Punti alla LEGA POKéMON?\n"
	.string "Continua così!$"

Route130_Text_RodneyIntro:
	.string "Che sorpresa! Non mi aspettavo\n"
	.string "un ALLENATORE in mare.\p"
	.string "Direi che dobbiamo lottare!$"

Route130_Text_RodneyDefeat:
	.string "Questo ragazzo è fortissimo…$"

Route130_Text_RodneyPostBattle:
	.string "Hai lo sguardo di chi ha affrontato\n"
	.string "prove durissime e le ha vinte.\l"
	.string "Ti sta proprio bene!$"

Route130_Text_KatieIntro:
	.string "Nel mare blu profondo,\n"
	.string "il mio cuore infranto trova\l"
	.string "conforto fra le onde.$"

Route130_Text_KatieDefeat:
	.string "Come il vasto mare blu,\n"
	.string "il mondo dei POKéMON ha\l"
	.string "abissi inimmaginabili.$"

Route130_Text_KatiePostBattle:
	.string "I bambini del mondo sognano\n"
	.string "di diventare un giorno\l"
	.string "CAMPIONE POKéMON.$"

Route130_Text_SantiagoIntro:
	.string "Fluttuare in mare aperto così…\n"
	.string "È pace.$"

Route130_Text_SantiagoDefeat:
	.string "Dovevo essere un po' meno pacifico!$"

Route130_Text_SantiagoPostBattle:
	.string "Nuotare e lottare così…\n"
	.string "Sono un uomo felice…$"

Route131_Text_RichardIntro:
	.string "Il mare pullula di POKéMON.\n"
	.string "Nuotare non è facile, sai.$"

Route131_Text_RichardDefeat:
	.string "I POKéMON allenati dagli ALLENATORI\n"
	.string "sono davvero forti…$"

Route131_Text_RichardPostBattle:
	.string "Anf… Anf…\n"
	.string "Sono distrutto…\p"
	.string "Andare è facile. È tornare\n"
	.string "che è dura.\p"
	.string "Avrò la forza per il viaggio\n"
	.string "di ritorno?$"

Route131_Text_HermanIntro:
	.string "Il mare… Il mare… Il mare…\n"
	.string "Mare fin dove arriva lo sguardo!\l"
	.string "Sono stanco e stufo del mare!$"

Route131_Text_HermanDefeat:
	.string "Bleah!$"

Route131_Text_HermanPostBattle:
	.string "Il mare mi annoia, ma nuotar devo.\p"
	.string "Sono nato nuotatore!\n"
	.string "Ecco cosa sono.$"

Route131_Text_SusieIntro:
	.string "Ciao, tesoro, aspetta!\n"
	.string "Dovremmo lottare, io e te!$"

Route131_Text_SusieDefeat:
	.string "Sei forte nonostante\n"
	.string "il tuo aspetto!$"

Route131_Text_SusiePostBattle:
	.string "Hai visto là un tipo che si lamenta\n"
	.string "di essere annoiato dal mare?\p"
	.string "Sono solo chiacchiere.\n"
	.string "È innamorato perso del mare!$"

Route131_Text_KaraIntro:
	.string "Perché agli uomini piacciono tanto\p"
	.string "i costumi? Tutti mi fissano!$"

Route131_Text_KaraDefeat:
	.string "Non so più che pesci pigliare!$"

Route131_Text_KaraPostBattle:
	.string "Forse non è il costume che li fa\n"
	.string "girare. Dev'essere la mia bellezza!$"

Route131_Text_ReliIntro:
	.string "RELI: Collaboreremo come fratelli\n"
	.string "per sfidarti!$"

Route131_Text_ReliDefeat:
	.string "RELI: Non abbiamo vinto anche se\n"
	.string "abbiamo collaborato…$"

Route131_Text_ReliPostBattle:
	.string "RELI: La gente di PACIFIDLOG vive\n"
	.string "col mare e coi POKéMON fin\l"
	.string "dal giorno in cui nasce.$"

Route131_Text_ReliNotEnoughMons:
	.string "RELI: Non hai due POKéMON?\n"
	.string "Allora niente lotta.$"

Route131_Text_IanIntro:
	.string "IAN: Do il massimo insieme a\n"
	.string "mia sorella!$"

Route131_Text_IanDefeat:
	.string "IAN: Ho dato il massimo con mia\n"
	.string "sorella, ma non abbiamo vinto…$"

Route131_Text_IanPostBattle:
	.string "IAN: Sai che PACIFIDLOG è\n"
	.string "una città fluttuante?\p"
	.string "Quindi ovunque ci sia il mare,\n"
	.string "è parte di PACIFIDLOG!$"

Route131_Text_IanNotEnoughMons:
	.string "IAN: Se hai due POKéMON,\n"
	.string "ti sfidiamo!$"

Route131_Text_TaliaIntro:
	.string "Se riesci a battermi, ti darò\n"
	.string "un'informazione fantastica!$"

Route131_Text_TaliaDefeat:
	.string "Oh?\n"
	.string "Ho perso?$"

Route131_Text_TaliaPostBattle:
	.string "C'è un posto strano qui vicino.\n"
	.string "C'è una torre enorme.\l"
	.string "Perché non ci dai un'occhiata?$"

Route131_Text_KevinIntro:
	.string "La gente di PACIFIDLOG è\n"
	.string "un branco pacifico.\p"
	.string "Non si arrabbia mai.\n"
	.string "Vale anche per me.$"

Route131_Text_KevinDefeat:
	.string "Ops!$"

Route131_Text_KevinPostBattle:
	.string "Tch! …Ah, aspetta.\n"
	.string "Non sono arrabbiato. Davvero!\p"
	.string "Però sei forte!\n"
	.string "Ahahah!$"

Route132_Text_GilbertIntro:
	.string "Da piccolo prendevo sempre il\n"
	.string "raffreddore, ma mi sono irrobustito\l"
	.string "iniziando a nuotare.$"

Route132_Text_GilbertDefeat:
	.string "Voglio più potenza…$"

Route132_Text_GilbertPostBattle:
	.string "Gli ALLENATORI girano campi e\n"
	.string "monti, quindi anche loro sono in forma.$"

Route132_Text_DanaIntro:
	.string "Cerco di non nuotare dove\n"
	.string "le correnti sono forti.$"

Route132_Text_DanaDefeat:
	.string "Oh, ti prego, no!$"

Route132_Text_DanaPostBattle:
	.string "Se mi trascina la corrente, perdo\n"
	.string "ogni senso dell'orientamento…$"

Route132_Text_RonaldIntro:
	.string "Vinci o perdi, non lo scopri\n"
	.string "finché non provi!$"

Route132_Text_RonaldDefeat:
	.string "Waah!\n"
	.string "Sono affondato!$"

Route132_Text_RonaldPostBattle:
	.string "Non lotto mai quando so di vincere.\n"
	.string "Mi piace lottare sul filo\l"
	.string "tra vittoria e sconfitta!$"

Route132_Text_KiyoIntro:
	.string "Penso ai POKéMON 24 ore al giorno.\n"
	.string "Come potresti mai battermi?$"

Route132_Text_KiyoDefeat:
	.string "Ho perso.\n"
	.string "Mi dichiaro sconfitto.$"

Route132_Text_KiyoPostBattle:
	.string "Urggh…\n"
	.string "Sei un fanatico dei POKéMON, vero?\p"
	.string "Pensi ai POKéMON 24 ore\n"
	.string "al giorno, dico bene?$"

Route132_Text_MakaylaIntro:
	.string "Sto sempre con mio marito,\n"
	.string "ma so vincere anche senza di lui.$"

Route132_Text_MakaylaDefeat:
	.string "Ah, non ero all'altezza.$"

Route132_Text_MakaylaPostBattle:
	.string "Quel ragazzo laggiù assomiglia\n"
	.string "a mio marito da giovane.\p"
	.string "Mi fa arrossire!$"

Route132_Text_JonathanIntro:
	.string "Qualcuno mi fissava.\n"
	.string "Eri tu?$"

Route132_Text_JonathanDefeat:
	.string "Wow!\n"
	.string "Sei davvero forte, altroché!$"

Route132_Text_JonathanPostBattle:
	.string "Ho la sensazione che\n"
	.string "qualcuno mi osservi.\p"
	.string "Non riesco a concentrarmi!$"

Route132_Text_PaxtonIntro:
	.string "Dove sarà andata mia moglie?\n"
	.string "Sto sempre con lei.\l"
	.string "Chissà se so vincere da solo.$"

Route132_Text_PaxtonDefeat:
	.string "Ah, vedo che da solo non\n"
	.string "sono riuscito a vincere.$"

Route132_Text_PaxtonPostBattle:
	.string "Mia moglie mi starà cercando.\n"
	.string "Meglio che la trovi subito.$"

Route132_Text_DarcyIntro:
	.string "Mi piaceva allenarmi qui da sola.\n"
	.string "Che rabbia tutta questa gente!$"

Route132_Text_DarcyDefeat:
	.string "Okay! Non mi lamenterò più della\n"
	.string "gente che passa di qui.$"

Route132_Text_DarcyPostBattle:
	.string "Immagino che farò coppia con quel\n"
	.string "vecchietto e sfiderò l'altra squadra.$"

Route133_Text_FranklinIntro:
	.string "Anche tu portato qui dalle correnti?\n"
	.string "Era destino.\l"
	.string "Lottiamo!$"

Route133_Text_FranklinDefeat:
	.string "Forte!\n"
	.string "Troppo forte!$"

Route133_Text_FranklinPostBattle:
	.string "Che fortuna che un ALLENATORE\n"
	.string "forte come te sia approdato qui…\l"
	.string "Devo essere maledetto…$"

Route133_Text_DebraIntro:
	.string "Ho vissuto una vita di dolore…\n"
	.string "Sono stata scacciata, e qui\l"
	.string "sono approdata…$"

Route133_Text_DebraDefeat:
	.string "Ancora una sconfitta…$"

Route133_Text_DebraPostBattle:
	.string "Una vita alla deriva…\n"
	.string "Non la voglio più!$"

Route133_Text_LindaIntro:
	.string "Benvenuto!\n"
	.string "Ti aspettavo!$"

Route133_Text_LindaDefeat:
	.string "No! Ti prego!$"

Route133_Text_LindaPostBattle:
	.string "Un bambino ALLENATORE forte…\n"
	.string "Che seccatura!$"

Route133_Text_WarrenIntro:
	.string "Voglio vincere come tutti, ma non\n"
	.string "allevo POKéMON come tutti.$"

Route133_Text_WarrenDefeat:
	.string "Accidenti!\n"
	.string "Il mio stile è ancora troppo fiacco!$"

Route133_Text_WarrenPostBattle:
	.string "È molto più divertente fare le cose come\n"
	.string "voglio io che essere come tutti gli altri.\l"
	.string "Insomma, è ovvio!$"

Route133_Text_BeckIntro:
	.string "Sono arrivato fin qui con i miei\n"
	.string "POKéMON Uccello.$"

Route133_Text_BeckDefeat:
	.string "Tu…\n"
	.string "Sei incredibilmente forte!$"

Route133_Text_BeckPostBattle:
	.string "Vorrei tornare a FORTREE,\n"
	.string "ma anche questo posto mi piace.$"

Route133_Text_MollieIntro:
	.string "Avrò lottato migliaia\n"
	.string "di volte. Ho perso il conto.$"

Route133_Text_MollieDefeat:
	.string "Avrò perso migliaia di volte,\n"
	.string "ma una sconfitta fa sempre male.$"

Route133_Text_MolliePostBattle:
	.string "Continua così, ragazzo. Così\n"
	.string "diventerai come me e mio marito.$"

Route133_Text_ConorIntro:
	.string "I giovani seguono la corrente\n"
	.string "senza meta. Non hanno direzione.$"

Route133_Text_ConorDefeat:
	.string "Hai le idee ben chiare.$"

Route133_Text_ConorPostBattle:
	.string "Non farti sviare dagli altri.\n"
	.string "Non perdere la direzione crescendo.$"

Route134_Text_JackIntro:
	.string "Anche i POKéMON che sanno nuotare\n"
	.string "vengono trascinati dalle correnti.$"

Route134_Text_JackDefeat:
	.string "Ahiieeeeh!$"

Route134_Text_JackPostBattle:
	.string "Credo che i POKéMON adorino le correnti\n"
	.string "veloci di queste zone.$"

Route134_Text_LaurelIntro:
	.string "I miei LUVDISC cercano una lotta\n"
	.string "divertente. Ti unisci a noi?$"

Route134_Text_LaurelDefeat:
	.string "Ops!$"

Route134_Text_LaurelPostBattle:
	.string "C'è un collezionista che cerca\n"
	.string "le SQUAME dei LUVDISC.$"

Route134_Text_AlexIntro:
	.string "Ok! Basta riposo, squadra!\n"
	.string "È ora di lottare!$"

Route134_Text_AlexDefeat:
	.string "Di nuovo a terra…$"

Route134_Text_AlexPostBattle:
	.string "I miei POKéMON UCCELLO si stancano\n"
	.string "dopo un lungo volo…$"

Route134_Text_HitoshiIntro:
	.string "Sei un ALLENATORE di POKéMON.\n"
	.string "Niente parole. Lottiamo ora.$"

Route134_Text_HitoshiDefeat:
	.string "… … … … … …\n"
	.string "… … … … … …$"

Route134_Text_HitoshiPostBattle:
	.string "Ti ho sfidato io, eppure\n"
	.string "ho perso. Che vergogna…$"

Route134_Text_AaronIntro:
	.string "La marea feroce di questa zona serve a\n"
	.string "renderci più forti che mai.$"

Route134_Text_AaronDefeat:
	.string "Ammmetto volentieri la sconfitta.$"

Route134_Text_AaronPostBattle:
	.string "Torneremo ad allenarci alle\n"
	.string "CASCATE METEORA.\p"
	.string "Se vuoi, dovresti venire anche tu.\n"
	.string "Ti renderà sicuramente più forte!$"

Route134_Text_KelvinIntro:
	.string "L-la nostra barca!\n"
	.string "La marea se l'è portata via!$"

Route134_Text_KelvinDefeat:
	.string "Uauauauaua!\n"
	.string "Ti prego, basta! Ti prego!$"

Route134_Text_KelvinPostBattle:
	.string "Se non possiamo usare SURF, come\n"
	.string "torniamo a casa?\p"
	.string "In realtà so che un POKéMON esausto\n"
	.string "può usare comunque SURF, ma non è giusto.$"

Route134_Text_MarleyIntro:
	.string "I tuoi POKéMON sanno schivare i nostri\n"
	.string "attacchi fulminei?$"

Route134_Text_MarleyDefeat:
	.string "Non sapevo esistesse una tecnica così!\n"
	.string "Ci hai battuti su tutta la linea.$"

Route134_Text_MarleyPostBattle:
	.string "Non ho perso la passione per la velocità.\n"
	.string "Mi impegnerò di più.$"

Route134_Text_ReynaIntro:
	.string "I miei POKéMON non si battono\n"
	.string "facilmente!$"

Route134_Text_ReynaDefeat:
	.string "Ma scherzi?\n"
	.string "Spiegami come ho perso!$"

Route134_Text_ReynaPostBattle:
	.string "Ah ah!\n"
	.string "Hai vinto, d'accordo!\p"
	.string "Mi rimetterò in forma sfidando\n"
	.string "gli ALLENATORI che incontro!$"

Route134_Text_HudsonIntro:
	.string "Dimmi, hai visto un altro MARINAIO\n"
	.string "da queste parti?$"

Route134_Text_HudsonDefeat:
	.string "Ma guarda un po'!$"

Route134_Text_HudsonPostBattle:
	.string "La nostra barca è andata alla deriva.\p"
	.string "Il mio amico è un tipo timido, quindi\n"
	.string "sono preoccupato per lui.$"

VSSeeker_Text_BatteryNotChargedNeedXSteps::
	.string "La batteria non è carica a sufficienza.\p"
	.string "Passi necessari per caricarla\n"
	.string "del tutto: {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

VSSeeker_Text_NoTrainersWithinRange::
	.string "Non ci sono Allenatori nei paraggi\n"
	.string "che possano lottare…\p"
	.string "Il VS Seeker si è spento.{PAUSE_UNTIL_PRESS}$"

VSSeeker_Text_TrainersNotReady::
	.string "Gli altri Allenatori non sembrano\n"
	.string "pronti a lottare.\p"
	.string "Aspettiamo più tardi.{PAUSE_UNTIL_PRESS}$"
