LilycoveCity_ContestLobby_Text_InterviewRequest:
	.string "Oh, ciao! Eri a una GARA\n"
	.string "POKéMON, vero?\l"
	.string "Si vede subito dai tuoi POKéMON.\p"
	.string "Sono una reporter. Sto lavorando a un\n"
	.string "servizio sulle GARE POKéMON.\p"
	.string "Se posso, risponderesti\n"
	.string "a qualche domanda?$"

LilycoveCity_ContestLobby_Text_DescribeContest:
	.string "Ah, davvero?\n"
	.string "Grazie.\p"
	.string "In breve, come descriveresti la\n"
	.string "GARA a cui hai appena partecipato?$"

LilycoveCity_ContestLobby_Text_WhatImageWhenYouHearX:
	.string "Ah, capisco.\n"
	.string "È un commento molto istruttivo.\p"
	.string "Si capisce bene com'era\n"
	.string "la GARA.\p"
	.string "Ho un'ultima domanda.\p"
	.string "Quando senti la parola “{STR_VAR_2},”\n"
	.string "quale immagine ti viene in mente?$"

LilycoveCity_ContestLobby_Text_ThatsAllForInterview:
	.string "Capisco!\p"
	.string "Quindi è così che immagini il concetto\n"
	.string "di “{STR_VAR_2}”.\p"
	.string "Grazie!\n"
	.string "Mi hai dato delle belle idee.\p"
	.string "Ora posso scrivere un buon servizio\n"
	.string "sulle GARE POKéMON.\p"
	.string "Magari, chissà, finirà persino\n"
	.string "in televisione.\l"
	.string "Spero che lo guarderai!$"

LilycoveCity_ContestLobby_Text_PleaseDoShareStoryWithMe:
	.string "Oh, peccato…\p"
	.string "Beh, se trovi una bella storia,\n"
	.string "raccontamela pure.$"

LilycoveCity_ContestLobby_Text_LookingForwardToNextContest:
	.string "Non vedo l'ora di vedere la tua\n"
	.string "prossima GARA POKéMON.$"

gTVBravoTrainerText00::
	.string "Sì!\n"
	.string "È il momento di BRAVO ALLENATORE!\p"
	.string "Oggi presentiamo un POKéMON\n"
	.string "di {STR_VAR_1}.\p"
	.string "Questo POKéMON vanta il rango {STR_VAR_3}\n"
	.string "nella categoria {STR_VAR_2}.$"

gTVBravoTrainerText01::
	.string "Vi presento {STR_VAR_2}, il\n"
	.string "{STR_VAR_1}!\p"
	.string "Il soprannome {STR_VAR_2}…\p"
	.string "Anche il soprannome emana un'aria\n"
	.string "che proclama “{STR_VAR_3}”!$"

gTVBravoTrainerText02::
	.string "Comunque, quando l'ALLENATORE {STR_VAR_1}\n"
	.string "ha iscritto il POKéMON a una GARA,\l"
	.string "abbiamo ottenuto alcune frasi\l"
	.string "appassionate sul fidato partner.$"

gTVBravoTrainerText03::
	.string "Interrogato sul CONTEST dopo la gara,\n"
	.string "{STR_VAR_1} ha risposto felice con un grande\l"
	.string "sorriso, “{STR_VAR_2}!”\p"
	.string "Beh, certo, il POKéMON di {STR_VAR_1} è arrivato\n"
	.string "numero {STR_VAR_3} al CONTEST.\p"
	.string "Quella frase si addice perfettamente a {STR_VAR_1}\n"
	.string "adesso, direi!$"

gTVBravoTrainerText04::
	.string "Alla domanda sulla GARA,\n"
	.string "{STR_VAR_1} ha risposto con un pizzico\l"
	.string "di amarezza, “{STR_VAR_2}.”\p"
	.string "Certo, il POKéMON di {STR_VAR_1} è arrivato\n"
	.string "al numero {STR_VAR_3} nella GARA.\p"
	.string "La delusione di {STR_VAR_1} si sente\n"
	.string "forte e chiara, direi!$"

gTVBravoTrainerText05::
	.string "Non vorreste sapere anche cosa\n"
	.string "immagina {STR_VAR_1} che sia {STR_VAR_2}?\p"
	.string "Ovviamente sì!\n"
	.string "E glielo abbiamo chiesto!\p"
	.string "La risposta è tutta condensata:\n"
	.string "“{STR_VAR_3}!”\p"
	.string "Ecco cosa rappresenta {STR_VAR_2}\n"
	.string "per {STR_VAR_1}!$"

gTVBravoTrainerText06::
	.string "L'ultima mossa usata da {STR_VAR_2}\n"
	.string "al {STR_VAR_1} è tutta all'insegna\l"
	.string "di “{STR_VAR_3}”!$"

gTVBravoTrainerText07::
	.string "Bravo, {STR_VAR_1}!\n"
	.string "Bravo, {STR_VAR_2}!\p"
	.string "Spero che potremo vedere\n"
	.string "{STR_VAR_1} raggiungere vette ancora più alte!\p"
	.string "È tutto il tempo che abbiamo!\n"
	.string "Alla prossima, ci vediamo!$"

gTVBravoTrainerText08::
	.string "Vi presento {STR_VAR_1} dell'ALLENATORE!$"

BattleFrontier_BattleTowerLobby_Text_InterviewRequest::
	.string "Ciao! Sei l'ALLENATORE che ha appena\n"
	.string "lottato, vero?\p"
	.string "Raccolgo interviste con ALLENATORI\n"
	.string "un po' dappertutto.\p"
	.string "Posso avere qualche parola sulle\n"
	.string "tue impressioni di lotta?$"

BattleFrontier_BattleTowerLobby_Text_HowDidBattleTowerTurnOut::
	.string "Lo farai? Davvero?\n"
	.string "Grazie!\l"
	.string "Allora, ehm…\p"
	.string "Come è andata oggi alla\n"
	.string "BATTLE TOWER?\p"
	.string "Sei soddisfatto della lotta?\n"
	.string "O sei insoddisfatto?$"

BattleFrontier_BattleTowerLobby_Text_SorryWeDisturbedYou::
	.string "Oh…\n"
	.string "Scusa se ti abbiamo disturbato.\p"
	.string "Concedici un'intervista la prossima\n"
	.string "volta che visiti la BATTLE TOWER.$"

BattleFrontier_BattleTowerLobby_Text_ObviousYouHadGreatBattle::
	.string "Beh, certo!\p"
	.string "Quell'espressione inconfondibile\n"
	.string "di soddisfazione in faccia…\p"
	.string "È ovvio che hai fatto una\n"
	.string "lotta fantastica.$"

BattleFrontier_BattleTowerLobby_Text_DifficultToMakeBattleTurnOutAsPlanned::
	.string "Oh, capisco…\p"
	.string "Beh, è davvero difficile far andare\n"
	.string "una lotta esattamente come previsto.$"

BattleFrontier_BattleTowerLobby_Text_DescribeYourBattle::
	.string "Oh, oh, posso fare un'altra domanda?\p"
	.string "Se dovessi descrivere le tue\n"
	.string "impressioni su questa lotta\l"
	.string "con una frase, quale sarebbe?$"

BattleFrontier_BattleTowerLobby_Text_ThatsGreatLine::
	.string "Oh, è di una classe incredibile!\p"
	.string "Che bella frase!\n"
	.string "Spero farai bene anche la prossima volta.\p"
	.string "Spero di rivederti!$"

BattleFrontier_BattleTowerLobby_Text_SilentType::
	.string "Oh, capisco…\p"
	.string "Però anche essere di poche parole\n"
	.string "è forte, no?\p"
	.string "Spero mi darai l'occasione\n"
	.string "di sentire di nuovo i tuoi pensieri!$"

BattleFrontier_BattleTowerLobby_Text_LookingForwardToNextBattle::
	.string "Non vedo l'ora della tua\n"
	.string "prossima lotta!$"

BravoTrainerBattleTower_Text_Intro::
	.string "Sì!\n"
	.string "È il momento di BRAVO TRAINER!\p"
	.string "Oggi parliamo di {STR_VAR_1},\n"
	.string "che ha affrontato la BATTLE TOWER!\p"
	.string "Per la sfida, {STR_VAR_1} ha schierato\n"
	.string "un {STR_VAR_2} coi fiocchi.$"

BravoTrainerBattleTower_Text_NewRecord::
	.string "La coppia ha stabilito un nuovo record di {STR_VAR_2}\n"
	.string "vittorie di fila nella gara {STR_VAR_1}!\l"
	.string "Bravo, ALLENATORE!$"

BravoTrainerBattleTower_Text_Lost::
	.string "La coppia ha ceduto a\n"
	.string "{STR_VAR_1} nel match numero {STR_VAR_2}.\l"
	.string "Bel tentativo, ALLENATORE!\p"
	.string "Ma è solo sfortuna incontrare\n"
	.string "{STR_VAR_1} così presto.\p"
	.string "Abbiamo chiesto le impressioni\n"
	.string "sul match con {STR_VAR_1}.$"

BravoTrainerBattleTower_Text_Won::
	.string "La coppia ha vinto battendo\n"
	.string "il {STR_VAR_2} di {STR_VAR_1} nettamente.\l"
	.string "Bravo, ALLENATORE!\p"
	.string "Battere persino {STR_VAR_1}…\n"
	.string "Incredibile! Sbalorditivo!\p"
	.string "Abbiamo chiesto all'ALLENATORE le\n"
	.string "impressioni sul momento di gloria.$"

BravoTrainerBattleTower_Text_LostFinal::
	.string "Dopo tante vittorie, la coppia si è\n"
	.string "arresa alla {STR_VAR_2} di {STR_VAR_1},\l"
	.string "l'ultimo ostacolo.\p"
	.string "Bel tentativo, ALLENATORE!\p"
	.string "Però va dato merito.\n"
	.string "Non si vedono molte coppie famose\l"
	.string "come {STR_VAR_1} e {STR_VAR_2}.\p"
	.string "Abbiamo chiesto all'ALLENATORE\n"
	.string "le impressioni sulla coppia di star.$"

BravoTrainerBattleTower_Text_Satisfied::
	.string "Ecco cosa ha detto l'ALLENATORE:\n"
	.string "“Sono soddisfatto!”\p"
	.string "Non è una risposta rinfrescante?\n"
	.string "Bravo, ALLENATORE!\p"
	.string "Non è fantastico poter lottare\n"
	.string "con piena soddisfazione?\p"
	.string "Ho scoperto quanta soddisfazione\n"
	.string "quando l'ALLENATORE ha detto:$"

BravoTrainerBattleTower_Text_Unsatisfied::
	.string "Ecco cosa ha detto l'ALLENATORE:\n"
	.string "“Non sono soddisfatto…”\p"
	.string "Il nostro ALLENATORE era un po' giù\n"
	.string "quando l'ha detto.\p"
	.string "Però non è facile lottare\n"
	.string "con piena soddisfazione, vero?\p"
	.string "Comunque, ho scoperto quanta\n"
	.string "insoddisfazione sentendo questo:$"

BravoTrainerBattleTower_Text_None1::
	.string "Nessuno$"

BravoTrainerBattleTower_Text_None2::
	.string "Nessuno$"

BravoTrainerBattleTower_Text_None3::
	.string "Nessuno$"

BravoTrainerBattleTower_Text_None4::
	.string "Nessuno$"

BravoTrainerBattleTower_Text_Response::
	.string "“{STR_VAR_1}.”$"

BravoTrainerBattleTower_Text_ResponseSatisfied::
	.string "“{STR_VAR_1}.”\n"
	.string "Non è fantastico?\p"
	.string "Esprime davvero la gioia di {STR_VAR_2},\n"
	.string "direi.\p"
	.string "Quella lotta con {STR_VAR_3} alla\n"
	.string "fine… È stata proprio quella che\l"
	.string "chiameresti “{STR_VAR_1}”!$"

BravoTrainerBattleTower_Text_ResponseUnsatisfied::
	.string "“{STR_VAR_1}.”\n"
	.string "Non è calzante?\p"
	.string "Quella lotta con {STR_VAR_3} alla\n"
	.string "fine… Non la descrivi che con\l"
	.string "“{STR_VAR_1}”!\p"
	.string "La delusione di {STR_VAR_2} è\n"
	.string "chiara e forte, direi!$"

BravoTrainerBattleTower_Text_Outro::
	.string "Bravo, {STR_VAR_1}!\n"
	.string "Bravo, {STR_VAR_2}!\p"
	.string "Spero che potremo vedere\n"
	.string "{STR_VAR_1} raggiungere vette ancora più alte!\p"
	.string "È tutto il tempo che abbiamo!\n"
	.string "Alla prossima, ci vediamo!$"

SlateportCity_PokemonFanClub_Text_InterviewRequestHasName:
	.string "Wow!\p"
	.string "Si vede che riempi di attenzioni il tuo\n"
	.string "{STR_VAR_1}.\p"
	.string "Ah, si chiama {STR_VAR_2}.\p"
	.string "Posso chiederti un favore?\p"
	.string "Sono una reporter TV e sto facendo\n"
	.string "un'indagine sui POKéMON.\p"
	.string "Ti andrebbe di rispondere a qualche\n"
	.string "domanda semplice?$"

SlateportCity_PokemonFanClub_Text_HereGoesQuickAnswers:
	.string "Benissimo! Grazie!\p"
	.string "Ok, cominciamo.\n"
	.string "Mi servono risposte brevi, va bene?$"

SlateportCity_PokemonFanClub_Text_DescribeFeelingsFirstMetMon:
	.string "Quando hai incontrato {STR_VAR_1},\n"
	.string "cosa hai provato?\p"
	.string "Come descriveresti le tue sensazioni\n"
	.string "di quel momento?$"

SlateportCity_PokemonFanClub_Text_LikenMonToSomethingYouLike:
	.string "Il tuo {STR_VAR_1} è curato con amore.\p"
	.string "Se dovessi paragonarlo a qualcosa\n"
	.string "che ti piace, a cosa sarebbe?$"

SlateportCity_PokemonFanClub_Text_WhatAttractedYouAboutMon:
	.string "Questa domanda riguarda ancora il tuo\n"
	.string "amato {STR_VAR_1}.\p"
	.string "Cosa ti ha colpito di {STR_VAR_1}?\n"
	.string "Cosa ti ha attirato?$"

SlateportCity_PokemonFanClub_Text_WhatDoPokemonMeanToYou:
	.string "Ok, ha senso.\p"
	.string "La prossima domanda potrebbe essere\n"
	.string "un po' difficile.\p"
	.string "Ecco qua…\p"
	.string "Cosa sono per te i POKéMON?$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview:
	.string "Capisco!\p"
	.string "Mmmh…\p"
	.string "Ok!\n"
	.string "Grazie dell'aiuto.\p"
	.string "È stato bello e istruttivo\n"
	.string "chiacchierare con te.\p"
	.string "Può darsi che la nostra intervista\n"
	.string "finisca in TV. Seguila!\p"
	.string "Ok, è tutto.\n"
	.string "Ciao ciao!$"

SlateportCity_PokemonFanClub_Text_HereIfYouGetUrgeToTellMe:
	.string "Oh, va bene…\p"
	.string "Se ti viene voglia di parlarmi dei\n"
	.string "POKéMON, io sono qui!$"

SlateportCity_PokemonFanClub_Text_EnjoyDoingInterviews:
	.string "Adoro questo lavoro: con le interviste\n"
	.string "impari a conoscere i POKéMON.$"

SlateportCity_PokemonFanClub_Text_InterviewRequest:
	.string "Ciao, sembri molto legato al tuo\n"
	.string "{STR_VAR_1}.\p"
	.string "Sai una cosa?\n"
	.string "Sono una reporter TV.\p"
	.string "Viaggio in giro intervistando la gente\n"
	.string "sui POKéMON.\p"
	.string "Ti andrebbe di raccontarmi qualcosa\n"
	.string "sul tuo {STR_VAR_1}?$"

SlateportCity_PokemonFanClub_Text_TellMeAnythingAboutYourMon:
	.string "Wow, grazie!\p"
	.string "Ok, allora dimmi pure ciò che vuoi\n"
	.string "sul tuo {STR_VAR_1}.$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview2:
	.string "Wow…\n"
	.string "Che racconto interessante.\p"
	.string "Sei davvero in sintonia con {STR_VAR_1},\n"
	.string "vero?\p"
	.string "Ho la sensazione che il tuo racconto\n"
	.string "farà un ottimo servizio TV.\p"
	.string "Ti prometto che ne farò\n"
	.string "uno spettacolo avvincente.\l"
	.string "Tieni gli occhi aperti.\p"
	.string "Ok, è tutto.\n"
	.string "Ciao ciao!$"

gTVFanClubOpinionsText00::
	.string "SIAMO IL FAN CLUB POKéMON!\p"
	.string "Siamo in onda!\p"
	.string "Qui raccogliamo le vostre opinioni\n"
	.string "e le grido per voi!\l"
	.string "Non è un programma fantastico?\p"
	.string "Oggi vi portiamo il reportage del\n"
	.string "nostro inviato al\l"
	.string "FAN CLUB POKéMON.\p"
	.string "Ma chi è il fan POKéMON\n"
	.string "di oggi?\p"
	.string "… … … … … … … …\p"
	.string "{STR_VAR_1}!\p"
	.string "Sentiamo cosa ha da dire {STR_VAR_1}\n"
	.string "su {STR_VAR_3}, il {STR_VAR_2}.\p"
	.string "E io griderò le sue parole d'amore\n"
	.string "in diretta TV!\p"
	.string "Uhh!\p"
	.string "Gridiamo!$"

gTVFanClubOpinionsText01::
	.string "Abbiamo chiesto a {STR_VAR_1}: “Quando hai\n"
	.string "visto per la prima volta il tuo {STR_VAR_2}, che\l"
	.string "pensiero hai fatto?”\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Eh già! Che bel grido!\p"
	.string "Non ti riporta alla mente quei\n"
	.string "bei tempi andati?$"

gTVFanClubOpinionsText02::
	.string "Abbiamo chiesto a {STR_VAR_1}: “Se dovessi\n"
	.string "paragonare il tuo {STR_VAR_2} a qualcosa,\l"
	.string "sarebbe…”\p"
	.string "… … … … … … … …\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Uao, che idea originale!\p"
	.string "Si sente l'intensità di\n"
	.string "Sensazione che l'ALLENATORE prova per\l"
	.string "{STR_VAR_2}.$"

gTVFanClubOpinionsText03::
	.string "E vediamo…\n"
	.string "Cosa aveva quel {STR_VAR_2}\l"
	.string "che ha conquistato {STR_VAR_1}?\p"
	.string "… … … … … … … …\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Uao! Che dichiarazione spettacolare!\p"
	.string "L'amore dell'ALLENATORE per il {STR_VAR_2}\n"
	.string "si sente forte e chiaro!$"

gTVFanClubOpinionsText04::
	.string "Hm? Oh, c'è ancora altro.\n"
	.string "Andiamo a vedere!\p"
	.string "Vediamo, dunque…\p"
	.string "Abbiamo chiesto a {STR_VAR_1}: “Cosa sono i POKéMON\n"
	.string "per te?”\p"
	.string "… … … … … …\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Bravo!\p"
	.string "È il grido più bello di oggi!\p"
	.string "“{STR_VAR_3}!”\p"
	.string "Ti viene voglia di gridarlo forte\n"
	.string "ancora e ancora!\p"
	.string "Dopo un grido così, è\n"
	.string "ora di salutarci alla prossima!\p"
	.string "Forza, un ultimo grido!\n"
	.string "Tutti insieme…\p"
	.string "“{STR_VAR_3}!”$"

gTVFanClubText00::
	.string "SIAMO IL POKéMON FAN CLUB!\p"
	.string "Siamo in onda!\p"
	.string "Oggi partiamo con l'\n"
	.string "ANGOLO SONDAGGIO POKéMON.\p"
	.string "Fra tutte le storie di POKéMON\n"
	.string "e ALLENATORI, quale nuovo dramma\l"
	.string "attirerà la nostra attenzione oggi?\p"
	.string "Vediamo…\p"
	.string "Questa!\p"
	.string "Iniziamo con questa Lettera!\p"
	.string "È una Lettera di {STR_VAR_1} su un\n"
	.string "amato {STR_VAR_2}.\p"
	.string "Vediamo con quanta passione il nostro\n"
	.string "autore sa esprimere l'amore per il {STR_VAR_2}!\l"
	.string "Hmhm…$"

gTVFanClubText01::
	.string "Uao!\n"
	.string "Che Lettera fantastica!$"

gTVFanClubText02::
	.string "Mi è piaciuta, la rileggo!$"

gTVFanClubText03::
	.string "Una bella Lettera va riletta\n"
	.string "e riletta!$"

gTVFanClubText04::
	.string "Il pezzo “{STR_VAR_3}” accentua\n"
	.string "davvero l'impatto emotivo!\p"
	.string "È una Lettera fantastica, con vera\n"
	.string "profondità di sentimenti!$"

gTVFanClubText05::
	.string "Soprattutto quel pezzo “{STR_VAR_3}”!\p"
	.string "Adoro come è usato “{STR_VAR_3}”!$"

gTVFanClubText06::
	.string "A proposito, e non è importante,\n"
	.string "ma “{STR_VAR_3}” è un detto fantastico.\p"
	.string "Ultimamente uso “{STR_VAR_3}” spesso\n"
	.string "nelle conversazioni.$"

gTVFanClubText07::
	.string "Se dovessi valutare questa lettera,\n"
	.string "le darei {STR_VAR_3} punti.\p"
	.string "La prossima volta mi aspetto una\n"
	.string "lettera ancora migliore, {STR_VAR_1}!\p"
	.string "Ops, guardate che ore sono?\n"
	.string "È ora di salutarci, alla prossima!$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequest:
	.string "Oh?\n"
	.string "Ti piacciono i POKéMON, per caso?\p"
	.string "Lavoro per la rete televisiva.\p"
	.string "Sto raccogliendo storie su POKéMON e\n"
	.string "ALLENATORI successe di recente.\p"
	.string "Se non ti dispiace, puoi parlarmi\n"
	.string "un po' di te?$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequestShort:
	.string "Sto raccogliendo storie su POKéMON e\n"
	.string "ALLENATORI successe di recente.\p"
	.string "Se non ti dispiace, puoi parlarmi\n"
	.string "un po' di te?$"

SlateportCity_OceanicMuseum_1F_Text_TellMeExperienceInvolvingPokemon:
	.string "Oh, davvero?\n"
	.string "Grazie!\p"
	.string "Allora raccontami qualcosa di\n"
	.string "interessante che ti è capitato\l"
	.string "con i POKéMON.$"

SlateportCity_OceanicMuseum_1F_Text_LetMeKnowIfYouHaveStory:
	.string "Oh, capisco…\p"
	.string "Beh, se hai una storia interessante\n"
	.string "da raccontare, fammelo sapere.$"

SlateportCity_OceanicMuseum_1F_Text_ThatsAllForInterview:
	.string "Oh, che bella storia!\p"
	.string "Farò in modo che la tua storia venga\n"
	.string "raccontata in televisione.\p"
	.string "Penso che andrà in onda presto,\n"
	.string "quindi resta in attesa.$"

SlateportCity_OceanicMuseum_1F_Text_BetterWriteUpStory:
	.string "Mmmh…\n"
	.string "Ho una bella storia per un programma TV.\p"
	.string "Meglio che la scriva in fretta!$"

gTVRecentHappeningsText00::
	.string "Ciao, è il momento di FATTI RECENTI.\p"
	.string "Per gli ALLENATORI di POKéMON ogni\n"
	.string "giorno è una storia da raccontare.\p"
	.string "Vogliamo farvi conoscere alcune di\n"
	.string "queste storie sui POKéMON.\p"
	.string "Oggi vi raccontiamo la storia\n"
	.string "dell'ALLENATORE {STR_VAR_1}.\p"
	.string "Cosa ha vissuto {STR_VAR_1} di recente?\n"
	.string "Scopriamolo.\p"
	.string "Vediamo…$"

gTVRecentHappeningsText01::
	.string "Non è stato istruttivo?\p"
	.string "La storia ci mostra chiaramente cosa\n"
	.string "ha vissuto {STR_VAR_1} di recente.\l"
	.string "È come se fossimo lì a testimoniarlo!$"

gTVRecentHappeningsText02::
	.string "“{STR_VAR_3}.” Questo\n"
	.string "dà risalto al racconto e profondità.$"

gTVRecentHappeningsText03::
	.string "“{STR_VAR_3}.”\n"
	.string "Dà al racconto un senso di luogo.\l"
	.string "Ci fa immaginare l'ambientazione.$"

gTVRecentHappeningsText04::
	.string "La parte “{STR_VAR_3}”\n"
	.string "del racconto è molto espressiva.$"

gTVRecentHappeningsText05::
	.string "{STR_VAR_1} ha raccontato una\n"
	.string "splendida storia con dei POKéMON.\p"
	.string "E ora anche la storia di {STR_VAR_1} è\n"
	.string "impressa indelebile nella tua anima.\p"
	.string "Per oggi è tutto.\n"
	.string "Sintonizzatevi la prossima volta.$"

gTVMassOutbreakText00::
	.string "Salve!\n"
	.string "È il momento di POKéMON NEWS.\p"
	.string "Abbiamo appena saputo di un evento\n"
	.string "molto raro.\p"
	.string "Ci sono segnalazioni di un'epidemia\n"
	.string "di {STR_VAR_2} nei dintorni\l"
	.string "di {STR_VAR_1}.\p"
	.string "{STR_VAR_2}, come saprete,\n"
	.string "è noto come un POKéMON raro\l"
	.string "e difficile da trovare.\p"
	.string "Sembra una rara occasione per\n"
	.string "vedere l'epidemia misteriosa di\l"
	.string "{STR_VAR_2} allo stato selvatico.\p"
	.string "Ecco le notizie di POKéMON NEWS.$"

gTV3CheersForPokeblocksText00::
	.string "MC: Speriamo che siate contenti,\n"
	.string "ecco “3 EVVIVA PER LE {POKEBLOCK}”!\p"
	.string "Oggi esaminiamo la {POKEBLOCK} preparata\n"
	.string "da {STR_VAR_1} e soci.\p"
	.string "Senza indugio, diamola\n"
	.string "al mio POKéMON gourmet GULPIN.\p"
	.string "… … … … … …\n"
	.string "… … … … … …$"

gTV3CheersForPokeblocksText01::
	.string "GULPIN: Gubi! Gubii!\p"
	.string "MC: E il verdetto è molto {STR_VAR_1}!\n"
	.string "GULPIN dice che sa di “{STR_VAR_2}!”\p"
	.string "Grazie mille, {STR_VAR_3}!$"

gTV3CheersForPokeblocksText02::
	.string "La miscelazione di {STR_VAR_1}\n"
	.string "lasciava a desiderare.\p"
	.string "Se sapesse miscelare meglio,\n"
	.string "il {POKEBLOCK} sarebbe più gustoso.$"

gTV3CheersForPokeblocksText03::
	.string "GULPIN: Gubi! Gubii!\p"
	.string "MC: Mmm… È troppo {STR_VAR_1}.\n"
	.string "GULPIN dice che sa di “{STR_VAR_2}!”\p"
	.string "Sembra che gli errori di {STR_VAR_3}\n"
	.string "abbiano rovinato la qualità…$"

gTV3CheersForPokeblocksText04::
	.string "Peccato che lo sforzo di {STR_VAR_1}\n"
	.string "sia stato sprecato.\p"
	.string "Speriamo che {STR_VAR_2} faccia\n"
	.string "una figura migliore la prossima volta!$"

gTV3CheersForPokeblocksText05::
	.string "Sintonizzatevi la prossima volta!\n"
	.string "Il nostro motto: “3 EVVIVA PER LE {POKEBLOCK}!”$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer::
	.string "Ciao!\p"
	.string "Sono un grande fan di {STR_VAR_1}.\n"
	.string "Cosa pensi di {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_ThatsWhatYouThink::
	.string "Capisco, capisco. Questo è ciò che pensi\n"
	.string "dell'ALLENATORE.$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer::
	.string "Hai completamente dimenticato\n"
	.string "{STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer2::
	.string "Sono un grande fan di {STR_VAR_1}.\n"
	.string "Cosa pensi di {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_HowStrongRateTrainer::
	.string "Quanto è forte {STR_VAR_1}\n"
	.string "su una scala da cento?$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer2::
	.string "Hai completamente dimenticato\n"
	.string "{STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_YouShouldMeetTrainer::
	.string "Oh, capisco!\n"
	.string "Dovresti conoscere {STR_VAR_1}, prima o poi.\l"
	.string "Sicuro diventeresti un fan anche tu!$"

LilycoveCity_PokemonTrainerFanClub_Text_ThankYouIllShareThisInfo::
	.string "Capisco, capisco.\p"
	.string "Grazie!\n"
	.string "È molto utile saperlo.\p"
	.string "Condividerò queste informazioni con gli\n"
	.string "altri fan di {STR_VAR_1} e ne parleremo.$"

LilycoveCity_PokemonTrainerFanClub_HopeYouCatchTVSpecial::
	.string "Presto ci sarà uno speciale TV\n"
	.string "su {STR_VAR_1}.\p"
	.string "Spero che lo guarderai!$"

gTVTrainerFanClubSpecialText00::
	.string "TRAINER FAN CLUB\n"
	.string "SPECIALE {STR_VAR_1}!\p"
	.string "Una presentazione speciale per\n"
	.string "i fan di {STR_VAR_1} in tutto HOENN!\p"
	.string "Oggi chiediamo: “Cosa pensa\n"
	.string "la gente di {STR_VAR_1}?”\p"
	.string "Abbiamo chiesto a {STR_VAR_2}\n"
	.string "come rappresentante degli ALLENATORI.\p"
	.string "Domanda: “In una parola, come\n"
	.string "descrivi {STR_VAR_1}?”\p"
	.string "Risposta: “{STR_VAR_3}.”\p"
	.string "Complimenti a {STR_VAR_2}!\n"
	.string "Che parere acuto!\p"
	.string "“{STR_VAR_3} {STR_VAR_1}.”\n"
	.string "Suona davvero bene!\p"
	.string "{STR_VAR_2} ha anche dato a {STR_VAR_1}\n"
	.string "un voto da 0 a 100.$"

gTVTrainerFanClubSpecialText01::
	.string "Il punteggio era di {STR_VAR_3} punti!\n"
	.string "È davvero un punteggio altissimo!\p"
	.string "{STR_VAR_2} deve tenere\n"
	.string "{STR_VAR_1} in grande stima.$"

gTVTrainerFanClubSpecialText02::
	.string "Il punteggio era di {STR_VAR_3} punti!\n"
	.string "È un buon punteggio.\p"
	.string "{STR_VAR_2} deve considerare\n"
	.string "{STR_VAR_1} un rivale.$"

gTVTrainerFanClubSpecialText03::
	.string "Il punteggio era di {STR_VAR_3} punti!\n"
	.string "È un punteggio piuttosto debole.\p"
	.string "{STR_VAR_2} deve considerare\n"
	.string "{STR_VAR_1} un semplice spalla.$"

gTVTrainerFanClubSpecialText04::
	.string "Il punteggio era di {STR_VAR_3} punto/i!\n"
	.string "È un punteggio pessimo.\p"
	.string "{STR_VAR_2} deve considerare\n"
	.string "{STR_VAR_1} un subalterno.$"

gTVTrainerFanClubSpecialText05::
	.string "Ecco fatto, gente!\p"
	.string "Credo che tutti abbiamo imparato\n"
	.string "qualcosa su {STR_VAR_1}.\p"
	.string "Per chiudere, vi lascio con\n"
	.string "le parole di {STR_VAR_2}.\p"
	.string "{STR_VAR_3} {STR_VAR_1}!$"

gTVNameRaterText00::
	.string "E ora, è il momento di…\n"
	.string "IL PROGRAMMA DELLO STRUZZANOMI.\p"
	.string "Leggo il destino dei tuoi POKéMON\n"
	.string "dal soprannome che hai scelto.\p"
	.string "Consigli è ciò che do, e sono\n"
	.string "consigli utili quelli che offro.\p"
	.string "Oggi leggerò il soprannome\n"
	.string "{STR_VAR_3} del POKéMON di {STR_VAR_1},\l"
	.string "{STR_VAR_2}.\p"
	.string "Hmhm…\p"
	.string "Hmm…\n"
	.string "Questo soprannome è…$"

gTVNameRaterText01::
	.string "Un soprannome che suggerisce talento in\n"
	.string "modi diversi.\p"
	.string "Esorto questo ALLENATORE ad avere\n"
	.string "coraggio e ad affrontare sfide.$"

gTVNameRaterText02::
	.string "Un soprannome che si sposa a\n"
	.string "meraviglia con {STR_VAR_1}, il nome dell'ALLENATORE.\p"
	.string "Suggerisce che formerete un'ottima\n"
	.string "squadra con tempi perfetti.$"

gTVNameRaterText03::
	.string "Un soprannome adatto a un esemplare\n"
	.string "unico di POKéMON!\p"
	.string "Se allevato bene, l'unicità di questo\n"
	.string "POKéMON sboccerà in pieno!$"

gTVNameRaterText04::
	.string "Un soprannome che nutrirà il lato\n"
	.string "affettuoso e premuroso dei POKéMON.\p"
	.string "Se allevato bene, questo POKéMON\n"
	.string "mostrerà un calore autentico!$"

gTVNameRaterText05::
	.string "Un ottimo soprannome che preannuncia\n"
	.string "grandi cose in arrivo.\p"
	.string "Sono curioso di sapere cosa riserverà\n"
	.string "il futuro a questo POKéMON.$"

gTVNameRaterText06::
	.string "Un buon soprannome che renderà il\n"
	.string "POKéMON sano e robusto!\p"
	.string "Quel POKéMON resterà in forma e\n"
	.string "forte per molto, molto tempo.$"

gTVNameRaterText07::
	.string "Un buon soprannome che renderà il\n"
	.string "POKéMON molto attivo!\p"
	.string "Penso che questo POKéMON sarà\n"
	.string "un forte combattente nelle lotte.$"

gTVNameRaterText08::
	.string "Un soprannome attraente che renderà\n"
	.string "il POKéMON molto affascinante!\p"
	.string "Non dubito che questo POKéMON sarà\n"
	.string "un gran seduttore alle GARE POKéMON.$"

gTVNameRaterText09::
	.string "Il soprannome {STR_VAR_1} si basa sulla\n"
	.string "lettera “{STR_VAR_3}.”\p"
	.string "Quella lettera è sostenuta dalla prima\n"
	.string "lettera “{STR_VAR_2},” che gli dà una solida\l"
	.string "presenza come soprannome.$"

gTVNameRaterText10::
	.string "Il soprannome {STR_VAR_1} è molto\n"
	.string "armonioso in modo piacevole.\p"
	.string "La presenza delle lettere “{STR_VAR_2}” e\n"
	.string "“{STR_VAR_3}”, beh, è davvero ottima!$"

gTVNameRaterText11::
	.string "Il soprannome {STR_VAR_1}, ha un\n"
	.string "che di sublime e fluido.\p"
	.string "Il passaggio dalla lettera “{STR_VAR_2}” a\n"
	.string "“{STR_VAR_3}” è davvero meraviglioso.$"

gTVNameRaterText12::
	.string "Esaminiamo altri esempi di bei\n"
	.string "soprannomi, vi va?$"

gTVNameRaterText13::
	.string "Ecco un esempio. Prendi una parte del\n"
	.string "nome dell'ALLENATORE {STR_VAR_1} e\l"
	.string "ottieni il bel soprannome {STR_VAR_2}{STR_VAR_3}.$"

gTVNameRaterText14::
	.string "Il soprannome {STR_VAR_2}{STR_VAR_3} funzionerebbe\n"
	.string "molto bene.$"

gTVNameRaterText15::
	.string "Il nome di specie del POKéMON,\n"
	.string "{STR_VAR_2}, potrebbe essere la base\l"
	.string "per creare il soprannome {STR_VAR_1}{STR_VAR_3}.$"

gTVNameRaterText16::
	.string "{STR_VAR_1}{STR_VAR_3} sarebbe un soprannome\n"
	.string "efficace.$"

gTVNameRaterText17::
	.string "Va sempre evitato l'uso del nome di\n"
	.string "un'altra specie di POKéMON.\p"
	.string "Per esempio, evitate di usare il nome di\n"
	.string "{STR_VAR_2} per creare {STR_VAR_1}{STR_VAR_3}.\l"
	.string "È inaccettabile.$"

gTVNameRaterText18::
	.string "Devo dire che {STR_VAR_1} è davvero\n"
	.string "un buon soprannome.\p"
	.string "Spero che l'ALLENATORE continui\n"
	.string "a trattare {STR_VAR_1} con amore.\p"
	.string "È tutto per la puntata di oggi.\n"
	.string "Alla prossima.$"

gTVPokemonAnglerText00::
	.string "PESCATORE DI {STR_VAR_2}\p"
	.string "ANNUNCIATORE: Ciao! Oggi avremo consigli\n"
	.string "sulla pesca di {STR_VAR_2}.\p"
	.string "GURU, che consiglio dai per\n"
	.string "catturare {STR_VAR_2}?\p"
	.string "GURU: Eh? Catturare {STR_VAR_2}?\n"
	.string "Beh, te lo dico, porta pazienza e\l"
	.string "aspetta. È questo il punto.\p"
	.string "Vedi {STR_VAR_1} laggiù?\n"
	.string "Quell'ALLENATORE è un buon esempio.\p"
	.string "Quell'ALLENATORE si è già fatto\n"
	.string "sfuggire {STR_VAR_3} POKéMON.\p"
	.string "Ma {STR_VAR_1} è lì che aspetta. Non molla.\n"
	.string "È la legge per catturare {STR_VAR_2}.\p"
	.string "ANNUNCIATORE: Capisco…\p"
	.string "Oh! {STR_VAR_1} ha finalmente preso un\n"
	.string "{STR_VAR_2}!\p"
	.string "L'ALLENATORE sembra quasi in lacrime\n"
	.string "dalla gioia!\p"
	.string "Vedendo quell'espressione, mi sta\n"
	.string "venendo voglia di pescare!\p"
	.string "Spettatori, prendetelo come spunto e\n"
	.string "provate a pescare {STR_VAR_2}?\p"
	.string "Alla prossima puntata, addio e\n"
	.string "buona pesca a tutti!$"

gTVPokemonAnglerText01::
	.string "PESCATORE DI {STR_VAR_2}\p"
	.string "ANNUNCIATORE: Ciao! Oggi avremo consigli\n"
	.string "sulla pesca di {STR_VAR_2}.\p"
	.string "GURU, che consiglio dai per\n"
	.string "catturare {STR_VAR_2}?\p"
	.string "GURU: Eh? Catturare {STR_VAR_2}?\n"
	.string "Beh, te lo dico, usa la CANNA da pesca\l"
	.string "con vigore!\p"
	.string "Vedi {STR_VAR_1} laggiù?\n"
	.string "Vedi come maneggia la CANNA?\p"
	.string "Quell'ALLENATORE ne ha già presi\n"
	.string "{STR_VAR_3} di fila.\p"
	.string "ANNUNCIATORE: È incredibile!\n"
	.string "Sembra una tempesta…\p"
	.string "Vedere una tecnica di quel livello mi\n"
	.string "fa venire voglia di pescare.\p"
	.string "Spettatori, prendetelo come spunto e\n"
	.string "provate a pescare {STR_VAR_2}?\p"
	.string "Alla prossima puntata, addio e\n"
	.string "buona pesca a tutti!$"

gTVPokemonTodayFailedText00::
	.string "Ciao!\p"
	.string "È l'ora di POKéMON TODAY!\p"
	.string "SORELLONA: Ciao! Siete tutti pieni di\n"
	.string "energia oggi?\p"
	.string "Oggi vediamo i POKéMON di {STR_VAR_1}:\n"
	.string "{STR_VAR_2}!\p"
	.string "FRATELLONE: Sì! Ecco cosa faremo\n"
	.string "adesso!$"

gTVPokemonTodayFailedText01::
	.string "Oh!\n"
	.string "A proposito di {STR_VAR_1}…\p"
	.string "SORELLONA, ho visto quel GENTILUOMO\n"
	.string "con i miei occhi!\p"
	.string "SORELLONA: Oh, e cosa hai visto?\p"
	.string "FRATELLONE: Beh, ho fatto un viaggio\n"
	.string "a {STR_VAR_2}.\p"
	.string "Ed è lì che mi sono imbattuto in\n"
	.string "{STR_VAR_1}, che tentava di catturare\l"
	.string "il POKéMON {STR_VAR_3}, ma…$"

gTVPokemonTodayFailedText02::
	.string "Il POKéMON è riuscito a scappare!\p"
	.string "Ha finito per sprecare tutte queste\n"
	.string "POKé BALL: {STR_VAR_2}!\p"
	.string "Dovevate vedere la faccia\n"
	.string "di delusione di {STR_VAR_1} quando\l"
	.string "il POKéMON è fuggito!$"

gTVPokemonTodayFailedText03::
	.string "Ma {STR_VAR_1} ha sbagliato e ha fatto\n"
	.string "svenire il POKéMON!\p"
	.string "Ha finito per sprecare tutte queste\n"
	.string "POKé BALL: {STR_VAR_2}!\p"
	.string "Dovevate vedere la faccia\n"
	.string "di sgomento di {STR_VAR_1}\l"
	.string "quando il POKéMON è svenuto!$"

gTVPokemonTodayFailedText04::
	.string "SORELLONA: Ehi, tu!\n"
	.string "Non è carino!\p"
	.string "Non si ride delle disgrazie\n"
	.string "degli altri!\p"
	.string "Oh, povero {STR_VAR_1}.\n"
	.string "Che peccato!\p"
	.string "FRATELLONE: È vero!\n"
	.string "Scusa, non riderò più.$"

gTVPokemonTodayFailedText05::
	.string "SORELLONA: Ahahah…\p"
	.string "FRATELLONE: Ehi!\n"
	.string "Anche tu hai riso!\p"
	.string "SORELLONA: Eh?!\p"
	.string "Io non ho riso!\n"
	.string "Davvero, non ho riso!\p"
	.string "Oh, povero {STR_VAR_1}.\n"
	.string "Che peccato!\p"
	.string "FRATELLONE: …$"

gTVPokemonTodayFailedText06::
	.string "SORELLONA: Basta sciocchezze!\n"
	.string "Vediamo il POKéMON di oggi…\p"
	.string "Eh?\n"
	.string "È già finito il tempo?\p"
	.string "Oh no!\n"
	.string "Non abbiamo parlato di nessun POKéMON!\p"
	.string "FRATELLONE: Alla prossima!\p"
	.string "SORELLONA: Ehi, non chiudere la\n"
	.string "puntata senza di me!$"

gTVPokemonTodaySuccessfulText00::
	.string "Ciao!\p"
	.string "È l'ora di POKéMON TODAY!\p"
	.string "SORELLONA: Ciao! Siete tutti pieni di\n"
	.string "energia oggi?\p"
	.string "Oggi vediamo i POKéMON di {STR_VAR_1}:\n"
	.string "{STR_VAR_2}!\p"
	.string "FRATELLONE: Sì! Ecco cosa faremo\n"
	.string "adesso!$"

gTVPokemonTodaySuccessfulText01::
	.string "SORELLONA: {STR_VAR_1} ha dato il nome\n"
	.string "{STR_VAR_3} al {STR_VAR_2}!\p"
	.string "Sembra che {STR_VAR_3} riceva cure\n"
	.string "affettuose e attente!$"

gTVPokemonTodaySuccessfulText02::
	.string "BIG BRO: L'ALLENATORE ha dovuto lanciare\n"
	.string "questi POKé BALL per prenderlo: {STR_VAR_3}!\p"
	.string "Alla fine è bastata una sola {STR_VAR_2}\n"
	.string "per catturarlo!$"

gTVPokemonTodaySuccessfulText03::
	.string "SORELLONA: Se è stato così facile\n"
	.string "catturarlo, era destino che\l"
	.string "{STR_VAR_1} e il {STR_VAR_2} si trovassero!$"

gTVPokemonTodaySuccessfulText04::
	.string "SORELLONA: Wow! Che bello!\p"
	.string "Ma si sa, un POKéMON che richiede\n"
	.string "molta fatica per essere catturato\l"
	.string "si guadagna l'amore del suo ALLENATORE!$"

gTVPokemonTodaySuccessfulText05::
	.string "SORELLONA: Il {STR_VAR_2} di {STR_VAR_1} è\n"
	.string "un POKéMON memorabile: per catturarlo\l"
	.string "è servita una preziosa MASTER BALL!\p"
	.string "FRATELLONE: Wow! Che grande!\p"
	.string "SORELLONA: {STR_VAR_1} ci teneva davvero\n"
	.string "a quel {STR_VAR_2}, altroché!$"

gTVPokemonTodaySuccessfulText06::
	.string "FRATELLONE: E poi ha dato il nome\n"
	.string "{STR_VAR_3} a quel {STR_VAR_2}…\p"
	.string "Si capisce bene che fiuto ha\n"
	.string "{STR_VAR_1} come ALLENATORE.\p"
	.string "SORELLONA: Concordo in pieno!$"

gTVPokemonTodaySuccessfulText07::
	.string "Se fossi io, darei quel nome\n"
	.string "a qualcosa tipo questo {STR_VAR_3}!\p"
	.string "FRATELLONE: Whoa! Potrebbe nascere\n"
	.string "qualcosa di nuovo!$"

gTVPokemonTodaySuccessfulText08::
	.string "{STR_VAR_2} il {STR_VAR_1}?\n"
	.string "Non suona perfetto?\p"
	.string "Le lettere e tutto il resto…\n"
	.string "suonano benissimo per il POKéMON\l"
	.string "{STR_VAR_1}!\p"
	.string "FRATELLONE: Sì, è vero!$"

gTVPokemonTodaySuccessfulText09::
	.string "Che io sappia, nessun ALLENATORE ha\n"
	.string "mai dato il nome {STR_VAR_2} al suo\l"
	.string "{STR_VAR_1}!\p"
	.string "FRATELLONE: Questo dimostra quanto\n"
	.string "buon gusto abbia l'ALLENATORE nello\l"
	.string "scegliere i nomi!$"

gTVPokemonTodaySuccessfulText10::
	.string "La prossima volta che catturo un\n"
	.string "POKéMON, gli darò il nome {STR_VAR_2}.\p"
	.string "FRATELLONE: Eh? Pure io!\n"
	.string "Userò anche io il nome {STR_VAR_2}!$"

gTVPokemonTodaySuccessfulText11::
	.string "SORELLONA: Oh no!\n"
	.string "Guarda che ora!\p"
	.string "Beh, gente, per oggi è tutto.\n"
	.string "Alla prossima!\p"
	.string "FRATELLONE: Ricorda, la prossima volta\n"
	.string "sotto ai riflettori potresti esserci tu!$"

SmartShopper_Text_Intro::
	.string "Ciao!\p"
	.string "È il momento di SHOPPER INTELLIGENTE.\p"
	.string "INTERVISTATORE: Come va, spettatori?\p"
	.string "Oggi visitiamo un negozio\n"
	.string "a {STR_VAR_2}.\p"
	.string "Vediamo quali sono stati i più\n"
	.string "venduti di recente.$"

SmartShopper_Text_ClerkNormal::
	.string "Intervistiamo il commesso per sapere\n"
	.string "tutto.\p"
	.string "Ciao, come vanno gli affari?\p"
	.string "COMMESSO: Oh, vanno benissimo.\p"
	.string "Di recente {STR_VAR_2} sta vendendo\n"
	.string "particolarmente bene.\p"
	.string "Proprio l'altro giorno un ALLENATORE\n"
	.string "di nome {STR_VAR_1} ha comprato {STR_VAR_3}.$"

SmartShopper_Text_RandomComment1::
	.string "INTERVISTATORE: Ha comprato\n"
	.string "{STR_VAR_3} {STR_VAR_2}? Che bottino!\p"
	.string "Se posso dirlo, {STR_VAR_1} doveva\n"
	.string "far scorta per un lungo viaggio\l"
	.string "in terre lontane.\p"
	.string "In viaggio i {STR_VAR_2} sono\n"
	.string "importantissimi!$"

SmartShopper_Text_RandomComment2::
	.string "INTERVISTATORE: A proposito di\n"
	.string "{STR_VAR_2}, ne ho comprati {STR_VAR_3}\l"
	.string "di recente.\p"
	.string "Del resto, {STR_VAR_2} è un oggetto forte!$"

SmartShopper_Text_RandomComment3::
	.string "INTERVISTATORE: {STR_VAR_2}?!\n"
	.string "Ma {STR_VAR_3} in una volta?!\p"
	.string "Non pensavo ci fosse gente\n"
	.string "che ne compra così tanti.\p"
	.string "Cielo, io posso permettermene solo\n"
	.string "uno o due alla volta…$"

SmartShopper_Text_RandomComment4::
	.string "INTERVISTATORE: Una volta ne comprai\n"
	.string "un bel po' dell'oggetto {STR_VAR_2}.\p"
	.string "Ma erano troppi, alla fine.\n"
	.string "Me ne sono pentito…\p"
	.string "Da allora compro solo lo stretto\n"
	.string "necessario…\p"
	.string "Ops!\p"
	.string "Non parliamo di me!$"

SmartShopper_Text_SecondItem::
	.string "COMMESSO: {STR_VAR_1} ha comprato anche\n"
	.string "l'oggetto {STR_VAR_2}, ben {STR_VAR_3}.\p"
	.string "INTERVISTATORE: Oh, che bravo.\n"
	.string "Anche {STR_VAR_2} è un ottimo oggetto.$"

SmartShopper_Text_ThirdItem::
	.string "COMMESSO: E l'ALLENATORE ha comprato\n"
	.string "anche {STR_VAR_3} dell'oggetto {STR_VAR_2}.$"

SmartShopper_Text_DuringSale::
	.string "COMMESSO: E c'era pure un grande saldo.\n"
	.string "Che acquisto intelligente.$"

SmartShopper_Text_OutroNormal::
	.string "INTERVISTATORE: Mmm… {STR_VAR_1} è proprio\n"
	.string "un abile cacciatore di affari!\p"
	.string "In totale, la spesa di {STR_VAR_1} è stata…\p"
	.string "¥{STR_VAR_2}?!\n"
	.string "Che cifra incredibile!\p"
	.string "Ops! Il tempo è scaduto!\n"
	.string "Ci vediamo alla prossima puntata!$"

SmartShopper_Text_IsVIP::
	.string "COMMESSO: {STR_VAR_1} è un cliente VIP,\n"
	.string "non c'è dubbio.$"

SmartShopper_Text_ClerkMax::
	.string "Intervistiamo il commesso per sapere\n"
	.string "tutto.\p"
	.string "Ciao, come vanno gli affari?\p"
	.string "COMMESSO: Oh, incredibilmente bene.\n"
	.string "È quasi travolgente.\p"
	.string "Di recente un ALLENATORE di nome {STR_VAR_1}\n"
	.string "ha comprato l'oggetto {STR_VAR_2} in blocco.\p"
	.string "L'ALLENATORE ha quasi esaurito le nostre\n"
	.string "scorte di {STR_VAR_2}.\p"
	.string "Non avrei mai sognato che un cliente\n"
	.string "avesse bisogno di tanti {STR_VAR_2}.\l"
	.string "È incredibile!\p"
	.string "INTERVISTATORE: Quindi tipo 100\n"
	.string "o 200 venduti?\p"
	.string "COMMESSO: Oh, no, molti di più!\p"
	.string "INTERVISTATORE: Oh, santo cielo!\n"
	.string "{STR_VAR_1} dev'essere un cliente speciale!\p"
	.string "COMMESSO: {STR_VAR_1} è un cliente VIP,\n"
	.string "non c'è dubbio.$"

SmartShopper_Text_OutroMax::
	.string "INTERVISTATORE: Mmm…\n"
	.string "È straordinario.\p"
	.string "Ma perché mai un ALLENATORE doveva\n"
	.string "comprare così tanti?\p"
	.string "… …\p"
	.string "Il mistero s'infittisce, ma il tempo\n"
	.string "per oggi è finito.\l"
	.string "Ci vediamo alla prossima puntata!\p"
	.string "Eppure {STR_VAR_1} resta un enigma…$"

gTVWorldOfMastersText00::
	.string "IL MONDO DEI MAESTRI\p"
	.string "Ciao, spettatori.\p"
	.string "Forse conoscete un TRAINER\n"
	.string "di nome {STR_VAR_1}.\p"
	.string "{STR_VAR_1} è famoso come maestro\n"
	.string "nel catturare POKéMON.\p"
	.string "La ricerca di POKéMON di {STR_VAR_1} si basa\n"
	.string "tutta su una attenta ricerca a piedi.\p"
	.string "In un giorno memorabile, il TRAINER\n"
	.string "ha camminato per {STR_VAR_2} passi.\p"
	.string "Il totale dei POKéMON catturati\n"
	.string "quel giorno ha raggiunto {STR_VAR_3}!$"

gTVWorldOfMastersText01::
	.string "Quella straordinaria impresa è stata\n"
	.string "possibile grazie alla fiducia tra\l"
	.string "il TRAINER e {STR_VAR_1}.$"

gTVWorldOfMastersText02::
	.string "Il maestro ha catturato l'ultimo\n"
	.string "{STR_VAR_3} del giorno vicino a {STR_VAR_2}.\p"
	.string "A quanto pare quel POKéMON gode\n"
	.string "di uno status speciale da record.\p"
	.string "I TRAINER abili dovrebbero essere spinti\n"
	.string "a battere questo bel record.\p"
	.string "È tutto per oggi.\n"
	.string "Alla prossima puntata.$"

gTVTodaysRivalTrainerText00::
	.string "L'ALLENATORE RIVALE DI OGGI!\p"
	.string "Ciao, colleghi ALLENATORI!\n"
	.string "Come va oggi?\p"
	.string "Oggi, come ogni giorno,\n"
	.string "esamineremo uno dei nostri rivali!$"

gTVTodaysRivalTrainerText07::
	.string "L'ALLENATORE rivale di oggi è {STR_VAR_1},\n"
	.string "che ora è nei pressi di {STR_VAR_3}.\p"
	.string "{STR_VAR_1} ha finora registrato\n"
	.string "{STR_VAR_2} POKéMON nel POKéDEX.$"

gTVTodaysRivalTrainerText08::
	.string "L'ALLENATORE rivale di oggi è {STR_VAR_1},\n"
	.string "che ora è in una BASE SEGRETA.\p"
	.string "{STR_VAR_1} ha finora registrato\n"
	.string "{STR_VAR_2} POKéMON nel POKéDEX.$"

gTVTodaysRivalTrainerText09::
	.string "L'ALLENATORE rivale di oggi è {STR_VAR_1}.\p"
	.string "Finora {STR_VAR_1} ha registrato\n"
	.string "{STR_VAR_2} POKéMON nel POKéDEX.$"

gTVTodaysRivalTrainerText10::
	.string "L'ALLENATORE rivale di oggi è {STR_VAR_1},\n"
	.string "che ora è su un traghetto.\p"
	.string "{STR_VAR_1} ha finora registrato\n"
	.string "{STR_VAR_2} POKéMON nel POKéDEX.$"

	.string "$"

gTVTodaysRivalTrainerText01::
	.string "Quante MEDAGLIE ha il nostro rivale?\n"
	.string "Il numero è {STR_VAR_1}!$"

gTVTodaysRivalTrainerText02::
	.string "Ma il nostro rivale non ha ottenuto\n"
	.string "nemmeno una MEDAGLIA!$"

gTVTodaysRivalTrainerText03::
	.string "Il nostro rivale non ha ottenuto un solo\n"
	.string "Simbolo del PARCO LOTTA.$"

gTVTodaysRivalTrainerText04::
	.string "Vediamo quanti Simboli del PARCO LOTTA\n"
	.string "ha il nostro rivale.\p"
	.string "Simboli Oro: {STR_VAR_1}!\n"
	.string "Simboli Argento: {STR_VAR_2}!$"

gTVTodaysRivalTrainerText05::
	.string "Il nostro rivale ha raccolto {STR_VAR_1} Punti\n"
	.string "Lotta al PARCO LOTTA.$"

gTVTodaysRivalTrainerText06::
	.string "Quindi, come sei messo\n"
	.string "in confronto a {STR_VAR_1}?\p"
	.string "L'avventura continua!\p"
	.string "Colleghi ALLENATORI!\p"
	.string "Continuiamo tutti ad andare avanti\n"
	.string "e a superare i rivali!$"

TrendWatcher_Text_Intro::
	.string "RETE OSSERVATREND DI DEWFORD!\p"
	.string "MC: Ehi, come va?\n"
	.string "Vi teniamo aggiornati sulle ultime\l"
	.string "mode di DEWFORD.\p"
	.string "Il nostro ospite è questo vecchio che\n"
	.string "è famoso per essere l'autorità\l"
	.string "su tutto ciò che riguarda DEWFORD.\p"
	.string "Anziano: Felice di essere qui.\p"
	.string "MC: Andiamo al dunque, forza.\p"
	.string "Cosa ci dici su ciò che va di moda\n"
	.string "tra la brava gente di DEWFORD?\p"
	.string "Anziano: {STR_VAR_1} {STR_VAR_2}.\p"
	.string "MC: {STR_VAR_1} {STR_VAR_2},\n"
	.string "dici?\p"
	.string "Anziano: No.\p"
	.string "{STR_VAR_1} {STR_VAR_2} non\n"
	.string "è mai diventato popolare.\p"
	.string "Vuoi sentirne parlare?\p"
	.string "MC: Ehm, no. Ciò che vogliamo sapere è\n"
	.string "cosa va di moda adesso…$"

@ Identical to below, may have been different in other languages
TrendWatcher_Text_MaleTaughtMePhrase::
	.string "Anziano: {STR_VAR_1} {STR_VAR_2}\n"
	.string "è ciò che mi ha insegnato {STR_VAR_3} da\l"
	.string "LITTLEROOT come tendenza…$"

TrendWatcher_Text_FemaleTaughtMePhrase::
	.string "Anziano: {STR_VAR_1} {STR_VAR_2}\n"
	.string "è ciò che mi ha insegnato {STR_VAR_3} da\l"
	.string "LITTLEROOT come tendenza…$"

TrendWatcher_Text_PhraseWasHopeless::
	.string "Ma è stato del tutto inutile.\p"
	.string "Festival {STR_VAR_1} {STR_VAR_2}!\p"
	.string "Gara {STR_VAR_1} {STR_VAR_2}!\p"
	.string "Ho provato a insegnarlo a tutti\n"
	.string "come meglio potevo, ma…\p"
	.string "Forse la parte {STR_VAR_1} non\n"
	.string "era giusta…\p"
	.string "MC: Ehm, scusa, amico, devo\n"
	.string "sentire cosa va ora…$"

@ Identical to below, may have been different in other languages
TrendWatcher_Text_MaleTellMeBigger::
	.string "Anziano: {STR_VAR_3}!\n"
	.string "Ti prego, dimmi qualcosa di più forte\l"
	.string "di quel {STR_VAR_1} {STR_VAR_2}!$"

TrendWatcher_Text_FemaleTellMeBigger::
	.string "Anziano: {STR_VAR_3}!\n"
	.string "Ti prego, dimmi qualcosa di più forte\l"
	.string "di quel {STR_VAR_1} {STR_VAR_2}!$"

TrendWatcher_Text_Outro::
	.string "MC: …Ehm… Bene, ecco a voi,\n"
	.string "gente alla moda!\p"
	.string "{STR_VAR_1} {STR_VAR_2}…ehm…\n"
	.string "Non è diventato di moda a DEWFORD!\p"
	.string "Il mio tempo è scaduto. Ci vediamo!\p"
	.string "Anziano: {STR_VAR_1} {STR_VAR_2}!$"

gTVHoennTreasureInvestigatorsText00::
	.string "INVESTIGATORI DI TESORI DI HOENN!\p"
	.string "Ciao, gente!\n"
	.string "Trovato oggetti segreti ultimamente?\p"
	.string "Come sempre, esaminiamo le segnalazioni\n"
	.string "di segreti da ogni dove!\p"
	.string "Iniziamo con una Lettera.\n"
	.string "Dice: “{STR_VAR_1} scoperto!”$"

gTVHoennTreasureInvestigatorsText01::
	.string "Uao, meglio controllare questa Lettera!\n"
	.string "Ve la leggo io.\p"
	.string "…Cari INVESTIGATORI,\n"
	.string "spero stiate bene.\p"
	.string "Di recente ho visto {STR_VAR_2} da qualche\n"
	.string "parte vicino a {STR_VAR_3}.\p"
	.string "L'ALLENATORE ha trovato l'oggetto\n"
	.string "{STR_VAR_1}. Che invidia.\p"
	.string "…Beh, ben fatto, {STR_VAR_2}!\p"
	.string "Spettatori, fatevi ispirare e\n"
	.string "accendete i vostri DETECTOR e cercate!\p"
	.string "Aspetto notizie emozionanti\n"
	.string "da tutti voi!$"

gTVHoennTreasureInvestigatorsText02::
	.string "Uao, meglio controllare questa Lettera!\n"
	.string "Ve la leggo io.\p"
	.string "…Cari INVESTIGATORI,\n"
	.string "spero stiate bene.\p"
	.string "Di recente ho visto {STR_VAR_2} su un traghetto.\p"
	.string "L'ALLENATORE ha trovato l'oggetto\n"
	.string "{STR_VAR_1}. Che invidia.\p"
	.string "…Beh, ben fatto, {STR_VAR_2}!\p"
	.string "Spettatori, fatevi ispirare e\n"
	.string "accendete i vostri DETECTOR e cercate!\p"
	.string "Aspetto notizie emozionanti\n"
	.string "da tutti voi!$"

gTVFindThatGamerText00::
	.string "TROVA IL GIOCATORE!\p"
	.string "Ehi, giocatori!\n"
	.string "Come gira il vostro {STR_VAR_2}?\p"
	.string "Come sempre, puntiamo il Riflettore\n"
	.string "su un raro ALLENATORE passato al\l"
	.string "GAME CORNER!\p"
	.string "Oggi il nostro giocatore n. 1 è…\n"
	.string "{STR_VAR_1}!$"

gTVFindThatGamerText01::
	.string "{STR_VAR_1} giocò a {STR_VAR_2}\n"
	.string "e vinse {STR_VAR_3} GETTONI rari.\p"
	.string "“Quando arriva {STR_VAR_1}, dobbiamo\n"
	.string "avere abbastanza GETTONI.”\p"
	.string "È ciò che mormorano i commessi\n"
	.string "della SALA GIOCHI quando gioca!\p"
	.string "Spettatori, tenete d'occhio i GETTONI\n"
	.string "come {STR_VAR_1} se andate alla SALA\l"
	.string "GIOCHI a giocare a {STR_VAR_2}.\p"
	.string "In diretta dalla SALA GIOCHI,\n"
	.string "dove si sente l'emozione!\p"
	.string "È tutto per oggi!$"

gTVFindThatGamerText02::
	.string "{STR_VAR_1} ha giocato a {STR_VAR_2}\n"
	.string "e ha perso {STR_VAR_3} gettoni.\p"
	.string "“Quando arriva {STR_VAR_1}, le nostre\n"
	.string "vendite di gettoni salgono.”\p"
	.string "È ciò che dicono i commessi del CASINÒ\n"
	.string "quando il nostro giocatore è in azione!$"

gTVFindThatGamerText03::
	.string "Spettatori, tenete d'occhio i GETTONI\n"
	.string "come {STR_VAR_1} se andate al GAME\l"
	.string "CORNER a giocare a {STR_VAR_2}.\p"
	.string "In diretta dal GAME CORNER,\n"
	.string "dove si sente l'emozione!\p"
	.string "È tutto per oggi!$"

gTVBreakingNewsText00::
	.string "ULTIM'ORA TV!$"

gTVBreakingNewsText01::
	.string "Raro {STR_VAR_2} catturato da\n"
	.string "{STR_VAR_1}!\p"
	.string "Siamo in diretta dalle vicinanze di\n"
	.string "{STR_VAR_3}!\p"
	.string "{STR_VAR_1} ha catturato con successo\n"
	.string "un raro {STR_VAR_2} qui poco fa!$"

gTVBreakingNewsText02::
	.string "Quando {STR_VAR_1} ha incontrato il raro\n"
	.string "{STR_VAR_2}, l'ALLENATORE ha mandato in campo\l"
	.string "il POKéMON {STR_VAR_3}.$"

gTVBreakingNewsText03::
	.string "In battaglia, il numero di POKé\n"
	.string "BALL lanciate dall'ALLENATORE è stato {STR_VAR_1}.\p"
	.string "Alla fine, il POKéMON raro è stato\n"
	.string "catturato con l'ultima {STR_VAR_2} usata.$"

gTVBreakingNewsText04::
	.string "In that instant, {STR_VAR_2}\n"
	.string "echoed with {STR_VAR_1}'s roars of\l"
	.string "triumphant joy.\p"
	.string "I must say I'm a little envious of\n"
	.string "{STR_VAR_1}. I'd love to roar, too.\p"
	.string "…That ends the live feed from\n"
	.string "the happy scene!$"

gTVBreakingNewsText05::
	.string "{STR_VAR_1} non riesce a catturare un raro\n"
	.string "{STR_VAR_2}!\p"
	.string "Siamo in diretta dalle vicinanze di\n"
	.string "{STR_VAR_3}!\p"
	.string "Proprio qui {STR_VAR_1} non è riuscito\n"
	.string "a catturare un raro {STR_VAR_2}!$"

gTVBreakingNewsText06::
	.string "Quando {STR_VAR_1} ha incontrato il raro\n"
	.string "{STR_VAR_2}, l'ALLENATORE ha mandato in campo\l"
	.string "il POKéMON {STR_VAR_3}.$"

gTVBreakingNewsText07::
	.string "L'ALLENATORE ha fatto usare a {STR_VAR_2}\n"
	.string "la mossa {STR_VAR_1}.\p"
	.string "Senza volerlo, l'ALLENATORE\n"
	.string "ha fatto svenire il POKéMON raro…$"

gTVBreakingNewsText12::
	.string "Però {STR_VAR_1} si è fatto prendere dal\n"
	.string "panico alla vista del raro {STR_VAR_2}.\p"
	.string "In preda alla Confusione, l'ALLENATORE\n"
	.string "ha ordinato a {STR_VAR_3} di attaccare.\p"
	.string "Senza volerlo, l'ALLENATORE\n"
	.string "ha fatto svenire il POKéMON raro.$"

gTVBreakingNewsText08::
	.string "In that instant, {STR_VAR_2}\n"
	.string "echoed with {STR_VAR_1}'s shrieks of\l"
	.string "frustration…$"

gTVBreakingNewsText09::
	.string "However, {STR_VAR_1} seemed to run\n"
	.string "out of POKé BALLS.\p"
	.string "The TRAINER had to break off\n"
	.string "the battle with the rare {STR_VAR_2}.\p"
	.string "In that instant, {STR_VAR_3}\n"
	.string "echoed with {STR_VAR_1}'s shrieks of\l"
	.string "frustration…$"

gTVBreakingNewsText10::
	.string "However, the {STR_VAR_2} fled without\n"
	.string "warning.\p"
	.string "In that instant, {STR_VAR_3}\n"
	.string "echoed with {STR_VAR_1}'s shrieks of\l"
	.string "frustration…$"

gTVBreakingNewsText11::
	.string "Devo dire che mi spiace per {STR_VAR_1}.\n"
	.string "Mi fa venire voglia di urlare anch'io.\p"
	.string "…Qui termina il collegamento\n"
	.string "dalla scena triste!$"

gTVSecretBaseVisitText00::
	.string "Ciao a tutti!\n"
	.string "È di nuovo ora di\l"
	.string "una VISITA ALLA BASE SEGRETA.\p"
	.string "Oggi visitiamo la BASE SEGRETA\n"
	.string "di {STR_VAR_1}.\p"
	.string "Come ha personalizzato {STR_VAR_1}\n"
	.string "la BASE SEGRETA?\p"
	.string "Scopriamolo!\n"
	.string "… … … … … …$"

gTVSecretBaseVisitText01::
	.string "Oh!\n"
	.string "Che meraviglia!\p"
	.string "Questo {STR_VAR_2}…\n"
	.string "Non è ciò che ci si aspetterebbe\l"
	.string "di trovare qui!$"

gTVSecretBaseVisitText02::
	.string "Oh!\n"
	.string "Che roba!\p"
	.string "Non c'è un solo pezzo\n"
	.string "di mobilio o oggetto d'arredo!\p"
	.string "I comuni mortali non potrebbero\n"
	.string "imitare questa audacia!\p"
	.string "È semplice, ma esplode, sì,\n"
	.string "esplode di selvatichezza!\p"
	.string "Ti faccio i miei complimenti, {STR_VAR_1}.\n"
	.string "Dovevi essere tu!$"

gTVSecretBaseVisitText03::
	.string "Oh! Capisco!\n"
	.string "Con perfetta chiarezza, lo vedo!\p"
	.string "Questo {STR_VAR_2} qui…\n"
	.string "Manda un messaggio efficace!$"

gTVSecretBaseVisitText04::
	.string "Oh! Capisco!\n"
	.string "Con perfetta chiarezza, lo vedo!\p"
	.string "Questo spazio è tenuto di proposito\n"
	.string "libero da oggetti d'arredo!\p"
	.string "Manda un messaggio efficace!$"

gTVSecretBaseVisitText05::
	.string "Uauuu!\p"
	.string "L'abbinamento di {STR_VAR_2}\n"
	.string "con {STR_VAR_3}!\p"
	.string "È una combinazione da sogno\n"
	.string "se mai ce n'è stata una!$"

gTVSecretBaseVisitText06::
	.string "Uauu!\p"
	.string "La posizione di questo {STR_VAR_2}\n"
	.string "proprio qui…\p"
	.string "Ha una presenza che riempie\n"
	.string "tutta la BASE SEGRETA!$"

gTVSecretBaseVisitText07::
	.string "Uauu!\p"
	.string "Qui non c'è nulla.\p"
	.string "Questo spazio vuoto ha un effetto\n"
	.string "su tutta la BASE SEGRETA.$"

gTVSecretBaseVisitText08::
	.string "Oh!\n"
	.string "Ecco che arriva {STR_VAR_1}!\l"
	.string "Sfidiamo l'ALLENATORE!\p"
	.string "… … … … … …\n"
	.string "… … … … … …$"

gTVSecretBaseVisitText09::
	.string "Sigh…\n"
	.string "I've got to hand it to {STR_VAR_1}.\p"
	.string "The TRAINER's POKéMON were truly\n"
	.string "worthy of the CHAMPION's title.\p"
	.string "They gave ample proof of {STR_VAR_1}'s\n"
	.string "toughness as a TRAINER.\p"
	.string "That the {STR_VAR_2} knew the move\n"
	.string "{STR_VAR_3}…\p"
	.string "It shows you what sort of a TRAINER\n"
	.string "{STR_VAR_1} is.\p"
	.string "Certainly, it was quite a lesson!$"

gTVSecretBaseVisitText10::
	.string "Aiyeeh!\n"
	.string "I've got to hand it to {STR_VAR_1}.\p"
	.string "The TRAINER's POKéMON were\n"
	.string "monstrously tough!\p"
	.string "They gave ample proof of {STR_VAR_1}'s\n"
	.string "tenacity as a TRAINER.\p"
	.string "That the {STR_VAR_2} knew the move\n"
	.string "{STR_VAR_3}…\p"
	.string "It shows you what sort of a TRAINER\n"
	.string "{STR_VAR_1} is.\p"
	.string "Certainly, it was quite a lesson!$"

gTVSecretBaseVisitText11::
	.string "Uau!\n"
	.string "Devo proprio riconoscerlo a {STR_VAR_1}.\p"
	.string "I POKéMON di quel TRAINER erano\n"
	.string "allenati in modo equilibrato.\p"
	.string "Hanno dimostrato la cura di {STR_VAR_1}\n"
	.string "come TRAINER.\p"
	.string "Che il {STR_VAR_2} conosca la mossa\n"
	.string "{STR_VAR_3}…\p"
	.string "Dice molto sul tipo di TRAINER\n"
	.string "che è {STR_VAR_1}.\p"
	.string "Certo, è stata una bella lezione!$"

gTVSecretBaseVisitText12::
	.string "Well, well!\n"
	.string "I've got to hand it to {STR_VAR_1}.\p"
	.string "The TRAINER's POKéMON showed\n"
	.string "great promise for future growth.\p"
	.string "They represented {STR_VAR_1}'s\n"
	.string "hopes and dreams.\p"
	.string "That the {STR_VAR_2} knew the move\n"
	.string "{STR_VAR_3}…\p"
	.string "It shows you what sort of a TRAINER\n"
	.string "{STR_VAR_1} is.\p"
	.string "Certainly, it was quite a lesson!$"

gTVSecretBaseVisitText13::
	.string "Devo dire, che BASE SEGRETA superba!\n"
	.string "Spettatori, se ne avete l'occasione,\p"
	.string "visitate la BASE SEGRETA\n"
	.string "di {STR_VAR_1}.\p"
	.string "Alla prossima, vi saluto!$"

gTVPokemonLotteryWinnerFlashReportText00::
	.string "Che emozione!\n"
	.string "Che dramma!\p"
	.string "È il FLASH REPORT DEI\n"
	.string "VINCITORI DELLA LOTTERIA POKéMON!\p"
	.string "Salve! Siamo in diretta dall'\n"
	.string "ANGOLO LOTTERIA POKéMON al\l"
	.string "piano terra del GRANDE\l"
	.string "MAGAZZINO DI LILYCOVE!\p"
	.string "Come sempre, oggi si è presentato\n"
	.string "un altro ALLENATORE fortunato!\p"
	.string "Il nome di quell'ALLENATORE…\n"
	.string "{STR_VAR_1}!\p"
	.string "{STR_VAR_1} ha vinto il premio {STR_VAR_2}\n"
	.string "e si è portato a casa {STR_VAR_3}!\p"
	.string "{STR_VAR_1}!\n"
	.string "Congratulazioni!\p"
	.string "Spettatori, non state solo a guardare,\n"
	.string "partecipate anche voi!\p"
	.string "Tutti noi del GRANDE MAGAZZINO\n"
	.string "DI LILYCOVE aspettiamo la vostra visita!\p"
	.string "Questa è stata una diretta dal\n"
	.string "GRANDE MAGAZZINO DI LILYCOVE,\l"
	.string "con la più grande scelta\l"
	.string "di tutto HOENN!$"

gTVThePokemonBattleSeminarText00::
	.string "THE POKéMON BATTLE SEMINAR!\p"
	.string "We examine battles to see what\n"
	.string "lessons we may learn from others.\p"
	.string "Today's case study is on {STR_VAR_1}'s\n"
	.string "battle.\p"
	.string "{STR_VAR_1}'s {STR_VAR_2} was\n"
	.string "battling one {STR_VAR_3}…$"

gTVThePokemonBattleSeminarText01::
	.string "E ha usato la mossa {STR_VAR_3}\n"
	.string "sul {STR_VAR_2}…\p"
	.string "Mmm… {STR_VAR_1}!\n"
	.string "È la cosa sbagliata da fare!$"

gTVThePokemonBattleSeminarText02::
	.string "Oltre alla mossa sbagliata,\n"
	.string "il {STR_VAR_1} dell'ALLENATORE conosceva$"

gTVThePokemonBattleSeminarText03::
	.string "le mosse {STR_VAR_1}, {STR_VAR_2}\n"
	.string "e {STR_VAR_3}.$"

gTVThePokemonBattleSeminarText04::
	.string "le mosse {STR_VAR_1} e\n"
	.string "{STR_VAR_2}.$"

gTVThePokemonBattleSeminarText05::
	.string "la mossa {STR_VAR_2}.$"

gTVThePokemonBattleSeminarText06::
	.string "Quindi, in questa situazione, cosa\n"
	.string "avrebbe dovuto usare l'ALLENATORE?\p"
	.string "… … … … … …\n"
	.string "La mossa {STR_VAR_1}!\p"
	.string "La mossa {STR_VAR_1} sarebbe stata\n"
	.string "decisamente meglio di {STR_VAR_2}.\p"
	.string "Spettatori, imparate da questo caso\n"
	.string "e lottate con intelligenza!\p"
	.string "Alla prossima, addio!$"

gTVTrainerFanClubText00::
	.string "Tutti insieme!\n"
	.string "TRAINER FAN CLUB!\p"
	.string "MC: Come va, gente?\n"
	.string "Oggi abbiamo radunato i fan di\l"
	.string "un TRAINER superpopolare: {STR_VAR_1}!\p"
	.string "FANS: Wrooooooaaaaah!\p"
	.string "FANS: {STR_VAR_1}!\p"
	.string "MC: Tutti quanti!\n"
	.string "Vi piace {STR_VAR_1}?!\p"
	.string "FANS: Adoriamo {STR_VAR_1}!\p"
	.string "MC: Cosa vi piace di\n"
	.string "{STR_VAR_1}?!$"

gTVTrainerFanClubText01::
	.string "FANS: Il suo modo stiloso di lanciare\n"
	.string "le POKé BALL!$"

gTVTrainerFanClubText02::
	.string "FANS: Il suo modo adorabile di correre!$"

gTVTrainerFanClubText03::
	.string "FANS: Come il TRAINER diventa tosto\n"
	.string "quando il gioco si fa duro!$"

gTVTrainerFanClubText04::
	.string "FANS: La sapienza del TRAINER sui\n"
	.string "POKéMON!$"

gTVTrainerFanClubText05::
	.string "FANS: La gentilezza del TRAINER verso\n"
	.string "tutti i POKéMON!$"

gTVTrainerFanClubText06::
	.string "FANS: Le sue fantastiche tecniche\n"
	.string "in Bicicletta!$"

gTVTrainerFanClubText07::
	.string "FANS: Il suo stile impressionante\n"
	.string "di acquisto!$"

gTVTrainerFanClubText08::
	.string "FANS: Il suo modo incantevole\n"
	.string "di soprannominare i POKéMON!$"

gTVTrainerFanClubText09::
	.string "FANS: Il suo stile ingegnoso\n"
	.string "di decorare una BASE SEGRETA!$"

gTVTrainerFanClubText10::
	.string "FANS: I suoi modi sicura di\n"
	.string "usare le MT!$"

gTVTrainerFanClubText11::
	.string "MC: Come avete visto, {STR_VAR_1}\n"
	.string "scotta! Come toccarlo, ahi!\p"
	.string "Tra i FANS di {STR_VAR_1}\n"
	.string "c'è uno slogan speciale!\p"
	.string "MC: Quando dico {STR_VAR_1},\n"
	.string "voi dite…\p"
	.string "FANS: {STR_VAR_2}!\p"
	.string "FANS: {STR_VAR_3}!\p"
	.string "FANS: {STR_VAR_2}!\p"
	.string "FANS: {STR_VAR_3}!\p"
	.string "MC: Esatto, quando sentite\n"
	.string "“{STR_VAR_1}”…\p"
	.string "rispondete con “{STR_VAR_2}\n"
	.string "{STR_VAR_3}!”\p"
	.string "Ha un suono così unico!\n"
	.string "Capisco perché diventano FANS\l"
	.string "di {STR_VAR_1}!\p"
	.string "Ok, tu davanti alla TV, unisciti a noi!\n"
	.string "Tutti insieme!\p"
	.string "MC: Quando dico {STR_VAR_1},\n"
	.string "voi dite…\p"
	.string "FANS: {STR_VAR_2}!\p"
	.string "FANS: {STR_VAR_3}!\p"
	.string "FANS: {STR_VAR_2}!\p"
	.string "FANS: {STR_VAR_3}!\p"
	.string "MC: Grazie per essere stati con noi,\n"
	.string "selvaggi FANS di {STR_VAR_1}!\l"
	.string "Lo spettacolo è finito! Alla prossima!\p"
	.string "MC: Quando dico {STR_VAR_1},\n"
	.string "voi dite…\p"
	.string "FANS: {STR_VAR_2}!\p"
	.string "FANS: {STR_VAR_3}!$"

TVSpotTheCuties_Text_Intro::
	.string "CHE TENEREZZA!\n"
	.string "POKéMON IN FIOCCHI!\p"
	.string "Salve, miei dolci telespettatori!\p"
	.string "Saprete darmi ragione: un POKéMON\n"
	.string "con i FIOCCHI è semplicemente divino!\p"
	.string "Oggi voglio mostrarvi\n"
	.string "un amabile POKéMON che ho notato\l"
	.string "mentre passeggiavo in città.\p"
	.string "Il bel POKéMON di oggi\n"
	.string "è {STR_VAR_2} di {STR_VAR_1}.$"

TVSpotTheCuties_Text_RibbonsLow::
	.string "Il numero di NASTRI che\n"
	.string "indossa {STR_VAR_2} è {STR_VAR_3}.\p"
	.string "Dice molto su quanto\n"
	.string "{STR_VAR_1} adori il POKéMON.$"

TVSpotTheCuties_Text_RibbonsMid::
	.string "{STR_VAR_2} ha ben\n"
	.string "{STR_VAR_3} NASTRI!\p"
	.string "Dice molto sull'amore di {STR_VAR_1}\n"
	.string "per i POKéMON!$"

TVSpotTheCuties_Text_RibbonsHigh::
	.string "{STR_VAR_2} indossa degli incredibili\n"
	.string "nastri: {STR_VAR_3}!\p"
	.string "Mostra la dedizione di {STR_VAR_1}\n"
	.string "come collezionista!$"

TVSpotTheCuties_Text_RibbonIntro::
	.string "Diamo un'occhiata più da vicino ai tanti\n"
	.string "NASTRI indossati da {STR_VAR_2}.$"

TVSpotTheCuties_Text_RibbonChampion::
	.string "Il FIOCCO CAMPIONE è davvero\n"
	.string "incantevole.\p"
	.string "{STR_VAR_2} l'ha ricevuto entrando\n"
	.string "nella HALL OF FAME.\p"
	.string "Esalta il coraggio\n"
	.string "di {STR_VAR_2}.\p"
	.string "{STR_VAR_2} e il FIOCCO CAMPIONE!\n"
	.string "L'abbinamento è superefficace!$"

TVSpotTheCuties_Text_RibbonCool::
	.string "Il FIOCCO CLASSE è davvero\n"
	.string "incantevole.\p"
	.string "{STR_VAR_2} l'ha ricevuto vincendo\n"
	.string "una GARA DI CLASSE.\p"
	.string "Esalta la classe\n"
	.string "di {STR_VAR_2}.\p"
	.string "{STR_VAR_2} e il FIOCCO CLASSE!\n"
	.string "L'abbinamento è superefficace!$"

TVSpotTheCuties_Text_RibbonBeauty::
	.string "Il FIOCCO BELLEZZA è davvero\n"
	.string "incantevole.\p"
	.string "{STR_VAR_2} l'ha ricevuto vincendo\n"
	.string "una GARA DI BELLEZZA.\p"
	.string "Esalta la bellezza\n"
	.string "di {STR_VAR_2}.\p"
	.string "{STR_VAR_2} e il FIOCCO BELLEZZA!\n"
	.string "L'abbinamento è superefficace!$"

TVSpotTheCuties_Text_RibbonCute::
	.string "Il FIOCCO GRAZIA è davvero\n"
	.string "incantevole.\p"
	.string "{STR_VAR_2} l'ha ricevuto vincendo\n"
	.string "una GARA DI GRAZIA.\p"
	.string "Esalta la grazia\n"
	.string "di {STR_VAR_2}.\p"
	.string "{STR_VAR_2} e il FIOCCO GRAZIA!\n"
	.string "L'abbinamento è superefficace!$"

TVSpotTheCuties_Text_RibbonSmart::
	.string "Il NASTRO CLASSE è davvero\n"
	.string "attraente.\p"
	.string "{STR_VAR_2} l'ha ricevuto per aver vinto\n"
	.string "una GARA CLASSE.\p"
	.string "Tira fuori davvero la classe\n"
	.string "di {STR_VAR_2}.\p"
	.string "{STR_VAR_2} e il NASTRO CLASSE!\n"
	.string "L'abbinamento è superefficace!$"

TVSpotTheCuties_Text_RibbonTough::
	.string "Il NASTRO GRINTA è davvero\n"
	.string "attraente.\p"
	.string "{STR_VAR_2} l'ha ricevuto per aver vinto\n"
	.string "una GARA GRINTA.\p"
	.string "Tira fuori davvero la grinta\n"
	.string "di {STR_VAR_2}.\p"
	.string "{STR_VAR_2} e il NASTRO GRINTA!\n"
	.string "L'abbinamento è superefficace!$"

TVSpotTheCuties_Text_RibbonWinning::
	.string "Il NASTRO VINCITORE è davvero\n"
	.string "attraente.\p"
	.string "{STR_VAR_2} l'ha ricevuto per le sue imprese\n"
	.string "alla TORRE LOTTA.\p"
	.string "Tira fuori davvero la forza\n"
	.string "di {STR_VAR_2}.\p"
	.string "{STR_VAR_2} e il NASTRO VINCITORE!\n"
	.string "L'abbinamento è superefficace!$"

TVSpotTheCuties_Text_RibbonVictory::
	.string "Il NASTRO VITTORIA è davvero\n"
	.string "attraente.\p"
	.string "{STR_VAR_2} l'ha ricevuto per le sue imprese\n"
	.string "alla TORRE LOTTA.\p"
	.string "Tira fuori davvero la forza\n"
	.string "incredibile di {STR_VAR_2}.\p"
	.string "{STR_VAR_2} e il NASTRO VITTORIA!\n"
	.string "L'abbinamento è superefficace!$"

TVSpotTheCuties_Text_RibbonArtist::
	.string "Il FIOCCO ARTISTA è davvero\n"
	.string "incantevole.\p"
	.string "{STR_VAR_2} l'ha ricevuto per essere\n"
	.string "stato la modella di un artista.\p"
	.string "Esalta il Fascino da pop-star\n"
	.string "di {STR_VAR_2}.\p"
	.string "{STR_VAR_2} e il FIOCCO ARTISTA!\n"
	.string "L'abbinamento è superefficace!$"

TVSpotTheCuties_Text_RibbonEffort::
	.string "Il NASTRO LAVORATORE è\n"
	.string "davvero attraente.\p"
	.string "{STR_VAR_2} l'ha ricevuto per essere\n"
	.string "un lavoratore molto dedito.\p"
	.string "Tira fuori davvero la determinazione\n"
	.string "di {STR_VAR_2}.\p"
	.string "{STR_VAR_2} e il NASTRO LAVORATORE!\n"
	.string "L'abbinamento è superefficace!$"

TVSpotTheCuties_Text_Outro::
	.string "…Sospiro…\p"
	.string "FIOCCHI e POKéMON…\n"
	.string "Che meraviglioso connubio!\p"
	.string "Prima di svenire dal piacere,\n"
	.string "vi saluto, cari!$"

gTVPokemonNewsBattleFrontierText00::
	.string "Salve!\n"
	.string "È il momento del NOTIZIARIO POKéMON.\p"
	.string "Abbiamo buone notizie dal\n"
	.string "PARCO LOTTA.$"

gTVPokemonNewsBattleFrontierText01::
	.string "L'ALLENATORE {STR_VAR_1} ha stabilito un nuovo\n"
	.string "record di {STR_VAR_2} vittorie di fila nella\l"
	.string "TORRE LOTTA, sfida in\l"
	.string "CAMERA LOTTA SINGOLA.\p"
	.string "Un brindisi a {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText02::
	.string "L'ALLENATORE {STR_VAR_1} ha stabilito un nuovo\n"
	.string "record di {STR_VAR_2} vittorie di fila nella\l"
	.string "TORRE LOTTA, sfida in\l"
	.string "CAMERA LOTTA DOPPIA.\p"
	.string "Un brindisi a {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText03::
	.string "L'ALLENATORE {STR_VAR_1} ha stabilito un nuovo\n"
	.string "record di {STR_VAR_2} vittorie di fila nella\l"
	.string "TORRE LOTTA, sfida in\l"
	.string "CAMERA LOTTA MULTIPLA.\p"
	.string "Un brindisi a {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText04::
	.string "L'ALLENATORE {STR_VAR_1} ha stabilito un nuovo\n"
	.string "record di {STR_VAR_2} vittorie di fila nella\l"
	.string "TORRE LOTTA, sfida in CAMERA LOTTA\l"
	.string "MULTIPLA IN COLLEGAMENTO.\p"
	.string "Un brindisi a {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText05::
	.string "L'ALLENATORE {STR_VAR_1} ha stabilito un nuovo\n"
	.string "record di {STR_VAR_2} campionati vinti\l"
	.string "nei TORNEI LOTTA SINGOLA\l"
	.string "della CUPOLA LOTTA.\p"
	.string "Un brindisi a {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText06::
	.string "L'ALLENATORE {STR_VAR_1} ha stabilito un nuovo\n"
	.string "record di {STR_VAR_2} campionati vinti\l"
	.string "nei TORNEI LOTTA DOPPIA\l"
	.string "della CUPOLA LOTTA.\p"
	.string "Un brindisi a {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText07::
	.string "L'ALLENATORE {STR_VAR_1} ha stabilito un nuovo\n"
	.string "record di {STR_VAR_2} vittorie di fila nella\l"
	.string "sfida Scambio Lotta Singola\l"
	.string "della FABBRICA LOTTA.\p"
	.string "Un brindisi a {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText08::
	.string "L'ALLENATORE {STR_VAR_1} ha stabilito un nuovo\n"
	.string "record di {STR_VAR_2} vittorie di fila nella\l"
	.string "sfida Scambio Lotta Doppia\l"
	.string "della FABBRICA LOTTA.\p"
	.string "Un brindisi a {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText09::
	.string "L'ALLENATORE {STR_VAR_1} ha stabilito un nuovo\n"
	.string "record superando {STR_VAR_2} stanze\l"
	.string "nella sfida Scelta Lotta\l"
	.string "del SENTIERO LOTTA.\p"
	.string "Un brindisi a {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText10::
	.string "L'ALLENATORE {STR_VAR_1} ha stabilito un nuovo\n"
	.string "record di {STR_VAR_2} vittorie di fila\l"
	.string "nei TORNEI KO A GRUPPI\l"
	.string "dell'ARENA LOTTA.\p"
	.string "Un brindisi a {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText11::
	.string "Il GENTILUOMO {STR_VAR_1} ha stabilito\n"
	.string "un nuovo record di {STR_VAR_2} vittorie\l"
	.string "nella sfida SINGOLO del PALAZZO\l"
	.string "LOTTA.\p"
	.string "Un evviva a {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText12::
	.string "Il GENTILUOMO {STR_VAR_1} ha stabilito\n"
	.string "un nuovo record di {STR_VAR_2} vittorie\l"
	.string "nella sfida DOPPIA del PALAZZO LOTTA.\l"
	.string "Che impresa!\p"
	.string "Un evviva a {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText13::
	.string "Il GENTILUOMO {STR_VAR_1} ha stabilito\n"
	.string "un nuovo record superando {STR_VAR_2}\l"
	.string "piani nella sfida Avventura della\l"
	.string "PIRAMIDE LOTTA.\p"
	.string "Un evviva a {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText14::
	.string "E ai tre POKéMON, {STR_VAR_1},\n"
	.string "{STR_VAR_2} e {STR_VAR_3}!\p"
	.string "Congratulazioni per la vostra\n"
	.string "prestazione da record!$"

gTVPokemonNewsBattleFrontierText15::
	.string "E ai due POKéMON, {STR_VAR_1}\n"
	.string "e {STR_VAR_2}!\p"
	.string "Congratulazioni per la vostra\n"
	.string "prestazione da record!$"

gTVPokemonNewsBattleFrontierText16::
	.string "E ai quattro POKéMON: {STR_VAR_1}!\p"
	.string "{STR_VAR_2}!\p"
	.string "{STR_VAR_3}!$"

gTVPokemonNewsBattleFrontierText17::
	.string "E a {STR_VAR_1}!\p"
	.string "Congratulazioni per la tua\n"
	.string "prestazione da record!$"

gTVPokemonNewsBattleFrontierText18::
	.string "Speriamo in altre imprese da record\n"
	.string "da {STR_VAR_1} e dai fedeli\l"
	.string "POKéMON!\p"
	.string "Queste sono le notizie di POKéMON NEWS!$"

gTVWhatsNo1InHoennTodayText00::
	.string "CHI È IL N. 1 DI HOENN OGGI?\n"
	.string "Sì, è di nuovo quel momento!\p"
	.string "Ciao, spettatori! Date il meglio\n"
	.string "in tutto ciò che fate?\p"
	.string "Vediamo il TRAINER\n"
	.string "che oggi ha dato il meglio!\p"
	.string "Il TRAINER n. 1 di oggi non è altro\n"
	.string "che {STR_VAR_1}!$"

gTVWhatsNo1InHoennTodayText01::
	.string "In un giorno, {STR_VAR_1} ha girato le SLOT\n"
	.string "al GAME CORNER {STR_VAR_2} volte.\p"
	.string "Mentre giocava, {STR_VAR_1} mormorava,\n"
	.string "“Per me i rulli non\l"
	.string "si muovono nemmeno…”\l"
	.string "Interessante, no?$"

gTVWhatsNo1InHoennTodayText02::
	.string "In un giorno, {STR_VAR_1} ha giocato\n"
	.string "alla ROULETTE del GAME\l"
	.string "CORNER {STR_VAR_2} volte.\p"
	.string "Mentre giocava, {STR_VAR_1} gridava,\n"
	.string "“Decideranno le palline!”\p"
	.string "Gli occhi del TRAINER erano fissi e\n"
	.string "il volto mostrava concentrazione.$"

gTVWhatsNo1InHoennTodayText03::
	.string "In un giorno, {STR_VAR_1} ha battuto\n"
	.string "POKéMON selvatici {STR_VAR_2} volte!\p"
	.string "A quanto pare, i POKéMON di {STR_VAR_1}\n"
	.string "sono diventati molto più forti.\p"
	.string "Sembrano pronti a lottare ovunque,\n"
	.string "in qualsiasi momento!$"

gTVWhatsNo1InHoennTodayText04::
	.string "In un solo giorno, {STR_VAR_1} ha usato\n"
	.string "il BERRY BLENDER {STR_VAR_2} volte!\p"
	.string "Verso la fine, persino {STR_VAR_1}\n"
	.string "sembrava stordito.\p"
	.string "Il TRAINER barcollava\n"
	.string "in giro come uno SPINDA!$"

gTVWhatsNo1InHoennTodayText05::
	.string "In un solo giorno, {STR_VAR_1} ha piantato\n"
	.string "{STR_VAR_2} BACCHE!\p"
	.string "Di conseguenza, i vestiti di {STR_VAR_1}\n"
	.string "si sono sporcati di terra.\p"
	.string "Dove il TRAINER ha piantato, sono\n"
	.string "sbocciati innumerevoli fiori.\p"
	.string "Si dice che i fiori calmino\n"
	.string "le emozioni delle persone.$"

gTVWhatsNo1InHoennTodayText06::
	.string "In un solo giorno, {STR_VAR_1} ha raccolto\n"
	.string "{STR_VAR_2} BACCHE!\p"
	.string "Lo ZAINO di {STR_VAR_1} era così pieno\n"
	.string "di BACCHE che il TRAINER faceva fatica\l"
	.string "a camminare!$"

gTVWhatsNo1InHoennTodayText07::
	.string "In un solo giorno, {STR_VAR_1} ha ottenuto\n"
	.string "{STR_VAR_2} Punti Lotta!\p"
	.string "Poi {STR_VAR_1} è stato visto alle prese\n"
	.string "con la scelta di scambiare\l"
	.string "i Punti Lotta con un oggetto o\l"
	.string "una decorazione raffinata.\p"
	.string "Si dice che il TRAINER sorridesse\n"
	.string "mentre valutava le opzioni.$"

gTVWhatsNo1InHoennTodayText08::
	.string "Ma pensa un po'!\p"
	.string "{STR_VAR_1}!\n"
	.string "Sei il TRAINER n. 1 di oggi!\p"
	.string "Spettatori, prendete esempio da {STR_VAR_1}!\n"
	.string "Anche voi potete essere n. 1 ogni giorno!$"

TVSecretBaseSecrets_Text_Intro::
	.string "SECRET BASE SECRETS!\p"
	.string "What do TRAINERS do in the secrecy\n"
	.string "of SECRET BASES?\p"
	.string "Today, we investigate {STR_VAR_1}'s\n"
	.string "SECRET BASE.\p"
	.string "Oh? It looks like {STR_VAR_2} has come\n"
	.string "for a visit.\p"
	.string "Let's have a peek!\p"
	.string "What will {STR_VAR_2} do?$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext1::
	.string "E ora cosa farà {STR_VAR_2}?$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext2::
	.string "E adesso, cosa farà {STR_VAR_2}?$"

TVSecretBaseSecrets_Text_TookXStepsBeforeLeaving::
	.string "Alla fine, {STR_VAR_2} ha fatto {STR_VAR_3} passi\n"
	.string "nella BASE SEGRETA di {STR_VAR_1}\l"
	.string "prima di andarsene.$"

TVSecretBaseSecrets_Text_BaseFailedToInterestPlayer::
	.string "Mmm…\p"
	.string "Sembra che la BASE SEGRETA di {STR_VAR_1}\n"
	.string "non abbia colpito {STR_VAR_2}…$"

TVSecretBaseSecrets_Text_PlayerEnjoyedBase::
	.string "{STR_VAR_2} sembra essersi divertito\n"
	.string "molto nella BASE SEGRETA di {STR_VAR_1}.$"

TVSecretBaseSecrets_Text_PlayerHugeFanOfBase::
	.string "{STR_VAR_2} appears to have become\n"
	.string "a huge fan of {STR_VAR_1}'s\l"
	.string "SECRET BASE.$"

TVSecretBaseSecrets_Text_Outro::
	.string "Gli spettatori possono visitare\n"
	.string "la BASE SEGRETA di {STR_VAR_1}.\p"
	.string "Alla prossima, in un'altra\n"
	.string "BASE SEGRETA! Grazie della compagnia!$"

TVSecretBaseSecrets_Text_StoppedMoving1::
	.string "Il visitatore si è fermato!\p"
	.string "Non si muove più!\p"
	.string "La BASE SEGRETA di {STR_VAR_1}\n"
	.string "era così deludente?$"

TVSecretBaseSecrets_Text_StoppedMoving2::
	.string "Il visitatore si è fermato!\p"
	.string "Non si muove più!\p"
	.string "È stanchezza?\n"
	.string "Il visitatore è sfinito?$"

TVSecretBaseSecrets_Text_UsedChair::
	.string "Il visitatore si è seduto su una sedia!\n"
	.string "È seduto!\p"
	.string "Guardate che faccia felice!\p"
	.string "Quella sedia dev'essere comodissima\n"
	.string "per suscitare una reazione simile!$"

TVSecretBaseSecrets_Text_UsedBalloon::
	.string "Il visitatore si è lanciato su un pallone!\p"
	.string "È scoppiato!\n"
	.string "Oh, cielo, è esploso!\p"
	.string "Il visitatore sembra spaventato\n"
	.string "dal rumore improvviso!$"

TVSecretBaseSecrets_Text_UsedTent::
	.string "Il visitatore è entrato in una TENDA!\p"
	.string "Il visitatore corre qua e là!\p"
	.string "Oh, cielo, salterella felice!\p"
	.string "Il visitatore sembra stupito\n"
	.string "dalle dimensioni della TENDA!$"

TVSecretBaseSecrets_Text_UsedPlant::
	.string "Il visitatore sta esaminando\n"
	.string "una pianta in vaso!\p"
	.string "Il visitatore ha gusti\n"
	.string "sorprendentemente maturi!$"

TVSecretBaseSecrets_Text_UsedGoldShield::
	.string "Il visitatore sta esaminando\n"
	.string "uno SCUDO ORO!\p"
	.string "Gli si sono illuminati\n"
	.string "gli occhi per lo stupore!$"

TVSecretBaseSecrets_Text_UsedSilverShield::
	.string "Il visitatore sta esaminando\n"
	.string "uno SCUDO ARGENTO!\p"
	.string "Il visitatore ha gli occhi sgranati!$"

TVSecretBaseSecrets_Text_UsedGlassOrnament::
	.string "Il visitatore sta esaminando\n"
	.string "un ORNAMENTO DI VETRO!\p"
	.string "Oh, no!\p"
	.string "Lo sta toccando!\p"
	.string "Si sta riempiendo\n"
	.string "di impronte…$"

TVSecretBaseSecrets_Text_UsedTV::
	.string "Il visitatore sta guardando la TV!\p"
	.string "Direi che è un grande fan della TV!$"

TVSecretBaseSecrets_Text_UsedMudBall::
	.string "Il visitatore ha pestato una PALLOTOLA!\p"
	.string "Il visitatore sembra felicissimo!$"

TVSecretBaseSecrets_Text_UsedBag::
	.string "…Oh?\p"
	.string "Il visitatore fruga nella sua\n"
	.string "BORSA e cerca qualcosa!\p"
	.string "Il visitatore ha tirato fuori\n"
	.string "un {STR_VAR_2}!\p"
	.string "Guardate che sorriso mentre\n"
	.string "mostra il {STR_VAR_2}!\p"
	.string "Sembra uno spot pubblicitario!$"

TVSecretBaseSecrets_Text_UsedCushion::
	.string "Il visitatore afferra un cuscino e…$"

TVSecretBaseSecrets_Text_HitCushion::
	.string "…comincia a colpirlo!\p"
	.string "Il visitatore è molto stressato?$"

TVSecretBaseSecrets_Text_HuggedCushion::
	.string "…lo stringe forte!\p"
	.string "Il visitatore è felice\n"
	.string "per qualcosa?$"

TVSecretBaseSecrets_Text_BattledWon::
	.string "Il visitatore sta parlando con\n"
	.string "{STR_VAR_1}!\p"
	.string "Sembra che stiano per\n"
	.string "fare una lotta!\p"
	.string "E…\p"
	.string "È il visitatore!\n"
	.string "Il visitatore ha vinto in trasferta!\p"
	.string "Il visitatore sta facendo\n"
	.string "una danza di vittoria!$"

TVSecretBaseSecrets_Text_BattledLost::
	.string "Il visitatore sta parlando con\n"
	.string "{STR_VAR_1}!\p"
	.string "Sembra che stiano per\n"
	.string "fare una lotta!\p"
	.string "E…\p"
	.string "È {STR_VAR_1}!\n"
	.string "Il visitatore ha perso!\p"
	.string "Il visitatore è abbattuto!$"

TVSecretBaseSecrets_Text_DeclinedBattle::
	.string "Il visitatore sta parlando con\n"
	.string "{STR_VAR_1}!\p"
	.string "Sembra che stiano per\n"
	.string "fare una lotta!\p"
	.string "E…\p"
	.string "No, il visitatore ha rifiutato!\p"
	.string "Alla fine non ci sarà nessuna lotta!\p"
	.string "Il visitatore troverà {STR_VAR_1}\n"
	.string "poco simpatico?$"

TVSecretBaseSecrets_Text_UsedPoster::
	.string "Il visitatore fissa intensamente\n"
	.string "un poster!\p"
	.string "Il poster è di suo\n"
	.string "gradimento?\p"
	.string "…Ma… C'è qualcosa di inquietante\n"
	.string "nel suo sguardo.$"

TVSecretBaseSecrets_Text_UsedNoteMat::
	.string "Il visitatore ha pestato un NOTE MAT!\p"
	.string "…Mmm…\n"
	.string "Il visitatore ha composto una melodia!$"

TVSecretBaseSecrets_Text_BattledDraw::
	.string "Il visitatore sta parlando con\n"
	.string "{STR_VAR_1}!\p"
	.string "Sembra che stiano per\n"
	.string "fare una lotta!\p"
	.string "E…\p"
	.string "È un pareggio!\n"
	.string "Non si è risolto nulla!\p"
	.string "Entrambi gli ALLENATORI sembrano\n"
	.string "molto delusi!$"

TVSecretBaseSecrets_Text_UsedSpinMat::
	.string "Il visitatore è salito su\n"
	.string "un TAPPETO GIRA!\p"
	.string "Sembra che abbia la testa che gira!\p"
	.string "Il visitatore barcolla!\n"
	.string "Attenzione!$"

TVSecretBaseSecrets_Text_UsedSandOrnament::
	.string "Il visitatore allunga la mano verso\n"
	.string "un ORNAMENTO DI SABBIA!\p"
	.string "Oh!\p"
	.string "Si è sbriciolato!\n"
	.string "È andato in pezzi!\p"
	.string "Il visitatore sembra mortificato\n"
	.string "e in colpa!$"

TVSecretBaseSecrets_Text_UsedDesk::
	.string "Il visitatore strofina la scrivania\n"
	.string "con un dito!\p"
	.string "A quanto pare, non sopporta\n"
	.string "la polvere!\p"
	.string "Il visitatore tiene molto\n"
	.string "all'ordine!$"

TVSecretBaseSecrets_Text_UsedBrick::
	.string "Il visitatore fissa un MATTONE!\p"
	.string "Forse sta pensando\n"
	.string "all'oggetto sul MATTONE.$"

TVSecretBaseSecrets_Text_UsedSolidBoard::
	.string "Il visitatore cammina sopra\n"
	.string "la TAVOLA SOLIDA.\p"
	.string "Continua a guardare in basso.\p"
	.string "Il visitatore è sorprendentemente\n"
	.string "timido e prudente!$"

TVSecretBaseSecrets_Text_UsedFence::
	.string "Il visitatore osserva con attenzione\n"
	.string "una staccionata!\p"
	.string "Gli è venuta una nuova idea\n"
	.string "per una Trappola?$"

TVSecretBaseSecrets_Text_UsedGlitterMat::
	.string "Il visitatore è salito su\n"
	.string "un TAPPETO GLITTER!\p"
	.string "Il visitatore sta assumendo\n"
	.string "varie pose!\p"
	.string "Sembra che stia sognando\n"
	.string "di essere una star!$"

TVSecretBaseSecrets_Text_UsedTire::
	.string "Il visitatore fissa intensamente\n"
	.string "un PNEUMATICO!\p"
	.string "Starà pensando al tipo di auto\n"
	.string "che potrebbe usarlo?$"

TVSecretBaseSecrets_Text_UsedStand::
	.string "Il visitatore è salito su un PIEDISTALLO!\p"
	.string "Il visitatore osserva la BASE\n"
	.string "di {STR_VAR_1} dall'alto!\p"
	.string "E…\p"
	.string "Lancia un ruggito!\n"
	.string "Il visitatore sta ruggendo!$"

TVSecretBaseSecrets_Text_BrokeDoor::
	.string "Il visitatore si è buttato a capofitto\n"
	.string "contro una PORTA SFONDABILE!\p"
	.string "Il visitatore ride a crepapelle!$"

TVSecretBaseSecrets_Text_UsedDoll::
	.string "Il visitatore parla con una bambola!\p"
	.string "…È un po' inquietante…$"

TVSecretBaseSecrets_Text_UsedSlide::
	.string "Il visitatore sale la scaletta\n"
	.string "di uno SCIVOLO!\p"
	.string "E…\p"
	.string "È scivolato giù!\p"
	.string "Sembra che il visitatore si stia\n"
	.string "divertendo un mondo!$"

TVSecretBaseSecrets_Text_UsedSlideButDidntGoDown::
	.string "Il visitatore sale la scaletta\n"
	.string "di uno SCIVOLO!\p"
	.string "E…\p"
	.string "Il visitatore è risceso\n"
	.string "dalla scaletta!\p"
	.string "Si è tirato indietro all'improvviso?$"

TVSecretBaseSecrets_Text_UsedJumpMat::
	.string "Il visitatore è salito su\n"
	.string "un TAPPETO SALTO!\p"
	.string "Ha saltato una volta!\p"
	.string "Due volte!\p"
	.string "E atterraggio perfetto!\p"
	.string "Il visitatore applaude!\n"
	.string "Che numero da solista!$"

gTVSafariFanClubText00::
	.string "SAFARI FAN CLUB!\p"
	.string "REPORTER: Bene, amici!\n"
	.string "Lanciate SAFARI BALL, eh?\p"
	.string "Scommetto che qui nella ZONA SAFARI\n"
	.string "ci sono un sacco di POKéMON!\p"
	.string "Parliamo un po' con questo bravo\n"
	.string "ragazzo, la GUIDA SAFARI!\p"
	.string "Bene, amico, come se la cavano gli\n"
	.string "ALLENATORI in visita?$"

gTVSafariFanClubText01::
	.string "GUIDA: Sembrano tutti impegnati\n"
	.string "al massimo.\p"
	.string "{STR_VAR_1} se la cava benissimo.\p"
	.string "Anzi, poco fa {STR_VAR_1} ha catturato\n"
	.string "{STR_VAR_2} POKéMON.$"

gTVSafariFanClubText02::
	.string "L'ALLENATORE è bravo con i {POKEBLOCK}.\n"
	.string "Ne ha usati {STR_VAR_2} quella volta, credo.$"

gTVSafariFanClubText03::
	.string "L'ALLENATORE non ha usato nemmeno un\n"
	.string "{POKEBLOCK}! Nemmeno uno!\p"
	.string "Ecco un vero esperto.$"

gTVSafariFanClubText04::
	.string "REPORTER: Davvero?\p"
	.string "Sembra che il nostro {STR_VAR_1}\n"
	.string "sia un grande maestro della SAFARI!\p"
	.string "GUIDA: Spero che l'ALLENATORE torni\n"
	.string "a mostrarci quella tecnica!$"

gTVSafariFanClubText05::
	.string "GUIDA: Non sembra che stiano andando\n"
	.string "molto bene.\p"
	.string "{STR_VAR_1} è andato male soprattutto.\p"
	.string "Anzi, poco fa l'ALLENATORE è riuscito\n"
	.string "a catturare solo {STR_VAR_2} POKéMON.$"

gTVSafariFanClubText06::
	.string "GUIDA: Non sembra che stiano andando\n"
	.string "molto bene.\p"
	.string "{STR_VAR_1} è andato male soprattutto.\p"
	.string "Anzi, poco fa l'ALLENATORE non ha\n"
	.string "catturato nessun POKéMON. Nemmeno uno!$"

gTVSafariFanClubText07::
	.string "L'ALLENATORE usa i {POKEBLOCK}.\n"
	.string "Ne ha usati {STR_VAR_2} quella volta, credo.\p"
	.string "Ma, caspita, spero che l'ALLENATORE\n"
	.string "diventi un po' più bravo.$"

gTVSafariFanClubText08::
	.string "Il ALLENATORE avrebbe più\n"
	.string "fortuna con i {POKEBLOCK}, che non\l"
	.string "furono usati per niente.$"

gTVSafariFanClubText09::
	.string "REPORTER: Davvero?\p"
	.string "Il nostro {STR_VAR_1} ha bisogno\n"
	.string "di più di ZONA SAFARI.\p"
	.string "GUIDA: Spero che l'ALLENATORE\n"
	.string "venga spesso a far pratica.$"

gTVSafariFanClubText10::
	.string "REPORTER: Proprio così!\n"
	.string "Affrontare le sfide è importante!\p"
	.string "Spettatori, venite alla ZONA SAFARI\n"
	.string "e raccogliete la sfida!\p"
	.string "Alla prossima, ciao!$"

ContestLiveUpdates_Text_Intro::
	.string "“POKéMON CONTEST IN DIRETTA!”\p"
	.string "SPEAKER: Grazie per essere con noi!\p"
	.string "Siamo in diretta dal luogo del\n"
	.string "{STR_VAR_1} appena concluso.\p"
	.string "La sala è ancora piena di\n"
	.string "un pubblico che non vuole andarsene.\p"
	.string "Spettatore: {STR_VAR_2}!\p"
	.string "Spettatore: {STR_VAR_3}!\p"
	.string "SPEAKER: Come avete sentito, il CONTEST\n"
	.string "è stato vinto dal POKéMON {STR_VAR_2}\l"
	.string "di {STR_VAR_3}.\p"
	.string "Spettatore: {STR_VAR_2}!\n"
	.string "Sei il migliore!\p"
	.string "Spettatore: {STR_VAR_3}!\n"
	.string "Grande!\p"
	.string "SPEAKER: Sentiamo cosa hanno\n"
	.string "da dire i fan su questo CONTEST.$"

ContestLiveUpdates_Text_WonBothRounds::
	.string "Spettatore: Il {STR_VAR_2} è stato il migliore in\n"
	.string "entrambe le fasi di giudizio!\p"
	.string "Quel {STR_VAR_2} continuerà a vincere!$"

ContestLiveUpdates_Text_BetterRound2::
	.string "Spettatore: Il {STR_VAR_2} non è andato\n"
	.string "bene nel primo giudizio, ma ha\l"
	.string "fatto il pieno nel secondo!\p"
	.string "È stata una rimonta miracolosa\n"
	.string "per quel {STR_VAR_2}. Evviva!$"

ContestLiveUpdates_Text_EqualRounds::
	.string "Spettatore: Il {STR_VAR_2} è rimasto\n"
	.string "costante sia nel primo che nel\l"
	.string "secondo giudizio.\p"
	.string "{STR_VAR_3} e il {STR_VAR_2},\n"
	.string "che coppia niente male!$"

ContestLiveUpdates_Text_BetterRound1::
	.string "Spettatore: In quanto a essere {STR_VAR_1},\n"
	.string "quel {STR_VAR_2} è stato eccezionale.\p"
	.string "Spero però che faccia esibizioni\n"
	.string "migliori la prossima volta.$"

ContestLiveUpdates_Text_GotNervous::
	.string "Spettatore: Quando il {STR_VAR_2} si è\n"
	.string "innervosito, non ho potuto fare a meno di\l"
	.string "gridargli incoraggiamento.\p"
	.string "Vorrei dire a quel\n"
	.string "{STR_VAR_2}: “Congratulazioni!”$"

ContestLiveUpdates_Text_StartledFoes::
	.string "Spettatore: L'esibizione di quel {STR_VAR_2}\n"
	.string "ha sorpreso anche me!\p"
	.string "{STR_VAR_2}, sei stato fantastico!$"

ContestLiveUpdates_Text_UsedCombo::
	.string "Spettatore: L'esibizione combinata di {STR_VAR_2}\n"
	.string "è stata stupefacente!\p"
	.string "Mi ha scosso nel profondo!$"

ContestLiveUpdates_Text_ExcitingAppeal::
	.string "Spettatore: L'esibizione del {STR_VAR_2}\n"
	.string "vincitore mi ha fatto battere il cuore!$"

ContestLiveUpdates_Text_WasCool::
	.string "{STR_VAR_2}!\n"
	.string "Eri forte!$"

ContestLiveUpdates_Text_WasBeautiful::
	.string "{STR_VAR_2}!\n"
	.string "Eri bellissimo!$"

ContestLiveUpdates_Text_WasCute::
	.string "{STR_VAR_2}!\n"
	.string "Eri carino!$"

ContestLiveUpdates_Text_WasSmart::
	.string "{STR_VAR_2}!\n"
	.string "Eri intelligente!$"

ContestLiveUpdates_Text_WasTough::
	.string "{STR_VAR_2}!\n"
	.string "Sei stato forte!$"

ContestLiveUpdates_Text_VeryExcitingAppeal::
	.string "Spettatore: L'esibizione del {STR_VAR_2}\n"
	.string "vincitore mi fa ancora battere il cuore!$"

ContestLiveUpdates_Text_VeryCool::
	.string "{STR_VAR_2}!\n"
	.string "Sei il re del cool!$"

ContestLiveUpdates_Text_VeryBeautiful::
	.string "{STR_VAR_2}!\n"
	.string "Sei il più bello!$"

ContestLiveUpdates_Text_VeryCute::
	.string "{STR_VAR_2}!\n"
	.string "Sei semplicemente il più carino!$"

ContestLiveUpdates_Text_VerySmart::
	.string "{STR_VAR_2}!\n"
	.string "Sei il più intelligente dei intelligenti!$"

ContestLiveUpdates_Text_VeryTough::
	.string "{STR_VAR_2}!\n"
	.string "Sei il più forte tra i forti!$"

ContestLiveUpdates_Text_TookBreak::
	.string "Spettatore: Anche quando il {STR_VAR_2}\n"
	.string "si è preso una pausa dalle esibizioni,\l"
	.string "non riuscivo a distogliere lo sguardo.\p"
	.string "Sono affascinato da quel {STR_VAR_2}.$"

ContestLiveUpdates_Text_GotStartled::
	.string "Spettatore: Quando {STR_VAR_2} è stato\n"
	.string "spaventato dall'esibizione di un POKéMON,\l"
	.string "sono quasi scoppiato a piangere.\p"
	.string "{STR_VAR_2}, sei stato tenace!\n"
	.string "Bravissimo!$"

ContestLiveUpdates_Text_MoveWonderful::
	.string "Spettatore: Oh…\n"
	.string "Il {STR_VAR_3} di quel {STR_VAR_2}!\l"
	.string "Il {STR_VAR_3} di {STR_VAR_2}!\l"
	.string "Il {STR_VAR_3} di {STR_VAR_2}!\l"
	.string "Come può essere così meraviglioso?$"

ContestLiveUpdates_Text_TalkAboutAnotherMon::
	.string "SPEAKER: Ecco fatto. Questo posto\n"
	.string "è pieno di fan di {STR_VAR_1}!\p"
	.string "Devo anche menzionare che un altro\n"
	.string "POKéMON, il {STR_VAR_3} di {STR_VAR_2}, \l"
	.string "mi ha colpito.\p"
	.string "Il {STR_VAR_3} di {STR_VAR_2}…$"

ContestLiveUpdates_Text_FailedToAppeal::
	.string "Non è riuscito a fare una sola esibizione\n"
	.string "nel secondo giudizio per l'emozione.\p"
	.string "La prossima volta, vorrei vedere questo\n"
	.string "{STR_VAR_1} fare anche solo un'esibizione.$"

ContestLiveUpdates_Text_LastInBothRounds::
	.string "È arrivato ultimo sia nel primo\n"
	.string "che nel secondo giudizio.\p"
	.string "Spero che {STR_VAR_1} rialleni questo\n"
	.string "{STR_VAR_2} e cancelli la vergogna di\l"
	.string "questo ultimo posto indiscusso.$"

ContestLiveUpdates_Text_NotExcitingEnough::
	.string "Non ha saputo sfruttare\n"
	.string "l'entusiasmo del pubblico per fare\l"
	.string "un'esibizione adeguata.\p"
	.string "Speriamo che {STR_VAR_1} impari a capire\n"
	.string "il pubblico e a portare la sua\l"
	.string "emozione alle stelle la prossima volta.$"

ContestLiveUpdates_Text_LostAfterWinningRound1::
	.string "Pur arrivando primo nel primo\n"
	.string "giudizio, le sue esibizioni nel secondo\l"
	.string "non hanno funzionato.\p"
	.string "Ha subito una umiliante sconfitta\n"
	.string "in rimonta.\p"
	.string "Sono sicuro che {STR_VAR_1} stia studiando\n"
	.string "esibizioni più efficaci ora.$"

ContestLiveUpdates_Text_NeverExciting::
	.string "Il pubblico non si è mai entusiasmato\n"
	.string "con le sue esibizioni nella seconda fase.\p"
	.string "Speriamo che smetta di preoccuparsi\n"
	.string "degli altri POKéMON e impari a rivolgere\l"
	.string "meglio le esibizioni al pubblico.$"

ContestLiveUpdates_Text_LostBySmallMargin::
	.string "Ha perso contro il {STR_VAR_2} di {STR_VAR_1}\n"
	.string "solo per un piccolo margine.\p"
	.string "Dev'essere straziante arrivare\n"
	.string "così vicino alla vittoria e fallire.\p"
	.string "Non mi stupirei se {STR_VAR_3}\n"
	.string "stesse piangendo per questo esito.$"

ContestLiveUpdates_Text_RepeatedAppeals::
	.string "Ha deluso il GIUDICE ripetendo\n"
	.string "le stesse esibizioni.\p"
	.string "È un errore imperdonabile in qualsiasi\n"
	.string "CONTEST, e il POKéMON l'ha pagato.\p"
	.string "{STR_VAR_1} dovrebbe vergognarsi per\n"
	.string "questa figuraccia.$"

ContestLiveUpdates_Text_ValiantEffortButLost::
	.string "{STR_VAR_1} ha fatto uno sforzo valoroso,\n"
	.string "ma…\p"
	.string "È stato tutto inutile, è arrivato ultimo.\p"
	.string "{STR_VAR_1} dovrebbe imparare da questa sconfitta\n"
	.string "e mettere a frutto la lezione.$"

ContestLiveUpdates_Text_Outro::
	.string "Vorrei chiudere questo programma con il\n"
	.string "solito saluto ai vincitori.\p"
	.string "Questa volta, sono {STR_VAR_1} e\n"
	.string "il {STR_VAR_2}!\p"
	.string "SPEAKER: Tutti pronti?\n"
	.string "Tutti insieme!\p"
	.string "Pubblico: {STR_VAR_1}! {STR_VAR_2}!\n"
	.string "Congratulazioni!\l"
	.string "Siete i vincitori del CONTEST!$"

gTVPokemonBattleUpdateText00::
	.string "“LOTTE POKéMON: AGGIORNAMENTO!”\p"
	.string "Vi portiamo i risultati delle lotte\n"
	.string "POKéMON in tempo reale!$"

gTVPokemonBattleUpdateText01::
	.string "Gli ALLENATORI {STR_VAR_1} e\n"
	.string "{STR_VAR_2} si sono sfidati in\l"
	.string "una LOTTA {STR_VAR_3}.\p"
	.string "Questo incontro è finito con la vittoria\n"
	.string "di {STR_VAR_1}!$"

gTVPokemonBattleUpdateText02::
	.string "In the battle, {STR_VAR_1}'s\n"
	.string "{STR_VAR_2} was a formidable force\l"
	.string "using {STR_VAR_3}!$"

gTVPokemonBattleUpdateText03::
	.string "Il {STR_VAR_2} di {STR_VAR_1} ha fatto\n"
	.string "una magra figura, che dolore.$"

gTVPokemonBattleUpdateText04::
	.string "Congratulazioni per la vittoria,\n"
	.string "{STR_VAR_1}!\p"
	.string "E per {STR_VAR_2} sconfitto,\n"
	.string "speriamo in un risultato migliore!\p"
	.string "Con questo si conclude la puntata di\n"
	.string "“LOTTE POKéMON: AGGIORNAMENTO!”$"

gTVPokemonBattleUpdateText05::
	.string "Le squadre degli ALLENATORI {STR_VAR_1} e\n"
	.string "{STR_VAR_2} si sono sfidate in una LOTTA MULTIPLA.\p"
	.string "Questo incontro è finito con la vittoria\n"
	.string "della squadra di {STR_VAR_1}.$"

gTVPokemonBattleUpdateText06::
	.string "Nella lotta, il {STR_VAR_2} nella\n"
	.string "squadra di {STR_VAR_1} è stato una forza\l"
	.string "usando {STR_VAR_3}.$"

gTVPokemonBattleUpdateText07::
	.string "La magra figura del {STR_VAR_3}\n"
	.string "nella squadra di {STR_VAR_2} ha pesato.\p"
	.string "Congratulazioni per la vittoria\n"
	.string "della tua squadra, {STR_VAR_1}!\p"
	.string "E per la squadra di {STR_VAR_2} sconfitta,\n"
	.string "speriamo in un risultato migliore!\p"
	.string "Con questo si conclude la puntata di\n"
	.string "“LOTTE POKéMON: AGGIORNAMENTO!”$"

GabbyAndTy_Text_GabbyPreFirstBattle:
	.string "GABBY: Oh! Abbiamo appena visto un\n"
	.string "ALLENATORE dall'aria tosta, proprio qui!\p"
	.string "Ok, motore avanti!\n"
	.string "Via all'intervista.$"

GabbyAndTy_Text_GabbyIntro:
	.string "GABBY: Oh! Sei {PLAYER}! Ciao!\n"
	.string "Ti ricordi di noi dall'altra volta?\p"
	.string "Ci mostri quanto sei diventato\n"
	.string "più forte? Ok, si intervista!$"

GabbyAndTy_Text_GabbyDefeatFirstTime:
	.string "GABBY: I miei occhi non mentivano!\n"
	.string "Ho scoperto un ALLENATORE strepitoso!$"

GabbyAndTy_Text_WhoAreYouInterview:
	.string "GABBY: Fantastico! Fantastico!\n"
	.string "Chi sei?!\p"
	.string "Sapevo che c'era qualcosa di speciale\n"
	.string "quando ti abbiamo visto!\p"
	.string "Oh, lascia che mi spieghi. Viaggiamo\n"
	.string "ovunque per intervistare\l"
	.string "ALLENATORI di ogni tipo.\p"
	.string "Allora, ci concedi un po' del tuo tempo\n"
	.string "per un'intervista?$"

GabbyAndTy_Text_QuoteFromLastInterview:
	.string "GABBY: “{STR_VAR_1}!”\p"
	.string "Ricordi? È la frase che ci hai dato\n"
	.string "come finale della lotta l'altra volta.\p"
	.string "Non dimentico mai cose del genere!$"

GabbyAndTy_Text_YouStompedUsInterviewAgain:
	.string "L'ultima volta che ci siamo sfidati,\n"
	.string "ci hai travolti sul nascere…\p"
	.string "Allora, che ne dici?\n"
	.string "Vuoi rilasciarci un'altra intervista?$"

GabbyAndTy_Text_YouThrewABallAtUsInterviewAgain:
	.string "L'altra volta che ci siamo sfidati,\n"
	.string "non ci hai lanciato una POKé BALL?\p"
	.string "Siamo rimasti scioccati! E l'abbiamo\n"
	.string "detto proprio a tutti!\p"
	.string "Comunque, che ne dici?\n"
	.string "Vuoi farci intervistare di nuovo?$"

GabbyAndTy_Text_CleverItemSkillsInterviewAgain:
	.string "L'ultima volta, con i tuoi oggetti\n"
	.string "ci hai battuti con astuzia.\p"
	.string "Allora, che ne dici?\n"
	.string "Vuoi rilasciarci un'altra intervista?$"

GabbyAndTy_Text_WeLookedRespectableInterviewAgain:
	.string "L'ultima volta che ci siamo sfidati,\n"
	.string "ne siamo usciti bene.\p"
	.string "Allora, che ne dici?\n"
	.string "Vuoi rilasciarci un'altra intervista?$"

GabbyAndTy_Text_InterviewAgain:
	.string "Allora, che ne dici?\n"
	.string "Vuoi rilasciarci un'altra intervista?$"

GabbyAndTy_Text_DescribeYourFeelings:
	.string "Ah, davvero?\n"
	.string "Grazie!\p"
	.string "Bene, ora descrivimi come ti sei\n"
	.string "sentito nella nostra lotta, ma\l"
	.string "breve e conciso. Vai!$"

GabbyAndTy_Text_PerfectWellBeSeeingYou:
	.string "GABBY: Mmm, sì!\n"
	.string "È il finale perfetto!\p"
	.string "Ho la sensazione che ne verrà\n"
	.string "un grande programma TV.\p"
	.string "Potrebbero trasmetterlo in TV,\n"
	.string "quindi cercaci!\p"
	.string "Ok!\n"
	.string "Ci vediamo!$"

GabbyAndTy_Text_DontGiveUpKeepingEyeOut:
	.string "GABBY: Oh…\p"
	.string "Va bene, ma non arrenderti!\n"
	.string "Terremo d'occhio i tuoi progressi!$"

GabbyAndTy_Text_KeepingAnEyeOutForYou:
	.string "GABBY: Terremo d'occhio\n"
	.string "i tuoi progressi!$"

GabbyAndTy_Text_GabbyNotEnoughMons:
	.string "GABBY: C'è in giro un ALLENATORE\n"
	.string "forte con tanti POKéMON?$"

GabbyAndTy_Text_GiveUsAnInterviewThisTime:
	.string "GABBY: Wow, sei un fenomeno!\p"
	.string "Sei diventato molto più forte, ma molto,\n"
	.string "da quando ci siamo sfidati.\p"
	.string "Avevamo ragione a puntare su di te\n"
	.string "quando ti abbiamo notato.\p"
	.string "Allora, che ne dici?\n"
	.string "Ci concedi un'intervista\l"
	.string "questa volta?$"

GabbyAndTy_Text_GabbyDefeat:
	.string "GABBY: Che lotta intensa!\n"
	.string "Hai ripreso tutto con la telecamera?$"

GabbyAndTy_Text_TyPreFirstBattle:
	.string "TY: Ehi, guarda qua! Un ALLENATORE\n"
	.string "dall'aria tosta, proprio qui!\l"
	.string "Motore avanti!$"

GabbyAndTy_Text_TyIntro:
	.string "TY: Ehi, guarda qua!\n"
	.string "Mi ricordo di te!\p"
	.string "Riprenderò tutta questa lotta\n"
	.string "con questa telecamera!$"

GabbyAndTy_Text_TyPostBattle:
	.string "TY: Sei un talento!\n"
	.string "Ho girato un filmato coi fiocchi!$"

GabbyAndTy_Text_TyNotEnoughMons:
	.string "TY: Hai solo un POKéMON\n"
	.string "e basta?\p"
	.string "Con più POKéMON faremmo\n"
	.string "un filmato migliore, ma…$"

GabbyAndTy_Text_TyDefeatFirstTime:
	.string "TY: Sì, abbiamo trovato un vero talento.\n"
	.string "È un grande scoop per noi!$"

GabbyAndTy_Text_TyDefeat:
	.string "TY: Già, ho ripreso tutto.\n"
	.string "L'intera lotta è sulla telecamera.$"

gTVInSearchOfTrainersText00::
	.string "A CACCIA DI ALLENATORI…\p"
	.string "GABBY: Ciao! Oggi visito una zona\n"
	.string "vicino a {STR_VAR_1}.\p"
	.string "Cerchiamo nuovi talenti\n"
	.string "promettenti del settore.\p"
	.string "Oggi abbiamo puntato la lente sul\n"
	.string "ALLENATORE {PLAYER}.\p"
	.string "C'è qualcosa in questo ALLENATORE\n"
	.string "che ha destato il nostro interesse.$"

gTVInSearchOfTrainersText01::
	.string "Abbiamo già lottato con {PLAYER}, ma\n"
	.string "possiamo confermare che l'ALLENATORE\l"
	.string "è decisamente migliorato.\p"
	.string "Sapevo che era qualcuno di speciale\n"
	.string "appena l'abbiamo visto!$"

gTVInSearchOfTrainersText02::
	.string "Il modo migliore per capire quanto\n"
	.string "è forte un ALLENATORE…\p"
	.string "Beh, il più rapido è lottare.\n"
	.string "E così iniziammo la ricerca!\p"
	.string "… …\p"
	.string "Così ci ritrovammo a lottare\n"
	.string "con {PLAYER}.\p"
	.string "In una prova dominante, fummo\n"
	.string "schiacciati, piegati e buttati via!\p"
	.string "{PLAYER} è spietatamente forte…\p"
	.string "Ecco le nostre impressioni dopo\n"
	.string "aver lottato con l'ALLENATORE di oggi.$"

gTVInSearchOfTrainersText03::
	.string "La combinazione di {STR_VAR_1} e\n"
	.string "{STR_VAR_3} era divina!\p"
	.string "Vederli, {STR_VAR_1} e\n"
	.string "{STR_VAR_3}, sostenersi con\l"
	.string "generosità nel pieno della lotta…\p"
	.string "Era uno spettacolo meraviglioso!\p"
	.string "{STR_VAR_2} è la mossa che l'ALLENATORE\n"
	.string "ha usato per ultima nella lotta.\p"
	.string "La mossa {STR_VAR_2} è di {STR_VAR_1}\n"
	.string "e {STR_VAR_3} il segno d'amicizia!$"

gTVInSearchOfTrainersText04::
	.string "…Ho perso fiducia in me stesso\n"
	.string "dopo il nostro scontro.\p"
	.string "Siamo stati battuti prima di poter\n"
	.string "sferrare un solo attacco.\l"
	.string "Ohhh… Singhiozzo…\p"
	.string "Nonostante ciò, le battaglie di {PLAYER}\n"
	.string "vale la pena vederle.\p"
	.string "Consiglio agli ALLENATORI sicuri\n"
	.string "di sfidare {PLAYER}.$"

gTVInSearchOfTrainersText05::
	.string "C'è una sola cosa da dire.\n"
	.string "Non azzardatevi a lanciare una POKé BALL\l"
	.string "durante una lotta tra ALLENATORI!\p"
	.string "{PLAYER} è forte, certo, ma non ha\n"
	.string "idea delle regole di base.\p"
	.string "Al nostro pubblico faccio una richiesta.\p"
	.string "Se vedete {PLAYER}, avvertite\n"
	.string "l'ALLENATORE!$"

gTVInSearchOfTrainersText06::
	.string "{PLAYER} è abile nel prevedere le\n"
	.string "mosse dell'avversario.\p"
	.string "Il tempismo nell'uso degli strumenti era\n"
	.string "notevolmente efficace!$"

gTVInSearchOfTrainersText07::
	.string "Sinceramente, pensavo di essere\n"
	.string "persino piuttosto bravo.\p"
	.string "Abbiamo perso, ma è stata\n"
	.string "una battaglia combattuta.\p"
	.string "Ma se fatichi contro di me,\n"
	.string "devi ancora allenarti, {PLAYER}!$"

gTVInSearchOfTrainersText08::
	.string "Dopo la battaglia, abbiamo chiesto a {PLAYER}\n"
	.string "un breve riassunto.\p"
	.string "L'ALLENATORE ha risposto: “{STR_VAR_1}”.\p"
	.string "I POKéMON di {PLAYER}, {STR_VAR_2} e\n"
	.string "{STR_VAR_3}…\l"
	.string "E “{STR_VAR_1}”…\p"
	.string "Mmm! Che profondità! C'è un significato\n"
	.string "profondo dietro quella frase!\p"
	.string "Non sorprende: un buon ALLENATORE ha\n"
	.string "cose belle da dire.\p"
	.string "È tutto per oggi!\n"
	.string "Alla prossima trasmissione!$"

ContestLadyShow_Text_Intro::
	.string "“GARE POKéMON IN DIRETTA!”\p"
	.string "COND: Scusate l'interruzione,\n"
	.string "e grazie per essere con noi!\p"
	.string "Vi parliamo in diretta da\n"
	.string "una gara appena conclusa:\l"
	.string "{STR_VAR_1}!\p"
	.string "Pubblico: ?!!!!\p"
	.string "COND: Oh! Sembra che i\n"
	.string "partecipanti stiano arrivando!\p"
	.string "Proverò a fare un'intervista\n"
	.string "improvvisata per voi a casa!\p"
	.string "Pubblico: ?!!!!\n"
	.string "?!!!!$"

ContestLadyShow_Text_Won::
	.string "SPEAKER: Scusate!\n"
	.string "Grazie per essere con noi in diretta!\p"
	.string "Posso congratularmi per la vittoria?\p"
	.string "Qual è stato il fattore chiave nella\n"
	.string "vittoria di oggi?\p"
	.string "BELLEZZA: Abbiamo dato il massimo\n"
	.string "oggi, io e il mio {STR_VAR_2}!\p"
	.string "Ma sono sicura che non ce l'avremmo fatta\n"
	.string "senza tutto l'aiuto che abbiamo\l"
	.string "ricevuto prima del CONTEST!\p"
	.string "SPEAKER: Hai qualcuno di speciale\n"
	.string "con cui vuoi condividere la gioia?\l"
	.string "Sentiamolo in diretta!\p"
	.string "BELLEZZA: Ehi, là fuori!\p"
	.string "{STR_VAR_3}! Ci stai guardando?\n"
	.string "Ce l'abbiamo fatta!\l"
	.string "Grazie!$"

ContestLadyShow_Text_Lost::
	.string "SPEAKER: Scusate!\n"
	.string "Grazie per essere con noi in diretta!\p"
	.string "Dovete essere delusi da questo\n"
	.string "esito. Avete commenti?\p"
	.string "BELLEZZA: È straziante…\n"
	.string "Io e il mio {STR_VAR_2} abbiamo dato il massimo…\p"
	.string "Ma sento di aver deluso tutti\n"
	.string "quelli che ci hanno sostenuto.\p"
	.string "SPEAKER: Mi dispiace dirlo, ma il POKéMON\n"
	.string "ha una colorazione un po' carente.\p"
	.string "BELLEZZA: {STR_VAR_3}, mi dispiace tanto…\n"
	.string "Farò meglio la prossima volta, giuro…\l"
	.string "…Sniff… Waaaaah!\p"
	.string "Pubblico: Hai visto?\n"
	.string "La poverina!\p"
	.string "SPEAKER: Uh… Oh no…\p"
	.string "Uh… È tutto il tempo che abbiamo oggi!\n"
	.string "Grazie per averci seguito!$"

ContestLadyShow_Text_LostBadly::
	.string "MC: Scusate!\n"
	.string "Grazie per essere con noi in diretta TV!\p"
	.string "Com'è andata la tua GARA?\p"
	.string "BELLEZZA: Non è andato niente bene…\n"
	.string "Per qualche motivo, il mio {STR_VAR_2}\l"
	.string "non riusciva a conquistare il pubblico.\p"
	.string "MC: Mi dispiace dirlo, ma la colorazione\n"
	.string "del POKéMON lascia un po' a desiderare.\p"
	.string "BELLEZZA: … … … … … …\n"
	.string "…Sniff… Waaaaah!\p"
	.string "Spettatori: Hai visto?\n"
	.string "Poverina!\p"
	.string "MC: Uh… Oh-oh…\p"
	.string "Uh… Per oggi è tutto!\n"
	.string "Grazie per averci seguito!$"
