Route4_Frlg_MapScripts::
	.byte 0

Route4_EventScript_Unused::
	end

Route4_EventScript_Woman::
	msgbox Route4_Text_TrippedOverGeodude, MSGBOX_NPC
	end

Route4_EventScript_MtMoonSign::
	msgbox Route4_Text_MtMoonEntrance, MSGBOX_SIGN
	end

Route4_EventScript_RouteSign::
	msgbox Route4_Text_RouteSign, MSGBOX_SIGN
	end

Route4_Text_TrippedOverGeodude::
	.string "Ahia! Sono inciampato in un\n"
	.string "POKéMON roccioso, GEODUDE!$"

Route4_Text_CrissyIntro::
	.string "Sono venuta al MT. MOON in cerca\n"
	.string "di POKéMON fungo.$"

Route4_Text_CrissyDefeat::
	.string "E dire che li avevo presi tutti!$"

Route4_Text_CrissyPostBattle::
	.string "Qui non ce ne saranno\n"
	.string "più di funghi.\p"
	.string "Credo di averli presi tutti.$"

Route4_Text_MtMoonEntrance::
	.string "MT. MOON\n"
	.string "Ingresso tunnel$"

Route4_Text_RouteSign::
	.string "PERCORSO 4\n"
	.string "MT. MOON - CERULEAN CITY$"

Text_MegaPunchTeach::
	.string "Un pugno di ruggente ferocia!\p"
	.string "Carico di potere distruttivo!\p"
	.string "Nei momenti difficili,\n"
	.string "MEGA PUNCH è l'attacco supremo!\l"
	.string "D'accordo, sì?\p"
	.string "Ora!\n"
	.string "Lascia che lo insegni ai tuoi POKéMON!$"

Text_MegaPunchDeclined::
	.string "Tornerai quando capirai\n"
	.string "il valore di MEGA PUNCH.$"

Text_MegaPunchWhichMon::
	.string "Bene!\n"
	.string "Quale POKéMON lo imparerà?$"

Text_MegaPunchTaught::
	.string "Ora siamo compagni nella via dei\n"
	.string "pugni!\p"
	.string "Meglio che vada prima che ti veda\n"
	.string "lo stolto fuorviato che là in giro\l"
	.string "allena solo i suoi stupidi calci.$"

Text_MegaKickTeach::
	.string "A kick of brutal ferocity!\p"
	.string "Packed with destructive power!\p"
	.string "When you get right down to it,\n"
	.string "MEGA KICK is the ultimate attack!\l"
	.string "Don't you agree?\p"
	.string "Okay!\n"
	.string "I'll teach it to your POKéMON!$"

Text_MegaKickDeclined::
	.string "Tornerai strisciando quando\n"
	.string "capirai il valore di MEGA KICK.$"

Text_MegaKickWhichMon::
	.string "Bene!\n"
	.string "Quale POKéMON vuole impararlo?$"

Text_MegaKickTaught::
	.string "Ora siamo anime affini nella via\n"
	.string "dei calci!\p"
	.string "Meglio che scappi prima che ti veda\n"
	.string "lo stolto illuso che là in giro\l"
	.string "allena solo i semplici pugni.$"

Route4_Text_PeopleLikeAndRespectBrock::
	.string "Oh, wow, quella è la BOULDERBADGE!\n"
	.string "L'hai presa da BROCK, vero?\p"
	.string "BROCK è forte. E non solo in lotta.\n"
	.string "La gente lo stima e lo rispetta.\p"
	.string "Voglio diventare CAPOPALESTRA\n"
	.string "come lui.$"
