VerdanturfTown_House_MapScripts::
	.byte 0

VerdanturfTown_House_EventScript_Woman1::
	msgbox VerdanturfTown_House_Text_TrainersGatherAtPokemonLeague, MSGBOX_NPC
	end

VerdanturfTown_House_EventScript_Woman2::
	msgbox VerdanturfTown_House_Text_DefeatEliteFourInARow, MSGBOX_NPC
	end

VerdanturfTown_House_Text_TrainersGatherAtPokemonLeague:
	.string "Lontano, nel cuore di EVER GRANDE CITY,\n"
	.string "c'è la LEGA POKéMON.\p"
	.string "Gli ALLENATORI che si radunano lì\n"
	.string "sono tutti spaventosamente abili.$"

VerdanturfTown_House_Text_DefeatEliteFourInARow:
	.string "Nella LEGA POKéMON, credo che le\n"
	.string "regole dicano di sfidare i\l"
	.string "SUPERQUATTRO tutti di fila.\p"
	.string "Se perdi con uno di loro, devi\n"
	.string "ricominciare la sfida dal\l"
	.string "primo.$"

