FuchsiaCity_House1_hns_MapScripts::
	.byte 0

FuchsiaCity_House1_EventScript_BillsOlderSister::
	msgbox FuchsiaCity_House1_Text_BillsOlderSister, MSGBOX_NPC
	end

FuchsiaCity_House1_EventScript_Youngster::
	msgbox FuchsiaCity_House1_Text_Youngster, MSGBOX_NPC
	end

FuchsiaCity_House1_Text_BillsOlderSister:
	.string "Mio nonno è da mio fratello BILL,\n"
	.string "al CAPO CELESTIA.$"

FuchsiaCity_House1_Text_Youngster:
	.string "Ho visto POKéMON lenti e strani in\n"
	.string "PISTA CICLABILE.$"

