VermilionCity_House1_hns_MapScripts::
	.byte 0

VermilionCity_House1_EventScript_Fisher::
	msgbox VermilionCity_House1_Text_FishingDude, MSGBOX_NPC
	end
VermilionCity_House1_EventScript_Photo::
	msgbox VermilionCity_House1_Text_Photo, MSGBOX_NPC
	end
VermilionCity_House1_Text_FishingDude:
	.string "Sono il TIPO DELLA PESCA, il più\n"
	.string "anziano dei FRATELLI PESCA.\p"
	.string "Hai conosciuto il GURU DELLA PESCA\n"
	.string "al LAGO D'IRA?\p"
	.string "Sogna di vedere il MAGIKARP più\n"
	.string "grande del mondo.\p"
	.string "Se non ti dispiace, potresti mostrargli\n"
	.string "i MAGIKARP che peschi?\p"
	.string "Chissà, potresti pescare il\n"
	.string "MAGIKARP dei suoi sogni.$"

VermilionCity_House1_Text_Photo:
	.string "È una foto di gente che pesca…\p"
	.string "Si stanno divertendo un mondo…$"
