Route19_Frlg_MapScripts::
	.byte 0

Route19_EventScript_RouteSign::
	msgbox Route19_Text_RouteSign, MSGBOX_SIGN
	end

Route19_Text_RichardIntro::
	.string "Devo scaldarmi i muscoli prima\n"
	.string "di andare a nuotare.$"

Route19_Text_RichardDefeat::
	.string "Bello caldo!$"

Route19_Text_RichardPostBattle::
	.string "Grazie, ragazzo!\n"
	.string "Sono pronto a nuotare.$"

Route19_Text_ReeceIntro::
	.string "Aspetta! Rallenta!\n"
	.string "Ti verrà un infarto!$"

Route19_Text_ReeceDefeat::
	.string "Ooh!\n"
	.string "Che brivido!$"

Route19_Text_ReecePostBattle::
	.string "Attento ai TENTACOOL.\n"
	.string "Pungono che è un dolore.$"

Route19_Text_MatthewIntro::
	.string "Adoro nuotare!\n"
	.string "E tu?$"

Route19_Text_MatthewDefeat::
	.string "Panciata!$"

Route19_Text_MatthewPostBattle::
	.string "Nuoto più veloce persino dei\n"
	.string "POKéMON marini.$"

Route19_Text_DouglasIntro::
	.string "Cosa c'è oltre l'orizzonte?$"

Route19_Text_DouglasDefeat::
	.string "Glub!$"

Route19_Text_DouglasPostBattle::
	.string "Vedo un paio di isole\n"
	.string "laggiù!$"

Route19_Text_DavidIntro::
	.string "Ho provato a immergermi per cercare\n"
	.string "POKéMON, ma niente.$"

Route19_Text_DavidDefeat::
	.string "Aiuto!$"

Route19_Text_DavidPostBattle::
	.string "Direi che i POKéMON di mare\n"
	.string "si pescano.$"

Route19_Text_TonyIntro::
	.string "Guardo il mare per dimenticare\n"
	.string "tutte le cose brutte successe.$"

Route19_Text_TonyDefeat::
	.string "Ooh!\n"
	.string "Che trauma!$"

Route19_Text_TonyPostBattle::
	.string "Guardo il mare per dimenticare\n"
	.string "la cosa brutta che è successa!$"

Route19_Text_AnyaIntro::
	.string "Oh, adoro il tuo mezzo!\n"
	.string "Me lo dai se vinco?$"

Route19_Text_AnyaDefeat::
	.string "Oh! Ho perso!$"

Route19_Text_AnyaPostBattle::
	.string "Per ISOLE SPUMARINE\n"
	.string "c'è ancora molta strada…\p"
	.string "Voglio tornare a FUCSIAPOLI…$"

Route19_Text_AliceIntro::
	.string "Nuotare è bello!\n"
	.string "Scottarsi no!$"

Route19_Text_AliceDefeat::
	.string "Che shock!$"

Route19_Text_AlicePostBattle::
	.string "Il mio ragazzo voleva nuotare fino a\n"
	.string "ISOLE SPUMARINE.$"

Route19_Text_AxleIntro::
	.string "Ehi, ciao!\n"
	.string "Queste acque sono insidiose!$"

Route19_Text_AxleDefeat::
	.string "Ooh!\n"
	.string "Pericolo!$"

Route19_Text_AxlePostBattle::
	.string "L-le mie gambe! Crampi!\n"
	.string "Glub, glub…$"

Route19_Text_ConnieIntro::
	.string "Ho nuotato fin qui con gli amici…\n"
	.string "Sono stanca…$"

Route19_Text_ConnieDefeat::
	.string "Sono esausta…$"

Route19_Text_ConniePostBattle::
	.string "Se cavalcassi un POKéMON sul\n"
	.string "mare, vorrei un LAPRAS.\p"
	.string "LAPRAS è così grande che\n"
	.string "mi terrebbe asciutta.$"

Route19_Text_RouteSign::
	.string "ROTTA 19\n"
	.string "FUCSIAPOLI - ISOLE SPUMA$"

Route19_Text_LiaIntro::
	.string "LIA: Badò a mio fratello.\n"
	.string "È appena diventato ALLENATORE.$"

Route19_Text_LiaDefeat::
	.string "LIA: Non si tratta così mio\n"
	.string "fratellino!$"

Route19_Text_LiaPostBattle::
	.string "LIA: Hai un fratello\n"
	.string "minore?\p"
	.string "Spero che gli insegni\n"
	.string "un sacco di cose.$"

Route19_Text_LiaNotEnoughMons::
	.string "LIA: Voglio lottare insieme\n"
	.string "a mio fratellino.\p"
	.string "Non hai due POKéMON?$"

Route19_Text_LucIntro::
	.string "LUC: Mia sorella mi ha insegnato\n"
	.string "a nuotare e ad allenare POKéMON.$"

Route19_Text_LucDefeat::
	.string "LUC: Oh, wow!\n"
	.string "Più forte di mia sorella!$"

Route19_Text_LucPostBattle::
	.string "LUC: Mia sorella è forte e gentile.\n"
	.string "La trovo fantastica!$"

Route19_Text_LucNotEnoughMons::
	.string "LUC: Non ci sto se non posso\n"
	.string "lottare con mia sorella.\p"
	.string "Non hai due POKéMON?$"
