FiveIsland_House2_Frlg_MapScripts::
	.byte 0

FiveIsland_House2_EventScript_OldMan::
	msgbox FiveIsland_House2_Text_MeadowBelongedToFamily, MSGBOX_NPC
	end

FiveIsland_House2_Text_MeadowBelongedToFamily::
	.string "Il PRATO è della nostra\n"
	.string "famiglia da generazioni.\p"
	.string "Ci avrei dovuto costruire una\n"
	.string "villa enorme.\p"
	.string "Meglio che vederci scorrazzare\n"
	.string "quei teppisti!$"

