Route21_North_Frlg_MapScripts::
	.byte 0

Route21_North_Text_RonaldIntro::
	.string "Vuoi sapere se i pesci\n"
	.string "abboccano?$"

Route21_North_Text_RonaldDefeat::
	.string "Uff!$"

Route21_North_Text_RonaldPostBattle::
	.string "Non prendo niente di buono.\n"
	.string "Neanche un POKéMON decente!$"

Route21_North_Text_WadeIntro::
	.string "Ho preso un bel po'!\n"
	.string "Ci proviamo?$"

Route21_North_Text_WadeDefeat::
	.string "Heheh, i MAGIKARP non sono\n"
	.string "all'altezza, vero?$"

Route21_North_Text_WadePostBattle::
	.string "Prendo solo MAGIKARP!$"

Route21_North_Text_SpencerIntro::
	.string "Il mare purifica corpo e anima!$"

Route21_North_Text_SpencerDefeat::
	.string "Ahi!$"

Route21_North_Text_SpencerPostBattle::
	.string "Il mare è fantastico, ma anche\n"
	.string "le montagne mi piacciono.$"

@ Below is the battle text for the Cue Ball that was on Route 21 in Gen 1.
@ This trainer wasnt used in Gen 3 so their text goes unused/untranslated
@ Interestingly they did add a rematch intro text for this trainer
@ English translations from RB are listed

@ "What's wrong with me swimming?"
Route21_North_Text_CueBallIntro::
	.string "おれだって　たまには\n"
	.string "およぎに　くるぜ！$"

@ "Cheap shot!"
Route21_North_Text_CueBallDefeat::
	.string "ぐわわ！$"

@ "I look like what? A studded inner tube? Get lost!"
Route21_North_Text_CueBallPostBattle::
	.string "うきやすそう　だと？\n"
	.string "うるせー　おおきな　おせわだッ！$"
