SevenIsland_SevaultCanyon_Entrance_Frlg_MapScripts::
	.byte 0

SevenIsland_SevaultCanyon_Entrance_EventScript_RouteSign::
	msgbox SevenIsland_SevaultCanyon_Entrance_Text_RouteSign, MSGBOX_SIGN
	end

SevenIsland_SevaultCanyon_Entrance_Text_MiahIntro::
	.string "Kyahaha!\n"
	.string "Ti spazzo via senza sforzo!$"

SevenIsland_SevaultCanyon_Entrance_Text_MiahDefeat::
	.string "Tch!\n"
	.string "Troppo forte per me!$"

SevenIsland_SevaultCanyon_Entrance_Text_MiahPostBattle::
	.string "Come?\n"
	.string "Non sembro quel che sono?\p"
	.string "Eh, fa parte della mia strategia!$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonIntro::
	.string "Ciao!\n"
	.string "Fai parte del mio fan club?$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonDefeat::
	.string "Oh, quindi non sei un fan…\p"
	.string "Beh, posso rimediare.\n"
	.string "Ti canto qualcosa!$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonPostBattle::
	.string "Lalalah…\n"
	.string "Mando in campo i miei POKéMON,\l"
	.string "le ragazze urlano in coro!$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasIntro::
	.string "Quest'isola è troppo estesa…\n"
	.string "Non è facile pattugliarla.$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasDefeat::
	.string "Uh-uh…$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasPostBattle::
	.string "Gli ALLENATORI di città\n"
	.string "sono davvero tosti.\p"
	.string "Andrai alla TORRE,\n"
	.string "vero?$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelineIntro::
	.string "Punisco chi maltratta\n"
	.string "i POKéMON!$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelineDefeat::
	.string "Non sembri un problema,\n"
	.string "ALLENATORE.$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelinePostBattle::
	.string "Se tratti bene i tuoi POKéMON,\n"
	.string "ti capiranno.$"

SevenIsland_SevaultCanyon_Entrance_Text_EveIntro::
	.string "EVE: Farò squadra con JON e\n"
	.string "l otteremo insieme.$"

SevenIsland_SevaultCanyon_Entrance_Text_EveDefeat::
	.string "EVE: Io e JON abbiamo perso.\n"
	.string "Ehehe.$"

SevenIsland_SevaultCanyon_Entrance_Text_EvePostBattle::
	.string "EVE: Mi impegnerò di più con\n"
	.string "JON.$"

SevenIsland_SevaultCanyon_Entrance_Text_EveNotEnoughMons::
	.string "EVE: Voglio fare squadra con JON\n"
	.string "quando ti sfido.\p"
	.string "Torna con due POKéMON, okay?$"

SevenIsland_SevaultCanyon_Entrance_Text_JonIntro::
	.string "JON: Quando sono con EVE, mi\n"
	.string "sembra di non poter mai perdere.$"

SevenIsland_SevaultCanyon_Entrance_Text_JonDefeat::
	.string "JON: Quando sono con EVE,\n"
	.string "non mi sembra di aver perso!$"

SevenIsland_SevaultCanyon_Entrance_Text_JonPostBattle::
	.string "JON: Quando sono con EVE, mi\n"
	.string "sent o frastornato se vinco o perdo.\p"
	.string "È STREGONE!$"

SevenIsland_SevaultCanyon_Entrance_Text_JonNotEnoughMons::
	.string "JON: Se è con EVE, sarò\n"
	.string "felice di lottare con te.\p"
	.string "Quindi vorrei fare una\n"
	.string "lotta due contro due, se posso.$"

SevenIsland_SevaultCanyon_Entrance_Text_RouteSign::
	.string "INGRESSO CANYON SEVAULT\p"
	.string "Si prega di non danneggiare\n"
	.string "le piante del CANYON.$"

