SafariZone_East_RestHouse_Frlg_MapScripts::
	.byte 0

SafariZone_East_RestHouse_EventScript_Rocker::
	msgbox SafariZone_East_Text_CaughtChanseyAllWorthwhile, MSGBOX_NPC
	end

SafariZone_East_RestHouse_EventScript_Scientist::
	msgbox SafariZone_East_Text_HowManyDidYouCatch, MSGBOX_NPC
	end

SafariZone_East_RestHouse_EventScript_BaldingMan::
	msgbox SafariZone_East_Text_TiredFromAllTheFun, MSGBOX_NPC
	end

SafariZone_East_Text_HowManyDidYouCatch::
	.string "Quanti ne hai presi?\n"
	.string "Sono distrutto dallo sforzo!$"

SafariZone_East_Text_CaughtChanseyAllWorthwhile::
	.string "Ho catturato un CHANSEY!\p"
	.string "Così ne è valsa la pena.$"

SafariZone_East_Text_TiredFromAllTheFun::
	.string "Fiuu!\n"
	.string "Sono stanco per tutto il divertimento!$"

