CeladonCity_House1_Frlg_MapScripts::
	.byte 0

CeladonCity_House1_EventScript_RocketChief::
	msgbox CeladonCity_House1_Text_SlotsReelInTheDough, MSGBOX_NPC
	end

CeladonCity_House1_EventScript_Rocket1::
	msgbox CeladonCity_House1_Text_ShippedMonsAsSlotPrizes, MSGBOX_NPC
	end

CeladonCity_House1_EventScript_Rocket2::
	msgbox CeladonCity_House1_Text_DontTouchGameCornerPoster, MSGBOX_NPC
	end

CeladonCity_House1_Text_SlotsReelInTheDough::
	.string "Eh eh!\p"
	.string "Le slot fruttano un sacco,\n"
	.string "altroché!$"

CeladonCity_House1_Text_ShippedMonsAsSlotPrizes::
	.string "CAPO!\p"
	.string "Abbiamo spedito altri duemila\n"
	.string "POKéMON come premi slot!\l"
	.string "Ancora oggi!$"

CeladonCity_House1_Text_DontTouchGameCornerPoster::
	.string "Non toccare il poster del GAME\n"
	.string "CORNER!\p"
	.string "Non c'è un interruttore segreto!$"

