SootopolisCity_House7_MapScripts::
	.byte 0

SootopolisCity_House7_EventScript_OldMan::
	msgbox SootopolisCity_House7_Text_CityFromEruptedVolcano, MSGBOX_NPC
	end

SootopolisCity_House7_EventScript_PokefanF::
	msgbox SootopolisCity_House7_Text_CaveMadeToKeepSomething, MSGBOX_NPC
	end

SootopolisCity_House7_Text_CityFromEruptedVolcano:
	.string "An underwater volcano erupted and\n"
	.string "forced itself up from the depths.\p"
	.string "Its crater emerged from the sea and\n"
	.string "became filled with rainwater.\p"
	.string "That's how SOOTOPOLIS CITY came into\n"
	.string "being.$"

SootopolisCity_House7_Text_CaveMadeToKeepSomething:
	.string "La grotta che collega SOOTOPOLIS\n"
	.string "al mondo esterno…\p"
	.string "Sembra fatta apposta per\n"
	.string "impedire a qualcosa di uscire.\p"
	.string "O me lo sto solo immaginando?$"

