PewterCity_House2_Frlg_MapScripts::
	.byte 0

PewterCity_House2_EventScript_OldMan::
	msgbox PewterCity_House2_Text_MonsLearnTechniquesAsTheyGrow, MSGBOX_NPC
	end

PewterCity_House2_EventScript_LittleBoy::
	msgbox PewterCity_House2_Text_MonsEasierCatchIfStatused, MSGBOX_NPC
	end

PewterCity_House2_Text_MonsLearnTechniquesAsTheyGrow::
	.string "I POKéMON imparano nuove\n"
	.string "tecniche crescendo.\p"
	.string "Ma alcune mosse gliele devono\n"
	.string "insegnare le persone.$"

PewterCity_House2_Text_MonsEasierCatchIfStatused::
	.string "Un POKéMON si cattura più\n"
	.string "facilmente se ha un problema\p"
	.string "di stato. Sonno, veleno,\n"
	.string "scottatura o paralisi…\p"
	.string "Sono tutti efficaci.\n"
	.string "Ma catturare non è mai sicuro!$"

