Route2_ViridianForest_NorthEntrance_Frlg_MapScripts::
	.byte 0

Route2_ViridianForest_NorthEntrance_EventScript_Youngster::
	msgbox Route2_ViridianForest_NorthEntrance_Text_ManyMonsOnlyInForests, MSGBOX_NPC
	end

Route2_ViridianForest_NorthEntrance_EventScript_OldMan::
	msgbox Route2_ViridianForest_NorthEntrance_Text_CanCutSkinnyTrees, MSGBOX_NPC
	end

Route2_ViridianForest_NorthEntrance_EventScript_CooltrainerF::
	msgbox Route2_ViridianForest_NorthEntrance_Text_CanCancelEvolution, MSGBOX_NPC
	end

Route2_ViridianForest_NorthEntrance_Text_ManyMonsOnlyInForests::
	.string "Molti POKéMON vivono solo nelle foreste \n"
	.string "e nelle caverne.\p"
	.string "Devi essere persistente e guardare\n"
	.string "ovunque per trovarne di diversi.$"

Route2_ViridianForest_NorthEntrance_Text_CanCutSkinnyTrees::
	.string "Hai notato gli alberi sottili\n"
	.string "sul ciglio della strada?\p"
	.string "Si possono tagliare con una mossa\n"
	.string "speciale dei POKéMON, dicono.$"

Route2_ViridianForest_NorthEntrance_Text_CanCancelEvolution::
	.string "Conosci la tecnica per annullare\n"
	.string "l'evoluzione?\p"
	.string "Quando un POKéMON si evolve, puoi\n"
	.string "fermare il processo.\p"
	.string "È una tecnica per allevare\n"
	.string "i POKéMON così come sono.$"

