TwoIsland_CapeBrink_House_Frlg_MapScripts::
	.byte 0

@ See move_tutors.inc

Text_UltimateMoveThatMon::
	.string "Ho perfezionato la mossa finale del\n"
	.string "suo tipo…\p"
	.string "Ma nessuno la prenderà per\n"
	.string "usarla in futuro?\p"
	.string "…Hm? Hmmm!\p"
	.string "T-tu…\n"
	.string "Qu-quel {STR_VAR_1}…$"

Text_JustMistaken::
	.string "…No…\n"
	.string "Mi ero solo sbagliato.$"

Text_AllowMeToTeachMonUltimateMove::
	.string "Oh! Questo è quello giusto!\n"
	.string "Questo è il POKéMON!\p"
	.string "Questo {STR_VAR_1} è degno di\n"
	.string "imparare la mia mossa finale!\p"
	.string "Me lo permetti?\p"
	.string "Permetti al tuo {STR_VAR_1} di\n"
	.string "imparare la mia {STR_VAR_2}?$"

Text_YouRejectIt::
	.string "Gaah! La rifiuti?\n"
	.string "No, non mi farò dissuadere!$"

Text_LetMeConferUltimateMove::
	.string "Me lo permetti?\p"
	.string "Allora, lascia che trasmetta la mia mossa\n"
	.string "finale {STR_VAR_2} al tuo {STR_VAR_1}.\p"
	.string "Ggggrah-awooo!$"

Text_TaughtMove::
	.string "Ansimo, ansimo, ansimo…\p"
	.string "Non pensavo di poter insegnare quella\n"
	.string "mossa mentre ero ancora vivo…$"

Text_MakeBestUseOfMove::
	.string "Ti imploro di fare il miglior\n"
	.string "uso di quella mossa e diventare forte!$"

Text_PassedOnEverythingIKnow::
	.string "Ansimo, ansimo, ansimo…\p"
	.string "Ora non ho rimpianti.\n"
	.string "Ho trasmesso tutto ciò che so.\p"
	.string "Ora posso vivere la mia vita sapendo\n"
	.string "che il mio lavoro è finito.$"

Text_FeelRejuvenated::
	.string "Dopo aver trasmesso la mia sapienza a\n"
	.string "te, mi sono sentito molto sollevato.\p"
	.string "Anzi, mi sento ringiovanito,\n"
	.string "come se fossi di nuovo giovane!$"
