ThreeIsland_BondBridge_Frlg_MapScripts::
	.byte 0

ThreeIsland_BondBridge_EventScript_BerryForestSign::
	msgbox ThreeIsland_BondBridge_Text_BerryForestAhead, MSGBOX_SIGN
	end

ThreeIsland_BondBridge_EventScript_BondBridgeSign::
	msgbox ThreeIsland_BondBridge_Text_BondBridgeSign, MSGBOX_SIGN
	end

ThreeIsland_BondBridge_Text_NikkiIntro::
	.string "Il sapore salato del mare…\n"
	.string "Mi solletica il cuore.$"

ThreeIsland_BondBridge_Text_NikkiDefeat::
	.string "…Sniff, sniff…\n"
	.string "C'è un odore sgradevole…$"

ThreeIsland_BondBridge_Text_NikkiPostBattle::
	.string "Forse quel puzzo è il sudore\n"
	.string "del tuo POKéMON…$"

ThreeIsland_BondBridge_Text_VioletIntro::
	.string "Dove corri con tanta\n"
	.string "fretta?$"

ThreeIsland_BondBridge_Text_VioletDefeat::
	.string "Stai allevando dei POKéMON\n"
	.string "fantastici.$"

ThreeIsland_BondBridge_Text_VioletPostBattle::
	.string "Se continui da questa parte,\n"
	.string "arriverai alla FORESTA BOSCO.$"

ThreeIsland_BondBridge_Text_AmiraIntro::
	.string "Mia mamma ha detto che non posso nuotare\n"
	.string "senza il mio salvagente.$"

ThreeIsland_BondBridge_Text_AmiraDefeat::
	.string "Uaaah!\n"
	.string "Uaaah!$"

ThreeIsland_BondBridge_Text_AmiraPostBattle::
	.string "Quest'anno finalmente\n"
	.string "imparerò a nuotare!$"

ThreeIsland_BondBridge_Text_AlexisIntro::
	.string "Evvai, evvai!\n"
	.string "POKéMON!$"

ThreeIsland_BondBridge_Text_AlexisDefeat::
	.string "E adesso cosa succede?$"

ThreeIsland_BondBridge_Text_AlexisPostBattle::
	.string "Ho vinto io?\n"
	.string "O ho perso io?$"

ThreeIsland_BondBridge_Text_TishaIntro::
	.string "Oh no, non venire qui!\n"
	.string "Ti prego, stammi lontano!$"

ThreeIsland_BondBridge_Text_TishaDefeat::
	.string "Va bene, hai vinto!\n"
	.string "Ora te ne vuoi andare?$"

ThreeIsland_BondBridge_Text_TishaPostBattle::
	.string "Un POKéMON mi ha strappato\n"
	.string "il costume.\p"
	.string "Non posso uscire dall'acqua!$"

ThreeIsland_BondBridge_Text_JoyIntro::
	.string "JOY: Ti mostreremo qual è il nostro\n"
	.string "POKéMON preferito!$"

ThreeIsland_BondBridge_Text_JoyDefeat::
	.string "JOY: Ohh…\n"
	.string "MEG!$"

ThreeIsland_BondBridge_Text_JoyPostBattle::
	.string "JOY: Non è stato divertente?\n"
	.string "Spero di lottare di nuovo!$"

ThreeIsland_BondBridge_Text_JoyNotEnoughMons::
	.string "JOY: Voglio tanto lottare con\n"
	.string "MEG.\p"
	.string "Un solo POKéMON non basta.$"

ThreeIsland_BondBridge_Text_MegIntro::
	.string "MEG: Ti mostreremo il nostro\n"
	.string "POKéMON preferito.$"

ThreeIsland_BondBridge_Text_MegDefeat::
	.string "MEG: Ohh…\n"
	.string "CHE GIOIA!$"

ThreeIsland_BondBridge_Text_MegPostBattle::
	.string "MEG: JOY, non è stato divertente?$"

ThreeIsland_BondBridge_Text_MegNotEnoughMons::
	.string "MEG: Voglio lottare insieme\n"
	.string "a JOY.\p"
	.string "Un solo POKéMON non basta.$"

ThreeIsland_BondBridge_Text_BerryForestAhead::
	.string "FORESTA BACche AVANTI$"

ThreeIsland_BondBridge_Text_BondBridgeSign::
	.string "PONTE LEGAME\n"
	.string "Si prega di fare silenzio.\p"
	.string "FORESTA BACche AVANTI$"

