Route25_Frlg_MapScripts::
	.byte 0

Route25_EventScript_SeaCottageSign::
	msgbox Route25_Text_SeaCottageSign, MSGBOX_SIGN
	end

Route25_EventScript_Man::
	msgbox Route25_Text_AreYouHereAlone, MSGBOX_NPC
	end

Route25_Text_JoeyIntro::
	.string "Gli ALLENATORI del posto\n"
	.string "si allenano qui.$"

Route25_Text_JoeyDefeat::
	.string "Niente male.$"

Route25_Text_JoeyPostBattle::
	.string "Tutti i POKéMON hanno debolezze.\n"
	.string "Anche i più forti.\p"
	.string "Perciò è meglio allevare\n"
	.string "POKéMON di tipi diversi.$"

Route25_Text_DanIntro::
	.string "Papà mi ha portato a una festa sulla\n"
	.string "M/N ANNA a PORTAMARINA.$"

Route25_Text_DanDefeat::
	.string "Non sono arrabbiato!$"

Route25_Text_DanPostBattle::
	.string "Sulla M/N ANNA ho visto ALLENATORI\n"
	.string "da tutto il mondo.$"

Route25_Text_FlintIntro::
	.string "Sono un tipo in gamba.\n"
	.string "Ho una ragazza!$"

Route25_Text_FlintDefeat::
	.string "Oh, accidenti…$"

Route25_Text_FlintPostBattle::
	.string "Oh, beh.\n"
	.string "La mia ragazza mi tirerà su.$"

Route25_Text_KelseyIntro::
	.string "Ciao!\n"
	.string "Il mio ragazzo è forte!$"

Route25_Text_KelseyDefeat::
	.string "Non sono in gran forma…$"

Route25_Text_KelseyPostBattle::
	.string "Vorrei che il mio ragazzo fosse\n"
	.string "bravo come te.$"

Route25_Text_ChadIntro::
	.string "Avevo questa sensazione…\n"
	.string "Sapevo che dovevo sfidarti!$"

Route25_Text_ChadDefeat::
	.string "Sapevo che avrei perso!$"

Route25_Text_ChadPostBattle::
	.string "Se il tuo POKéMON è confuso,\n"
	.string "cambialo.\p"
	.string "È una buona tattica.$"

Route25_Text_HaleyIntro::
	.string "La mia amica ha tanti POKéMON carini.\n"
	.string "Che invidia!$"

Route25_Text_HaleyDefeat::
	.string "Non sono poi così gelosa!$"

Route25_Text_HaleyPostBattle::
	.string "Vieni dal MT. MOON?\n"
	.string "Posso avere un CLEFAIRY?$"

Route25_Text_FranklinIntro::
	.string "Sono appena sceso dal MT. MOON,\n"
	.string "ma ho ancora benzina nel serbatoio!$"

Route25_Text_FranklinDefeat::
	.string "Ti sei dato da fare!$"

Route25_Text_FranklinPostBattle::
	.string "Accidenti!\n"
	.string "Uno ZUBAT mi ha morso in quella grotta.$"

Route25_Text_NobIntro::
	.string "Vado a vedere la collezione di\n"
	.string "un POKéMANIAC al capo.$"

Route25_Text_NobDefeat::
	.string "Mi hai battuto, e alla grande,\n"
	.string "pure!$"

Route25_Text_NobPostBattle::
	.string "Il POKéMANIAC merita proprio\n"
	.string "il nome.\p"
	.string "La sua collezione ha molte specie\n"
	.string "rare di POKéMON.$"

Route25_Text_WayneIntro::
	.string "Vai a vedere BILL?\n"
	.string "Prima, si lotta!$"

Route25_Text_WayneDefeat::
	.string "Sei un fenomeno.$"

Route25_Text_WaynePostBattle::
	.string "Il sentiero qui sotto è una scorciatoia\n"
	.string "per CERULEAN CITY.$"

Route25_Text_SeaCottageSign::
	.string "CASA DEL MARE\n"
	.string "Qui vive BILL!$"

Route25_Text_MistyHighHopesAboutThisPlace::
	.string "This cape is a famous date spot.\p"
	.string "MISTY, the GYM LEADER, has high\n"
	.string "hopes about this place.$"

Route25_Text_AreYouHereAlone::
	.string "Ciao, sei qui da solo?\p"
	.string "Se sei al promontorio di CELESTOPOLI…\n"
	.string "Beh, dovresti stare in coppia.$"

