Route17_Frlg_MapScripts::
	.byte 0

Route17_EventScript_ItemsNotice::
	msgbox Route17_Text_WatchOutForDiscardedItems, MSGBOX_SIGN
	end

Route17_EventScript_TrainerTips1::
	msgbox Route17_Text_SameSpeciesGrowDifferentRates, MSGBOX_SIGN
	end

Route17_EventScript_TrainerTips2::
	msgbox Route17_Text_PressBToStayInPlace, MSGBOX_SIGN
	end

Route17_EventScript_RouteSign::
	msgbox Route17_Text_RouteSign, MSGBOX_SIGN
	end

Route17_EventScript_BallsNotice::
	msgbox Route17_Text_DontThrowGameThrowBalls, MSGBOX_SIGN
	end

Route17_EventScript_CyclingRoadSign::
	msgbox Route17_Text_CyclingRoadSign, MSGBOX_SIGN
	end

Route17_Text_RaulIntro::
	.string "Non ci si arricchisce\n"
	.string "sfidando i ragazzini.$"

Route17_Text_RaulDefeat::
	.string "Che batosta!$"

Route17_Text_RaulPostBattle::
	.string "Si trovano belle cose in giro\n"
	.string "sulla PISTA CICLABILE.\p"
	.string "Raccoglierle e venderle\n"
	.string "rende bene.$"

Route17_Text_IsaiahIntro::
	.string "Vado fiero del mio fisico, ragazzo.\n"
	.string "Forza!$"

Route17_Text_IsaiahDefeat::
	.string "Uao!$"

Route17_Text_IsaiahPostBattle::
	.string "Ti caccerei via a pancia\n"
	.string "in avanti!$"

Route17_Text_VirgilIntro::
	.string "Vai a FUCSIAPOLI?$"

Route17_Text_VirgilDefeat::
	.string "Che botta!$"

Route17_Text_VirgilPostBattle::
	.string "Adoro gareggiare in discesa!$"

Route17_Text_BillyIntro::
	.string "Siamo MOTOCICLISTI!\n"
	.string "Le strade sono nostre, amico!$"

Route17_Text_BillyDefeat::
	.string "Bruciato!$"

Route17_Text_BillyPostBattle::
	.string "Cerchi l'avventura?$"

Route17_Text_NikolasIntro::
	.string "Fatti fulminare dal VOLTORB!$"

Route17_Text_NikolasDefeat::
	.string "A terra!$"

Route17_Text_NikolasPostBattle::
	.string "Ho preso il mio VOLTORB nella\n"
	.string "CENTRALE ABBANDONATA.$"

Route17_Text_ZeekIntro::
	.string "Ho fatto salire di livello il POKéMON,\n"
	.string "ma non si evolve. Perché?$"

Route17_Text_ZeekDefeat::
	.string "Ma come!$"

Route17_Text_ZeekPostBattle::
	.string "Forse alcuni POKéMON hanno bisogno\n"
	.string "di PIETRE per evolversi.$"

Route17_Text_JamalIntro::
	.string "Ho bisogno di muovermi un po'!$"

Route17_Text_JamalDefeat::
	.string "Fiuu!\n"
	.string "Che allenamento!$"

Route17_Text_JamalPostBattle::
	.string "Sicuro di aver perso peso!$"

Route17_Text_CoreyIntro::
	.string "Sii ribelle!$"

Route17_Text_CoreyDefeat::
	.string "Aaah!$"

Route17_Text_CoreyPostBattle::
	.string "Lotta per le tue idee!$"

Route17_Text_JaxonIntro::
	.string "Bella BICI!\n"
	.string "Come va?$"

Route17_Text_JaxonDefeat::
	.string "Perbacco!$"

Route17_Text_JaxonPostBattle::
	.string "In discesa è difficile sterzare.$"

Route17_Text_WilliamIntro::
	.string "Vai via, ragazzino!\n"
	.string "Sono distrutto!$"

Route17_Text_WilliamDefeat::
	.string "Sei soddisfatto?$"

Route17_Text_WilliamPostBattle::
	.string "Devo farmi un pisolino!$"

Route17_Text_WatchOutForDiscardedItems::
	.string "È un avviso.\p"
	.string "Attenzione agli oggetti abbandonati.$"

Route17_Text_SameSpeciesGrowDifferentRates::
	.string "CONSIGLI PER ALLENATORI\p"
	.string "Ogni POKéMON è unico.\p"
	.string "Anche POKéMON della stessa specie\n"
	.string "e livello crescono diversamente.$"

Route17_Text_PressBToStayInPlace::
	.string "CONSIGLI PER ALLENATORI\p"
	.string "Premi il tasto B per restare fermo\n"
	.string "mentre sei in discesa.$"

Route17_Text_RouteSign::
	.string "PERCORSO 17\n"
	.string "AZZURROPOLI - FUCSIAPOLI$"

Route17_Text_DontThrowGameThrowBalls::
	.string "È un avviso!\p"
	.string "Non gettare la partita, getta le POKé\n"
	.string "BALL, piuttosto!$"

Route17_Text_CyclingRoadSign::
	.string "PISTA CICLABILE\n"
	.string "Fine discesa!$"

