Route6_Frlg_MapScripts::
	.byte 0

Route6_EventScript_UndergroundPathSign::
	msgbox Route6_Text_UndergroundPathSign, MSGBOX_SIGN
	end

Route6_Text_RickyIntro::
	.string "Chi va là?\n"
	.string "Smetti di ascoltarci!$"

Route6_Text_RickyDefeat::
	.string "Non riesco proprio a vincere!$"

Route6_Text_RickyPostBattle::
	.string "Sussurro…\n"
	.string "Sussurro…$"

Route6_Text_NancyIntro::
	.string "Scusa!\n"
	.string "È una conversazione privata!$"

Route6_Text_NancyDefeat::
	.string "Uffa!\n"
	.string "Odio perdere.$"

Route6_Text_NancyPostBattle::
	.string "Sussurro…\n"
	.string "Sussurro…$"

Route6_Text_KeigoIntro::
	.string "Qui in giro non ci sono molti insetti.$"

Route6_Text_KeigoDefeat::
	.string "No!\n"
	.string "Stai scherzando!$"

Route6_Text_KeigoPostBattle::
	.string "Mi piacciono gli insetti, torno alla\n"
	.string "FORESTA DI VIRIDIAN.$"

Route6_Text_JeffIntro::
	.string "Eh?\n"
	.string "Vuoi parlare con me?$"

Route6_Text_JeffDefeat::
	.string "Che pizza…\n"
	.string "Non ho superato la tua sfida…$"

Route6_Text_JeffPostBattle::
	.string "Dovrei portare più POKéMON con\n"
	.string "me. Mi sentirei più sicuro.$"

Route6_Text_IsabelleIntro::
	.string "Io?\n"
	.string "Beh, okay. Gioco!$"

Route6_Text_IsabelleDefeat::
	.string "Non è andata bene…$"

Route6_Text_IsabellePostBattle::
	.string "Voglio diventare più forte.\n"
	.string "Qual è il tuo segreto?$"

Route6_Text_ElijahIntro::
	.string "Non ti ho mai visto da queste parti.\n"
	.string "Sei forte?$"

Route6_Text_ElijahDefeat::
	.string "Sei troppo forte!$"

Route6_Text_ElijahPostBattle::
	.string "I miei POKéMON sono deboli?\n"
	.string "O sono scarso io?\l"
	.string "Tu che dici?$"

Route6_Text_UndergroundPathSign::
	.string "VIA SOTTERRANEA\n"
	.string "CERULEAN CITY - VERMILION CITY$"

