SixIsland_OutcastIsland_Frlg_MapScripts::
	.byte 0

SixIsland_OutcastIsland_EventScript_Rocket::
	trainerbattle_single TRAINER_TEAM_ROCKET_GRUNT_46, SixIsland_OutcastIsland_Text_RocketIntro, SixIsland_OutcastIsland_Text_RocketDefeat
	msgbox SixIsland_OutcastIsland_Text_RocketPostBattle, MSGBOX_AUTOCLOSE
	end

SixIsland_OutcastIsland_Text_RocketIntro::
	.string "Da queste parti non ci sono\n"
	.string "POKéMON rari! Nemmeno uno!\p"
	.string "Questo mi fa arrabbiare, sai.\n"
	.string "Me la prendo con te!$"

SixIsland_OutcastIsland_Text_RocketDefeat::
	.string "…Eh?$"

SixIsland_OutcastIsland_Text_RocketPostBattle::
	.string "Allora, non hai visto\n"
	.string "POKéMON rari, vero?$"

SixIsland_OutcastIsland_Text_TylorIntro::
	.string "Non ho proprio fortuna.\n"
	.string "Una lotta mi distrarrebbe!$"

SixIsland_OutcastIsland_Text_TylorDefeat::
	.string "No, niente fortuna…$"

SixIsland_OutcastIsland_Text_TylorPostBattle::
	.string "Non posso tornare a casa senza\n"
	.string "aver catturato qualcosa.$"

SixIsland_OutcastIsland_Text_MymoIntro::
	.string "Anf… Anf…\p"
	.string "Ho nuotato dal PORTO DI SIX ISLE\n"
	.string "tutto d'un fiato.$"

SixIsland_OutcastIsland_Text_MymoDefeat::
	.string "Anf…\n"
	.string "Anf…$"

SixIsland_OutcastIsland_Text_MymoPostBattle::
	.string "Sono solo a metà strada…\n"
	.string "Sono distrutto…$"

SixIsland_OutcastIsland_Text_NicoleIntro::
	.string "Non è facile mandare i POKéMON\n"
	.string "in campo mentre si nuota, sai?$"

SixIsland_OutcastIsland_Text_NicoleDefeat::
	.string "Non ho perso nel nuoto con te.\n"
	.string "Questo non mi importa.$"

SixIsland_OutcastIsland_Text_NicolePostBattle::
	.string "Vai verso l'isola più\n"
	.string "avanti?\p"
	.string "Non ci ho visto niente\n"
	.string "di interessante.$"

SixIsland_OutcastIsland_Text_AvaIntro::
	.string "AVA: Facciamo una\n"
	.string "lotta marina due contro due!$"

SixIsland_OutcastIsland_Text_AvaDefeat::
	.string "AVA: Oh, sei fantastico!\n"
	.string "E per di più sei da solo!$"

SixIsland_OutcastIsland_Text_AvaPostBattle::
	.string "AVA: Sai, preferisco il\n"
	.string "mare a qualsiasi piscina.$"

SixIsland_OutcastIsland_Text_AvaNotEnoughMons::
	.string "AVA: Ci sfidi\n"
	.string "in lotta?\p"
	.string "Ti servono almeno due POKéMON\n"
	.string "per farlo.$"

SixIsland_OutcastIsland_Text_GebIntro::
	.string "GEB: Sorellona, aiuto!\n"
	.string "Lotta insieme a me!$"

SixIsland_OutcastIsland_Text_GebDefeat::
	.string "GEB: Wow, sorellona, questo\n"
	.string "è davvero forte!$"

SixIsland_OutcastIsland_Text_GebPostBattle::
	.string "GEB: Mi aggrappo a mia sorella\n"
	.string "perché non tocco il fondo.$"

SixIsland_OutcastIsland_Text_GebNotEnoughMons::
	.string "GEB: Lotta contro me e\n"
	.string "mia sorella!\p"
	.string "…Oh, non hai due POKéMON?$"
