Route14_Frlg_MapScripts::
	.byte 0

Route14_EventScript_RouteSign::
	msgbox Route14_Text_RouteSign, MSGBOX_SIGN
	end

Route14_Text_CarterIntro::
	.string "Devi usare le MT per insegnare\n"
	.string "mosse buone ai POKéMON.$"

Route14_Text_CarterDefeat::
	.string "Non sono ancora abbastanza forte.$"

Route14_Text_CarterPostBattle::
	.string "Hai delle MN, vero? I POKéMON\n"
	.string "non dimenticano quelle mosse facilmente.$"

Route14_Text_MitchIntro::
	.string "I miei POKéMON uccello sono pronti\n"
	.string "per la lotta.$"

Route14_Text_MitchDefeat::
	.string "Non sono pronto!$"

Route14_Text_MitchPostBattle::
	.string "I miei POKéMON uccello devono imparare\n"
	.string "mosse migliori.$"

Route14_Text_BeckIntro::
	.string "Vendono MT al\n"
	.string "CENTRO COMMERCIALE di AZZURROPOLI.\p"
	.string "Le MT non sono rare, ma pochi\n"
	.string "hanno le MN.$"

Route14_Text_BeckDefeat::
	.string "Ah, che peccato!$"

Route14_Text_BeckPostBattle::
	.string "Prova a insegnare a un POKéMON una\n"
	.string "mossa del suo stesso tipo.\p"
	.string "A quanto pare aumenta la potenza\n"
	.string "della mossa.$"

Route14_Text_MarlonIntro::
	.string "Hai insegnato ai tuoi POKéMON\n"
	.string "uccello come usare VOLO?\p"
	.string "Potrai librarti con loro\n"
	.string "nel cielo!$"

Route14_Text_MarlonDefeat::
	.string "Abbattuto in fiamme!$"

Route14_Text_MarlonPostBattle::
	.string "I POKéMON uccello sono il mio amore.\n"
	.string "Non voglio allevare altro.$"

Route14_Text_DonaldIntro::
	.string "Hai sentito la leggenda dei\n"
	.string "miraggi alati?$"

Route14_Text_DonaldDefeat::
	.string "Perché?\n"
	.string "Perché ho perso?$"

Route14_Text_DonaldPostBattle::
	.string "Beh, i miraggi alati sono i\n"
	.string "POKéMON uccello leggendari.\p"
	.string "Sono tre: ARTICUNO,\n"
	.string "ZAPDOS e MOLTRES.$"

Route14_Text_BennyIntro::
	.string "Non mi va, ma va bene.\n"
	.string "Andiamo!$"

Route14_Text_BennyDefeat::
	.string "Lo sapevo!$"

Route14_Text_BennyPostBattle::
	.string "Vincere, perdere… È insignificante\n"
	.string "sotto questo cielo immenso.$"

Route14_Text_LukasIntro::
	.string "Dai, dai.\n"
	.string "Andiamo, andiamo, andiamo!$"

Route14_Text_LukasDefeat::
	.string "Argh!\n"
	.string "Ho perso! Sparisci!$"

Route14_Text_LukasPostBattle::
	.string "Cosa, cosa, cosa?\n"
	.string "Cosa vuoi ancora?$"

Route14_Text_IsaacIntro::
	.string "Devo ammazzare il tempo.\n"
	.string "Zitto e combatti.$"

Route14_Text_IsaacDefeat::
	.string "Come?\n"
	.string "Tu!?$"

Route14_Text_IsaacPostBattle::
	.string "Allevare POKéMON è una palla, sai.$"

Route14_Text_GeraldIntro::
	.string "Veniamo fin qui in bici per gli\n"
	.string "spazi aperti.$"

Route14_Text_GeraldDefeat::
	.string "Che disastro!$"

Route14_Text_GeraldPostBattle::
	.string "Bello che hai reso i tuoi POKéMON\n"
	.string "così forti.\p"
	.string "La forza vince!\n"
	.string "E lo sai!$"

Route14_Text_MalikIntro::
	.string "Una lotta POKéMON?\n"
	.string "Che bello! Si mena!$"

Route14_Text_MalikDefeat::
	.string "Che botta!$"

Route14_Text_MalikPostBattle::
	.string "Sai chi vincerebbe, io e te\n"
	.string "uno contro uno!$"

Route14_Text_RouteSign::
	.string "PERCORSO 14\n"
	.string "Ovest verso FUCSIAPOLI$"

Route14_Text_KiriIntro::
	.string "KIRI: JAN, diamo il massimo,\n"
	.string "davvero il massimo.$"

Route14_Text_KiriDefeat::
	.string "KIRI: Uff…\n"
	.string "Abbiamo perso, vero?$"

Route14_Text_KiriPostBattle::
	.string "KIRI: Abbiamo perso per colpa mia?$"

Route14_Text_KiriNotEnoughMons::
	.string "KIRI: Possiamo combattere se hai\n"
	.string "due POKéMON.$"

Route14_Text_JanIntro::
	.string "JAN: KIRI, si parte!\n"
	.string "Dobbiamo impegnarci!$"

Route14_Text_JanDefeat::
	.string "JAN: Eeeeh!\n"
	.string "Non vale!$"

Route14_Text_JanPostBattle::
	.string "JAN: KIRI, non piangere!\n"
	.string "Ci impegneremo di più la prossima volta.$"

Route14_Text_JanNotEnoughMons::
	.string "JAN: Vuoi combattere?\n"
	.string "Non hai abbastanza POKéMON.$"
