SafariZone_Center_RestHouse_Frlg_MapScripts::
	.byte 0

SafariZone_Center_RestHouse_EventScript_Sara::
	msgbox SafariZone_Center_Text_WhereDidErikGo, MSGBOX_NPC
	end

SafariZone_Center_RestHouse_EventScript_Scientist::
	msgbox SafariZone_Center_Text_CatchingMonsAsGifts, MSGBOX_NPC
	end

SafariZone_Center_Text_WhereDidErikGo::
	.string "SARA: Dove sarà andato il mio ragazzo,\n"
	.string "ERIK?$"

SafariZone_Center_Text_CatchingMonsAsGifts::
	.string "Catturo POKéMON da portare a casa\n"
	.string "come regalo.$"

