@ Flavor text for interacting with various background objects

EventScript_Bookshelf::
	msgbox Text_Bookshelf, MSGBOX_SIGN
	end

EventScript_PokeMartShelf::
	msgbox Text_PokeMartShelf, MSGBOX_SIGN
	end

EventScript_Food::
	msgbox Text_Food, MSGBOX_SIGN
	end

EventScript_VideoGame::
	msgbox Text_VideoGame, MSGBOX_SIGN
	end

EventScript_Computer::
	msgbox Text_Computer, MSGBOX_SIGN
	end

EventScript_ImpressiveMachine::
	msgbox Text_ImpressiveMachine, MSGBOX_SIGN
	end

EventScript_Blueprints::
	msgbox Text_Blueprints, MSGBOX_SIGN
	end

EventScript_Burglary::
	msgbox Text_Burglary, MSGBOX_SIGN
	end

EventScript_PlayerFacingTVScreen::
	msgbox Text_PlayerFacingTVScreen, MSGBOX_SIGN
	end

EventScript_Cabinet::
	msgbox Text_DishesPlatesNeatlyLinedUp, MSGBOX_SIGN
	end

EventScript_Kitchen::
	msgbox Text_Kitchen, MSGBOX_SIGN
	end

EventScript_Dresser::
	msgbox Text_Dresser, MSGBOX_SIGN
	end

EventScript_Snacks::
	msgbox Text_Snacks, MSGBOX_SIGN
	end

EventScript_Painting::
	msgbox Text_Painting, MSGBOX_SIGN
	end

EventScript_PowerPlantMachine::
	msgbox Text_PowerPlantMachine, MSGBOX_SIGN
	end

EventScript_Telephone::
	msgbox Text_Telephone, MSGBOX_SIGN
	end

EventScript_AdvertisingPoster::
	msgbox Text_AdvertisingPoster, MSGBOX_SIGN
	end

EventScript_TastyFood::
	msgbox Text_TastyFood, MSGBOX_SIGN
	end

EventScript_TrashBin::
	msgbox Text_TrashBin, MSGBOX_SIGN
	end

EventScript_Cup::
	msgbox Text_Cup, MSGBOX_SIGN
	end

EventScript_PolishedWindow::
	msgbox Text_PolishedWindow, MSGBOX_SIGN
	end

EventScript_BeautifulSkyWindow::
	msgbox Text_BeautifulSkyWindow, MSGBOX_SIGN
	end

EventScript_BlinkingLights::
	msgbox Text_BlinkingLights, MSGBOX_SIGN
	end

EventScript_NeatlyLinedUpTools::
	msgbox Text_NeatlyLinedUpTools, MSGBOX_SIGN
	end

EventScript_PokemartSign::
	msgbox Text_PokemartSign, MSGBOX_SIGN
	end

EventScript_PokecenterSign::
	msgbox Text_PokecenterSign, MSGBOX_SIGN
	end

EventScript_Indigo_UltimateGoal::
	msgbox Text_Indigo_UltimateGoal, MSGBOX_SIGN
	end

EventScript_Indigo_HighestAuthority::
	msgbox Text_Indigo_HighestAuthority, MSGBOX_SIGN
	end

@ Flavor text for interacting with various background objects

Text_Bookshelf::
	.string "È pieno zeppo di libri\n"
	.string "sui POKéMON.$"

Text_NothingButPokemonBooks::
	.string "ほんだなに　ならんでいるのは\n"
	.string "ポケモンの　ほん　ばかりだ$"

Text_ATownMap::
	.string "UNA MAPPA DELLA CITTÀ.$"

Text_PokeMartShelf::
	.string "Wow!\n"
	.string "Un sacco di roba POKéMON!$"

Text_DishesPlatesNeatlyLinedUp::
	.string "Piatti e stoviglie sono\n"
	.string "ben allineati.$"

Text_Kitchen::
	.string "Che profumo delizioso!\n"
	.string "Qui qualcuno ha cucinato.$"

Text_Dresser::
	.string "È un cassettone ben fatto.\n"
	.string "Ci sta un sacco di roba.$"

Text_Snacks::
	.string "C'è un mucchio di snack qui.$"

Text_PokemartSign::
	.string "Tutto ciò che ti serve!\n"
	.string "MART POKéMON$"

Text_PokecenterSign::
	.string "Cura i tuoi POKéMON!\n"
	.string "CENTRO POKéMON$"

Text_Indigo_UltimateGoal::
	.string "ALTOPIANO INDIGO\p"
	.string "Il traguardo di ogni ALLENATORE!\n"
	.string "SEDE LEGA POKéMON$"

Text_Indigo_HighestAuthority::
	.string "ALTOPIANO INDIGO\p"
	.string "La massima autorità POKéMON!\n"
	.string "SEDE LEGA POKéMON$"

Text_Food::
	.string "Dovrebbe essere pieno di ogni\n"
	.string "cosa buona da mangiare.$"

Text_Blueprints::
	.string "È una specie di progetto.\n"
	.string "Pieno di schemi e scritte.$"

Text_Painting::
	.string "È un bel quadro di un POKéMON.\n"
	.string "Sembra stia bene.$"

Text_PowerPlantMachine::
	.string "Che macchina sarà mai?\n"
	.string "Meglio non toccarla!$"

Text_Telephone::
	.string "È un telefono.\n"
	.string "Meglio non usarlo.$"

Text_Computer::
	.string "Solo parole complicate e\n"
	.string "numeri senza senso…$"

Text_AdvertisingPoster::
	.string "È un poster pubblicitario su\n"
	.string "tanti tipi di prodotti.$"

Text_TastyFood::
	.string "Oh, che buon profumo!\n"
	.string "Fa venire fame allo stomaco!$"

Text_TrashBin::
	.string "Dentro qui…\n"
	.string "……\p"
	.string "Non c'è niente!$"

Text_Cup::
	.string "È una tazza con il segno\n"
	.string "di un POKéMON.$"

Text_PolishedWindow::
	.string "La finestra è molto ben lucidata.$"

Text_BeautifulSkyWindow::
	.string "Fuori dalla finestra…\p"
	.string "Il cielo è di una bellezza\n"
	.string "fantastica.$"

Text_BlinkingLights::
	.string "Luci di vari colori si\n"
	.string "accendono e si spengono.$"

Text_NeatlyLinedUpTools::
	.string "Ogni tipo di attrezzo è\n"
	.string "ben allineato.$"

Text_ImpressiveMachine::
	.string "È una specie di macchina.\n"
	.string "È davvero impressionante.$"

Text_VideoGame::
	.string "È l'ultimo videogioco!\n"
	.string "Sembra proprio divertente!$"

Text_Burglary::
	.string "Ci sono chiari segni di furto\n"
	.string "qui…$"

Text_PlayerFacingTVScreen::
	.string "C'è un POKéMON in TV!\n"
	.string "Sembra si stia divertendo.$"
