ThreeIsland_House4_Frlg_MapScripts::
	.byte 0

ThreeIsland_House4_EventScript_BaldingMan::
	msgbox ThreeIsland_House4_Text_GhostsInBerryForest, MSGBOX_NPC
	end

ThreeIsland_House4_EventScript_LittleBoy::
	msgbox ThreeIsland_House4_Text_PapaKeepsLyingToMe, MSGBOX_NPC
	end

ThreeIsland_House4_Text_GhostsInBerryForest::
	.string "Non andare mai, mai da solo\n"
	.string "nella FORESTA BACCA.\p"
	.string "Perché?\n"
	.string "Ci sono i fantasmi.$"

ThreeIsland_House4_Text_PapaKeepsLyingToMe::
	.string "Papà continua a dirmi bugie e non\n"
	.string "mi lascia uscire a giocare!$"

