PewterCity_Museum_2F_Frlg_MapScripts::
	.byte 0

PewterCity_Museum_2F_EventScript_Man::
	msgbox PewterCity_Museum_1F_Text_WhatsSpecialAboutMoonStone, MSGBOX_NPC
	end

PewterCity_Museum_2F_EventScript_OldMan::
	msgbox PewterCity_Museum_1F_Text_BoughtColorTVForMoonLanding, MSGBOX_NPC
	end

PewterCity_Museum_2F_EventScript_Scientist::
	msgbox PewterCity_Museum_1F_Text_RunningSpaceExhibitThisMonth, MSGBOX_NPC
	end

PewterCity_Museum_2F_EventScript_LittleGirl::
	msgbox PewterCity_Museum_1F_Text_AskedDaddyToCatchPikachu, MSGBOX_NPC
	end

PewterCity_Museum_2F_EventScript_BaldingMan::
	msgbox PewterCity_Museum_1F_Text_PikachuSoonIPromise, MSGBOX_NPC
	end

PewterCity_Museum_2F_EventScript_SpaceShuttle::
	msgbox PewterCity_Museum_1F_Text_SpaceShuttle, MSGBOX_SIGN
	end

PewterCity_Museum_2F_EventScript_MoonStone::
	msgbox PewterCity_Museum_1F_Text_MeteoriteThatFellOnMtMoon, MSGBOX_SIGN
	end

Text_SeismicTossTeach::
	.string "I segreti dello spazio…\n"
	.string "I misteri della terra…\p"
	.string "Ci sono tante cose di cui\n"
	.string "sappiamo così poco.\p"
	.string "Ma questo ci deve spronare a\n"
	.string "studiare, non a gettare la spugna.\p"
	.string "L'unica cosa da gettare…\p"
	.string "Ehm, che ne dici di SEISMIC TOSS?\n"
	.string "Lo insegno a un POKéMON?$"

Text_SeismicTossDeclined::
	.string "Davvero?\n"
	.string "Sono certo che tornerai a cercarla.$"

Text_SeismicTossWhichMon::
	.string "Quale POKéMON vuole imparare\n"
	.string "SEISMIC TOSS?$"

Text_SeismicTossTaught::
	.string "Spero che non getterai la spugna.\n"
	.string "Continua così.$"

PewterCity_Museum_1F_Text_WhatsSpecialAboutMoonStone::
	.string "PIETRA LUNARE, eh?\p"
	.string "Cosa avrà di speciale?\n"
	.string "A me sembra una roccia comune.$"

PewterCity_Museum_1F_Text_BoughtColorTVForMoonLanding::
	.string "20 luglio 1969!\p"
	.string "Quel giorno l'umanità ha messo\n"
	.string "piede sulla Luna.\p"
	.string "Comprai una TV a colori solo per\n"
	.string "poter vedere quel telegiornale.$"

PewterCity_Museum_1F_Text_RunningSpaceExhibitThisMonth::
	.string "Questo mese teniamo una mostra\n"
	.string "spaziale.$"

PewterCity_Museum_1F_Text_AskedDaddyToCatchPikachu::
	.string "Voglio un PIKACHU!\n"
	.string "È così carino!\p"
	.string "Ho chiesto al mio papà di prenderlo!$"

PewterCity_Museum_1F_Text_PikachuSoonIPromise::
	.string "Sì, un PIKACHU presto, te lo prometto!$"

PewterCity_Museum_1F_Text_SpaceShuttle::
	.string "Navetta spaziale$"

PewterCity_Museum_1F_Text_MeteoriteThatFellOnMtMoon::
	.string "Un meteorite caduto sul MONTE LUNA.\n"
	.string "Si pensa sia una PIETRA LUNARE.$"

