SSAnne_2F_Room3_Frlg_MapScripts::
	.byte 0

SSAnne_2F_Room3_EventScript_Gentleman::
	msgbox SSAnne_2F_Room3_Text_SeenMonsFerryPeople, MSGBOX_NPC
	end

SSAnne_2F_Room3_EventScript_OldMan::
	msgbox SSAnne_2F_Room3_Text_SomeTreesCanBeCutDown, MSGBOX_NPC
	end

SSAnne_2F_Room3_Text_SeenMonsFerryPeople::
	.string "Ah, sì, ho visto dei POKéMON\n"
	.string "traghettare gente sull'acqua!$"

SSAnne_2F_Room3_Text_SomeTreesCanBeCutDown::
	.string "I piccoli alberi si abbattono\n"
	.string "con la mossa TAGLIO.\p"
	.string "Ma ricorda bene!\n"
	.string "TAGLIO è una mossa MN.\p"
	.string "Una volta imparata, non si\n"
	.string "dimentica facilmente.$"

