PetalburgCity_House1_MapScripts::
	.byte 0

PetalburgCity_House1_EventScript_Man::
	msgbox PetalburgCity_House1_Text_TravelingIsWonderful, MSGBOX_NPC
	end

PetalburgCity_House1_EventScript_Woman::
	msgbox PetalburgCity_House1_Text_GoOnAdventure, MSGBOX_NPC
	end

PetalburgCity_House1_Text_TravelingIsWonderful:
	.string "Viaggiare è meraviglioso!\p"
	.string "Da giovane ho girato i mari\n"
	.string "e le montagne!$"

PetalburgCity_House1_Text_GoOnAdventure:
	.string "Sigh…\p"
	.string "Vorrei partire per un'avventura\n"
	.string "con qualche POKéMON…\p"
	.string "Strisciare nell'erba umida…\n"
	.string "Scalare montagne rocciose…\p"
	.string "Attraversare i mari in tempesta…\n"
	.string "Vagare in caverne buie…\p"
	.string "E a volte sentire anche un po'\n"
	.string "di nostalgia di casa…\p"
	.string "Viaggiare dev'essere fantastico!$"

