SafariZone_North_RestHouse_Frlg_MapScripts::
	.byte 0

SafariZone_North_RestHouse_EventScript_Fisher::
	msgbox SafariZone_East_Text_PrizeInDeepestPartOfSafariZone, MSGBOX_NPC
	end

SafariZone_North_RestHouse_EventScript_Scientist::
	msgbox SafariZone_East_Text_KeepAnyItemFoundOnSafari, MSGBOX_NPC
	end

SafariZone_North_RestHouse_EventScript_Gentleman::
	msgbox SafariZone_East_Text_MyEeveeEvolvedIntoFlareon, MSGBOX_NPC
	end

SafariZone_East_Text_KeepAnyItemFoundOnSafari::
	.string "Puoi tenere ogni oggetto che trovi\n"
	.string "nella ZONA SAFARI.\p"
	.string "Ma resterai senza tempo se provi\n"
	.string "a prenderli tutti insieme.$"

SafariZone_East_Text_PrizeInDeepestPartOfSafariZone::
	.string "Vai nella parte più profonda della\n"
	.string "ZONA SAFARI. Vinci un premio!$"

SafariZone_East_Text_MyEeveeEvolvedIntoFlareon::
	.string "Il mio EEVEE si è evoluto in FLAREON.\p"
	.string "Ma l'EEVEE di un amico è diventato un\n"
	.string "VAPOREON. Chissà perché?$"

