ViridianCity_Mart_hns_MapScripts::
	.byte 0

ViridianCity_Mart_EventScript_Lass::
	msgbox ViridianMart_Text_Lass, MSGBOX_NPC
	end

ViridianCity_Mart_EventScript_Cooltrainer::
	msgbox ViridianMart_Text_CooltrainerM, MSGBOX_NPC
	end

ViridianMart_Text_Lass:
	.string "Il CAPOPALESTRA qui è davvero forte.$"

ViridianMart_Text_CooltrainerM:
	.string "Sei mai stato a CINNABAR?\p"
	.string "È un'isola molto a sud di qui.$"

