@ Handled by data/scripts/day_care.inc

Route5_PokemonDayCare_Frlg_MapScripts::
	.byte 0

Route5_PokemonDayCare_Text_WantMeToRaiseMon::
	.string "Gestisco il servizio PENSIONE.\p"
	.string "Vuoi che allievi uno dei\n"
	.string "tuoi POKéMON?$"

Route5_PokemonDayCare_Text_ComeAgain::
	.string "Torna presto.$"

Route5_PokemonDayCare_Text_WhichMonShouldIRaise::
	.string "Quale POKéMON devo allenare?$"

Route5_PokemonDayCare_Text_ComeAnytimeYouLike::
	.string "Va bene.\n"
	.string "Torna quando vuoi.$"

Route5_PokemonDayCare_Text_LookAfterMonForAWhile::
	.string "Va bene, mi prenderò cura del tuo\n"
	.string "{STR_VAR_1} per un po'.$"

Route5_PokemonDayCare_Text_ComeSeeMeInAWhile::
	.string "Torna a trovarmi fra un po'.$"

Route5_PokemonDayCare_Text_MonNeedsToSpendMoreTime::
	.string "Sei già tornato?\p"
	.string "Il tuo {STR_VAR_1} deve stare\n"
	.string "ancora un po' con me.$"

Route5_PokemonDayCare_Text_OweMeXForMonsReturn::
	.string "Mi devi ¥{STR_VAR_2} per il ritorno\n"
	.string "di questo POKéMON.$"

Route5_PokemonDayCare_Text_ThankYouHeresMon::
	.string "Grazie!\n"
	.string "Ecco il tuo POKéMON.$"

Route5_PokemonDayCare_Text_PlayerGotMonBack::
	.string "{PLAYER} ha ripreso {STR_VAR_1}\n"
	.string "dall'UOMO DELLA PENSIONE.$"

Route5_PokemonDayCare_Text_OnlyHaveOneMonWithYou::
	.string "Oh? Hai un solo POKéMON\n"
	.string "con te.$"

Route5_PokemonDayCare_Text_WhatWillYouBattleWith::
	.string "Se mi lasci quel POKéMON,\n"
	.string "con cosa combatterai?$"

Route5_PokemonDayCare_Text_MonHasGrownByXLevels::
	.string "Il tuo {STR_VAR_1} è cresciuto molto.\n"
	.string "Sì, direi parecchio.\p"
	.string "Fammi vedere…\n"
	.string "Di livello è cresciuto di {STR_VAR_2}.\p"
	.string "Non sono bravo?$"

Route5_PokemonDayCare_Text_YouveGotNoRoomForIt::
	.string "Non puoi riprendere questo POKéMON\n"
	.string "se non hai posto per lui.$"

Route5_PokemonDayCare_Text_DontHaveEnoughMoney::
	.string "Non hai abbastanza soldi.$"

Route5_PokemonDayCare_Text_WantMeToTakeALookAtYours::
	.string "きみの\n"
	.string "みてみるかね？$"

Route5_PokemonDayCare_Text_CantAcceptMonWithHM::
	.string "わるいけど　ひでんのわざを　もった\n"
	.string "ポケモンは　あずかれないなぁ$"
