Route3_Frlg_MapScripts::
	.byte 0

Route3_EventScript_Youngster::
	msgbox Route3_Text_TunnelFromCeruleanTiring, MSGBOX_NPC
	end

Route3_EventScript_RouteSign::
	msgbox Route3_Text_RouteSign, MSGBOX_SIGN
	end

Route3_Text_TunnelFromCeruleanTiring::
	.string "Fiu… Meglio riposare…\n"
	.string "Uff…\p"
	.string "Quel tunnel da CELESTOPOLI ti\n"
	.string "sfianca!$"

Route3_Text_ColtonIntro::
	.string "Ehi!\n"
	.string "Ti ho visto nel BOSCO SMERALDO!$"

Route3_Text_ColtonDefeat::
	.string "Mi hai battuto di nuovo!$"

Route3_Text_ColtonPostBattle::
	.string "Ci sono altri tipi di POKéMON\n"
	.string "oltre a quelli delle foreste.$"

Route3_Text_BenIntro::
	.string "Ciao!\n"
	.string "Mi piacciono i pantaloncini!\p"
	.string "Sono comodi da morire e\n"
	.string "facili da mettere!$"

Route3_Text_BenDefeat::
	.string "Non ci credo!$"

Route3_Text_BenPostBattle::
	.string "Usi il PC di un CENTRO POKéMON\n"
	.string "per conservare i POKéMON?\p"
	.string "Ogni BOX può contenere fino a\n"
	.string "30 POKéMON.$"

Route3_Text_JaniceIntro::
	.string "Scusi!\n"
	.string "Mi hai guardata, vero?$"

Route3_Text_JaniceDefeat::
	.string "Che cattivo!$"

Route3_Text_JanicePostBattle::
	.string "Non fissare se non vuoi\n"
	.string "lottare!$"

Route3_Text_GregIntro::
	.string "Sei un ALLENATORE?\n"
	.string "Lottiamo subito!$"

Route3_Text_GregDefeat::
	.string "Con dei POKéMON nuovi avrei\n"
	.string "vinto!$"

Route3_Text_GregPostBattle::
	.string "Se un BOX POKéMON del PC si\n"
	.string "riempie, passa a un altro BOX.$"

Route3_Text_SallyIntro::
	.string "Quello sguardo che mi hai dato…\n"
	.string "È così intrigante!$"

Route3_Text_SallyDefeat::
	.string "Sii gentile!$"

Route3_Text_SallyPostBattle::
	.string "Puoi evitare le lotte non\n"
	.string "facendoti vedere dagli ALLENATORI.$"

Route3_Text_CalvinIntro::
	.string "Ehi! Non porti i pantaloncini!\n"
	.string "Che cosa ti prende?$"

Route3_Text_CalvinDefeat::
	.string "Perso!\n"
	.string "Perso! Perso!$"

Route3_Text_CalvinPostBattle::
	.string "Porto sempre i pantaloncini, anche\n"
	.string "d'inverno. È la mia regola.$"

Route3_Text_JamesIntro::
	.string "Ti sfido con i POKéMON\n"
	.string "che ho appena preso.$"

Route3_Text_JamesDefeat::
	.string "Fatto e finito!$"

Route3_Text_JamesPostBattle::
	.string "I POKéMON allenati sono più forti\n"
	.string "di quelli selvatici.$"

Route3_Text_RobinIntro::
	.string "Ih!\n"
	.string "Mi hai toccata?$"

Route3_Text_RobinDefeat::
	.string "Tutto qui?$"

Route3_Text_RobinPostBattle::
	.string "La PERCORSO 4 è ai piedi del\n"
	.string "MONTE LUNA.$"

Route3_Text_RouteSign::
	.string "PERCORSO 3\n"
	.string "MONTE LUNA AVANTI$"

