OneIsland_TreasureBeach_Frlg_MapScripts::
	.byte 0

OneIsland_TreasureBeach_EventScript_Boy::
	msgbox OneIsland_TreasureBeach_Text_GoodThingsWashUpOnBeach, MSGBOX_NPC
	end

OneIsland_TreasureBeach_Text_AmaraIntro::
	.string "Distesa, cullata dalle onde…\n"
	.string "È squisito.$"

OneIsland_TreasureBeach_Text_AmaraDefeat::
	.string "Ho perso…\n"
	.string "Che brutta sensazione.$"

OneIsland_TreasureBeach_Text_AmaraPostBattle::
	.string "Da queste parti il mare è\n"
	.string "piacevolmente caldo.$"

OneIsland_TreasureBeach_Text_GoodThingsWashUpOnBeach::
	.string "La corrente dell'oceano porta cose\n"
	.string "buone su questa spiaggia.\p"
	.string "Ecco perché vengo spesso qui a\n"
	.string "cercare sulla riva.$"

