Route15_Frlg_MapScripts::
	.byte 0

Route15_EventScript_RouteSign::
	msgbox Route15_Text_RouteSign, MSGBOX_SIGN
	end

Route15_Text_KindraIntro::
	.string "Ho appena scambiato dei POKéMON.\n"
	.string "Posso provarli su di te?$"

Route15_Text_KindraDefeat::
	.string "Non basta!$"

Route15_Text_KindraPostBattle::
	.string "Non puoi cambiare il soprannome\n"
	.string "dei POKéMON ottenuti in scambio.\p"
	.string "Solo l'ALLENATORE originale può\n"
	.string "farlo cambiare.$"

Route15_Text_BeckyIntro::
	.string "Sembri gentile, credo di\n"
	.string "poterti battere.\p"
	.string "Ci provo!$"

Route15_Text_BeckyDefeat::
	.string "No, sbagliato!$"

Route15_Text_BeckyPostBattle::
	.string "Ho paura dei MOTOCICLISTI. Sembrano\n"
	.string "così brutti e cattivi!$"

Route15_Text_EdwinIntro::
	.string "Quando fischio, posso evocare\n"
	.string "POKéMON uccello.$"

Route15_Text_EdwinDefeat::
	.string "Ow!\n"
	.string "Che tragedia!$"

Route15_Text_EdwinPostBattle::
	.string "Forse non sono portato per le lotte.\n"
	.string "Non è il mio tipo, credo.$"

Route15_Text_ChesterIntro::
	.string "Hmm? I miei uccelli tremano!\n"
	.string "Sei forte, vero?$"

Route15_Text_ChesterDefeat::
	.string "Proprio come pensavo!$"

Route15_Text_ChesterPostBattle::
	.string "È ovvio, dovresti saperlo,\n"
	.string "ma…\p"
	.string "Mosse come TERREMOTO e ABISSO\n"
	.string "non hanno effetto sui POKéMON uccello.$"

Route15_Text_GraceIntro::
	.string "Oh, sei un tesoro!\n"
	.string "Proprio come un POKéMON adorabile!$"

Route15_Text_GraceDefeat::
	.string "Eri così carino, anche!$"

Route15_Text_GracePostBattle::
	.string "Ti perdono.\n"
	.string "So resistere.\l"
	.string "Ormai sono grande.$"

Route15_Text_OliviaIntro::
	.string "Alleno POKéMON per difendermi\n"
	.string "perché vivo da sola.$"

Route15_Text_OliviaDefeat::
	.string "Per me i POKéMON non sono\n"
	.string "questione di vincere o perdere.$"

Route15_Text_OliviaPostBattle::
	.string "Adoro quando i miei POKéMON\n"
	.string "mi accolgono quando torno.\p"
	.string "Mi rassicura molto.$"

Route15_Text_ErnestIntro::
	.string "Ehi, ragazzino! Forza!\n"
	.string "Le ho appena prese da un perdente!$"

Route15_Text_ErnestDefeat::
	.string "Perché no?$"

Route15_Text_ErnestPostBattle::
	.string "La vita è breve.\n"
	.string "È bello fare il fuorilegge.\l"
	.string "VIVA IL TEAM ROCKET!$"

Route15_Text_AlexIntro::
	.string "Sborsa tutti i tuoi soldi quando\n"
	.string "perdi contro di me, ragazzino!$"

Route15_Text_AlexDefeat::
	.string "Non può essere vero!$"

Route15_Text_AlexPostBattle::
	.string "Scherzavo sui soldi.\n"
	.string "Non prendermi sul serio.$"

Route15_Text_CeliaIntro::
	.string "Cosa c'è di bello in giro?\n"
	.string "Scambiare POKéMON!$"

Route15_Text_CeliaDefeat::
	.string "Ho detto scambio!$"

Route15_Text_CeliaPostBattle::
	.string "Scambio POKéMON con i miei amici\n"
	.string "in continuazione.$"

Route15_Text_YazminIntro::
	.string "Vuoi giocare coi miei POKéMON?$"

Route15_Text_YazminDefeat::
	.string "Sono stata troppo impaziente!$"

Route15_Text_YazminPostBattle::
	.string "Andrò ad allenarmi con gente più debole.$"

Route15_Text_RouteSign::
	.string "PERCORSO 15\n"
	.string "Ovest verso FUCSIAPOLI$"

Route15_Text_MyaIntro::
	.string "MYA: Sei perfetto.\n"
	.string "Mi aiuti ad allenare mio fratello?$"

Route15_Text_MyaDefeat::
	.string "MYA: RON, devi concentrarti!\n"
	.string "Pensa a quello che fai!$"

Route15_Text_MyaPostBattle::
	.string "MYA: Ok, alziamo il tiro.\n"
	.string "Aggiungo un esercizio al programma!$"

Route15_Text_MyaNotEnoughMons::
	.string "MYA: Vuoi sfidarci?\n"
	.string "Ti servono due POKéMON, però.$"

Route15_Text_RonIntro::
	.string "RON: Mia sorella diventa\n"
	.string "spaventosa quando perdiamo.$"

Route15_Text_RonDefeat::
	.string "RON: Oh, no, no…\n"
	.string "Sorella, mi dispiace!$"

Route15_Text_RonPostBattle::
	.string "RON: Oh, che barba…\n"
	.string "Vorrei una sorella più gentile…$"

Route15_Text_RonNotEnoughMons::
	.string "RON: Volevi lottare con me\n"
	.string "e mia sorella?\p"
	.string "Ti servono due POKéMON, allora.$"
