CeruleanCity_Mart_hns_MapScripts::
	.byte 0

CeruleanCity_Mart_EventScript_Juggler::
	msgbox CeruleanMart_Text_CooltrainerM, MSGBOX_NPC
	end

CeruleanCity_Mart_EventScript_CooltrainerF::
	msgbox CeruleanMart_Text_CooltrainerF, MSGBOX_NPC
	end

CeruleanMart_Text_CooltrainerM:
	.string "Incontrerai molti allenatori\n"
	.string "sulla via del CAPO CELESTOPOLI.\p"
	.string "Vogliono vedere come se la\n"
	.string "cavano con altri allenatori.$"

CeruleanMart_Text_CooltrainerF:
	.string "MISTY è quasi l'unica in\n"
	.string "città a battere gli allenatori al\l"
	.string "CAPO CELESTOPOLI.$"
