Route10_Frlg_MapScripts::
	.byte 0

Route10_EventScript_Unused::
	end

Route10_EventScript_NorthRockTunnelSign::
	msgbox Route10_Text_RockTunnelDetourToLavender, MSGBOX_SIGN
	end

Route10_EventScript_SouthRockTunnelSign::
	msgbox Route10_Text_RockTunnel, MSGBOX_SIGN
	end

Route10_EventScript_PowerPlantSign::
	msgbox Route10_Text_PowerPlant, MSGBOX_SIGN
	end

Route10_Text_MarkIntro::
	.string "Wow, sei arrivato fin quassù?\n"
	.string "Forse sei un POKéMANIAC anche tu?\l"
	.string "Vuoi vedere la mia collezione?$"

Route10_Text_MarkDefeat::
	.string "Uhm.\n"
	.string "Non sono arrabbiato!$"

Route10_Text_MarkPostBattle::
	.string "A casa ho POKéMON più rari!$"

Route10_Text_ClarkIntro::
	.string "Ah-ahahah-ah-ah!$"

Route10_Text_ClarkDefeat::
	.string "Ah-ahah!\n"
	.string "Non sto ridendo!\l"
	.string "Ah-hetciù! Ahah-ah-ciù!$"

Route10_Text_ClarkPostBattle::
	.string "Ahah-ah-ciù!\n"
	.string "Ah-ciù!\l"
	.string "Sniff! Tira su!$"

Route10_Text_HermanIntro::
	.string "Ciao, piccolo!\n"
	.string "Vuoi vedere i miei POKéMON?$"

Route10_Text_HermanDefeat::
	.string "Oh, no!\n"
	.string "I miei POKéMON!$"

Route10_Text_HermanPostBattle::
	.string "Non mi piaci.\n"
	.string "Non mi piace nessuno più bravo di me!$"

Route10_Text_HeidiIntro::
	.string "Sono stata in una PALESTRA POKéMON\n"
	.string "un paio di volte.\p"
	.string "…Ma perdo sempre.$"

Route10_Text_HeidiDefeat::
	.string "Oooh!\n"
	.string "Dopo tutto il mio allenamento!$"

Route10_Text_HeidiPostBattle::
	.string "Ho notato alcuni POKéMANIACI\n"
	.string "gironzolare qui intorno.\p"
	.string "Riuscite a immaginarlo? Loro?\n"
	.string "Quassù in montagna?$"

Route10_Text_TrentIntro::
	.string "Ah!\n"
	.string "L'aria di montagna è deliziosa!$"

Route10_Text_TrentDefeat::
	.string "Mi sono schiarito le idee!$"

Route10_Text_TrentPostBattle::
	.string "Mi sento gonfio di aria di montagna!$"

Route10_Text_CarolIntro::
	.string "Mi sento un po' debole.\n"
	.string "Non cammino da un po'.$"

Route10_Text_CarolDefeat::
	.string "Sono troppo stanca.\n"
	.string "Non ero in forma.$"

Route10_Text_CarolPostBattle::
	.string "I POKéMON qui in montagna\n"
	.string "sono così paffuti…\p"
	.string "Vorrei che esistessero POKéMON rosa\n"
	.string "con un motivo floreale!$"

Route10_Text_RockTunnelDetourToLavender::
	.string "GALLERIA ROCCIOSA\n"
	.string "Deviazione per LAVANDONIA$"

Route10_Text_RockTunnel::
	.string "GALLERIA ROCCIOSA$"

Route10_Text_PowerPlant::
	.string "CENTRALE ELETTRICA$"

