LavenderTown_Mart_hns_MapScripts::
	.byte 0

LavenderTown_Mart_EventScript_Pokefan::
	msgbox LavenderMart_Text_PokefanM, MSGBOX_NPC
	end

LavenderTown_Mart_EventScript_Rocker::
	msgbox LavenderMart_Text_Rocker, MSGBOX_NPC
	end

LavenderMart_Text_PokefanM:
	.string "Il REPELLENTE è indispensabile\n"
	.string "per esplorare una grotta.\p"
	.string "Anche se mi piace esplorare,\n"
	.string "non le ho ancora visitate\l"
	.string "tutte.$"

LavenderMart_Text_Rocker:
	.string "Ho sentito di un artigiano che\n"
	.string "crea BALL personalizzate a\l"
	.string "FIORVESCOPOLI, a JOHTO.\p"
	.string "Ne vorrei un po'.$"
