FuchsiaCity_SafariZone_Office_Frlg_MapScripts::
	.byte 0

FuchsiaCity_SafariZone_Office_EventScript_Worker1::
	msgbox FuchsiaCity_SafariZone_Office_Text_NicknamedWardenSlowpoke, MSGBOX_NPC
	end

FuchsiaCity_SafariZone_Office_EventScript_Worker2::
	msgbox FuchsiaCity_SafariZone_Office_Text_WardenIsVeryKnowledgeable, MSGBOX_NPC
	end

FuchsiaCity_SafariZone_Office_EventScript_Worker3::
	msgbox FuchsiaCity_SafariZone_Office_Text_CouldntUnderstandWarden, MSGBOX_NPC
	end

FuchsiaCity_SafariZone_Office_EventScript_Worker4::
	msgbox FuchsiaCity_SafariZone_Office_Text_PrizeInSafariZone, MSGBOX_NPC
	end

FuchsiaCity_SafariZone_Office_Text_NicknamedWardenSlowpoke::
	.string "Per noi il GUARDIANO è\n"
	.string "“SLOWPOKE”\p"
	.string "Sai, ha quell'aria assente\n"
	.string "da SLOWPOKE.$"

FuchsiaCity_SafariZone_Office_Text_WardenIsVeryKnowledgeable::
	.string "Il GUARDIANO SLOWPOKE\n"
	.string "conosce bene i POKéMON.\p"
	.string "Ha persino fossili di POKéMON\n"
	.string "estinti.$"

FuchsiaCity_SafariZone_Office_Text_CouldntUnderstandWarden::
	.string "È passato il GUARDIANO\n"
	.string "SLOWPOKE, ma non capivo\p"
	.string "nulla. Ha problemi di linguaggio!$"

FuchsiaCity_SafariZone_Office_Text_PrizeInSafariZone::
	.string "Il GUARDIANO SLOWPOKE ha\n"
	.string "una promozione in corso.\p"
	.string "Raggiungi l'angolo più lontano\n"
	.string "della ZONA SAFARI.\p"
	.string "Se ci riesci, vinci un premio\n"
	.string "molto comodo!$"

