SixIsland_House_Frlg_MapScripts::
	.byte 0

SixIsland_House_EventScript_OldMan::
	msgbox SixIsland_House_Text_GoodPlaceForNatureAndHistory, MSGBOX_NPC
	end

SixIsland_House_Text_GoodPlaceForNatureAndHistory::
	.string "Per i giovani non c'è niente\n"
	.string "di emozionante su quest'isola.\p"
	.string "Ma è un bel posto per natura\n"
	.string "e storia.\p"
	.string "Rilassati e goditi il soggiorno.$"

