Route13_Frlg_MapScripts::
	.byte 0

Route13_EventScript_TrainerTips1::
	msgbox Route13_Text_LookToLeftOfThatPost, MSGBOX_SIGN
	end

Route13_EventScript_TrainerTips2::
	msgbox Route13_Text_SelectToSwitchItems, MSGBOX_SIGN
	end

Route13_EventScript_RouteSign::
	msgbox Route13_Text_RouteSign, MSGBOX_SIGN
	end

Route13_Text_SebastianIntro::
	.string "I miei POKéMON uccello vogliono\n"
	.string "lottare con te!$"

Route13_Text_SebastianDefeat::
	.string "La combo dei miei PIDGEY e PIDGEOTTO\n"
	.string "ha perso?$"

Route13_Text_SebastianPostBattle::
	.string "I miei POKéMON sembrano felici\n"
	.string "anche se hanno perso.$"

Route13_Text_SusieIntro::
	.string "Dicono che sono brava per la mia età.$"

Route13_Text_SusieDefeat::
	.string "Ohh!\n"
	.string "Ho perso!$"

Route13_Text_SusiePostBattle::
	.string "Voglio diventare una brava ALLENATRICE.\n"
	.string "Mi allenerò sodo, vedrai.$"

Route13_Text_ValerieIntro::
	.string "Wow!\n"
	.string "Le tue MEDAGLIE sono troppo belle!$"

Route13_Text_ValerieDefeat::
	.string "Non basta!$"

Route13_Text_ValeriePostBattle::
	.string "Quelle MEDAGLIE le hai prese dai\n"
	.string "CAPOPALESTRA. Lo so!$"

Route13_Text_GwenIntro::
	.string "I miei graziosi POKéMON vogliono\n"
	.string "conoscerti.$"

Route13_Text_GwenDefeat::
	.string "Bravo!\n"
	.string "Hai vinto alla grande!$"

Route13_Text_GwenPostBattle::
	.string "Devi far lottare i POKéMON\n"
	.string "per renderli più forti.$"

Route13_Text_AlmaIntro::
	.string "Trovai del CARBURANTE in una grotta\n"
	.string "mentre esploravo.$"

Route13_Text_AlmaDefeat::
	.string "Oh, che peccato!\n"
	.string "Ho sbagliato tutto!$"

Route13_Text_AlmaPostBattle::
	.string "Il CARBURANTE ha aumentato la VELOCITÀ\n"
	.string "dei miei POKéMON.$"

Route13_Text_PerryIntro::
	.string "Non ho intenzione di perdere.\n"
	.string "Non con il vento a mio favore!$"

Route13_Text_PerryDefeat::
	.string "Il vento è girato!$"

Route13_Text_PerryPostBattle::
	.string "Sono a pezzi.\n"
	.string "Me ne torno a casa in VOLO.$"

Route13_Text_LolaIntro::
	.string "Certo, gioco con te, tesoro.$"

Route13_Text_LolaDefeat::
	.string "Oh!\n"
	.string "Piccola bestiola!$"

Route13_Text_LolaPostBattle::
	.string "Chissà chi è più forte, i POKéMON\n"
	.string "maschi o le femmine?$"

Route13_Text_SheilaIntro::
	.string "Vuoi lottare contro qualche\n"
	.string "POKéMON con me?$"

Route13_Text_SheilaDefeat::
	.string "Già finita?$"

Route13_Text_SheilaPostBattle::
	.string "In realtà non so niente\n"
	.string "di POKéMON.\p"
	.string "Quelli che uso… li ho scelti\n"
	.string "per il loro aspetto!$"

Route13_Text_JaredIntro::
	.string "Che cosa guardi?$"

Route13_Text_JaredDefeat::
	.string "Accidenti!\n"
	.string "Ingranaggi a secco!$"

Route13_Text_JaredPostBattle::
	.string "Sparisci!$"

Route13_Text_RobertIntro::
	.string "Vado sempre con POKéMON uccello.\n"
	.string "Mi sono dedicato a loro.$"

Route13_Text_RobertDefeat::
	.string "Senza energia!$"

Route13_Text_RobertPostBattle::
	.string "Vorrei poter volare come PIDGEY e\n"
	.string "PIDGEOTTO…$"

Route13_Text_LookToLeftOfThatPost::
	.string "CONSIGLI PER ALLENATORI\p"
	.string "Guarda, guarda!\n"
	.string "Guarda a sinistra di quel palo!$"

Route13_Text_SelectToSwitchItems::
	.string "CONSIGLI PER ALLENATORI\p"
	.string "Usa SELECT per cambiare oggetto\n"
	.string "nella finestra OGGETTI.$"

Route13_Text_RouteSign::
	.string "PERCORSO 13\n"
	.string "A nord verso SILENCE BRIDGE$"

