#include "global.h"
#include "strings.h"
#include "battle_pyramid_bag.h"
#include "item_menu.h"

ALIGNED(4)
const u8 gText_ExpandedPlaceholder_Empty[] = _("");
const u8 gText_ExpandedPlaceholder_Kun[] = _("");
const u8 gText_ExpandedPlaceholder_Chan[] = _("");
const u8 gText_ExpandedPlaceholder_Sapphire[] = _("ZAFFIRO");
const u8 gText_ExpandedPlaceholder_Ruby[] = _("RUBINO");
const u8 gText_ExpandedPlaceholder_Emerald[] = _("SMERALDO");
const u8 gText_ExpandedPlaceholder_Aqua[] = _("AQUA");
const u8 gText_ExpandedPlaceholder_Magma[] = _("MAGMA");
const u8 gText_ExpandedPlaceholder_Archie[] = _("ARCHIE");
const u8 gText_ExpandedPlaceholder_Maxie[] = _("MAXIE");
const u8 gText_ExpandedPlaceholder_Kyogre[] = _("KYOGRE");
const u8 gText_ExpandedPlaceholder_Groudon[] = _("GROUDON");
const u8 gText_ExpandedPlaceholder_Brendan[] = _("BRENDAN");
const u8 gText_ExpandedPlaceholder_May[] = _("MAY");
const u8 gText_ExpandedPlaceholder_Red[] = _("ROSSO");
const u8 gText_ExpandedPlaceholder_Green[] = _("VERDE");
const u8 gText_ExpandedPlaceholder_Silver[] = _("ARGENTO");
const u8 gText_EggNickname[POKEMON_NAME_LENGTH + 1] = _("UOVO");
const u8 gText_Pokemon[POKEMON_NAME_LENGTH + 1] = _("POKéMON");
const u8 gText_Player[] = _("GIOCATORE"); // Unused
const u8 gText_Pokedex[] = _("POKéDEX"); // Unused
const u8 gText_Time[] = _("ORA");
const u8 gText_Badges[] = _("MEDAGLIE"); // Unused
const u8 gText_AButton[] = _("Pulsante A"); // Unused
const u8 gText_BButton[] = _("Pulsante B"); // Unused
const u8 gText_RButton[] = _("Tasto R"); // Unused
const u8 gText_LButton[] = _("Tasto L"); // Unused
const u8 gText_Start[] = _("INIZIO"); // Unused
const u8 gText_Select[] = _("SCEGLI"); // Unused
const u8 gText_ControlPad[] = _("+ Pulsantiera"); // Unused
const u8 gText_LButtonRButton[] = _("Tasto L  Tasto R"); // Unused
const u8 gText_Controls[] = _("COMANDI"); // Unused
ALIGNED(4) const u8 gText_PickOk[] = _("{DPAD_UPDOWN}SCEGLI {A_BUTTON}OK"); // Unused
ALIGNED(4) const u8 gText_Next[] = _("{A_BUTTON}AVANTI");
ALIGNED(4) const u8 gText_NextBack[] = _("{A_BUTTON}AVANTI {B_BUTTON}INDIETRO");
ALIGNED(4) const u8 gText_PickNextCancel[] = _("{DPAD_UPDOWN}SCEGLI {A_BUTTON}AVANTI {B_BUTTON}ANNULLA");
ALIGNED(4) const u8 gText_PickCancel[] = _("{DPAD_UPDOWN}SCEGLI {A_BUTTON}{B_BUTTON}ANNULLA");
ALIGNED(4) const u8 gText_AButtonExit[] = _("{A_BUTTON}ESCI");
const u8 gText_Boy[] = _("UOMO");
const u8 gText_Girl[] = _("DONNA");
const u8 gText_ThisIsAPokemon[] = _("Ecco un “POKéMON.”{PAUSE 96}\p");
const u8 gText_5MarksPokemon[] = _("????? POKéMON");
const u8 gText_UnkHeight[] = _("{CLEAR_TO 0x0C}??'??”");
const u8 gText_UnkHeightMetric[] = _("???.? m");
const u8 gText_UnkWeight[] = _("????.? lbs.");
const u8 gText_UnkWeightMetric[] = _("??.? kg.");
const u8 gText_EmptyPkmnCategory[] = _("                       POKéMON"); // Unused
const u8 gText_EmptyHeight[] = _("{CLEAR_TO 0x0C}    '    ”"); // Unused
const u8 gText_EmptyWeight[] = _("        .   lbs."); // Unused
const u8 gText_EmptyPokedexInfo1[] = _(""); // Unused
const u8 gText_CryOf[] = _("VERSO DI");
const u8 gText_EmptyPokedexInfo2[] = _(""); // Unused
const u8 gText_SizeComparedTo[] = _("IN CONFRONTO A ");
const u8 gText_PokedexRegistration[] = _("Registrazione al POKéDEX completata.");
const u8 gText_HTHeight[] = _("AL");
const u8 gText_WTWeight[] = _("PS");
const u8 gText_SearchingPleaseWait[] = _("Ricerca…\nAttendi.");
const u8 gText_SearchCompleted[] = _("Ricerca completata.");
const u8 gText_NoMatchingPkmnWereFound[] = _("Nessun POKéMON trovato.");
const u8 gText_SearchForPkmnBasedOnParameters[] = _("Cerca i POKéMON in base ai\nparametri scelti.");
const u8 gText_SwitchPokedexListings[] = _("Cambia l'elenco del POKéDEX.");
const u8 gText_ReturnToPokedex[] = _("Torna al POKéDEX.");
const u8 gText_SelectPokedexMode[] = _("Scegli la modalità POKéDEX.");
const u8 gText_SelectPokedexListingMode[] = _("Scegli la modalità elenco POKéDEX.");
const u8 gText_ListByFirstLetter[] = _("Elenca per prima lettera del nome.\nSolo POKéMON visti.");
const u8 gText_ListByBodyColor[] = _("Elenca per colore del corpo.\nSolo POKéMON visti.");
const u8 gText_ListByType[] = _("Per tipo.\nSolo POKéMON tuoi.");
const u8 gText_ExecuteSearchSwitch[] = _("Cerca/cambia.");
#if IS_HNS
const u8 gText_DexHoennTitle[] = _("DEX JOHTO");
#else
const u8 gText_DexHoennTitle[] = _("DEX HOENN");
#endif
const u8 gText_DexNatTitle[] = _("POKéDEX NAZ");
const u8 gText_DexSortNumericalTitle[] = _("MODO NUMERICO");
const u8 gText_DexSortAtoZTitle[] = _("MODALITÀ A-Z");
const u8 gText_DexSortHeaviestTitle[] = _("MODALITÀ PESO");
const u8 gText_DexSortLightestTitle[] = _("MODALITÀ LEGGERO");
const u8 gText_DexSortTallestTitle[] = _("MODALITÀ ALTEZZA");
const u8 gText_DexSortSmallestTitle[] = _("MODALITÀ MINIMA");
const u8 gText_DexSearchAlphaABC[] = _("ABC");
const u8 gText_DexSearchAlphaDEF[] = _("DIF");
const u8 gText_DexSearchAlphaGHI[] = _("GHI");
const u8 gText_DexSearchAlphaJKL[] = _("JKL");
const u8 gText_DexSearchAlphaMNO[] = _("MNO");
const u8 gText_DexSearchAlphaPQR[] = _("PQR");
const u8 gText_DexSearchAlphaSTU[] = _("STU");
const u8 gText_DexSearchAlphaVWX[] = _("VWX");
const u8 gText_DexSearchAlphaYZ[] = _("YZ");
const u8 gText_DexSearchColorRed[] = _("ROSSO");
const u8 gText_DexSearchColorBlue[] = _("BLU");
const u8 gText_DexSearchColorYellow[] = _("GIALLO");
const u8 gText_DexSearchColorGreen[] = _("VERDE");
const u8 gText_DexSearchColorBlack[] = _("NERO");
const u8 gText_DexSearchColorBrown[] = _("MARRONE");
const u8 gText_DexSearchColorPurple[] = _("VIOLA");
const u8 gText_DexSearchColorGray[] = _("GRIGIO");
const u8 gText_DexSearchColorWhite[] = _("BIANCO");
const u8 gText_DexSearchColorPink[] = _("ROSA");
#if IS_HNS
const u8 gText_DexHoennDescription[] = _("POKéDEX di JOHTO");
#else
const u8 gText_DexHoennDescription[] = _("POKéDEX di HOENN");
#endif
const u8 gText_DexNatDescription[] = _("POKéDEX nazionale");
const u8 gText_DexSortNumericalDescription[] = _("I POKéMON sono elencati secondo il\nnumero.");
const u8 gText_DexSortAtoZDescription[] = _("I POKéMON visti e catturati sono in\nordine alfabetico.");
const u8 gText_DexSortHeaviestDescription[] = _("I POKéMON catturati sono elencati dal\npiù pesante al più leggero.");
const u8 gText_DexSortLightestDescription[] = _("I POKéMON catturati sono elencati dal\npiù leggero al più pesante.");
const u8 gText_DexSortTallestDescription[] = _("I POKéMON catturati sono elencati dal\npiù alto al più basso.");
const u8 gText_DexSortSmallestDescription[] = _("I POKéMON posseduti sono in ordine\ndal più basso al più alto.");
const u8 gText_DexEmptyString[] = _("");
const u8 gText_DexSearchDontSpecify[] = _("NON SPECIFICARE.");
const u8 gText_DexSearchTypeNone[] = _("NESSUNO");
const u8 gText_SelectorArrow[] = _("▶");
const u8 gText_EmptySpace[] = _(" "); // Unused
const u8 gText_WelcomeToHOF[] = _("Benvenuto nella HALL OF FAME!");
const u8 gText_HOFDexRating[] = _("POKéMON visti: {STR_VAR_1}!\nPOKéMON catturati: {STR_VAR_2}!\pValutazione POKéDEX del PROF. BIRCH!\pPROF. BIRCH: Vediamo…\p");
const u8 gText_HOFDexSaving[] = _("SALVATAGGIO…\nNON SPEGNERE LA CONSOLE.");
const u8 gText_HOFCorrupted[] = _("I dati della HALL OF FAME sono corrotti.");
const u8 gText_HOFNumber[] = _("HALL OF FAME N. {STR_VAR_1}");
const u8 gText_LeagueChamp[] = _("CAMPIONE DELLA LEGA!\nCONGRATULAZIONI!");
const u8 gText_Number[] = _("N. ");
const u8 gText_Level[] = _("Lv. ");
const u8 gText_IdNumberSlash[] = _("ID No. /"); // Unused
const u8 gText_Name[] = _("NOME");
const u8 gText_IDNumber[] = _("ID No.");
const u8 gText_BirchInTrouble[] = _("Il PROF. BIRCH è nei guai!\nLibera un POKéMON e salvalo!");
const u8 gText_ConfirmStarterChoice[] = _("Scegli questo POKéMON?");
const u8 gText_Pokemon4[] = _("POKéMON"); // Unused
const u8 gText_FlyToWhere[] = _("VOLO dove?");
const u8 gMenuText_Use[] = _("USA");
const u8 gMenuText_Toss[] = _("GETTA");
const u8 gMenuText_Register[] = _("REGISTRA");
const u8 gMenuText_Give[] = _("DAI");
const u8 gMenuText_Confirm[] = _("CONFERMA");
const u8 gText_Cancel[] = _("ANNULLA");
const u8 gText_Cancel2[] = _("ANNULLA");
const u8 gText_EmptyString2[] = _("");
const u8 gText_None[] = _("NESSUNO");
const u8 gText_FiveMarks[] = _("?????");
const u8 gText_Slash[] = _("/");
const u8 gText_OneDash[] = _("-");
const u8 gText_TwoDashes[] = _("--");
const u8 gText_ThreeDashes[] = _("---");
const u8 gText_MaleSymbol[] = _("♂");
const u8 gText_FemaleSymbol[] = _("♀");
const u8 gText_LevelSymbol[] = _("{LV}");
const u8 gText_NumberClear01[] = _("{NO}{CLEAR 0x01}");
const u8 gText_RightArrow[] = _("{RIGHT_ARROW}"); // Unused
const u8 gText_IDNumber2[] = _("{ID}{NO}");
const u8 gText_Space[] = _(" ");
const u8 gText_SelectorArrow2[] = _("▶");
const u8 gText_GoBackPrevMenu[] = _("Torna al\nmenu precedente.");
const u8 gText_WhatWouldYouLike[] = _("Cosa vuoi fare?");
const u8 gMenuText_Give2[] = _("DAI");
const u8 gText_xVar1[] = _("×{STR_VAR_1}");
const u8 gText_Berry2[] = _(" BACCA"); // Unused
const u8 gText_Coins[] = _("{STR_VAR_1} GETTONI");
const u8 gText_CloseBag[] = _("CHIUDI ZAINO");
const u8 gText_Var1IsSelected[] = _("{STR_VAR_1}\nè selezionato.");
const u8 gText_CantWriteMail[] = _("Non puoi scrivere\nla LETTERA qui.");
const u8 gText_NoPokemon[] = _("Non c'è nessun\nPOKéMON.");
const u8 gText_MoveVar1Where[] = _("Sposta\n{STR_VAR_1}\ndove?");
const u8 gText_Var1CantBeHeld[] = _("{STR_VAR_1} non si può tenere.");
const u8 gText_TossHowManyVar1s[] = _("Quanti ne vuoi\nbuttare: {STR_VAR_1}?");
const u8 gText_ThrewAwayVar2Var1s[] = _("Buttati {STR_VAR_2}\n{STR_VAR_1}.");
const u8 gText_ConfirmTossItems[] = _("Vuoi buttare\n{STR_VAR_2}\n{STR_VAR_1}?");
#if IS_HNS
    const u8 gText_DadsAdvice[] = _("Il consiglio di ELM…\n{PLAYER}, c'è un tempo e un luogo per\ltutto!{PAUSE_UNTIL_PRESS}");
#else
    const u8 gText_DadsAdvice[] = _("Il consiglio di PAPÀ…\n{PLAYER}, c'è un tempo e un luogo per\ltutto!{PAUSE_UNTIL_PRESS}");
#endif
const u8 gText_PlayerUsedVar2[] = _("{PLAYER} usa\n{STR_VAR_2}.{PAUSE_UNTIL_PRESS}");
const u8 gText_RepelEffectsLingered[] = _("Ma l'effetto del REPELLENTE\nè rimasto di prima.{PAUSE_UNTIL_PRESS}");
const u8 gText_LureEffectsLingered[] = _("Ma l'effetto del PROFUMO INVITO\nè rimasto di prima.{PAUSE_UNTIL_PRESS}");
const u8 gText_BoxFull[] = _("Il BOX è pieno.{PAUSE_UNTIL_PRESS}");
const u8 gText_TheField[] = _("il campo");
const u8 gText_TheBattle[] = _("la lotta");
const u8 gText_ThePokemonList[] = _("la LISTA POKéMON");
const u8 gText_TheShop[] = _("il negozio");
const u8 gText_ThePC[] = _("il PC");

const u8 *const gBagMenu_ReturnToStrings[] =
{
    [ITEMMENULOCATION_FIELD]               = gText_TheField,
    [ITEMMENULOCATION_BATTLE]              = gText_TheBattle,
    [ITEMMENULOCATION_PARTY]               = gText_ThePokemonList,
    [ITEMMENULOCATION_SHOP]                = gText_TheShop,
    [ITEMMENULOCATION_BERRY_TREE]          = gText_TheField,
    [ITEMMENULOCATION_BERRY_BLENDER_CRUSH] = gText_TheField,
    [ITEMMENULOCATION_ITEMPC]              = gText_ThePC,
    [ITEMMENULOCATION_FAVOR_LADY]          = gText_TheField,
    [ITEMMENULOCATION_QUIZ_LADY]           = gText_TheField,
    [ITEMMENULOCATION_APPRENTICE]          = gText_TheField,
    [ITEMMENULOCATION_WALLY]               = gText_TheBattle,
    [ITEMMENULOCATION_PCBOX]               = gText_ThePC,
    [ITEMMENULOCATION_BERRY_TREE_MULCH]    = gText_TheField,
};

const u8 *const gPyramidBagMenu_ReturnToStrings[] =
{
    [PYRAMIDBAG_LOC_FIELD]       = gText_TheField,
    [PYRAMIDBAG_LOC_BATTLE]      = gText_TheBattle,
    [PYRAMIDBAG_LOC_PARTY]       = gText_ThePokemonList,
    [PYRAMIDBAG_LOC_CHOOSE_TOSS] = gText_TheField
};

const u8 gText_ReturnToVar1[] = _("Torna a\n{STR_VAR_1}.");

const u8 *const gPocketNamesStringsTable[] =
{
    [POCKET_ITEMS] =        COMPOUND_STRING("STRUMENTI"),
    [POCKET_POKE_BALLS] =   COMPOUND_STRING("POKé BALL"),
    [POCKET_TM_HM]  =       COMPOUND_STRING("MT e MN"),
    [POCKET_BERRIES] =      COMPOUND_STRING("BACCHE"),
    [POCKET_KEY_ITEMS] =    COMPOUND_STRING("STRUMENTI"),
    [POCKET_MEDICINE] =     COMPOUND_STRING("MEDICINE"),
#if I_COMBINE_BAG_POCKETS == FALSE
    [POCKET_BATTLE_ITEMS] = COMPOUND_STRING("LOTTA"),
    [POCKET_TREASURES] =    COMPOUND_STRING("TESORI"),
#endif
};

const u8 gText_NumberItem_TMBerry[] = _("{NO}{STR_VAR_1}{CLEAR 0x03}{STR_VAR_2}");
const u8 gText_NumberItem_HM[] = _("{CLEAR_TO 0x11}{STR_VAR_1}{CLEAR 0x05}{STR_VAR_2}");

const u8 gText_ShopBuy[] = _("COMPRA");
const u8 gText_ShopSell[] = _("VENDI");
const u8 gText_ShopQuit[] = _("ESCI");
const u8 gText_ThatItemIsSoldOut[] = _("Mi dispiace, ma quel prodotto è esaurito.{PAUSE_UNTIL_PRESS}");
const u8 gText_SoldOut[] = _("ESAURITO");
const u8 gText_InBagVar1[] = _("NELLO ZAINO: {STR_VAR_1}");
const u8 gText_QuitShopping[] = _("Fine acquisti.");
const u8 gText_Var1CertainlyHowMany[] = _("{STR_VAR_1}? Certo.\nQuanti ne vuoi?");
const u8 gText_Var1CertainlyHowMany2[] = _("{STR_VAR_1}? Certo.\nQuanti ne vuoi?");
const u8 gText_Var1AndYouWantedVar2[] = _("{STR_VAR_1}? E ne vuoi {STR_VAR_2}?\nSono ¥{STR_VAR_3}.");
const u8 gText_Var1AndYouWantedVar2BP[] = _("{STR_VAR_1}? E ne vuoi {STR_VAR_2}?\nSono {STR_VAR_3}BP.");
const u8 gText_Var1IsItThatllBeVar2[] = _("{STR_VAR_1}, eh?\nSono ¥{STR_VAR_2}. Lo vuoi?");
const u8 gText_YouWantedVar1ThatllBeVar2[] = _("Vuoi {STR_VAR_1}?\nSono ¥{STR_VAR_2}. Va bene?");
const u8 gText_YouWantedVar1ThatllBeVar2BP[] = _("Vuoi {STR_VAR_1}?\nSono {STR_VAR_2}BP. Va bene?");
const u8 gText_HereYouGoThankYou[] = _("Ecco qua!\nGrazie mille.");
const u8 gText_ThankYouIllSendItHome[] = _("Grazie!\nLo mando al tuo PC di casa.");
const u8 gText_ThanksIllSendItHome[] = _("Grazie!\nLo mando al PC di casa tua.");
const u8 gText_YouDontHaveMoney[] = _("Non hai abbastanza soldi.{PAUSE_UNTIL_PRESS}");
const u8 gText_YouDontHaveEnoughBP[] = _("Non hai abbastanza\nBP.{PAUSE_UNTIL_PRESS}");
const u8 gText_DontHaveEnoughVar1[] = _("Non hai abbastanza\n{STR_VAR_1}.{PAUSE_UNTIL_PRESS}");
const u8 gText_Var1SureHowMany[] = _("{STR_VAR_1}? Certo.\nQuanti ne vuoi?");
const u8 gText_xOne[] = _("x1");
const u8 gText_xFive[] = _("x5");
const u8 gText_KurtVar1AndYouWantedVar2Plural[] = _("E ne volevi {STR_VAR_2}?\nSono {STR_VAR_3} bacche.");
const u8 gText_KurtVar1AndYouWantedVar2Singular[] = _("E ne volevi {STR_VAR_2}?\nÈ {STR_VAR_3} bacca.");
const u8 gText_KurtGettingStarted[] = _("KURT: Inizio subito!");
const u8 gText_ExitMenu[] = _("ESCI");
const u8 gText_NoMoreRoomForThis[] = _("Non hai più spazio per questo\noggetto.{PAUSE_UNTIL_PRESS}");
const u8 gText_SpaceForVar1Full[] = _("Lo spazio per {STR_VAR_1} è pieno.{PAUSE_UNTIL_PRESS}");
const u8 gText_AnythingElseICanHelp[] = _("Serve altro? Posso aiutarti\ncon qualcos'altro?");
const u8 gText_CanIHelpWithAnythingElse[] = _("Posso aiutarti con qualcos'altro?");
const u8 gText_ThrowInPremierBall[] = _("Ti do anche una PREMIER BALL.{PAUSE_UNTIL_PRESS}");
const u8 gText_ThrowInPremierBalls[] = _("Ti do anche {STR_VAR_1} PREMIER BALL.{PAUSE_UNTIL_PRESS}");
const u8 gText_CantBuyKeyItem[] = _("{STR_VAR_2}? Oh, no.\nNon posso comprarlo.{PAUSE_UNTIL_PRESS}");
const u8 gText_HowManyToSell[] = _("{STR_VAR_2}?\nQuanti ne vuoi vendere?");
const u8 gText_ICanPayVar1[] = _("Posso pagare ¥{STR_VAR_1}.\nVa bene?");
const u8 gText_TurnedOverVar1ForVar2[] = _("Hai dato {STR_VAR_2}\ne ricevuto ¥{STR_VAR_1}.");
const u8 gText_PokedollarVar1[] = _("¥{STR_VAR_1}");
const u8 gText_HP3[] = _("PS");
const u8 gText_SpAtk3[] = _("ATT. SP.");
const u8 gText_SpDef3[] = _("DIF. SP.");
const u8 gText_WontHaveEffect[] = _("Non avrà alcun effetto.{PAUSE_UNTIL_PRESS}");
const u8 gText_NextFusionMon[] = _("Scegli con quale {PKMN} fonderti.");
const u8 gText_CantBeUsedOnPkmn[] = _("Non si può usare su\nquel POKéMON.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCantSwitchOut[] = _("{STR_VAR_1} non può essere\nsostituito!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadyInBattle[] = _("{STR_VAR_1} è già\nin lotta!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadySelected[] = _("{STR_VAR_1} è già stato\nscelto.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnHasNoEnergy[] = _("{STR_VAR_1} non ha più\nenergia per lottare!{PAUSE_UNTIL_PRESS}");
const u8 gText_CantSwitchWithAlly[] = _("Non puoi scambiare i POKéMON di {STR_VAR_1}\ncon i tuoi!{PAUSE_UNTIL_PRESS}");
const u8 gText_EggCantBattle[] = _("Un UOVO non può lottare!{PAUSE_UNTIL_PRESS}");
const u8 gText_CantUseUntilNewBadge[] = _("Non si può usare finché non\nottieni una nuova MEDAGLIA.{PAUSE_UNTIL_PRESS}");
const u8 gText_NoMoreThanVar1Pkmn[] = _("Non più di {STR_VAR_1} POKéMON\npossono entrare.{PAUSE_UNTIL_PRESS}");
const u8 gText_SendMailToPC[] = _("Vuoi inviare la MESSAGGIO\nrimossa al PC?");
const u8 gText_MailSentToPC[] = _("Il MESSAGGIO è stato inviato al PC.{PAUSE_UNTIL_PRESS}");
const u8 gText_PCMailboxFull[] = _("La CASELLA del PC è piena.{PAUSE_UNTIL_PRESS}");
const u8 gText_MailMessageWillBeLost[] = _("Se rimuovi il MESSAGGIO,\nandrà perso. Va bene?");
const u8 gText_RemoveMailBeforeItem[] = _("Devi rimuovere il MESSAGGIO\nprima di dare un oggetto.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnWasGivenItem[] = _("{STR_VAR_1} riceve\n{STR_VAR_2} da tenere.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadyHoldingItemSwitch[] = _("{STR_VAR_1} tiene già\nun {STR_VAR_2}.\pVuoi scambiare\ni due oggetti?");
const u8 gText_PkmnNotHolding[] = _("{STR_VAR_1} non tiene\nnulla.{PAUSE_UNTIL_PRESS}");
const u8 gText_ReceivedItemFromPkmn[] = _("Hai ricevuto {STR_VAR_2}\nda {STR_VAR_1}.{PAUSE_UNTIL_PRESS}");
const u8 gText_MailTakenFromPkmn[] = _("Il MESSAGGIO è stato tolto\nal POKéMON.{PAUSE_UNTIL_PRESS}");
const u8 gText_SwitchedPkmnItem[] = _("Hai preso {STR_VAR_2} e\nmesso {STR_VAR_1} al suo posto.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnHoldingItemCantHoldMail[] = _("Questo POKéMON tiene un\noggetto. Non può tenere MESSAGGI.{PAUSE_UNTIL_PRESS}");
const u8 gText_MailTransferredFromMailbox[] = _("La POSTA è stata trasferita\ndalla CASELLA POSTA.{PAUSE_UNTIL_PRESS}");
const u8 gText_BagFullCouldNotRemoveItem[] = _("Lo ZAINO è pieno. Impossibile\nrimuovere lo strumento.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnLearnedMove3[] = _("{STR_VAR_1} ha imparato\n{STR_VAR_2}!");
const u8 gText_PkmnLearnedMove4[] = _("{STR_VAR_1} ha imparato\n{STR_VAR_2}!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCantLearnMove[] = _("{STR_VAR_1} e {STR_VAR_2}\nnon sono compatibili.\p{STR_VAR_2} non può\nessere imparata.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnNeedsToReplaceMove[] = _("{STR_VAR_1} vuole imparare\nla mossa {STR_VAR_2}.\pMa {STR_VAR_1} conosce\ngià quattro mosse.\pVuoi eliminare una mossa\ne imparare {STR_VAR_2}?");
const u8 gText_StopLearningMove2[] = _("Vuoi smettere di insegnare\n{STR_VAR_2}?");
const u8 gText_MoveNotLearned[] = _("{STR_VAR_1} non ha imparato\nla mossa {STR_VAR_2}.{PAUSE_UNTIL_PRESS}");
const u8 gText_WhichMoveToForget[] = _("Quale mossa dimenticare?{PAUSE_UNTIL_PRESS}");
const u8 gText_12PoofForgotMove[] = _("1, {PAUSE 15}2, e{PAUSE 15}… {PAUSE 15}… {PAUSE 15}… {PAUSE 15}{PLAY_SE SE_BALL_BOUNCE_1}Puff!\p{STR_VAR_1} ha dimenticato\ncome usare {STR_VAR_2}.\pE…{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadyKnows[] = _("{STR_VAR_1} conosce già\n{STR_VAR_2}.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnHPRestoredByVar2[] = _("I PS di {STR_VAR_1} sono stati\nripristinati di {STR_VAR_2} punti.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCuredOfPoison[] = _("{STR_VAR_1} è guarito\ndall'avvelenamento.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCuredOfParalysis[] = _("{STR_VAR_1} è guarito\ndalla paralisi.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnWokeUp2[] = _("{STR_VAR_1} si è svegliato.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnBurnHealed[] = _("La scottatura di {STR_VAR_1} è guarita.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnFrostbiteHealed[] = _("Il congelamento di {STR_VAR_1} è guarito.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnThawedOut[] = _("{STR_VAR_1} si è scongelato.{PAUSE_UNTIL_PRESS}");
const u8 gText_PPWasRestored[] = _("I PP sono stati ripristinati.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnRegainhedHealth[] = _("{STR_VAR_1} ha recuperato salute.{PAUSE_UNTIL_PRESS}"); // Unused
const u8 gText_PkmnBecameHealthy[] = _("{STR_VAR_1} è di nuovo in salute.{PAUSE_UNTIL_PRESS}");
const u8 gText_MovesPPIncreased[] = _("I PP di {STR_VAR_1} sono aumentati.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnElevatedToLvVar2[] = _("{STR_VAR_1} è salito\nal liv. {STR_VAR_2}.");
const u8 gText_PkmnGainedExp[] = _("{STR_VAR_1} ha ottenuto {STR_VAR_2} Punti Esperienza!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnGainedExpAndElevatedToLvVar3[] = _("{STR_VAR_1} ha ottenuto {STR_VAR_2} Punti Esp.\ned è salito al liv. {STR_VAR_3}!");
const u8 gText_PkmnBaseVar2StatIncreased[] = _("{STR_VAR_1}: statistica {STR_VAR_2}\nbase aumentata.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnFriendlyBaseVar2Fell[] = _("{STR_VAR_1} è diventato amichevole.\nLa base {STR_VAR_2} è calata!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAdoresBaseVar2Fell[] = _("{STR_VAR_1} ti adora!\nLa base {STR_VAR_2} è calata!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnFriendlyBaseVar2CantFall[] = _("{STR_VAR_1} è diventato amichevole.\nLa base {STR_VAR_2} non può calare!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnSnappedOutOfConfusion[] = _("{STR_VAR_1} è uscito dalla\nconfusione.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnGotOverInfatuation[] = _("{STR_VAR_1} non è più\ninfatuato.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnTransformed[] = _("{STR_VAR_1} si è trasformato!{PAUSE_UNTIL_PRESS}");
const u8 gText_ThrowAwayItem[] = _("Buttare via\n{STR_VAR_1}?");
const u8 gText_ItemThrownAway[] = _("Il {STR_VAR_1}\nè stato buttato via.{PAUSE_UNTIL_PRESS}");
const u8 gText_TeachWhichPokemon2[] = _("Insegna a quale POKéMON?"); // Unused
const u8 gText_ChoosePokemon[] = _("Scegli un POKéMON.");
const u8 gText_MoveToWhere[] = _("Sposta dove?");
const u8 gText_TeachWhichPokemon[] = _("Insegna a quale POKéMON?");
const u8 gText_UseOnWhichPokemon[] = _("Usa su quale POKéMON?");
const u8 gText_GiveToWhichPokemon[] = _("Dai a quale POKéMON?");
const u8 gText_DoWhatWithPokemon[] = _("Cosa fare con questo {PKMN}?");
const u8 gText_NothingToCut[] = _("Non c'è nulla da TAGLIARE.");
const u8 gText_CantSurfHere[] = _("Non puoi usare SURF qui.");
const u8 gText_AlreadySurfing[] = _("Stai già usando SURF.");
const u8 gText_CantUseHere[] = _("Non puoi usarlo qui.");
const u8 gText_RestoreWhichMove[] = _("Quale mossa ripristini?");
const u8 gText_BoostPp[] = _("Aumentare i PP di quale mossa?");
const u8 gText_DoWhatWithItem[] = _("Cosa vuoi fare con l'oggetto?");
const u8 gText_NoPokemonForBattle[] = _("Nessun POKéMON per la lotta!");
const u8 gText_ChoosePokemon2[] = _("Scegli un POKéMON.");
const u8 gText_NotEnoughHp[] = _("PS insufficienti…");
const u8 gText_PokemonAreNeeded[] = _("Servono {STR_VAR_1} POKéMON.");
const u8 gText_PokemonCantBeSame[] = _("I POKéMON non possono essere uguali.");
const u8 gText_NoIdenticalHoldItems[] = _("Niente strumenti identici.");
const u8 gText_CurrentIsTooFast[] = _("La corrente è troppo forte!");
const u8 gText_DoWhatWithMail[] = _("Cosa vuoi fare con la LETTERA?");
const u8 gText_ChoosePokemonCancel[] = _("Scegli un POKéMON o ANNULLA.");
const u8 gText_ChoosePokemonConfirm[] = _("Scegli un POKéMON e conferma.");
const u8 gText_SendWhichMonToPC[] = _("Quale POKéMON invii al PC?");
const u8 gText_MoveItemWhere[] = _("Dove sposti l'oggetto?");
const u8 gText_XsYAnd[] = _("{STR_VAR_2} di {STR_VAR_1} e\n");
const u8 gText_XsYWereSwapped[] = _("{STR_VAR_2} di {STR_VAR_1} sono stati scambiati!{PAUSE_UNTIL_PRESS}");
const u8 gText_EnjoyCycling[] = _("Andiamo in bici!");
const u8 gText_InUseAlready_PM[] = _("È già in uso.");
const u8 gText_AlreadyHoldingOne[] = _("{STR_VAR_1} tiene già\nun {STR_VAR_2}.");
const u8 gText_WhichAppliance[] = _("Ordina quale\ncongegno?");
const u8 gText_NoUse[] = _("Inutile.");
const u8 gText_Able[] = _("SÌ");
const u8 gText_First_PM[] = _("PRIMO");
const u8 gText_Second_PM[] = _("SECONDA");
const u8 gText_Third_PM[] = _("TERZA");
const u8 gText_Able2[] = _("SÌ");
const u8 gText_NotAble[] = _("NO");
const u8 gText_Able3[] = _("SÌ!");
const u8 gText_NotAble2[] = _("NO!");
const u8 gText_Learned[] = _("APPRESA");
const u8 gText_Have[] = _("HO");
const u8 gText_DontHave[] = _("NON CE L'HA");
const u8 gText_Fourth[] = _("QUARTA");
const u8 gText_PkmnCantParticipate[] = _("Quel POKéMON non può partecipare.{PAUSE_UNTIL_PRESS}");
const u8 gText_CancelParticipation[] = _("Annullare la partecipazione?");
const u8 gText_CancelBattle[] = _("Annullare la lotta?");
const u8 gText_ReturnToWaitingRoom[] = _("Tornare alla SALA D'ATTESA?");
const u8 gText_CancelChallenge[] = _("Annullare la sfida?");
const u8 gText_EscapeFromHere[] = _("Vuoi fuggire da qui e tornare\na {STR_VAR_1}?");
const u8 gText_ReturnToHealingSpot[] = _("Vuoi tornare al luogo di cura\nusato in {STR_VAR_1}?");
const u8 gText_PauseUntilPress[] = _("{PAUSE_UNTIL_PRESS}");
const u8 gJPText_AreYouSureYouWantToSpinTradeMon[] = _("{STR_VAR_1}を ぐるぐるこうかんに\nだして よろしいですか？");
ALIGNED(4) const u8 gText_OnlyPkmnForBattle[] = _("È il tuo unico\nPOKéMON per la lotta.");
ALIGNED(4) const u8 gText_PkmnCantBeTradedNow[] = _("Quel POKéMON non può essere\nscambiato ora.");
ALIGNED(4) const u8 gText_PkmnCantBeTraded[] = _("Quel POKéMON non può essere scambiato.");
ALIGNED(4) const u8 gText_EggCantBeTradedNow[] = _("Un UOVO non può essere scambiato ora.");
ALIGNED(4) const u8 gText_OtherTrainersPkmnCantBeTraded[] = _("Il POKéMON dell'altro\nALLENATORE non può essere scambiato.");
ALIGNED(4) const u8 gText_OtherTrainerCantAcceptPkmn[] = _("L'altro ALLENATORE non può\naccettare quel POKéMON ora.");
ALIGNED(4) const u8 gText_CantTradeWithTrainer[] = _("Non puoi scambiare con\nquell'ALLENATORE ora.");
ALIGNED(4) const u8 gText_NotPkmnOtherTrainerWants[] = _("Non è il tipo di POKéMON\nche vuole l'altro ALLENATORE.");
ALIGNED(4) const u8 gText_ThatIsntAnEgg[] = _("Quello non è un UOVO.");
const u8 gText_Register[] = _("REGISTRA");
const u8 gText_Attack3[] = _("ATTACCO");
const u8 gText_Defense3[] = _("DIFESA");
const u8 gText_SpAtk4[] = _("ATT. SP.");
const u8 gText_SpDef4[] = _("DIF. SP.");
const u8 gText_Speed2[] = _("VELOCITÀ");
const u8 gText_HP4[] = _("PS");
const u8 gText_EmptyString8[] = _(""); // Unused
const u8 gText_OTSlash[] = _("AO/");
const u8 gText_RentalPkmn[] = _("POKéMON A NOLEGGIO");
const u8 gText_TypeSlash[] = _("TIPO/");
const u8 gText_Power[] = _("POTERE");
const u8 gText_Accuracy2[] = _("PRECISIONE");
const u8 gText_Appeal[] = _("APPELLO");
const u8 gText_Jam[] = _("BOSCO");
const u8 gText_Status[] = _("STATO");
const u8 gText_ExpPoints[] = _("PUNTI ESP.");
const u8 gText_NextLv[] = _("PROSS. LIV.");
const u8 gText_RibbonsVar1[] = _("FIOCCHI: {STR_VAR_1}");
const u8 gText_EmptyString5[] = _("");
const u8 gText_Events[] = _("EVENTI"); // Unused
const u8 gText_Switch[] = _("SCAMBIA");
const u8 gText_PkmnInfo[] = _("INFO POKéMON");
const u8 gText_PkmnSkills[] = _("ABILITà POKéMON");
const u8 gText_BattleMoves[] = _("MOSSE LOTTA");
const u8 gText_ContestMoves[] = _("MOSSE GARA");
const u8 gText_Info[] = _("INFO");
const u8 gText_EggWillTakeALongTime[] = _("Sembra che questo UOVO\nimpiegherà molto a schiudersi.");
const u8 gText_EggWillTakeSomeTime[] = _("Cosa nascerà da questo?\nCi vorrà un po' di tempo.");
const u8 gText_EggWillHatchSoon[] = _("Si muove di tanto in tanto.\nDovrebbe schiudersi presto.");
const u8 gText_EggAboutToHatch[] = _("Sta emettendo dei suoni.\nSta per schiudersi!");
const u8 gText_EggReadyToHatch_Nuzlocke[] = _("Pronto a schiudersi, ma bloccato\ndall'incontro Nuzlocke!");
const u8 gText_HMMovesCantBeForgotten2[] = _("Le mosse MN non si possono\ndimenticare ora.");
const u8 gText_XNatureMetAtYZ[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}{DYNAMIC 6}{DYNAMIC 7} nature,\nincontrato a {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1},\n{DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}.");
const u8 gText_XNatureHatchedAtYZ[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}{DYNAMIC 6}{DYNAMIC 7} nature,\nschiuso a {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1},\n{DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}.");
const u8 gText_XNatureObtainedInTrade[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}{DYNAMIC 6}{DYNAMIC 7} nature,\nottenuto in uno scambio.");
const u8 gText_XNatureFatefulEncounter[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}{DYNAMIC 6}{DYNAMIC 7} nature,\nottenuto in un incontro\nfatidico a {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}.");
const u8 gText_XNatureProbablyMetAt[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}{DYNAMIC 6}{DYNAMIC 7} nature,\nforse incontrato a {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1},\n{DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}.");
const u8 gText_XNature[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}{DYNAMIC 6}{DYNAMIC 7} nature");
const u8 gText_XNatureMetSomewhereAt[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}{DYNAMIC 6}{DYNAMIC 7} nature,\nincontrato in un luogo a {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}.");
const u8 gText_XNatureHatchedSomewhereAt[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5}{DYNAMIC 6}{DYNAMIC 7} nature,\nschiuso in un luogo a {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}.");
const u8 gText_OddEggFoundByCouple[] = _("Un UOVO di POKéMON strano trovato\ndai coniugi PENSIONE.");
const u8 gText_PeculiarEggNicePlace[] = _("Un UOVO di POKéMON peculiare\nottenuto in un bel posto.");
const u8 gText_PeculiarEggTrade[] = _("Un UOVO di POKéMON peculiare\nottenuto in uno scambio.");
const u8 gText_EggFromHotSprings[] = _("Un UOVO di POKéMON ottenuto\nalle sorgenti termali.");
const u8 gText_OddEggFromDaycare[] = _("Un UOVO di POKéMON\nottenuto alla pensione.");
const u8 gText_EggFromTraveler[] = _("Un UOVO di POKéMON\nda un viaggiatore.");
const u8 gText_ApostropheSBase[] = _(" BASE");
const u8 gText_OkayToDeleteFromRegistry[] = _("Eliminare {STR_VAR_1}\ndal REGISTRO?");
const u8 gText_RegisteredDataDeleted[] = _("I dati registrati sono stati eliminati.{PAUSE_UNTIL_PRESS}");
const u8 gText_NoRegistry[] = _("Non c'è nessun REGISTRO.{PAUSE_UNTIL_PRESS}");
const u8 gText_DelRegist[] = _("ELIM. REGISTRO");
const u8 gText_Var3Var1SlashVar2[] = _("{STR_VAR_3}{STR_VAR_1}/{STR_VAR_2}"); // Unused
const u8 gText_Decorate[] = _("DECORA");
const u8 gText_PutAway[] = _("RIPONI");
const u8 gText_Toss2[] = _("GETTA");
const u8 gText_Color161Shadow161[] = _("{COLOR 161}{SHADOW 161}");
const u8 gText_PutOutSelectedDecorItem[] = _("Metti il decorativo scelto.");
const u8 gText_StoreChosenDecorInPC[] = _("Metti il decorativo scelto nel PC.");
const u8 gText_ThrowAwayUnwantedDecors[] = _("Butta i decorativi inutili.");
const u8 gText_NoDecorations[] = _("Non ci sono decorativi.{PAUSE_UNTIL_PRESS}");
const u8 gText_Desk[] = _("TAVOLO");
const u8 gText_Chair[] = _("SEDIA");
const u8 gText_Plant[] = _("PIANTA");
const u8 gText_Ornament[] = _("ORNAMENTO");
const u8 gText_Mat[] = _("STUOIA");
const u8 gText_Poster[] = _("POSTER");
const u8 gText_Doll[] = _("PELUCHE");
const u8 gText_Cushion[] = _("CUSCINO");
const u8 gText_Gold[] = _("ORO");
const u8 gText_Silver[] = _("ARGENTO");
const u8 gText_PlaceItHere[] = _("Metterlo qui?");
const u8 gText_CantBePlacedHere[] = _("Non si può mettere qui.");
const u8 gText_CancelDecorating[] = _("Annullare la decorazione?");
const u8 gText_InUseAlready[] = _("È già in uso.");
const u8 gText_NoMoreDecorations[] = _("Non puoi mettere altri decorativi.\nIl massimo è {STR_VAR_1}.");
const u8 gText_NoMoreDecorations2[] = _("Non puoi mettere altri decorativi.\nIl massimo è {STR_VAR_1}.");
const u8 gText_MustBePlacedOnDesk[] = _("Qui non si può mettere.\nDeve andare su un TAVOLO, ecc."); // Unused
const u8 gText_CantPlaceInRoom[] = _("Questo decorativo non si può mettere\nnella tua stanza.");
const u8 gText_CantThrowAwayInUse[] = _("Questo decorativo è in uso.\nNon si può buttare.");
const u8 gText_DecorationWillBeDiscarded[] = _("Questo {STR_VAR_1} sarà eliminato.\nVa bene?");
const u8 gText_DecorationThrownAway[] = _("Il decorativo è stato buttato.");
const u8 gText_StopPuttingAwayDecorations[] = _("Smettere di riporre i decorativi?");
const u8 gText_NoDecorationHere[] = _("Qui non c'è nessun decorativo.");
const u8 gText_ReturnDecorationToPC[] = _("Riportare il decorativo nel PC?");
const u8 gText_DecorationReturnedToPC[] = _("Il decorativo è stato riportato nel PC.");
const u8 gText_NoDecorationsInUse[] = _("Non ci sono decorativi in uso.{PAUSE_UNTIL_PRESS}");
const u8 gText_NoItems[] = _("Non ci sono oggetti.{PAUSE_UNTIL_PRESS}");
const u8 gText_NoMailHere[] = _("Non c'è nessuna LETTERA.{PAUSE_UNTIL_PRESS}");
const u8 gText_WhatToDoWithVar1sMail[] = _("Cosa vuoi fare con\nla POSTA di {STR_VAR_1}?");
const u8 gText_MessageWillBeLost[] = _("Il messaggio andrà perso.\nVa bene?");
const u8 gText_BagIsFull[] = _("Lo ZAINO è pieno.{PAUSE_UNTIL_PRESS}");
const u8 gText_MailToBagMessageErased[] = _("La POSTA è tornata nello ZAINO,\nil messaggio è stato cancellato.{PAUSE_UNTIL_PRESS}");
const u8 gText_Dad[] = _("PAPÀ");
const u8 gText_Mom[] = _("MAMMA");
const u8 gText_MomHowMuchDeposit[] = _("Quanto vuoi depositare\ncon tua MAMMA?");
const u8 gText_MomHowMuchWithdraw[] = _("Quanto vuoi prelevare\nda tua MAMMA?");
const u8 gText_MomMatchCallDesc[] = _("CALMO E GENTILE");
const u8 gText_MomMatchCallName[] = _("MAMMA");
const u8 gText_MomMenuCheckSavings[] = _("CONTO");
const u8 gText_MomMenuDeposit[] = _("DEPOSITA");
const u8 gText_MomMenuWithdraw[] = _("RITIRATA");
const u8 gText_MomMenuToggleSaving[] = _("RISPARMIA");
const u8 gText_MomMenuExit[] = _("ESCI");
const u8 gText_Info2[] = _("INFO");
const u8 gText_CoolnessContest[] = _("GARA DI CLASSE");
const u8 gText_BeautyContest[] = _("GARA BELLEZZA");
const u8 gText_CutenessContest[] = _("GARA DI GRAZIA");
const u8 gText_SmartnessContest[] = _("GARA DI ACUME");
const u8 gText_ToughnessContest[] = _("GARA DI FORZA");
const u8 gText_Decoration2[] = _("DECORAZIONI");
const u8 gText_PackUp[] = _("RIORDINA");
const u8 gText_Registry[] = _("REGISTRO");
const u8 gText_Information[] = _("INFORMAZIONI");
const u8 gText_Yes[] = _("SÌ");
const u8 gText_No[] = _("NO");
const u8 gText_Lv50[] = _("LV. 50");
const u8 gText_OpenLevel[] = _("LIVELLO LIBERO");
const u8 gText_RedShard[] = _("COCCIO ROSSO");
const u8 gText_YellowShard[] = _("COCCIO GIALLO");
const u8 gText_BlueShard[] = _("COCCIO BLU");
const u8 gText_GreenShard[] = _("COCCIO VERDE");
const u8 gText_BattleFrontier[] = _("PARCO LOTTA");
const u8 gText_Cool[] = _("CLASSE");
const u8 gText_Beauty[] = _("BELLEZZA");
const u8 gText_Cute[] = _("GRAZIA");
const u8 gText_Smart[] = _("CLASSE");
const u8 gText_Tough[] = _("FORZA");
const u8 gText_Normal[] = _("NORMALE");
const u8 gText_Super[] = _("SUPER");
const u8 gText_Hyper[] = _("IPER");
const u8 gText_Master[] = _("MAESTRO");
const u8 gText_Cool2[] = _("CLASSE");
const u8 gText_Beauty2[] = _("BELLEZZA");
const u8 gText_Cute2[] = _("GRAZIA");
const u8 gText_Smart2[] = _("CLASSE");
const u8 gText_Tough2[] = _("FORZA");
const u8 gText_Items[] = _("STRUMENTI");
const u8 gText_Key_Items[] = _("STRUMENTI");
const u8 gText_Poke_Balls[] = _("POKé BALL");
const u8 gText_TMs_Hms[] = _("MT e MN");
const u8 gText_Berries2[] = _("BACCHE");
const u8 gText_Medicine[] = _("MEDICINE");
#if I_COMBINE_BAG_POCKETS == FALSE
const u8 gText_BattleItems[] = _("STRUMENTI");
const u8 gText_Treasures[] = _("TESORI");
#endif
const u8 gText_SomeonesPC[] = _("PC DI QUALCUNO");
const u8 gText_LanettesPC[] = _("PC DI LANETTE");
const u8 gText_BillsPc[] = _("PC DI BILL");
const u8 gText_PlayersPC[] = _("PC DI {PLAYER}");
const u8 gText_HallOfFame[] = _("ALBO D'ORO");
const u8 gText_LogOff[] = _("ESCI");
const u8 gText_Challenges[] = _("SFIDE");
const u8 gText_Opponent[] = _("AVVERSARIO");
const u8 gText_Tourney_Tree[] = _("TABELLONE TORNEO");
const u8 gText_ReadyToStart[] = _("PRONTI VIA");
const u8 gText_Single2[] = _("SINGOLO");
const u8 gText_Double2[] = _("DOPPIO");
const u8 gText_Multi[] = _("MULTI");
const u8 gText_MultiLink[] = _("MULTI-LINK");
const u8 gText_MenuOptionPokedex[] = _("POKéDEX");
const u8 gText_MenuOptionPokemon[] = _("POKéMON");
const u8 gText_MenuOptionBag[] = _("ZAINO");
#if IS_HNS
const u8 gText_MenuOptionPokenav[] = _("POKéGEAR");
#else
const u8 gText_MenuOptionPokenav[] = _("POKéNAV");
#endif
const u8 gText_Blank[] = _("");
const u8 gText_MenuOptionSave[] = _("SALVA");
const u8 gText_MenuOptionOption[] = _("OPZIONI");
const u8 gText_MenuOptionExit[] = _("ESCI");
const u8 gText_SouthernIsland[] = _("ISOLA MERIDIONALE");
const u8 gText_BirthIsland[] = _("ISOLA NASCITA");
const u8 gText_FarawayIsland[] = _("ISOLA LONTANA");
const u8 gText_NavelRock[] = _("ROCCIA NAVEL");
const u8 gText_NormalTagMatch[] = _("NORMALE");
const u8 gText_VarietyTagMatch[] = _("VARIETÀ");
const u8 gText_UniqueTagMatch[] = _("UNICO");
const u8 gText_ExpertTagMatch[] = _("ESPERTI");
const u8 gText_TradeCenter[] = _("CENTRO SCAMBI");
const u8 gText_Colosseum[] = _("COLOSSEUM");
const u8 gText_RecordCorner[] = _("ANGOLO RECORD");
const u8 gText_BerryCrush3[] = _("BERRY CRUSH");
const u8 gText_BattleRules[] = _("REGOLE LOTTA");
const u8 gText_JudgeMind[] = _("GIUDIZIO: MENTE");
const u8 gText_JudgeSkill[] = _("GIUDIZIO: ABILITà");
const u8 gText_JudgeBody[] = _("GIUDIZIO: CORPO");
const u8 gText_BasicRules[] = _("REGOLE BASE");
const u8 gText_SwapPartners[] = _("SCAMBIO: ALLEATO");
const u8 gText_SwapNumber[] = _("SCAMBIO: NUMERO");
const u8 gText_SwapNotes[] = _("SCAMBIO: NOTE");
const u8 gText_BattleBasics[] = _("BASI DELLA LOTTA");
const u8 gText_PokemonNature[] = _("NATURA POKéMON");
const u8 gText_PokemonMoves[] = _("MOSSE POKéMON");
const u8 gText_Underpowered[] = _("DEBOLE");
const u8 gText_WhenInDanger[] = _("IN PERICOLO");
const u8 gText_BattlePokemon[] = _("LOTTA POKéMON");
const u8 gText_BattleTrainers[] = _("LOTTA ALLENATORI");
const u8 gText_GoOn[] = _("AVANTI");
const u8 gText_Record2[] = _("RECORD");
const u8 gText_Rest[] = _("RIPOSO");
const u8 gText_Retire[] = _("RITIRATI");
const u8 gText_1F[] = _("1F");
const u8 gText_2F[] = _("2F");
const u8 gText_3F[] = _("3F");
const u8 gText_4F[] = _("4F");
const u8 gText_5F[] = _("5F");
const u8 gText_6F[] = _("6P");
const u8 gText_7F[] = _("7P");
const u8 gText_8F[] = _("8P");
const u8 gText_9F[] = _("9P");
const u8 gText_10F[] = _("10P");
const u8 gText_11F[] = _("11P");
const u8 gText_B1F[] = _("P1");
const u8 gText_B2F[] = _("P2");
const u8 gText_B3F[] = _("P3");
const u8 gText_B4F[] = _("P4");
const u8 gText_Rooftop[] = _("TETTO");
const u8 gText_ElevatorNowOn[] = _("Ora su:");
const u8 gText_BP[] = _("PB");
const u8 gText_RankingHall[] = _("SALA CLASSIFICA");
const u8 gText_ExchangeService[] = _("SERVIZIO SCAMBI");
const u8 gText_LilycoveCity[] = _("PORTO ALGHEPOLI");
const u8 gText_SlateportCity[] = _("PORTO SELCEPOLI");
const u8 gText_Exit[] = _("ESCI");
const u8 gText_YourPartysFull[] = _("La tua squadra è piena!{PAUSE_UNTIL_PRESS}");
const u8 gText_InParty[] = _("IN SQUADRA");
const u8 gText_PokemonMaleLv[] = _("{DYNAMIC 0}{BACKGROUND WHITE}{TEXT_COLORS LIGHT_RED GREEN WHITE}♂{BACKGROUND WHITE}{TEXT_COLORS DARK_GRAY LIGHT_GRAY WHITE}/{LV}{DYNAMIC 1}"); // Unused
const u8 gText_PokemonFemaleLv[] = _("{DYNAMIC 0}{BACKGROUND WHITE}{TEXT_COLORS LIGHT_GREEN BLUE WHITE}♀{BACKGROUND WHITE}{TEXT_COLORS DARK_GRAY LIGHT_GRAY WHITE}/{LV}{DYNAMIC 1}"); // Unused
const u8 gText_PokemonNoGenderLv[] = _("{DYNAMIC 0}/{LV}{DYNAMIC 1}"); // Unused
const u8 gText_PokemonMaleLv2[] = _("{DYNAMIC 0}{BACKGROUND WHITE}{TEXT_COLORS LIGHT_RED GREEN WHITE}♂{BACKGROUND WHITE}{TEXT_COLORS DARK_GRAY LIGHT_GRAY WHITE}/{LV}{DYNAMIC 1}{DYNAMIC 2}"); // Unused
const u8 gText_PokemonFemaleLv2[] = _("{DYNAMIC 0}{BACKGROUND WHITE}{TEXT_COLORS LIGHT_GREEN BLUE WHITE}♀{BACKGROUND WHITE}{TEXT_COLORS DARK_GRAY LIGHT_GRAY WHITE}/{LV}{DYNAMIC 1}{DYNAMIC 2}"); // Unused
const u8 gText_PokemonNoGenderLv2[] = _("{DYNAMIC 0}/{LV}{DYNAMIC 1}{DYNAMIC 2}"); // Unused
const u8 gText_CombineFourWordsOrPhrases[] = _("Combina quattro parole o frasi");
const u8 gText_AndMakeYourProfile[] = _("e crea il tuo profilo.");
const u8 gText_CombineSixWordsOrPhrases[] = _("Combina sei parole o frasi");
const u8 gText_AndMakeAMessage[] = _("e crea un messaggio.");
const u8 gText_FindWordsThatDescribeYour[] = _("Trova le parole che descrivono");
const u8 gText_FeelingsRightNow[] = _("le tue sensazioni ora.");
const u8 gText_WithFourPhrases[] = _("Con quattro frasi,"); // Unused
const u8 gText_CombineNineWordsOrPhrases[] = _("Combina nove parole o frasi");
const u8 gText_AndMakeAMessage2[] = _("e crea un messaggio.");
const u8 gText_ChangeJustOneWordOrPhrase[] = _("Cambia solo una parola o frase");
const u8 gText_AndImproveTheBardsSong[] = _("e migliora la canzone del BARDO.");
const u8 gText_YourProfile[] = _("Il tuo profilo");
const u8 gText_YourFeelingAtTheBattlesStart[] = _("La tua sensazione a inizio lotta");
const u8 gText_WhatYouSayIfYouWin[] = _("Cosa dici se vinci una lotta");
const u8 gText_WhatYouSayIfYouLose[] = _("Cosa dici se perdi una lotta");
const u8 gText_TheAnswer[] = _("La risposta");
const u8 gText_TheMailMessage[] = _("Il messaggio MESSAGGIO");
const u8 gText_TheMailSalutation[] = _("Il saluto del MESSAGGIO"); // Unused
const u8 gText_TheBardsSong2[] = _("La nuova canzone");
const u8 gText_CombineTwoWordsOrPhrases[] = _("Combina due parole o frasi");
const u8 gText_AndMakeATrendySaying[] = _("e crea un modo di dire.");
const u8 gText_TheTrendySaying[] = _("Il modo di dire");
const u8 gText_IsAsShownOkay[] = _("è come mostrato. Va bene?");
const u8 gText_CombineTwoWordsOrPhrases2[] = _("Combina due parole o frasi");
const u8 gText_ToTeachHerAGoodSaying[] = _("per insegnarle un bel detto.");
const u8 gText_FindWordsWhichFit[] = _("Trova le parole adatte");
const u8 gText_TheTrainersImage[] = _("all'immagine dell'ALLENATORE.");
const u8 gText_TheImage[] = _("L'immagine:");
const u8 gText_OutOfTheListedChoices[] = _("Fra le scelte elencate,");
const u8 gText_SelectTheAnswerToTheQuiz[] = _("scegli la risposta al quiz!");
const u8 gText_AndCreateAQuiz[] = _("e crea un quiz!");
const u8 gText_PickAWordOrPhraseAnd[] = _("Scegli una parola o frase e");
const u8 gText_SetTheQuizAnswer[] = _("imposta la risposta.");
const u8 gText_TheAnswerColon[] = _("La risposta:");
const u8 gText_TheQuizColon[] = _("Il quiz:"); // Unused
const u8 gText_ApprenticePhrase[] = _("Frase dell'apprendista:");
const u8 gText_QuitEditing[] = _("Uscire dalla modifica?");
const u8 gText_StopGivingPkmnMail[] = _("Vuoi smettere di dare POKéMON MAIL?");
const u8 gText_AndFillOutTheQuestionnaire[] = _("e compilare il questionario.");
const u8 gText_LetsReplyToTheInterview[] = _("Rispondiamo all'intervista!");
const u8 gText_AllTextBeingEditedWill[] = _("Tutti i testi in modifica saranno");
const u8 gText_BeDeletedThatOkay[] = _("cancellati. Va bene?");
const u8 gText_QuitEditing2[] = _("Uscire dalla modifica?"); // Unused
const u8 gText_EditedTextWillNotBeSaved[] = _("Il testo modificato non sarà salvato."); // Unused
const u8 gText_IsThatOkay[] = _("Va bene?"); // Unused
const u8 gText_PleaseEnterPhraseOrWord[] = _("Inserisci una frase o parola."); // Unused
const u8 gText_EntireTextCantBeDeleted[] = _("Non si può cancellare tutto il testo.");
const u8 gText_OnlyOnePhrase[] = _("Si può cambiare una sola frase.");
const u8 gText_OriginalSongWillBeUsed[] = _("Verrà usata la canzone originale.");
const u8 gText_ThatsTrendyAlready[] = _("È già una moda!"); // Unused
const u8 gText_CombineTwoWordsOrPhrases3[] = _("Unisci due parole o frasi.");
const u8 gText_QuitGivingInfo[] = _("Vuoi smettere di dare info?"); // Unused
const u8 gText_StopGivingPkmnMail2[] = _("Vuoi smettere di dare POKéMON MAIL?"); // Unused
const u8 gText_CreateAQuiz2[] = _("Crea un quiz!"); // Unused
const u8 gText_SetTheAnswer[] = _("Imposta la risposta!"); // Unused
const u8 gText_CancelSelection[] = _("Annullare la selezione?"); // Unused
const u8 gText_Profile[] = _("PROFILO");
const u8 gText_AtTheBattlesStart[] = _("A inizio lotta:");
const u8 gText_UponWinningABattle[] = _("Se vinci una lotta:");
const u8 gText_UponLosingABattle[] = _("Se perdi una lotta:");
const u8 gText_TheBardsSong[] = _("La Canzone del BARDO");
const u8 gText_WhatsHipAndHappening[] = _("Cosa va di moda adesso?");
const u8 gText_Interview[] = _("Intervista");
const u8 gText_GoodSaying[] = _("Bel detto");
const u8 gText_FansQuestion[] = _("Domanda del fan");
const u8 gJPText_WhatIsTheQuizAnswer[] = _("クイズの こたえは？"); // Unused
const u8 gText_ApprenticesPhrase[] = _("Frase dell'apprendista");
const u8 gText_Questionnaire[] = _("QUESTIONARIO");
const u8 gText_YouCannotQuitHere[] = _("Non puoi uscire qui.");
const u8 gText_SectionMustBeCompleted[] = _("Questa sezione va completata.");
const u8 gText_F700sQuiz[] = _("Quiz di {DYNAMIC 0}");
const u8 gText_Lady[] = _("Lady");
const u8 gText_AfterYouHaveReadTheQuiz[] = _("Dopo aver letto la domanda");
const u8 gText_QuestionPressTheAButton[] = _("del quiz, premi il pulsante A.");
const u8 gText_TheQuizAnswerIs[] = _("Qual è la risposta del quiz?");
const u8 gText_LikeToQuitQuiz[] = _("Vuoi abbandonare questo quiz");
const u8 gText_ChallengeQuestionMark[] = _("quiz?");
const u8 gText_IsThisQuizOK[] = _("Quiz accettato?");
const u8 gText_CreateAQuiz[] = _("Crea un quiz!");
const u8 gText_SelectTheAnswer[] = _("Scegli la risposta!");
const u8 gText_LyricsCantBeDeleted[] = _("Il testo non si può cancellare.");
const u8 gText_PokemonLeague[] = _("LEGA POKéMON");
const u8 gText_PokemonCenter[] = _("CENTRO POKéMON");
const u8 gText_Coolness[] = _("Classe ");
const u8 gText_Beauty3[] = _("Bellezza ");
const u8 gText_Cuteness[] = _("Grazia ");
const u8 gText_Smartness[] = _("Acume ");
const u8 gText_Toughness[] = _("Forza ");
const u8 gText_SaveFailedCheckingBackup[] = _("Salvataggio fallito. Controllo la\nmemoria di backup… Attendi.\n{COLOR RED}“Tempo: circa 1 minuto”");
const u8 gText_BackupMemoryDamaged[] = _("La memoria di backup è danneggiata,\no la batteria interna è scarica.\nPuoi giocare, ma non salvare.");
const u8 gText_GamePlayCannotBeContinued[] = _("{COLOR RED}“Impossibile continuare.\nTorno al titolo…”");
const u8 gText_CheckCompleted[] = _("Controllo completato.\nProvo a salvare di nuovo.\nAttendi.");
const u8 gText_SaveCompleteGameCannotContinue[] = _("Salvataggio completato.\n{COLOR RED}“Impossibile continuare.\nTorno al titolo.”");
const u8 gText_SaveCompletePressA[] = _("Salvataggio completato.\n{COLOR RED}“Premi il pulsante A.”");
const u8 gText_Ferry[] = _("TRAGHETTO");
const u8 gText_SecretBase[] = _("BASE SEGRETA");
const u8 gText_Hideout[] = _("NASCONDIGLIO");
const u8 gText_ResetRTCConfirmCancel[] = _("Reset orologio?\nA: Sì, B: No");
const u8 gText_PresentTime[] = _("Ora attuale nel gioco");
const u8 gText_PreviousTime[] = _("Ora precedente nel gioco");
const u8 gText_PleaseResetTime[] = _("Reimposta l'ora.");
const u8 gText_ClockHasBeenReset[] = _("L'orologio è stato reimpostato.\nI dati saranno salvati. Attendi.");
const u8 gText_SaveCompleted[] = _("Salvataggio completato.");
const u8 gText_SaveFailed[] = _("Salvataggio fallito…");
const u8 gText_NoSaveFileCantSetTime[] = _("Non c'è un file di salvataggio,\nquindi l'ora non si può impostare.");
const u8 gText_InGameClockUsable[] = _("Il sistema di regolazione dell'orologio\ndi gioco è ora disponibile.");
const u8 gText_Spicy2[] = _("piccante");
const u8 gText_Dry2[] = _("secco");
const u8 gText_Sweet2[] = _("dolce");
const u8 gText_Bitter2[] = _("amaro");
const u8 gText_Sour2[] = _("aspro");
const u8 gText_Single[] = _("SINGOLO");
const u8 gText_Double[] = _("DOPPIO");
const u8 gText_Knockout[] = _("K.O.");
const u8 gText_Mixed[] = _("MISTO");
const u8 gText_First[] = _("primo");
const u8 gText_Second[] = _("secondo");
const u8 gText_Third[] = _("terzo");
#if OW_POISON_DAMAGE < GEN_4
const u8 gText_PkmnFainted_FldPsn[] = _("{STR_VAR_1} è esausto…\p\n");
#else
const u8 gText_PkmnFainted_FldPsn[] = _("{STR_VAR_1} ha resistito al veleno.\nIl veleno è sparito!\p");
#endif
const u8 gText_PkmnSurvived_FldPsn[] = _("{STR_VAR_1} ha resistito al veleno.\nIl veleno è sparito!\p");
const u8 gText_Marco[] = _("MARCO");
const u8 gText_TrainerCardName[] = _("NOME: ");
const u8 gText_TrainerCardIDNo[] = _("ID No.");
const u8 gText_TrainerCardMoney[] = _("SOLDI");
const u8 gText_PokeDollar[] = _("¥"); // Unused
const u8 gText_TrainerCardPokedex[] = _("POKéDEX");
const u8 gText_EmptyString6[] = _("");
const u8 gText_Colon2[] = _(":");
const u8 gText_Points[] = _(" punti"); // Unused
const u8 gText_TrainerCardTime[] = _("ORA");
const u8 gJPText_BattlePoints[] = _("ゲ-ムポイント"); // Unused. Name presumed, translation is Game Points
const u8 gText_Var1sTrainerCard[] = _("SCHEDA ALLENATORE di {STR_VAR_1}");
const u8 gText_HallOfFameDebut[] = _("ESORDIO ALBO D'ORO  ");
const u8 gText_LinkBattles[] = _("LOTTE IN LINK");
const u8 gText_LinkCableBattles[] = _("LOTTE VIA CAVO");
const u8 gText_WinsLosses[] = _("V:{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}  S:{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_2}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}");
const u8 gText_PokemonTrades[] = _("SCAMBI POKéMON");
const u8 gText_UnionTradesAndBattles[] = _("SCAMBI E LOTTE UNION");
const u8 gText_BerryCrush[] = _("BERRY CRUSH");
const u8 gText_WaitingTrainerFinishReading[] = _("In attesa che l'altro ALLENATORE\nfinisca di leggere la tua SCHEDA.");
const u8 gText_PokeblocksWithFriends[] = _("{POKEBLOCK} CON GLI AMICI");
const u8 gText_NumPokeblocks[] = _("{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}");
const u8 gText_WonContestsWFriends[] = _("GARE VINTE CON AMICI");
const u8 gText_BattlePtsWon[] = _("PUNTI LOTTA VINTI");
const u8 gText_NumBP[] = _("{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}PL");
const u8 gText_BattleTower[] = _("TORRE LOTTA");
const u8 gText_WinsStraight[] = _("V/{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}  FILA/{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_2}");
const u8 gText_BattleTower2[] = _("TORRE LOTTA");
const u8 gText_BattleDome[] = _("DOME LOTTA");
const u8 gText_BattlePalace[] = _("PALAZZO LOTTA");
const u8 gText_BattleFactory[] = _("FABBRICA LOTTA");
const u8 gText_BattleArena[] = _("ARENA LOTTA");
const u8 gText_BattlePike[] = _("PILONE LOTTA");
const u8 gText_BattlePyramid[] = _("PIRAMIDE LOTTA");

ALIGNED(4) const u8 gText_FacilitySingle[] = _("{STR_VAR_1} SINGOLO");
ALIGNED(4) const u8 gText_FacilityDouble[] = _("{STR_VAR_1} DOPPIO");
ALIGNED(4) const u8 gText_FacilityMulti[] = _("{STR_VAR_1} MULTI");
ALIGNED(4) const u8 gText_FacilityLink[] = _("{STR_VAR_1} LINK");
ALIGNED(4) const u8 gText_Facility[] = _("{STR_VAR_1}");

const u8 gText_Give[] = _("Dai");
const u8 gText_NoNeed[] = _("No");
const u8 gText_AnnouncingResults[] = _("Annuncio dei risultati!");
const u8 gText_PreliminaryResults[] = _("I risultati preliminari!");
const u8 gText_Round2Results[] = _("Risultati round 2!");
const u8 gText_ContestantsMonWon[] = _("{STR_VAR_2} di {STR_VAR_1} vince!");
const u8 gText_CommunicationStandby[] = _("In attesa di comunicazione…");
const u8 gText_ColorDarkGray[] = _("{COLOR DARK_GRAY}");
const u8 gText_ColorDynamic6WhiteDynamic5[] = _("{BACKGROUND WHITE}{TEXT_COLORS DYNAMIC_COLOR6 DYNAMIC_COLOR5 WHITE}"); // Unused
const u8 gText_HealthboxNickname[] = _("{BACKGROUND DARK_GRAY}{ACCENT DARK_GRAY}");
const u8 gText_EmptySpace2[] = _(" "); // Unused
const u8 gText_HealthboxGender_Male[] = _("{COLOR DYNAMIC_COLOR2}♂");
const u8 gText_HealthboxGender_Female[] = _("{COLOR DYNAMIC_COLOR1}♀");
const u8 gText_HealthboxGender_None[] = _("{COLOR DYNAMIC_COLOR2}");
const u8 gText_Upper[] = _("MAIUS");
const u8 gText_Lower[] = _("minus");
const u8 gText_Others[] = _("ALTRI");
const u8 gText_Symbols[] = _("SIMBOLI");
const u8 gText_Register2[] = _("REGISTRA");
const u8 gText_Exit2[] = _("ESCI");
const u8 gText_QuitChatting[] = _("Chiudere la chat?");
const u8 gText_RegisterTextWhere[] = _("Dove registrare il testo?");
const u8 gText_RegisterTextHere[] = _("Registrare qui il testo?");
const u8 gText_InputText[] = _("Scrivi testo.");
const u8 gText_F700JoinedChat[] = _("{DYNAMIC 0} è entrato in chat!");
const u8 gText_F700LeftChat[] = _("{DYNAMIC 0} ha lasciato la chat.");
const u8 gJPText_PlayersXPokemon[] = _("{DYNAMIC 0}の{DYNAMIC 1}ひきめ:"); // Unused
const u8 gJPText_PlayersXPokmonDoesNotExist[] = _("{DYNAMIC 0}の{DYNAMIC 1}ひきめは いません"); // Unused
const u8 gText_ExitingChat[] = _("Uscita dalla chat…");
const u8 gText_LeaderLeftEndingChat[] = _("Il LEADER, {DYNAMIC 0}, è uscito\ne la chat è finita.");
const u8 gText_RegisteredTextChangedOKToSave[] = _("Il testo registrato è cambiato.\nVuoi salvare la partita?");
const u8 gText_AlreadySavedFile_Chat[] = _("Esiste già un file salvato.\nVuoi sovrascriverlo?");
const u8 gText_SavingDontTurnOff_Chat[] = _("SALVATAGGIO…\nNON SPEGNERE LA CONSOLE.");
const u8 gText_PlayerSavedGame_Chat[] = _("{DYNAMIC 0} ha salvato la partita.");
const u8 gText_IfLeaderLeavesChatEnds[] = _("Se il LEADER esce, la chat\nfinisce. Va bene?");
const u8 gText_Hello[] = _("CIAO");
const u8 gText_Pokemon2[] = _("POKéMON");
const u8 gText_Trade[] = _("SCAMBIO");
const u8 gText_Battle[] = _("LOTTA");
const u8 gText_Lets[] = _("ANDIAMO");
const u8 gText_Ok[] = _("OK!");
const u8 gText_Sorry[] = _("SCUSA");
const u8 gText_YaySmileEmoji[] = _("EVVIVA{EMOJI_BIGSMILE}");
const u8 gText_ThankYou[] = _("GRAZIE MILLE");
const u8 gText_ByeBye[] = _("CIAO-CIAO!");
const u8 gText_HatchedFromEgg[] = _("{STR_VAR_1} è uscito dall'UOVO!");
const u8 gText_NicknameHatchPrompt[] = _("Vuoi dare un soprannome al\n{STR_VAR_1} appena nato?");
ALIGNED(4) const u8 gText_ReadyPickBerry[] = _("Pronti a schiacciare le BACCHE?\nScegli una BACCA da usare.\p");
ALIGNED(4) const u8 gText_WaitForAllChooseBerry[] = _("Attendi mentre ogni membro\nsceglie una BACCA.");
ALIGNED(4) const u8 gText_EndedWithXUnitsPowder[] = _("{PAUSE_MUSIC}{PLAY_BGM MUS_LEVEL_UP}Hai ottenuto {STR_VAR_1} unità di\nPulviscoppio di BACCA liscio.{RESUME_MUSIC}\pIl tuo Pulviscoppio di BACCA\nè {STR_VAR_2} in tutto.\p");
ALIGNED(4) const u8 gText_RecordingGameResults[] = _("Salvataggio dei risultati nel\nfile di gioco.\lAttendi.");
ALIGNED(4) const u8 gText_PlayBerryCrushAgain[] = _("Vuoi rigiocare a SCHIACCIA BACCHE?");
ALIGNED(4) const u8 gText_YouHaveNoBerries[] = _("Non hai BACCHE.\nIl gioco verrà annullato.");
ALIGNED(4) const u8 gText_MemberDroppedOut[] = _("Un membro si è ritirato.\nIl gioco verrà annullato.");
ALIGNED(4) const u8 gText_TimesUpNoGoodPowder[] = _("Tempo scaduto.\pNon si è fatto un buon\nPulviscoppio…\p");
ALIGNED(4) const u8 gText_CommunicationStandby2[] = _("In attesa di comunicazione…");
ALIGNED(4) const u8 gText_1DotBlueF700[] = _("1. {COLOR BLUE}{SHADOW LIGHT_BLUE}{DYNAMIC 0}");
ALIGNED(4) const u8 gText_1DotF700[] = _("1. {DYNAMIC 0}");
ALIGNED(4) const u8 gText_SpaceTimes2[] = _(" volta/e");
ALIGNED(4) const u8 gText_XDotY[] = _("{STR_VAR_1}.{STR_VAR_2}");
ALIGNED(4) const u8 gText_Var1Berry[] = _("BACCA {STR_VAR_1}");
ALIGNED(4) const u8 gText_TimeColon[] = _("Tempo:");
ALIGNED(4) const u8 gText_PressingSpeed[] = _("Velocità:");
ALIGNED(4) const u8 gText_Silkiness[] = _("Levigatezza:");
ALIGNED(4) const u8 gText_StrVar1[] = _("{STR_VAR_1}");
ALIGNED(4) const u8 gText_SpaceMin[] = _(" min. ");
ALIGNED(4) const u8 gText_XDotY2[] = _("{STR_VAR_1}.{STR_VAR_2}");
ALIGNED(4) const u8 gText_SpaceSec[] = _(" sec.");
ALIGNED(4) const u8 gText_XDotY3[] = _("{STR_VAR_1}.{STR_VAR_2}");
ALIGNED(4) const u8 gText_TimesPerSec[] = _(" Volte/sec.");
ALIGNED(4) const u8 gText_Var1Percent[] = _("{STR_VAR_1}%");
ALIGNED(4) const u8 gText_PressesRankings[] = _("Classifica pressioni");
ALIGNED(4) const u8 gText_CrushingResults[] = _("Risultati schiacciata");
ALIGNED(4) const u8 gText_NeatnessRankings[] = _("Classifica finezza");
ALIGNED(4) const u8 gText_CoopRankings[] = _("Classifica cooperativa");
ALIGNED(4) const u8 gText_PressingPowerRankings[] = _("Classifica forza");
const u8 gText_BerryCrush2[] = _("BERRY CRUSH");
const u8 gText_PressingSpeedRankings[] = _("Classifica velocità");
const u8 gText_Var1Players[] = _("{STR_VAR_1} GIOCATORI");
const u8 gText_SymbolsEarned[] = _("Simboli Ottenuti");
const u8 gText_BattleRecord[] = _("Record Lotte");
const u8 gText_BattlePoints[] = _("Punti Lotta");
const u8 gText_UnusedCancel[] = _("ANNULLA"); // Unused
const u8 gText_EmptyString7[] = _("");
const u8 gText_CheckFrontierMap[] = _("Vedi MAPPA PARCO LOTTA.");
const u8 gText_CheckTrainerCard[] = _("Vedi SCHEDA ALLENATORE.");
const u8 gText_ViewRecordedBattle[] = _("Guarda la lotta registrata.");
const u8 gText_PutAwayFrontierPass[] = _("Riponi il PASS PARCO LOTTA.");
const u8 gText_CurrentBattlePoints[] = _("I tuoi Punti Lotta attuali.");
const u8 gText_CollectedSymbols[] = _("I tuoi Simboli collezionati.");
const u8 gText_BattleTowerAbilitySymbol[] = _("Torre Lotta - Simbolo Abilità");
const u8 gText_BattleDomeTacticsSymbol[] = _("Dome Lotta - Simbolo Tattica");
const u8 gText_BattlePalaceSpiritsSymbol[] = _("Palazzo Lotta - Simbolo Spirito");
const u8 gText_BattleArenaGutsSymbol[] = _("Arena Lotta - Simbolo Dentistretti");
const u8 gText_BattleFactoryKnowledgeSymbol[] = _("Fabbrica Lotta - Simbolo Sapienza");
const u8 gText_BattlePikeLuckSymbol[] = _("Serpe Lotta - Simbolo Fortuna");
const u8 gText_BattlePyramidBraveSymbol[] = _("Piramide Lotta - Simbolo Audace");
const u8 gText_ThereIsNoBattleRecord[] = _("Non c'è alcun Record Lotte.");
const u8 gText_BattleTower3[] = _("TORRE LOTTA");
const u8 gText_BattleDome2[] = _("DOME LOTTA");
const u8 gText_BattlePalace2[] = _("PALAZZO LOTTA");
const u8 gText_BattleArena2[] = _("ARENA LOTTA");
const u8 gText_BattleFactory2[] = _("FABBRICA LOTTA");
const u8 gText_BattlePike2[] = _("PILONE LOTTA");
const u8 gText_BattlePyramid2[] = _("PIRAMIDE LOTTA");
const u8 gText_BattleTowerDesc[] = _("Metti KO gli avversari e punta in alto!\nLa tua abilità sarà messa alla prova.");
const u8 gText_BattleDomeDesc[] = _("Continua a vincere nel torneo!\nLe tue tattiche alla prova.");
const u8 gText_BattlePalaceDesc[] = _("Guarda i tuoi POKéMON lottare!\nIl tuo spirito alla prova.");
const u8 gText_BattleArenaDesc[] = _("Vinci con POKéMON in squadra!\nIl tuo fegato alla prova.");
const u8 gText_BattleFactoryDesc[] = _("Vinci usando POKéMON a noleggio!\nLa tua sapienza sarà messa alla prova.");
const u8 gText_BattlePikeDesc[] = _("Scegli uno dei tre sentieri!\nLa tua fortuna alla prova.");
const u8 gText_BattlePyramidDesc[] = _("Punta in alto esplorando!\nIl tuo coraggio alla prova.");
const u8 gText_Powder[] = _("POLVERE");
const u8 gText_BerryPickingRecords[] = _("RECORD RACCOLTA BACCA DODRIO");
const u8 gText_BerriesPicked[] = _("BACCA raccolta:");
const u8 gText_BestScore[] = _("Record:");
const u8 gText_BerriesInRowFivePlayers[] = _("BACCA raccolte di fila con\ncinque giocatori:");
const u8 gText_BerryPickingResults[] = _("Ecco i risultati della RACCOLTA BACCA!");
const u8 gText_10P30P50P50P[] = _("{CLEAR_TO 0x03}10P{CLEAR_TO 0x2B}30P{CLEAR_TO 0x53}50P{CLEAR_TO 0x77}{EMOJI_MINUS}50P");
const u8 gText_AnnouncingRankings[] = _("Ecco la classifica!");
const u8 gText_AnnouncingPrizes[] = _("Ecco i premi!");
const u8 gText_1Colon[] = _("1:");
const u8 gText_2Colon[] = _("2:");
const u8 gText_3Colon[] = _("3:");
const u8 gText_4Colon[] = _("4:");
const u8 gText_5Colon[] = _("5:");
const u8 gText_FirstPlacePrize[] = _("Chi vince riceve\nquesto {DYNAMIC 0}!");
const u8 gText_CantHoldAnyMore[] = _("Non puoi tenerne altri!");
const u8 gText_FilledStorageSpace[] = _("Lo spazio è pieno.");
const u8 gText_WantToPlayAgain[] = _("Vuoi giocare ancora?");
const u8 gText_SomeoneDroppedOut[] = _("Qualcuno si è ritirato.\nIl collegamento verrà annullato.");
const u8 gText_SpacePoints[] = _(" punti");
const u8 gText_CommunicationStandby3[] = _("In attesa di comunicazione…");
const u8 gText_SpacePoints2[] = _(" punti");
const u8 gText_SpaceTimes3[] = _(" volta/e");
const u8 gText_PkmnJumpRecords[] = _("RECORD SALTO POKéMON");
const u8 gText_JumpsInARow[] = _("Salti di fila:");
const u8 gText_BestScore2[] = _("Record:");
const u8 gText_ExcellentsInARow[] = _("ECCELLENTI di fila:");
const u8 gText_AwesomeWonF701F700[] = _("Che punteggio! Hai\nvinto {DYNAMIC 1} {DYNAMIC 0}!");
const u8 gText_FilledStorageSpace2[] = _("Lo spazio è pieno.");
const u8 gText_CantHoldMore[] = _("Non puoi tenerne altri!");
const u8 gText_WantToPlayAgain2[] = _("Vuoi giocare ancora?");
const u8 gText_SomeoneDroppedOut2[] = _("Qualcuno si è ritirato.\nIl collegamento verrà annullato.");
const u8 gText_CommunicationStandby4[] = _("In attesa di comunicazione…");
const u8 gText_LinkContestResults[] = _("Gara Link di {PLAYER}");
const u8 gText_1st[] = _("1º");
const u8 gText_2nd[] = _("2º");
const u8 gText_3rd[] = _("3º");
const u8 gText_4th[] = _("4º");
const u8 gText_Friend[] = _("Amico");
const u8 gText_Pokemon3[] = _("POKéMON"); // Unused
const u8 gJPText_MysteryGift[] = _("ふしぎなもらいもの");
const u8 gJPText_DecideStop[] = _("{A_BUTTON}けってい {B_BUTTON}やめる");
const u8 gJPText_ReceiveMysteryGiftWithEReader[] = _("カードeリーダー{PLUS}　で\nふしぎなもらいものを　よみこみます");
const u8 gJPText_SelectConnectFromEReaderMenu[] = _("カードeリーダー{PLUS}の　メニューから\n‘つうしん'を　えらび");
const u8 gJPText_SelectConnectWithGBA[] = _("‘ゲームボーイアドバンスとつうしん'\nを　せんたく　してください");
const u8 gJPText_SelectConnectAndPressA[] = _("カードeリーダー{PLUS}の　‘つうしん'を\nえらんで　Aボタンを　おしてください"); // Unused
const u8 gJPText_LinkIsIncorrect[] = _("せつぞくが　まちがっています");
const u8 gJPText_CardReadingHasBeenHalted[] = _("カードの　よみこみを\nちゅうし　しました");
const u8 gJPText_UnableConnectWithEReader[] = _("カードeリーダー{PLUS}と\nつうしん　できません"); // Unused
const u8 gJPText_Connecting[] = _("つうしん　ちゅう　です");
const u8 gJPText_ConnectionErrorCheckLink[] = _("つうしん　エラーです\nせつぞくを　たしかめて　ください");
const u8 gJPText_ConnectionErrorTryAgain[] = _("つうしん　エラーです\nはじめから　やりなおして　ください"); // Link error
const u8 gJPText_AllowEReaderToLoadCard[] = _("カードeリーダー{PLUS}　に\nカードを　よみこませて　ください");
const u8 gJPText_ConnectionComplete[] = _("つうしん　しゅうりょう！");
const u8 gJPText_NewTrainerHasComeToHoenn[] = _("あらたな　トレーナーが\nホウエンに　やってきた！");
const u8 gJPText_PleaseWaitAMoment[] = _("しばらく　おまちください");
const u8 gJPText_WriteErrorUnableToSaveData[] = _("かきこみ　エラー　です\nデータが　ほぞん　できませんでした");
const u8 gText_SingleBattleRoomResults[] = _("Risultati Sala Singolo di {PLAYER}");
const u8 gText_DoubleBattleRoomResults[] = _("Risultati Sala Doppio di {PLAYER}");
const u8 gText_MultiBattleRoomResults[] = _("Risultati Sala Multi Lotta di {PLAYER}");
const u8 gText_LinkMultiBattleRoomResults[] = _("Risultati Sala Multi Lotta Link di {PLAYER}");
const u8 gText_SingleBattleTourneyResults[] = _("Risultati Torneo Lotta Singola di {PLAYER}");
const u8 gText_DoubleBattleTourneyResults[] = _("Risultati Torneo Lotta Doppia di {PLAYER}");
const u8 gText_SingleBattleHallResults[] = _("Risultati Sala Lotta Singola di {PLAYER}");
const u8 gText_DoubleBattleHallResults[] = _("Risultati Sala Lotta Doppia di {PLAYER}");
const u8 gText_BattleChoiceResults[] = _("Risultati Scelta Lotta di {PLAYER}");
const u8 gText_SetKOTourneyResults[] = _("Risultati Torneo KO di {PLAYER}");
const u8 gText_BattleSwapSingleResults[] = _("Risultati Scambio Lotta Singola di {PLAYER}");
const u8 gText_BattleSwapDoubleResults[] = _("Risultati Scambio Lotta Doppia di {PLAYER}");
const u8 gText_BattleQuestResults[] = _("Risultati Lotta Avventura di {PLAYER}");
const u8 gText_Lv502[] = _("LV. 50");
const u8 gText_OpenLv[] = _("LIV. LIB.");
const u8 gText_WinStreak[] = _("Vittorie: {STR_VAR_1}");
const u8 gText_Current[] = _("ATTUALE");
const u8 gText_Record[] = _("RECORD");
const u8 gText_Prev[] = _("PREC.");
const u8 gText_RentalSwap[] = _("Noleggio/Scambio");
const u8 gText_Total[] = _("Totale");
const u8 gText_ClearStreak[] = _("Serie: {STR_VAR_1}");
const u8 gText_Championships[] = _("Titoli: {STR_VAR_1}");
const u8 gText_RoomsCleared[] = _("Sale superate: {STR_VAR_1}");
const u8 gText_TimesCleared[] = _("Superate:{CLEAR 0x05}{STR_VAR_1}");
const u8 gText_KOsInARow[] = _("KO di fila: {STR_VAR_1}");
const u8 gText_TimesVar1[] = _("Volte: {STR_VAR_1}");
const u8 gText_FloorsCleared[] = _("Piani superati: {STR_VAR_1}");

ALIGNED(4) const u8 gText_RecordsLv50[] = _("LV. 50");
ALIGNED(4) const u8 gText_RecordsOpenLevel[] = _("LIVELLO LIBERO");
ALIGNED(4) const u8 gText_FrontierFacilityWinStreak[] = _("Vittorie: {STR_VAR_2}");
ALIGNED(4) const u8 gText_FrontierFacilityClearStreak[] = _("Serie: {STR_VAR_2}");
ALIGNED(4) const u8 gText_FrontierFacilityRoomsCleared[] = _("Sale superate: {STR_VAR_2}");
ALIGNED(4) const u8 gText_FrontierFacilityKOsStreak[] = _("KO di fila: {STR_VAR_2}");
ALIGNED(4) const u8 gText_FrontierFacilityFloorsCleared[] = _("Piani superati: {STR_VAR_2}");
ALIGNED(4) const u8 gText_123Dot[][3] = {_("1."), _("2."), _("3.")};
const u8 gText_FrontierFacilityTotalCaughtSpeciesBanned[] = _(" e {STR_VAR_2} POKéMON che hai\ncatturato non sono idonei");
const u8 gText_FrontierFacilityIncluding[] = _(".\pFra questi: ");
const u8 gText_FrontierFacilityAreInelegible[] = _(" non sono idonei");

const u8 gText_YesNo[] = _("SÌ\nNO");
const u8 gText_SelectorArrow3[] = _("▶");
const u8 gText_Peekaboo[] = _("CUCCÙ!");
const u8 gText_CommErrorCheckConnections[] = _("Errore di comunicazione…\nControlla i collegamenti,\npoi spegni e riaccendi.");
const u8 gText_CommErrorEllipsis[] = _("Errore di comunicazione…");
const u8 gText_MoveCloserToLinkPartner[] = _("Avvicinati ai tuoi partner.\nEvita gli ostacoli in mezzo.");
const u8 gText_ABtnRegistrationCounter[] = _("Pulsante A: Contatore");
const u8 gText_ABtnTitleScreen[] = _("Pulsante A: Titolo");
const u8 gText_NumPlayerLink[] = _("LINK {STR_VAR_1}P");
const u8 gText_BronzeCard[] = _("BRONZO");
const u8 gText_CopperCard[] = _("RAME");
const u8 gText_SilverCard[] = _("ARGENTO");
const u8 gText_GoldCard[] = _("ORO");
const u8 gText_Day[] = _("Giorno");
const u8 gText_Colon3[] = _(":");
const u8 gText_Confirm2[] = _("CONFERMA");
const u8 gText_Days[] = _("Giorni"); // Unused
const u8 gText_TimeColon2[] = _("Tempo:"); // Unused
const u8 gText_GameTime[] = _("Tempo di gioco"); // Unused
const u8 gText_RTCTime[] = _("Ora RTC"); // Unused
const u8 gText_UpdatedTime[] = _("Ora aggiornata"); // Unused
const u8 gText_MenuPokedex[] = _("POKéDEX");
const u8 gText_MenuPokemon[] = _("POKéMON");
const u8 gText_MenuBag[] = _("ZAINO");
#if IS_HNS
const u8 gText_MenuPokenav[] = _("{POKE}GEAR");
#else
const u8 gText_MenuPokenav[] = _("POKéNAV");
#endif
const u8 gText_MenuPlayer[] = _("{PLAYER}");
const u8 gText_MenuSave[] = _("SALVA");
const u8 gText_MenuOption[] = _("OPZIONI");
const u8 gText_MenuExit[] = _("ESCI");
const u8 gText_MenuRetire[] = _("RITIRATI");
const u8 gText_MenuRest[] = _("RIPOSO");
const u8 gText_MenuDexNav[] = _("DEXNAV");
const u8 gText_SafariBallStock[] = _("SAFARI BALL\nScorte: {STR_VAR_1}");
const u8 gText_MenuSafariStats[] = _("{STR_VAR_1}/{STR_VAR_2}\nBALL  {STR_VAR_3}");
const u8 gText_BattlePyramidFloor[] = _("Piramide Lotta\n{STR_VAR_1}");
const u8 gText_Floor1[] = _("Piano 1");
const u8 gText_Floor2[] = _("Piano 2");
const u8 gText_Floor3[] = _("Piano 3");
const u8 gText_Floor4[] = _("Piano 4");
const u8 gText_Floor5[] = _("Piano 5");
const u8 gText_Floor6[] = _("Piano 6");
const u8 gText_Floor7[] = _("Piano 7");
const u8 gText_Peak[] = _("Vetta");
const u8 gText_LinkStandby2[] = _("In attesa…\n… … B: Annulla");
const u8 gText_PressAToLoadEvent[] = _("Premi A per caricare l'evento.\n… … B: Annulla");
const u8 gText_LoadingEvent[] = _("Caricamento…");
const u8 gText_DontRemoveCableTurnOff[] = _("Non togliere il cavo Game Link.\nNon spegnere la console.");
const u8 gText_EventSafelyLoaded[] = _("L'evento è stato caricato.");
const u8 gText_LoadErrorEndingSession[] = _("Errore di caricamento.\nFine sessione.");
const u8 gJPText_Player[] = _("プレイヤー"); // Unused
const u8 gJPText_Sama[] = _("さま"); // Unused
const u8 gText_DexHoenn[] = _("HOENN");
const u8 gText_DexNational[] = _("NAZIONALE");
const u8 gText_PokedexDiploma[] = _("GIOCATORE: {CLEAR 0x10}{COLOR RED}{SHADOW LIGHT_RED}{PLAYER}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}\n\nQuesto documento certifica\nche hai completato con\nsuccesso il tuo\nPOKéDEX {STR_VAR_1}.\n\n{CLEAR_TO 0x42}{COLOR RED}{SHADOW LIGHT_RED}GAME FREAK");
const u8 gJPText_GameFreak[] = _("{COLOR RED}{SHADOW LIGHT_RED}ゲ-ムフリ-ク"); // Unused
const u8 gText_DiplomaEmpty[] = _("{COLOR RED}{SHADOW LIGHT_RED}"); // Unused
const u8 gText_Hoenn[] = _("HOENN");
const u8 gText_Kanto[] = _("KANTO");
const u8 gText_Johto[] = _("JOHTO");
const u8 gText_JohtoKanto[] = _("JOHTO & KANTO");
const u8 gText_XWillBeSentToY[] = _("{STR_VAR_2} sarà\ninviato a {STR_VAR_1}.");
const u8 gText_ByeByeVar1[] = _("Ciao ciao, {STR_VAR_2}!");
const u8 gText_XSentOverY[] = _("{STR_VAR_1} ha inviato {STR_VAR_3}.");
const u8 gText_TakeGoodCareOfX[] = _("Prenditi cura di {STR_VAR_3}!");

const u8 gText_ThreeQuestionMarks[] = _("???");
const u8 gText_FourQuestionMarks[] = _("????");
const u8 gText_MaxHP[] = _("PS MAX");
const u8 gText_Attack[] = _("ATTACCO");
const u8 gText_Defense[] = _("DIFESA");
const u8 gText_Speed[] = _("VELOCITÀ");
const u8 gText_SpAtk[] = _("ATT. SP.");
const u8 gText_SpDef[] = _("DIF. SP.");
const u8 gText_Plus[] = _("{PLUS}");
const u8 gText_Dash[] = _("-");
const u8 gText_MixingRecords[] = _("Mescolando i record…");
const u8 gText_RecordMixingComplete[] = _("Scambio record completato.\nGrazie per l'attesa.");
const u8 gText_RentalPkmn2[] = _("POKéMON A NOLEGGIO");
const u8 gText_SelectFirstPkmn[] = _("Scegli il primo POKéMON.");
const u8 gText_SelectSecondPkmn[] = _("Scegli il secondo POKéMON.");
const u8 gText_SelectThirdPkmn[] = _("Scegli il terzo POKéMON.");
const u8 gText_Rent[] = _("NOLEGGIA");
const u8 gText_Summary[] = _("RIEPILOGO");
const u8 gText_Others2[] = _("ALTRI");
const u8 gText_Deselect[] = _("ANNULLA");
const u8 gText_TheseThreePkmnOkay[] = _("Vanno bene questi tre POKéMON?");
const u8 gText_Yes2[] = _("SÌ");
const u8 gText_No2[] = _("NO");
const u8 gText_CantSelectSamePkmn[] = _("Non puoi scegliere lo stesso {PKMN}.");
const u8 gText_PkmnSwap[] = _("SCAMBIO POKéMON");
const u8 gText_SelectPkmnToSwap[] = _("Scegli il POKéMON da scambiare.");
const u8 gText_SelectPkmnToAccept[] = _("Scegli il POKéMON da accettare.");
const u8 gText_Swap[] = _("SCAMBIA");
const u8 gText_Summary2[] = _("RIEPILOGO");
const u8 gText_Rechoose[] = _("RISCEGLI");
const u8 gText_QuitSwapping[] = _("Smetti di scambiare?");
const u8 gText_Yes3[] = _("SÌ");
const u8 gText_No3[] = _("NO");
const u8 gText_PkmnForSwap[] = _("{PKMN} DA SCAMBIARE");
const u8 gText_Cancel3[] = _("ANNULLA");
const u8 gText_Swap2[] = _("SCAMBIA"); // Unused
const u8 gText_Accept[] = _("ACCETTA"); // Unused
const u8 gText_AcceptThisPkmn[] = _("Accetti questo POKéMON?");
const u8 gText_4Spaces[] = _("    "); // Unused
const u8 gText_SamePkmnInPartyAlready[] = _("Stesso {PKMN} già in squadra.");
const u8 gText_DecimalPoint[] = _(".");
const u8 gText_SavingPlayer[] = _("GIOCATORE");
const u8 gText_SavingBadges[] = _("MEDAGLIE");
const u8 gText_SavingPokedex[] = _("POKéDEX");
const u8 gText_SavingTime[] = _("ORA");
const u8 gText_WirelessCommStatus[] = _("Stato comunicazione wireless");
const u8 gText_PeopleTrading[] = _("In scambio:");
const u8 gText_PeopleBattling[] = _("In lotta:");
const u8 gText_PeopleInUnionRoom[] = _("Persone nella UNION ROOM:");
const u8 gText_PeopleCommunicating[] = _("In comunicazione:");
const u8 gText_F700Players[] = _("{DYNAMIC 0} giocatori");
const u8 gText_F701Players[] = _("{DYNAMIC 1} giocatori");
const u8 gText_F702Players[] = _("{DYNAMIC 2} giocatori");
const u8 gText_F703Players[] = _("{DYNAMIC 3} giocatori");

const u8 *const gTextTable_Players[] = {
    gText_F700Players,
    gText_F701Players,
    gText_F702Players,
    gText_F703Players
};

ALIGNED(4) const u8 gText_WonderCards[] = _("CARTE MAGICHE");
ALIGNED(4) const u8 gText_WonderNews[] = _("NOTIZIE MAGICHE");
ALIGNED(4) const u8 gText_WirelessCommunication[] = _("COMUNICAZIONE WIRELESS");
ALIGNED(4) const u8 gText_Friend2[] = _("AMICO");
ALIGNED(4) const u8 gText_Exit3[] = _("ESCI");
ALIGNED(4) const u8 gText_Receive[] = _("RICEVI");
ALIGNED(4) const u8 gText_Send[] = _("INVIA");
ALIGNED(4) const u8 gText_Toss[] = _("GETTA");
ALIGNED(4) const u8 gText_VarietyOfEventsImportedWireless[] = _("Vari eventi verranno importati\nvia comunicazione wireless.");
ALIGNED(4) const u8 gText_WonderCardsInPossession[] = _("Leggi le WONDER CARD in tuo\npossesso.");
ALIGNED(4) const u8 gText_ReadNewsThatArrived[] = _("Leggi le NEWS arrivate.");
ALIGNED(4) const u8 gText_ReturnToTitle[] = _("Torna al menu iniziale.");
ALIGNED(4) const u8 gText_DontHaveCardNewOneInput[] = _("Non hai una WONDER CARD,\nquindi ne verrà inserita una.");
ALIGNED(4) const u8 gText_DontHaveNewsNewOneInput[] = _("Non hai WONDER NEWS,\nquindi ne verranno inserite.");
ALIGNED(4) const u8 gText_WhereShouldCardBeAccessed[] = _("Dove vuoi accedere alla\nWONDER CARD?");
ALIGNED(4) const u8 gText_WhereShouldNewsBeAccessed[] = _("Dove vuoi accedere alle\nWONDER NEWS?");
ALIGNED(4) const u8 gText_CommunicationStandbyBButtonCancel[] = _("In attesa di comunicazione…\nPulsante B: Annulla"); // Unused
ALIGNED(4) const u8 gText_Communicating[] = _("Comunicazione…");
ALIGNED(4) const u8 gText_CommunicationCompleted[] = _("Comunicazione completata.");
ALIGNED(4) const u8 gText_CommunicationError[] = _("Errore di comunicazione.");
ALIGNED(4) const u8 gText_CommunicationCanceled[] = _("La comunicazione è stata annullata.");
ALIGNED(4) const u8 gText_ThrowAwayWonderCard[] = _("Buttare la WONDER CARD\ne inserirne una nuova?");
ALIGNED(4) const u8 gText_HaventReceivedCardsGift[] = _("Non hai ancora ricevuto il dono della\nCARD. Inserire una nuova CARD?");
ALIGNED(4) const u8 gText_WonderCardReceivedFrom[] = _("Hai ricevuto una WONDER CARD\nda {STR_VAR_1}.");
ALIGNED(4) const u8 gText_WonderNewsReceivedFrom[] = _("Hai ricevuto una WONDER NEWS\nda {STR_VAR_1}.");
ALIGNED(4) const u8 gText_WonderCardReceived[] = _("Hai ricevuto una nuova\nWONDER CARD.");
ALIGNED(4) const u8 gText_WonderNewsReceived[] = _("Hai ricevuto una nuova\nWONDER NEWS.");
ALIGNED(4) const u8 gText_NewStampReceived[] = _("Hai ricevuto un nuovo STAMP.");
ALIGNED(4) const u8 gText_NewTrainerReceived[] = _("È arrivato un nuovo ALLENATORE.");
ALIGNED(4) const u8 gText_AlreadyHadCard[] = _("Avevi già quella\nWONDER CARD.");
ALIGNED(4) const u8 gText_AlreadyHadNews[] = _("Avevi già quella\nWONDER NEWS.");
ALIGNED(4) const u8 gText_AlreadyHadStamp[] = _("Avevi già quello\nSTAMP.");
ALIGNED(4) const u8 gText_NoMoreRoomForStamps[] = _("Non c'è più spazio per altri\nSTAMP.");
ALIGNED(4) const u8 gText_RecordUploadedViaWireless[] = _("Il tuo record è stato inviato via\nCOMUNICAZIONE WIRELESS.");
ALIGNED(4) const u8 gText_CantAcceptCardFromTrainer[] = _("Non puoi accettare una WONDER CARD\nda questo ALLENATORE.");
ALIGNED(4) const u8 gText_CantAcceptNewsFromTrainer[] = _("Non puoi accettare le WONDER NEWS\nda questo ALLENATORE.");
ALIGNED(4) const u8 gText_NothingSentOver[] = _("Non è stato inviato nulla…");
ALIGNED(4) const u8 gText_WhatToDoWithCards[] = _("Cosa vuoi fare\ncon le WONDER CARD?");
ALIGNED(4) const u8 gText_WhatToDoWithNews[] = _("Cosa vuoi fare\ncon le WONDER NEWS?");
ALIGNED(4) const u8 gText_SendingWonderCard[] = _("Invio della tua WONDER CARD…");
ALIGNED(4) const u8 gText_SendingWonderNews[] = _("Invio della tua WONDER NEWS…");
ALIGNED(4) const u8 gText_WonderCardSentTo[] = _("La tua WONDER CARD è stata inviata\na {STR_VAR_1}.");
ALIGNED(4) const u8 gText_WonderNewsSentTo[] = _("La tua WONDER NEWS è stata\ninviata a {STR_VAR_1}.");
ALIGNED(4) const u8 gText_StampSentTo[] = _("Uno STAMP è stato inviato a {STR_VAR_1}.");
ALIGNED(4) const u8 gText_GiftSentTo[] = _("Un REGALO è stato inviato a {STR_VAR_1}.");
ALIGNED(4) const u8 gText_OtherTrainerHasCard[] = _("L'altro ALLENATORE ha già la stessa\nWONDER CARD.");
ALIGNED(4) const u8 gText_OtherTrainerHasNews[] = _("L'altro ALLENATORE ha già le stesse\nWONDER NEWS.");
ALIGNED(4) const u8 gText_OtherTrainerHasStamp[] = _("L'altro ALLENATORE ha già lo stesso\nSTAMP.");
ALIGNED(4) const u8 gText_OtherTrainerCanceled[] = _("L'altro ALLENATORE ha annullato\nla comunicazione.");
ALIGNED(4) const u8 gText_CantSendGiftToTrainer[] = _("Non puoi inviare un MYSTERY GIFT a\nquesto ALLENATORE.");
ALIGNED(4) const u8 gText_IfThrowAwayCardEventWontHappen[] = _("Se butti via la CARD,\nil suo evento non avverrà. Va bene?");
ALIGNED(4) const u8 gText_OkayToDiscardNews[] = _("Vuoi davvero scartare questa\nNEWS?");
ALIGNED(4) const u8 gText_HaventReceivedGiftOkayToDiscard[] = _("Non hai ricevuto il\nREGALO. Vuoi scartarlo?");
ALIGNED(4) const u8 gText_DataWillBeSaved[] = _("I dati verranno salvati.\nAttendi.");
ALIGNED(4) const u8 gText_SaveCompletedPressA[] = _("Salvataggio completato.\nPremi il pulsante A.");
ALIGNED(4) const u8 gText_WonderCardThrownAway[] = _("La WONDER CARD è stata buttata via.");
ALIGNED(4) const u8 gText_WonderNewsThrownAway[] = _("Le WONDER NEWS sono state buttate via.");
ALIGNED(4) const u8 gText_MysteryGift[] = _("DONO SEGRETO");
ALIGNED(4) const u8 gText_PickOKExit[] = _("{DPAD_UPDOWN}SCEGLI {A_BUTTON}OK {B_BUTTON}ESCI");
ALIGNED(4) const u8 gText_PickOKCancel[] = _("{DPAD_UPDOWN}SCEGLI {A_BUTTON}OK {B_BUTTON}ANNULLA");
const u8 gText_PlayersBattleResults[] = _("RISULTATI LOTTA di {PLAYER}");
const u8 gText_TotalRecordWLD[] = _("RECORD TOTALE V:{STR_VAR_1} S:{STR_VAR_2} P:{STR_VAR_3}");
const u8 gText_WinLoseDraw[] = _("{CLEAR_TO 0x53}VITTORIE{CLEAR_TO 0x80}SCONFITTE{CLEAR_TO 0xB0}PARI");
const u8 gText_CommunicationStandby5[] = _("In attesa di comunicazione…");
const u8 gDaycareText_GetAlongVeryWell[] = _("I due sembrano andare\nmolto d'accordo.");
const u8 gDaycareText_GetAlong[] = _("I due sembrano andare d'accordo.");
const u8 gDaycareText_DontLikeOther[] = _("I due non sembrano\npiacersi molto.");
const u8 gDaycareText_PlayOther[] = _("I due preferiscono giocare con altri\nPOKéMON che tra loro.");
const u8 gText_NewLine2[] = _("\n");
const u8 gText_Exit4[] = _("ESCI");
const u8 gText_Lv[] = _("{LV}");
const u8 gText_TimeBoard[] = _("CRONOMETRO");
const u8 gText_TimeCleared[] = _("TEMPO FINALE");
const u8 gText_XMinYDotZSec[] = _("{STR_VAR_1} min. {STR_VAR_2}.{STR_VAR_3} sec.");
const u8 gText_TrainerHill1F[] = _("1F");
const u8 gText_TrainerHill2F[] = _("2F");
const u8 gText_TrainerHill3F[] = _("3F");
const u8 gText_TrainerHill4F[] = _("4F");
const u8 gText_TeachWhichMoveToPkmn[] = _("Insegnare quale {STR_VAR_3} a\n{STR_VAR_1}?");
const u8 gText_MoveRelearnerTeachMoveConfirm[] = _("Insegnare {STR_VAR_2}?");
const u8 gText_MoveRelearnerPkmnLearnedMove[] = _("{STR_VAR_1} ha imparato\n{STR_VAR_2}!");
const u8 gText_MoveRelearnerPkmnTryingToLearnMove[] = _("{STR_VAR_1} sta cercando di imparare\n{STR_VAR_2}.\pMa {STR_VAR_1} non può imparare\npiù di quattro mosse.\pVuoi cancellare una mossa\nper fare spazio a {STR_VAR_2}?");
const u8 gText_MoveRelearnerStopTryingToTeachMove[] = _("Vuoi smettere di insegnare\n{STR_VAR_2}?");
const u8 gText_MoveRelearnerAndPoof[] = _("{PAUSE 32}1, {PAUSE 15}2 e {PAUSE 15}… {PAUSE 15}… {PAUSE 15}… {PAUSE 15}{PLAY_SE SE_BALL_BOUNCE_1}Puff!\p");
const u8 gText_MoveRelearnerPkmnForgotMoveAndLearnedNew[] = _("{STR_VAR_1} ha dimenticato {STR_VAR_3}.\pE…\p{STR_VAR_1} ha imparato {STR_VAR_2}.");
const u8 gText_MoveRelearnedPkmnDidNotLearnMove[] = _("{STR_VAR_1} non ha imparato\nla mossa {STR_VAR_2}."); // Unused
const u8 gText_MoveRelearnerGiveUp[] = _("Vuoi rinunciare a insegnare una\nnuova mossa a {STR_VAR_1}?");
const u8 gText_MoveRelearnerWhichMoveToForget[] = _("Quale mossa vuoi\ndimenticare?\p");
const u8 gText_MoveRelearnerBattleMoves[] = _("MOSSE LOTTA");
const u8 gText_MoveRelearnerContestMovesTitle[] = _("MOSSE GARA");
const u8 gText_MoveRelearnerType[] = _("TIPO/"); // Unused
const u8 gText_MoveRelearnerPP[] = _("PP/");
const u8 gText_MoveRelearnerPower[] = _("POTENZA/");
const u8 gText_MoveRelearnerAccuracy[] = _("PRECISIONE/");
const u8 gText_MoveRelearnerAppeal[] = _("APPELLO");
const u8 gText_MoveRelearnerJam[] = _("BOSCO");
const u8 gText_ClearAllSaveData[] = _("Cancellare tutti i dati di salvataggio?");
const u8 gText_ClearingData[] = _("Cancellazione…\nAttendere.");
const u8 gText_IsThisTheCorrectTime[] = _("L'ora è corretta?");
const u8 gText_Confirm3[] = _("CONFERMA");
const u8 gText_Cancel4[] = _("ANNULLA");
const u8 gText_CommStandbyAwaitingOtherPlayer[] = _("In attesa di comunicazione…\nAttendo che un altro giocatore scelga.");
const u8 gText_BattleWasRefused[] = _("La lotta è stata rifiutata.{PAUSE 60}");
const u8 gText_RefusedBattle[] = _("Hai rifiutato la lotta.{PAUSE 60}");
const u8 gText_NoWeather[] = _("NESSUN METEO"); // Below are unused debug names for weather types
const u8 gText_Sunny[] = _("SOLARE"); // Unused
const u8 gText_Sunny2[] = _("SOLE2"); // Unused
const u8 gText_Rain[] = _("PIOGGIA"); // Unused
const u8 gText_Snow[] = _("NEVE"); // Unused
const u8 gText_Lightning[] = _("LUMINOSO"); // Unused
const u8 gText_Fog[] = _("NEBBIA"); // Unused
const u8 gText_VolcanoAsh[] = _("CENERE VULCANO"); // Unused
const u8 gText_Sandstorm[] = _("TERREMPESTA"); // Unused
const u8 gText_Fog2[] = _("NEBBIA2"); // Unused
const u8 gText_Seafloor[] = _("FONDALE"); // Unused
const u8 gText_Cloudy[] = _("NUVOLOSO"); // Unused
const u8 gText_Sunny3[] = _("SOLE3"); // Unused
const u8 gText_HeavyRain[] = _("PIOGGIA FORTE"); // Unused
const u8 gText_Seafloor2[] = _("FONDALE2"); // Unused
const u8 gText_DelAll[] = _("CANC.TUTTO");
const u8 gText_Cancel5[] = _("ANNULLA");
const u8 gText_Ok2[] = _("OK");
const u8 gText_Quiz[] = _("QUIZ");
const u8 gText_Answer[] = _("RISPOSTA");
const u8 gText_PokeBalls[] = _("POKé BALL");
const u8 gText_Berry[] = _("BACCA");
const u8 gText_Berries[] = _("BACCHE");
const u8 gText_Obtained999RareCandies[] = _("Hai ottenuto 999\nCARAMELLI RARI!{PAUSE_UNTIL_PRESS}");
const u8 gText_ExpShareOn[] = _("Il Condivis. Esp. è stato attivato.{PAUSE_UNTIL_PRESS}");
const u8 gText_ExpShareOff[] = _("Il Condivis. Esp. è stato disattivato.{PAUSE_UNTIL_PRESS}");
ALIGNED(4) const u8 gText_Ghost[] = _("SPETTRO");
const u8 gText_Boulderbadge[] = _("MEDAGLIA SASSO");
const u8 gText_Cascadebadge[] = _("MEDAGLIA CASCATA");
const u8 gText_Thunderbadge[] = _("MEDAGLIA TUONO");
const u8 gText_Rainbowbadge[] = _("MEDAGLIA ARCOBALENO");
const u8 gText_Soulbadge[] = _("MEDAGLIA ANIMA");
const u8 gText_Marshbadge[] = _("MEDAGLIA PALUDE");
const u8 gText_Volcanobadge[] = _("MEDAGLIA VULCANO");
const u8 gText_Earthbadge[] = _("MEDAGLIA TERRA");
const u8 gText_OakImportantToGetToKnowPokemonThroughly[] = _("OAK: È importante conoscere\nbene i tuoi POKéMON.\p");
const u8 gText_OakThisIsListOfPokemon[] = _("Questa è la lista dei tuoi POKéMON,\n{PLAYER}.\pAprila per vedere le statistiche\ne le mosse dei tuoi POKéMON.\pScegli qui i POKéMON anche se\nvuoi usare uno strumento su uno.{PAUSE_UNTIL_PRESS}");

const u8 gText_GBPlayerOn[] = _("Il GB Player è stato acceso.\nSuoni del passato riempiono l'aria.{PAUSE_UNTIL_PRESS}");
const u8 gText_GBPlayerOff[] = _("Il GB Player è stato spento.\nI suoni della nostalgia svaniscono.{PAUSE_UNTIL_PRESS}");

const u8 gText_Sunday[] = _("DOMENICA");
const u8 gText_Monday[] = _("LUNEDì");
const u8 gText_Tuesday[] = _("MARTEDì");
const u8 gText_Wednesday[] = _("MERCOLEDÌ");
const u8 gText_Thursday[] = _("GIOVEDÌ");
const u8 gText_Friday[] = _("VENERDì");
const u8 gText_Saturday[] = _("SABATO");
const u8 gText_LoveBall[] =     _("LOVE    / PECHA  / (FRD/PSI)");
const u8 gText_Lure[] =         _("LURE    / RAWST  / (ACQ/DRG)");
const u8 gText_FriendBall[] =   _("FRIEND / CHERI  / (COL/ERB)");
const u8 gText_Heavy[] =        _("HEAVY   / ORAN   / (ROC/TER/ACC)");
const u8 gText_Moon[] =         _("MOON    / CHESTO / (BUI/SPE/VEL)");
const u8 gText_Fast[] =         _("FAST    / ASPEAR / (ELE/LOT/FUO)");
const u8 gText_LevelBall[] =    _("LEVEL  / PERSIM / (NOR/VOL/GHI)");
const u8 gText_Vermilion[] = _("VERMILION");
const u8 gText_Olivine[] = _("OLIVINE");
const u8 gText_Floor0[] = _("Piano 0");
const u8 gText_Pal[] = _("Pal");
const u8 gText_Underling[] = _("Sgherro");
const u8 gText_Strategy[] = _("Strategia");
const u8 gText_Training[] = _("Allenamento");
const u8 gText_Cheating[] = _("Imbroglio");
const u8 gText_WeakPerson[] = _("Debole");
const u8 gText_ToughPerson[] = _("Tipo tosto");
const u8 gText_Anybody[] = _("Nessuno");
const u8 gText_Love2[] = _("Amore");
const u8 gText_Violence[] = _("Violenza");
const u8 gText_Knowledge[] = _("Sapienza");
const u8 gText_Tough3[] = _("Tosto");
const u8 gText_Weak[] = _("Debole");
const u8 gText_Both[] = _("Entrambi");
const u8 gText_GreenStone[] = _("PIETRA VERDE");
const u8 gText_RedStone[] = _("PIETRA ROSSA");
const u8 gText_BlueStone[] = _("PIETRA BLU");
