VermilionCity_House2_hns_MapScripts::
	.byte 0

VermilionCity_House2_EventScript_PokefanF::
	msgbox VermilionCity_House2_Text_PokefanF, MSGBOX_NPC
	end

VermilionCity_House2_EventScript_Youngster::
	msgbox VermilionCity_House2_Text_Youngster, MSGBOX_NPC
	end

VermilionCity_House2_Text_PokefanF:
	.string "Conosci il TRENO\n"
	.string "MAGNETICO?\p"
	.string "È una ferrovia che va a\n"
	.string "FIORINVETRO, a JOHTO.$"

VermilionCity_House2_Text_Youngster:
	.string "Voglio andare a ZAFFERANOPOLI a\n"
	.string "vedere il TRENO MAGNETICO.$"
