FiveIsland_House1_Frlg_MapScripts::
	.byte 0

FiveIsland_House1_EventScript_Woman::
	msgbox FiveIsland_House1_Text_HusbandWentOffFishing, MSGBOX_NPC
	end

FiveIsland_House1_Text_HusbandWentOffFishing::
	.string "Non preoccuparti di comprare\n"
	.string "per cena stasera!\p"
	.string "…Così ha detto mio marito\n"
	.string "andando a pescare oggi.\p"
	.string "Non so se posso fidarmi\n"
	.string "che mantenga la promessa.$"

