SSAqua_RoomNW_hns_MapScripts::
    map_script MAP_SCRIPT_ON_TRANSITION, SSAqua_RoomNW_OnTransition
	.byte 0

SSAqua_RoomNW_OnTransition::
    goto_if_ge VAR_SSAQUA_STATE, 3, SSAqua_RoomNW_SetTrainerPos
    end

SSAqua_RoomNW_SetTrainerPos::
    setobjectxyperm 2, 2, 6
    setobjectxyperm 3, 4, 3
    end

SSAqua_RoomNW_EventScript_Stanly::
    lock
    faceplayer
    msgbox SSAqua_RoomNW_Text_SailorStanlySeen, MSGBOX_DEFAULT
    trainerbattle_no_intro TRAINER_STANLY_HNS, SSAqua_RoomNW_Text_SailorStanlyBeaten
	msgbox SSAqua_RoomNW_Text_SailorStanlyAfterBattle, MSGBOX_DEFAULT
    closemessage
    fadescreenswapbuffers FADE_TO_BLACK
    delay 60
    playse SE_DOOR
    removeobject LOCALID_SSAQUA_SLEEPYSAILOR
    fadescreenswapbuffers FADE_FROM_BLACK
    setvar VAR_SSAQUA_STATE, 3
	end

SSAqua_RoomNW_EventScript_Edward::
    trainerbattle_single TRAINER_EDWARD_HNS, SSAqua_RoomNW_Text_GentlemanEdwardSeen, SSAqua_RoomNW_Text_GentlemanEdwardBeaten
	msgbox SSAqua_RoomNW_Text_GentlemanEdwardAfterBattle, MSGBOX_AUTOCLOSE
	end

SSAqua_RoomNW_EventScript_Corey::
    trainerbattle_single TRAINER_COREY_HNS, SSAqua_RoomNW_Text_BurglarCoreySeen, SSAqua_RoomNW_Text_BurglarCoreyBeaten
	msgbox SSAqua_RoomNW_Text_BurglarCoreyAfterBattle, MSGBOX_AUTOCLOSE
	end


SSAqua_RoomNW_Text_SailorStanlySeen:
	.string "Sì, sono un marinaio, certo.\p"
	.string "Non stavo bighellonando!\p"
	.string "La cabina era vuota, quindi\n"
	.string "mi sono fatto un riposino!\p"
	.string "Ah, lasciamo perdere! Lottiamo!$"

SSAqua_RoomNW_Text_SailorStanlyBeaten:
	.string "Scusa! È tutta colpa mia!$"

SSAqua_RoomNW_Text_SailorStanlyAfterBattle:
	.string "Da marinaio devo fare\n"
	.string "lavori pesanti. È estenuante!$"

SSAqua_RoomNW_Text_GentlemanEdwardSeen:
	.string "Oh, no. Ho perso qualcosa\n"
	.string "di molto importante.$"

SSAqua_RoomNW_Text_GentlemanEdwardBeaten:
	.string "Io… non riesco a trovarlo…$"

SSAqua_RoomNW_Text_GentlemanEdwardAfterBattle:
	.string "Ci rinuncio. Non serve\n"
	.string "guardare.\p"
	.string "Dimentica tutto!$"

SSAqua_RoomNW_Text_BurglarCoreySeen:
	.string "Yeehaw! Che fortuna!$"

SSAqua_RoomNW_Text_BurglarCoreyBeaten:
	.string "Che sfortuna! Ho perso!$"

SSAqua_RoomNW_Text_BurglarCoreyAfterBattle:
	.string "Ho trovato una bella moneta qui.\p"
	.string "Qualcuno l'avrà persa…$"
