LilycoveCity_House4_MapScripts::
	.byte 0

LilycoveCity_House4_EventScript_Man1::
	msgbox LilycoveCity_House4_Text_MysteriesAtBottomOfSea, MSGBOX_NPC
	end

LilycoveCity_House4_EventScript_Man2::
	msgbox LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis, MSGBOX_NPC
	end

LilycoveCity_House4_Text_MysteriesAtBottomOfSea:
	.string "I più grandi misteri del pianeta sono\n"
	.string "in fondo al mare.\p"
	.string "Qualcuno l'ha detto, ma non so…$"

LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis:
	.string "C'è una fossa profonda\n"
	.string "tra MOSSDEEP e SOOTOPOLIS.\p"
	.string "Almeno, così mi hanno detto.$"

