OneIsland_KindleRoad_Frlg_MapScripts::
	.byte 0

OneIsland_KindleRoad_EventScript_RouteSign::
	msgbox OneIsland_KindleRoad_Text_RouteSign, MSGBOX_SIGN
	end

OneIsland_KindleRoad_EventScript_EmberSpaSign::
	msgbox OneIsland_KindleRoad_Text_EmberSpaSign, MSGBOX_SIGN
	end

OneIsland_KindleRoad_Text_MariaIntro::
	.string "Che bel tempo!\n"
	.string "Perfetto per una lotta!$"

OneIsland_KindleRoad_Text_MariaDefeat::
	.string "Ahiieeeeh!$"

OneIsland_KindleRoad_Text_MariaPostBattle::
	.string "Non schizzarmi la faccia!\n"
	.string "Mi rovini il trucco.$"

OneIsland_KindleRoad_Text_AbigailIntro::
	.string "Sto iniziando a scottarmi...$"

OneIsland_KindleRoad_Text_AbigailDefeat::
	.string "Oh, sei proprio terribile.$"

OneIsland_KindleRoad_Text_AbigailPostBattle::
	.string "Mi piace il tuo cappello.\n"
	.string "Forse dovrei metterlo anch'io…$"

OneIsland_KindleRoad_Text_FinnIntro::
	.string "Da qui, il MONTE BRACE si erge\n"
	.string "fino al cielo.$"

OneIsland_KindleRoad_Text_FinnDefeat::
	.string "Beh, sei forte, eh?$"

OneIsland_KindleRoad_Text_FinnPostBattle::
	.string "Il cielo è immenso da queste\n"
	.string "parti.$"

OneIsland_KindleRoad_Text_GarrettIntro::
	.string "Mi riposavo dal nuoto,\n"
	.string "e tu mi sfidi?$"

OneIsland_KindleRoad_Text_GarrettDefeat::
	.string "Ehi, ma che…\n"
	.string "Sei proprio forte!$"

OneIsland_KindleRoad_Text_GarrettPostBattle::
	.string "Invece di usare sempre SURF,\n"
	.string "nuota un po' anche tu.$"

OneIsland_KindleRoad_Text_TommyIntro::
	.string "Aspetta! Un attimo!\n"
	.string "Credo di aver preso un pesce grosso!$"

OneIsland_KindleRoad_Text_TommyDefeat::
	.string "Ho perso di nuovo tutto…$"

OneIsland_KindleRoad_Text_TommyPostBattle::
	.string "Non solo ho perso, ma mi è\n"
	.string "scappato anche il più grosso!$"

OneIsland_KindleRoad_Text_SharonIntro::
	.string "Mi aiuti con il mio\n"
	.string "allenamento?$"

OneIsland_KindleRoad_Text_SharonDefeat::
	.string "Sei stato di un livello superiore.$"

OneIsland_KindleRoad_Text_SharonPostBattle::
	.string "È chiaro che sei abile.\n"
	.string "Mi piaci!$"

OneIsland_KindleRoad_Text_TanyaIntro::
	.string "Non passa giorno senza che\n"
	.string "ci alleniamo!$"

OneIsland_KindleRoad_Text_TanyaDefeat::
	.string "Che sciocca che sono!$"

OneIsland_KindleRoad_Text_TanyaPostBattle::
	.string "D'ora in poi mi allenerò ancora di più!$"

OneIsland_KindleRoad_Text_SheaIntro::
	.string "Ogni mattina, prima di colazione,\n"
	.string "nuoto intorno a quest'isola.$"

OneIsland_KindleRoad_Text_SheaDefeat::
	.string "Anf…\n"
	.string "Anf…$"

OneIsland_KindleRoad_Text_SheaPostBattle::
	.string "Ho perso perché sono distrutto\n"
	.string "da tutta la corsa che ho fatto…$"

OneIsland_KindleRoad_Text_HughIntro::
	.string "Vestiti adeguato per la lotta!\n"
	.string "Togliti quel completo frivolo!$"

OneIsland_KindleRoad_Text_HughDefeat::
	.string "Perché io?!$"

OneIsland_KindleRoad_Text_HughPostBattle::
	.string "Persino gli artisti marziali sono\n"
	.string "attenti alla moda, oggigiorno…$"

OneIsland_KindleRoad_Text_BryceIntro::
	.string "Sai, tutto è più buono\n"
	.string "quando sei in mezzo alla natura.$"

OneIsland_KindleRoad_Text_BryceDefeat::
	.string "Nooo, che sconfitta!$"

OneIsland_KindleRoad_Text_BrycePostBattle::
	.string "L'acqua delle zone vulcaniche è\n"
	.string "deliziosa.$"

OneIsland_KindleRoad_Text_ClaireIntro::
	.string "Il pranzo ci ha riempiti: ci batti\n"
	.string "per un po' di esercizio?$"

OneIsland_KindleRoad_Text_ClaireDefeat::
	.string "Mi hai fatto sudare tutta.$"

OneIsland_KindleRoad_Text_ClairePostBattle::
	.string "Che faccio?\n"
	.string "Ho di nuovo fame.$"

OneIsland_KindleRoad_Text_KiaIntro::
	.string "KIA: Io e mio fratello siamo\n"
	.string "una coppia fantastica!$"

OneIsland_KindleRoad_Text_KiaDefeat::
	.string "KIA: Eh?!\n"
	.string "Non ci credo!$"

OneIsland_KindleRoad_Text_KiaPostBattle::
	.string "KIA: Come può esistere uno\n"
	.string "più forte di mio fratello?$"

OneIsland_KindleRoad_Text_KiaNotEnoughMons::
	.string "KIA: Se vuoi lottare con noi,\n"
	.string "devi portare almeno due\l"
	.string "POKéMON con te.$"

OneIsland_KindleRoad_Text_MikIntro::
	.string "MIK: Insieme a KIA non temo\n"
	.string "nulla!$"

OneIsland_KindleRoad_Text_MikDefeat::
	.string "MIK: Uao!\n"
	.string "Troppo forte!$"

OneIsland_KindleRoad_Text_MikPostBattle::
	.string "MIK: Come ha potuto fallire\n"
	.string "la mia coppia con KIA?$"

OneIsland_KindleRoad_Text_MikNotEnoughMons::
	.string "MIK: Ehi, vuoi lottare\n"
	.string "con noi due?\p"
	.string "Allora porta almeno due\n"
	.string "POKéMON con te.$"

OneIsland_KindleRoad_Text_RouteSign::
	.string "Questa è la VIA VULCANICA.\p"
	.string "Prosegui dritto per il MONTE BRACE.$"

OneIsland_KindleRoad_Text_EmberSpaSign::
	.string "Accendi il Fuoco nel Cuore!\n"
	.string "VIA VULCANICA$"

